### ISSUE TITLE
Antlr left recursion rule should call after terminal symbol on the left

### ISSUE THREAD

**Issue by ZeroxLim** [antlr/antlr4#1004]
I tried to make a simple arithmetic operation with precedence. Such as 2 + 3 *  4 

this generated the subtree like below, which is correct( Ignore the number behind expr, use to tag them )

                     expr(1)
             /        |         \
        expr(2)       +(3)     expr(4)
           |                /     |     \
      literal            expr(5)  *      expr
           |               |               |
          2           literal          literal
                           |               |
                           3               4

Problem lies on the generate parser will have the following visit order( using listener, generated in  javascript )
exit2 -> enter4 -> visit 3 -> enter(5)

I writing a simple stack to convert the tree to a json notation, each of them is just a object with children.
But due to this, it mess up the stack because the visit order is totally wrong.

Hope for a swift reply on this. (grammar below)

    grammar ExprTest;
    
    parse:
    expression;
    
    expression
        : expression ( '*' | '/' ) expression
        | expression ( '+' | '-' ) expression
        | literal;

    literal
        : RealLiteral
        | NumberLiteral;
    
    RealLiteral
        : NumberLiteral '.' Digit*;

    NumberLiteral
        : '0'
        | NonZeroDigit Digit* ;

    Non_Digit
        : [a-zA-Z_] ;

    Digit
        : '0'
        | NonZeroDigit ;

    NonZeroDigit
        : [1-9] ;

    WS  :  [ \t\r\n\u000C]+ -> skip ;

    COMMENT
        :   '/*' .*? '*/' -> skip ;

    LINE_COMMENT
        :   '//' ~[\r\n]* -> skip ;

**Comment by sharwell** [comment]
Are you registering your listener via `addParseListener`, or are you using `ParseTreeWalker` after the parse is complete?

The reason I ask is these two methods are very different. The documentation for `addParseListener` [describes in detail](https://github.com/antlr/antlr4/blob/1e6b4efb5f0eeb2a0b9ff116bbd4e1891f72de17/runtime/JavaScript/src/antlr4/Parser.js#L190-L197) how entry and exit events are allowed to be reordered and in some cases even omitted altogether. `ParseTreeWalker` on the other hand should always walk the tree in the some order nodes appear in the tree.

**Comment by ZeroxLim** [comment]
I using the addParseListener.

**Comment by sharwell** [comment]
`addParseListener` is a feature for expert users who need to plan on using it to solve very specific situations. You'll want to use `ParseTreeWalker` instead.

**Comment by ZeroxLim** [comment]
End up I write my own traverser, thanks anyway. Closing the issue
