### ISSUE TITLE
Begin Of File (BOF) token

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#1016]
Consider the following grammar:

```ANTLR
grammar expr;
begin: expr EOF;
expr: ID
    | expr 'and' expr
    ;
ID: [a-zA-Z_][a-zA-Z_0-9]*;
WS: [ \t\n\r\f]+ -> skip;
ERROR: .;
```

I want to match entire input file with ```begin``` rule. For example, file with such content:
```X1 X2 and X3```

But got the following string tree. Parser processed file without errors.
```(begin (expr (expr X2) and (expr X3)) <EOF>)```

If I remove ```EOF``` token from grammar, I got the following string tree also without parser errors:
```(begin (expr X1))```

But I want to parse entire file with or without errors. So I suggest to introduce new BOF token in order to rewrite ```begin``` rule by such way:

```begin: BOF expr EOF;```

**Comment by sharwell** [comment]
The parser always starts at the beginning. If it can't match from the beginning, an error is reported.

Can you post the Java code to reproduce your example? If it really isn't reporting an error, then that would be a bug.

**Comment by KvanTTT** [comment]
Sorry, this is my fault. I configured lexer and parser not properly.
