### ISSUE TITLE
more lexer command starts new token

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#1017]
Consider the following grammar:

```ANTLR
grammar text;

text: (Text Or?)* EOF;

Text:  ~('|')+;
Or:    '|' '|';
More:  '|'       -> more;
```

I am trying to parse the following text: ```abc|abc||abc|``` and getting tokens stream:
```Text (abc) Text (|abc) Or (||) Text (abc) EOF```

But I expect text parts merged.

It it a bug or feature? If it is not a bug, how can I rewrite this grammar to reach expected behaviour?

**Comment by sharwell** [comment]
`-> more` affects the behavior of the *next* token, not the previous token. You can see this reflected in the second token produced by your example.

**Comment by KvanTTT** [comment]
@sharwell thanks for clarify!
I rewrite the grammar by the following way:

```ANTLR
grammar expr;
text: (Text Or?)* EOF;
Text:  ('|' ~'|' | ~'|')+;
Or:     '|' '|';
```

But another question appeared. For the same input ```abc|abc||abc|``` I get the lexer error:
```token recognition error at: '|' at 0:12```. If I rewrite Text rule by such way:
```ANTLR
Text:  ('|' ~'|' | '|' EOF | ~'|')+;
``` 
and this error dissapear. So, EOF token is not treated as ~'|'. Is this right?

Another way to rewrite ```Text``` rule is
```ANTLR
Text:  ('|' ~'|' | ~'|')+ | (~'|')* '|';
```

But such syntax quite cumbersome. So, lexer command for merging current lexem and *previous* token would be useful.
