### ISSUE TITLE
[csharp] Problem with simple grammar

### ISSUE THREAD

**Issue by MichaelLogutov** [antlr/antlr4#1021]
I have this simple grammatic:

    parse: '{' valueList '}';

    valueList: value (',' value)*;
    value: QUOTED_STRING;

    STRING: [a-zA-Z0-9 -_]+;
    QUOTED_STRING: '"' STRING '"';
    WS: [ \t]+ -> skip;

When passed string:

    {"a"}

It outputs:

    line 1:1 mismatched input '"a"' expecting QUOTED_STRING

Why is that?

I'm using antlr-4.5.1-complete.jar and Antlr4.Runtime, Version=4.5.1.0, Culture=neutral, PublicKeyToken=e78b2c5abd1fcb3f

**Comment by KvanTTT** [comment]
Use "fragment" modifier for your STRING rule or simply use
```
QUOTED_STRING: '"' [a-zA-Z0-9 -_]+ '"';
```
Now your test sample matched as STRING instead of QUOTED_STRING.

**Comment by MichaelLogutov** [comment]
Strange... It works. Can you please explain why?

**Comment by KvanTTT** [comment]
You did not escape '-' char inside STRING rule and ANTLR recognize it as range from ' ' to '_'. Quote is in this range. So, my first answer is not correct and you should use the following rule:
```
STRING: [a-zA-Z0-9 \-_]+;
```

**Comment by MichaelLogutov** [comment]
Hm...
Actually, I think I need that STRING token. You see, I need to parse text string like this:

    abc {"a", "b"}

So my actuall grammar looks like this:

    parse: (
             text
             | '{' valueList '}'
           )+;

    text: STRING;

    valueList: value (',' value)*;
    value: QUOTED_STRING;

    fragment CHAR: [a-zA-Zа-яёА-ЯЁ0-9 -_];
    STRING: CHAR+;
    QUOTED_STRING: '"' CHAR+ '"';
    WS: [ \t]+ -> skip;

And when I pass this string:

    abc {"a"}

I've got:

    line 1:5 mismatched input '"a"' expecting QUOTED_STRING

**Comment by ericvergnaud** [comment]
Have you tried declaring quoted string before string?

**Comment by MichaelLogutov** [comment]
Now spaces are not skipped:

    parse: (
             text
             | '{' valueList '}'
           )+;

    text: STRING;

    valueList: value (',' value)*;
    value: '"' id '"';

    id: STRING;

    STRING: [a-zA-Z0-9 \-_]+;
    WS: [ \t]+ -> skip;

For

    { "a"}

I've got 

    line 1:1 extraneous input ' ' expecting '"'

**Comment by ericvergnaud** [comment]
Hi,
your STRING pattern accepts spaces, so your input reads '{' STRING value,  not '{' WS STRING

**Comment by MichaelLogutov** [comment]
Curious... But I need that spaces to be allowed inside quotes and in plain text, so I can parse string like this:

    abc { "a", "b" }

into:
* [abc ]
* [a], [b]

**Comment by ericvergnaud** [comment]
then you’ll have to use a more complex definition of STRING, see the grammars on the web site

**Comment by KvanTTT** [comment]
@MichaelLogutov , you should not-greedy rule for strings like this ```'"' .*? '"'``` or use modes. Please, read an official [doc](https://theantlrguy.atlassian.net/wiki/display/ANTLR4/ANTLR+4+Documentation) and learn by [samples](https://github.com/antlr/grammars-v4) at first.

**Comment by MichaelLogutov** [comment]
Ok, thanks everyone. Will do. I'll close the issue and comment the completed solution later.

**Comment by MichaelLogutov** [comment]
I went with this grammar (because I did not need to save excact spaces in text):

    TEXT: [a-zA-Z0-9\-_]+;
    STRING: '"' ~["]+ '"';
    WS: [ \t]+ -> skip;

    parse: (
             text
             | valueList
           )+;

    text: TEXT;

    valueList: '{' value (',' value)* '}';
    value: STRING;
