### ISSUE TITLE
JavaScript: getExpectedTokens() behaves incorrectly on consecutive parser runs

### ISSUE THREAD

**Issue by martin-probst** [antlr/antlr4#1023]
I'm using an antlr4 generated JavaScript parser for code completion purposes with a custom language and noticed a strange behaviour resulting in out-of-context suggestions of the code completer.
For debugging purposes and to being able to reproduce this issue, I simplified my grammar to the following:

*TestLexer.g4*
```
lexer grammar TestLexer;

KEY_ENT : 'entity';
KEY_MEMB : 'members';
KEY_FOO : 'foo';
KEY_BAR : 'bar';
KEY_A : 'a';
KEY_B : 'b';
KEY_C : 'c';
CBO : '{';
CBC : '}';
ID : [A-Z][a-z]*;
COLON : ':';
SEMICOLON : ';';
STR : '"' (~'"')* '"';
WS  :  [ \t\r\n]+ -> skip;
ERROR_TOKEN : .;
```

*TestParser.g4*
```
parser grammar TestParser;
options {tokenVocab=TestLexer;}

root : entity+;
entity : KEY_ENT ID CBO entityContent CBC;
entityContent : members;
members : KEY_MEMB CBO member* CBC;
member : (KEY_A | KEY_B) COLON STR SEMICOLON;
```

The generated antlr4 JavaScript parser is run similarly to the basic JavaScript usage example. Consider the following code to reproduce my problem:
```javascript
var antlr4 = require('antlr4/index.js');
var TestLexer = require('./TestLexer.js');
var TestParser = require('./TestParser.js');

var ErrorListener = function(errors) {
  antlr4.error.ErrorListener.call(this);
  this.errors = errors;
  return this;
};

ErrorListener.prototype = Object.create(antlr4.error.ErrorListener.prototype);
ErrorListener.prototype.constructor = ErrorListener;
ErrorListener.prototype.syntaxError = function(rec, sym, line, col, msg, e) {
  this.errors.push(msg);
};

var input = 'entity Foo { members { a : "foo bar"; b : "foo"; X } }';

var errors = [];

// first parser run 
var chars = new antlr4.InputStream(input);
var lexer = new TestLexer.TestLexer(chars);
var tokens  = new antlr4.CommonTokenStream(lexer);

var parser = new TestParser.TestParser(tokens);
parser.buildParseTrees = true;
var listener = new ErrorListener(errors);

parser.removeErrorListeners();
parser.addErrorListener(listener);
parser.root();
console.log(errors); // --> extraneous input 'X' expecting {'a', 'b', '}'}'

// to this point everthing is like expected
// now we simulate a second run with newly instantiated objects on the very same input

errors = [];
chars = new antlr4.InputStream(input);
lexer = new TestLexer.TestLexer(chars);
tokens  = new antlr4.CommonTokenStream(lexer);

parser = new TestParser.TestParser(tokens);
parser.buildParseTrees = true;
listener = new ErrorListener(errors);

parser.removeErrorListeners();
parser.addErrorListener(listener);
parser.root();
console.log(errors); // --> extraneous input 'X' expecting {'entity', 'a', 'b', '}'}' 

// now 'entity' pops up within the expected tokens, which is not a valid expectation
// in the current context of the erroneous token 'X'
```
Looks like a bug to me. Even if all the objects are newly instantiated like above, some state seems to remain and leads to the faulty behaviour, for the output is always correct on the first run.

Thanks in advance for helping me with this issue. In the context of my actual, quite complex grammar, I get lots of faulty tokens from the root context, which is quite annoying because my code completion shows incorrect suggestions.
Martin

**Comment by ericvergnaud** [comment]
Hi,
indeed the parser keeps data across runs. This is called a warmup and leads to better performance after several runs.
can you try inputting 'entity Foo { members { a : "foo bar"; b : "foo"; entity } }'; on a 3rd run to see if it shouts?
I would expect it to do so, and it will help narrow down the source of this unexpected behavior.
Also can you specify:
 - which version of antlr tool/runtime
 - which JavaScript engine
If not already the case, can you try with the latest source code (not the latest release)?
Also please attach the generated parser files + sample script to reproduce.
Eric

**Comment by martin-probst** [comment]
Hi Eric,

I checked my above test code with node v4.0.0 and node v0.10.35. But the behaviour is also observable in the current Chrome browser, which is my actual target for the auto completion.
Antlr4 version is 4.5.1. Unfortunately GitHub refuses to accept the javascript-files on upload. I created them from the grammars of my initial post with:
```
java -Xmx500M -cp "/usr/local/lib/antlr-4.5.1-complete.jar:$CLASSPATH" org.antlr.v4.Tool -Dlanguage=JavaScript TestLexer.g4 TestParser.g4
```
A third run with your suggested input snippet produces: 
`extraneous input 'entity' expecting '}'`

I still need to check with the latest antl4 source code like you suggested. Will be back with the results...

Cheers,
Martin

**Comment by ericvergnaud** [comment]
can you not zip them?

**Comment by martin-probst** [comment]
It tried, but GitHub tells me, only PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, or PDF are allowed.

So I tried to upload the files with an additional .txt suffix to get around this restriction. This results in the following error:
*Attaching documents requires write permission to this repository. Try again with a PNG, GIF, or JPG.*
:angry:

**Comment by martin-probst** [comment]
I checked out the current source, built the tool from sources and used the included runtime. So I can now confirm that this problem still persists with the current sources (last commit 8abc1106f704cc3f from Oct. 9).
The grammars and the code snippet from my first post are sufficient to reproduce the described problem with the tool and runtime from the current sources.

**Comment by martin-probst** [comment]
@ericvergnaud I think I found the bug in the JS-runtime's ATN.js. nextTokensNoContext added token intervals from error recovery to the actual state, changing it permanently in consecutive parser runs.
This does not seem to have happened intentionally and simply using a local variable fixed the problem.

**Comment by martin-probst** [comment]
I hope I now got to the core of the bug with my current pull request. Sorry about the previous one, where I missed the caching intention.
In general, one could consider to make use of "immutable" objects in some cases or return clones when using getters in places where it is not performance critical.
