### ISSUE TITLE
Incorrectly generated code for Python 3 target

### ISSUE THREAD

**Issue by jmflorezff** [antlr/antlr4#1037]
I found this issue while working with the example Java grammar. To replicate follow these steps:
 - Use Antlr v4.5.1
 - Download the grammar from [the repository] (https://github.com/antlr/grammars-v4/blob/master/java/Java.g4)
 - Generate code for Python 3 using the following command `antlr4 -Dlanguage=Python3 Java.g4` (It will give some errors about 'type' being a Python keyword but that's not the issue right now)
 - Open file `JavaLexer.py`
 - Around lines 708 and 717 you'll find something like this: `Character.toCodePoint((char)_input.LA(-2), (char)_input.LA(-1))`

That's the problem, castings in python are of the form `type(expression)` so when trying to run it, the interpreter will complain about invalid syntax.

That expression should actually be `Character.toCodePoint(chr(_input.LA(-2)), chr(_input.LA(-1)))`

**Comment by ericvergnaud** [comment]
Hi,

this is because the grammar contains Java code between curly brackets.
These never get translated.  
To use this grammar in Python, you first need to replace the Java code in curly brackets by the corresponding Python code.

Eric

**Comment by jmflorezff** [comment]
Ah, sorry. Those code snippets are easy to miss

**Comment by ericvergnaud** [comment]
Np. Please close this issue.
