### ISSUE TITLE
"Unary prefix" cases preferred ahead of "primary" cases in left-recursive rules

### ISSUE THREAD

**Issue by michaelpj** [antlr/antlr4#1048]
```
grammar repro;

expr : literal                      
     | op expr                    
     | left=expr op right=expr
     ;

literal : '-'? Integer;

op : '+' | '-' ;

Integer : [0-9]+ ;

WS  :  [ \t\r\n\u000C]+ -> channel(1) ;
```

```
echo "-1" | java -cp antlr-4.5.1-complete.jar:. org.antlr.v4.gui.TestRig repro expr -tree
(expr (op -) (expr (literal 1)))
```

That is, `-1` parses as a unary minus applied to a literal 1, rather than a literal -1, despite the fact that the latter rule is an earlier alternative.

Now, I know that ANTLR rewrites left-recursive rules to parse them sensibly. Examining the log, I can see the following rewrite of the rule:
```
2015-11-20 11:29:01:089 left-recursion LogManager.java:49 expr
    :   ( {} op<tokenIndex=13> expr<tokenIndex=15,p=2> 
        | literal<tokenIndex=9> 
        )
        (
          {precpred(_ctx, 1)}?<p=1> op<tokenIndex=23> right=expr<tokenIndex=27,p=2>
        )*
    ;
```
It looks like we put the recursive-but-not-left-recursive alternatives first, then the non-recursive (primary) alternatives, and then the left-recursive alternatives. This surprises me - I would have thought that we'd try the non-recursive alternatives first, but that doesn't appear to be the case.

Is this the intended behaviour?

**Comment by michaelpj** [comment]
To clarify my surprise a bit more: since this is an example of an ambiguity, I would have expected the order of alternatives to affect which version is chosen.

**Comment by parrt** [comment]
Hmm...yes, this seems very odd. Looking at your PR now too.
