### ISSUE TITLE
white space in antlr error messages

### ISSUE THREAD

**Issue by davidcok** [antlr/antlr4#1050]
I have a lexer/parser that works great and is set to ignore white space.
Consequently, I think, "no viable input at" error messages report a string of text with no white space separating the text rendering of the tokens found so far.
This is a hard to read error message and unfriendly to non-antlr-aware users.

What about separating the tokens in this and any similar messages with spaces?
One can of course make all custom error messages, but for those messages that are not, or are not yet, made custom, this fix would help. Or is there a better way to accomplish it?

**Comment by HSorensen** [comment]
The problem is with the getText() method.
If you compile ANTLR yourself you can look at this commit from my fork for a possible hack for Java:
[commit/21e681921](https://github.com/antlr/antlr4/commit/21e681921f6edc8ed0c0fa9e349bfa3e5fbb1b1e)

**Comment by sharwell** [comment]
@davidcok It sounds like you are using `-> skip` in your lexer rules. If you use `-> channel(HIDDEN)` instead, your hidden tokens will still not affect parsing but their text will appear in error messages.
