### ISSUE TITLE
Javascript visitor modify prototype methods

### ISSUE THREAD

**Issue by xaltotungreat** [antlr/antlr4#1058]
Hello Terence and the team. I'm so impressed with Antlr that I wanted to donate but PayPal is not available in my country (at least as far as I know it is very complicated to move some money to a PayPal account). I'm working with the javascript runtime and found the following error in tree\Tree.js:

ParseTreeListener.prototype.visitTerminal = function(node) {
};

ParseTreeListener.prototype.visitErrorNode = function(node) {
};

These 2 methods must belong to the prototype of ParseTreeVisitor not ParseTreeListener (I modified it in my project and it worked). Everything else works great! You are the best programmers!

**Comment by ericvergnaud** [comment]
Correct, but actually, those are never called. Some wiring code could be missing in visitAtom.
Did you bump into this by reading the code or do you have a repeatable use case?

**Comment by xaltotungreat** [comment]
Hello Eric. I have a repeatable use case. Here is my grammar:

grammar LogicalExpression;

rLogicalExpression
	: rOneComparisonExpr rOneLogicalFragment*                                                                           # fullLogicalExpr
	;

rOneLogicalFragment
	: op = (AND_OPERAND | OR_OPERAND) rOneComparisonExpr                                                                # oneLogicalFragment
	;
	
rOneComparisonExpr
	: rComparisonOperand op = (EQUALS | NOT_EQUALS | GREATER | LESS | GREATER_EQUALS | LESS_EQUALS) rComparisonOperand  # oneComparisonExpr
	;

rComparisonOperand
	: NUMERIC_CONSTANT                                                                                                  # CompOperNumeric
	| BOOLEAN_CONSTANT                                                                                                  # CompOperBool
	| VARIABLE_NAME                                                                                                     # CompOperVariableName
	;

AND_OPERAND: [Aa][Nn][Dd];                                                                     // conjunction operand
OR_OPERAND: [Oo][Rr];                                                                          // disjunction operand
GREATER: '>';
LESS: '<';
GREATER_EQUALS: '>=';
LESS_EQUALS: '<=';
EQUALS: '==';
NOT_EQUALS: '!=';
BOOLEAN_CONSTANT: '[Tt][Rr][Uu][Ee]' | '[Ff][Aa][Ll][Ss][Ee]';                                 // boolean constants
NUMERIC_CONSTANT: NUMERIC_CONSTANT_INTEGER | NUMERIC_CONSTANT_FRACTIONAL;                      // any number
NUMERIC_CONSTANT_INTEGER: DIGIT | NONZERO_DIGIT DIGIT+;
NUMERIC_CONSTANT_FRACTIONAL: DIGIT '.' DIGIT* | NONZERO_DIGIT DIGIT+ '.' DIGIT* | '.' DIGIT+;
VARIABLE_NAME: [_A-Za-z][_A-Za-z0-9]*;                                                         // name of a variable
WS: [ \t\r\n]+ -> skip;                                                                        // skip tabs, whitespace

fragment
DIGIT: ZERO_DIGIT | NONZERO_DIGIT;

fragment
ZERO_DIGIT: '0';

fragment
NONZERO_DIGIT: [1-9];

One of the methods generated for the visitor is
LogicalExpressionVisitor.prototype.visitCompOperVariableName = function(ctx) {
	// the code is mine, the method visitChildren is also local, it executes 'accept' for every child
	console.log('ComOperVarName');
	visitChildren(this, ctx); // I visit the children of this method here (not absolutely necessary but I did this for debugging)
};
The only child of this CompOperVariableName is a symbol element VARIABLE_NAME.
I found that the following code is executed when I try to visit this only child:
TerminalNodeImpl.prototype.accept = function(visitor) {
	return visitor.visitTerminal(this);
};
But before I made the modifications in tree.js my visitor didn't have this method.

**Comment by ericvergnaud** [comment]
Actually, those methods are also required on ParseTreeListener

**Comment by ericvergnaud** [comment]
fixed by #1060

**Comment by xaltotungreat** [comment]
This is good news. I also noticed this but (I mean no offence this is your code and you can do what you think is right) but it is correct for listener methods to be called visitSomething? Usually generated listener methods follow the pattern enterSomething/exitSomething. Visitor methods are called visitSomething. 
But anyway you are doing a great job Eric.

**Comment by ericvergnaud** [comment]
The rule here is to stick as much as possible to the reference Java implementation in order to facilitate maintenance 

Envoyé de mon iPhone

**Comment by sharwell** [comment]
@xaltotungreat terminals and error nodes do not have children, so enter/exit would just result in two consecutive calls in the same context. By naming them visit*, it's clear that only one method is called and no children are visited automatically.
