### ISSUE TITLE
Unable to access the documentation

### ISSUE THREAD

**Issue by imranazad** [antlr/antlr4#1061]
I'm unable to access the documentation, when going to the URL I get a login page: https://theantlrguy.atlassian.net/wiki/display/ANTLR4/ANTLR+4+Documentation

**Comment by PhydeauxLeChien** [comment]
I have the same problem.

**Comment by vemilyus** [comment]
All the docs that were in the Confluence Wiki have moved to the repo: [Link](https://github.com/antlr/antlr4/tree/master/doc).

**Comment by imranazad** [comment]
Thanks
