### ISSUE TITLE
python3 generated invalid syntax

### ISSUE THREAD

**Issue by h4ck3rm1k3** [antlr/antlr4#1062]
using the version  commit 01e6923dbd1c3cc37925459b491d9ad93eeb4ca6 Date:   Tue Dec 8 11:39:09 2015 -0800
using the input : https://github.com/antlr/grammars-v4/blob/master/antlr4/ANTLRv4Parser.g4
and the command :
java -jar ../../antlr4/tool/target/antlr4-4.5.2-SNAPSHOT.jar  -Dlanguage=Python3 *.g4  

I get invalid syntax generated : 

```
python3.4 ANTLRv4Lexer.py 
  File "ANTLRv4Lexer.py", line 979
    return Character.isJavaIdentifierPart(Character.toCodePoint((char)_input.LA(-2), (char)_input.LA(-1)))
                                                                           ^
SyntaxError: invalid syntax
```

Looks very much like c or java typecasting

**Comment by ericvergnaud** [comment]
Hi,

not sure where you take the *.g4 syntax from. Have you tried specifying the exact grammar file name?

Eric

**Comment by h4ck3rm1k3** [comment]
sure that does not make any difference, the * expands on the command line.
java -jar ../../../antlr4/tool/target/antlr4-4.5.2-SNAPSHOT.jar
 -Dlanguage=Python3 ./ANTLRv4Lexer.g4
this produces the same result

On Sun, Dec 13, 2015 at 9:06 AM, ericvergnaud <notifications@github.com>
wrote:

> Hi,
>
> not sure where you take the *.g4 syntax from. Have you tried specifying
> the exact grammar file name?
>
> Eric
>
> > Le 13 déc. 2015 à 20:24, James Michael DuPont <notifications@github.com>
> a écrit :
> >
> > using the version commit 01e6923 <
> https://github.com/antlr/antlr4/commit/01e6923dbd1c3cc37925459b491d9ad93eeb4ca6>
> Date: Tue Dec 8 11:39:09 2015 -0800
> > using the input :
> https://github.com/antlr/grammars-v4/blob/master/antlr4/ANTLRv4Parser.g4 <
> https://github.com/antlr/grammars-v4/blob/master/antlr4/ANTLRv4Parser.g4>
> > and the command :
> > java -jar ../../antlr4/tool/target/antlr4-4.5.2-SNAPSHOT.jar
> -Dlanguage=Python3 *.g4
> >
> > I get invalid syntax generated :
> >
> > python3 test.py
> > mdupont@mdupont-Aspire-7750G:~/experiments/grammars-v4/antlr4$
> python3.4 ANTLRv4Lexer.py
> > File "ANTLRv4Lexer.py", line 979
> > return
> Character.isJavaIdentifierPart(Character.toCodePoint((char)_input.LA(-2),
> (char)_input.LA(-1)))
> > ^
> > SyntaxError: invalid syntax
> > Looks very much like c or java typecasting
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/antlr/antlr4/issues/1062>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/antlr/antlr4/issues/1062#issuecomment-164262275>.
>



-- 
James Michael DuPont
Kansas Linux Fest http://kansaslinuxfest.us
Free/Libre Open Source and Open Knowledge Association of Kansas
http://openkansas.us
Member of Free Libre Open Source Software Kosova http://www.flossk.org
Saving Wikipedia(tm) articles from deletion http://SpeedyDeletion.wikia.com

**Comment by ericvergnaud** [comment]
Have you tried with 4.5.1?

Envoyé de mon iPhone

**Comment by h4ck3rm1k3** [comment]
as opposed to the head? I can check out the tag. I was able to fix various
problems but could not get the parser to work. Am trying the java parser
now instead of python.

On Sun, Dec 13, 2015 at 6:29 PM, ericvergnaud <notifications@github.com>
wrote:

> Have you tried with 4.5.1?
>
> Envoyé de mon iPhone
>
>
> > Le 13 déc. 2015 à 23:11, James Michael DuPont <notifications@github.com>
> a écrit :
> >
> > sure that does not make any difference, the * expands on the command
> line.
> > java -jar ../../../antlr4/tool/target/antlr4-4.5.2-SNAPSHOT.jar
> > -Dlanguage=Python3 ./ANTLRv4Lexer.g4
> > this produces the same result
> >
> > On Sun, Dec 13, 2015 at 9:06 AM, ericvergnaud <notifications@github.com>
> > wrote:
> >
> > > Hi,
> > >
> > > not sure where you take the *.g4 syntax from. Have you tried specifying
> > > the exact grammar file name?
> > >
> > > Eric
> > >
> > > > Le 13 déc. 2015 à 20:24, James Michael DuPont <
> notifications@github.com>
> > > a écrit :
> > > >
> > > > using the version commit 01e6923 <
> > >
> https://github.com/antlr/antlr4/commit/01e6923dbd1c3cc37925459b491d9ad93eeb4ca6
> >
> > > Date: Tue Dec 8 11:39:09 2015 -0800
> > > > using the input :
> > >
> https://github.com/antlr/grammars-v4/blob/master/antlr4/ANTLRv4Parser.g4 <
> > >
> https://github.com/antlr/grammars-v4/blob/master/antlr4/ANTLRv4Parser.g4>
> > > > and the command :
> > > > java -jar ../../antlr4/tool/target/antlr4-4.5.2-SNAPSHOT.jar
> > > -Dlanguage=Python3 *.g4
> > > >
> > > > I get invalid syntax generated :
> > > >
> > > > python3 test.py
> > > > mdupont@mdupont-Aspire-7750G:~/experiments/grammars-v4/antlr4$
> > > python3.4 ANTLRv4Lexer.py
> > > > File "ANTLRv4Lexer.py", line 979
> > > > return
> > >
> Character.isJavaIdentifierPart(Character.toCodePoint((char)_input.LA(-2),
> > > (char)_input.LA(-1)))
> > > > ^
> > > > SyntaxError: invalid syntax
> > > > Looks very much like c or java typecasting
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub <
> > > https://github.com/antlr/antlr4/issues/1062>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/antlr/antlr4/issues/1062#issuecomment-164262275>.
> > >
> >
> >
> >
> > --
> > James Michael DuPont
> > Kansas Linux Fest http://kansaslinuxfest.us
> > Free/Libre Open Source and Open Knowledge Association of Kansas
> > http://openkansas.us
> > Member of Free Libre Open Source Software Kosova http://www.flossk.org
> > Saving Wikipedia(tm) articles from deletion
> http://SpeedyDeletion.wikia.com
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/antlr/antlr4/issues/1062#issuecomment-164310319>.
>



-- 
James Michael DuPont
Kansas Linux Fest http://kansaslinuxfest.us
Free/Libre Open Source and Open Knowledge Association of Kansas
http://openkansas.us
Member of Free Libre Open Source Software Kosova http://www.flossk.org
Saving Wikipedia(tm) articles from deletion http://SpeedyDeletion.wikia.com

**Comment by ericvergnaud** [comment]
I believe those grammars are bound to the Java target (the tool is written in Java) but I couldn't find the source for the breaking fragment...

Envoyé de mon iPhone

**Comment by sharwell** [comment]
It's part of [**LexBasic.g4**](https://github.com/antlr/grammars-v4/blob/master/antlr4/LexBasic.g4#L205-L208), which is [imported by **ANTLRv4Lexer.g4**](https://github.com/antlr/grammars-v4/blob/master/antlr4/ANTLRv4Lexer.g4#L45).

Semantic predicates are not translated to other languages by the code generator. These were written in Java, so it's not surprising that the generated code does not work in Python. You will need to convert all actions and predicates from Java to Python before these grammars can be used there.
