### ISSUE TITLE
Consecutive lexer literals warning

### ISSUE THREAD

**Issue by SimonSntPeter** [antlr/antlr4#1068]
When starting ANTLR4 I understood clearly that with the idiomatic 

SKIPWS : [ \t\r\n]+ -> skip ;

that whitespaces would be skipped. This is true in the parser but not in the lexer (obviously, in hindsight) but it cost me a couple of hours when trying to understand why these didn't work:

NOT_BETWEEN: 'not' 'between' ;
-and-
cneq : ( '<' '>' ) | ('!' '=' ) ;  // allows for spaces in inequality e.g  a <   > b

Possible fix: If 2 consecutive literals appear in a lex rule consider that the user has likewise misunderstood this (otherwise they'd have written something like '<>'), and warn appropriately.
Don't report e.g.

NOT_BETWEEN: NOT 'between' ;

as this is not unreasonable.

**Comment by parrt** [comment]
actually I can't change as you might want [aA] 'nd' w/o a space.
