### ISSUE TITLE
Optionally report unused lexer/parser rules

### ISSUE THREAD

**Issue by SimonSntPeter** [antlr/antlr4#1069]
Sam Harwell points out this is dubious given that all parse rules can be considered roots from which a caller can start parsing from, and some rules deliberately left unused (his example <https://github.com/tunnelvisionlabs/antlr4-grammar-postgresql/blob/master/src/com/tunnelvisionlabs/postgresql/PostgreSqlLexer.g4#L609-L636>).
However it may be helpful to allow them to be reported. Definition of unused rule is any parse/lex rule unreferenced by any other. Put this onto stdout and let the user decide what to do with it.

**Comment by KvanTTT** [comment]
Yes, it is especially usefull in grammar developing stage. Moreover, parsing from custom rule is rarely used feature.

Maybe additional attribute should be added to parser rule? Something like ```root```. If rule will have not this attribute and will have not any references, the warning will be generated.

**Comment by KvanTTT** [comment]
What about such syntax for root rules?

```ANTLR
parserRule1, root
	: parserRule2
	| TOKEN
	...
	;
```

If at least one rule this "root" attribute exists, warnings will be generated for unreachable parser rules like this:

```ANTLR
parserRule1, root    // No warning, root.
	: parserRule2
	: parserRule3
	;

parserRule2          // Warning: this rule has not "root" attribute and references.
	: TOKEN1
	;

parserRule3          // No warning because it has reference from parserRule1.
	: parserRule4
	| TOKEN2
	;
	
parserRule5, root    // No warning here because it's root.
	: TOKEN3
	;
```

But if grammar has no root nodes, warnings will not be generated (for back compability issues with old format). In most cases only one root rule required in grammar development. But root node brings logical clarity.

**Comment by KvanTTT** [comment]
Another idea: put "root" attribute before rule declaration (similary to token "fragment" modifier):
```ANTLR
root parserRule1
    : parserRule2
    | TOKEN
    ...
    ;
```
Moreover it can be extended to "caseSensitive" or "caseInsensitive" modifier in mode (implemented in [this PR](https://github.com/antlr/antlr4/pull/1092)):
```ANTLR
caseInsensitive mode PHP;
Abstract: 'abstract';
Array: 'array';
As: 'as';
```

**Comment by KvanTTT** [comment]
If roots will be exist, they can be available in Parser class:
```C#
public override List<ParseRuleContext> Roots { get; }
```
Similary to ```Vocabulary```.

**Comment by parrt** [comment]
I think this is a matter for dev tools, like the intellij plugin, not antlr itself so i'm closing.

**Comment by KvanTTT** [comment]
> I think this is a matter for dev tools, like the intellij plugin, not antlr itself so i'm closing.

But dev tools don't have info about root rules, they highlight everything unused. It's untidy.
