### ISSUE TITLE
indicate token types as well as numbers in -tokens dump

### ISSUE THREAD

**Issue by SimonSntPeter** [antlr/antlr4#1073]
Very handy if the token dump given by flag -tokens also gave their type instead of their numbers only.
When I have problems I currently have to open MSSQLLexer.tokens in emacs with auto-revert-mode on, then look from a dump like

``` [@0,1:6='select',<256>,1:1]
[@1,12:12='v',<295>,2:2]
[@2,13:13='.',<108>,2:3]
[@3,14:14='b',<295>,2:4]
...
```

to the .tokens file to make sure 'select' is indeed a SELECT and not an IDENT. To have

```
[@0,1:6='select',<256>,1:1, is SELECT]
[@1,12:12='v',<295>,2:2, is IDENT]
[@2,13:13='.',<108>,2:3, is DOT]
[@3,14:14='b',<295>,2:4, is IDENT]
...
```

may be so useful? 
Note: is it newbies that have most to gain from this, or experienced guys too?

**Comment by KvanTTT** [comment]
:+1: This more pleasant and informative for debug.

**Comment by parrt** [comment]
I use the intellij plugin but you're right! I added function `CommonToken.toString(Recognizer)` and called from test rig.

```
[@0,0:0='a',<ID>,1:0]
[@1,1:1='+',<'+'>,1:1]
[@2,2:2='b',<ID>,1:2]
[@3,4:3='<EOF>',<EOF>,2:0]
```
