### ISSUE TITLE
Accidental clash between lexer rule and lexer literal recognising same string causes parse to fail

### ISSUE THREAD

**Issue by SimonSntPeter** [antlr/antlr4#1074]
This may be a more general problem in that an a lexer rule and a literal regexp may do the same, but just literal discussed here.
Had a lex rule
```
EQ : '=' ;
```
but forgot I also had a rule that contained a literal equals, something like

```
column_def '=' expression;
```
This caused parse to fail because (I believe) an anonymous lexer token was created in addition to EQ, one got picked up and used where I expected the other and the parse failed mysteriously. If my understanding of this is correct, perhaps warn if a lex literal and a lex rule match the same thing, and tell the user not to do this?

**Comment by KvanTTT** [comment]
It is wrong. When you use '=' token in parser without lexer rule it's unnamed. On the other hand, if you declare ```EQ : '=';``` lexer rule, lexem '=' will be named EQ.

**Comment by SimonSntPeter** [comment]
I'm not arguing with you but *something* breaks. I've reproduced it. Given a working grammar, I successfully parse

```select case when 1 = 2 then a else b end```

I change exactly one rule, from

```
old_style_aliased_column :
        sident CEQ expression
    ;
```

to

```
old_style_aliased_column :
        sident '=' expression
    ;
```

recompile and it fails. The MSSQL.tokens file for the successful parse is this (signifcantly change part only show).

```
T__0=1
T__1=2
STRING_CONST=3
UNICODE_CONST=4
BINARY_CONST=5
...
BDIDENT=314
QDIDENT=315
SKIPWS=316
'XXX_TODO_XXX'=1
'TODO_XXX'=2
'bigint'=17
```

but for the failing parse the .tokens file looks like this

```
T__0=1
T__1=2
T__2=3       <<< new!
STRING_CONST=4
UNICODE_CONST=5
BINARY_CONST=6
...
BDIDENT=315
QDIDENT=316
SKIPWS=317
'='=1       <<< new!
'XXX_TODO_XXX'=2
'TODO_XXX'=3
'bigint'=18
```

Ignoring the renumbering of tokens, a new literal has appeared. Bottom line is, I can break the parse by mixing literals and rules. It cost me a couple of hours, I just want to prevent the same happening for anyone else.

**Comment by jimidle** [comment]
Generally I advise not to use literals in the parser for other than trivial
parsers, and especially not when you are just starting out. The ability to
specify literals in the parser is loved by some and disliked by others
(including me), for this reason.

Jim

**Comment by KvanTTT** [comment]
@jimidle , I like literals in parser because of readability reason :smile:

**Comment by SimonSntPeter** [comment]
@jimidle: "Generally I advise not to use literals in the parser for other than trivial parsers, and especially not when you are just starting out". This is *precisely* what n00bs like myself will do then be baffled by the fallout (this cost me ~2 hours of frustration). I'm suggesting the parser to educate them on their first mistake, if possible, not after someone has to help them out on stackoverflow.

**Comment by KvanTTT** [comment]
Sorry for offtopic, but I did not find another way to connect with @SimonSntPeter.
Are you working on MSSQL grammar? If you are, could you please connect with me, beacause of I'am also working on it.

**Comment by jimidle** [comment]
Why is
LPAREN
Less readable than
'('
But as I said, in different words, horses for courses. 






On Fri, Dec 18, 2015 at 1:41 AM -0800, "Ivan Kochurkin" <notifications@github.com> wrote:












@jimidle , I like literals in parser because of readability reason

**Comment by jimidle** [comment]
I think you didn't get my point to be honest. If you search the list I have been advocating not having this for your reasoning for lots of years. ;)






On Fri, Dec 18, 2015 at 2:02 AM -0800, "SimonSntPeter" <notifications@github.com> wrote:












@jimidle: "Generally I advise not to use literals in the parser for other than trivial parsers, and especially not when you are just starting out". This is precisely what n00bs like myself will do then be baffled by the fallout (this cost me ~2 hours of frustration). I'm suggesting the parser to educate them on their first mistake, if possible, not after someone has to help them out on stackoverflow.

**Comment by SimonSntPeter** [comment]
@jimidle : "I think you didn't get my point to be honest. If you search the list I have been advocating not having this for your reasoning for lots of years. ;)"
Doubtless you're correct and warned of this repeatedly but would newbies go back through posts or jump in and make mistakes? Cos I can tell you it's the latter. If ANTLR can easily warn of these kind of things, why not? It's a usability feature. User-friendliness FTW.

Given previous advice, I've moved completely from literals to lexer rules, but as to " Why is LPAREN Less readable than '(' "   FYI it's because ( is more graphically distinct then a sequence of capital letters. Why + is more visually distinct then ADDITION when surrounded by other CAPITALISED WORDS.  And capital letters are known to be less readable than lower case (something to do with horizontal spatial frequency, I can't remember). All this is very well known by psychologists.
And also irrelevant if the parser chokes, so it's all lexer rules now...

**Comment by SimonSntPeter** [comment]
@KvanTTT : If I read it right, the ANTLR4 book agrees with your first comment where you said I was wrong:  "Having both the literal and lexical rule MULT is not problem; they both result in the same token type" (P73), but I could reproduce the problem, and the .tokens file changed. I don't understand.

**Comment by parrt** [comment]
This should work fine. `EQ : '=' ;` is just an alias for '='. Both are interchangeable, UNLESS you have another token def that can match '=' (by mistake?) and then order matters. '=' might then refer to another token not EQ.
