### ISSUE TITLE
JavaScript visitors not visiting children

### ISSUE THREAD

**Issue by RedTailedHawk** [antlr/antlr4#1076]
My generated visitors are working fine in Python and Java, but not in JavaScript.  Could it be that the generated JavaScript is just a stub and does not visit the children?

```
// Visit a parse tree produced by rql2Parser#expression.
rql2Visitor.prototype.visitExpression = function(ctx) {
};
```

I'm using ANTLR 4.5.1 to generate the code.  Is there a later version I should be using?

Thanks for any help.
-Larry

**Comment by juniperoserra** [comment]
The issue is that there is a bug in ParseTreeVisitor.visit.

Inside the "`map`" clause where it says, "`ctx.accept(this)`" it should say "`child.accept(this)`" 

It can be patched from the outside.
I'll try to set up a pull request.

`ParseTreeVisitor.prototype.visit = function(ctx) {
    if (Array.isArray(ctx)) {
        return ctx.map(function(child) {
            return child.accept(this);
        }, this);
    } else {
        return ctx.accept(this);
    }
};`
