### ISSUE TITLE
ANTLR4 problem with malformed(?) backslash-specified unicode literal 

### ISSUE THREAD

**Issue by SimonSntPeter** [antlr/antlr4#1077]
Trivial bug. Seems to produce invalid java, which then bombs. Problem may be that unicode chars of form "\u..." are expected to be of 4 digits.
This should reproduce

```
fragment MONEYSIGN : [\u24\uA2] ;
```

gets me a java stack dump starting

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "24\u"
```

Curiously this doesn't except

```
fragment MONEYSIGN : [\u24] ;
```

Using antlr 4.5.1

**Comment by SimonSntPeter** [comment]
Above isn't very helpful. Better code to reproduce is

```
grammar MSSQL;

moneysymbol : MONEYSYMBOL ;

MONEYSYMBOL : [\u24\uA2] ;  

SKIPWS : [ \t\r\n]+ -> skip ;
```

and start the parse at moneysymbol. Book says unicode must be in form \uXXXX so this really is minor. However if you just have "MONEYSYMBOL : [\u24] ;" then it doesn't crash but fails with this on the command line (when given input $, which is character \u24):

```
line 1:0 token recognition error at: '$'
[@0,3:2='<EOF>',<-1>,2:0]
enter   moneysymbol, LT(1)=<EOF>
line 2:0 missing MONEYSYMBOL at '<EOF>'
exit    moneysymbol, LT(1)=<EOF>
```

which I take to mean that it's expecting something but didn't get it.

**Comment by KvanTTT** [comment]
I'll fix it and another lexical issues like this:
```ANTLR
INVALID_RANGE:         'GH'..'LM';
INVALID_RANGE_2:       'F'..'A' | 'Z';
INVALID_CHAR_SET:      [f-az];
```
