### ISSUE TITLE
Javascript runtime - Missing constructor functions

### ISSUE THREAD

**Issue by cosenmarco** [antlr/antlr4#1078]
Hi,
I'm missing the constructor function at two locations:
- In `src/antlr4/Parser.js` missing function ParseTreePatternMatcher:

``` javascript
var m = new ParseTreePatternMatcher(lexer, this);
```
- In `atn/SemanticContext.js` missing Object SemanticPredicate:

``` javascript
result = result === null ? o : SemanticPredicate.andContext(result, o);
```

I cannot provide test cases though, I just noticed this by running a lint tool.

**Comment by parrt** [comment]
@cosenmarco  does this cause problems or is it just an error from lint?

**Comment by cosenmarco** [comment]
Hey Terence, I abandoned the project I was working on which used antlr4 javascript frontend, so I cannot help anymore with this, sorry...

**Comment by parrt** [comment]
ok, no problem.
