### ISSUE TITLE
Empty alternative - require it to be explicit?

### ISSUE THREAD

**Issue by SimonSntPeter** [antlr/antlr4#1086]
I don't know if anyone else has had significant problems with accidentally introducing empty alternatives (producing error "rule ... contains an optional block which contains at least one alternative that can match an empty string"), but I've done it twice and the second time's taken me ~4 hours to track down, in part because the consecutive |'s were separated by a comment which disguised it. The distance of the errors reported from the actual problem were large.
Would having an explicit 'this alt left intentionally blank' symbol be worthwhile?

**Comment by parrt** [comment]
Hmm...possible but I hesitate to alter the meta-language at this point. it could collide with legacy grammars.
