### ISSUE TITLE
Javascript runtime, better packaging for use in browsers

### ISSUE THREAD

**Issue by bd82** [antlr/antlr4#1088]
The javascript runtime uses 'honey require' to load resources in the browser
This causes several issues:

* **Synchronized** loading of ~50 files can easily take 5-10 seconds with 100-200ms latency.
* The current version of honey [require.js](https://github.com/antlr/antlr4/blob/master/runtime/JavaScript/src/lib/require.js#L65) does not work on IE 11 as:
```new URL(...)``` will throw ```Object doesn't support this action```.
* Performance degradation of [~30%](http://sap.github.io/chevrotain/performance/antlr4.html) on chrome.
 * not sure why, may be related to use of eval to load the modules?
* Generated code uses a mixture of module loading (require) and global variables (antlr4).

**Comment by bd82** [comment]
**Suggestion:**
There is no need for a new module loading system. please consider using one of the 'standard' existing tools instead.
for example:
* [UMD - Universal Module Definition](https://github.com/umdjs/umd)
* [Browserify](http://browserify.org/)
* [webpack](https://webpack.github.io/docs/motivation.html)

I am no expert on these tools. but one way would be to(there are probably better ways...):
* package all the files to a **single antlr4.js** and wrap them in UMD
 * This will resolve the loading time (1 request vs 50)
 * The UMD pattern will allow the **same** antlr4.js file to be used different standard module loading
   environments.
 * How to: 

    ```
    npm install -g browserify (just once)
    cd antlr4/runtime/JavaScript/src
    browserify ./antlr4/index.js -o antlr4.js -s antlr4
    (now open antlr4/runtime/JavaScript/src/antlr4.js in your favorite editor)
    ```
* modify the lexer/listener/parser code generation to also be wrapped using UMD.
  * Same reasoning... generating files that can be loaded in multiple environments.
 
As mentioned earlier, There are probably better ways... this is just one option.
The main thing is to use 'standard' tools to avoid the issues mentioned above.

**Comment by ericvergnaud** [comment]
Hi thanks for this.

A few comments:
 - it does not make much sense to compress the runtime, without all the related .js (not just the generated ones, but also the ones written by the developer)
 - nodejs compatibility is required which very few ‘standard' compressors support
 - many developers have their own constraints when it comes to code distribution, it is much simpler for them to incorporate raw scripts than files which have already been compressed by another compressor
 - the last thing I want is to ‘edit’ the runtime in a single file

We will therefore not follow your proposal.
However, I strongly encourage you to contribute by providing a step by step packaging method in a documentation page 

Eric

**Comment by ericvergnaud** [comment]
Hi,

the javascript runtime is not bound to ‘honey require’, but rather to the nodejs ‘require’ syntax and behavior, you can use any nodejs compatible ‘require’ script.
If you have issues with honey require, and I suggest you report the issue to its author, it is not part of antlr and is not supported. It is only provided for convenience.
AFAIK, all CommonJS ‘require’ modules use ‘eval’ to load the downloaded scripts, so a bit more digging on the chrome performance issue (vs what?) would be useful.
Also not sure why the antlr4 global variable would be an ‘issue’

Eric

**Comment by bd82** [comment]
Hi @ericvergnaud.

In response to your first comment:
Compression/Packaging is **not** mutually exclusive with the source code being split into multiple files.
nor does it conflict with running in node.js or delivering 'raw scripts'.

The above is only true if one assumes that the source code is delivered **as is** to the consumer.

#### An Example:
Lets look at [Less.js](https://github.com/less/less.js).

* Less.js runs both in node.js and in the browser.
* Their sources are split into [multiple files](https://github.com/less/less.js/tree/master/lib/less) written using node.js require / export syntax.
* ``` npm install less ``` will install **all** those separate files. 
* ``` bower install less ``` however will **only** contain concatenated versions as in a browser context
       aggregated libraries are important.
 * It even contains two different concatenated versions, simple concatenated and a minified one.
* The [download page](http://lesscss.org/#download-options) has links to concatenated minified version.

The discussion is not about changing the sources file structure (single big file), nor is it about 
changing the existing delivery method of 'raw scripts'.

It is about a feature request to **also** deliver ANTLR4 JS runtime in an **easy to consume** manner in the browser.

**Comment by bd82** [comment]
Hi @ericvergnaud.

In response to your second comment:

 > the javascript runtime is not bound to ‘honey require’, but rather to the nodejs ‘require’ syntax and behavior, you can use any nodejs compatible ‘require’ script.

That puts the burden on consuming ANTLR4 in the browser on the user. If ANTLR4 can not be easily
consumed and used in the browser. does this mean the browser is a second class citizen for the Javascript runtime?
If so should it be called the Node.js runtime?

> If you have issues with honey require, and I suggest you report the issue to its author, it is not part of antlr and is not supported. It is only provided for convenience.

I don't have issues with honey require, I managed to hack around it and I don't think it is needed at all, but my hack meant changing generated code, so I think the solution should include generation code changes and not just documenting a step by step process.

**Users of ANTLR4 in the browser are those that will have issues** (mentioned above):
I Think that is a concern of ANTLR. unless Browser usage is officially unsupported?

> AFAIK, all CommonJS ‘require’ modules use ‘eval’ to load the downloaded scripts, so a bit more digging on the chrome performance issue (vs what?) would be useful.

> "vs what?" 

I ran a (hacked) concatenated version of ANTLR **VS** one loaded using honey require.js 
forgot to link to the [source](https://github.com/SAP/chevrotain/blob/gh-pages/performance/antlr4.html) 
* in chrome the honey require is slower
* in firefox its the same
* in IE 11 honey require does not work at all.

Unfortunately I don't have the time right now to investigate it farther.

> Also not sure why the antlr4 global variable would be an ‘issue’

It a minor style issue, of mixing module loading mechanics. my bad for bringing it up as it distracts from the main issue. please forget I mentioned it...

**Comment by ericvergnaud** [comment]
Hi,

Less.js has 3 different sets of raw scripts for node, rhino and browser.
This may be relevant for less which manipulates UI elements, but it’s not for antlr which only manipulates data structures.
As already mentioned, I believe compression/packaging should be done at a higher level than just the runtime.
Some people have successfully implemented that without changing the file structure or the generated code.
See: https://github.com/antlr/antlr4/pull/971 <https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fantlr%2Fantlr4%2Fpull%2F971&sa=D&sntz=1&usg=AFQjCNGOCaOia9Jw_m4cV9T57FqfckdfcA>

Eric

**Comment by ericvergnaud** [comment]
You do have issues with honey require since according to you it does not work in IE11…
I don’t have time either to investigate your issues, which are not antlr4 issues, but packaging ones.
I disagree on your proposed approach, so will not investigate it.
If you think it should be done differently, then please feel free to propose a contribution.

**Comment by bd82** [comment]
Thanks for the discussion. It is obviously your library and up to you to decide what is in the scope of
the library and how important it is (or not) to be easily consumable in the browser.

I believe differently and make sure to release libraries I write in an easy to consume manner
for either node.js/browser.

I also do not believe there is much point in proposing a contribution when the discussion is not about technical feasibility, but rather about the scope of the product features, nor am I sure I can create
this contribution as it will involve modifying the npm release artifacts / development work flow
which is not a good idea as a first commit to a project...

Thanks again.
Shahar.

**Comment by NeacsuCristian** [comment]
Related to: The current version of honey require.js does not work on IE 11 as: new URL(...) will throw Object doesn't support this action.

The require.js were updated, but not as well on this github.
Please find the update on :
         https://github.com/flowyapps/honey-require

Thank you!

**Comment by Esmool** [comment]
I think all you guys did not get the point of @bd82 . I'm facing the same situation of him. The Antlr4 javascript runtime is written in the CommonJS's style of 'require()', not async. It's fine for the use of NodeJS to handle server side requirements. But in the browser, the async type of 'require' is recommended.

I've tried using Browserify to pack all the runtime into a bundle and change the 'require' feature to async.  But failed to load it using RequireJs. I'm still working on it.

As the webpack method mentioned in the doc. It works. But for the developer it's not that friendly. No one likes changing a little and packing a lot to test their codes. Separated runtime and lexer/parser are much quick for developing.

**Comment by ericvergnaud** [comment]
Hi,

I personally webpack my generated parsers with antlr, so not sure why this is an issue.
to me there is no strong argument in favour of a pre-packed runtime vs the above, except user preferences
please feel free to propose a way to webpack/minify antlr runtime.
provided it does not require significant changes in the runtime code, I will look into the PR.

Eric

**Comment by Esmool** [comment]
I'm trying. Not done yet. Dam, it's really a nightmare try this.

The key point is **ASYNC**, and **SEPERATE** the runtime & generated parser/lexer codes as you noticed.

Why I have to do this is the Java version of ANTLR4 runtime producing a  heap leak while hosted in tomcat to handle each web request. It's another long story...
