### ISSUE TITLE
use of "exception" keyword in grammar

### ISSUE THREAD

**Issue by hofiee** [antlr/antlr4#1089]
Dear All!

I was playing around with a grammar, an was coming to the following issue.
The grammar below generates non-compilable java-code. Reason is because the java-keyword \"exception\" is used.
I am working with antlr 4.5.1, and am pretty new so I have no idea if this is expected behaviour or not. At least a warning when using \"exception\" would be nice from a user point-of-view.

Thanks!

Manfred

grammar reproduce_exception;
exception_init
    : exception=name
    ;
name : ID
     ;
ID   :   [a-zA-Z] [a-zA-Z0-9$#_]*
     ;

**Comment by KvanTTT** [comment]
You can add this word to keywords list: https://github.com/antlr/antlr4/blob/master/tool/src/org/antlr/v4/codegen/target/JavaTarget.java#L52

**Comment by parrt** [comment]
Hi. this collides with a Java class not a keyword so probably not much I can do. i'll close.
