### ISSUE TITLE
~[\]] breaks next token

### ISSUE THREAD

**Issue by andrewbaxter** [antlr/antlr4#1091]
```
grammar test;
test : TEST;
UNUSED : ~[\]];
TEST : 'a';
```

will fail to parse the file:
```
a
```

with the error message:
```
line 1:0 mismatched input 'a' expecting 'a'
```

These alternatives also fail:
```
UNUSED : ~']';
UNUSED : ~(']');
```

For comparison, 
```
grammar test;
test : TEST;
UNUSED : [\]];
TEST : 'a';
```
works.

Antlr version 4.5-1 (Arch linux)

**Comment by jimidle** [comment]
Declare tokens like 'a' before all encompassing rule like OTHER.  In general have a final rule:
ERROR: . ;






On Thu, Jan 7, 2016 at 11:17 PM -0800, "andrewbaxter" <notifications@github.com> wrote:










grammar test;
test : TEST;
UNUSED : ~[\]];
TEST : 'a';




will fail to parse the file:

a




with the error message:

line 1:0 mismatched input 'a' expecting 'a'




These alternatives also fail:

UNUSED : ~']';
UNUSED : ~(']');




For comparison, 

grammar test;
test : TEST;
UNUSED : [\]];
TEST : 'a';




works.



Antlr version 4.5-1 (Arch linux)

**Comment by andrewbaxter** [comment]
> Declare tokens like 'a' before all encompassing rule like OTHER.

Thanks for the suggestions!  Trying:
```
grammar test;
UNUSED : ~[\]];
TEST : 'a';
test : TEST;
```
doesn't work (same error).

I'm not sure what you meant with the final rule, but this didn't work either:
```
grammar test;
UNUSED : ~[\]];
TEST : 'a';
ERROR : .;
test : TEST;
error : .;
```

Just to clarify, my above grammar is a minimal test case that reproduces an issue I had with a more complex grammar.

**Comment by KvanTTT** [comment]
You should to rewrite your grammar by the following way:
```ANTLR
grammar test;
TEST : 'a';
UNUSED : ~[\]];
test : TEST;
```
And it will work as expected. But your issue related to this one: https://github.com/antlr/antlr4/issues/1072

**Comment by jimidle** [comment]
'a' should be before your unused token






On Fri, Jan 8, 2016 at 12:28 AM -0800, "andrewbaxter" <notifications@github.com> wrote:













Declare tokens like 'a' before all encompassing rule like OTHER.




Thanks for the suggestions!  Trying:

grammar test;
UNUSED : ~[\]];
TEST : 'a';
test : TEST;




doesn't work (same error).



I'm not sure what you meant with the final rule, but this didn't work either:

grammar test;
UNUSED : ~[\]];
TEST : 'a';
ERROR : .;
test : TEST;
error : .;




Just to clarify, my above grammar is a minimal test case that reproduces an issue I had with a more complex grammar.

**Comment by andrewbaxter** [comment]
> You should to rewrite your grammar by the following way:
I see, reading the other issue it makes sense.  

So to explain my understanding, `UNUSED` and `TEST` overlap, and since `UNUSED` comes first in the grammar the input `a` gets turned into an `UNUSED` token.  The parser gets `UNUSED` token `a`, but wants a `TEST` token (which is defined as `a`), so the error message is roughly "Got `UNUSED` token with value `a`, but expected a `TEST` token that matches `a`".

Maybe modes would help me, but it looks like I need to do more reading in any case.

Thanks for the help!
