### ISSUE TITLE
[RFC] Incremental Parsing 

### ISSUE THREAD

**Issue by HSorensen** [antlr/antlr4#1093]
I was doing some research on how to use ANTLR parser incrementally. I came across some old discussions from ~2009 this offered various solutions outside ANTLR core itself.

Since a lot of time has passed and new versions of ANTLR has been created I wanted to check if there is a recommendation on how to implement ANTLR parsers for incremental parsing.

**Comment by parrt** [comment]
The parsing part would be easy...lexer not so much ;)  No work going on in this area for ANTLR.

**Comment by HSorensen** [comment]
Can you outline how the parser part can be done ?

So if I know which part of a parsed document has changed is there a way to
reconcile the full parsetree by replacing part of the tree with a newly
parsed sub-tree.

Thanks
Henrik

**Comment by parrt** [comment]
It's a variation on the memoization used in PEG parsers and ANTLR v3.  At the start of each rule function, you have code that asks a cache whether or not you have been to this rule at this input position before. If so, it tells you how much input is consumed and then you simply seek to that position and return immediately from the function. cool, eh?
