### ISSUE TITLE
C# backtrack won't work.

### ISSUE THREAD

**Issue by eocron** [antlr/antlr4#1095]
grammar Test;
options {
  backtrack=true;
  memoize=true;
  language = CSharp3;
}

prog:   (code)+;

code
    :   BT {Console.WriteLine("BT");}
    |   OTHER {Console.WriteLine("OTHER");}
    ;

BT : 'ABC';
OTHER : .;
_______________________________________________________
This grammar outputs:
Input: ABC -> token ABC selected.
Input: ACD -> 3 tokens OTHER selected.
Input: ABD -> throw early exit exception. Should be 3 OTHER also.

This test also fails on ANTLRWorks.

**Comment by sharwell** [comment]
There is no backtracking in ANTLR 4. You should remove the `backtrack` and `memoize` options from your grammar.

It sounds like you are encountering #118. In addition to the above changes, you should add an explicit `EOF` to your start rule, which appears to be `prog`:

```antlr
prog
  : code+ EOF
  ;
```
