### ISSUE TITLE
Bug in generated JavaScript for recursive rule action

### ISSUE THREAD

**Issue by spurcell** [antlr/antlr4#1096]
I have a LISP-style recursive list construct in my grammar like so:

``` JavaScript
// we do this the old-fashioned way because that's what the compiler wants
statement_list returns [retVal]
    : statement {$retVal = {type: "stmt_list", head: $statement.retVal, tail: null};}
    | statement statement_list {$retVal = {type: "stmt_list", head: $statement.retVal, tail: $statement_list.retVal};}
    ;
```

I'm using actions to build up an AST in the form of nested JS objects. However, the `tail` property is always null for the second rule where it should be non-null. When I look at the generated code, I see

``` JavaScript
localctx.retVal =  {type: "stmt_list", head: localctx._statement.retVal, tail: localctx.retVal}
```

The `tail` property is being set to the (unset) retVal attribute of the _local_ context, not the sub-context pertaining to the recursive statement_list rule, and that's why it's always null. The code should be generated as:

``` JavaScript
localctx.retVal =  {type: "stmt_list", head: localctx._statement.retVal, tail: localctx._statement_list.retVal}
```

When I make the change by hand to the generated parser, it works like a charm.

**Comment by parrt** [comment]
Dup of https://github.com/antlr/antlr4/issues/1295 I think.
