### ISSUE TITLE
parsing matching rule with non-matching lexer parts

### ISSUE THREAD

**Issue by drewcanitz** [antlr/antlr4#1101]
I feel like this is almost certainly a misunderstanding on my part, but I just don't get it.  I have the Antlr 4 book and have tried to figure out what I'm don't wrong, but my mistake isn't clear to me.  Can anyone help explain and maybe give guidance how I can improve my grammar?

I have a very simple grammar.

`grammar BindingPath;

path
   : step ('.' step)*
   ;

step
   : TEXT '[' INT ']'       # IndexPathStep
   | '(' TEXT '.' TEXT ')'  # CastPathStep
   | TEXT                   # NameToResolve
   ;

INT : [0-9]+ ;
TEXT : ~[.()\[\]]+ ;`

I have an input "groups3[2]".  This invokes my first rule IndexPathStep as I expect.  

However if I have input "groups3[two]" it still matches the first rule but the INT context member is null.  I think this should not match the first rule because the word "two" doesn't match the lexer token INT.  I think that I should get a parser error in this case.  I think the "groups3" part should fall into the third rule leaving the "[two]" part which doesn't match any rules and give a parser error.  Why is it matching the first rule and not failing?

I'm ultimately trying to build a grammar that will parse Windows Xaml x:Bind propertyPath following the documented rules here.  [x:Bind propertyPath.](https://msdn.microsoft.com/en-us/library/windows/apps/mt204783.aspx#property_path)

Thanks in advance for any help to clear up my misunderstanding.

**Comment by ericvergnaud** [comment]
Hi,

the best place to get antler support is here:
https://groups.google.com/forum/#!forum/antlr-discussion

As per the below, would you agree that given the ‘[‘, the first rule is the closest match for groups3[two] ?
Antlr does fail, and gracefully recovers (which is most precious when editing code). If you want to prevent that behavior you need to override the error strategy.

Eric

**Comment by drewcanitz** [comment]
Thanks!  The BailErrorStrategy does seem to be what I want.  I appreciate the pointer to the google forum.  I'll ask questions like this there in the future.
