### ISSUE TITLE
IE 11 honey require.js incompatibility - Solution

### ISSUE THREAD

**Issue by NeacsuCristian** [antlr/antlr4#1102]
The current require.js on this repo is outdated. 
It was as well an issue before that describe best the problem:
- The current version of honey require.js does not work on IE 11 as: new URL(...) will throw Object doesn't support this action.

For javascript users that have the same problem, please use the updated version of require.js:
https://github.com/flowyapps/honey-require

Hope this helps. 
All the best.

**Comment by ericvergnaud** [comment]
Thanks. Closing since the js runtime is now web packed.
