### ISSUE TITLE
avoid java.lang.StackOverflowError

### ISSUE THREAD

**Issue by WolfgangFahl** [antlr/antlr4#1105]
see http://stackoverflow.com/questions/31193527/stackoverflowerror-in-antlr4

The LexerATNSimulator should IMHO give up after a certain number of recursions before the StackOverflowError happens and spit out some information what is going on to help debug the grammer that causes the problem.

```
java.lang.StackOverflowError
    at org.antlr.v4.runtime.atn.LexerATNSimulator.getEpsilonTarget(LexerATNSimulator.java:499)
    at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:480)
    at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:482)
    at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:482)
...
```

**Comment by parrt** [comment]
@WolfgangFahl Did you get an error from antlr during code generation? It's an optional token or something.

**Comment by parrt** [comment]
@WolfgangFahl  If this is an issue of actual stack size because of parsing, you can increase the stack size remarkably big in Java ;)   Did you see an error message when you generated code? Can I close this?

**Comment by Ma124** [comment]
@parrt I have the same problem. I increased the stack size but it didn't work.

**Comment by WolfgangFahl** [comment]
Increasing the stacksize obviously won't help. No please don't close this. It would be helpful to get an avoidance/debug help implemented.

**Comment by parrt** [comment]
it's an infinite loop issue when someone puts a lexer rule that can match the empty string I believe. detecting infinite loops in that case might be undecidable. (halting problem)

**Comment by KvanTTT** [comment]
Seems like it's related to https://github.com/antlr/antlr4/issues/2860 I've suggested a decision there:

* Raise `rule FRAGMENT can match the empty string` for fragments too
* Convert this warning to error

**Comment by WolfgangFahl** [comment]
This is definitely not a halting problem since the stack is a limited resource and it should be avoided to overrun the limit. The limit is known and therefore simple counting can decide when the limit is reached (or almost reached).

**Comment by KvanTTT** [comment]
It seems like I've fixed this case. Lexer should throw `EPSILON_CLOSURE` on such rules as well as parser does it. For instance, here is another fix for parser: https://github.com/antlr/antlr4/pull/1477

**Comment by KvanTTT** [comment]
@parrt it should be closed as well :)

**Comment by WolfgangFahl** [comment]
@parrt @KvanTTT thanks
