### ISSUE TITLE
Release for 4.5.2 with some changelog ?

### ISSUE THREAD

**Issue by opsec** [antlr/antlr4#1106]
Is 4.5.2 officially released ? Will there be a changelog ? I'm asking as maintainer of the FreeBSD port devel/antlr4.

**Comment by SimonSntPeter** [comment]
Indeed, I looked for a changelog myself and couldn't find one. I wanted to know what I'm upgrading to, so for now I've stuck with what I've got. Changelog very welcome!

**Comment by parrt** [comment]
Maybe here? https://github.com/antlr/antlr4/releases
