### ISSUE TITLE
Scannerless parsing

### ISSUE THREAD

**Issue by Kaba2** [antlr/antlr4#1107]
This is not a bug, but merely a feature request.

I use ANTLR4 for parsing mathematical symbol names in Latex, such as nexists (yes, somewhat exotic:). I do this without a scanner, because I need the ability of the ALL(*) parser to lookahead the correct prediction. Everything works great. The only laborious thing is that I need to type character sequences 'l' 'i' 'k' 'e' 't' 'h' 'i' 's'.

Why? Because if 'n', 'exists' and 'ne' are tokens, then 'ne' matches the start of 'nexists', and the rest of the input is deemed erroneous. The way around is to separate the tokens into characters, such as 'n' 'e', in which case the ambiguity between the negation 'n' in 'nexists' and the first 'n' in 'ne' forces the ALL(*) to lookahead further.

It would be great if there was either

a) a way to specify the grammar as being scannerless, so that 'likethis' is automatically converted to 'l' 'i' 'k' 'e' 't' 'h' 'i' 's', or
b) an additional notation, such as "likethis", which would be interpreted as 'l' 'i' 'k' 'e' 't' 'h' 'i' 's'.

I have read your paper on ALL(*), and your book; the ANTLR4 is a very impressive parser. Thank you for the effort you have put in it.

**Comment by Kaba2** [comment]
Alternatively, the problem can be seen as a lexing problem.

It is possible to correctly lex the symbol names _outside of ANTLR_ by the following simple two-stage approach:

1. Create a list A of regexes of long (length >= 4) identifiers which occur in symbol-names. Example: 'left', 'exists', 'arrow'.
2. Repeatedly find the longest regex in A in a symbol-name from left to right. The spans which are not recognized are marked as such. Example: 'nnearrow' ==> ['nne', 'arrow'], where 'nne' is unrecognized.
3. Create a list B of regexes of short (length < 4) identifiers which occur in symbol-names, such as 'n', 'ne', 'v', etc.
4. Repeat the approach of 2. for the unrecognized spans. Example: 'nne' ==> ['n', 'ne'].

We may then combine these fragments to 'n ne arrow', which is easy for ANTLR to analyze on the token level.

It would be nice if ANTLR was able to solve this lexing problem directly. However, at least now I can't see how to achieve this. This is how I end up doing character-based parsing as in the first message.

**Comment by Kaba2** [comment]
I noticed that I can take a hybrid of the two approaches above:

* Write every token of length < 4 one character at a time: Example: 'n' 'n' 'e'.
* Write every token of length >= 4 normally. Example 'right'.

This seems to give the best of both world. This technique is also mentioned in the ANTLR4 book on page 211 under Context-Sensitive Lexical Problems.

It seems to me that decomposing short tokens into single-character tokens is a common lexer pattern. Even though I limit to decomposing only tokens of length < 4, it is still laborious to write these subsequent characters. This takes me back to my first post: it would be nice to have a helper notation for doing that.

**Comment by SimonSntPeter** [comment]
Are you saying your tokens need not have any separators between them? Ewww.
If it helps, I got tired of writing like this 
AND : [aA] [nN] [dD]
and just used a bit of python to automate it. It works well. .

**Comment by Kaba2** [comment]
Yes. This is a somewhat unusual parsing application. What I am doing is capturing the informal Latex naming conventions under a formal grammar. An example input is 'leftrightarrow', and there are about 5500 of these. I now have 160 tokens of length < 4 which had to be decomposed into single characters. It works fine. I will also go for Python to automate the decomposition.

**Comment by parrt** [comment]
thanks for suggestion though I'm going to not do.
