### ISSUE TITLE
Presence of unused rule causes parse to fail.

### ISSUE THREAD

**Issue by SimonSntPeter** [antlr/antlr4#1113]
(looks like markup is messing up quoted text a little below)

Code to reproduce

```
grammar MSSQL;

sql_items :
                (
                        opt_sql_separators
                        sql_item
                ) *
                opt_sql_separators
                EOF
        ;

begin_end_block :
                BEGIN
                        // comment out just sql_items rule
                        // below to eliminate bug
                       sql_items   // <--- this
                END
        ;

BEGIN : 'begin' ;
END : 'end' ;

opt_sql_separators : ( SEMICOLON * ) ;

SEMICOLON : ';' ;

sql_item : 'iamtesting' ;

SKIPWS : [ \t\r\n]+ -> skip ;

```

Start rule is `sql_items` (ie. I do java org.antlr.v4.gui.TestRig MSSQL sql_items -gui -trace -tokens). Input is 

> iamtesting

Trace shows this, note "line 2:0 no viable alternative at input '<EOF>'" although it has parsed all input successfully (line "consume [@0,0:9='iamtesting',<1>,1:0] rule sql_item").

> iamtesting
> ^Z
> [@0,0:9='iamtesting',<1>,1:0]
> [@1,12:11='<EOF>',<-1>,2:0]
> enter   sql_items, LT(1)=iamtesting
> enter   opt_sql_separators, LT(1)=iamtesting
> exit    opt_sql_separators, LT(1)=iamtesting
> enter   sql_item, LT(1)=iamtesting
> consume [@0,0:9='iamtesting',<1>,1:0] rule sql_item
> exit    sql_item, LT(1)=<EOF>
> line 2:0 no viable alternative at input '<EOF>'
> exit    sql_items, LT(1)=<EOF>

To cause bug to go away comment out line indicated in the code in parse rule `begin_end_block`. Trace of now-successful parse

> iamtesting
> ^Z
> [@0,0:9='iamtesting',<1>,1:0]
> [@1,12:11='<EOF>',<-1>,2:0]
> enter   sql_items, LT(1)=iamtesting
> enter   opt_sql_separators, LT(1)=iamtesting
> exit    opt_sql_separators, LT(1)=iamtesting
> enter   sql_item, LT(1)=iamtesting
> consume [@0,0:9='iamtesting',<1>,1:0] rule sql_item
> exit    sql_item, LT(1)=<EOF>
> enter   opt_sql_separators, LT(1)=<EOF>
> exit    opt_sql_separators, LT(1)=<EOF>
> consume [@1,12:11='<EOF>',<-1>,2:0] rule sql_items
> exit    sql_items, LT(1)=<EOF>

Note that `begin_end_block` is used nowhere.

**Comment by SimonSntPeter** [comment]
In addition, suspect this is also at the root of another of my SO questions <http://stackoverflow.com/questions/35141969/antlr4-empty-alternative-not-working-as-expected>.

**Comment by SimonStPeter** [comment]
Is there any resolution to this as it's becoming rather pressing. As a workaround, would turning * operators into explicit recursion avoid the problem?

**Comment by jimidle** [comment]
Your grammar is erroneous. 

You have a start rule sql_items that terminates with EOF. Then you embed it between BEGIN and END. How can it ever reach 'END' when it is expecting to see EOF first? A rule containing EOF should only ever be a top level rule.

Refactor your grammar, and also do not use 'literals' in your parser. Organize your lexer rules manually and you shoudl get there.

I do not think this is the bug you are reporting but perhaps this kind of thing could be warned about.

I suggest that you close this as a bug and instead take up the topic on the forum, where you can get help with your grammar.

**Comment by SimonStPeter** [comment]
@jimidle you're quite right about the EOF being in the wrong place. That's blatantly wrong and just an foolish oversight by me. 
The literals were just there for this grammar - I took 200k and stripped it down to the core then fed lex tokens back in until it compiled just for reporting this. My main grammar, per your suggestion months ago, has all literals given as lex rules and in a separate file.
I agree about warning about it. I'll close this and open another issue mentioning warning on it.
Thanks.
