### ISSUE TITLE
TokenStreamRewriter for Python

### ISSUE THREAD

**Issue by RedTailedHawk** [antlr/antlr4#1115]
Has any work been done migrating TokenStreamRewriter to Python?  If not, I may have some bandwidth to port it over.  Is there a general estimate you could give as to the level of effort (easy, medium, hard)?

Thanks.
-Larry

**Comment by ericvergnaud** [comment]
Hi,

no work has been done. Not sure about an estimate, but certainly less than a day worth of work.

**Comment by RedTailedHawk** [comment]
OK thanks.  If I get a solid window of time, I'll give it a shot.

**Comment by ericvergnaud** [comment]
:-)

**Comment by lygav** [comment]
@ericvergnaud 
Hello, so i've implemented the TokenStreamRewriter to Python2 run-time.
Please look into PR #1273 
I would very appreciate feedback especially regarding how to integrate with auto generated test suite.
If all goes well i'll expand on this with implementing additional parts for Python2 and Python3 runtimes.

Thanks

**Comment by ericvergnaud** [comment]
@lygav thanks for this, it would indeed be great if you could add some tests, which is now much simpler, see https://github.com/antlr/antlr4/blob/master/doc/adding-tests.md
