### ISSUE TITLE
Rename terminal constants

### ISSUE THREAD

**Issue by msteiger** [antlr/antlr4#1118]
I'm writing a JSON editor that uses the [grammars-v4/JSON.g4](https://github.com/antlr/grammars-v4/blob/master/json/JSON.g4) grammar to extract the syntax tree from the text.

antlr generates a [lexer](https://github.com/msteiger/Json-Eclipse-Plugin/blob/develop/jsonedit-model/src/main/java/com/boothen/jsonedit/antlr/JSONParser.java) and [parser](https://github.com/msteiger/Json-Eclipse-Plugin/blob/develop/jsonedit-model/src/main/java/com/boothen/jsonedit/antlr/JSONLexer.java) that work with int constants of the form `T__0`, `T__1` and so on. I want to assign better names at least for the keywords (`true`, `false`, `null`). For example, `T__6` should become `TRUE`, etc. How would I do that?

* Can I tweak the `JSON.g4` file so that antlr4 does that?
* Can I rename the int constants (and the lexer's `ruleNames` strings) in the lexer/parser without breaking things?

Thanks!

**Comment by KvanTTT** [comment]
Create tokens in this or separated file by the following way:
```ANTLR
TRUE: 'true';
FALSE: 'false';
NULL: 'null';
```
See [Java](https://github.com/antlr/grammars-v4/blob/master/java/Java.g4#L612) grammar for example. Please use stackoverflow.com for questions.

**Comment by msteiger** [comment]
Thanks a lot!
