### ISSUE TITLE
antlr4 goes into infinite loop

### ISSUE THREAD

**Issue by SimonSntPeter** [antlr/antlr4#1122]
Trying to answer issue " Bad parsing of ternary expressions" #1119, got antlr into an endless loop.  
Input is

`3 between 9 and 10 and 4 between 65 and 76`

start parse from 'expression' ie. 

`java org.antlr.v4.gui.TestRig MSSQL expression -gui -trace -tokens`

Code is:

```
grammar MSSQL;

expression :
        disjuncted_search_condition
    ;

disjuncted_search_condition :
        betweener
        (
            or
            betweener
        ) *
    ;

betweener :
        predicate
            betweenness expression and expression
    ;

betweenness : between | not_between ;
not_between : not between ;

conjuncted_search_condition :
        predicate
        (
            and
            predicate
        ) * 
    ;

predicate :
        DECDIGITS
    ;

and : 'and' ;
or : 'or' ;
not : 'not' ;
between : 'between' ;
data_type : 'int' ;
SEMICOLON : ';' ;
as : 'as' ; 
CEQ : '=' ;

DECDIGITS : [0-9]+ ;
sident : '@i' ;
```

output is 

> 3 between 9 and 10 and 4 between 65 and 76
> ^Z
> [@0,0:0='3',<10>,1:0]
> [@1,2:8='between',<4>,1:2]
> [@2,10:10='9',<10>,1:10]
> [@3,12:14='and',<1>,1:12]
> [@4,16:17='10',<10>,1:16]
> [@5,19:21='and',<1>,1:19]
> [@6,23:23='4',<10>,1:23]
> [@7,25:31='between',<4>,1:25]
> [@8,33:34='65',<10>,1:33]
> [@9,36:38='and',<1>,1:36]
> [@10,40:41='76',<10>,1:40]
> [@11,44:43='<EOF>',<-1>,2:0]
> enter   expression, LT(1)=3
> enter   disjuncted_search_condition, LT(1)=3
> enter   betweener, LT(1)=3
> enter   predicate, LT(1)=3
> consume [@0,0:0='3',<10>,1:0] rule predicate
> exit    predicate, LT(1)=between
> enter   betweenness, LT(1)=between
> enter   between, LT(1)=between
> consume [@1,2:8='between',<4>,1:2] rule between
> exit    between, LT(1)=9
> exit    betweenness, LT(1)=9
> enter   expression, LT(1)=9
> enter   disjuncted_search_condition, LT(1)=9
> enter   betweener, LT(1)=9
> enter   predicate, LT(1)=9
> consume [@2,10:10='9',<10>,1:10] rule predicate
> exit    predicate, LT(1)=and
> enter   betweenness, LT(1)=and
> line 1:12 no viable alternative at input 'and'
> exit    betweenness, LT(1)=and
> enter   expression, LT(1)=and
> enter   disjuncted_search_condition, LT(1)=and
> enter   betweener, LT(1)=and
> enter   predicate, LT(1)=and
> consume [@4,16:17='10',<10>,1:16] rule predicate
> exit    predicate, LT(1)=and
> enter   betweenness, LT(1)=and
> line 1:19 no viable alternative at input 'and'
> exit    betweenness, LT(1)=and
> enter   expression, LT(1)=and
> enter   disjuncted_search_condition, LT(1)=and
> enter   betweener, LT(1)=and
> enter   predicate, LT(1)=and
> consume [@6,23:23='4',<10>,1:23] rule predicate
> exit    predicate, LT(1)=between
> enter   betweenness, LT(1)=between
> enter   between, LT(1)=between
> consume [@7,25:31='between',<4>,1:25] rule between
> exit    between, LT(1)=65
> exit    betweenness, LT(1)=65
> enter   expression, LT(1)=65
> enter   disjuncted_search_condition, LT(1)=65
> enter   betweener, LT(1)=65
> enter   predicate, LT(1)=65
> consume [@8,33:34='65',<10>,1:33] rule predicate
> exit    predicate, LT(1)=and
> enter   betweenness, LT(1)=and
> line 1:36 no viable alternative at input 'and'
> exit    betweenness, LT(1)=and
> enter   expression, LT(1)=and
> enter   disjuncted_search_condition, LT(1)=and
> enter   betweener, LT(1)=and
> enter   predicate, LT(1)=and
> consume [@10,40:41='76',<10>,1:40] rule predicate
> exit    predicate, LT(1)=<EOF>
> enter   betweenness, LT(1)=<EOF>
> line 2:0 no viable alternative at input '<EOF>'
> exit    betweenness, LT(1)=<EOF>
> enter   expression, LT(1)=<EOF>
> enter   disjuncted_search_condition, LT(1)=<EOF>
> enter   betweener, LT(1)=<EOF>
> enter   predicate, LT(1)=<EOF>
> exit    predicate, LT(1)=<EOF>
> enter   betweenness, LT(1)=<EOF>
> exit    betweenness, LT(1)=<EOF>
> enter   expression, LT(1)=<EOF>
> enter   disjuncted_search_condition, LT(1)=<EOF>
> enter   betweener, LT(1)=<EOF>
> enter   predicate, LT(1)=<EOF>
> exit    predicate, LT(1)=<EOF>
> enter   betweenness, LT(1)=<EOF>
> exit    betweenness, LT(1)=<EOF>
> enter   expression, LT(1)=<EOF>
> enter   disjuncted_search_condition, LT(1)=<EOF>
> ...and so on forever

Windows 2008 R2, recent version of antr4, not the very latest though (how do I get the version?)

can reproduce?

**Comment by AlexanderMorou** [comment]
Not sure why you're getting an endless loop, but your language never references conjuncted_search_condition as a viable alternative, so the input "3 between 9 and 10 and 4 between 65 and 76" is a valid sub-string of the language, but it won't parse in full.  You notice the 'no viable alt' on the middle 'and' from the text '9 and 10'.  The only valid thing at this point should be 'or', the parse should end once no viable alt is encountered, me thinks, but I'm unfamiliar on end-game conditions with ANLR.

**Comment by SimonSntPeter** [comment]
@AlexanderMorou, thanks for the feedback; the grammar's junk and I know it and probably should have made it clear. I was trying to sort another issue but hit this, dumped .g4 and trace here and hurried on. Didn't mean to waste your time...

**Comment by parrt** [comment]
I can't reproduce. i get:

```
line 1:1 token recognition error at: ' '
line 1:9 token recognition error at: ' '
line 1:11 token recognition error at: ' '
line 1:15 token recognition error at: ' '
line 1:18 token recognition error at: ' '
line 1:22 token recognition error at: ' '
line 1:24 token recognition error at: ' '
line 1:32 token recognition error at: ' '
line 1:35 token recognition error at: ' '
line 1:39 token recognition error at: ' '
line 1:42 token recognition error at: '\n'
[@0,0:0='3',<10>,1:0]
[@1,2:8='between',<4>,1:2]
[@2,10:10='9',<10>,1:10]
[@3,12:14='and',<1>,1:12]
[@4,16:17='10',<10>,1:16]
[@5,19:21='and',<1>,1:19]
[@6,23:23='4',<10>,1:23]
[@7,25:31='between',<4>,1:25]
[@8,33:34='65',<10>,1:33]
[@9,36:38='and',<1>,1:36]
[@10,40:41='76',<10>,1:40]
[@11,43:42='<EOF>',<-1>,2:0]
line 1:12 no viable alternative at input 'and'
line 1:19 no viable alternative at input 'and'
line 1:36 no viable alternative at input 'and'
line 2:0 no viable alternative at input '<EOF>'
```

**Comment by SimonSntPeter** [comment]
@parrt - Token recognition errors at start are caused by me missing the whitespace skipping. Got dropped somewhere along the line, just add 
```
fragment ALLWSes   : [ \t\r\n]+ ;
SKIPWS : ALLWSes -> skip ;
```
to the .g4 file.
But whether it does or doesn't skip whitespaces, it loops anyway for me. Version of antlr I'm on is 4.5.1. You're on 4.5.2? If so, can prob assume it's fixed (perhaps add it to regression tests if applicable).

**Comment by Gui13** [comment]
I have the same issue with another grammar of mine. Should I open another issue or maybe post here?

**Comment by ericvergnaud** [comment]
Hi,

Please discuss this on the Google discussion group.

Eric

**Comment by SimonStPeter** [comment]
@Gui13 when asking questions *please* post *all* of your grammar (or a compilable part thereof) as I had to spend time filling in the gaps and my guess may not even match what you wrote. Anyway, code below parses all your 3 expressions instantaneously. Am using antlr 4.5.1. Code I used is
```
grammar MSSQL;

start_parse: formula EOF;

formula : (expr|boolExpr);

boolExpr
  : bool                                            # booleanExpr
  | l=expr operator=(GT|LT|GEQ|LEQ) r=expr          # boolComparisonExpr
  | l=boolExpr operator=(OR|AND) r=boolExpr         # boolAndOrExpr
  | l=expr (not='!')? EQUALS r=expr                 # boolEqualsExpr
  | l=expr BETWEEN low=expr AND high=expr           # boolBetweenExpr
  | l=expr IS (NOT)? NULL                           # boolIsNullExpr
  | l=atom LIKE regexp=string                       # boolLikeExpr
  | l=atom ('IN'|'in') '(' string (',' string)* ')' # boolInExpr
  | '(' boolExpr ')'                                # boolParensExpr
  ;


bool: 'true' | 'false' ;
string : 'xxxx' ;
atom :  ATOM ;
ATOM : ('-'|'+')? [0-9]+ ('.' [0-9]+)? ;


expr
    : atom                                                 # atomArithmeticExpr
	| '[' identifier ']'								   # dontknowwhatthisis
    | (PLUS|MINUS) expr                                    # plusMinusExpr
    | l=expr operator=(MULT|DIV) r=expr                    # multdivArithmeticExpr
    | l=expr operator=(PLUS|MINUS) r=expr                  # addsubtArithmeticExpr
    | function=IDENTIFIER '(' (expr ( ','  expr )* ) ? ')' # functionExpr
    | '(' expr ')'                                         # parensArithmeticExpr
    ;


PLUS : '+' ;
MINUS: '-' ;

MULT : '*' ;
DIV : '/' ;

GT : '>' ;
LT : '<' ;
GEQ: '>=' ;
LEQ: '<=' ;
EQUALS : '=' ;
BETWEEN : 'between' ;
AND : 'and' ;
IS : 'is' ;
NOT : 'not' ;
NULL : 'null' ;
LIKE : 'like' ;
OR : 'or' ;


identifier : IDENTIFIER ;
IDENTIFIER : [a-zA-Z][a-zA-Z0-9]* ;

SKIPWS : [ \t\r\n]+ -> skip ; 
```

**Comment by jimidle** [comment]
As I answered on the bug report, which I think you should close and pursue
in the forums, your first grammar, assuming it is a complete test case is
erroneous.

You cannot embed a top level rule ending with EOF within the other rules.
That rule is looking for EOF and so it looks roughly like:

*something* BEGIN EOF END EOF

Obviously this does not make any sense. It is probably confusing ANTLR.

Move all your 'literals' to real lexer rules.
If you do need to recursively embed a rule, then it isn't a top level rule,
refactor

top: stuff EOF;

stuff : statementorsomething block* ;

block: BEGIN stuff END ;

...

// Fixed terminals/keywords
BEGIN: 'begin' ;
END: 'end;;

// General..
//
ID: 'A'..'Z'+;

// Fluff
WS: ' ' ->skip() ;

// ERROR
//
ERR: . ;

**Comment by SimonStPeter** [comment]
@jimidle Hi Jim, I think you replied to the wrong issue. I presume you meant #1113

**Comment by parrt** [comment]
I think we fixed this in recent fix for https://github.com/antlr/antlr4/issues/1398
