### ISSUE TITLE
Stable 4.5 Nuget package?

### ISSUE THREAD

**Issue by mattiasnordqvist** [antlr/antlr4#1123]
Will there be a stable nuget release of this https://www.nuget.org/packages/Antlr4/4.5.0-alpha003 any time soon?

**Comment by KvanTTT** [comment]
Moreover there is not latest alpha.

**Comment by sharwell** [comment]
A stable 4.5.3 release is now available through NuGet.

**Comment by mattiasnordqvist** [comment]
Feels like giving birth with 9 months pregnancy. :)

**Comment by sharwell** [comment]
@mattiasnordqvist To be fair, it was released in July. I just missed this issue since it's on the wrong repository. But when I did see it I didn't want to leave you hanging. :)
