### ISSUE TITLE
[Javascript Target] How to get errors and not show in console?

### ISSUE THREAD

**Issue by afucher** [antlr/antlr4#1126]
Hi,

How can I disable the messages in console and get the errors in parser? Just like a "try catch"...

Or I need to implement my own ErrorStrategy to do this?

**Comment by ericvergnaud** [comment]
Hi,

you either need to install your own error listener, or implement your own error strategy.

Eric

**Comment by afucher** [comment]
Ok!

There is any place a documentation of this? Or examples?

**Comment by ericvergnaud** [comment]
This is not the place for support, go to our google antlr discussion group.

**Comment by afucher** [comment]
Sorry, but I just as it because I'm interested tô make some code examples for this if doesn't exist and send a PR... 

But ok, I'm going to Google groups. 

Thks
