### ISSUE TITLE
$stop not available in @after

### ISSUE THREAD

**Issue by gagern** [antlr/antlr4#1129]
The [parser rule attributes](https://github.com/antlr/antlr4/blob/master/doc/actions.md#parser-rule-attributes) documentation claims:

> **`stop` (Token):** The last nonhidden channel token to be matched by the rule. When referring to the current rule, this attribute is available only to the after and finally actions.

But apparently the token is not available even in the `@after` action.

Example:

```
grammar test ;

top
    : e { System.out.println("e.start = " + $e.start + ", e.stop = " + $e.stop); }
    ;

e
    @after { System.out.println("start = " + $start + ", stop = " + $stop); }
    : '(' e ')'
    | OTHER+
    ;

OTHER: .;
```

Running `(1+1)` through the `TestRig` I see

```
start = [@1,1:1='1',<3>,1:1], stop = null
start = [@0,0:0='(',<1>,1:0], stop = null
e.start = [@0,0:0='(',<1>,1:0], e.stop = [@4,4:4=')',<2>,1:4]
```

I observed this in ANTLR 4.5.2 and could reproduce it in a 4.5.3 snapshot based on d0fb48c2b89128158950f4b32a61d50d52d981ea.

**Comment by parrt** [comment]
wow. thanks! looking at PR now.

**Comment by parrt** [comment]
Looks like exitRule() is doing the work:

```
    public void exitRule() {
		if ( matchedEOF ) {
			// if we have matched EOF, it cannot consume past EOF so we use LT(1) here
			_ctx.stop = _input.LT(1); // LT(1) will be end of file
		}
		else {
			_ctx.stop = _input.LT(-1); // stop node is what we just matched
		}
        // trigger event on _ctx, before it reverts to parent
        if ( _parseListeners != null) triggerExitRuleEvent();
		setState(_ctx.invokingState);
		_ctx = (ParserRuleContext)_ctx.parent;
    }
```

but that happens AFTER `@after` actions. Hmm...

**Comment by gagern** [comment]
@parrt: Right. And I'd keep the code in `exitRule` since that's invoked inside the `finally` block, so it remains active in case of an error. Setting the `stop` token twice doesn't hurt. I'm currently using `_input.LT(-1)` as a workaround, after reading that code.

**Comment by parrt** [comment]
ok, i tried altering templates but backed it out. your solution is best!
