### ISSUE TITLE
Add 'Bowtie' separated-by operator to grammar files

### ISSUE THREAD

**Issue by Groostav** [antlr/antlr4#1132]
Hey guys,

when you have the production

``` g4
nonEmptyArgList : argument ( ',' argument )*
```

Which is to say 'arguments separated by commas' or more generally 'one production separated by another production', can we have a special operator for that?

or, in antlr's own case:

``` g4
optionValue
    :   id (DOT id)*

//...

delegateGrammars
    :   IMPORT delegateGrammar (COMMA delegateGrammar)* SEMI

//...

idList
    : id ( COMMA id )* COMMA?
```

you get kind've sick of writing it _...although that last one is funky_

Can you augment your EBNF to support what my compilers class called a bowtie?

These grammars then become

``` g4
nonEmptyParamList : argument ⋈ ','

//...

optionValue
    :   id ⋈ DOT

//...

delegateGrammars
    :   IMPORT delegateGrammar ⋈ COMMA SEMI

//...

idList
    : id ⋈ COMMA COMMA?
```

Needless to say I like unicode grammars although finding a surrogate for the unicode bowtie '⋈' on the standard ascii table might be advisable.

The really nice thing about this is that it alleviates the undue pressure to create a production out of the separatee (bowties left side) in the name of code-clone reduction. I might have the perfectly legal (but kind've ugly) grammar

``` g4
rule: Alpha beta cappa (',' Alpha beta cappa)*
```

to which, anybody in the java community would think 'well we can factor that to'

``` g4
rule: left (',' left)* ;
left: Alpha beta cappa
```

which is correct, but makes your tree deeper. With a bowtie, the pressure to do that is much reduced because you need not copy-paste your left side:

``` g4
rule: (Alpha beta cappa) ⋈ ','
```

Similarly, if you wanted the argument list above to match a zero-argument invocation, then

``` g4
argList: (argument ( ',' argument )* )?
```

_which is pretty messy_

becomes

``` g4
argList: (argument ⋈ ',')?
```

which is a lot nicer :smiley: 

I _believe_ you wouldn't even need to break any existing parser-visitors since you can use the same indexed lists for children of a bowtie as you do now.

Would be nifty!

**Comment by SimonSntPeter** [comment]
Hi, please see ' Allow a rule-delimited lexer and/or parser sequence' #1071 
I agree it's neater but I'm even less convinced of its value now than I was before. YMMV though.

**Comment by parrt** [comment]
Hi. yeah, nice idea but I'll leave as-is.
