### ISSUE TITLE
Allow (re)placing code in the constructor

### ISSUE THREAD

**Issue by gagern** [antlr/antlr4#1133]
Sometimes it would be nice to be able to perform some additional initialization of `@member` variables in the constructor. Perhaps using additional arguments.

One possible solution would be moving [the template line](https://github.com/antlr/antlr4/blob/d0fb48c2b89128158950f4b32a61d50d52d981ea/tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg#L348)

```java
    _interp = new ParserATNSimulator(this,_ATN,_decisionToDFA,_sharedContextCache);
```

from the constructor template into a protected abstract method which gets called by the super constructor. Then you could add an option to not emit a constructor, but instead allow the grammar file to provide one (or multiple) constructors, with whatever arguments, access permissions, `throws` specifications or whatever seem appropriate.

**Comment by parrt** [comment]
Hi. I'm leery of adding more options etc... so I'm going to close but thanks!  Certainly in Java you can use a {...} anonymous constructor in the `@members` section already.

**Comment by gagern** [comment]
An anonymous `{…}` in `@members` can't take constructor arguments into account. So I don't see that as a full-featured solution. Sure, I can work around it somehow, but I still maintain it would have been useful.

GNU Bison has such features using `%lex-param` resp. `%parse-param` directives, in combination with `%code init {…}` resp. `%code lexer {…}` blocks.

**Comment by parrt** [comment]
howdy! I usually just create a subclass of the parser and do whatever I need to do. I try to keep actions out of the grammar anyway so... ;)     Also in general my philosophy at this point is not to mess with ANTLR too much as it's been honed over 25 years, at least in terms of its programmers interface. Any change requires a lot of momentum.

**Comment by JesperGravgaard** [comment]
I have successfully added new constructors with additional parameters directly in the @members section. It works perfectly well.

However, I am not sure if the is considered misuse of @members section. 

```
@parser::members {
    List<String> typedefs;

	public TypedefParser(TokenStream input, List<String> typedefs) {
		this(input);
		this.typedefs = typedefs;
	}

}
```

**Comment by parrt** [comment]
Sounds good to me :)
