### ISSUE TITLE
Document grammar options

### ISSUE THREAD

**Issue by gagern** [antlr/antlr4#1134]
The section [Grammar Options](https://github.com/antlr/antlr4/blob/d0fb48c2b89128158950f4b32a61d50d52d981ea/doc/options.md#grammar-options) states:

> All grammars can use the following options.

But there is no list of options following that paragraph. Looks as though some text got copied from the book, but not enough to make any sense on its own.

**Comment by parrt** [comment]
Saw that too! fixing shortly.

**Comment by parrt** [comment]
Fixed by e4a425321960f0bf4af4f9df313b4fb6ae01254f
