### ISSUE TITLE
Antlr4cs 4.4.3 (C#) throws NullPointerException when compiling XPath grammar (xpath.g4)

### ISSUE THREAD

**Issue by alukyan** [antlr/antlr4#1135]
Development environment details:
Visual Studio 2015
Oracle JRE 8u73

...\packages\Antlr4.4.3.0\build\Antlr4.targets(132,5): error AC0031: ANTLR cannot generate 'org.antlr.v4.codegen.CSharp_v4_5_2Target' code as of version 4.3
...\packages\Antlr4.4.3.0\build\Antlr4.targets(132,5): error AC1000: Unknown build error: Exception in thread "main" java.lang.NullPointerException
...\packages\Antlr4.4.3.0\build\Antlr4.targets(132,5): error AC1000: Unknown build error: 	at org.antlr.v4.codegen.CodeGenerator.getTemplates(CodeGenerator.java:91)
...\packages\Antlr4.4.3.0\build\Antlr4.targets(132,5): error AC1000: Unknown build error: 	at org.antlr.v4.automata.LexerATNFactory.<init>(LexerATNFactory.java:114)
...\packages\Antlr4.4.3.0\build\Antlr4.targets(132,5): error AC1000: Unknown build error: 	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:403)
...\packages\Antlr4.4.3.0\build\Antlr4.targets(132,5): error AC1000: Unknown build error: 	at org.antlr.v4.Tool.process(Tool.java:376)
...\packages\Antlr4.4.3.0\build\Antlr4.targets(132,5): error AC1000: Unknown build error: 	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:343)
...\packages\Antlr4.4.3.0\build\Antlr4.targets(132,5): error AC1000: Unknown build error: 	at org.antlr.v4.CSharpTool.main(CSharpTool.java:59)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by sharwell** [comment]
You are working with a different C# target; it's in the [tunnelvisionlabs/antlr4cs](https://github.com/tunnelvisionlabs/antlr4cs) repository. Support for the C# target you are working with was added in [v4.4.1-alpha001](https://github.com/tunnelvisionlabs/antlr4cs/releases/tag/v4.4.1-alpha001) and then expanded in [v4.5-alpha003](https://github.com/tunnelvisionlabs/antlr4cs/releases/tag/v4.5-alpha003).
