### ISSUE TITLE
Antlr 4 and spring

### ISSUE THREAD

**Issue by tmarcoe** [antlr/antlr4#1141]
I'm writing a web application with a full accounting package. To make it more configurable, I'm doing all of the accounting functions in a 4GL, written in antlr. I developed the language in a separate project and made sure it was working before I integrated it into my web project. The web project works, and the antlr project works. However, when I integrate the 2, none of my autowired beans work, after antlr is called. Everything works fine before that point. 

Is there any issue like that, that you know of?

I can supply code, if you wish.

**Comment by parrt** [comment]
Hmm...what is the issue? error msg?

**Comment by tmarcoe** [comment]
I apologize, the issue was resolved. I found out that I needed to upgrade
my Spring Libraries to a later version. My language actually works very
well now. I can write transaction definitions and/or modify them without
affecting the core language.

Thank you be for getting back to me and thank you for your time.

I absolutely love working in antlr.

**Comment by parrt** [comment]
at your service :)

**Comment by tmarcoe** [comment]
Thank you for being so responsive.
