### ISSUE TITLE
[BUG?] Grammar auto-builds java sources, even when it's not in a source directory

### ISSUE THREAD

**Issue by xoxota99** [antlr/antlr4#1145]
I keep a bunch of .g4 files in a "doc" folder of my project, for referring to. I don't intend for those to generate sources. Despite setting the correct "source" folders in my project settings, the ANTLR tool still generates Java source for any grammars it finds, regardless of their location in the project.

**Comment by parrt** [comment]
Hmm...sounds more like an IDE or build tool issue.

**Comment by xoxota99** [comment]
Yep! Wrong project sorry.
