### ISSUE TITLE
Rules named 'return' generates invalid python2 code

### ISSUE THREAD

**Issue by Wingpad** [antlr/antlr4#1148]
I was building a grammar with a rule called "return" and when I compiled it using the Python2 target it did not catch it as a reserved word and generated the code `def return(self):` which is invalid python syntax. This is an issue since the reserved word `tuple` is caught and the ANTLR target prevents auto-generated code that would otherwise fail.

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/pull/1149
