### ISSUE TITLE
Silently Consuming Original Exceptions

### ISSUE THREAD

**Issue by bahrigencsoy** [antlr/antlr4#1150]
I was trying to write an interpreter-like application when I was stuck with this situation. I was trying to store contexts to be called later with explicit calls to Listener implementation. This bug (feature?) causes the original exception to be swallowed, leaving me in a really confusing situation, trying to figure out the original exception which was consumed silently.

Here is a simplified grammar, tested with `antlr-4.5.2`:

```
grammar ExceptionTest;

nodes: ( a | b | c  )*;

a : 'A' ;
b : 'B' ;
c : 'C' ;
```

And the test code:

```java
public class CorrectExceptionTest {

    static class Listener extends ExceptionTestBaseListener {

        BContext laterContext = null;
        boolean doAssign = true;

        @Override
        public void exitA(AContext ctx) {
            System.out.println("Exit A");
        }

        @Override
        public void exitB(BContext ctx) {
            System.out.println("Exit B");
            if (laterContext == null && doAssign) {
                laterContext = ctx;
                return;
            }
            System.out.println("Throwing exception from exitB()");
            throw new RuntimeException("This is the exception I want to see");
        }

        @Override
        public void exitC(CContext ctx) {
            System.out.println("Exit C");
            if (laterContext == null) {
                throw new RuntimeException("This is not the exception I want to see");
            }
            BContext copy = laterContext;
            laterContext = null;
            doAssign = false;
            exitB(copy);
        }
    }

    @Test
    public void correctException() throws Exception {
        ExceptionTestLexer lexer = new ExceptionTestLexer(new ANTLRInputStream("ABC"));
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        ExceptionTestParser parser = new ExceptionTestParser(tokens);
        parser.addParseListener(new Listener());
        try {
            parser.nodes();
            fail("Expecting exception");
        } catch (RuntimeException ex) {
            System.out.println(ex.getMessage());
            assertEquals("This is the exception I want to see", ex.getMessage());
        }
    }

}

```

And the output, notice that `exitC()` is called twice:

```
Exit A
Exit B
Exit C
Exit B
Throwing exception from exitB()
Exit C
This is not the exception I want to see
````

**Comment by ericvergnaud** [comment]
Hi,

having the parser always ‘successfully’ parse input is a feature, not a bug :-)
if you want to rethrow exceptions rather than let them be swallowed, you need to implement your own error strategy

Eric

**Comment by bahrigencsoy** [comment]
Hi,

I guess I was in a sentimental state when I was stuck in this situation; after all I was trying to implement my own mini-language the whole weekend. :) I have slightly reworded the submission report and will try to come up with a workaround using ErrorStrategy, and then update/close the bug.

**Comment by bahrigencsoy** [comment]
Sorry I couldn't implement a workaround using custom `ANTLRErrorListener` or `ANTLRErrorStrategy` implementations; no one notifies these with the original exception.

The only workaround I can think of is to store exceptions instead of throwing them, but seems like a tedious work. I am leaving the bug submission as-is.

**Comment by ericvergnaud** [comment]
What is wrong is your design, where you want to throw/manage exceptions too early in the process.
You should think of this with at least 2 or 3 phases:
 - parsing the text itself, the expectation is that this will never fail, even if the input incorrect, unless you decide otherwise thanks to a custom error strategy
 - walking the AST, either using a listener or a visitor. Your code is not doing this, so throwing exceptions from code that is never called is unlikely to produce any result.
 - eventually, you would produce a structure out of the AST in phase 2, then you ‘interpret’ it
In terms of you own phased progress, you should start by reading the book.
What your code shows is that you don’t understand haw ANTLR works. 
Filing bugs is not going to help.

**Comment by bahrigencsoy** [comment]
I was aware that this would not be a bug, but decided to fill one instead of asking StackOverflow. I thought that submission would be linked to similar submissions, helping more people, sorry for the inconvenience.

Anyway, your answer helped me correct my code as follows:

```java
    @Test
    public void correctException() throws Exception {
        ExceptionTestLexer lexer = new ExceptionTestLexer(new ANTLRInputStream("ABC"));
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        ExceptionTestParser parser = new ExceptionTestParser(tokens);
        NodesContext nodes = parser.nodes();

        try {
            ParseTreeWalker.DEFAULT.walk(new Listener(), nodes);
            fail("Expecting exception");
        } catch (RuntimeException ex) {
            System.out.println(ex.getMessage());
            assertEquals("This is the exception I want to see", ex.getMessage());
        }
    }
```

Thanks.

**Comment by ericvergnaud** [comment]
the place for support is the google group
filing bugs that you know are not bugs is unfriendly

**Comment by bahrigencsoy** [comment]
If I had been more experienced with antlr, this bug submission could have been an "type:improvement" with probably an accompanying pull request. But again, if I was more experienced with antlr, I wouldn't fall into this pitfall.

I still think there is a room for improvement here, generated code could be more aware of its state and warn user about the unexpected exception it swallows. 

But again, am sorry for inconvenience I caused.
