### ISSUE TITLE
mixfix operators? (operator extensibility)

### ISSUE THREAD

**Issue by dtwelch** [antlr/antlr4#1155]
So after doing some fairly quick searches (perhaps using the wrong terms) I was wondering if it's indeed possible write grammars in antlr4 that allow users to define custom infix operators (something like the technique described here: http://www.cse.chalmers.se/~nad/publications/danielsson-norell-mixfix.pdf)?

So for instance, if a user wanted to define a set containment operator they could do something like this (assuming some syntax)

```
Def. _ '∈' _ : B = ...
```

though perhaps they'd also have to manually supply a precedence number (which is fine)..

Figured before I starting banging my head against the wall too hard on this I'd just ask the devs themselves.. Is there an example of this somewhere using antlr4 that anyone knows about?

**Comment by SimonStPeter** [comment]
As no actual expert has answered it, let a distinctly non-expert try. 
What you're asking is a feature your language provides (viz. extensibility), not built in to your language (ie. have 'element_of' as part of your lang's BNF).  I don't know any way of doing this natively in ANTLR4. It seems deeply unlikely that there is one. As precedence is specified only by explicitly providing an operator in a list of alts, where the order gives the prec ie.
```
expr '*' expr
|
expr '+' expr
```
so * has higher prec than +, it seems even more unlikely. 
I'd suggest, as an ANTLR  noob myself, that you accept expressions as something like
``` expr ( binop_ident expr )*```
and sort out the validity and precedence yourself by looking at 'binop_ident' and manually constructing the tree from that. I suspect it'll get a bit ugly with unary ops unless you enforce brackets around things.
HTH
