### ISSUE TITLE
locateTool in runtime test suite too restrictive

### ISSUE THREAD

**Issue by gagern** [antlr/antlr4#1156]
On my MacPorts system, the python test suite fails to run out of the box because my `python3.5` binary is installed in `/opt/local/bin`, not in `/usr/bin/` or  `/usr/local/bin/` as expected by `BasePythonTest.locateTool`. Can't you use the `PATH` environment variable? Or even better yet, just name the binary and leave it to `ProcessBuilder` to launch the command by name only, using whatever `PATH` convention is to be applied on the current platform?

The `node` locator has a similar issue. But it doesn't throw a `RuntimeException` as the Python version does, but instead throws a `NullPointerException` since `locateTool` there just returns `null` which then is used to construct a `File`. The `csharp` thingy is a bit better on the one hand, since it calls `mono` by name without a path. But on the other hand it's worse since it attempts to locate `xbuild` using those hardwired paths without allowing for a system property override. It looks as though it attempty to run all the tests, but has `null` as the output for each of them. At this point I gave up trying to run the complete suite on my system.

On the whole it would be nice if you could just selectively skip tests for some of these languages, without failing the test phase altogether. Not sure whether Maven/Surefire/Junit is up to that task, though.

**Comment by ericvergnaud** [comment]
The Python tests only fall back to auto resolve location if a property isn't provided, see:
	String propName = getPropertyPrefix() + "-python";
    	String prop = System.getProperty(propName);
 Same for nodejs
Please close this issue.

**Comment by gagern** [comment]
@ericvergnaud: [The docs](https://github.com/antlr/antlr4/blob/14f05bbcc6573dfe8c367df2cf051b79cc1332f6/doc/building-antlr.md#testing-tool-and-targets) say nothing about manually specifying paths for these binaries. Looking at the sources to work out all the names will shut out potential contributors, or will result in untested pull requests. But worst of all, there is no such support for `xbuild`.

If you *really* want to force users into specifying all the binaries manually, then document that properly, make sure it's possible for all binaries, and remove the auto-guessing of paths. Otherwise please reconsider. If you don't have time to implement this, ask for a patch, but don't close until one is donated.

**Comment by gagern** [comment]
I just proposed a patch in #1157, in the hope of increasing the chances that this gets addressed.

**Comment by ericvergnaud** [comment]
I don't want to force users into anything, this is merely for antlr developers and contributors.
We all work for free, so your tone is inappropriate.
Since the issue lies in the docs, I suggest that you propose a fix to the docs (which your PR doesn't provide).

**Comment by gagern** [comment]
I meant the users of the test suite, most of whom would be developers or at least power users of antlr. Sorry if I sounded disrespectful, I didn't mean to. I was just slightly frustrated because I had the impression that an easily fixable problem would remain unaddressed just because a cumbersome workaround already exists.

The issue lies only partly with the docs; the lack of system property override for `xbuild` can't be remedied that way. But you are right, I can include a change to the documentation in addition to the changes already present in my PR. Will do so shortly.

**Comment by WolfgangFahl** [comment]
It would be an advantage if the tests run "out of the box" on more systems. I am also using a Mac with MacPorts and a "mvn test" did not look to work properly since there were assumptions about where files are located that seem not to have been met.

**Comment by WolfgangFahl** [comment]
Given:

Tests run: 1965, Failures: 229, Errors: 392, Skipped: 42
I'd reopen this

**Comment by parrt** [comment]
For now, I improved the doc. https://github.com/antlr/antlr4/commit/06285d16d72763d8f2367e5920a5d198d4f0a0a2
