### ISSUE TITLE
Match empty token at eof

### ISSUE THREAD

**Issue by max4t** [antlr/antlr4#1158]
Hi,

I'm using lexer mode to match strings in my grammar from an example. It looks like this:

``` antlr
QUOTE
 : '\'' -> pushMode(StringMode)
 ;
mode StringMode;
STRING
 : ('\\' ~[\r\n] | ~[\\\r\n'] )+
 ;
STRING_QUOTE
 : '\'' -> type(QUOTE),popMode
 ;
UNTERM_STRING
 : {self._input.LA(1) in [ord('\r'), ord('\n'), Token.EOF]}? -> popMode
 ;
```

For `'stuff\n`, i get the tokens QUOTE, STRING, UNTERM_STRING, NEWLINE
But for `'stuff`, i get QUOTE, STRING. But i expected UNTERM_STRING at the end because the predicate would have been true at the end.
I'm assuming the lexer stopped to look for any new token as soon as it reaches the end of the file

So is it possible de "force" the token UNTERM_STRING to match when EOF is reached?

**Comment by octavian-nita** [comment]
Hi max4t,

First off, I am not convinced this is an issue with ANTLR itself. It looks more like you have a question on how one would implement something using ANTLR... Therefore, I don't think your question qualifies for this section (i.e. as an ANTLR issue / bug) but rather to be posted somewhere here: http://www.antlr.org/support.html

Second, while I am not an ANTLR expert (but have used it on several occasions), when trying to generate a recognizer from your grammar snippet, I get a warning: "non-fragment lexer rule UNTERM_STRING can match the empty string". This might have something to do with your problem -- see here for a simple explanation: http://stackoverflow.com/questions/21420899/antlr-and-empty-strings-contradictory-behavior

However, adding 'fragment' to UNITERM_STRING, we get another warning: 'fragment rule UNTERM_STRING contains an action or command which can never be executed' ...

**Comment by max4t** [comment]
Thanks for the answer. This might not have been the best place to start asking. But I had an underlying question in mind that i should have mentioned. Once the lexer reaches EOF, it stops immediately or it looks for some remaining tokens? Depending on the intended implementation, it can be an issue. I think it could be useful to match some tokens with the intention to match the parser's rules. For instance, the parse match a series of block that ends with a new line, then we may want the lexer to send an extra newline before the EOF to be sure the each block have its newline.

Regarding the warning (which was once an error), it's meant to prevent infinite recursion.

```antlr
UNTERM_STRING
 : {self._input.LA(1) in [ord('\r'), ord('\n'), Token.EOF]}?
 ;
```
In the above example (note the missing `popMode`), an end of line would potentially match indefinitely because it doesn't consume any character so the next one would always be the end of line. But in my case, the action `popMode` prevent the recursion by changing the mode and making it impossible for the lexer to match this token again (unless a similar token exist in the new mode which is not my case). So, in my first example, the warning is not a problem.
