### ISSUE TITLE
Javascript target wiki page

### ISSUE THREAD

**Issue by mikij** [antlr/antlr4#1159]
In README.md of JavaScript runtime I found this link https://theantlrguy.atlassian.net/wiki/display/ANTLR4/JavaScript+Target. But it asks me to login and if I don't have account to contact administrator. What steps I need to do to access this Wiki page?

thanks

**Comment by ericvergnaud** [comment]
Hi
all the docs have moved to GitHub.
Eric

**Comment by BurtHarris** [comment]
I had run into this as well.  Updating the README would help everyone, but I was unsure where to point it to.

**Comment by ericvergnaud** [comment]
The official site is http://www.antlr.org

**Comment by mikij** [comment]
So to conclude this issue all docs that is relevant for JavaScript target is at this url [https://github.com/antlr/antlr4/blob/master/doc/javascript-target.md](url)
