### ISSUE TITLE
Node.js SyntaxError: Unexpected identifier 'boolean' in ANTLR4 JavaScript Lexer

### ISSUE THREAD

**Issue by jj5** [antlr/antlr4#1166]
An issue loading the JavaScript lexer as shown [on StackOverflow](http://stackoverflow.com/questions/36525936/node-js-syntaxerror-unexpected-identifier-boolean-in-antlr4-javascript-lexer).

**Comment by ericvergnaud** [comment]
The ECMAScript.g4 grammar is designed for Java only.
To use it with JavaScript, you need to translate the Java fragments in the grammar to Javascript.

**Comment by jj5** [comment]
Thanks Eric! I've had a go at translating the Java fragments into JavaScript. Seems to work. You can get a copy of the grammar here: [ECMAScript.JavaScriptTarget.g4](https://www.progclub.org/pcrepo/jj5-test/trunk/antlr4-js/ECMAScript.JavaScriptTarget.g4).

**Comment by ericvergnaud** [comment]
Hi,
please feel free to submit a pull request to add this grammar to the directory.
Eric
