### ISSUE TITLE
rule 'program' contains a closure with at least one alternative that can match an empty string

### ISSUE THREAD

**Issue by PUSRISTEK** [antlr/antlr4#1167]
Here is my simple grammar

`grammar ilp;

program
	:	statements+ EOF
	;

statements
	: var_declaration*
	| 'tampilkan' Lparen identifier Rparen Semicolon
	;

var_declaration
	:	primitive_type identifier Semicolon	
	|	primitive_type identifier '=' expression Semicolon	
	|	primitive_type identifier '[' expression ']' Semicolon							
	;
	
expression
	: Num
	| string
	| Decimal
	;

primitive_type
	:	'angka32'
	|	'bita'
	|	'angka64'
	|	'desimal'
	|	'karakter'
	|	'kalimat'	
	|	'logika'
	|	'komposisi'	
	;

identifier
	: Id 
	;

string 
	: '"' (~'"'|'\\"')* '"' 
	;

Semicolon
	: ';'
	;

Lparen
	: '(' 
	;

Rparen
	: ')'
	;

Comma
	: ','
	;

Id
	:	Letter(Letter|Digit)*
	;

Num
	:	Digit
	;
	
Decimal 
	: 	'-'?[0-9]+('.'[0-9]+)? 
	;

fragment 
Digit
	: [0-9]+
	;

Letter
	:	[a-zA-Z]
	;

WS
	:	[  \t\r\n\u000C]+ -> skip ;

LINE_COMMENT
	:	'//' ~[\r\n]* -> skip
	;`

but its give me error. why?
what should i do?

**Comment by KvanTTT** [comment]
You should not use empty alternatives such as `var_declaration*` in rule
```ANTLR
statements
: var_declaration*
| 'tampilkan' Lparen identifier Rparen Semicolon
;
```
Replace it with `var_declaration+` or rewrite rules.
Please, use stackoverflow.com for questinons.

**Comment by PUSRISTEK** [comment]
KVANTTT thankyou so much you save my life :') 
if i have quetion i will email you. its work now :)
i generate for c#

**Comment by jimidle** [comment]
You have specified your 'string' rule as a parser rule, but it should be a
lexer rule. Fix that, then see if you still get the error
