### ISSUE TITLE
Swift target (not yet integrated) doesn't allow ? in rule arg actions

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#1168]
```
classDef returns [var scope: STClass?]
```

gives

```
public  class ClassDefContext: ParserRuleContext {
    weak var host: SmalltalkParser!
    public var scope: ? STClass;
```

but what i really want is:

```
public  class ClassDefContext: ParserRuleContext {
    weak var host: SmalltalkParser!
    public var scope: STClass?;
```

**Comment by janyou** [comment]
Currently, this can only be used:

`classDef returns [STClass scope]`

Because the common template is so defined.
e.g. **test/runtime/templates/CompositeParsers/DelegatorInvokesDelegateRuleWithArgs.stg**:

```
slaveGrammar(grammarName) ::= <<
parser grammar S;
a[int x] returns [int y] : B {<write("\"S.a\"")>} {$y=1000;} ;
>>
```

**Comment by hanjoes** [comment]
I submitted a PR for this a while ago, please check [this](https://github.com/antlr/antlr4/pull/1207/commits/b9f32249179d665ece32cf965a05dceeec468668). Not sure how are the recent changes to ANTLR will work with the change tho, will follow up.

**Comment by sharwell** [comment]
@parrt I expected the original rule in the grammar to appear like this:

```
classDef returns [STClass? scope]
```

In other words, I expected ANTLR grammars to retain prefix typing even when the target language uses postfix typing.

**Comment by parrt** [comment]
all other actions are in target language, such as local var def, though. Hmm...what about other pascal-like languages? If it is ONLY the `?` issue with Swift then maybe we can just use `STClass?` as you say.

**Comment by parrt** [comment]
@hanjoes can we get away with `type var` syntax like @sharwell suggests? Does it translate properly to Swift?

**Comment by hanjoes** [comment]
from the code perspective we can do this, but i feel more consistent if we use the postfix type decl for swift since as you mentioned actions are language specific. Using postfix decl was actually my first hunch when I tried to write a grammar for the swift target, it feels more natural.

**Comment by parrt** [comment]
@hanjoes do you mean `rule[x : STClass?]`?

**Comment by hanjoes** [comment]
yes.

**Comment by parrt** [comment]
my concern was also consistency between parameters and what you can do inside of action. Sam pointed out though that such parameters would not work in his ANTLRWorks2 plug-in because he parses the parameter actions to syntax highlight the argument names. I guess that only matters if (a) you are actually putting parameters into your grammar and you are using that development environment. It's no problem to update the parameter parser in my plug-in.  Hmm...

**Comment by parrt** [comment]
The comment in the code makes it very clear it is language dependent:

```java
/** Parse args, return values, locals
 *
 *  rule[arg1, arg2, ..., argN] returns [ret1, ..., retN]
 *
 *  text is target language dependent.  Java/C#/C/C++ would
 *  use "int i" but ruby/python would use "i".
 */
```

I will proceed with your PR if you can add yourself to the contributors.txt file.

**Comment by parrt** [comment]
@janyou I will have to update the unit tests so they use a template reference to get the appropriate declaration. Something like `rule[<argdef("argname","typename")>]` and then the test rig will do the appropriate replacement, pulling template `argdef` from target.test.stg file.

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/pull/1365
