### ISSUE TITLE
Slow parsing even in SSL mode

### ISSUE THREAD

**Issue by afd** [antlr/antlr4#1169]
Hi

I am using Antlr to parse programs written in GLSL, the OpenGL Shading Language.  As part of a project I am working on, I generate large GLSL shaders that I then need to parse.  My Antlr parser works just fine for small-ish shaders, but is prohibitively slow for large examples.

I have tried using SLL prediction and BailErrorStrategy, as recommended in other posts, but these don't solve the problem.  In my application domain I do expect programs to be syntactically correct.

Can anyone advise me on whether there are other options I could try, or ways in which I could re-structure my grammar to speed things up?

My grammar is attached, as is the file that is slow to parse.

My parser Java-based and I'm using antlr-4.5.3-complete.jar.

Here is the core of my parsing code:

ANTLRInputStream input = new ANTLRInputStream(new FileInputStream(filename));
GLSLLexer lexer = new GLSLLexer(input);
CommonTokenStream tokens = new CommonTokenStream(lexer);
GLSLParser parser = new GLSLParser(tokens);
parser.setErrorHandler(new BailErrorStrategy());
parser.getInterpreter().setPredictionMode(PredictionMode.SLL);
Translation_unitContext ctx = parser.translation_unit();

Thanks in advance for any help

Ally

[GLSL.grammar.txt](https://github.com/antlr/antlr4/files/214719/GLSL.grammar.txt)
[slowtoparse.frag.txt](https://github.com/antlr/antlr4/files/214726/slowtoparse.frag.txt)

**Comment by ericvergnaud** [comment]
Hi
please move this to the google discussion group. This is not the place for support.
Eric

**Comment by KvanTTT** [comment]
Can you please format your grammar and post question in discussion group as @ericvergnaud pointed or on stackoverflow.com?

**Comment by afd** [comment]
Thanks - I posted to the discussion group.  Regarding formatting the grammar - I was not sure what you meant; the grammar file is exactly what I pass to Antlr.  I guess someone in the discussion group will advise on formatting if I'm missing some specific requirement.

Cheers

Ally
