### ISSUE TITLE
ANTLR4 - String Rule To Get Whitespace

### ISSUE THREAD

**Issue by PUSRISTEK** [antlr/antlr4#1173]
i am not experienced and still learning about grammar. i just need an example grammar that support for whitespace and special character like !,",#,$,^,&. Because with my current grammar and the rules inside i cant print out some string that support white space and special symbol. i know whitespace are tossed).

For example if i give input : Hello World!!!!!
the output is HelloWorld <-- the whitespace & char (!) tossed

See this image
[http://i.stack.imgur.com/rDDmg.jpg](url)
why??

here is my current grammar example.g4

`    string
    : '"' (~'"'|'\"')* '"'
    ;

Id
    : Letter(Letter|Digit)*
    ;

Num
    : Digit
    ;

fragment
    Digit
    : [0-9]+
    ;

Letter
    : [a-zA-Z]
    ;

LINE_COMMENT
    : '//' ~[\r\n]* -> skip
    ;`

 i cant understand what happen. i need an advice. thanks.

**Comment by jimidle** [comment]
You are declaring your rule for string as a parser rule. Lexer rules should
begin with UPPER CASE:

STRING : ....

You Letter rules is not a fragment, so it conflicts with Id

You have not specified what to do with whitespace in your lexer, so it will
just not match and give an error.

Find one of the online tutorials, or buy the book, or better still, do both.

Jim

**Comment by PUSRISTEK** [comment]
thanks jim, to share your time for help me. 
okay i am try to change string into STRING to make it become lexer rule and add fragment to Letter.
i will post here for the result.

**Comment by PUSRISTEK** [comment]
JIM THANKSS you save my life.. :') 
now i am under graduate thesis, 
could you share your email jim?
