### ISSUE TITLE
Parsing String or Maybe double Quote Failure in my Grammar

### ISSUE THREAD

**Issue by PUSRISTEK** [antlr/antlr4#1176]
Hello recently i am learning about ANTLR 4. this is great tool to learning about DSL.
My grammar, is work properly if i am added one string for variable declaration but its going messy when i am added two or more string on input. here is my input :
 
```
program sederhana
{
     kelas contoh1
     {
           byte a = 1 + 3 ;
           tampilkan(a);
           string b = "Hello World";
           tampilkan(b);
           string c = "success";
           tampilkan(c);
      }
}
```
And here i was get messy on parse tree : 
![messy](https://cloud.githubusercontent.com/assets/16291319/14578310/c9ab1e82-03ae-11e6-84d2-92cf5e0ed794.png)

 we see clearly when using -tokens 
![bugg](https://cloud.githubusercontent.com/assets/16291319/14578323/7e29e46a-03af-11e6-9ab4-e56e7fb4561b.JPG)

but if iam add one string everythis is going fine, this is another example :
![1](https://cloud.githubusercontent.com/assets/16291319/14578317/478654b6-03af-11e6-8271-e76015b890bc.png)

and here is my grammar :
`grammar ilp;

program
	: program_declaration* EOF
	| statements EOF
	;
	
program_declaration
	: Program identifier Lcurly classes+ Rcurly
	;

classes
	: class_declaration
	; 

class_declaration
	: Kelas identifier Lcurly statements* Rcurly
	;

statements
	: statement+
	;

statement
	: var_declaration
	| func_declaration
	| identifier '=' expression Semicolon
	;

var_declaration
	: primitive_type identifier Semicolon
	| primitive_type identifier '=' expression Semicolon
	| primitive_type identifier '[' expression ']' Semicolon
	;

func_declaration
	:	predefined_fun Lparen identifier Rparen Semicolon
	|	predefined_fun Lparen String (Comma|identifier|Num)* Rparen Semicolon
	;

expression
	: expression op=('*'|'/') expression   # MulDiv
	| expression op=('+'|'-') expression   # AddSub
	| Lparen expression Rparen		       # Parenthesis
	| Num								   # Number
	| String							   # Stringg
	| Decimal							   # Decimal
	;

predefined_fun
	:
	| 'tampilkan'
	| 'tampil'
	;

primitive_type
	: 'int32'
	| 'byte'
	| 'int64'
	| 'float'
	| 'char'
	| 'string'
	| 'bool'
	| 'array'
	;

identifier
	: Id
	;

Program
	: 'program'
	;

Kelas
	: 'kelas'
	;

WS
	: [ \t\r\n\u000C]+ -> skip 
	;

MUL 
	: '*'
	;

DIV 
	: '/'
	;

ADD 
	: '+'
	;

SUB 
	: '-'
	;

Semicolon
	: ';'
	;

Lparen
	: '('
	;

Rparen
	: ')'
	;

Lcurly
	: '{' 
	;

Rcurly
	: '}' 
	;

Comma
	: ','
	;

String
	: '"' (~'"'|'\"')* '"'
	;

Id
	: Letter(Letter|Digit)*
	;

Num
	: Digit
	;

Decimal
	: '-'?[0-9]+('.'[0-9]+)?
	;

fragment
Letter
	: [a-zA-Z]
	;

fragment
Digit
	: [0-9]+
	;
`
i would be happy, if someone can help me to fix this issue and explain me a bit why this is happen. thanks ^_^

**Comment by ericvergnaud** [comment]
Hi,

please move this to the google discussion group.

Eric
