### ISSUE TITLE
 rule has non-LL(*) decision due to recursive rule invocations reachable from alts 

### ISSUE THREAD

**Issue by QRD-RD** [antlr/antlr4#1178]
hi i am beginier at antlr and when i attempt to generate parser i have this errors

[11:49:26] error(211): vv.g:52:3: [fatal] rule Expr has non-LL(_) decision due to recursive rule invocations reachable from alts 1,5.  Resolve by left-factoring or using syntactic predicates or using backtrack=true option.
[11:49:26] error(211): vv.g:1:8: [fatal] rule Tokens has non-LL(_) decision due to recursive rule invocations reachable from alts 2,9.  Resolve by left-factoring or using syntactic predicates or using backtrack=true option.

my grammar 

grammar vv;

StmtBlock
        : '{'  'VariableDecl\* ' Stmt\*  '}'
        ;

Stmt  
       : ( Expr )?  ';' 
       | IfStmt 
       | WhileStmt 
       | ForStmt 
       | BreakStmt 
       | ReturnStmt 
       | PrintStmt 
       | StmtBlock
       ;

IfStmt 
       :  'if' '(' Expr ')' Stmt ( 'else' Stmt )?
       ;

WhileStmt 
       : 'while'  '(' Expr ')'  Stmt
       ;

 ForStmt 
    : 'for' '(' ( Expr )?  ';'  Expr  ';'  ( Expr )?  ')'  Stmt
    ;

ReturnStmt 
        : 'return' ( Expr )?  ';'
        ;   

BreakStmt 
        : 'break'  ';'
        ;

PrintStmt 
        : 'Print'  '(' Expr ( ','Expr )\*  ')' ';' 
        ;

Expr 
    : LValue LFExpr
    | 'Constant' LRExpr
    | 'this' LRExpr
    | 'Call' LRExpr
    | '(' Expr ')' LRExpr 
    | '-' Expr LRExpr

```
| '!' Expr LRExpr
| 'ReadInteger'  '()' LRExpr
| 'ReadLine' '()' LRExpr
| 'new' 'ident' LRExpr
| 'NewArray'  '(' Expr  ','  'Type'  ')'  LRExpr
;
```

LFExpr
    : '=' Expr LRExpr
    | LRExpr
    ;

LRExpr
    : '+' Expr LRExpr
    | '-' Expr LRExpr
    | '*' Expr LRExpr
    | '/' Expr LRExpr
    | '%' Expr LRExpr
    | '<' Expr LRExpr
    | '<=' Expr LRExpr
    | '>' Expr LRExpr
    | '>=' Expr LRExpr
    | '==' Expr LRExpr
    | '!=' Expr LRExpr
    | '&&' Expr LRExpr
    | '||' Expr LRExpr
    |
    ;   

LValue 
    : 'ident' 

```
| 'Constant' LRExpr LFLValue 
| 'this' LRExpr LFLValue 
| 'Call' LRExpr LFLValue 
| '('  Expr ')' LRExpr LFLValue 
| '-' Expr LRExpr LFLValue 
| '!' Expr LRExpr LFLValue 
| 'ReadInteger'  '()' LRExpr LFLValue 
| 'ReadLine' '()' LRExpr LFLValue 
| 'new' 'ident' LRExpr LFLValue 
| 'NewArray'  '(' Expr  ','  'Type'  ')' LRExpr LFLValue 

;
```

LFLValue
    : '.ident'
    | '['  Expr  ']'
    ;

LRLValue
    : '=' Expr LRExpr LFLRLValue

```
| '+' Expr LRExpr LFLRLValue
| '-' Expr LRExpr LFLRLValue
| '*' Expr LRExpr LFLRLValue
| '/' Expr LRExpr LFLRLValue
| '%' Expr LRExpr LFLRLValue
| '<' Expr LRExpr LFLRLValue
| '<=' Expr LRExpr LFLRLValue
| '>' Expr LRExpr LFLRLValue
| '>=' Expr LRExpr LFLRLValue
| '==' Expr LRExpr LFLRLValue
| '!=' Expr LRExpr LFLRLValue
| '&&' Expr LRExpr LFLRLValue
| '||' Expr LRExpr LFLRLValue

| '.ident' LRLValue

| '[' Expr ']' LRLValue

|
;
```

LFLRLValue
    : '.ident' LRLValue
    | '['  Expr  ']' LRLValue
    ;       

how i can solve this errors
any helping please
thanks

**Comment by ericvergnaud** [comment]
Hi 
Please move this to the Google discussion group
Eric

Envoyé de mon iPhone

**Comment by QRD-RD** [comment]
thanks

**Comment by parrt** [comment]
that error is from version 3 not 4. it is not a bug but a question. do not ask questions here.
