### ISSUE TITLE
[antlr4.5.3]Semantic predicate fails to turn off the alternative of rule

### ISSUE THREAD

**Issue by danielsun1106** [antlr/antlr4#1179]
Here is the test case, which is modified from a Hello sample:
**fails to recognize "hello world"**
```antlr
grammar Hello;

s  : r EOF;
r  : 'hello' ID 
   | {false}? 'hello' 'world';

ID : [a-z]+ ;
WS : [ \t\r\n]+ -> skip ;
```

I turn off  the rule alternative by semantic predicate{false}? :
```antlr
{false}? 'hello' 'world'
```

but antlr4 fails to recognize the input text:
```plain
hello world
```
**error message:** line 1:0 no viable alternative at input 'hello'

What I expect is antlr4 can use the first alternative('hello' ID) to recognize the input text"hello world"
```plain
'hello' ID
```

**When the alternative is removed, antlr4 can recognize "hello world" sucessfully.**
```antlr
grammar Hello;

s  : r EOF;
r  : 'hello' ID;

ID : [a-z]+ ;
WS : [ \t\r\n]+ -> skip ;
```

**Comment by ericvergnaud** [comment]
Hi,

please move this to the google discussion group.

Eric

**Comment by danielsun1106** [comment]
OK, thanks.

**Comment by danielsun1106** [comment]
Eric's answer is here: https://groups.google.com/forum/#!topic/antlr-discussion/na4l09J4MFA
