### ISSUE TITLE
antlr4cpp CMake?

### ISSUE THREAD

**Issue by realms50** [antlr/antlr4#1180]
@DanMcLaughlin

For some reason there is no issue tracker for https://github.com/DanMcLaughlin/antlr4cpp, so I'm going to add them here until that changes.

OK. The issue is this: the antlr4cpp repo seems to going in the CMake direction, but only for Linux. I suggest that CMake also be used for other platforms. Many people use CLion instead of Xcode on OS X these days. With CMake, what IDE you're using doesn't matter.

**Comment by DanMcLaughlin** [comment]
Because I closed the issues for antlr4cpp as it's no longer active, instead opening one on my antlr4 fork. 

On this topic please feel free to contribute cmake support yourself :)

**Comment by DanMcLaughlin** [comment]
Also please close this issue as it doesn't belong on the main antlr4 repo
