### ISSUE TITLE
Misused EOF causes ANTR4 confusion: possibly detect and report instead.

### ISSUE THREAD

**Issue by SimonStPeter** [antlr/antlr4#1181]
In issue #1113 @jimidle pointed out the flaw as being an EOF used in a rule which was called from elsewhere. This was a simple oversight by me, not a misunderstanding of how to use EOF.
Perhaps antlr can check for this? Suggestion:
1. ensure EOF occurs in exactly one rule
2. that rule is not called recursively (it can be called by other rules as this is reasonable `parse: getheader getbody getpostscript ;` where `getpostscript` can contain the EOF).
Maybe this will prove too constraining, I don't know.

**Comment by sharwell** [comment]
The specific analysis of interest would be detecting cases where a non-EOF transition can appear after an EOF transition (in the follow set). However, even if detected this is not necessarily an error (see below).

Note to potential implementers: I've noticed some anomalies in the LL(1) static analysis so I'm not sure the existing code can be used as-is for this purpose.

Interesting additional things to note:

1. EOF can occur in more than one rule
2. EOF does not have to be the last terminal matched - specifically an EOF can appear after another EOF as in #531, #534, #535, #537, #539
3. EOF can appear in the middle of certain rules, such as the following (from [TemplateLexer.g4](https://github.com/tunnelvisionlabs/antlrworks2/blob/master/org-antlr-works-editor/src/org/antlr/works/editor/st4/experimental/TemplateLexer.g4)):

    ```antlr
    TemplateExpression_STRING
        :   '"' (~('"' | '\\') | '\\' (. | EOF))* '"' -> type(STRING)
        ;
    ```

**Comment by parrt** [comment]
@sharwell can you remember what the LL(1) anomalies were related to? I can poke around.
