### ISSUE TITLE
update npm package to version 4.5.3

### ISSUE THREAD

**Issue by maiermic** [antlr/antlr4#1182]
@ericvergnaud Please update the [antlr4 npm package](https://www.npmjs.com/package/antlr4) from 4.5.2 to version 4.5.3

[**How do I get the runtime in Node.js?**](https://github.com/antlr/antlr4/blob/master/doc/javascript-target.md#how-do-i-get-the-runtime-in-nodejs) is outdated, too.

**Comment by ericvergnaud** [comment]
done
please propose an updated doc :-)
