### ISSUE TITLE
feature - native support by antlr for scala / swift targets

### ISSUE THREAD

**Issue by johndpope** [antlr/antlr4#1184]
Swift target here
https://github.com/janyou/ANTLR-Swift-Target

I know Brian Kent has this branch here - but I couldn't get it to work. 
https://github.com/bdkent/antlr4-scala-target-example

**Comment by ewanmellor** [comment]
Swift support (derived from janyou's branch above) is in master now.

**Comment by parrt** [comment]
Fixed in 4.6 release :)

**Comment by johndpope** [comment]
nice.
