### ISSUE TITLE
Is it possible to add TOKEN automatically if conditional Token is absent

### ISSUE THREAD

**Issue by konopiux** [antlr/antlr4#1191]
`lessExpression: attribute lt dr=value? {if($ctx.dr==null) "somehow add predefined value to expression" };`

If it is possible that when I enter:
"attr < 5" in java tree visitor I will get `5` when visiting valueContext, but
"attr < " will still visit valueContext, but with value `?`.

is it possible to make such condition in rule file?

**Comment by ericvergnaud** [comment]
Hi,

please close this and ask this question on the google discussion group.

Eric
