### ISSUE TITLE
unused import warnings for generated imports specified in header

### ISSUE THREAD

**Issue by arifogel** [antlr/antlr4#1192]
If I put a java import in a grammar header, then the generated listener files also contain those imports. Thus they get unused import warnings. One easy fix would be to put @SuppressWarnings("unused") right above the class declaration in generated listener classes.

**Comment by arifogel** [comment]
Wait never mind that causes a separate warning if there are no unused imports. Perhaps antlr4 could be smart about imports in the header by simply not including them? They aren't actually necessary in the listener files; they are only needed in the generated parser/lexer.

**Comment by parrt** [comment]
Hi. I'm going to  close this as I don't think I will get around to any kind of fix. thanks anyway.
