### ISSUE TITLE
Installation over http is unsafe

### ISSUE THREAD

**Issue by cpitclaudel** [antlr/antlr4#1193]
Hi,

ANTLR looks great, but the recommended download happening over HTTP is a bad idea, isn't it?

For the home page:

```
curl -O http://www.antlr.org/download/antlr-4.5.3-complete.jar
```

**Comment by ericvergnaud** [comment]
Hi,

please move this discussion to the google discussion group.

Eric

**Comment by cpitclaudel** [comment]
AFAICT the issue persists. What was there to discuss?

**Comment by parrt** [comment]
I don't understand. antlr is a public library not your bank statement. who cares about https?

**Comment by cpitclaudel** [comment]
I'm not worried about privacy, I'm worried about integrity.  As it stands, there's no way for me to ensure that the binaries I download from ANTLR's website aren't tampered with.

An alternative to HTTPS is listing checksums for the download on a secure page.

**Comment by parrt** [comment]
I see. Maybe using maven uses https.

**Comment by cpitclaudel** [comment]
Probably! I'm not very familiar with Maven.

There's another, very simple solution.  Instead of suggesting to download a file from antlr's HTTP servers (http://www.antlr.org/download/antlr-4.5.3-complete.jar), you could point to a GitHub release.

**Comment by parrt** [comment]
Howdy! I deployed a snapshot and it has hash. these are the individual jars though: https://oss.sonatype.org/content/repositories/snapshots/org/antlr/antlr4/4.6-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/org/antlr/antlr4-runtime/4.6-SNAPSHOT/

**Comment by cpitclaudel** [comment]
Yay, thanks so much! I imagine you'll update the home page after the next release?
Thanks again for fixing this issue :) (and for the cool work on ANTLR, of course)

**Comment by parrt** [comment]
Yep, note that I can't guarantee my machine isn't hacked so you might still be getting corrupt software ;)  

Regardless, I think you'll find ANTLR a pleasure to use as a parser generator.

**Comment by cpitclaudel** [comment]
That's a risk I'll take :) ANTLR is a breautiful piece of software; thanks so much!
