### ISSUE TITLE
Any way for lexers to match against Unicode categories like Lu?

### ISSUE THREAD

**Issue by willfaught** [antlr/antlr4#1196]
Distinguishing between upper and lowercase Unicode letters for languages like Haskell and Go (for example) would be really useful. The `..` range operator is insufficient, as these categories are multiple ranges with "holes" in between.

**Comment by grosenberg** [comment]
Look at https://github.com/antlr/grammars-v4/blob/master/stringtemplate/LexUnicode.g4

**Comment by willfaught** [comment]
@grosenberg Thanks!
