### ISSUE TITLE
the line number of token is error

### ISSUE THREAD

**Issue by todylu** [antlr/antlr4#1197]
I have a file, there are "0D 0D 0A" (\r\r\n) at the end of each line. Editor tool(Nodepad++) regards it as two lines, but from 'ANTLR' point view, this is one line.

How to change ANTLR to follow editor tool rule. (the version of ANTLR is 4.5.3)

**Comment by ericvergnaud** [comment]
Hi,

please move this question to the google discussion group.

Eric

**Comment by todylu** [comment]
OK, I have posted it to google "antlr-discussion" group. please close the issue.
