### ISSUE TITLE
Build fails with LANG={POSIX,C} (docker)

### ISSUE THREAD

**Issue by wjkohnen** [antlr/antlr4#1200]
After the good news of #659 I've had a very hard time to merge ANTLR's build dependencies into my Go development docker image. 

Building "ANTLR 4 Tool" failed with: 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project antlr4: Compilation failure: Compilation failure:
[ERROR] /tmp/antlr4/tool/src/org/antlr/v4/analysis/AnalysisPipeline.java:[103,62] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /tmp/antlr4/tool/src/org/antlr/v4/analysis/AnalysisPipeline.java:[103,63] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /tmp/antlr4/tool/src/org/antlr/v4/analysis/AnalysisPipeline.java:[103,64] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /tmp/antlr4/tool/src/org/antlr/v4/analysis/LeftRecursiveRuleAnalyzer.java:[333,28] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /tmp/antlr4/tool/src/org/antlr/v4/analysis/LeftRecursiveRuleAnalyzer.java:[333,29] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /tmp/antlr4/tool/src/org/antlr/v4/analysis/LeftRecursiveRuleAnalyzer.java:[333,30] error: unmappable character for encoding ASCII
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :antlr4
```

It took me quite a detour, but finally I've figured that the Ubuntu docker images don't have any UTF-8 locales installed by default, so LANG, LC_\* are set to POSIX. This is my workaround:

```
RUN locale-gen en_US.UTF-8
RUN dpkg-reconfigure locales
ENV LANG=en_US.UTF-8
```

After I've successfully compiled ANTLR, double checks with LANG=C and LANG=POSIX (with UTF-8 locales available) comfirmed above error. The quoted error is triggered by non-ASCII characters in source code comments. But it would also fail with non-ASCII string literals (I don't remember where). 

IMHO the build should be env independent, but I wouldn't mind if this (closed) issue would sit here as a future reference. I am curious though, why does this fail even with `<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`!? 

Oh, by the way: If you try to build ANTLR within a docker image, take Ubuntu Trusty. Don't waste your time with Debian Jessie, Ubuntu Precise (the default OS image of travis-ci) or Ubuntu Xenial.

**Comment by ericvergnaud** [comment]
Looks like this is actually a general Java issue, not an ANTLR one, see for example
http://stackoverflow.com/questions/9811382/compiling-javac-a-utf8-encoded-java-source-code-with-a-bom

**Comment by wjkohnen** [comment]
That is actually not related. Java treats the BOM as part of the compilation unit (which it shouldn't) and as such it is illegal. Encodings don't matter at that point. 

This issue is about UTF-8 characters where they are a legal part of the source code. Just somehow `javac` does not always get the `-encoding` option, although Maven has been configured to do that. Or not.

**Comment by ericvergnaud** [comment]
I meant it relates to the wrong reading of encoding of source files by javac, not to antlr.

**Comment by wjkohnen** [comment]
This matter is confusing and I spent _too_ _much_ _time_ on it. :)

**Comment by parrt** [comment]
@wjkohnen what can I do to help? something i can add to pom.xml?

**Comment by wjkohnen** [comment]
It builds successfully now. I think the new test templating solves this? 

Tested with https://hub.docker.com/r/wjkohnen/gopherbase/ (github.com/wjkohnen/dkr-gopherbase), setting 'LANG' to 'C' and maven starget 'install'.

**Comment by parrt** [comment]
hooray! thanks.
