### ISSUE TITLE
Duplicate lex/parse rules don't cause problems or warnings in imported files

### ISSUE THREAD

**Issue by SimonStPeter** [antlr/antlr4#1202]
Trivial to reproduce, bung the following in an imported file (specifically, a file that is included by `import someotherfile;` into an antlr grammar file)

```
fragment XX : [aA] ;
fragment XX : [aA] ;

HELLO : 'hello' ;
HELLO : 'hello' ;

hello: HELLO ;
hello: HELLO ;
```

Is this a byproduct of included files silently overriding rules in the file into which they are imported? 
Antlr version 4.5.3, running on windows

**Comment by ericvergnaud** [comment]
Hi,

there is indeed a byproduct of rules in a grammar overriding rules of an imported grammar.
however I believe having duplicate rules in any grammar should raise errors.

Eric

**Comment by KvanTTT** [comment]
Maybe something like `override` modifier should be used?
