### ISSUE TITLE
<type 'exceptions.UnicodeDecodeError'>

### ISSUE THREAD

**Issue by akashdepth** [antlr/antlr4#1208]
I am using antlr in python.

java -jar antlr-jar-file  dlanguage=python2 java8.g4

shows error message in grammar.i fixed it after it in Java8Lexer.py it show (char) undefined  i change it to chr and fixed it also.

but when running it for my file it shows.I think it is unable to reading copyright symbol

('Unexpected error:', <type 'exceptions.UnicodeDecodeError'>)

**Comment by ericvergnaud** [comment]
Hi,
this is not the place for support.
please move this to the google discussions group.
Eric
