### ISSUE TITLE
Unresolvable ambiguity when parsing expression: (1 = 2 + 3)

### ISSUE THREAD

**Issue by Endeavourl** [antlr/antlr4#1209]
Note: this issue is for tracking purposes of a bug report i privately sent to @parrt and @sharwell because the only reproduction i have is using my private grammar files.

Short version of that bug report is that in my grammar for PostgreSQL SQL flavor there's an ambiguity when parsing expression (1 = 2 + 3) (outer parens matter and equals sign is comparison operator).
Or, more generally, any expression of the form (X op1 Y op2 Z) results in ambiguity, where precedence of op1 < op2, and op2 is a binary operator that has an unary prefix version, X Y Z are arbitrary expressions, and again, outer parens do matter.
Grammar expression rules are written using left-recursion form.

I believe this is a bug because:
a) I'm close to absolutely sure that there are no ambiguity in the grammar after days of checking and rechecking;
b) I couldn't reproduce the bug by moving relevant or even _all_ required rules to a separate grammar. Even worse, the bug may or may not show itself depending on the order in which i comment out rules/alternatives from the main grammar file.
I won't go into specifics with rule names etc here since it won't make sense without my grammar files. My private bug report should contain plenty.

**Comment by SimonStPeter** [comment]
@Endeavourl: Interesting. I've had some very odd bugs caused by my accidental misuse of EOF (giving rise to #1113 leading to #1181), and some reports of errors far distant from their real cause when accidentally introducing empty options, but not this. I really doubt I can help, but just an "is borked" notice isn't useful - can you give any more info like a stack trace, the error message or anything? Also do please check it's not related to the issues I mention above.

**Comment by parrt** [comment]
I'd love to track this down.

**Comment by SimonStPeter** [comment]
@Endeavourl : hi, any progress on this?

**Comment by parrt** [comment]
nope. sorry.

**Comment by Endeavourl** [comment]
@SimonStPeter sorry had a very busy couple of weeks
I do use EOFs but they're limited to "entry point" rules that aren't called from anywhere. On a quick glance, issues you linked were caused by rules predicting EOF in the middle of input. I don't believe that's the case with my rules.

Some more info about my issue... Well, just to give you a general idea, buggy rules look like this
```antlr
test_entry : vex EOF;  
vex
  : '(' vex ')'
  | <assoc=right> ('+' | '-') vex
  | vex ('+'| '-') vex
  | vex '=' vex
  | value_expression_primary
  ;
value_expression_primary
  : // a bunch of elementary expression parts alternatives
  ;
```
The weirdest part is that `primary`'s contents don't really matter here, because depending on the order in which you add/remove them the ambiguity may or may not appear for identical rules.
I. e., i can replace `primary` with `literal` and it works fine, no ambiguity. Then i use `primary` again, do some commenting inside it to localise cause, get bizarre results, replace `primary` with `literal` again this time - and ambiguity stays. This is why i believe that this is a bug, clearly this shouldn't be happening.

I don't have any stacktraces because, as i said, it's an ambiguity. It is reported both by IDEA plugin's profiler and by `reportAmbiguity` method of a custom error listener.
I don't know what else i can post since this issue is only reproducible using my grammar files and i can't post those. I guess i could post `reportAmbiguity` argument dumps but i'm not sure how much help it would do since you can't repro and debug this anyway.

@parrt wait... you couldn't repro this using files from my email or something? I don't understand why you close this so early. I thought having a working debuggable repro would help a lot for someone who knows where to look (unlike me).

**Comment by parrt** [comment]
ooops.  didn't mean to close I hit the wrong button.

**Comment by SimonStPeter** [comment]
@Endeavourl : We're all busy, no worries... 
the EOF problem was me not ANTLR, and if you're sure it's not that then good, one less to worry about. The empty alts were another cause of baffling behaviour - what exaclt is the error message you're getting?
I'll try to look at it but starting job soon and have a mountain of learning nto do, so very tied up.
Doubt I can help, just trying to eliminate the obvious.
@parrt : my question was aimed at Endeavourl, honestly I was not trying to hassle you.

**Comment by parrt** [comment]
Note to self: See email from Alexander Fri, 20 May 2016 14:44:27 +0300 Subject: Weird behaviour/bug in ANTLR4

**Comment by parrt** [comment]
Ok, I'm now working on this bug. Any chance you have a small(er) grammar and some input that exhibits the problem?

**Comment by parrt** [comment]
@Endeavourl I see input `(1=2+3)` gives ambiguity as you say. ANTLR plugin for intellij shows two interpretations:

<img width="1042" alt="screen shot 2016-11-07 at 9 30 06 am" src="https://cloud.githubusercontent.com/assets/178777/20068296/063bd1d8-a4cd-11e6-941a-29227e89365e.png">

The tree on left is the one chosen, which is correct. `+` has higher precedence than `=` so all is well. Any grammar for expressions is ambiguous. I don't see a problem here.

**Comment by Endeavourl** [comment]
I thought that the order of alternatives in `vex` would give them strict precedence thus ruling out the second variant where `EQUAL` has higher precedence than `PLUS`. Did i misunderstand how this should work?

As for smaller grammar, as i said, i tried to minimize it and the ambiguity wouldn't reproduce that way. Even with full grammar the ambiguity is not easily reproduced and can appear and disappear with arbitrary changed (which is also indicative of some kind of a bug, IMO).
You should be able to remove all the unrelated rules for SQL CREATE statements but with this kind of unstable behaviour i'm not sure about it.
I'll try to minimize the grammar somewhat while also keeping the ambiguity sometime this week.

**Comment by parrt** [comment]
You are correct, precedence *resolves* the ambiguity but you cannot remove a grammar ambiguity for *language* ambiguity.

Unless there is another issue, I'll close ok?

**Comment by Endeavourl** [comment]
Ok, i think i get what you're saying.
Anyway, you're the expect here and i'm really not, so close it if this works as intended.

Still, have you considered the way it (almost) randomly does or doesn't report the ambiguity for the same input? Or the way ambiguity disappears on the same vex rule just moved to a separate grammar? This behaviour seems very suspicious to me but maybe i just don't get something.
Either way, thanks for looking into this.

**Comment by parrt** [comment]
Hmm...well, changing the grammar can introduce/remove ambiguity very easily so I'll call this intended behavior. thanks for the excellent report though!
