### ISSUE TITLE
PHPLexer.py not completely translated to Python2 target (Java fragments remain)

### ISSUE THREAD

**Issue by in-the-name-of-science** [antlr/antlr4#1220]
When I follow the instructions to create a Lexer/Parser in the Python language I get the following error when trying to invoke the generated PHPLexer.py:

```
Traceback (most recent call last):
  File "Test-ANTLR.py", line 2, in <module>
    from PHPLexer import PHPLexer
  File "/home/test/PHPLexer.py", line 1456
    public bool AspTags = true;
              ^
SyntaxError: invalid syntax
```

It would appear that Java language has made it into my Python file during the Lexer/Parser generation.

Here are the steps I took to generate the Lexer/Parser:
1. Downloaded the v4 grammars:
   `git clone https://github.com/antlr/grammars-v4.git`
2. Configured ANTLRv4 for my Ubuntu system (following [these](https://github.com/antlr/antlr4/blob/master/doc/getting-started.md) instructions). The example grammar works as expected.
3. Copied the PHP grammars into my local directory
4. Generated the Lexer using the php/PHPLexer.g4 grammar from the repo:
   `antlr4 -Dlanguage=Python2 PHPLexer.g4`
5. Generated the Parser using the php/PHPParser.g4 grammar from the repo:
   `antlr4 -Dlanguage=Python2 PHPParser.g4`

at this state I now have the following generated files:

```
-rw-rw-r-- 1 mark mark  19109 Jun 27 10:00 PHPParser.g4
-rw-rw-r-- 1 mark mark  15099 Jun 27 10:32 PHPLexer.g4
-rw-rw-r-- 1 mark mark 103727 Jun 27 10:32 PHPLexer.py
-rw-rw-r-- 1 mark mark   4877 Jun 27 10:32 PHPLexer.tokens
-rw-rw-r-- 1 mark mark 576964 Jun 27 10:33 PHPParser.py
-rw-rw-r-- 1 mark mark  35642 Jun 27 10:33 PHPParserListener.py
-rw-rw-r-- 1 mark mark   4877 Jun 27 10:33 PHPParser.tokens
```

Using the example code from the Python targets I use the following code:

```
from antlr4 import *
from PHPLexer import PHPLexer
from PHPParser import PHPParser

def main(argv):
    input = FileStream(argv[1])
    lexer = PHPLexer(input)
    stream = CommonTokenStream(lexer)
    parser = PHPParser(stream)
    tree = parser.StartRule()

if __name__ == '__main__':
    main(sys.argv)
```

However the error is generated when importing the PHPLexer since there is invalid Python code inside of PHPLexer.py:

```
Traceback (most recent call last):
  File "Test-ANTLR.py", line 2, in <module>
    from PHPLexer import PHPLexer
  File "/home/test/PHPLexer.py", line 1456
    public bool AspTags = true;
              ^
SyntaxError: invalid syntax
```

Please advise.

**Comment by KvanTTT** [comment]
PHP parser contains code actions because of case sensitivity and now it's working only for C# runtime.
For Pyhon, Java or JavaScript runtimes grammar should be refined.

**Comment by KvanTTT** [comment]
@in-the-name-of-science if you are still interested, a new PHP grammar with python runtime is available on official repository: https://github.com/antlr/grammars-v4/tree/master/php
