### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by RobertPastor** [antlr/antlr4#1222]
Dear Sir,

I am using the Oracle PLSQL g4 grammar available from here:
https://github.com/antlr/grammars-v4/tree/master/plsql 

The code is generated (using antlr-4.5.3-complete.jar) for a Python 2 target.
-visitor -Dlanguage=Python2

With the attached SQL test file : PCR In Out Detected Release.sql
It appears that - using the traces - the analyzer freezes (several times) around the following rule
enter   table_ref_aux, LT(1)=(

Hence it takes more than 50 seconds to parse it.
conditions are : 
1) parser._interp.predictionMode = PredictionMode.LL
2) usage of a specific error listener

I have also tried :
1) the two level stages (SLL then LL) parsing without conclusive results.
2) PredictionMode.LL_EXACT_AMBIG_DETECTION 
Could you help ?
Thanks in advance
Robert

[PLSQL Test file.sql.txt](https://github.com/antlr/antlr4/files/339507/PLSQL.Test.file.sql.txt)

**Comment by ericvergnaud** [comment]
Hi,

please open a thread on the google discussion group.
this is not the place for support.

Kind regards,

Eric

**Comment by kkbkris** [comment]
Dear Sender at GitHub Support,

Thank you for your message.

Where do we post support questions?

Yours sincerely and many thanks,
Kristian Robert David Stacey,
Former Student and Undergraduate Reading Computer Science and Electronics Master Degree in Engineering and Masters Degree in Science Joint Honours. @ University of Bristol



On 29 Jun 2016, at 17:40, "ericvergnaud" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

please open a thread on the google discussion group.
this is not the place for support.

Kind regards,

Eric

> Le 29 juin 2016 ? 16:57, Robert <notifications@github.com<mailto:notifications@github.com>> a ?crit :
>
> Dear Sir,
>
> I am using the Oracle PLSQL g4 grammar available from here:
> https://github.com/antlr/grammars-v4/tree/master/plsql <https://github.com/antlr/grammars-v4/tree/master/plsql>
> The code is generated (using antlr-4.5.3-complete.jar) for a Python 2 target.
> -visitor -Dlanguage=Python2
>
> With the attached SQL test file : PCR In Out Detected Release.sql
> It appears that - using the traces - the analyzer freezes (several times) around the following rule
> enter table_ref_aux, LT(1)=(
>
> Hence it takes more than 50 seconds to parse it.
> conditions are :
> 1) parser._interp.predictionMode = PredictionMode.LL
> 2) usage of a specific error listener
>
> I have also tried :
> 1) the two level stages (SLL then LL) parsing without conclusive results.
> 2) PredictionMode.LL_EXACT_AMBIG_DETECTION
> Could you help ?
> Thanks in advance
> Robert
>
> PLSQL Test file.sql.txt <https://github.com/antlr/antlr4/files/339507/PLSQL.Test.file.sql.txt>
> -
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <https://github.com/antlr/antlr4/issues/1222>, or mute the thread <https://github.com/notifications/unsubscribe/ADLYJPkkt4W5Tce_80WQLda11WEFfRWAks5qQoftgaJpZM4JBOdr>.
>


-

**Comment by ericvergnaud** [comment]
https://groups.google.com/forum/#!forum/antlr-discussion

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/commit/fca5e458d3cbbc0d24fbefd2e6ac47569d479afa
