### ISSUE TITLE
Actions for Javascript

### ISSUE THREAD

**Issue by ghosthope** [antlr/antlr4#1225]
Hey. I use ANTLR to write a parser to Javascript. And I want to use an action on Javascript. But when you write action, for example,
`flag: WSS * AT_SIGN dText LINE | WSS * AT_SIGN dText EOF {alert ( "!!!");};`
project returns a compilation error. However, if you write
`flag: WSS * AT_SIGN dText LINE | WSS * AT_SIGN dText EOF {System.out.println ( "!!!");};`
compilation is successful and the output is javascript code, but the code to insert System.out.println ( "!!!");

Javascript code is not supported by actions?

**Comment by KvanTTT** [comment]
What compilation error was returned in the first case?

**Comment by ericvergnaud** [comment]
Hi,
this is not the place for support.
Please move this to the Google discussion group.
Eric

Envoyé de mon iPhone
