### ISSUE TITLE
Grammar with BailErrorStrategy accepts invalid input (extra semicolon)

### ISSUE THREAD

**Issue by DavidBiesack** [antlr/antlr4#1226]
I have a grammar with a `start` rule that parses an `expression` followed by `EOF`. For this bug report I simplified the `expression` grammar to just the `name` rule.

``` ANTLR
start : expression EOF ;
expression  :  name    ;
PERIOD                    : '.';
name  :  identifier ( PERIOD identifier )* ;

identifier : ID ;
// etc
```

I configure the parser with `BailErrorStrategy` -- I do not want to allow any input which is not matched, so no automatic recovery. The test cases verify that some invalid inputs do not parse, such as 

```
a.b.
.abc
```

etc.

However the input

```
a;
```

is accepted and should not be. The semicolon should not be allowed. ANTLR ignores it.

The grammar and JUnit test and Gradle build are in the attached tar file. To build/test, extract the zip
[antlr.defect.zip](https://github.com/antlr/antlr4/files/346998/antlr.defect.zip)
 file, cd into the source directory and run the tests using Gradle. (You can also run your own install of `gradle` instead of `gradlew` if you prefer.)

```
   unzip antlr.defect.tar
   cd antlr.defect
  ./gradlew test  # or gradle test to run your own install of gradle


```

the build fails. open `build/reports/tests/index.html` to see the error:

```
Caused by: java.lang.AssertionError: 2: ** No parse failure on input 'a;' (invalid name)
```

This is running ANTLR 4.5.3 (see the `build.gradle` file for the dependency)

**Comment by sharwell** [comment]
It sounds like your lexer is producing an error and discarding input before it ever makes its way to the parser. Its important to write your lexer so it converts all possible input sequences into a series of tokens, otherwise the parser will not be able to report errors with any context.

The best way to do this is to use the following as the last rule in your lexer grammar:

```antlr
// Any character which does not match one of the above rules will appear in the token stream as
// an ErrorCharacter token. This ensures the lexer itself will never encounter a syntax error,
// so all error handling may be performed by the parser.
ErrorCharacter
	:	.
	;
```

You can see several additional ways to incorporate error recovery information into your lexer rules in my [PostgreSQL lexer grammar](https://github.com/tunnelvisionlabs/antlr4-grammar-postgresql/blob/master/src/com/tunnelvisionlabs/postgresql/PostgreSqlLexer.g4).

**Comment by DavidBiesack** [comment]
Thanks for the response, @sharwell ... but to me this feels like the wrong 'solution'. I have a grammar. If the input has an error (unrecognized input), the lexer and parser together should respond to it via the error handler (perhaps via the lexer throwing an exception when the parser calls for a token and the lexer could not scan a valid token, such as the semicolon in my example). The parser should then pass that error on to the registered error handler and either bail or try to recover, perhaps by skipping the invalid character, depending on the parser's `ANTLRErrorStrategy` error handler

Adding a lexer rule to work around the implementation seems like the wrong solution.

P. 153 of The Definitive ANTLR 4 Reference says explicitly "If there are lexical errors, ANTLR also emits an error message indicating the character or characters it could not match as part of a token." then mentions overriding getMissingSymbol() in DefaultErrorStrategy -- thus, should BailErrorStrategy not handle this out of the box?

p. 173 also shows defining a recover(LexerNoViableAltException e) method, but that does not work for me -- the input still parses without error. 

Adding the `ErrorCharacter` as you show does work (thank you)  but this this still feels like a bug to me. (the `RecognitionException` does not even identify the ErrorCharacter - I get `line 1:4 no viable alternative at input '<EOF>'` instead of on the `;`) However, I realize that making this type of change to ANTLR could be disruptive and break many existing grammars.

**Comment by DavidBiesack** [comment]
I should note that I encountered this when I was porting an existing grammar from ANTLR v3 to ANTLR v4.

With v3, ANTLR rejected the erroroneous test case input
```
a;
```
 (this was in my existing JUnit tests.) So this represents (in my mind) a regression from v3 to v4 -- a grammar that worked as expected in v3 does not work the same way in v4.

**Comment by DavidBiesack** [comment]
Also note that the parser throws a `ParseCancellationException` when I use the `ErrorCharacter` workaround, but the exception's `getMessage()` is `null`. The cause is a `InputMismatchException` also with `null` message. This makes assisting the user difficult as the app cannot give a good message to the user as to why the input is invalid.

**Comment by parrt** [comment]
ANTLR's lexer will emit "bad token" error for `;` but from then on it's not an error. Parser will not see it.
