### ISSUE TITLE
Using antlr4 v4.5.3 to parse a java file that has more than 3000 lines gives OUT OF MEMORY error.

### ISSUE THREAD

**Issue by Rajasuriya** [antlr/antlr4#1227]
Although increasing the heap size helps, I'm just wondering if there is a way to optimize the memory usage.

**Comment by KvanTTT** [comment]
What Java grammar are you using? Java or Java8? See this [discussion](https://github.com/antlr/grammars-v4/issues/215) for detail.

**Comment by Rajasuriya** [comment]
@KvanTTT Thanks for the quick reply!
Its [Java8.g4](https://github.com/antlr/grammars-v4/blob/master/java8/Java8.g4), 
I'm hoping that the new grammar will resolve this issue. May I know when will it be available?
Also, Is there any other way to optimize?

**Comment by KvanTTT** [comment]
I hope it will be available closer to autumn. For optimizations see [Java grammars section](http://blog.ptsecurity.com/2016/06/theory-and-practice-of-source-code.html#java--and-java8-grammars) in my topic.

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/commit/fca5e458d3cbbc0d24fbefd2e6ac47569d479afa
