### ISSUE TITLE
SLL Mode disambiguation/performance

### ISSUE THREAD

**Issue by WolfgangFahl** [antlr/antlr4#1232]
As outlined in #994 some grammars have a bad timing behavior when using with ANTL4. 
As #994 recommends a two phase strategy should be used in this case. The following grammar is a "badly" behaving grammar even using two phase strategy:

```
/**
 * see https://github.com/antlr/antlr4/issues/994
 */
grammar numexpr;

numexpr: if_statement EOF;

if_statement:
  if_part ( else_part ) ? 'endif';

if_part:
  'if' expr statement_list|
  'if' expr;

else_part:
  'else' statement_list |
  'else';

statement_list:
  statement +;  


statement: if_statement; 

expr: ID
    | VALUE
    | 'not' expr
    | expr '=' expr
    | expr 'and' expr
    | expr 'or' expr
    | expr 'between' expr 'and' expr
    ;

VALUE: [0-9]+;
ID: [a-zA-Z_][a-zA-Z_0-9]*;
WS: [ \t\n\r\f]+ -> skip;
ERROR: .;
```

I'll elaborate more on stackoverflow see http://stackoverflow.com/questions/38294579/antlr4-performance-issue

**Comment by KvanTTT** [comment]
Did you try to split left-recursive `expr` rule on not-recursive or primitive recursive rules as it described [in my article](http://blog.ptsecurity.com/2016/06/theory-and-practice-of-source-code.html#java--and-java8-grammars)?

**Comment by WolfgangFahl** [comment]
Thank you @KvanTTT 

Indeed  the following grammar behaves better. But how does ANTLR debug info help me in converting my grammar? The real grammar I am having trouble with is much bigger then this example :-)

```
/**
 * see https://github.com/antlr/antlr4/issues/994
 */
grammar primrecexpr;

primrecexpr: if_statement EOF;

if_statement:
  if_part ( else_part ) ? 'endif';
 
if_part:
  'if' expr statement_list|
  'if' expr;

else_part:
  'else' statement_list |
  'else';

statement_list:
  statement +;  
  
statement: if_statement; 


expr:
    notexpr
    | expr 'and' expr
    | expr 'or' expr
    ;    

notexpr: 
    'not' notexpr
    | equalexpr;

equalexpr: 
    atomexpr |   
    equalexpr '=' equalexpr
    ;

atomexpr:
   ID
    | VALUE;

VALUE: [0-9]+;
ID: [a-zA-Z_][a-zA-Z_0-9]*;
WS: [ \t\n\r\f]+ -> skip;
ERROR: .;
```

**Comment by danielsun1106** [comment]
When developing the parser for Groovy,  we had the same issue. You can try the antlr4(com.tunnelvisionlabs:antlr4) optimized by @sharwell

**Comment by parrt** [comment]
You have hit a nonlinearity in the parsing algorithm. @sharwell  and I are discussing an improvement.

**Comment by parrt** [comment]
Dup of #994

**Comment by WolfgangFahl** [comment]
Excellent it is good to see some progress here. I think pointing out a non linear situation would already be a good start.
