### ISSUE TITLE
extraction of literals

### ISSUE THREAD

**Issue by widc** [antlr/antlr4#1235]
The extraction of literals from a token with alternatives (e.g. from this one  "OfEach: 'of each' | 'for each';") returns nulls instead of the literals.
In our grammar file we have several of these token definitions, where no other special symbols like *, +, or ? are used.
We have to hard-code these missing literals outside of the grammar file to cope with this behaviour. This external code has to be updated manually to keep it synchronized with the grammar.

Would it be possible to also recognize and report the 'of each' and 'for each' strings in the example above as literals?

**Comment by parrt** [comment]
sorry but I really don't understand this bug report.
