### ISSUE TITLE
getText method with arguments not always works correctly

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#1238]
I created `CommonTokenStream` from list of tokens by the following way:

``` Java
List<? extends Token> preprocessorTokens = (List<Token>)lexer.getAllTokens();
ListTokenSource codeTokenSource = new ListTokenSource(tokens);
CommonTokenStream tokensStream = new CommonTokenStream(codeTokenSource);
```

After it I tried to call method `getText(context)` for RuleContext but it returned a wrong result:

``` Java
tokensStream.getText(context); // returns incorrect text, only text of first token
tokensStream.getText();             // returns correct text of all tokens
```

If `fill()` method was called before `getText` methods, these methods return a correct text:

``` Java
tokensStream.fill();
tokensStream.getText(context); // returns correct text of tokens from context
tokensStream.getText();             // returns correct text of all tokens
```

**Comment by sharwell** [comment]
On a complete side note, you have an invalid cast in there. Your first line should actually be this:

```java
List<? extends Token> preprocessorTokens = lexer.getAllTokens();
```

**Comment by KvanTTT** [comment]
Thank you! I'm familiar with Java not very good :)

**Comment by sharwell** [comment]
No problem, thanks for taking time to follow up on the Java side of this issue!
