### ISSUE TITLE
python2_api is too slow

### ISSUE THREAD

**Issue by mars00772** [antlr/antlr4#1239]
ncalls         tottime  percall  cumtime  percall filename:lineno(function)
1089345/11806     3.142    0.000   14.203    0.001 antlr4\atn\ParserATNSimulator.py:1163(closure_)
  1127090         1.653    0.000    1.653    0.000 antlr4\atn\ATNConfig.py:45(**init**)
  1542899         1.401    0.000    5.097    0.000 antlr4\atn\ParserATNSimulator.py:1232(getEpsilonTarget)
1115917/11806     1.315    0.000   14.222    0.001 antlr4\atn\ParserATNSimulator.py:1121(closureCheckingStopState)
2100131/986037    0.976    0.000    1.728    0.000 {hash}
  4222077         0.868    0.000    0.868    0.000 {isinstance}
   836337         0.831    0.000    2.072    0.000 antlr4\atn\ParserATNSimulator.py:1223(<lambda>)
   470116         0.733    0.000    3.863    0.000 antlr4\atn\ATNConfigSet.py:92(add)
   470116         0.722    0.000    2.743    0.000 antlr4\atn\ATNConfigSet.py:117(getOrAdd)
      552         0.411    0.001    0.607    0.001 antlr4\atn\PredictionMode.py:497(getConflictingAltSubsets)
527777/261858     0.399    0.000    0.444    0.000 antlr4\PredictionContext.py:159(**eq**)
   199665         0.369    0.000    0.634    0.000 antlr4\atn\ATNConfig.py:83(**eq**)
   536913         0.322    0.000    1.205    0.000 antlr4\atn\ATNConfig.py:95(**hash**)
  2350555         0.295    0.000    0.398    0.000 {method 'get' of 'dict' objects}

**Comment by ericvergnaud** [comment]
Hi,
sorry to be straightforward but this contribution is not helpful.
Please close this and move the topic to the google discussion group.
Eric

**Comment by mars00772** [comment]
ok
