### ISSUE TITLE
[4.x][Java] Lexical modes token duplicates

### ISSUE THREAD

**Issue by igmar** [antlr/antlr4#1240]
antlr currently forbids reusing tokens in multiple lexical modes. While this can be handles (by calling setType(), it's less then optimal. Having a  

mode FOO, BAR;
COMMA:        ',' ;
DOT:              '.' ;

would be a nice to have. This is especially the case for "common" tokens, such as whitespace, dots, comma's, colons, etc. It would make the lexer source a bit less messy.

**Comment by parrt** [comment]
hi.  A decent idea but I'm mainly in bug fix mode these days so I'm going to close. thanks.
