### ISSUE TITLE
Doc antlr4 / doc / javascript-target.md outdated, states there is no NPM package for antlr4 runtime

### ISSUE THREAD

**Issue by BurtHarris** [antlr/antlr4#1241]
At page https://github.com/antlr/antlr4/blob/master/doc/javascript-target.md it currently says:
   Right now, there is no npm package available, so you need to register a link instead...

This information seems out-of-date.   I just found the NPM package [**antlr4**](https://www.npmjs.com/package/antlr4) version 4.5.3 published by ericvergnaud 3 months ago.   Assuming this posting is reliable, perhaps javascript-target.md should be updated.

**Comment by ericvergnaud** [comment]
Hi,
thanks. Can you propose an update?
Eric

**Comment by BurtHarris** [comment]
Sure, but I wanted to make sure I had everything working first.    I think I've found another bug, will file separately.   Thanks.

**Comment by BurtHarris** [comment]
@ericvergnaud will you have a look at my pull request #1250

**Comment by ericvergnaud** [comment]
Will do but currently on vacation 

Envoyé de mon iPhone

**Comment by parrt** [comment]
@ericvergnaud  has the documentation been updated in any of our PRs?

**Comment by ericvergnaud** [comment]
need to check

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/pull/1250 I believe.
