### ISSUE TITLE
Require js file specified in superClass option

### ISSUE THREAD

**Issue by melihovv** [antlr/antlr4#1245]
If I understand correctly, if I want my lexer class extends class specified in superClass options, I should write this (js runtime)
```antlr4
lexer grammar LemonLexer;
options {superClass = LexerAdaptor;}
@header {var LexerAdaptor = require('./lexer-adaptor');}
```
In Java only superClass option is enough for this, if LemonLexer and LexerAdaptor in the same namespace. But in js it isn't. It will be better to extend parser/lexer with only superClass option, automatically require file with name superClass by default.
There is another option - use webpack imports-loader, but it is not so handy.

**Comment by ericvergnaud** [comment]
Hi, thanks for this.
FYI, the superClass option is only critical for statically typed languages.
In JavaScript, you are better off extending the generated lexer at runtime.

**Comment by melihovv** [comment]
Thanks, it is a good idea!)
