### ISSUE TITLE
Add TypeScript typings for antlr4 JavaScript target

### ISSUE THREAD

**Issue by BurtHarris** [antlr/antlr4#1254]
[TypeScript](http://www.typescriptlang.org/) is a compile-time static type checking extension to the JavaScript language.  Existing JavaScript packages (like the antlr4 JavaScript runtime) can be annotated with TypeScript declarations without modifying the original source code.   This enables TypeScript enabled tools, like the VSCode and Atom IDEs, to provide IntelliSense features even though the JavaScript language is dynamically typed.

It would improve the usability of antlr4 in JavaScript environments to provide such type annotations.   I'll start the ball rolling with some runtime type definitions in `index.d.ts`.   To complete the task would require the JavaScript target to generate `.d.ts` files along with the generated `.js' files.

**Comment by KvanTTT** [comment]
> To complete the task would require the JavaScript target to generate .d.ts files along with the generated `.js' files.
It would be great to add TypeScript typings to generated Visitor and Listener.

**Comment by BurtHarris** [comment]
Thanks @KvanTTT, its good to know there's interest.   I am working on that, but having trouble with my build environment.   I've withdraw my first attempt at a pull request for this but *I'll be back.*

**Comment by afucher** [comment]
@BurtHarris any progress?? I saw your typescript branch, are you still working on it?

**Comment by bitwolfsoftware** [comment]
@BurtHarris I would love this as well.

**Comment by Phmager** [comment]
Me too.

**Comment by BurtHarris** [comment]
Good things come to those who wait.   I've been busy.

**Comment by parrt** [comment]
Closing in favor of discussion here https://github.com/antlr/antlr4/issues/1286
