### ISSUE TITLE
Bug: `<loopExpr; format="myformat">` format attribute seem not working properly (no effect).

### ISSUE THREAD

**Issue by gaulouis** [antlr/antlr4#1257]
Hello,

In *.stg template there is "} while (`<loopExpr>` );" occurrence than generate "} while (_la==SELECT) {" in my case.
I need to generate : "} while (_la==SQL_SYMBOL_SELECT) {" where SQL is "`<file.genPackage; format="upper">`", "SYMBOL" is a constant and "SELECT" is varName

Can anyone help me to fix my problem ?

**Comment by BurtHarris** [comment]
Your description of the problem probably needs clarification with more context, e.g. *.stg in what directory?   There are at least 150 .stg files in the source code.

**Comment by gaulouis** [comment]
thank you for your quick response.

I'am working on Antlr4.5.2 to create a CTarget.
According to https://github.com/antlr/antlr4/blob/master/doc/creating-a-language-target.md i have copied antlr4/tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg to antlr4/tool/resources/org/antlr/v4/tool/templates/codegen/C/C.stg

I'am testing my CTarget whit MySQL grammar in the offical github
In Java.stg, near line 524 `<loopExpr>` is generated by Java code and i do not know how to modify *.java

I have modified antlr4/tool/src/org/antlr/v4/codegen/target/CTarget.java to use `<loopExpr format="glib_naming_convention">` but i can't specify the SQL package name (prefix).

**Comment by parrt** [comment]
Hi. `<s; format="Cap">` should work for you to capitalize all strings. StringRenderer is registered with ST for code gen I think.
