### ISSUE TITLE
.gitignore and antlr4 codegen/target directory...

### ISSUE THREAD

**Issue by BurtHarris** [antlr/antlr4#1260]
I think I ran into a problem there's a problem with `.gitignore` excluding **`target/`** while developing a new language target for TypeScript.   

Am I correct in thinking that items under `tool/src/org/antlr/v4/codegen/target/` **should not** be excluded from source control?

**Comment by BurtHarris** [comment]
I have to wonder if this has blocked any fixes people might have made to files under `tool/src/org/antlr/v4/codegen/target/` from getting into the release!

**Comment by gaulouis** [comment]
Hello,

I faced the same problem. To overcome it, I have used the option ``-f`` for ``git add -f MyTarget.java``
I have see your modification in your pullrequest. Perhaps it would be wiser to specify each directory. Because, what happen if i would like to minification js in ``./runtime/JavaScript/target``
 
So i propose to replace in ``.gitignore``
``target/``
by
``./antlr4-maven-plugin/target``
``./tool-testsuite/target``
``./runtime/Java/target``
``./tool/target``
``./runtime-testsuite/target``
``./runtime-testsuite/target/classes/Java/target``

**Comment by BurtHarris** [comment]
Thanks for your feedback @gaulouis.

I considered that, here's my reasoning for going the other way:   ANTLR has adopted Mavin (relatively recently I think), which works best with a documented set of [conventions](http://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html), among which is the convention that "The `target` directory is used to house all output of the build."    Thus a general exclusion of target is in keeping with the general practice of not checking in build products.   

If I understand your scenario correctly, the target directory you are describing _would_ be output of a minifiy (or similar) step in the build.   As such, it doesn't belong in the source-control repository.   That's not to say that the minified sources don't belong in some other sort of repository (e.g. Bower or NPM).  But that's just fine as different configuration files control building those packages, so an entry in .gitignore doesn't prevent that.

The directory I excluded *is* an exception, as it contains source files.   Perhaps a safer way of deailing with it would be to rename the 'target' directory they are in, but adding a speific exclusion seemed a less intrusive change.

**Comment by parrt** [comment]
Hmm... is it just me or is github not closing issues automatically anymore? Anyway, closed by https://github.com/antlr/antlr4/pull/1261

**Comment by BurtHarris** [comment]
@part, I think this is because I didn't know the magic incantation to make it happen.   Since you mention it, I found this:  https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by parrt** [comment]
Yeah, it always used to work for me but now it is not.  I must be doing something weird with branches or something.

**Comment by BurtHarris** [comment]
No, @parrt, you misunderstand.   I think is because I didn't put the right keywords in my commit comment.

**Comment by parrt** [comment]
ok, but i have "Fixes #xxx" in a number of recent msgs only to have it not close issue.
