### ISSUE TITLE
Please help me understand why ParseTreePatternMatcher seems unimplmented in JavaScript runtime

### ISSUE THREAD

**Issue by BurtHarris** [antlr/antlr4#1264]
Working with the JavaScript runtime, it seems like `ParseTreePatternMatcher` is not implemented, although it is used as a constructor in Parser.js at line 334.   

Can someone please help me understand this?

**Comment by ericvergnaud** [comment]
Hi
It's definitely a possibility
The Javascript Runtime was implemented using a TDD strategy so any code not breaking the tests was simply ignored
Eric 

Envoyé de mon iPhone

**Comment by BurtHarris** [comment]
I see, thank you Eric.     

Could it be that methods like Parser.compileParseTreePattern() are there to support the "tool" and thus are only needed in th Java version?
