### ISSUE TITLE
A bug of the antlr4 python3 runtime 4.5.3

### ISSUE THREAD

**Issue by yagweb** [antlr/antlr4#1265]
In the file IntervalSet.py, the statement at line 147 is,
     _i.start = v + 1_.
In which the variable _i_ is of type _range_, so its member _start_ is readonly.
Maybe it can be replaced by, 
    _self.intervals[self.intervals.index(i)] = range(v + 1, i.stop)._

**Comment by ericvergnaud** [comment]
Hi,
thanks for this.
I agree with the bug, not with the fix. I think it should be:
self.intervals[k] = range(v + 1, i.stop)
Can you provide a test to reproduce the issue?

**Comment by parrt** [comment]
@ericvergnaud looks like no test is coming. should we just fix it?

**Comment by ericvergnaud** [comment]
will do

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/pull/1460
