### ISSUE TITLE
NuGet package Antlr4 throws 'External packages cannot depend on packages that target projects.' error on install.

### ISSUE THREAD

**Issue by watkipet** [antlr/antlr4#1267]
As of at least version 4.5.3.1-beta001, installing the `Antlr4` NuGet package in Visual Studio 2010 with NuGet 2.8.60318.667 causes NuGet to output the following when it attempts to install the `Antlr4` package:

```
Attempting to resolve dependency 'Antlr4.CodeGenerator (≥ 4.5.3.1-beta001)'.
External packages cannot depend on packages that target projects.
```

The other two packages, `Antlr4.Runtime` and `Antlr4.CodeGenerator`, install fine and ANTLR appears to work. Is `Antlr4` a meta-package that is supposed to install the two mentioned above? I notice it depends on them. Perhaps an update to NuGet is causing that package to fail where it succeeded in the past? There is a [blog article](https://danlimerick.wordpress.com/2011/10/01/getting-around-nugets-external-package-dependency-problem/) on this error, but it's from 2011.

**Comment by sharwell** [comment]
:warning: Note that this is not the correct GitHub repository for the two artifacts you mentioned. You are actually looking for the [tunnelvisionlabs/antlr4cs](https://github.com/tunnelvisionlabs/antlr4cs) repository.

> Is Antlr4 a meta-package that is supposed to install the two mentioned above?

Yes.

> Perhaps an update to NuGet is causing that package to fail where it succeeded in the past?

I believe it's the other way around. I would expect the actions you took to complete successfully in versions of Visual Studio which are able to use NuGet Package Manager 3 and newer.
