### ISSUE TITLE
What is the utility of adjustment of Lexer/Parser::_serializedATN

### ISSUE THREAD

**Issue by gaulouis** [antlr/antlr4#1270]
Hello everyone,

I'am porting Antlr4-runtime-Java to C (for [GLib](https://developer.gnome.org/glib/) platforme) at [Antlr4-runtime-GLib](https://github.com/gaulouis/antlr4/tree/GLib/runtime/GLib/antlr) with good work in progress.

To support the "old" compilers, I do not use Unicode to store data serialized ATN (from generated Lexer/Parser::_serializedATN), but directly hexadecimal notation and without  "adjustment" (`data[i] = (char)(data[i] - 2);` see: [ATNDeserializer::deserialize](https://github.com/antlr/antlr4/blob/master/runtime/Java/src/org/antlr/v4/runtime/atn/ATNDeserializer.java#L135)) .
Also, before going further, I would like to know what is the reason for this choice? What is the responsability of this code?

The serial number could it not be sufficient to avoid version problems?

Any guidance would be appreciated

**Comment by BurtHarris** [comment]
Could it be to account for two pseudo-tokens generated by Lexers, that have negative values: EOF and EPSILON?

**Comment by mike-lischke** [comment]
Sorry, I can't follow @gaulouis. The serialized ATN **is** stored as word values. This is not Unicode but just binary data. You can take this over 1:1.

**Comment by gaulouis** [comment]
Agree on the representation of the data.
My question was also about adjustment. I do not understand how this [loop](https://github.com/antlr/antlr4/blob/master/runtime/Java/src/org/antlr/v4/runtime/atn/ATNDeserializer.java#L113) is useful:
```
		for (int i = 1; i < data.length; i++) {
			data[i] = (char)(data[i] - 2);
		}
```

**Comment by sharwell** [comment]
See tunnelvisionlabs/antlr4ts#144 for an explanation of this.

**Comment by gaulouis** [comment]
Thanks for the help, and the time you gave me
