### ISSUE TITLE
Context sensitivity and error reporting 

### ISSUE THREAD

**Issue by marcospassos** [antlr/antlr4#1272]
We're working on a grammar for a new language that is part of a large startup project. This  language uses many keywords that cannot be reserved. To handle this context sensitivity problem, we adopted the approach suggested in the definitive guide - pass all keywords to the parser as keyword token types, and then we create a parser id rule that matches ID and any of the keywords. The drawback of this approach is that it "pollutes" the error reporting. Instead of suggesting an `ID` as an expected token, it suggests all the keywords, because it's part of the prediction set.

Is there any way to produce a better error reporting in such cases?

**Comment by parrt** [comment]
@marcospassos  I think you would need to add your own error listener and change the message.

**Comment by marcospassos** [comment]
@parrt in fact, it's something much more advanced. I had to rewrite the LL1Analyzer to extract this information.

**Comment by parrt** [comment]
Ah.  so you asked it for what can come next for `id` rule?

**Comment by marcospassos** [comment]
Yes, so in our case, we'd like to show something like _Missing token 'ID'_ rather than _Token mismatch, expecting TOKEN_1, TOKEN_2, ...TOKEN_100_.

**Comment by marcospassos** [comment]
In fact, I've overrided the LL1Analyzer and replaced the first-set of the rule `id` for the _synthetic_ token `id`.

**Comment by parrt** [comment]
ah. ok, nice.
