### ISSUE TITLE
JavaScript target visitor pattern: not correctly interpreting alternative names

### ISSUE THREAD

**Issue by jamespedid** [antlr/antlr4#1275]
This issue was attempted to be addressed in #1100 but it seems like the fix fell through.

The issue at hand is that when you use the alternative expression syntax like this

```
grammar Expr;

prog:   stat+;

stat:   expr NEWLINE                # printExpr
    |   ID '=' expr NEWLINE         # assign
    |   NEWLINE                     # blank
    ;
```

The visitors that are generated do not produce the proper methods to respond to them. While I'm inexperienced with Antlr4 in general, I would expect the following methods to be generated in the visitor prototype

``` Javascript
visitStat() {
}

visitPrintExpr() {
}

visitAssign() {
}

visitBlank() {
}
```

**Comment by jamespedid** [comment]
I'm unsure how your testing works for this project, due to its complexity. If you can explain how to add a test for this kind of change, (and it would be less work for you to do just that), I can add a test case for this  fix if possible.

**Comment by ericvergnaud** [comment]
Hi,
the testing is built to ensure consistent behaviors across targets.
In brief, there is a bunch of test-specific templates and a bunch of target-specific templates, which combined are used to generate the tests.
There are currently no tests for visitors, hence the lack of implementation in javascript.
Adding a test requires creating a test template (using StringTemplate) in runtime-testsuite/resources/org/antlr/v4/test/runtime/templates.
A good starting point could be to create a "Visitors" directory and adapt the existing "Listeners" templates to use visitors instead.
You then need to generate the unit tests, using  runtime-testsuite/src/org/antlr/v4/testgen/TestGenerator, this will generate the tests for all targets.
From there, you can fix the failing tests by enhancing the language templates accordingly.
Please note that you need to regenerate the tests after each template change.
Good luck,
Eric

**Comment by BurtHarris** [comment]
Thanks @ericvergnaud  for the comment above on building test cases.   Am I correct in finding no docs on writing runtime tests?

It seems like test-case creation really needs serious polyglot; the `.stg` are like Greek to me.    Yes, I've read the StringTemplate docs at least twice, but wrapping my head around this test mechanism, with no comments to speak of, looks like the hardest part of contributing to this project.    

It helps me understand some of your earlier comments better.  :-)

**Comment by ericvergnaud** [comment]
Hi
I will try to write a how-to shortly
Eric

Envoyé de mon iPhone

**Comment by ericvergnaud** [comment]
Hi,

actually, there is already a doc, here:
https://github.com/antlr/antlr4/blob/master/doc/adding-tests.md

.stg files are String Template Groups. The StringTemplate library is key to ANTLR since it is used to generate lexers and parsers from the grammar structure. To learn more about StringTemplate, read here: http://www.stringtemplate.org

Good luck
