### ISSUE TITLE
ANTLR4  returns wrong error

### ISSUE THREAD

**Issue by ismyrnov** [antlr/antlr4#1277]
Hi , I faced with returning wrong error, here my g4 file :

[g4_file.txt](https://github.com/antlr/antlr4/files/461570/g4_file.txt)

It has :
    **| FIELD PRESENT               #presentExp
    | FIELD OPERATOR VALUE        #simpleExp**

and when string to pars is :

**"photos pr1"**  -  the **"pr1"** is not matched and there should be error message:
  
**"mismatched input 'pr1' expecting PRESENT",** 

but I've got wrong error message: 
**"no viable alternative at input 'photospr1'"**

Could you please fix ANTLR4 error message ?

Thanks,
Iurii Smyrnov
ismyrnov@talend.com

**Comment by ericvergnaud** [comment]
Hi,

the place for support is the google discussion group.
Please close this.

Eric

**Comment by ismyrnov** [comment]
In google discussion group this issue is ignored

**Comment by ericvergnaud** [comment]
You won’t get more support here.
Please be patient.
