### ISSUE TITLE
Strange code in JavaScript - PredictionContext.js line 191

### ISSUE THREAD

**Issue by ghosthope** [antlr/antlr4#1280]
Hi.
I searched  some ways for optimization in ANTLR for JavaScript and found one strange line in code:
https://github.com/antlr/antlr4/blob/d0fb48c2b89128158950f4b32a61d50d52d981ea/runtime/JavaScript/src/antlr4/PredictionContext.js#L191
I researched like SingletonPredictionContext class implemented. I don't sure but SingletonPredictionContext doesn't have property EMPTY_RETURN_STATE always because PredictionContext.call(this, hashString); (https://github.com/antlr/antlr4/blob/d0fb48c2b89128158950f4b32a61d50d52d981ea/runtime/JavaScript/src/antlr4/PredictionContext.js#L136) doesn't give this property to SingletonPredictionContext. <function>.call(this,...) doesn't translate properties from prototype to children. Need to use Object.create or PredictionContext.EMPTY_RETURN_STATE in line 191 for this.

Does it a bug or mistake or typo?

**Comment by ericvergnaud** [comment]
Indeed this is a typo, the code should read PredictionContext.EMPTY_RETURN_STATE
Thanks for pointing this, however Not sure it has any impact on performance

Envoyé de mon iPhone

**Comment by ghosthope** [comment]
You are right, it has not impact on performance. I just found the typo. But it can have impact on algorithm and logic. Not sure, need more research.
Thanks.

Live long and prosper \\//
