### ISSUE TITLE
Suggestion: add antlr4 ISSUE_TEMPLATE file to repository.

### ISSUE THREAD

**Issue by BurtHarris** [antlr/antlr4#1284]
We seem to get a lot of support requests posted as _Issues_ in this repository which are really questions or discussions.   GitHub has a new mechanism to setup templates for Issues (and pull requests) in a repository which might be a good place to include links to the stackExchange and google groups mechanisms.     See https://github.com/blog/2111-issue-and-pull-request-templates.

**Comment by parrt** [comment]
interesting. i'll look

**Comment by parrt** [comment]
Fixed with https://github.com/antlr/antlr4/commit/f3215d73d8900d45178c9d88c2aab2bb8c1ba680
