### ISSUE TITLE
JavaScript: visitChildren() method is missing on ParseTreeVisitor

### ISSUE THREAD

**Issue by cgudrian** [antlr/antlr4#1285]
The accept() method of RuleContext calls a visitChildren() method on a visitor. This method is neither provided by the runtime nor generated. Who is supposed to implement it?

**Comment by BurtHarris** [comment]
In the Java runtime its implemented on AbstractParseTreeVisitor..   In JavaScript the class hierarchy is a bit different, ParseTreeVisitor has a method called visit() which seems like a close match, but it in turn calls a visitAtom method which has been the subject of issue #1058.

**Comment by cgudrian** [comment]
Issues #1275 and #1100 are also dealing with the JavaScript visitor. Is this thing currently broken? Coming from the Java world it's not always evident what's "broken" or "just different". :)

Furthermore the implementations of the generated visitX methods are all empty while the Java version implements a depth-first-algorithm. Where's the rationale behind that?

**Comment by ericvergnaud** [comment]
Hi,
the rationale is that since I don't personally use visitors, there was not test case initially, and so no implementation.
There have been a number of contributions on this subject, none of which has yet reached the point of release, due to lack of involvement from the contributors.
I would be really happy to bless a contribution for this.
Eric

**Comment by cgudrian** [comment]
Hi, Eric! I did not mean to offend anyone. I'm just totally unfamiliar with the JavaScript portion of the runtime and wasn't sure if it's a missing feature or a case of PEBKAC. I'll have a look if I can improve on the situation.

**Comment by ericvergnaud** [comment]
I'm not offended, no worry, just clarifying the expectations.

**Comment by jamespedid** [comment]
I have found some success with the PR #1276. Whether or not this is the best solution, I'm unsure, but it seems to have some common usage going for it.
