### ISSUE TITLE
Running a limited subset of runtime-testsuite

### ISSUE THREAD

**Issue by BurtHarris** [antlr/antlr4#1291]
As the set of target runtimes and test cases grows, the time-complexity of running  `runtime-testsuite` using `mvn install` increases O(M*N).   To speed up the dev cycle for someone working on a particular target, it seems like we need a documented way to run a subset of the test cases, e.g. run only the JavaScript test cases.   

Similarly when debugging a particular test failure, it is often useful to run an even smaller set of tests _with target-language debugging enabled._    

Most testing frameworks I've used in the past include features to do this sort of thing.  Perhaps this is just a question of documenting some existing features in `runtime-testsuite`, or perhaps it will require code change.   Not being an experienced Java programmer, I'm not sure, but I suggest some effort is needed to support both of the above use-cases.

**Comment by ericvergnaud** [comment]
Hi,

once the tests are generated, from your favourite IDE you should be able to run a subset of them.

Eric

**Comment by parrt** [comment]
@BurtHarris works now. allows in parallel testing and target specific. see https://github.com/antlr/antlr4/blob/master/doc/building-antlr.md
