### ISSUE TITLE
$e.v yields incorrect value 0 in "e returns [int v] : '1' {$v = 1;} | '(' e ')' {$v = $e.v;} ;"

### ISSUE THREAD

**Issue by harriman** [antlr/antlr4#1295]
The incorrect result can be seen in the Interactive Calculator example (actions/tools/Expr.g4) in chapter 10 of the ANTLR4 book, page 181, in which parenthesized expressions always yield 0. 

When a rule invokes itself recursively, and no label is used, incorrect code is generated when an action references either a variable returned by the recursive call, or any of the subexpression's predefined attributes `text`, `start`, `stop`, or `ctx`. The generated code refers to the current rule's context;  instead it should refer to the child's context. In the calculator example, `$e.v` incorrectly accesses `_localctx.v` (the field where the current rule should put its result, which is initially 0 if numeric or null if a reference type). Thus, the example action assigns the uninitialized field to itself. Instead it should access `_localctx.e.v` (the result from the recursive invocation).

The problem does not occur when the grammar assigns a label renaming the self-invocation - for example, it would be ok if changed to `'(' ee=e ')' {$v = $ee.v;} ;`

**Comment by harriman** [comment]
Seems to be the same problem as #571. Fix #630 did not actually fix it.

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/pull/1296
