### ISSUE TITLE
Matched tokens being marked as error

### ISSUE THREAD

**Issue by marcospassos** [antlr/antlr4#1299]
I found a case where the parser is marking matched tokens found inside error nodes as an error. For instance, given the malformed expression `1 * 2 +++`, this is the resulting tree:

![antlr4_parse_tree](https://cloud.githubusercontent.com/assets/943036/19059272/fbd9c52a-89b4-11e6-96f1-58314aa28204.png)

However, it's the expected tree:

![image](https://cloud.githubusercontent.com/assets/943036/19059287/224132f2-89b5-11e6-951c-0e456d91f5ce.png)

Notice that the operators `+` are being marked as an error in the first tree, although they have being recognized as operators. 

It worth noting that the former tree was generated using the TestRig, while the latter is a screenshot of the tree generated in the IntelliJ plugin. This issue is most likely related to antlr/intellij-plugin-v4#180.

**Comment by marcospassos** [comment]
@parrt can we get it merged for 4.6?

**Comment by parrt** [comment]
are you sure this isn't an issue with the plug-in?

**Comment by marcospassos** [comment]
In fact no. When the panic mode strategy is activated, it consumes every token until a token present in the recovery set is found. However, it doesn't close the error condition - hence, when the next token is matched, it's created as an error token.

**Comment by parrt** [comment]
interesting.  So, again, the plug-in does a better job than the generated code. haha.

**Comment by marcospassos** [comment]
Yeah, I don't know what is happening exactly, may be machine learning. I'm thinking about creating a wrapper to run our parser through the IntelliJ once the results are more promising (Y)

**Comment by marcospassos** [comment]
Yes, I think so. We've here 20+ unit tests broken that can assert these fixes. I'll test the snapshot by tomorrow to confirm.

**Comment by marcospassos** [comment]
@parrt this bug is still present in 4.6. Could you please reopen this issue?

Please, take this grammar as example:

```antlr
grammar TestGrammar;

program
    //: primary 'IS' 'BETWEEN' primary 'AND' primary ('EXCLUSIVE' | 'INCLUSIVE')
    : 'index' 'of' primary 'in' primary (FROM primary)?
;

primary
    : INTEGER     # TestInt
    | identifier  # TestId
;

identifier
    : IDENTIFIER
    | FROM
;

operator
    : '>='
    | '<='
;

INTEGER: [0-9]+;
IDENTIFIER: [a-zA-Z]+;
FROM: 'from';

WHITESPACE
    : (' ' | '\n' | '\t' | '\r' )+ -> channel(HIDDEN)
;
```
Input:
```
index of in users from 1
```

Result:
```
(program index of (primary in (identifier users)) <missing 'in'> (primary (identifier from)))
```

![image](https://cloud.githubusercontent.com/assets/943036/21084727/1b747144-bfef-11e6-850d-59051954fb47.png)

Where did the token `1` go? If the `FROM` token is recognized as an identifier, why is it marked as an error?

**Comment by marcospassos** [comment]
@parrt this bug is still present in 4.6. Could you please reopen this issue?

Please, take this grammar as example:

```antlr
grammar TestGrammar;

program
    : 'index' 'of' primary 'in' primary (FROM primary)?
;

primary
    : INTEGER    # Int
    | identifier    # Id
;

identifier
    : IDENTIFIER
    | FROM
;

INTEGER: [0-9]+;
IDENTIFIER: [a-zA-Z]+;
FROM: 'from';

WHITESPACE
    : (' ' | '\n' | '\t' | '\r' )+ -> channel(HIDDEN)
;
```
Input:
```
index of in users from 1
```
Result:
```
(program index of (primary in (identifier users)) <missing 'in'> (primary (identifier from)) 1 <EOF>)
```
![tree](https://cloud.githubusercontent.com/assets/943036/21084830/1f3afd92-bff0-11e6-9550-f4786d00a258.jpg)

If the `FROM` token is recognized as an identifier, why is this marked as error?

**Comment by marcospassos** [comment]
Another example:

```antlr
grammar TestGrammar;

program
    :  'any' identifier 'in' primary index? (SATISFY | SATISFIES) enclosed EOF
;

enclosed
    : '{' primary '}'
;

index
    : INDEXED BY identifier
;

primary
    : INTEGER     # TestInt
    | identifier  # TestId
;

identifier
    : IDENTIFIER
    | SATISFY
    | SATISFIES
    | INDEXED
    | BY
;


INTEGER: [0-9]+;
SATISFIES: 'satisfies';
SATISFY: 'satisfy';
INDEXED: 'indexed';
BY: 'by';
IDENTIFIER: [a-zA-Z]+;

WHITESPACE
    : (' ' | '\n' | '\t' | '\r' )+ -> channel(HIDDEN)
;
```
Input:
```
any foo in 2 indexed a satisfy { 1 }
```
Result:
``` 
(program any (identifier foo) in (primary 2) (index indexed <missing 'by'> (identifier a)) satisfy (enclosed { (primary 1) }) <EOF>)
```
![tree](https://cloud.githubusercontent.com/assets/943036/21085265/f0e72f40-bff6-11e6-8433-00a86e274baf.jpg)

**Comment by parrt** [comment]
@marcospassos For your first post, "*If the FROM token is recognized as an identifier, why is this marked as error?*" It is not recognized as `identifier`. It **tried** to match `identifier` but failed as it found `FROM`.

**Comment by marcospassos** [comment]
So, why is it inside the`identifier` tree? If the parser detects that it's missing the `by` token, so `from` is recognized as an identifier, no?

**Comment by parrt** [comment]
:) First note that it's `identifier` not `IDENTIFIER`.  The grammar tells it to call `identifier` and so it does but it can't match `from` to either alt so it's an error node.

**Comment by parrt** [comment]
@marcospassos hold on.

**Comment by marcospassos** [comment]
@parrt yes, I know, it's a tree, not the identifier itself. But, take a look how the interpreter handles it:

![image](https://cloud.githubusercontent.com/assets/943036/21085955/f2c42f40-bffe-11e6-8c9d-b0fd076c789c.png)

**Comment by marcospassos** [comment]
About the second case, I could not realize whether they're the same issue or not.

**Comment by marcospassos** [comment]
Again, the interpreter rocks 💯

**Comment by parrt** [comment]
Found bug. easy fix but had to do for like 8 targets ;) waiting on tests to run...

**Comment by marcospassos** [comment]
Great! @parrt, notice that https://github.com/marcospassos/antlr4/commit/c5c987b99f735561b13bdc4b8ea8283ddfe3b39e is a different case for the same bug. When I turn this fix off, some tokens are marked as error even when they match appropriately.

**Comment by marcospassos** [comment]
@parrt could you please provide a snapshot?

**Comment by parrt** [comment]
https://oss.sonatype.org/content/repositories/snapshots/org/antlr/antlr4-runtime/4.6-SNAPSHOT/

**Comment by parrt** [comment]
@marcospassos for your other tweak, I don't think it's valid to put end error condition in consumeUntil().  It must match a valid token in correct position to switch this off.

**Comment by marcospassos** [comment]
As soon as I get home I'll provide small grammar that shows up this bug and then we discuss the best way to fix it.

**Comment by marcospassos** [comment]
@parrt https://github.com/antlr/antlr4/commit/b11ff9636aacd028f87a15e75b3927a0b7c67d20 fixes https://github.com/marcospassos/antlr4/commit/c5c987b99f735561b13bdc4b8ea8283ddfe3b39e. Thank you very much!
