### ISSUE TITLE
Token names are in wrong position in lexer.getRuleNames()

### ISSUE THREAD

**Issue by alovassy** [antlr/antlr4#1300]
I try to get the token names using the generated ...Lexer.java like this:
tokenType == -1 ? "EOF" : lexer.getRuleNames()[ tokenType - 1 ]

Sometimes the lexer rule names are in wrong position.
These are the 2 problematic cases, when the lexer rule name positions are modified:
1. fragments are not tokens, but they are listed in ruleNames[]
2. tokens, which are defined, but has no rule are not listed in ruleNames[]

It is a bug in ANTLR 4.4

**Comment by sharwell** [comment]
This was fixed by adding the `Vocabulary` interface in release 4.5. See #711.
