### ISSUE TITLE
Allow retrieving the underlying original input.

### ISSUE THREAD

**Issue by nielsbasjes** [antlr/antlr4#1302]
The ParseTree.getText() method returns the concatenation of all the tokens that are used in a specific ParseTree. In there the skipped characters have been removed in the lexer.

In some specific cases there is a need to get the underlying full (unmodified) source text including all the characters that were skipped (i.e. spaces, comments and such).

I propose a new method getSourceText to provide this.

**Comment by nielsbasjes** [comment]
To give you some insight [my use case:](https://github.com/nielsbasjes/yauaa) I need this is a situation where I use Antlr4 to do pattern detection in text and when a pattern is found I need to extract the original that has been matched.

**Comment by parrt** [comment]
@nielsbasjes Can't we solve this by just using channel not skip in lexer? Any runtime change could mean ripple effect across all targets.

**Comment by nielsbasjes** [comment]
My usecase is a situation where I want to find patterns and afterwards extract the unmodified matched string.
The reason I did it this way is that I initially had the spaces explicitly in my lexer and parser yet this made it very hard to read; a lot of SPACE+ in the parser . Using this construct it became a lot better to read and maintain.
I figured others may have a similar situation so that is why I submitted this change proposal.

**Comment by parrt** [comment]
If you send the whitespace to the parser on a hidden channel, you don't have to have matching of whitespace inside the parser but you still get the full input stream.

**Comment by nielsbasjes** [comment]
Today I did some digging through the code and noticed that the javadoc of the getText method says:

	/** Return the combined text of all child nodes. This method only considers
	 *  tokens which have been added to the parse tree.
	 *  <p>
	 *  Since tokens on hidden channels (e.g. whitespace or comments) are not
	 *  added to the parse trees, they will not appear in the output of this
	 *  method.
	 */

So I apparently do not understand your last comment. 
How does putting the spaces on a hidden channel (instead of doing a skip) relate to getting the full input stream? 
Even with the skip I get everything from the input stream so from what I understand right now it makes no difference (hence I put up this change proposal).

**Comment by parrt** [comment]
You ask the stream not the tree for the text.

**Comment by zspitz** [comment]
@parrt I understand that the original source shouldn't be part of the parse tree, as the parse tree works off of the token stream, which already is filtered by channel. But could the tree hold and expose some reference to the parser instance? Then I could write the following:

    var parser = tree.Parser;
    var originalSource = parser.TokenStream.TokenSource.InputStream.ToString();

My use case is for the [VS debugging visualizer](https://github.com/zspitz/ANTLR4ParseTreeVisualizer). The visualizer targets parse trees, and only has access to the parse tree, and no other objects such as the token stream. The visualizer syncs selection -- when the user selects a node in the parse tree, the corresponding text is selected. However, the `StartIndex` and `StopIndex` of the payload on the selected node relate to the original text which includes the hidden channel; while the displayed source -- which is generated using `tree.GetText()` -- doesn't have the text from the hidden channel.

![image](https://user-images.githubusercontent.com/312166/67677283-4f23e180-f98c-11e9-9984-979ef67f6eec.png)

**Comment by ericvergnaud** [comment]
Hi,

the parser input is a token stream which refers to the lexer which refers to the input.
so not sure what is missing?

Eric

**Comment by zspitz** [comment]
@ericvergnaud But I cannot access the parser from the tree alone.

Given the following code (where `HelloLexer` and `HelloParser` are ANTLR-generated classes; `r` is a tree-returning method):
```
// using Antlr.Runtime

var code = "hello world";
var input = new AntlrInputStream(code);
var lexer = new HelloLexer(input);
var tokens = new CommonTokenStream(lexer);
var parser = new HelloParser(tokens);
var tree = parser.r();
```
I can do this:
```
var originalSource = parser.TokenStream.TokenSource.InputStream.ToString();
```
But the visualizer only has access to `tree` and nothing else, which means no access to the parser which created the tree, and thus no access to the original source.

**Comment by ericvergnaud** [comment]
why can’t you pass an object { tree, parser } to the visualizer?

**Comment by zspitz** [comment]
Because the visualizer only works on a single object, exposed in the VS editor while debugging. For an example of how this looks in the editor, see https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/debugging-expression-trees-in-visual-studio .

**Comment by zspitz** [comment]
@ericvergnaud Because the visualizer only works on a single object, exposed in the VS editor while debugging. For an example of how this looks in the editor, see https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/debugging-expression-trees-in-visual-studio#to-open-a-visualizer-for-an-expression-tree .

**Comment by parrt** [comment]
Well, adding a full pointer to each node of a parse tree is a super heavy burden when you can keep your own parser pointer around.  Not sure how to solve your problem but obviously i'm not going to modify default ANTLR for this. sorry!

**Comment by ericvergnaud** [comment]
C# supports extension methods, have you explored that option?

**Comment by zspitz** [comment]
@parrt The operative words being _when you can keep your own parser pointer around._

But I do have a workaround in any case, as described above.

**Comment by ericvergnaud** [comment]
yes, using a singleton could also do the trick

**Comment by zspitz** [comment]
@ericvergnaud Could you clarify what you mean by _using a singleton_?

**Comment by ericvergnaud** [comment]
Well surely you would not be debugging 2 parsers simultaneously
So you could set the singleton as part of the parsing pipeline
And call DebuggedParser.Instance from within the tree nodes

**Comment by zspitz** [comment]
> And call DebuggedParser.Instance from with the tree nodes

Not really. A custom visualizer is a separate library, with no real knowledge of the project currently being debugged. The user can choose a specific object while debugging, and Visual Studio packages that object and passes it to the visualizer assembly.

For example, say my current project -- MyProject.dll -- uses types from the ANTLR runtime. While debugging MyProject, and coming across an instance of an ANTLR type, or that inherits from an ANTLR type -- say, SubStmtParserContext that inherits from ParserContext -- I can choose to inspect this instance with the associated visualizer dll. The visualizer dll knows about ANTLR types because it has a reference to the ANTLR runtime, but it doesn't know about my specific project, and it wouldn't know about the singleton.
