### ISSUE TITLE
XPathLexer.java missing from src?

### ISSUE THREAD

**Issue by rmbarnett-rice** [antlr/antlr4#1307]
When compiling:

antlr4-master\runtime\Java\src

I get the following compilation error:

antlr4-master\runtime\Java\src\org\antlr\v4\runtime\tree\xpath\XPath.java:

Error:(87, 17) java: cannot find symbol
  symbol:   class XPathLexer
  location: class org.antlr.v4.runtime.tree.xpath.XPath

**Comment by ericvergnaud** [comment]
Hi,
you are missing the maven build step which generates these files.
Eric

**Comment by parrt** [comment]
Yeah, see https://github.com/antlr/antlr4/blob/master/doc/building-antlr.md and run `mvn -DskipTests install`
