### ISSUE TITLE
ANTLR 4 C# compilation failed with System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by lextm** [antlr/antlr4#1308]
[MSBuild_834cb7d1-788a-4941-8d7b-6fa3ce4588de.failure.txt](https://github.com/antlr/antlr4/files/533662/MSBuild_834cb7d1-788a-4941-8d7b-6fa3ce4588de.failure.txt)

Attached is the build log in Visual Studio 15 Preview 5. Not sure if this is an MSBuild issue though.

Currently no workaround has been found by me.

**Comment by ericvergnaud** [comment]
HI
Support is provided on the Google discussion group.
Please close this.
Eric

Envoyé de mon iPhone
