### ISSUE TITLE
ExprLexer/ExprParser not found

### ISSUE THREAD

**Issue by a-nigredo** [antlr/antlr4#1310]
Hi
I created maven project with dependencies antlr4, antlr4-runtime and plugin antlr4-maven-plugin in Intellij Idea but when I try to run simple application like
`public class Application {
    public static void main(String[] args) throws Exception {
        ANTLRStringStream in = new ANTLRFileStream("D:\\java\\antlr\\src\\main\\java\\dev\\nigredo\\run.s");
        ExprLexer lexer = new ExprLexer(in);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        ExprParser parser = new ExprParser(tokens);
        parser.eval();
    }
}` 
compiler cant see class ExprLexer and ExpParser.

How to fix this problem?

**Comment by parrt** [comment]
Hmm...must be a pom.xml issue.  Maybe check one of mine https://github.com/antlr/stringtemplate4/blob/master/pom.xml

**Comment by pierreydumas** [comment]
@parrt No, it's not a pom.xml issue. Your pom use 3.5.2. He uses v4. The code he wants to run is v3. There's a guy who has his own implementation of the "missing" classes in v4.
I found [this code](http://jakubdziworski.github.io/java/2016/04/01/antlr_visitor_vs_listener.html) very helpful.
