### ISSUE TITLE
<EOF> error when generating parser

### ISSUE THREAD

**Issue by JoeyAcc** [antlr/antlr4#1315]
I need an XQuery parser, so I copied and then massaged the official grammar.
However, I get this error: 
````
error(50): xquery.g4::: syntax error: mismatched character '<EOF>' expecting '"'
error(50): xquery.g4:276:0: syntax error: '<EOF>' came as a complete surprise to me while looking for rule element
````

I have no idea how to get rid of the error, I tried looking at all the rules containing single and double quote literals, which could presumably make a difference here. 
So either I'm doing something wrong, which is entirely possible, or I've discovered a bug in ANTLR4.

I created a [gist](https://gist.github.com/JoeyAcc/b8e8c785c201e03eb6a20ecec6df1174) that contains the grammar as I have it now, which is modified from [the official XQuery grammar](https://www.w3.org/TR/xquery-xpath-parsing/#XQuery-EBNF) to make ANTLR accept it.

As an added detail, I gave [the official XPath grammar](https://www.w3.org/TR/xquery-xpath-parsing/#XPath-EBNF) the same treatment and the parser generation works fine there (whether the generated parser is correct or not is a future step for me). 

Could anyone help me out with this?

**Comment by ericvergnaud** [comment]
Hi
This discussion would be better located on the Google discussion group.
Eric

Envoyé de mon iPhone

**Comment by JoeyAcc** [comment]
Indeed, the discussion there helped me out quite a bit. So this issue can be closed now.

**Comment by rugglcon** [comment]
I realize this issue was closed 4 weeks ago, but I'm running into the same problem. Could you try and link the specific discussion that helped you out? Thanks.

**Comment by JoeyAcc** [comment]
Thing is, the discussion ended up *not* helping me out at all. In fact I'm hand-writing a recursive descent parser because that will actually work for me.

**Comment by harshaghanta** [comment]
I got the same error. For me, it was due to the line break & EOF difference between windows & Linux operating systems. Things started working once i replaced all the line breaks.
