### ISSUE TITLE
ANTLR 4.5.3 & java.lang.StackOverflowError

### ISSUE THREAD

**Issue by Nulleye** [antlr/antlr4#1317]
I can't use the complete 4.5.3 jar as the "ANTLR tool" in Eclipse, the jar manifest seems to be incorrect, 
I can use the 4.5 jar with no problems.

However, my problem is, If I define a lexer and a composed grammar with multiple related grammar files, to avoid error and warning tips to appear in Eclipse, I have to put "imports " to lexer and related grammar files in every grammar file, but If I do that, I get this error on every file:

Exception in thread "main" java.lang.StackOverflowError
	at org.antlr.v4.Tool.loadImportedGrammar(Tool.java:618)
	at org.antlr.v4.tool.Grammar.loadImportedGrammars(Grammar.java:399)
	at org.antlr.v4.tool.Grammar.loadImportedGrammars(Grammar.java:413)
... many repeated lines ...
	at org.antlr.v4.tool.Grammar.loadImportedGrammars(Grammar.java:413)
	at org.antlr.v4.tool.Grammar.loadImportedGrammars(Grammar.java:413)

BUILD SUCCESSFUL
Total time: 8 second(s)

But If I put the import only in the main grammar file it builds fine, but then I get many error tips everywhere.

This happen also in 4.5 and 4.2 complete jar.
What I'm doing wrong?

**Comment by ericvergnaud** [comment]
Hi,
the best place to get support is the google discussion group.
Eric

**Comment by Nulleye** [comment]
ok, sorry
thanks

**Comment by Nulleye** [comment]
Sorry to reopen this, just a small comment.
For what I see in the code, circular imports are not supported in ANTLR?
loadImportedGrammars() gets into an infinite loop in that circumstance.

**Comment by ericvergnaud** [comment]
Hi
The answer would be useful to more people on the Google group
Eric 

Envoyé de mon iPhone
