### ISSUE TITLE
@janyou needs to sign contributors.txt

### ISSUE THREAD

**Issue by ewanmellor** [antlr/antlr4#1328]
@janyou, please submit a pull request adding yourself to contributors.txt.  This gives a license to The ANTLR Project to distribute your work.  This is required before your work on the Swift backend can be merged into master.

See https://github.com/ewanmellor/antlr4/commit/0a00ec981a0e7247a700fd8248b44d2e3d7fdddc for an example.

**Comment by janyou** [comment]
thanks

**Comment by ewanmellor** [comment]
Merged into https://github.com/ewanmellor/antlr4/tree/swift-target.
