### ISSUE TITLE
Decide on the use of JSON serialization in the Swift target

### ISSUE THREAD

**Issue by ewanmellor** [antlr/antlr4#1329]
The Swift backend in https://github.com/ewanmellor/antlr4/tree/swift-target currently serializes to JSON rather than the existing ANTLR serialization.

Per @janyou this was done because the ANTLR original serialization will cause Xcode to crash (open the generated file and scroll).  I do not know which version of Xcode @janyou was using.

@parrt Do you want to take the JSON serialization (adding a dependency on javax.json) or change the Swift backend back to use the original serialization?

**Comment by parrt** [comment]
Well, it would be better if it used the same serialization. People don't really need to look at the Lexer anyway. I certainly don't ;)

**Comment by ewanmellor** [comment]
I've started with the switch back to the original ATN serialization.  The Swift deserializer isn't complete, so there's still work to do there before it will pass.  I am half-finished with this right now.

**Comment by parrt** [comment]
@ewanmellor @hanjoes need help on this?

**Comment by hanjoes** [comment]
I wish I can start working on this issue, but a little bit more context on this issue would be good. I understand we should switch away from JSON serialization to keep it consistent. I have two questions though:
1. Is this causing unit tests failures?
2. What role does ATN play in ANTLR runtime.

**Comment by parrt** [comment]
I suppose it if works, it's our biggest hurdle and we should leave it as-is.

The ATN is a state machine representing the grammar and is serialized to strings or shorts to be stored with generated parser.

**Comment by ewanmellor** [comment]
I have pushed my work-in-progress to https://github.com/ewanmellor/antlr4/tree/non-json-atn-serialization.  I will be able to pick this up again on Saturday, but you are welcome to work on it instead if you don't want to wait.

The current code at https://github.com/ewanmellor/antlr4/tree/swift-target is using JSON to serialize the ATN, rather than encoding it as a binary.  The Java target uses a binary encoding, and then puts that inside a string like "\u2014\8A\u1012" and so on.

The problem with Swift is that it doesn't use Java's escaping rules, so we can't use that serialization directly.  A Swift string would look something like "\u{2014}\u{0008}A\u{1012}".  That is obviously more bloated than the Java encoding.  There is also a big problem in the current Swift compiler, in that if you have lots of string literals joined with "+" so that you can line-wrap, then the compile is exponentially expensive, because it's trying to type-infer over all of those string appends in one go.

I tried to get around this by using a literal array of ints for the encoding.  That is what is in https://github.com/ewanmellor/antlr4/tree/non-json-atn-serialization.  I think that this was a mistake though, and just putting this in a separate file with the direct binary encoding would be better.

Alternatively, we just base-64 encode the binary, and put that in a long string literal.  I can't find any info on string length limits in Swift, but my guess is that we should at least be able to get 64k in one.

**Comment by janyou** [comment]
Another option is to make a simple json writer, to remove the dependence on the javax.json-1.0.4.jar/javax.json-api-1.0.jar.

**Comment by parrt** [comment]
Ah yes,  I don't want to add another dependency to the tool. please don't add any dependencies in pom.xml

**Comment by parrt** [comment]
@ewanmellor base-64 strings might be the right way to go.

**Comment by ericvergnaud** [comment]
@ewanmellor or an array of ints is the Swift compiler does not complain about very big arrays

**Comment by parrt** [comment]
I have looked at am ok with the JSON serialization mechanism that exists now ( @hanjoes  and I worked on it today). It is using output of ATNPrinter and stores as string literal in a separate class but the Swift runtime engine pulls that in rather than loading from file. So, we're good as-is.
