### ISSUE TITLE
Change use of OptionalValue in Swift target

### ISSUE THREAD

**Issue by ewanmellor** [antlr/antlr4#1331]
From @sharwell: Regarding the proposed change to `MultipleAlternativesWithCommonLabel.stg` I recommend a different approach than OptionalValue. Not all targets have the concept of optional values treat this particular reference as an optional value. In particular, the TypeScript target treats this as a required value (at least it does today). I recommend renaming the template to something like `<LabelAtIndex("e", 0)>`, which targets can implement as optional or required according to the way lists are exposed by the code generator for that target.

The code in https://github.com/ewanmellor/antlr4/tree/swift-target is using `OptionalValue`, so it needs to be updated.

**Comment by parrt** [comment]
Resolved differently than OptionalValue as runtime mechanism has been upgraded.
