### ISSUE TITLE
`sync()` affects valid parse

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#1338]
While resolving https://github.com/antlr/antlr4/issues/1337, I get:

TestLeftRecursion.testJavaExpressions_10, 11 fail with bad parse (input is valid) when I add

```go
p.GetErrorHandler().Sync(p)
```

to template `LL1OptionalBlockSingleAlt`:

```
Expected :(s (e (e (e (e a) . f) ( (expressionList (e x)) )) == (e (e T) . c)) <EOF>)
Actual   :(s (e (e (e (e a) . f) ( x )) == (e (e T) . c)) <EOF>)
```

@pboyer heads up ;)

**Comment by pboyer** [comment]
Thanks @parrt. I'l take a look ASAP.
