### ISSUE TITLE
antlr4-maven-plugin: code generated in wrong encoding

### ISSUE THREAD

**Issue by thraidh** [antlr/antlr4#1342]
antlr4-maven-plugin provides an option to specify the input encoding, but the output of the generator is always in the system default encoding.

If the default encoding of the project is different, this causes an uncompilable project.

I suggest that the output of the generator is always encoded in the project encoding.

Steps to reproduce:
- set project.build.sourceEncoding in you pom.xml to UTF-8
- write a lexer which contains an UTF-8 encoded character with ordinal number >127
- set your system encoding to something not UTF-8 (e.g. export LANG=en_US on linux, default on windows)
- try mvn clean install

Result:
- the generated lexer java code contains your character but in Latin1, not UTF-8

**Comment by jimidle** [comment]
Might be better to specify in \unnnn notation?






On Mon, Nov 7, 2016 at 5:37 PM +0800, "thraidh" <notifications@github.com> wrote:












antlr4-maven-plugin provides an option to specify the input encoding, but the output of the generator is always in the system default encoding.


If the default encoding of the project is different, this causes an uncompilable project.


I suggest that the output of the generator is always encoded in the project encoding.


Steps to reproduce:

set project.build.sourceEncoding in you pom.xml to UTF-8
write a lexer which contains an UTF-8 encoded character with ordinal number >127
set your system encoding to something not UTF-8 (e.g. export LANG=en_US on linux, default on windows)
try mvn clean install



Result:

the generated lexer java code contains your character but in Latin1, not UTF-8

**Comment by thraidh** [comment]
You can also set `JAVA_TOOL_OPTIONS` to `-Dfile.encoding=UTF8` as a workaround.
Using `\uNNNN` notation for characters which are on your keyboard (like umlauts) is a bit counter-intuitive, especially if the maven plugin explicitly supports input encodings other than ASCII.

The correct fix would be to change https://github.com/antlr/antlr4/blob/master/antlr4-maven-plugin/src/main/java/org/antlr/mojo/antlr4/Antlr4Mojo.java#L518 to:

    return new BufferedWriter(new OutputStreamWriter(outputStream, outputEncoding));

where `outputEncoding` is an instance variable

	@Parameter(property = "project.build.sourceEncoding")
	protected String outputEncoding;
