### ISSUE TITLE
Refactor runtime test generation mechanism

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#1347]
* separate out infrastructure code in Java.test.stg which generates unit tests in java
* separate out long members like classes, methods into actual java, go, python files and have another property of test that says "include support" code
* remove index.stg requirement, simply look for .stg files in subdirs
* ignore should generate comment in code not actual code; otherwise it requires new templates for all targets even if they ignore the test
* better doc including a template of required test templates and what the templates do
* GUI to generate new tests
* update test gen to check consistency across targets, verify all needed templates are there
* can we trap stderr/stdout to avoid massive dump of testing output; verbose flag?
* merge Base*Test.java to factor common code.

**Comment by mike-lischke** [comment]
Suggestion: parameter(s) to switch between all tests, only a single target, only a single group in a target, only a single test. Would help debugging a lot.

**Comment by parrt** [comment]
yeah, you won't believe how much i've rebuilt. See branch https://github.com/parrt/antlr4/tree/testgen-rebuild

E.g., I'm working on this file https://github.com/parrt/antlr4/blob/testgen-rebuild/runtime-testsuite/XXXTest/test/org/antlr/v4/test/runtime/xxx/java/TestParserExec.java

**Comment by mike-lischke** [comment]
Now we need new documentation how to write test the "new way" :-D

**Comment by parrt** [comment]
oh crap! i new i forgot something. adding to list right now.
