### ISSUE TITLE
New optimization for parser generator

### ISSUE THREAD

**Issue by abique** [antlr/antlr4#1354]
Hi,

The following changes in my grammar made the parsing of if statements a lot faster, but I think that antlr could have figure it itself:

```diff
if_statement
    returns [IfStatement stmt]
+   locals [Statement fstmt = null; ]
    @after { assert $stmt != null; }
    :
-
-   t='if' par_exp st=statement 'else' sf=statement {
-      $stmt = new IfStatement($par_exp.value, $st.stmt, $sf.stmt);
-      $stmt.setTextLocation($t.line, $t.pos);
-   }
-   | t='if' par_exp st=statement {
-      $stmt = new IfStatement($par_exp.value, $st.stmt, null);
+   t='if' par_exp st=statement ('else' sf=statement {$fstmt = $sf.stmt; })? {
+      $stmt = new IfStatement($par_exp.value, $st.stmt, $fstmt);
       $stmt.setTextLocation($t.line, $t.pos);
    }
    ;
```

As every rules in `if_statement` starts with `'if' par_exp st=statement'` ANTLR could have figured that it was possible to factor them.

**Comment by parrt** [comment]
Hi. Yes, I've considered auto left-factoring but decided not to implement in the end. thanks though.

**Comment by abique** [comment]
Why not?
There are a bunch of cases in my grammar which would benefit from this optimization yet they are painful and not natural (to me) to rewrite with left factoring.

**Comment by parrt** [comment]
It's up to me to decide if I'm willing to spend effort. Sorry. 25 years is enough on one project for me.

**Comment by abique** [comment]
OK I understand. Thank you for this software!
