### ISSUE TITLE
Integrate Dart Target and runtime

### ISSUE THREAD

**Issue by thosakwe** [antlr/antlr4#1367]
@tiagomazzutti [ported ANTLR4 to Dart](https://github.com/tiagomazzutti/antlr4dart.git) 3 years ago, and I think it would be nice if it were distributed with the main tool. The [runtime](https://github.com/tiagomazzutti/antlr4dart-runtime) is in its own repo, which potentially could be cloned into the antlr4 organization.

If you think this is a good idea, I will create a PR.

**Comment by parrt** [comment]
Hi. I will certainly be interested in taking a look. @tiagomazzutti can you re-base on the current master? then I can take a look

**Comment by parrt** [comment]
@thosakwe The original author looks to be busy and suggests some updates would be required to current DART. are you interested in trying to bring this forward?

**Comment by parrt** [comment]
The issue is that we'd also need to make sure all the runtime tests work. I could set up but I can't fill in any DART code.

**Comment by thosakwe** [comment]
Interested, but it will take some time. I need to learn StringTemplate
first.

**Comment by parrt** [comment]
Ok, note there is doc on basic process. https://github.com/antlr/antlr4/blob/master/doc/creating-a-language-target.md

**Comment by thosakwe** [comment]
Thanks. I'll likely just migrate the Java code, because Dart bears many
similarities to it.

First will be the runtime, then the templates.

**Comment by thosakwe** [comment]
@parrt I plan to finish by this week

**Comment by parrt** [comment]
Wow, really @thosakwe ? Including getting the runtime test thingy working? You can use other targets as a model.

**Comment by parrt** [comment]
Note that all contributors must sign the contributors.txt file. thanks!

**Comment by thosakwe** [comment]
Already signed it. :)

Java and Dart are very similar. Plus, much of the old Dart runtime can be
upgraded with minimal friction.

The tests will take some time, but hopefully it only takes a few days.

On Nov 28, 2016 8:38 PM, "Terence Parr" <notifications@github.com> wrote:

Note that all contributors must sign the contributors.txt file. thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/antlr/antlr4/issues/1367#issuecomment-263450872>, or mute
the thread

**Comment by parrt** [comment]
We would need @tiagomazzutti to sign also unless you are redoing from scratch.

**Comment by parrt** [comment]
@thosakwe I think I'll leave dart for next release. I'm now just finishing a few bugs and will release soon.

**Comment by thosakwe** [comment]
I think that would be best. Congrats on the release!

**Comment by JacobGood1** [comment]
Is a Dart target going to be in the next release?

**Comment by thosakwe** [comment]
@JacobGood1 Depends when the next release is. I'm steadily working on the [new runtime](https://github.com/thosakwe/dart_antlr4), but truth be told, there is a LOT of stuff to port. So... Cross your fingers? 

I'm eager to use ANTLR in Dart, so I guarantee that there will be continual updates.

**Comment by JacobGood1** [comment]
@thosakwe that was a quick reply... excellent!

**Comment by parrt** [comment]
Any progress guys? @thosakwe

**Comment by thosakwe** [comment]
Gonna be a while. I'm going to try to find someone else to help port,
because the API is huge and I don't have nearly as much time as I had
thought.

**Comment by thosakwe** [comment]
Unfortunately, I have little to no time to complete this. If anybody else ever starts it up, I'd be willing to assist.

But as of right now, I have no time, and the Dart community doesn't have much interest in parsing in general right now.

Sorry to disappoint. :/

**Comment by thosakwe** [comment]
I just recently used the old Dart port of ANTLR in a project, and remembered this issue. 

Attempting to redo the runtime from scratch was a way larger task than I had assumed, and I wasn't able to find anyone willing to join me, so I'm not sure that would be an option.

It would be far easier for me to fork the existing implementation, and upgrade it to current Dart APIs (although it still works right now). The problem is that the original author seems to be completely inactive, and I can't find a way to contact him. 

@tiagomazzutti

**Comment by lingyv-li** [comment]
Hi @thosakwe , I would like to help with this issue. I plan to convert current JS target to dart and upgrade the old dart code generator.
