### ISSUE TITLE
Repeated epsilon transitions in ATN from left-recursive grammar

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#1369]
See `TestATNConstruction.testForRepeatedTransitionsToStopState()`. This grammar yields extra (repeated) transitions to block end states:

```
grammar T;
s : e EOF;
e :<assoc=right> e '*' e
  |<assoc=right> e '+' e
  |<assoc=right> e '?' e ':' e
  |<assoc=right> e '=' e
  | ID
  ;
ID : 'a'..'z'+ ;
WS : (' '|'\n') -> skip ;
```

The ATNPrinter shows repeats:

```
RuleStop_e_3->BlockEnd_26
RuleStop_e_3->BlockEnd_26
...
RuleStop_e_3->BlockEnd_26
```

It looks to be the FOLLOW edges emanating from `e`'s stop state 3 to right edges of block alts to state 26. could really slow down closure that falls off end of rule.

<img width="1456" alt="screen shot 2016-11-17 at 12 30 11 pm" src="https://cloud.githubusercontent.com/assets/178777/20406344/d5e907f6-acc1-11e6-83d2-991560fd3f72.png">

**Comment by parrt** [comment]
@mike-lischke can you verify things work on your big grammar at home?  It should not have extra edges. Does it perform better?

**Comment by mike-lischke** [comment]
Yes, I had this fix added already in the C++ runtime and it work without problems.
