### ISSUE TITLE
Incorrectly tagged source code for release 4.5.3

### ISSUE THREAD

**Issue by hugheaves** [antlr/antlr4#1372]
Hi. Thanks for the great tool!

I'm using 4.5.3 in a product for which I have to be able to build the ANTLR binaries from source. However, the 4.5.3 source zip download linked on the website and in the "releases" section of GitHub is actually for 4.5.4-SNAPSHOT.

It looks like both commit b92f227 (4.5.4-SNAPSHOT) and commit 567fcc6 (4.5.3 - final version) were tagged as "4.5.3".:

https://github.com/antlr/antlr4/commits/master/pom.xml

I'm going to just use the 567fcc6 version to build 4.5.3, but thought I'd point out the discrepancy.

Thanks,
Hugh

**Comment by parrt** [comment]
oh crap. yeah, i remember having to fiddle with tags. I'm going to leave as 4.6 is coming soon.
