### ISSUE TITLE
mysql grammer / parser java code not working

### ISSUE THREAD

**Issue by dosapati** [antlr/antlr4#1380]
Just trying out [mysql grammer](https://github.com/antlr/grammars-v4/tree/master/mysql) and it's not parsing a simple SQL as expected. Did I do any mistake? My goal is to get the table name and columns names identified by the parser. Using ANTLR version 4.5.3

```
import com.my.MySQLLexer;
import com.my.MySQLParser;
import org.antlr.v4.runtime.*;
import java.io.StringReader;
public class ANTLRDemo {
  public static void main(String[] args) throws Exception {
    CharStream stream = new ANTLRInputStream(new StringReader("SELECT * FROM TAB1;"));

    MySQLLexer m = new MySQLLexer(stream);

    CommonTokenStream tokens = new CommonTokenStream(m);

    MySQLParser p1 = new MySQLParser(tokens);

    p1.getBuildParseTree();
    p1.expression();

    System.out.println("p1 = " + p1.table_name().getText() + " -->> " + p1.column_list().getText());


  }
}
```

**Comment by ericvergnaud** [comment]
Hi,
the place for support is the google discussion group.
Please close this.
Eric

**Comment by dosapati** [comment]
My apologies, can you please help me with this simple one. stuck with this for long time.
