### ISSUE TITLE
Lexer does not notify about error for token with indentical repeated commands

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#1388]
ANTLR should generate errors if token have several identical commands `skip`, `more`, `mode`, `type`, `channel` and other. At present time lexer uses the last identical command if several commands presented.

If we use the following grammar and input:
```ANTLR
lexer grammar Lexer;

channels { CHANNEL1, CHANNEL2 }
tokens { TEST1, TEST2 }

TOKEN: 'aaaa'  -> mode(MODE1), mode(MODE2);

mode MODE1;

MODE1_TOKEN: 'bbbb';

mode MODE2;

MODE2_TOKEN: 'bbbb';
MODE2_TOKEN1: 'cccc' -> type(TEST1),  type(TEST2);
MODE2_TOKEN2: 'dddd' -> channel(CHANNEL1), channel(CHANNEL2), channel(DEFAULT_TOKEN_CHANNEL);
```

**Input:**
```
aaaabbbbccccdddd
```

We will get the following type-value output in  `DEFAULT_TOKEN_CHANNEL`:

```
TOKEN(aaaa) MODE2_TOKEN(bbbb) TEST2(cccc) MODE2_TOKEN2(dddd) EOF
```

Also it does not make sense to use such commands combinations:
* `mode`, `pushMode`, `popMode` 
* `skip`, `more`, `type`.

**Comment by KvanTTT** [comment]
Maybe it's better to use warning instead of error for this issue.

**Comment by KvanTTT** [comment]
I prepared a list of command sets. 

### Reduntant
* mode(MODE1), pushMode(MODE2) - first command ignored.
* mode(MODE1), popMode - first command ignored.
* pushMode, popMode - no command.
* popMode, pushMode - no command.

### Possible but too complex (why?)
* pushMode(MODE1), mode(MODE2) - push MODE1 and straight switch to MODE2.
* popMode, mode(MODE2) - pop mode and straight switch to MODE2.

### Incompatible (and commutative)
* skip, more
* skip, type(TYPE1)
* skip, channel(CHANNEL1)
* more, type(TYPE1)
* more, channel(CHANNEL1)

`more` command also can be replaced with not yet implemented command [`less`](https://github.com/antlr/antlr4/issues/212).

### Allowed (also commutative)
* type(TYPE1), channel(CHANNEL1)

**Comment by sharwell** [comment]
Some corrections to the previous list:

* `mode(MODE1), pushMode(MODE2)`: This is not redundant. The use of `mode` changes the return state for the following `popMode`.
* `popMode, pushMode(MODE1)`: This is equivalent to `mode(MODE1)` when the stack is not empty, but would throw an exception if the stack is empty.
* `pushMode(MODE1), mode(MODE2)`: Equivalent to `pushMode(MODE2)`.

**Comment by KvanTTT** [comment]
@sharwell I fixed the table with your corrections except for first one. How `mode` command changes the state for the following `popMode`?

Also I missed the fact that two `pushMode` or `popMode` commands actually are not duplicated.

**Comment by sharwell** [comment]
@KvanTTT

> How `mode` command changes the state for the following `popMode`?

 `pushMode(X)` pushes the current mode onto stack, and then sets the current mode to `X`. Suppose you are in mode `A` and execute the following sequence:

1. Start in mode `A` with the stack `[]`
1. `mode(B)`: Now we are in mode `B` with the stack `[]`
1. `pushMode(C)`: Now we are in mode `C` with the stack `[B]`
1. `popMode`: now we are in mode `B` with the stack `[]`

If we did not execute the `mode` command, then we'd have the following behavior instead:

1. Start in mode `A` with the stack `[]`
1. `pushMode(C)`: Now we are in mode `C` with the stack `[A]`
1. `popMode`: now we are in mode `A` with the stack `[]`

**Comment by KvanTTT** [comment]
@sharwell thank you for the explanation. I got it and fixed the table. I decided not to resolve cases with `pushMode` and `popMode` commands. I'll fix cases with `skip`, `more`, `type` and `channel` commands.
