### ISSUE TITLE
[RFC] Add channel command for modes

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#1390]
In some cases it would be convenient to add tokens from certain mode to certain channel. For example: grammars with preprocessing. See [DIRECITVE_MODE in C# grammar](https://github.com/KvanTTT/grammars-v4/blob/master/csharp/CSharpLexer.g4#L254).

Instead of repeated `channel(DIRECTIVE)` command for every token:
```ANTLR
mode DIRECTIVE_MODE;

DIRECTIVE_WHITESPACES:         Whitespace+      -> channel(HIDDEN);
DIGITS:                        [0-9]+           -> channel(DIRECTIVE);
DIRECTIVE_TRUE:                'true'           -> channel(DIRECTIVE), type(TRUE);
DIRECTIVE_FALSE:               'false'          -> channel(DIRECTIVE), type(FALSE);
DEFINE:                        'define'         -> channel(DIRECTIVE);
...
```

We will able to override `channel` command only for tokens with not mode channel (`HIDDEN` channel in above mentioned sample).
```ANTLR
mode DIRECTIVE_MODE                             -> channel(DIRECTIVE);

DIRECTIVE_WHITESPACES:         Whitespace+      -> channel(HIDDEN);
DIGITS:                        [0-9]+;
DIRECTIVE_TRUE:                'true'           -> type(TRUE);
DIRECTIVE_FALSE:               'false'          -> type(FALSE);
DEFINE:                        'define';
...
```

Ideally it would be great to add something like `caseInsensitive(true)` command to modes and entire grammar. See these issues for detail: [Ignore case new syntax](https://github.com/antlr/antlr4/issues/1002), [caseInsensitive modifier](https://github.com/antlr/antlr4/issues/1069#issuecomment-170576789).

**Comment by parrt** [comment]
A very reasonable request, but given my limited time, I will have to focus on bug fixes rather than improvements.

**Comment by KvanTTT** [comment]
I can try to implement it for the next iteration if you are interested.

**Comment by parrt** [comment]
@KvanTTT I think I'd rather leave channels explicit for now.
