### ISSUE TITLE
add doc on using Swift target with antlr 4

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#1392]
Need info on how to run Swift-based parsers. Update https://github.com/antlr/antlr4/blob/master/doc/swift-target.md

**Comment by parrt** [comment]
@hanjoes maybe you can help too?

**Comment by hanjoes** [comment]
Sure, I'm willing to help. I will be in mountains in the next 3 days. Will work on this intermittently, but will make more effort when I got back.

**Comment by parrt** [comment]
Looks like we got some initial doc here from @janyou https://github.com/antlr/antlr4/pull/1396 so I will close but feel free to update guys.
