### ISSUE TITLE
javascript visitor has problems with (recursive rules and?) alt labels

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#1393]
From [stackoverflow](http://stackoverflow.com/questions/36758475/antlr4-javascript-target-issue-with-visitor-and-labeled-alternative/39180194#39180194):

*In runtime source code, ParseTreeVisitor.visit in the latest javascript runtime(4.5.2) is a bit different from python2 version(4.5.3). In python2 version, ParseTreeVisitor.visit leverage RuleContext.accept method to trigger different visitor events. I assumed developers of Antlr4 forgot to update javascript runtime.*

*There is quick workaround.* In `antlr4/tree/Tree.js`:

```
ParseTreeVisitor.prototype.visit = function(ctx) {
    // if (Utils.isArray(ctx)) {
    //  var self = this;
    //  return ctx.map(function(child) { return visitAtom(self, child)});
    // } else {
    //  return visitAtom(this, ctx);
    // }
    return ctx.accept(this)
};
```

*There is a better way which doesn't modify library function.*

```
ValidatorVisitor.prototype.visitExpr = function(ctx) {
    return ctx.accept(this);
}
```

**Comment by ericvergnaud** [comment]
already fixed
