### ISSUE TITLE
(Golang target) More than one rule element label in parser rule generates golang code that is unable to compile

### ISSUE THREAD

**Issue by syn-ful** [antlr/antlr4#1401]
Before submitting an issue to ANTLR, please check off these boxes:
 
- [x] I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [x] I have done a search of the existing issues to make sure I'm not sending in a duplicate

### Expected behavior
Go code that successfully compiles.

### Actual behavior

When trying to compile Golang code from a grammar that has multiple rule element labels, the code fails to compile.  I'm using this grammar successfully with a Python2 target.

```
$ go run ../test_parse.go 
# _/Users/c/git-repos/antlr/hosts_grammar/TEST/parser
./test_parser.go:198: _m redeclared in this block
        previous declaration at ./test_parser.go:192
```

### Steps to reproduce the behavior

Directory structure:
```
$ tree
.
├── parser
│   ├── Test.g4
│   ├── Test.tokens
│   ├── TestLexer.tokens
│   ├── test_base_listener.go
│   ├── test_lexer.go
│   ├── test_listener.go
│   └── test_parser.go
└── test_parse.go
```

Grammar:
  ***Notice multiple rule element labels in single parser rule.  It doesn't matter if the elements tags point to the same token rule (such as below with "ID") or different token rules.***
```
grammar Test;

firmwareSection
  : 'boot nxos bootflash:/' a_firmware=ID a_sup=ID
  ;

ID
  :[A-Za-z][A-Za-z0-9_\-\.\:@\$]*
  ;

WS
  :  [ \n\t]+ ->skip
  ;
```

Application code (adapted from Golang target README.md page):
```
package main

import (
    "github.com/antlr/antlr4/runtime/Go/antlr"
    "./parser"
    "os"
    "fmt"
)


type Structerize struct {
	*parser.BaseTestListener
}

func NewStructurize() *Structerize {
	return new(Structerize)
}

func (this *Structerize) EnterHostnameSection(ctx antlr.ParserRuleContext) {
	fmt.Println(ctx.GetText())
}

func main() {
	input := antlr.NewFileStream(os.Args[1])
	lexer := parser.NewTestLexer(input)
	stream := antlr.NewCommonTokenStream(lexer, 0)
	p := parser.NewTestParser(stream)
	p.AddErrorListener(antlr.NewDiagnosticErrorListener(true))
	p.BuildParseTrees = true
	tree := p.FirmwareSection()
	antlr.ParseTreeWalkerDefault.Walk(NewStructurize(), tree)
}
```

ANLTR4 command: 
```
alias antlr4-go='java -Xmx500M -cp ~/.m2/repository/org/antlr/antlr4/4.6-SNAPSHOT/antlr4-4.6-SNAPSHOT.jar org.antlr.v4.Tool -Dlanguage=Go'
```

Attempt to run go code:
```
$ go run ../test_parse.go 
# _/Users/c/git-repos/antlr/hosts_grammar/TEST/parser
./test_parser.go:198: _m redeclared in this block
        previous declaration at ./test_parser.go:192
```

The generated code tries to declare the `_m` variable twice within the same namespace scope in `test_parser.go` (line 192 & 198).
```
	p.SetState(3)

	var _m = p.Match(TestParserID)

	localctx.(*FirmwareSectionContext).a_firmware = _m

	p.SetState(4)

	var _m = p.Match(TestParserDIGIT)

	localctx.(*FirmwareSectionContext).a_sup = _m
```

**Comment by pboyer** [comment]
At first glance, this would appear to be fixed by: https://github.com/antlr/antlr4/pull/1423

**Comment by syn-ful** [comment]
Thanks @pboyer.  I was just getting ready to submit my own PR.  Glad you pointed that out.  I definitely think that will solve that problem.  I'm seeing another problem with fuzzy parsing.  I think it's similar to what @ereyes01 is seeing now.  I'll submit a separate bug for that issue.

**Comment by millergarym** [comment]
@pboyer I haven't tried it, but #1423 should fix this.
@syn-ful If you would like to test it you can find a built Antlr4 and easily go gettable code at https://github.com/millergarym/antlr4-go

**Comment by syn-ful** [comment]
Thanks @millergarym.  I just validated that this issue is fixed by https://github.com/antlr/antlr4/pull/1423.  Looks like I'm running into the same issue that https://github.com/pboyer/antlr4/pull/90 should fix now.  

Thanks for the responses.

**Comment by parrt** [comment]
@millergarym @pboyer can I close this now?

**Comment by pboyer** [comment]
Yup @parrt. Cc @syn-ful
