### ISSUE TITLE
Add support to label rules of mixed types

### ISSUE THREAD

**Issue by marcospassos** [antlr/antlr4#1409]
Currently it's allowed to label rules of mixed types, however it compiles to an invalid code.

```antlr
example: value=integer | value=string;
```
The generated parser will contain a `value` property which type is `StringContext` (because it was declared later). IMHO, the most appropriate behaviour is to declare the property as `ParserRuleContext` (all rules) or `ParseTree` (rules and tokens).

**Comment by sharwell** [comment]
Overall I like this idea. In TypeScript we can actually make the return type `(IntegerContext | StringContext)`. That said, my bigger recommendation is to avoid using labels where possible for two big reasons:

1. Labels are not set in some error handling scenarios, but using the generated accessor methods `integer()` and `string()` will work in these same scenarios.

2. Labels increase the memory overhead for nodes in the parse tree, so if you can get the same information without a label then it's a win for parsing big inputs.

**Comment by parrt** [comment]
Should probably just emit a tool error.

**Comment by KvanTTT** [comment]
I can try to fix it.

**Comment by sharwell** [comment]
For whoever fixes it, make sure there is a unit test showing the following works fine:

```antlr
example
  : value=integer # integerExample
  | value=string # stringExample
  ;
```

**Comment by KvanTTT** [comment]
Also labels work not intuitive for repetitions:

```ANTLR
rule1                         // Correct 
    : t1 = a  #aLabel
    | t1 = b  #bLabel
    ;

rule2                         // Incorrect type casting in generated code 
    : t2 = a | t2 = b
    ;

rule3                         // t3 label points on the last element of a+ sequence
    : t3 = a+
    ;

rule4                         // t4 label points on the last element of b+ sequence
    : (t4 = b)+
    ;
```

This issue related to https://github.com/antlr/antlr4/issues/1163.

**Comment by parrt** [comment]
Yeah, i think we should leave as-is but gen an error.

**Comment by KvanTTT** [comment]
We also can not use a `+=` operator for rules with different types (table updated):
```ANTLR
rule5
    : t5 += a+ b t5 += c+
    ;
```
