### ISSUE TITLE
to improve language translation

### ISSUE THREAD

**Issue by ikeas68** [antlr/antlr4#1415]
in DefaultErrorStrategy class we have message for error
but for two functions they have no expection raised
```
protected void reportUnwantedToken(Parser recognizer) {
		if (inErrorRecoveryMode(recognizer)) {
			return;
		}

		beginErrorCondition(recognizer);

		Token t = recognizer.getCurrentToken();
		String tokenName = getTokenErrorDisplay(t);
		IntervalSet expecting = getExpectedTokens(recognizer);
		String msg = "extraneous input "+tokenName+" expecting "+
			expecting.toString(recognizer.getVocabulary());
		recognizer.notifyErrorListeners(t, msg, null); // no exception
	}

	protected void reportMissingToken(Parser recognizer) {
		if (inErrorRecoveryMode(recognizer)) {
			return;
		}

		beginErrorCondition(recognizer);

		Token t = recognizer.getCurrentToken();
		IntervalSet expecting = getExpectedTokens(recognizer);
		String msg = "missing "+expecting.toString(recognizer.getVocabulary())+
			" at "+getTokenErrorDisplay(t);

		recognizer.notifyErrorListeners(t, msg, null); // no exception
	}
```

is it possible to have new exception for this two functions ? for language error translation text it's better to have the same result as reportInputMismatch for example ...

**Comment by parrt** [comment]
Can you implement an `ANTLRErrorStrategy`?

**Comment by ikeas68** [comment]
yes i have implemented SycloneErrorStrategy
extend DefaultErrorStrategy

and override
reportUnwantedToken
and
reportMissingToken

for create UnwantedTokenException (in reportUnwantedToken)
and MissingTokenException (in reportMissingToken)

but i think it's better if in error raised we have the same behavior in
each raised function ....

code for sample :
public class SycloneErrorStrategy extends DefaultErrorStrategy {

@Override
protected void reportUnwantedToken(final Parser recognizer) {
if (inErrorRecoveryMode(recognizer)) {
return;
}

beginErrorCondition(recognizer);

final Token t = recognizer.getCurrentToken();
final String tokenName = getTokenErrorDisplay(t);
final IntervalSet expecting = getExpectedTokens(recognizer);
final String msg = "extraneous input " + tokenName + " expecting " +
expecting.toString(recognizer.getVocabulary());
recognizer.notifyErrorListeners(t, msg,
new UnwantedTokenException(recognizer));
}

@Override
protected void reportMissingToken(final Parser recognizer) {
if (inErrorRecoveryMode(recognizer)) {
return;
}

beginErrorCondition(recognizer);

final Token t = recognizer.getCurrentToken();
final IntervalSet expecting = getExpectedTokens(recognizer);
final String msg = "missing " +
expecting.toString(recognizer.getVocabulary()) +
" at " + getTokenErrorDisplay(t);

recognizer.notifyErrorListeners(t, msg,
new MissingTokenException(recognizer));
}
}


2016-11-28 19:30 GMT+01:00 Terence Parr <notifications@github.com>:

**Comment by parrt** [comment]
You can throw any exception you want, new or otherwise.
