### ISSUE TITLE
antlr4 - unable to identify/parse multi-line sql comment

### ISSUE THREAD

**Issue by SomnathB** [antlr/antlr4#1416]
I am using Antlr4 for parsing oracle grammer. I am trying to read oracle file(PLSQL) as input and convert it to equivalent T-SQL construct. I have used the grammer file for plsql present in github @ - https://github.com/antlr/grammars-v4/blob/master/plsql/plsql.g4

The exact grammar which address multiple-line and single-line comment is

SINGLE_LINE_COMMENT: '--' ( ~('\r' | '\n') )* (NEWLINE|EOF) -> channel(HIDDEN); MULTI_LINE_COMMENT: '/' .? '*/' -> channel(HIDDEN);

OR

SINGLE_LINE_COMMENT: '--' ( ~('\r' | '\n') )* (NEWLINE|EOF) -> skip;
MULTI_LINE_COMMENT: '/' .? '*/' -> skip;

The issue is there with multi-line-comment. There are 2 issues that I am facing.

When my input is in the below format, its not skipping it with either of the above grammar . I want my target t-sql file should maintain the same text as output .

/* Formatted on 7/15/2015 5:37:14 PM (QP5 v5.163.1008.3004)

Anything

*/

When my input is in the below format, its give the error as mentioned below.

/* Formatted on 7/15/2015 5:37:14 PM (QP5 v5.163.1008.3004)

Author: Anyname

Anything

*/

I get the error as - Exception - Not able to parse: org.antlr.v4.runtime.misc.ParseCancellationException: line 3:8 no viable alternative at input ':Anyname'

I am new to antlr, and i see a lot of people has reported this error, however I am unable to get a proper resolution on the error. Any pointers and help would be greatly appreciated.

**Comment by parrt** [comment]
Shouldn't that be `MULTI_LINE_COMMENT: '/*'...`?  If you get ParseCancellationException then you are using bail error strategy. try not using that and see what it says.

**Comment by SomnathB** [comment]
It already has a '/*'. I think there was an issue copy-pasting above :) 

SINGLE_LINE_COMMENT: '--' ( ~('\r' | '\n') )* (NEWLINE|EOF) -> skip;
MULTI_LINE_COMMENT: '/*' .*? '*/' -> skip;

**Comment by parrt** [comment]
Are you missing `.*?` as well?

**Comment by SomnathB** [comment]
.*? is also present.

**Comment by parrt** [comment]
without a complete (small) grammar. I can't help.

**Comment by SomnathB** [comment]
This link will have the grammar. 

https://github.com/antlr/grammars-v4/blob/master/plsql/plsql.g4


There the grammar specifies. 

"//{ Rule #097 <COMMENT>
SINGLE_LINE_COMMENT: '--' ( ~('\r' | '\n') )* (NEWLINE|EOF) -> channel(HIDDEN);
MULTI_LINE_COMMENT: '/*' .*? '*/' -> channel(HIDDEN);"

My input sql file is 

/* Formatted on 7/15/2015 5:37:14 PM (QP5 v5.163.1008.3004)

Author: Anyname

Anything

*/

**Comment by SomnathB** [comment]
Does it help ? Or do you require additional details ?

**Comment by parrt** [comment]
well,I had no trouble using that grammar to parse comments so... I suggest you go to the discussion group. this site is for bugs
