### ISSUE TITLE
Consider introducing an error code property to RecognitionError 

### ISSUE THREAD

**Issue by marcospassos** [antlr/antlr4#1420]
Our team is facing a very basic problem with Antlr4: we need to throw exceptions for specific syntax errors, but we need to identify each of theses errors. We cannot just extend the classes adding a  error code, because it need to be done at the root class, the `RecognitionError`. Once Antlr uses errors not only to tell that a error happened, but also as a signal to triggers actions according to the error, we're unable to create our own root exception.

We believe it's a good ideia to add a `code` property to the `RecognitionError` class. It's a backward compatible change that would make error catching much more cleaner.

@parrt, if you agree, we would be glad to submit a PR.

**Comment by parrt** [comment]
Can't you just implement an `ANTLRErrorStrategy`?

**Comment by marcospassos** [comment]
No. Let's suppose we want to notify about a specific error, such as a missing closing parenthesis. It's a syntactic error, that we would like to throw from a rule action and catch in the listener. But, of course, we don't want to compare the error message, so we need something more reliable. Errors strategies do not help much here.

**Comment by marcospassos** [comment]
Long story short, this is what we're trying to do:
https://github.com/antlr/antlr4/blob/9a027e22971308161d4b4f08c4e23488136ca170/tool/src/org/antlr/v4/tool/ErrorType.java

**Comment by parrt** [comment]
How about rewriting this default method:

```java
	protected void reportInputMismatch(Parser recognizer,
									   InputMismatchException e)
	{
		String msg = "mismatched input "+getTokenErrorDisplay(e.getOffendingToken())+
		" expecting "+e.getExpectedTokens().toString(recognizer.getVocabulary());
		recognizer.notifyErrorListeners(e.getOffendingToken(), msg, e);
	}
```

so you pass a new exception to `recognizer.notifyErrorListeners()`?

**Comment by parrt** [comment]
that new exception can wrap old one or be totally new

**Comment by marcospassos** [comment]
Yes, but we still need a way to distinguish the errors caught in the error strategy. I can't just extend the `RecognitionException`, because there are other exception classes like `FailedPredicated` and `NoViableAlt` that are expected from the parsing engine. By the other hand, I can't just create one class per exception, otherwise we'll end up with [dozens of exception classes](https://github.com/antlr/antlr4/blob/9a027e22971308161d4b4f08c4e23488136ca170/tool/src/org/antlr/v4/tool/ErrorType.java). We also need all information currently provided by builtin exception, so our wrappers would look like proxies, what does not make too much sense.

**Comment by parrt** [comment]
Why not just create a single MarcoWrapperException with a field containing the appropriate error code and then wrap all exceptions coming from ANTLR in that?
