### ISSUE TITLE
"Getting started" should say "javac *.java" instead of "javac Hello*.java"

### ISSUE THREAD

**Issue by charlag** [antlr/antlr4#1421]
- [x] I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [x] I have done a search of the existing issues to make sure I'm not sending in a duplicate

The "Getting Started" example won't work because not all files will be compiled.
(I know you're probably sick of the problem with the examples but this is really important for newcomers).

**Comment by parrt** [comment]
`*.java` covers `Hello*.java`
