### ISSUE TITLE
Redefenition error for tokens with identical name from section and from declaration

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#1425]
Consider the following grammar:

```ANTLR
lexer grammar L;
tokens { TEST1 }
TEST1: 'a';
TEST2: 'b';
TEST2: 'c';
```

### Expected behavior
ANTLR should generate two redefenition errors for tokens `TEST1` and `TEST2`.

### Actual behavior
ANTLR generates redefinition error for only `TEST2` token.

**Comment by sharwell** [comment]
❓ What happens for the following grammar?

```
lexer grammar L;
tokens { TEST1 }
TEST1: 'a';
TEST2: 'b';
```

💭 I'm not actually sure we have a redefinition of `TEST1` at all. In ANTLR 3, you could assign a literal value to a token in a `tokens{}` block. That is no longer possible, which means there's no way in ANTLR 4 to have a true conflict here (multiple definitions for the same token).

**Comment by parrt** [comment]
Yeah, I think the tokens{} thing is really saying "it's a token" so likely no error.
