### ISSUE TITLE
Generated code works fine in java but hangs forever in Python 3

### ISSUE THREAD

**Issue by saifellafi** [antlr/antlr4#1429]
Hello,

I am parsing SAS code, which at a specific situation it has a possibility of writing single line comments:

`*this is a comment;`

the thing is, this may also happen:

`v = 5 * 29; *the * 29 is a multiplication, not a comment. but this is a comment`;

So I created this LINE_COMMENT grammar identifier:

`LINE_COMMENT    :   ([\r\n]+|';') '*' ~[\r\n;]* ';' -> channel(HIDDEN) ;`

which works fine when running grun tool to see the tree using Java code.
But running through Python3 generated code, I get

`extraneous input '*' expecting {<EOF>, <INVALID>...}`

for the piece of text \n*Hello world;

Not sure whats going on, thanks!
Saif

**Comment by saifellafi** [comment]
I realized I need to have a new line before the comment for it to work.
Not sure if there is a better way to do this though.

**Comment by saifellafi** [comment]
I was not completely wrong. Even with a new line, this grammar is making the code on Python3 hang for ever upon execution

`LINE_COMMENT    :   ([\r\n]+|';') '*' ~[\r\n]* ';' -> channel(HIDDEN) ;`

**Comment by saifellafi** [comment]
To my surprise, even this takes 5 minutes to run

`LINE_COMMENT    :   '*Some comment;' -> channel(HIDDEN) ;`

**Comment by sharwell** [comment]
@saifellafi It sounds to me like you have a semantic predicate in your grammar. Can you do a search for `}?` in your grammar and include a copy here of all lexer rules that it's found in?

**Comment by saifellafi** [comment]
Thank you @sharwell but I havent found any `}?` on my grammar rules

**Comment by saifellafi** [comment]
I think this was misleading. It does not have anything to do with the problem mentioned above.
The issue is that, as I made it so a multiplication isn't a comment, actual code to parse is bigger.

By completely removing all the comments and comment line rule, python is taking around 3 to 4 minutes to execute on a 60 lines text.

The slowness problem is somewhere else in all my grammar file.

**Comment by saifellafi** [comment]
Slowness problem comes from a simple recursive grammar:

```
assignment
 : IF assertion THEN assign_stmt (ELSE assignment)?
 ;
assertion
  : expression assertion_operator (assertion|expression)
  ;

assertion_operator
 : ( '=' | EQ | NE | GT | LT | GE | LE )
 ;
```

The mere existence of **one** ELSE statements in the target text takes the time from 4 seconds to about ~3-4 minutes

**Comment by sharwell** [comment]
@saifellafi Can you try writing `assignment` as the following?

```
assignment
 : IF assertion THEN assign_stmt (ELSE assignmentWithElse)?
 ;
assignmentWithElse
 : IF assertion THEN assign_stmt ELSE assignment
 ;
```

:bulb: This is one of the reasons I started work on a `baseContext` option. While not currently implemented in the reference release of ANTLR, the option would allow you to write the following to get the *performance* of the form I posted here while getting the *parse tree* of your original grammar.

```
assignment
 : IF assertion THEN assign_stmt (ELSE assignmentWithElse)?
 ;
assignmentWithElse
options { baseContext = assignment; } // Makes this rule also produce an AssignmentContext
 : IF assertion THEN assign_stmt ELSE assignment
 ;
```

**Comment by sharwell** [comment]
@saifellafi Can you post `assign_stmt` rule as well?

**Comment by saifellafi** [comment]
```
assign_stmt
 : expression_variable '=' expression ';'
 ;
expression_variable
 : variables
 ;
variables
 : tbd_variables
 | variables DOT variables
 | Identifier
 // place all the keywords here to resolve "keywords can also be identifiers" problem   
 | DATE
 | ALTER
 | DROP
 ;

literal
 : INT
 | FloatingPointLiteral
 | STRINGLITERAL
 | DateLiteral
 | TimeLiteral
 | DateTimeLiteral
 | BitLiteral
 | NameLiteral
 | HexLiteral
 | DOT
 ;

tbd_variables
 : MixedArgval
 ;

MixedArgval
 : Identifier Argval DOT? Junk*
 | Argval
 ;

Identifier  : [a-zA-Z_] [a-zA-Z_0-9]*;
Argval : '&' [a-zA-Z_0-9]+;
Junk : [a-zA-Z_0-9] [a-zA-Z_0-9]*;
```

```
expression
 : expression_literal
 | expression_variable
 | expression_assignment
 | <assoc=right> expression '=' expression
 | '(' expression ')'
 | expression '(' expressionList? ')'
 | expression '{' expression '}'
 | expression '[' expression ']'
 | <assoc=right> expression '**' expression
 | <assoc=right> expression_sum_op expression
 | NOT expression
 | expression MIN expression
 | expression MAX expression
 | expression expression_prod_op expression
 | expression expression_sum_op expression
 | expression ('||' | '!!' ) expression
 ;


expression_prod_op
 : ('*'|'/'|'%')
 ;

expression_sum_op
 : ('+'|'-')
 ;

expression_literal
 : literal
 ;

expression_variable
 : variables
 ;

```

**Comment by sharwell** [comment]
You might be hitting the issue we fixed just days ago (#994). Specifically, the decision `(assertion|expression)` needs to look through a complete `expression` to make a decision.

What happens if you rewrite `assertion` like this?

```
assertion
  : expression (assertion_operator expression)+
  ;
```

**Comment by saifellafi** [comment]
Thank you @sharwell . just tried that but nothing changed. still slow with one ELSE.

**Comment by sharwell** [comment]
Yeah, it's really likely this is at least impacted by the recent improvements. They were merged into the Python target in #1427 but I don't know what that means for release.

**Comment by saifellafi** [comment]
Thank you @sharwell . I am starting a mid-long term project. So I might be considering moving to Java then, as it looks like parsing times are considerably faster. Will be waiting for release!

**Comment by parrt** [comment]
@saifellafi I merged @ericvergnaud 's fix paralleling the java fix. please try with latest antlr/antlr4 build.

**Comment by saifellafi** [comment]
@parrt Thank you, but sorry I am very new to antlr and not know the release structure very well. Do you mean I should try build master from source or is there a new official release build?

**Comment by parrt** [comment]
@saifellafi yep, gotta build from src. see https://github.com/antlr/antlr4/blob/master/doc/building-antlr.md

**Comment by parrt** [comment]
Please try this 
[antlr4-4.6-SNAPSHOT.jar.zip](https://github.com/antlr/antlr4/files/643426/antlr4-4.6-SNAPSHOT.jar.zip)  If it's better, I can close. @ericvergnaud has made some changes.

**Comment by saifellafi** [comment]
@parrt 

I've just tried. Unfortunately no difference. Both **antlr-4.5.3-complete.jar** vs **antlr4-4.6-SNAPSHOT.jar** take the same time ~2.45 minutes to complete the processing. There is a warning when using snapshot though: _ANTLR runtime and generated code versions disagree: 4.5.3!=4.6_

**Comment by saifellafi** [comment]
@parrt 
I will gladly try but I'd need a python3 runtime library like this one: https://pypi.python.org/pypi/antlr4-python3-runtime

any chance you could provide such to help me test?

**Comment by parrt** [comment]
I can't upload to pypi til it's ready. can i make a copy locally and upload for you to github?

**Comment by revolucion09** [comment]
Thats more than enough, as long as it is Python3 I can just throw the library inside the python lib

**Comment by parrt** [comment]
i don't know how to do that. can't you just clone and do setup.py install or whatever?

**Comment by saifellafi** [comment]
(sorry I used wrong account -->
Thats more than enough, as long as it is Python3 I can just throw the library inside the python lib
)

Okay, I will find the git repo and clone it, just wanted to ask you since you know the better which snapshot version you used so it matches with the Jar file you proposed :)

**Comment by parrt** [comment]
Here's the link to download https://github.com/antlr/antlr4/archive/master.zip

**Comment by saifellafi** [comment]
I am sorry. I tried but cannot proceed with building this myself. Got huge amount of maven and proxy enterprise blocks all around. The only thing I can do know is having the python3 runtime library compiled and I can throw it inside Python3/lib/site-packages

**Comment by parrt** [comment]
ok, we can test after release unless you can tell me how to get you the package w/o releasing it.

**Comment by saifellafi** [comment]
If you have ANTLR4 snapshot master built on your pc and are able to 'import antlr' in python3, then it means you have the library available at PYTHON_PATH/Lib/site-packages/antlr4, if you could zip such folder and upload it for me, then I can try it. 

If you cannot, you can build antlr4 for python (not sure about the process: https://github.com/antlr/antlr4/blob/master/doc/building-antlr.md) but this will generate the runtime libraries for all languages including Python, for which you should find somewhere the antlr4 folder with python3 runtime code

**Comment by parrt** [comment]
[antlr4.zip](https://github.com/antlr/antlr4/files/649874/antlr4.zip)

@saifellafi try this zip of that antlr4 dir

**Comment by saifellafi** [comment]
Tried it and it works fine. Went down from 2.45min to almost instant processing time to parse recursive test!

**Comment by parrt** [comment]
Woot! @ericvergnaud fyi
