### ISSUE TITLE
Different getText() behavior for C++ target

### ISSUE THREAD

**Issue by samtatasurya** [antlr/antlr4#1434]
Hi,

I am currently trying out ANTLR 4 C++ target. Although I understand that it is still in development, I noticed one bug that results in different behavior when using `getText()` than that of Java target.

In C++, `getText()` returns a string in which the tokens are separated by a comma and a space, i.e. `", "`. On the other hand, Java target returns a string which results from direct appending of the tokens.

After tracking the root cause, the difference comes from this:
**RuleContext.java, line 161**
`builder.append(getChild(i).getText());`

**RuleContext.cpp, line 82**
`ss << ", ";`

While it seems trivial, it causes unexpected outputs when porting existing codes from Java to C++.

@mike-lischke Do we expect the C++ target to be fixed and followed the Java target (the _de facto_ target) behavior, or it will remain like this?

**Comment by mike-lischke** [comment]
In an attempt to make the getText() output more readable I adjusted the producing code. But later I found that this output is also used in testingm, so I reverted it mostly. If there is still something left like here this just needs to be made like it is done in the Java target. The getText() function is rather a debugging means, so it's output format really shouldn't matter (but easily consumable by humans).

**Comment by samtatasurya** [comment]
Hi Mike, thanks for the reply.
So, would you suggest to leave the current C++ `getText()` as-is?

**Comment by mike-lischke** [comment]
I wrote: "If there is still something left, like here, then it just needs to be made like it is done in the Java target." and this is one of the things that must be changed back yet. If you like you can do it yourself and offer a patch here.

**Comment by samtatasurya** [comment]
Okay noted. I misunderstood your full explanation earlier.

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/issues/1440
