### ISSUE TITLE
Help Needed in Antlr parsing performance issue

### ISSUE THREAD

**Issue by SomnathB** [antlr/antlr4#1442]
We are facing issues with antlr performance for parsing oracle files. The oracle files for conversion has significant large size 17/24/38 mb files. While building the parsetree, it taking a lot of time and memory. Its  even giving core OOM dump. We tried disabling the building of parse tree, however that doesnot work as the walker doesn’t go thru the files and generates a blank file. We tried to use  BufferedInputStream in place of FileInoutStream, We even tried to use 
BufferedTokenStream,  UnbufferedCharStream,  UnbufferedTokenStream, instead of the other respective or equivalent stream for parser and lexer. None of the options  are working and the parse tree is taking a lot of memory and time to be generated and traversed. We tried running with 2 Gigs of heap memory as well , however it goes beyond that and gives core OOM dump . 

From the online forums it seems this is a very common  problem in antlr when it tries to parse large input files. As alterative it either suggests to break down the input files into multiple small files . It also says that we can leave aside listeners and visitors and create objects directly in the grammer and use hashmaps/vectors.

http://stackoverflow.com/questions/36602692/are-there-any-good-examples-to-references-where-setbuildparsetree-false
http://stackoverflow.com/questions/17500291/can-antlr4-java-parser-handle-very-large-files-or-can-it-stream-files/26120662#26120662
http://stackoverflow.com/questions/16432469/is-it-possible-to-parse-big-file-with-antlr

Have you encountered any such antlr problems in the past and if yes how was it handled? Any suggestions that would help in reducing the memory footprint and make the performance faster specific to antlr? 

The input file mostly contains selects and insert statements. but these files are large volume. 
"
INSERT INTO crmuser.OBJECT_CONFIG_DETAILS(
ATTRIBCONFIGID,OBJCONFIGID,ATTRIBNAME,PARENTNAME,ISREQUIRED
,ISSELECTED,READACCESS,WRITEACCESS,DEFAULTLABEL,CONFIGLABEL
,DATATYPE,ISCOMPOSITE,ISMANDATORY,ATTRIBSIZE,ATTRIBRANGE
,ATTRIBVALUES,ISWRITABLE)
VALUES ( 
91933804, 1682878, 'ACCOUNTS_EXTBO.RELATIVE_MEMBER_ID', 'ACCOUNTS_EXTBO', 
'N', 'Y', 'F', 'F', 'ACCOUNTS_EXTBO.RELATIVE_MEMBER_ID', 
'ACCOUNTS_EXTBO.RELATIVE_MEMBER_ID', 'String', 'N', 'N', 50, 
null, null, 'N')
;

INSERT INTO crmuser.OBJECT_CONFIG_DETAILS(
ATTRIBCONFIGID,OBJCONFIGID,ATTRIBNAME,PARENTNAME,ISREQUIRED
,ISSELECTED,READACCESS,WRITEACCESS,DEFAULTLABEL,CONFIGLABEL
,DATATYPE,ISCOMPOSITE,ISMANDATORY,ATTRIBSIZE,ATTRIBRANGE
,ATTRIBVALUES,ISWRITABLE)
VALUES ( 
91933805, 1682878, 'ACCOUNTS_EXTBO.ELIGIBILITY_CRITERIA', 'ACCOUNTS_EXTBO', 
'N', 'Y', 'F', 'F', 'ACCOUNTS_EXTBO.ELIGIBILITY_CRITERIA', 
'ACCOUNTS_EXTBO.ELIGIBILITY_CRITERIA', 'String', 'N', 'N', 50, 
null, null, 'N')
;

"

**Comment by sharwell** [comment]
This behavior is highly dependent on the actual grammar in use, and to a lesser extent the input. If possible, can you include those?

Also, have you tried running with my fork of ANTLR (it's in the com.tunnelvisionlabs group ID on Maven)? Most of the optimizations it contains center around reducing the memory footprint during parsing, which can have a dramatic impact depending on the actual type of problems you are facing.

**Comment by SomnathB** [comment]
Hi Sam,
 This is the grammar file I am using. PFB the link to the plsql grammar file. 
https://github.com/antlr/grammars-v4/blob/master/plsql/plsql.g4. 

Thanks for pointing to another version of antlr. I will try to use it and see if  that helps.

**Comment by sharwell** [comment]
@SomnathB The maximum lookahead I saw for the expressions you gave is k=2. At least for this input, it seems the memory overhead is *not* due to complex parsing operations. You can confirm this by checking if you run out of memory when you are not building parse trees, but are running out of memory when you are building parse trees.

Try increasing the available memory to something like `-Xmx12g` and see if that resolves the problem.

**Comment by KvanTTT** [comment]
What runtime are you using?
With sharwell C# runtime I take the following result for your pl/sql code fragment (in seconds):

```
Total parse time:      00:00:00.0944427
  ANTLR lexing time:   00:00:00.0131789
  ANTLR parsing time:  00:00:00.0478179
```
