### ISSUE TITLE
Conversion error when build cpp target

### ISSUE THREAD

**Issue by ivan-khudyashev** [antlr/antlr4#1443]
Error when make test grammar.
> antlr4_runtime/cpp/demo/Linux/main.cpp:28:42: error: conversion from ‘antlrcpptest::TParser::MainContext*’ to non-scalar type ‘Ref<antlr4::tree::ParseTree> {aka std::shared_ptr<antlr4::tree::ParseTree>}’ requested
>    Ref<tree::ParseTree> tree = parser.main();
> demo/CMakeFiles/antlr4-demo.dir/build.make:62: ошибка выполнения рецепта для цели «demo/CMakeFiles/antlr4-demo.dir/Linux/main.cpp.o»
> make[2]: *** [demo/CMakeFiles/antlr4-demo.dir/Linux/main.cpp.o] Ошибка 1
> CMakeFiles/Makefile2:252: ошибка выполнения рецепта для цели «demo/CMakeFiles/antlr4-demo.dir/all»
> make[1]: *** [demo/CMakeFiles/antlr4-demo.dir/all] Ошибка 2
> Makefile:127: ошибка выполнения рецепта для цели «all»
> make: *** [all] Ошибка 2

Sequence of actions.
I. Download zip-archive project https://github.com/antlr/antlr4/archive/master.zip
II. Unpack zip-archive into directory: `sompath/antlr4_runtime/cpp`
III. Download into directory `sompath/antlr4_runtime/cpp` file antlr4-4.5.4-SNAPSHOT.jar from here:
http://www.soft-gems.net/index.php/tools/49-the-antlr4-c-target-is-here
link for download: http://www.soft-gems.net/supplement/download.php?ID=105
IV. Execute command from Readme.md
1. `cd sompath/antlr4_runtime/cpp`
2. `mkdir build && mkdir run && cd build`
3. `cmake .. -DANTLR_JAR_LOCATION=sompath/antlr4_runtime/cpp/antlr4-4.5.4-SNAPSHOT.jar -DWITH_DEMO=True`
4. `make`
**ERROR**

Conditions:
OS: Ubuntu 16.04.1 LTS
`java -version`:  
> openjdk version "1.8.0_111"
> OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
> OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

`g++ --version`: 

> g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by gaulouis** [comment]
Hello, Maybe the compiler has an impact

The [documentation](https://github.com/antlr/antlr4/blob/master/doc/building-antlr.md) say : clang (for C++ target)

Try to instal Clang

**Comment by ivan-khudyashev** [comment]
@gaulouis thanks for reply, i install Clang, but this is not help: same error.

**Comment by gaulouis** [comment]
If you set the WITH_DEMO to False the compilation succeeds
``cmake .. -DANTLR_JAR_LOCATION=sompath/antlr4_runtime/cpp/antlr4-4.5.4-SNAPSHOT.jar -DWITH_DEMO=False``

**Comment by ivan-khudyashev** [comment]
@gaulouis that's great work, thank you! After replace this `Ref<tree::ParseTree> tree = parser.main();` on this `TParser::MainContext* tree = parser.main();` it is successfully comply and get executable example
