### ISSUE TITLE
What’s the meaning of _input.LT(1)

### ISSUE THREAD

**Issue by LinZhang1004** [antlr/antlr4#1454]
On page 210 of "The Definitive ANTLR 4 Reference," there is a code as follows:
`
keyIF : {_input.LT(1).getText().equals("if")}? ID ;
`
Can anyone tell me what’s the meaning of _input.LT(1)? Thanks.

**Comment by KvanTTT** [comment]
Please read carefully issue template before issue creation:
```
 Before submitting an issue to ANTLR, please check off these boxes:
 
- [ ] I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [ ] I have done a search of the existing issues to make sure I'm not sending in a duplicate
```

**Comment by sharwell** [comment]
`_input.LT(1)` returns the `Token` instance for the next token. In this example, the grammar itself only enforces that `keyIF` matches an `ID`. The predicate further restricts the rule to only match an ID whose text is identical to `if`.

**Comment by LinZhang1004** [comment]
Dear sharwell, thank you for your quick reply. I still want to make sure I understand what you said. `_input.LT(1)` returns the `Token` instance for the next token, where "the next token' is `expr`, right?
