### ISSUE TITLE
What is the meaning of different values of invokingState?

### ISSUE THREAD

**Issue by LinZhang1004** [antlr/antlr4#1455]
On page 269 of "The Definitive ANTLR 4 Reference," there is a code as follows:

```
public class CSVParser extends Parser {
       ...
       public final RowContext row(String[] columns) throws RecognitionException {
              RowContext _localctx = new RowContext(_ctx, 4, columns);
              enterRule(_localctx, RULE_row);
              ...
       }
       ...
}
```

On page 270 of "The Definitive ANTLR 4 Reference," there is a code as follows:

```
public final AContext a(Map<String,String> x, int y) throws RecognitionException {
       AContext _localctx = new AContext(_ctx, 0, x, y);
       enterRule(_localctx, RULE_a);
       ...
}
```

Are the "4" and "0" in the above codes the values of invokingState? If yes, what's the the meaning of different values of invokingState? Thanks.

**Comment by sharwell** [comment]
The invoking state performs a function similar to the call stack you see for a thread while executing Java code. It roughly identifies the location in the grammar from which the current rule was called.

:memo: In the actual generated code, the numbers `4` and `0` do not appear as constants, but rather as a call to `getState()`.

**Comment by parrt** [comment]
@LinZhang1004 please stop asking questions here
