### ISSUE TITLE
[Cpp] namespace pollution of the antlr4 namespace from generated lexer/parser

### ISSUE THREAD

**Issue by Naios** [antlr/antlr4#1457]
50646a6da8

Generated C++ parsers and lexers are making the `antlr4` scope globally available through a
`using namespace antlr4` statement in the generated *Parser.h and *Lexer.h which leads to a namespace pollution, especially when not using a custom namespace (`-package` option).

See the sources from the cpp target demo project:

TParser.h
```c++
/* parser postinclude section */

using namespace antlr4;

/* parser context section */
```

The expected behaviour is that included headers never make namespaces globally available,
which means the `using namespace antlr4` statement needs to be removed but this could break existing
code including generated headers while not fully qualifying classes in the `antlr4` namespace.

See http://stackoverflow.com/questions/5849457/using-namespace-in-c-headers for details.

**Comment by Naios** [comment]
I could open a PR for it, however I wanted to ask first whether it will be accepted because of the possible breakage of code not declaring classes as part of the `antlr4` namespace as explained above.

**Comment by sharwell** [comment]
I don't think we've had a first release of this target, so now would be the time to do it if we're going to do it. @mike-lischke What do you think?

**Comment by gaulouis** [comment]
I can do it tonight if someone can do the Java [generate one file per class](https://github.com/antlr/antlr4/issues/1456) else I continue my search...

**Comment by mike-lischke** [comment]
Right, while I made sure not to use `using namespace` in any of the runtime files I did that for the generated files and this can easily be fixed. @Naios if you are willing to do that and open a PR for merging that then go ahead. Every help is appreciated.
