### ISSUE TITLE
[runtime-testsuite][CppTarget] Do not support g++

### ISSUE THREAD

**Issue by gaulouis** [antlr/antlr4#1478]
The [building documention](https://github.com/antlr/antlr4/blob/master/doc/building-antlr.md) only mentions the compiler Clang++
However, I can build runtime-CppTarget with g++ and Clang ++ but runtime-tests for CppTarget failled at compile time with g++.

Does CppTarget need to support the g++ compiler ?

**Comment by mike-lischke** [comment]
g++ should work as well, but it is slower than using cmake (and clang). The runtime tests have a very specific task and are not of so general interest like the runtime itself, so IMO the restriction to clang for the tests is totally ok. Hence I vote for closing this issue.

**Comment by gaulouis** [comment]
I'am not sur. But if i apply this patch i have some compilation error (convertion type error ) with g++
When i run ../.travis/run-test-cpp.sh

```
diff --git a/runtime-testsuite/test/org/antlr/v4/test/runtime/cpp/BaseCppTest.java b/runtime-testsuite/test/org/antlr/v4/test/runtime/cpp/BaseCppTest.java
index 146812f..8a57a7d 100644
--- a/runtime-testsuite/test/org/antlr/v4/test/runtime/cpp/BaseCppTest.java
+++ b/runtime-testsuite/test/org/antlr/v4/test/runtime/cpp/BaseCppTest.java
@@ -587,12 +587,16 @@ public class BaseCppTest implements RuntimeTestSupport {
                String includePath = runtimePath + "/runtime/src";
                String binPath = new File(new File(tmpdir), "a.out").getAbsolutePath();
                String inputPath = new File(new File(tmpdir), "input").getAbsolutePath();
+               String cxx = System.getenv("CXX");// clang++, g++-5, ...
+               if (cxx==null || cxx.length()==0) {
+                       cxx = new String("clang++");// FIXME: with $> export CXX="clang++"
+               }
 
                // Build runtime using cmake once.
                synchronized (runtimeBuiltOnce) {
                        if ( !runtimeBuiltOnce ) {
                                try {
-                                       String command[] = {"clang++", "--version"};
+                                       String command[] = {cxx, "--version"};
                                        String output = runCommand(command, tmpdir, "printing compiler version");
                                        System.out.println("Compiler version is: "+output);
                                }
@@ -623,8 +627,9 @@ public class BaseCppTest implements RuntimeTestSupport {
                }
 
                try {
-                       List<String> command2 = new ArrayList<String>(Arrays.asList("clang++", "-std=c++11", "-I", includePath, "-L.", "-lantlr4-runtime", "-o", "a.out"));
-                       command2.addAll(allCppFiles(tmpdir));
+                       List<String> command2 = new ArrayList<String>(Arrays.asList(cxx, "-std=c++11"));
+                       command2.addAll(allCppFiles(tmpdir));
+                       command2.addAll(Arrays.asList("-o", "a.out", "-I", includePath, "-L.", "-lantlr4-runtime"));
                        if (runCommand(command2.toArray(new String[0]), tmpdir, "building test binary") == null) {
                                return null;
                        }

```

I'll investigate tomorrow

**Comment by mike-lischke** [comment]
I still think we should adjust the test system to the needs of the tests instead of the other way around. It's adding a lot of extra work to make the test so flexible, for no real benefit. What are you trying to solve with that?

**Comment by gaulouis** [comment]
I do not have Clang++ installed. But i think than Clang can not do 2 time more fast than g++.

I want to solve the ambiguity on travis
``$] cd runtime-testsuites``
``$] export TARGET=cpp``
``$] export CXX=g++-5`` if g++ is never used why use this export
``$] ../.travis/run-test-cpp.sh``
Then, on Travis serveur Clang++ is used
While, on my local machine i got an error ``Error: Can't find Clang++`` while i use CXX=g++

Travis server can run test with g++ on linux and run test with clang++ on Mac without modifing travis commands.
I think a few changes should be enough to have multi platforme tests

**Comment by parrt** [comment]
It is now building fine with g++ on travis so I'll close.

**Comment by gaulouis** [comment]
According to my experience it can't build with g++ because the command line is poorly formed.

Travis run Clang ``JDK: oraclejdk7 Compiler: clang`` on Linux
@see https://travis-ci.org/antlr/antlr4/jobs/183804197
``.Compiler version is: clang version 3.4 (tags/RELEASE_34/final)``

In my opinion, to fix the g++ build tests, wee must modify the Cpp tests templates. Because it seam than Clang++ does not make difference between  return structure and return pointer of struct. According to my tests, it is sufficient to add "*" here and there. As far as I can remember there are one test or two that fails because of it.

Anyway, I ended up installing Clang.
