### ISSUE TITLE
'Master' branch instructions for generating Go code do not work

### ISSUE THREAD

**Issue by carbocation** [antlr/antlr4#1489]
- [x] I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [x] I have done a search of the existing issues to make sure I'm not sending in a duplicate

I'm trying to generate Go code from Hello.g4. However, when I run `antlr4 -Dlanguage=Go Hello.g4` I get the error:
`error(31):  ANTLR cannot generate Go code as of version 4.5.3`

But looking over the git tags, I don't see 4.6.0 as an option:

```bash
$ git tag --list
4.0
4.0-rc-1
4.1
4.2
4.2-SNAPSHOT
4.2.1
4.2.2
4.3
4.4
4.5
4.5-rc-1
4.5-rc-2
4.5.1
4.5.1-1
4.5.1-beta-1
4.5.2
4.5.3
antlr-4.0b1
antlr-4.0b2
antlr-4.0b3
antlr4-master-4.5.3
```

Is the documentation in master just running ahead of the available code? Should I be using a different branch or tag?

**Comment by parrt** [comment]
your `antlr4` is seeing an old jar. that is the only conclusion.

**Comment by carbocation** [comment]
I'm sorry, I must be missing something. On the github.com/antlr/antlr4 master branch, [following the installation instructions](https://github.com/antlr/antlr4/blob/master/doc/getting-started.md), I see the following installation instructions:
```
$ cd /usr/local/lib
$ curl -O http://www.antlr.org/download/antlr-4.5.3-complete.jar
```

Testing my version after I follow those instructions (and the remaining instructions on that page) I can see that I've successfully installed 4.5.3:
```
$ antlr4 
ANTLR Parser Generator  Version 4.5.3
```

Then, [the Antlr Go documentation on the master branch tells us to use the 4.6.0 branch](https://github.com/antlr/antlr4/blob/master/doc/go-target.md), but this does not exist.
```
$ git checkout tags/4.6.0
error: pathspec 'tags/4.6.0' did not match any file(s) known to git.
```

So, if 4.5.3 is an old jar, but there is no 4.6.0 jar, what am I supposed to be doing differently? It seems that the instructions in the master branch (with regards to generating Go code) cannot be followed.

**Comment by parrt** [comment]
Hi @carbocation 4.6.0 has not been released, so we haven't updated the online doc yet. :)  If you tell it to use 4.5.3 jar, it will not be 4.6.0.

**Comment by carbocation** [comment]
Oooh, now I get it. I was using github, but to do that I'd really have to build it from source. If I want to use pre-built jars, I need to use the official website documentation. Thanks for helping me figure out the issue!
