### ISSUE TITLE
Strange lexer behavior

### ISSUE THREAD

**Issue by unthingable** [antlr/antlr4#1490]
(antlr4 4.5.3) It appears that the lexer rule `('0'..'9' ('0'..'9' | 'a'..'f' | 'A'..'F'))` matches all valid inputs between "00" and "9f" _except_ "01". Could that be right?

Example:
```
HexNibble: ('0'..'9' ('0'..'9' | 'a'..'f' | 'A'..'F')) ;
hexNibble: HexNibble+;

00 02 03 0f 44 01
line 1:15 extraneous input '01' expecting {<EOF>, HexNibble}
```

**Comment by unthingable** [comment]
n00b mistake, pardon. Had a conflicting parser rule elsewhere that matched "01".

**Comment by sharwell** [comment]
@unthingable :bulb: If you use separate `lexer grammar` and `parser grammar`, it is not possible to make this mistake.
