### ISSUE TITLE
Running multiple ANTLR4 lexer/parser instances in parallel threads. 

### ISSUE THREAD

**Issue by SomnathB** [antlr/antlr4#1500]
Hi Techies,
      I tried running antlr4 ( both the base version and the optimized version from tunnelvisionlabs) in parallel threads. However I dont see a difference in performance and the performance is not reducing drastically. I am running the process in the same jvm for 50 or 100 threads. I am creating separate instance of parser, lexer, visitor. However when I see the thread in visual vm it shows me the state of the threads in "monitor" and none of the thread achieve a running status in parallel at the same time. . I am attaching the thread state snapshot. 

  I have 4 cores of CPU however none of the CPU reach high usage. They are all in average of 28-30%. 

I am using executor service framework for creating the threadpool and callable interface to give me output from each thread. PFB  the code below for the antlr runner  whhich is submitted to the executor service. I have tried with Unbufferedchar/token stream and antlrinputstream/commontokenstream. The threads run in parallel, however the antlr code piece doesnot seem to run in parallel. 

Is there some configuration which I need to change to make core antlr4 code run in parallel ? Is antlr4 actually designed and enabled internally to run in parallel threads in the same jvm ? 

Note: the visitor/parser/lexer base classes are generated by the latest antlr4 tunnelvision version api.  The evalVisitor class is the implementation of the generated base visitor class. Except the logger and some property files inside the custom visitor class, nothing else is a static variable. I can pass on the custom visitor class code if required. . 

	public String call() throws Exception {
		// TODO Auto-generated method stub
		
		String pgsql="";
		StringBuffer buffer = new StringBuffer("");
		Thread t = Thread.currentThread();
		 t.setName("Thread Name -- "+threadhashcode);
		 _debugLog.debug(t.getName());
		try{
			lexer = new PLSQLLexer(strm);
			lexer.removeErrorListeners();
			lexer.setTokenFactory(new CommonTokenFactory(true));
			//lexer.addErrorListener(ThrowingErrorListener.INSTANCE);
			tokens = new UnbufferedTokenStream( lexer);
			parser = new PLSQLParser(tokens);
			parser.removeErrorListeners();
			parser.addErrorListener(ThrowingErrorListener.INSTANCE);
			tree = parser.sql_script();
			
			//tree = parser.table_declaration();
			visitor = new EvalVisitor(_configObj,_utilObj);
			pgsql = visitor.visit(tree).toString();
		}
		catch(Exception e ){
			_errLog.error(e.getMessage());
			//_errLog.error(IOUtils.toString(stream));
			_errLog.error(t.getName());
			throw e;
		}
	

![image](https://cloud.githubusercontent.com/assets/2179009/21142586/eaa8e7f4-c168-11e6-8dfa-fb432048c914.png)

![image](https://cloud.githubusercontent.com/assets/2179009/21142608/0683b648-c169-11e6-8350-88871d4c011c.png)

**Comment by parrt** [comment]
Where is it "locked"?

**Comment by SomnathB** [comment]
Got the issue finally. I looked at the thread dump and the contention is there in log4j and not antlr. I turned off logging and its resolved now.
