### ISSUE TITLE
Ability to get indented string tree 

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#1502]
At present time all runtimes have a method for getting result tree in lisp format `toStringTree`. It would be also good to have a method `toStringTreeIndented`. Indented output more applicable for string trees comparison (diff). See the sample output for input grammar and text below.

#### Grammar

```ANTLR
grammar Test;

expression
    : <assoc=right> expression '^' expression
    | expression ('*' | '/') expression
    | expression ('+' | '-') expression
    | '(' expression ')'
    | ID
    ;
    
ID:     [a-zA-Z] [0-9a-zA-Z]*;
DIGIT:  [0-9]+;
WS:     [ \t\r\n] -> skip;
```

#### Text
```
a1 * (a2 + a3 + a4 - a5 ^ a6 ^ (a8 + a9 / a10)) * a11 * a12
```

#### toStringTree method

```
(expression (expression (expression (expression a1) * (expression ( (expression (expression (expression (expression a2) + (expression a3)) + (expression a4)) - (expression (expression a5) ^ (expression (expression a6) ^ (expression ( (expression (expression a8) + (expression (expression a9) / (expression a10))) ))))) ))) * (expression a11)) * (expression a12))
```

#### toStringTreeIndented method

```
(expression
  (expression
    (expression
      (expression
        'a1'
      )
      '*'
      (expression
        '('
        (expression
          (expression
            (expression
              (expression
                'a2'
              )
              '+'
              (expression
                'a3'
              )
            )
            '+'
            (expression
              'a4'
            )
          )
          '-'
          (expression
            (expression
              'a5'
            )
            '^'
            (expression
              (expression
                'a6'
              )
              '^'
              (expression
                '('
                (expression
                  (expression
                    'a8'
                  )
                  '+'
                  (expression
                    (expression
                      'a9'
                    )
                    '/'
                    (expression
                      'a10'
                    )
                  )
                )
                ')'
              )
            )
          )
        )
        ')'
      )
    )
    '*'
    (expression
      'a11'
    )
  )
  '*'
  (expression
    'a12'
  )
)
```

Also it is usefull to have a method that returns a tree in JSON format (tree serialization in fact).

**Comment by parrt** [comment]
how about the inspect() GUI? It can show the hierarchy and the tree.

**Comment by KvanTTT** [comment]
GUI is great, but not very combortable for me. I am using my own tools and text editors.

**Comment by KvanTTT** [comment]
Also it is very useful for *.tree files in our grammars-v4 repository. See vb6 directory for example https://github.com/antlr/grammars-v4/tree/master/vb6/examples/statements

**Comment by grosenberg** [comment]
[SnippetsTest](https://github.com/grosenberg/SnippetsTest/blob/master/src/test/java/net/certiv/remark/test/TestBase.java) at line 99 has

       /**
	 * Pretty print out a whole tree. {@link #getNodeText} is used on the node payloads to get the
	 * text for the nodes. (Derived from Trees.toStringTree(....))
	 */
         public String toPrettyTree(final Tree t, final List<String> ruleNames) ...

The resulting production is an indented parse tree representation quite similar to your suggested output.  License is BSD, so feel free to adapt to your own needs.

**Comment by parrt** [comment]
Thanks, @grosenberg !

**Comment by siliconvoodoo** [comment]
I figured you could copy paste to emacs, go to lisp mode `M-x lisp-mode`.
Then install https://github.com/tuhdo/semantic-refactor
And run `M-x srefactor-lisp-format-buffer` but this package doesn't appear in my MELPA list. so downer.
