### ISSUE TITLE
The C++ target is awesome, but a tad slower

### ISSUE THREAD

**Issue by pureconfig** [antlr/antlr4#1507]
I moved a *very* complicated grammar from ANTLR3 to 4 about a year ago, but have not been able to use it much because I need the C++ backend. Last weekend, I figured I should give the recently merged C++ target a run for its money, and pipe everything through my tests.

And, WOW, everything works! I've stressed the generated parser several days now, without a single problem. I am so impressed.

The only downside is that it's a bit slower than my ANTLR3 based parser (about 10%). Not critical at all for my use case, but still an issue for some I guess. This may very well be due to the new parser algorithm hitting a snag on my grammar, not the C++ backend itself. I also realize these are the early days, I'm sure optimizations are possible in the future.

If there was a donate button somewhere, I would press it.

**Comment by parrt** [comment]
Well, I'll close this as we'll improve things over time. Glad it works!  donate button added: https://github.com/antlr/antlr4

**Comment by pureconfig** [comment]
Awesome! I hope @mike-lischke gets some of the money

**Comment by jimidle** [comment]
I had quite a lot more time to optimize the v3 C runtime than Mike has had
for the v4 C++, so it needs a little time to mature. Actually I felt there
was a lot of room for improvement in v3 and was always going to write it
again in a different way but never did!

I am sure that you will see the v4 C++ target improve and surpass the
performance of v3. The valgrind tool is extremely useful for this. In the
end the v3 C runtime spent all it's time in LA(n) :)

Jim

**Comment by mike-lischke** [comment]
I'm so glad to get such a positive feedback, thanks @pureconfig. The memory management is quite conservative atm, as stability was my top premise. I'm still thinking about how to make this faster. Also, there might here and there be bugs that prevent the C++ runtime from using some optimizations. Anyway, this will hopefully all mature over time.
