### ISSUE TITLE
Javascript Target documentation contains no reference to existing NPM package?

### ISSUE THREAD

**Issue by RobertDiebels** [antlr/antlr4#1520]
Before submitting an issue to ANTLR, please check off these boxes:
 
- [ x] I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [ x] I have done a search of the existing issues to make sure I'm not sending in a duplicate

Hi,

This is an issue about the documentation on the javascript-target. The documentation states that there is no npm package availabe for ANTLR4 (https://github.com/antlr/antlr4/blob/master/doc/javascript-target.md).

I was wondering if this: https://www.npmjs.com/package/antlr4 is your package or if it is privately mantained?

If it is actually an NPM package of your organization I think the documentation should reflect this.

Greetings, Robert.

**Comment by ericvergnaud** [comment]
Thanks, the doc needs an update

Envoyé de mon iPhone

**Comment by RobertDiebels** [comment]
@ericvergnaud No problem. Just wanted to be sure :D !

**Comment by parrt** [comment]
fixed by https://github.com/antlr/antlr4/pull/1524
