### ISSUE TITLE
C++ 4.6 target - huge lib file

### ISSUE THREAD

**Issue by pureconfig** [antlr/antlr4#1526]
The C++ target available at http://www.antlr.org/download.html contains a .a (static lib file) that's a whopping 43,7MB. 

That can't be right. My tiny parser is not so tiny anymore.

**Comment by parrt** [comment]
@mike-lischke Any ideas?

**Comment by mike-lischke** [comment]
Totally normal. Static libs contain all symbols and other build info. After compilation the binary is much smaller. If size is an issue try the dynamic lib. And, come on, what are 43MB these days ;-)

**Comment by pureconfig** [comment]
> Static libs contain all symbols and other build info.

So this is a debug build??

> And, come on, what are 43MB these days ;-)

Considering the grand total of the rest of the (embedded) application is 1.25MB, I'd say *a lot*

**Comment by parrt** [comment]
I believe it is debug lib. We should maybe make both available?

**Comment by mike-lischke** [comment]
Static libs need all the symbols anyway or you cannot create the final binary. It hasn't to do with debug vs release builds.

I have no influence on the size of the generated libraries. If you want to link statically to the ANTLR runtime you have to use the static library, regardless of its size. You can see this with any other non trivial project. Static libs are always much larger than DLLs or the final binary. This is just how it works (and not only on Windows). If size matters for you (e.g. because you want to store the library somewhere) then use the DLL and link dynamically.

**Comment by pureconfig** [comment]
> You can see this with any other non trivial project

@mike-lischke Mike, come on, don't assume I'm a total noob. I just checked *the entire boost library with all it's static libraries*, and it's 15MB *in total*. 

This is for an embedded target and I simply can't use the dynamic library.

Could you please make a release build?

**Comment by mike-lischke** [comment]
Boost is mostly header-only, no good comparison here. And as I said before, there is no debug library in the package. It's only the release libs.

I just tested this again in detail. Building a static library in VS 2015 generates a  235MB sized lib file (release configuration, in debug config it's 224MB). Then I created the demo app which links statically to this lib and the resulting size is 909KB (for debug: 5.4MB). Again: I have no influence on the size of that lib, so if you don't trust me then just build it yourself - it's very easy to do. But I can tell you that you won't see a different size.

**Comment by gaulouis** [comment]
Hi @pureconfig You know, ANTLR is open source, you have the right to improve the code.

I think you are right. On linux, with g++, I get 1.6MB for the shared library, and 3MB for the static library (antlr.4.5.4)
I have read the CMakeLists.txt and for me nothing wrong. But I'm not very talented...

I think, we can get a runtime at 400KB in pure C... So, for me, 50MB It's hard to swallow. Maybe we should incriminate Windows

**Comment by pureconfig** [comment]
@gaulouis This is macOS, 43MB

**Comment by mike-lischke** [comment]
@gaulouis Interesting that the static lib generated with gcc is so much smaller. I have seen quite a number of static libs, some really big. For Windows there is a way to make the static lib much smaller, by disabling "whole program optimization", at the cost of larger final binaries. This feature puts a lot of extra info into the static lib (size dropped to 73MB without this optimization). But here I say it again: the size of the static lib doesn't matter - you don't ship that. The final binary size is what really matters.

**Comment by pureconfig** [comment]
@mike-lischke The final binary is still too large. How about a release build so I can test?

**Comment by mike-lischke** [comment]
Good to know you are on macOS :-/

**Comment by pureconfig** [comment]
I don't know why you assumed I was on Windows.

**Comment by mike-lischke** [comment]
This is what I get on macOS:

```bash
-rwxr-xr-x  1 Mike  staff   1514640 20 Dez 10:42 antlr4-cpp-demo
drwxr-xr-x  3 Mike  staff       102 20 Dez 10:42 antlr4-cpp-demo.dSYM
-rw-r--r--  1 Mike  staff  42587992 20 Dez 10:42 libantlr4-runtime.a
-rwxr-xr-x  1 Mike  staff   1462200 20 Dez 10:42 libantlr4-runtime.dylib
drwxr-xr-x  3 Mike  staff       102 20 Dez 10:42 libantlr4-runtime.dylib.dSYM
```

43MB for the static lib and 1.5MB for the final binary. I don't believe you can't get it smaller than that without changing the entire runtime source code.

**Comment by pureconfig** [comment]
@mike-lischke OK, this is a release build?? Weird.

By the way, what's the target name for the newly released 4.6 IntelliJ plugin? I've tried cpp, cxx, c++, but the plugin says "ANTLR cannot generate c++ code as of version 4.6"

**Comment by gaulouis** [comment]
@pureconfig try "Cpp"

@mike-lischke I get 1.4MB too for the antlr-demo

@pureconfig "I don't know why you assumed I was on Windows."
Should I answer? Because the philosophy of Windows is to provide compiled libraries whereas on the Unix system the phylosophy is to compile yourself. Mac is Unix , 

@mike-lischke with option -h ls is better

**Comment by mike-lischke** [comment]
Yes, release build (debug is 49MB for the static lib, 3.6MB for the dylib and also 3.6MB for the demo).

@gaulouis ah, thanks for the ls hint.

**Comment by pureconfig** [comment]
@gaulouis "Cpp" was correct, but no files actually get generated :(

**Comment by pureconfig** [comment]
@gaulouis "Cpp" made it work, thanks!

**Comment by pureconfig** [comment]
I guess this is fine then.

**Comment by gaulouis** [comment]
Oh no! You remind me that I use freetype. You just spoiled the day.

You have right. This is the GNU philosophy, not UNIX
