### ISSUE TITLE
Python 2 - missing IllegalStateException import in PredictionContext.py

### ISSUE THREAD

**Issue by RobertPastor** [antlr/antlr4#1531]
Before submitting an issue to ANTLR, please check off these boxes:
 
- [ ] I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [ ] I have done a search of the existing issues to make sure I'm not sending in a duplicate

[cut]
Please include information about the expected behavior, actual behavior, and the smallest grammar or code that reproduces the behavior. If appropriate, please indicate the code generation targets such as Java, C#, ...  Pointers into offending code regions are also very welcome.
[/cut]

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/pull/1536
