### ISSUE TITLE
C++ target - generated files doesn't compile

### ISSUE THREAD

**Issue by pureconfig** [antlr/antlr4#1532]
I generated source for a simple grammar, and I get a lot of these:

```
error: virtual function 'getRuleIndex' has a different return type ('size_t' (aka 'unsigned long')) than the function it overrides (which has return type 'ssize_t' (aka 'long'))
    virtual size_t getRuleIndex() const override;


error: 'getSerializedATN' marked 'override' but does not override any member functions
  virtual const std::vector<uint16_t> getSerializedATN() const override;
```

@mike-lischke Am I doing something fundamentally wrong?

Compiling with CLion/clang 8.0.0/macOS Sierra.

**Comment by mike-lischke** [comment]
There is a mismatch between the runtime code and your generated files. Are you sure you have the latest C++ runtime sources? E.g. `getRuleIndex` is [defined here](https://github.com/antlr/antlr4/blob/master/runtime/Cpp/runtime/src/RuleContext.h#L83) and as you can see it returns `size_t`. So the generated code is correct.

**Comment by pureconfig** [comment]
Correct :/
