### ISSUE TITLE
Explain me Array2DHashSet

### ISSUE THREAD

**Issue by gaulouis** [antlr/antlr4#1534]
Hello,

In ATNConfigSet [configLookup](https://github.com/antlr/antlr4/blob/9e2c0f76f913b48589da1319ee1edbd9a2cc1fe8/runtime/Java/src/org/antlr/v4/runtime/atn/ATNConfigSet.java#L77) is type of Array2DHashSet (in other word, a Set of Array)
However [getOrAddImpl](https://github.com/antlr/antlr4/blob/9e2c0f76f913b48589da1319ee1edbd9a2cc1fe8/runtime/Java/src/org/antlr/v4/runtime/misc/Array2DHashSet.java#L83) use the same comparatorEquality in Set and in Array(bucket)

So for me, we only can have a Set of Array with one element.
So, i can a Set is sufficient.

Did I miss a subtlety of Java language, or i'am right ?

**Comment by sharwell** [comment]
This type exists so we can create a `Set<T>` which has a custom implementation of equality. Normally in Java, implementations of `Set<T>` use the `Object.hashCode` and `Object.equals` methods of the objects you are adding to the set to determine whether two objects are equal or not. This limitation is too restrictive for ANTLR's implementation, where we have two different sets of the same objects that use different representations of equality.
