### ISSUE TITLE
python2: Bug in IntervalSet.py:removeOne causes exception when taking complement

### ISSUE THREAD

**Issue by arifogel** [antlr/antlr4#1538]
Sorry for not including code right off, but this looks like an obvious bug with an obvious fix:
In the removeOne function in runtime/Python2/src/antlr4/IntervalSet.py, in the last elif case, a 'range' is used instead of an Interval. This causes a type error later on where an Interval is expected instead of a list.

`self.intervals[k] = range(v + 1, i.stop)`
Should be:
`self.intervals[k] = Interval(v + 1, i.stop)`

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/pull/1541
