### ISSUE TITLE
[Bug] Doxygen doc

### ISSUE THREAD

**Issue by gaulouis** [antlr/antlr4#1553]
Hello,

There are a bug In the description of RuleContext
http://www.antlr.org/api/Java/org/antlr/v4/runtime/RuleContext.html

Best regards

**Comment by parrt** [comment]
where? what?

**Comment by gaulouis** [comment]
Where:
near lines  https://github.com/antlr/antlr4/blob/master/runtime/Java/src/org/antlr/v4/runtime/RuleContext.java#L33
https://github.com/antlr/antlr4/blob/master/runtime/Java/src/org/antlr/v4/runtime/RuleContext.java#L51

What:
The documentation block show java code without formating it.
Maybe, this can be resolved with [\code](https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdcode)
```
 * \code{.java}
 *  public final SContext s() throws RecognitionException {
 *      SContext _localctx = new SContext(_ctx, getState()); <-- create new node
 *      enterRule(_localctx, 0, RULE_s);                     <-- push it
 *      ...
 *      exitRule();                                          <-- pop back to _localctx
 *      return _localctx;
 *  }
 *  \endcod
```

**Comment by sharwell** [comment]
@gaulouis :memo: Java uses Javadoc, not doxygen. The particular comment you referenced is missing *many* `{@code ...}`, `<p>`, `<pre>`, and `<code>` elements (and perhaps others).

**Comment by parrt** [comment]
thanks but i'm too lazy to fix all that ;)
