### ISSUE TITLE
Allow backticks (`) to be used to resolve symbol conflict with Swift target

### ISSUE THREAD

**Issue by therealbnut** [antlr/antlr4#1559]
Hi,

I'm getting symbol conflict errors when running antlr 4.6 with `language=Swift` on [Swift.g4](https://github.com/antlr/grammars-v4/blob/master/swift/Swift.g4) from `antlr/grammars-v4`.

```
error(134): Swift.g4:508:48: symbol operator conflicts with generated code in target language or runtime
error(134): Swift.g4:512:39: symbol associativity conflicts with generated code in target language or runtime
...
```

I believe that antlr can be patched to fix these issues with `language=Swift`.

FYI @teverett @janyou

### Expected outcome

Ideally [SwiftTarget.java](https://github.com/antlr/antlr4/tree/master/tool/src/org/antlr/v4/codegen/target/SwiftTarget.java) would not include Swift keywords in `visibleGrammarSymbolCausesIssueInGeneratedCode`, instead generated symbols using those keywords would be escaped as below:

Swift can escape tokens using backticks (`` ` ``) so you can have a reserved word like `operator` used as a variable, function, property etc. like this:
```swift
let `operator` = "hello world"
func `associativity`() -> Associativity { return .Left }
```

I tried to make these changes myself, but I'm not familiar enough with antlr to know the best place to make the change.

### Details to reproduce

I ran `antlr-4.6-complete.jar` from [here](http://www.antlr.org/download/antlr-4.6-complete.jar) on `Swift.g4` from [here](https://github.com/antlr/grammars-v4/blob/master/swift/Swift.g4) like this:
```
CLASSPATH="<path>/antlr-4.6-complete.jar:."; java -jar <path>/antlr-4.6-complete.jar <path>/grammars-v4/swift/Swift.g4  -Dlanguage=Swift 
```

I received the following output:
```
warning(180): Swift.g4::: chars "᷀-–" used multiple times in set [᷀-–]
warning(180): Swift.g4::: chars "–-⃿" used multiple times in set [–-⃿]
warning(180): Swift.g4::: chars "–-️" used multiple times in set [–-️]
warning(180): Swift.g4::: chars "–-︯" used multiple times in set [–-︯]
error(134): Swift.g4:513:0: symbol associativity conflicts with generated code in target language or runtime
error(134): Swift.g4:1025:0: symbol operator conflicts with generated code in target language or runtime
error(134): Swift.g4:320:38: symbol operator conflicts with generated code in target language or runtime
error(134): Swift.g4:375:30: symbol operator conflicts with generated code in target language or runtime
error(134): Swift.g4:506:50: symbol operator conflicts with generated code in target language or runtime
error(134): Swift.g4:507:52: symbol operator conflicts with generated code in target language or runtime
error(134): Swift.g4:508:48: symbol operator conflicts with generated code in target language or runtime
error(134): Swift.g4:512:39: symbol associativity conflicts with generated code in target language or runtime
error(134): Swift.g4:593:67: symbol operator conflicts with generated code in target language or runtime
error(134): Swift.g4:1004:53: symbol operator conflicts with generated code in target language or runtime
error(134): Swift.g4:1011:53: symbol operator conflicts with generated code in target language or runtime
error(134): Swift.g4:1023:55: symbol operator conflicts with generated code in target language or runtime
```

---

Before submitting an issue to ANTLR, please check off these boxes:
 
- [x] I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [x] I have done a search of the existing issues to make sure I'm not sending in a duplicate

**Comment by parrt** [comment]
thanks but I think this is my desired/expected behavior (the errors).  every target has different reserved symbols .

**Comment by therealbnut** [comment]
@parrt 
I'm only suggesting the SwiftTarget's behavior is modified, it shouldn't matter that every target has different reserved symbols.

My point was that Swift has a mechanism to allow you to use reserved symbols as identifiers, these errors should never need to be encountered when compiling generated Swift code.

**Comment by parrt** [comment]
You might be able to convince the swift target people to wrap the output vars in backticks.

**Comment by therealbnut** [comment]
That's what I was hoping this issue was :)

**Comment by therealbnut** [comment]
I included @teverett and @janyou as they worked on SwiftTarget, I'm not sure if there's anyone more appropriate, do you know?

**Comment by parrt** [comment]
@therealbnut haha. yeah but I'm not in favor of adding backticks around every var. Better to do like other targets: add naughty words to a list.

**Comment by therealbnut** [comment]
@parrt I was imagining that you'd only add backticks around words in that list.

**Comment by parrt** [comment]
Easy for human but possibly complicated for codegen that gens lots of symbols.

**Comment by KvanTTT** [comment]
CSharp target also have such escaping list: https://github.com/antlr/antlr4/blob/4.6/tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg#L1061

 "values" and "default" won't work for Swift target too if backticks will be implemented: https://github.com/antlr/antlr4/issues/1125

**Comment by parrt** [comment]
interesting. i had no idea the C# target did that. complicated ;)  ok, so i'll add `values` to C#.

**Comment by KvanTTT** [comment]
Already done: https://github.com/antlr/antlr4/pull/1764
