### ISSUE TITLE
visitorSuperClass and listenerSuperClass options

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#1561]
I want to have my own implementation of methods
```
Result Visit(IParseTree tree);
Result VisitChildren(IRuleNode node);
Result VisitErrorNode(IErrorNode node);
Result VisitTerminal(ITerminalNode node);
```
So it would be great to have an options `visitorSuperClass` and `listenerSuperClass` too.

**Comment by sharwell** [comment]
I'm currently :-1: for multiple reasons:

1. Interfaces are generated for the listener and visitor, allowing any implementation of these methods to be provided.
2. The specified methods are virtual, so they can be freely implemented even if you extend the base concrete implementation. In fact, the requested behavior can be provided by creating an abstract class derived from the listener and visitor.

At this time I believe this would cause more confusion and maintenance overhead than it would provide user benefits.

Do you have any examples where this would be particularly useful. I'm having trouble thinking of any.

**Comment by KvanTTT** [comment]
I have several visitor classes for different languages and want to have a common `Visit` and `VisitChildren` code for them. Anyway I can not have a common implementation without `dynamic` keyword (C# runtime) because of a generic nature of visitor class. It's not very clear.

So, I'am closing this issue for now. Sorry for inconvinience.
