### ISSUE TITLE
Antlr Maven Plugin Generated Code show error in Eclipse: Type The method enterEveryRule(ParserRuleContext) of type XXXBaseListener must override a superclass method	XXX.java	

### ISSUE THREAD

**Issue by imben1109** [antlr/antlr4#1571]
I am using Antlr Maven Plugin to test code generation. But the generated code throw the following error in Eclipse.

Description	Resource	Path	Location	Type
The method enterEveryRule(ParserRuleContext) of type XXXBaseListener must override a superclass method	XXX.java

**Comment by parrt** [comment]
hmm...i'm using the plugin (generating java) all the time and I don't see this.

**Comment by parrt** [comment]
@imben1109 can you be more specific?

**Comment by imben1109** [comment]
@parrt I make mistake in my eclipse config.  The Java Compiler is set to 1.5. The @override annotation on interface method should only apply to java 1.6 or above. This is my silly issue.
