### ISSUE TITLE
Dynamic query Parsing Issue using antlr4

### ISSUE THREAD

**Issue by SomnathB** [antlr/antlr4#1577]
We are trying to convert Oracle pl/sql to sql server t-sql. We are using the oracle grammar file as per the below url. 
https://github.com/antlr/grammars-v4/blob/master/plsql/plsql.g4.

The pl/sql block contains/forms a query dynamically like the example below. 

exec_stmt :=  'UPDATE dedupjobqueue  SET status = ''COMPLETED'' WHERE bank_id = ''' || v_bank_id ||''' AND orgkey ='''|| sorgkey||''' and JobID != '|| JobID || '';

The translation to t-sql construct is having some issues. The result being broken down incorrectly as mentioned below. Have a close look at the semicolon ";" in between the dynamic query. 

SET @exec_stmt = 'Update CORPNEGATIVEJOBQUEUE SET status=''COMPLETED'' WHERE bank_id=''';
 + @v_bank_id + ''' AND CORP_key =''' + @sorgkey + ''' and JobID != ' + @JobID + ''

It should have done it as below. 
SET @exec_stmt = 'Update CORPNEGATIVEJOBQUEUE SET status=''COMPLETED'' WHERE bank_id=''' + @v_bank_id + ''' AND CORP_key =''' + @sorgkey + ''' and JobID != ' + @JobID + ''  ;

Can someone help in suggesting if the grammar needs to be changed to handle it and any other pointers ?

**Comment by parrt** [comment]
please ask questions in the google group.
