### ISSUE TITLE
BufferedTokenStream cannot be reused after EOF

### ISSUE THREAD

**Issue by sharwell** [antlr/antlr4#1584]
Currently `BufferedTokenStream` cannot be reused after reaching EOF. The `fetchedEOF` flag is set to true when the first EOF is encountered, and `setTokenSource` does not reset it. This prevents the stream from ever attempting to fetch more tokens from the source, leaving it as empty.

Credit for finding this issue goes to @JanCervak, who reported it in tunnelvisionlabs/antlr4cs#136.

**Comment by parrt** [comment]
Hmm..so you've changed your mind about this? ;) https://github.com/antlr/antlr4/issues/895

**Comment by sharwell** [comment]
@parrt No, that issue relates to a different method.

**Comment by parrt** [comment]
yup, but you argued against due to changes in public api. let's change both :)

**Comment by sharwell** [comment]
@parrt These are totally different scenarios. `reset` works fine as documented but `setTokenSource` leaves the stream in an unusable state.

**Comment by parrt** [comment]
but reset didn't work for me as it didn't reset eof flag

**Comment by sharwell** [comment]
@parrt If `reset` were to clear the buffer, it would also need to reset the `TokenSource` it draws from to the original state used for the stream. That might not be possible, since the `TokenSource` might not have been positioned at the beginning of some input. It sounds like the original issue that led to #895 is someone tried to use `reset()` when they actually needed the behavior of `setTokenSource`. However, if `setTokenSource` were used it would still be broken due to the issue here.

**Comment by sharwell** [comment]
💭 Between `seek(0)` and `setTokenSource(source)`, perhaps the solution here is to leave `reset` as-is but mark it `@Deprecated`. That removes the confusion without breaking anyone currently using it successfully.

**Comment by sharwell** [comment]
@parrt I found many examples in the wild of users calling `reset()` instead of `seek(0)` to reset the token stream for the fallback part of two-stage parsing strategy. If the semantics of `reset()` were changed as proposed, all these cases would break because the fallback stage would not be parsing the same set of tokens as the first stage.
