### ISSUE TITLE
Maven Plugin doesn't agree with IDEA Plugin on location of `.tokens` files

### ISSUE THREAD

**Issue by CAD97** [antlr/antlr4#1593]
This is an issue when running separate `lexer grammar` and `parser grammar` (thus using `options { tokenVocab = MyLexer ; }`).

File Structure:

```
Project
| 📁 src
| | 📁 main
| | | 📁 antlr4
| | | | 📁 imports
| | | | 📦 some.package
| | | | | 📄 MyLexer.g4
| | | | | 📄 MyParser.g4
| 📁 target
| | 📁 generated-sources
| | | 📁 antlr4
| | | | 📦 some.package
| | | | | 📄 MyLexer.java
| | | | | 📄 MyParser.java
| | | | 📄 MyLexer.tokens
| | | | 📄 MyParser.tokens
| 📄 pom.xml
```

The configuration for each `.g4` is correct (`~` means path to project)

```
Output directory where all output is generated | ~\target\generated-sources\antlr4
Location of imported grammars                  | ~\src\main\antlr4\imports
Grammar file encoding; e.g., euc-jp            | UTF-8
Package/namespace for the generated code       | some.package
Language (e.g., Java, Python2, CSharp, ...)    | Java
```

The IDEA plugin looks for the `.tokens`s in the folder `~/target/generated-sources/antlr4/some/package`, but the maven plugin puts them in `~/target/generated-sources/antlr4`.

IMHO, it makes more sense for the `.tokens` to be generated in the corresponding package where the generated code is located. This means that projects with grammars in multiple packages will have the `.tokens` files in the folders alongside the generated sources, instead of flat in the root of the generated sources folder.

I've uploaded a zip of a minimal reproduction case to a GitHub Gist. Note that the ANTLR file configuration has a `~` in the paths rather than the path to the project (as I don't know where you're putting the project). https://gist.github.com/CAD97/d607d5b7965b640949c80e9ec3231830

As this is a disagreement between the Maven plugin and the IDEA plugin, I've created this bug on both repositories.
antlr/intellij-plugin-v4: https://github.com/antlr/intellij-plugin-v4/issues/293
antlr/antlr4/antlr4-maven-plugin: https://github.com/antlr/antlr4/issues/1593

**Comment by parrt** [comment]
Hi @CAD97 . verrrrry interesting.  I think the tool expects to gen `.tokens` files at the root of the output dir. The package thing is for the target language. So likely maven plugin is doing "right" thing.  Safe thing is for me to update plugin to look in both places. Would that solve the issue(s)?

**Comment by CAD97** [comment]
Wherever the base tool by itself puts the `.tokens` files by default is "right", as the base tool is what we're automating with the plugins.

Accepting either would probably be the beatnik path forward - "be generous in what you accept, and strict on what you output" etc. - and would allow the two plugins to be used in tandem.

So yes, accepting `.tokens` files from either location would indeed make this a non-issue, so long as there is a sane default if (for some bizzare reason) (duplicate) files are present in both locations. (I woul suggest in the case of a conflict, default to the current behavior and print a warning to clean the project and eliminate the conflict.)

**Comment by parrt** [comment]
Actually, is this related to https://github.com/antlr/antlr4/issues/1087 ?

**Comment by parrt** [comment]
It looks like mvn plugin generates to `${project.build.directory}/generated-sources/antlr4` with `-o` option which will write .tokens and oh wait. It uses a custom `Tool` that alters standard tool behavior to write generated code using dir structure it sees for .g4 files.  Hmm...ok, so maven plugin differs from default on command line. I'm going to leave both and just make the intellij antlr plugin look in more places.  That should solve both.
