### ISSUE TITLE
unable to resolve ArrayInitLexer and ArrayInitParser in definitive antlr4 book

### ISSUE THREAD

**Issue by RajaPotluri** [antlr/antlr4#1598]
Before submitting an issue to ANTLR, please check off these boxes:
 
- [x] I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [ ] I have done a search of the existing issues to make sure I'm not sending in a duplicate

[cut]
when i tried example arrayinit Test.java i am getting an error with ArrayInitLexer and ArrayInitParser those are not included in org.antlr.v4.runtime.* or org.antlr.v4.runtime.tree.*. how do i solve the issue and make the code compile.
package sample;

//import ANTLR's runtime libraries
import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;

public class antlr_test {

	public static void main(String[] args) throws Exception{
		// TODO Auto-generated method stub
		// create a CharStream that reads from standard input
		
		ANTLRInputStream input = new ANTLRInputStream(System.in);
		
		//create a lexer that feeds off of inputCharStream
		ArrayInitLexer lexer = new ArrayInitLexer(input);
		
		//create a buffer of tokens pulled from the lexer
		CommonTokenStream tokens = new CommontokenStream(lexer);
		
		//create a parser that feeds off the tokens buffer
		ArrayInitParser parser = new ArrayInitParser(tokens);
		
		ParseTree tree = parser.init(); // begin parsing at init rule
		System.out.println(tree.toStringTree(parser));
		
		

	}

}

[/cut]

**Comment by mike-lischke** [comment]
@RajaPotluri Can you please edit your question to follow the style of the others? That means: a short heading which is shown in the bug list, remove the [cut][/cut] part, which is there to remind you and not meant to be left in and then describe your problem in the main text instead. Thanks.

**Comment by parrt** [comment]
no doubt didn't run antlr on the grammars.

**Comment by drogbababa** [comment]
I meet the same problem in eclipse, Do you figure it out?

**Comment by robertdwornik** [comment]
You have to add a dependency to project by creating lib folder at the top of your project and put *.jar file there. If you use vs code add "Maven for Java" extension.
