### ISSUE TITLE
Important: license files removal is bad

### ISSUE THREAD

**Issue by mike-lischke** [antlr/antlr4#1600]
Before submitting an issue to ANTLR, please check off these boxes:
 
- [x] I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [x] I have done a search of the existing issues to make sure I'm not sending in a duplicate

In revision [efc3f82] all license files were removed from various targets, which is a bad idea. Not only breaks it e.g. the source provisioning script in the C++ target, it also leaves it without an explicit license description which is necessary when you e.g. distribute source code via Linux distros. Many people expect a license file in the root folder of the source folder and we can get into trouble with Linux distro maintainers if we don't have a license file. Finally, I can imagine that these files are legally required by certain companies. So I'd vote for reverting this patch.

**Comment by sharwell** [comment]
@mike-lischke Your build should now be pulling the license file from the root of this repository for inclusion in the distribution.

**Comment by mike-lischke** [comment]
Ah, I should have looked there first. Thanks.
