### ISSUE TITLE
Lexer command 'more' is over-inclusive.

### ISSUE THREAD

**Issue by grosenberg** [antlr/antlr4#1605]
Consider:

    @tokens { STUFF } 

    @members {
        protected void handleEndAction() {
            popMode();
            if (_modeStack.size() > 0) {
                setType(STUFF);
            }
        }
    }

    BEGIN   : '{' -> pushMode(Stuff) ;

    mode Stuff;

        NESTED         : LBrace    -> type(STUFF), pushMode(Stuff)   ;
        END               : RBrace    { handleEndAction(); };

        KEYWORD1    : WORD1;
        KEYWORD2    : WORD2;

        OTHER       : .    -> type(STUFF), more   ;

Absent nesting and keyword matches, all of the content that is matched by the `OTHER` rule winds 
up prepended to the textual content of the `END` token. No `STUFF` tokens are emitted.

With nesting and/or keyword matches, `STUFF` (only in the case of nesting) and keyword tokens will be emitted, though with textual content entirely dependent on preceding `OTHER` matches. In other words, variable. 

While not significant if only token type is considered, often the token content must be evaluated. Irrelevant prepended content complicates this. Currently, the only practical alternative is to not use the `more` command and suffer generation of a lot of single character tokens if skipping is not acceptable.

Rather than glomming onto the first non-more'd token, i.e., being over-inclusive, a better behavior would be for the `more` command to only apply to matches of its own lexer rule.

For the input `{any non-keyword text}`, compare the results:

    BEGIN[text='{'] END[text='any non-keyword text}']                  // existing behavior
    BEGIN[text='{'] STUFF[text='any non-keyword text'] END[text='}']   // rationalized behavior

Whether to change the behavior of the existing  command, introducing a possibly breaking change, add another command, or other is left as an open question.

The rationalized behavior could solve (IIUC) the problem identified in Issue #1433.

**Comment by sharwell** [comment]
The shortest way to get the behavior you want is probably to not use the `more` command, and instead create a `TokenSource` implementation that sits between your `Lexer` and your `TokenStream` for the purpose of combining adjacent `OTHER` tokens into a single `OTHER` token. Or you can go the direction of [**PositionAdjustingLexer.g4**](https://github.com/antlr/antlr4/blob/master/tool-testsuite/test/org/antlr/v4/test/tool/PositionAdjustingLexer.g4) and split tokens that contain more than you wanted in a single token.

To get the behavior you want from the grammar alone (no extra actions or post-processing), you'd probably need to use modes and zero-length tokens (both supported) along with lookahead assertions (not supported).

**Comment by grosenberg** [comment]
@sharwell : thanks for the offered help. I already understand, however, there are many ways to work around the issue, have done so, and would not have raised the issue here for that purpose.

The purpose of the issue was to identify a use case, whose nature appears to be **exactly** what the `more` command was intended to address, but does so in-elegantly at best. And, requires clumsy, fragile workarounds instead.

Ideally, the `more` command (or something similar) should handle this case cleanly. The simplest, most direct way, I suggest, would be to limit the glomming of the `more` command to its own lexer rule. To modify the existing behavior would only require a small modification to the `Lexer` class -- the existing behavior implementation is very simple.

Perhaps there are cases where the rationalized behavior would not be desirable (other than because it could be a breaking change). But I cannot identify any.

**Comment by parrt** [comment]
Hi guys. this'd be a low priority for me so I'm closing to clean up issues list.

**Comment by cutephoton** [comment]
I encountered this issue so I thought I'd ack this to let maintainers know it would be beneficial. My interpretation of the proposal above is to offer a 'more-like' operator that instead provides auto-merging of same tokens until something better comes around. Hopefully I'm right about that. :)

> The shortest way to get the behavior you want is probably to not use the `more` command, and instead create a `TokenSource` implementation that sits between your `Lexer` and your `TokenStream` for the purpose of combining adjacent `OTHER` tokens into a single `OTHER` token. Or you can go the direction of [**PositionAdjustingLexer.g4**](https://github.com/antlr/antlr4/blob/master/tool-testsuite/test/org/antlr/v4/test/tool/PositionAdjustingLexer.g4) and split tokens that contain more than you wanted in a single token.
> 
> To get the behavior you want from the grammar alone (no extra actions or post-processing), you'd probably need to use modes and zero-length tokens (both supported) along with lookahead assertions (not supported).

One of the proposed workaround of combining tokens involves a lot of unnecessary object creation and destruction. The PositionAdjustingLexer might work, but if you plan to use more than one backend, it appears cumbersome to support. It feels like it ought to be a one-liner like more.

It would be pretty low on my priorities too so I understand why it's closed. :)
