### ISSUE TITLE
Add a new option for naming convention of generated classes and Visitor, Listener methods

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#1615]
Consider the [tsql](https://github.com/antlr/grammars-v4/blob/master/tsql/tsql.g4) grammar. It has been written in **snake_case** naming convention for parse rules. But if I use C# runtime the ugly `Visit_sql_clause` methods are generated instead of pleasant methods in C# code convention: `VisitSqlClause`.

So, I suggest to introduce a new option `naming-convention` with the following list of values:

* **PascalCase**: `VisitRootRule`
* **CamelCase**: `visitRootRule`
* **SnakeCase**: `visit_root_rule`
* **SnakeCaseUpper**: `VISIT_ROOT_RULE`
* **Runtime**: dependent on runtime naming convention (PascalCase for C#, camelCase for Java, etc.)
* **NotChange**

By default `NotChange` value will be selected.

**Comment by KvanTTT** [comment]
Also an option **indent** with `tabs` and `spaces` values can be added.

**Comment by bramp** [comment]
Should this be an option, or just a detail that the target language decides? I'm not sure if ever want the Go target to generate anything but PascalCase, and if I did specify say camel case, the act of lower casing the first letter makes the Go API non public.

**Comment by KvanTTT** [comment]
I don't know the best solution. On the one hand, different projects can use different code styles. on the other - single runtime option simplifies and unifies processing.

**Comment by raizam** [comment]
A solution is really needed for the C# target...
generated snake_case should be replaced by PascalCase...
cc @parrt

**Comment by KvanTTT** [comment]
For now, I think it's better to use the runtime style without an option for simplicity.

**Comment by parrt** [comment]
Yeah, even though the generated classes are weird I hesitate to make such a huge change as it would break all existing code in projects that use generated parsers.

**Comment by KvanTTT** [comment]
You are also against a new option like `-runtimeNamingConvention` that allows names transformation to runtime style, aren't you? Because it requires more tests and users will report issues both with disabled and enabled option that complicates everything.

**Comment by parrt** [comment]
Yep, each option doubles the state space of the program.

**Comment by parrt** [comment]
I think I'll close for now.

**Comment by SuperJMN** [comment]
Is it so difficult to add a naming convention option to comply better with the generated code? for C# it's a complete mess.
