### ISSUE TITLE
[CSharp] &rarr; (Right arrow) escaping in XML Comments

### ISSUE THREAD

**Issue by xied75** [antlr/antlr4#1618]
Currently if we build CSharp runtime with either VS or dotnet cli, we get these warning messages:

```
/home/dong/github/fork/antlr4/runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Atn/ParserATNSimulator.cs(260,57): warning CS1570: XML comment has badly formed XML -- 'Reference to undefined entity 'rarr'.'
/home/dong/github/fork/antlr4/runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Atn/ParserATNSimulator.cs(261,63): warning CS1570: XML comment has badly formed XML -- 'Reference to undefined entity 'rarr'.'
/home/dong/github/fork/antlr4/runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Atn/ParserATNSimulator.cs(2050,51): warning CS1570: XML comment has badly formed XML -- 'Reference to undefined entity 'rarr'.'
```

In the code comment we are trying to use the escaping sequence to display a Right arrow (as in Java, Python target). The problem is, we get this in the generated xml file after build:
```
<!-- Badly formed XML comment ignored for member "F:Antlr4.Runtime.Atn.ParserATNSimulator.mergeCache" -->
```

Apparently msbuild can't recognize this escaping sequence at all, so it give up on trying to generate doc for this member. I have also tested with CDATA, seems the whole CDATA chunk was output as is, not just the content within as I expected.

The XML Comment has only limited ability to understand some escaping sequence, e.g. the most popular ```&lt; &gt;``` thing, but it can't recognize ```&rarr;``` if we use it, we can see a red tilde under the & char.

On the other hand, if we do 
```csharp
/// <summary>
///  test &#x2192;
/// </summary>
public class MergeCache
```
(http://right-arrow.net/)

Then we can have the arrow showing in Intellisence.

Not really sure what is the intended purpose of those comments, if it's for generating xml doc, then better replace ```&rarr;``` with ```&#x2192;```

If it's for people to read it directly in the code for better understanding, I guess it's better to replace that with a simple ->

**Comment by ericvergnaud** [comment]
Hi,

those comments were simply copied from the Java runtime.
Please fell free to submit a PR.

Eric

**Comment by sharwell** [comment]
@xied75 I would actually recommend replacing them with the right arrow character itself (&rarr;), and saving the files as UTF-8.
