### ISSUE TITLE
XPathLexer not updated in release process

### ISSUE THREAD

**Issue by davesisson** [antlr/antlr4#1620]
Similar to #796 the XPathLexer.class was built with 4.5.3 instead of 4.6.  As a result the following error message will result whenever the XPath libraries are used:

"ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.6"

**Comment by sharwell** [comment]
Should definitely include a regression test as well to make sure this doesn't happen in the future.

**Comment by davesisson** [comment]
Turns out the problem here is the way we're building it (in a different way).  In order to avoid a cyclic dependency we're building XPathLexer with an older version of the ANTLR tool:

https://github.com/antlr/antlr4/blob/master/runtime/Java/pom.xml#L75

If we can fix this somehow (presumably by not using antlr4-maven-plugin to build the XPathLexer.g4 file) we can make sure it's always built the right way.

But yes, a regression test seems warranted given that this has happened twice so far.

**Comment by juhakivekas** [comment]
What is currently the best solution to overcome this problem? Is there a workaround that may include cyclic dependencies. I would like to use this feature of the antlr tool and I haven't compiled any part of the project yet.

Given an example of regression tests (I can only find unit tests) I could create the needed test.

**Comment by juhakivekas** [comment]
For anyone looking for a quick fix, reverting to 4.5.3 works fine.

    git checkout 4.5.3
    mvn -DskipTests install

**Comment by davesisson** [comment]
An alternative I thought of last night was to modify the antlr4-maven-plugin to allow it to point to a smaller dependency.  The maven plugin presumably depends on the whole antlr4 target (which this is a part of) where we only need the tool to complete this particular action.

Maybe the plugin should always be modified to only require the tool.  (That would mean we'd have to give the runtime dependency to the generated code separately.)

**Comment by parrt** [comment]
I wish I knew mvn better. I'm afraid to touch the plug-in for fear of screwing it up. I'm not even sure of how to make this work. @sharwell  I think we had this solved in the past right? How do we get XPath.g4 generated to Java and compiled after a complete build so that we can generated with the same version as the software?

**Comment by parrt** [comment]
Ok, way to solve this once and for all is to do away with the .g4 based lexer. I will build one by hand quickly.

**Comment by parrt** [comment]
Any comments before I accept the [pull](https://github.com/antlr/antlr4/pull/1748)?
