### ISSUE TITLE
CommonToken toString improvement

### ISSUE THREAD

**Issue by huhlig** [antlr/antlr4#163]
CommonToken toString (used by TestRig with showTokens) should include token ruleName as well as rule ID to aid in debugging. Currently it outputs the string value and rule ID but not the rule name which makes quickly debugging ambiguous or badly written tokens much more difficult.

Perhaps adding a getRuleName for the token would be preferential as well.

**Comment by parrt** [comment]
Hi. i'm closing as I think we have a solution, if not a perfectly easy one.
