### ISSUE TITLE
C#Antlr4.6 runtime class Pair<>contains a couple errors.

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#1634]
I have been porting codebuff to C#. In doing so, I noticed several problems with Pair<> in the lastest version on the master branch of https://github.com/antlr/antlr4/blob/master/runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Misc/Pair.cs.

(1) The ToString() method contains a call to String.Format(). The format parameter is not correct. It uses "%s,%s" which is Java/C++/etc. Please use "{0}, {1}" and read https://msdn.microsoft.com/en-us/library/system.string.format(v=vs.110).aspx#Format_Brief.

(2) When used with HashSet<Pair<int,int>>, there should not be duplicates. However, the current version does. In other words, when I compare the type between Java and C#, they don't function identically. Consider the following test code:
`            HashSet<Pair<int, int>> the_hash_set = new HashSet<Pair<int, int>>();
            the_hash_set.Add(new Pair<int, int>(1, 2));
            the_hash_set.Add(new Pair<int, int>(1, 2));
            the_hash_set.Add(new Pair<int, int>(2, 1));
            foreach (var p in the_hash_set)
                System.Console.WriteLine(p);
`
I should see: "(1,2) (2,1)" (as in Java, which I tested), but I see instead "(1,2) (1,2) (2,1)" using this C# code. Looking at the C# source code Pair.cs, and comparing with the Java source, the test in the C# should be fixed. One can either implement the equivalent comparison classes and code in C#, or use something like this:

`/* Copyright (c) 2012-2016 The ANTLR Project. All rights reserved.
 * Use of this file is governed by the BSD 3-clause license that
 * can be found in the LICENSE.txt file in the project root.
 */

using System;

namespace ConsoleApplication16
{

    public class Pair<A, B>
    {
        public readonly A a;
        public readonly B b;

        public Pair(A a, B b)
        {
            this.a = a;
            this.b = b;
        }

        public override bool Equals(object obj)
        {
            if (obj == this)
            {
                return true;
            }
            else if (!(obj is Pair<A, B>))
            {
                return false;
            }

            Pair<A, B> other = (Pair<A, B>)obj;
            if (a != null)
            {
                if (b != null)
                    return a.Equals(other.a) && b.Equals(other.b);
                else
                    return a.Equals(other.a) && other.b == null;
            }
            else
            {
                if (b != null)
                    return other.a == null && b.Equals(other.b);
                else
                    return other.a == null && other.b == null;
            }
        }

        public override int GetHashCode()
        {
            int hash = MurmurHash.Initialize();
            hash = MurmurHash.Update(hash, a);
            hash = MurmurHash.Update(hash, b);
            return MurmurHash.Finish(hash, 2);
        }

        public override String ToString()
        {
            return String.Format("({0}, {1})", a, b);
        }
    }

}

`

**Comment by ericvergnaud** [comment]
Hi,

thanks.
Can you submit a PR (and sign contributors)?

Eric

**Comment by kaby76** [comment]
I would prefer not. (1) I am barely functional with Git. (2) I have no idea what the proper build/test procedure is with Antlr. (3) Pair<> is used in several places so any change will affect a bit. (4) There should be regression tests for all of these primitive classes, including Pair<>. The change I suggest may not be acceptable. Years ago, I have been criticized by someone on the project, so I prefer not to touch the code.
