### ISSUE TITLE
Java attempts to interpret windows paths containing \u as unicode making generated code uncompilable

### ISSUE THREAD

**Issue by huhlig** [antlr/antlr4#164]
Code generated on windows using default windows path style of backslashes attempts to decode any subdirectory starting with u as a unicode parser.

Example D:\path\to\util\grammar.g4

\util becomes an invalid escape character and prevents compilation as discussed on Mailing list.

**Comment by VanceDuncan** [comment]
@sharwell / @parrt , was there a resolution for this? I'm seeing this behavior using Antlr 4.12.0 from within IntelliJ. Is there a way to force it to use forward slashes rather than backslashes? Perhaps a compile option in the pom.xml file, or something.

**Comment by sschuberth** [comment]
@VanceDuncan I [believe](https://github.com/antlr/antlr4/issues/2569#issuecomment-1437290697) this is a regression. The issues was fixed once, and it worked until ANTLR 4.11.1, but version 4.12.0 reintroduced this issue. So reverting to version 4.11.1 for now helps.
