### ISSUE TITLE
Cpp Examples fail to compile with 'antlrcpptest::TLexer': cannot instantiate abstract class

### ISSUE THREAD

**Issue by apacha** [antlr/antlr4#1642]
When trying to run the current demo for Antlr4Cpp the build failes with the error: 'antlrcpptest::TLexer': cannot instantiate abstract class.

Steps to reproduce:

- Clone repository
- Follow instructions from antlr4-master\runtime\Cpp\demo\README.md:
    - Download [antlr-4.6-complete.jar](http://www.antlr.org/download/antlr-4.6-complete.jar) and place it in the same folder
    - Run generate.cmd (which produces the lexer and parser files in the `generated` folder)
    - Open demo\Windows\antlr4cpp-vs2015.sln and try to build

Expected output: A green build and an application that I could run
Actual output: A build error inside of the generated TLexer.cpp because the method 

    virtual const std::vector<std::string>& getChannelNames() const = 0;

from Lexer.h:159 is not overridden by the implementing class TLexer.h.

**Comment by mike-lischke** [comment]
This should be solved now. I got the same problem and simply regenerated my files, after which the compilation went through successfully.

**Comment by KvanTTT** [comment]
`getChannelNames` method will work since 4.6.1 version which has not been released yet.

**Comment by apacha** [comment]
Well, the point is, that the generated code does not compile out of the box, and it is not clear to me, what the implementation of getChannelNames should look like inside TLexer.cpp.
Can you at least make sure, that this issue makes it into 4.6.1?
And what exactly do you mean with "use the antlr repo to generate the parser files"?

**Comment by KvanTTT** [comment]
You try to run old ANTLR 4.6 generator for grammar from upcoming 4.6.1 version. I don't find any unclearness in these versions incompatibility. The method `virtual const std::vector<std::string>& getChannelNames() const = 0;` is abstract and is should be overridden in concrete class. But ANTLR 4.6 does not generate overridden method. So, use 4.6.1 generator instead.

**Comment by apacha** [comment]
Ok, now I see. I've used the code from the repository which is already ready for 4.6.1 but still used the 4.6 parser generator. Thanks for the help. Now it runs fine.
