### ISSUE TITLE
Using C# Anltr 4.5.3 stable code generation doesn't compile with error 'compareTo' 

### ISSUE THREAD

**Issue by pos123** [antlr/antlr4#1645]
Hi

Using antlr4.5.3 with visual studio 2015 to process the CPP14.g4 grammar file on github failed to compile. There was an error in the generated code 'compareTo' not being a method on a string in c#. It should be 'CompareTo' ( capital C ).

**Comment by parrt** [comment]
Likely this is an action within the grammar and therefore specific to a particular language; apparently Java.
