### ISSUE TITLE
Cpp runtime: compile needed <functional> header

### ISSUE THREAD

**Issue by rimmartin** [antlr/antlr4#1646]
Before submitting an issue to ANTLR, please check off these boxes:
 
- [x ] I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [x ] I have done a search of the existing issues to make sure I'm not sending in a duplicate

For -std=c++11 I needed to add
```
#include <functional>
```
to https://github.com/antlr/antlr4/blob/master/runtime/Cpp/runtime/src/antlr4-common.h#L36 to get  a compile with gcc 6.2 and 7.0.0 with http://www.antlr.org/download/antlr4-cpp-runtime-4.6-source.zip and the tip of the repo
which enables the use of
http://en.cppreference.com/w/cpp/utility/functional/function

**Comment by mike-lischke** [comment]
@parrt You can close this issue since the code is merged.
