### ISSUE TITLE
Using HIDDEN channel causes errors while using skip does not

### ISSUE THREAD

**Issue by r2mzes** [antlr/antlr4#1668]
Hi, I have found an issue with channel(HIDDEN).
I have thoroughly described it at stackoverflow: 
http://stackoverflow.com/questions/42253229/antlr4-using-hidden-channel-causes-errors-while-using-skip-does-not

**Comment by KvanTTT** [comment]
This is a feature, not a bug :) See my answer on StackOverflow.

**Comment by r2mzes** [comment]
You are right indeed. Thank you for the answer :)
Closing the issue
