### ISSUE TITLE
Throw warning if symbol conflicts with generated code in another language or runtime

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#1670]
Consider grammar with `file` root element. If generate parser for **Python2** target the following error will be thrown: 
```
error(134): L.g4:18:0: symbol file conflicts with generated code in target language or runtime
```
But if we change runtime to **Java** no error and warning will be thrown.

So, I suggest to throw a warning in this case:
```
warning(134): L.g4:18:0: symbol file conflicts with generated code in another language or runtime
```

This check allows us to write more universal grammars for all targets.

**Comment by mike-lischke** [comment]
Hmm, but then you might get warnings for names that you don't care for, since you don't intent to use a grammar in another language. That doesn't play well with build systems that strive zero error and warning messages.

**Comment by KvanTTT** [comment]
Maybe ANTLR should have a command line parameter `universal` that point on whether grammar should be wide or not? The user from this issue https://github.com/antlr/grammars-v4/issues/568 suffers from runtime keywords.

**Comment by mike-lischke** [comment]
How can this work out? You would need to test for all supported languages and as soon as a new language comes up you have to update that. That's this kind of cleverness which gets in the way more than what it solves. If a grammar is not compatible with a target language it must be changed, as easy as that.

**Comment by parrt** [comment]
I think most people use a single target and so I think we are okay. Closing.
