### ISSUE TITLE
Lexer action `skip` can break diagnostic output

### ISSUE THREAD

**Issue by mike-lischke** [antlr/antlr4#1681]
Before submitting an issue to ANTLR, please check off these boxes:
 
- [x] I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [x] I have done a search of the existing issues to make sure I'm not sending in a duplicate

This is issue is more of a cosmetic one, but still somewhat annoying. A grammar, which skips all whitespaces (instead of putting them on a custom channel) will cause diagnostic output (e.g. error messages) to look very strange, because all whitespaces are removed there (or rather: not included, since no tokens exist for them). Similar problems can appear when a user retrieves text created from actual tokens.

Not sure if that can be solved cleanly. Just thought I mentioned it :-)

**Comment by KvanTTT** [comment]
This is not a bug and duplicate :-)
[white space in antlr error messages](https://github.com/antlr/antlr4/issues/1050)

**Comment by mike-lischke** [comment]
Oh, didn't find that one, thanks.
