### ISSUE TITLE
A new indent option for better code style compliance in generated code

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#1682]
I decided to create a new issue separated from this one: [Add a new option for naming convention of generated Visitor and Listener methods](https://github.com/antlr/antlr4/issues/1615).

I suggest to add a new option `indent` with the following syntax: `-Dindent space4`. This value causes to generate code with four spaces indentation.

Default value is `tab1`.

**Comment by ericvergnaud** [comment]
Mmmmm...
Indentation is more or less hard coded in the generator templates and  cannot change at runtime.
I'm not supportive

Envoyé de mon iPhone

**Comment by KvanTTT** [comment]
Tabs can be replaced with spaces in template itself.

**Comment by ericvergnaud** [comment]
That would mean it is no longer an option.

**Comment by sharwell** [comment]
@KvanTTT The templates are intended to be self-consistent within a particular language, but there is no intent to make them consistent with particular coding styles. The use of tabs vs. spaces in the generated code is a file size issue. Some editors will refuse to open files over a certain size (varies by editor), and changing from tabs to spaces will substantially increase the number of ANTLR generated files which exceed these limits, posing a usability problem which we're currently avoiding.

**Comment by KvanTTT** [comment]
> but there is no intent to make them consistent with particular coding styles.

Why not if it's possible and easy to implement?

> The use of tabs vs. spaces in the generated code is a file size issue

At present time C++ runtime uses 2 spaces as an indent, Python runtimes use 4 spaces. According to this reason, we have to replace all spaces with tabs.

> changing from tabs to spaces will substantially increase the number of ANTLR generated files which exceed these limits, posing a usability problem which we're currently avoiding.

I generated a parser for big [PL/SQL grammar](https://github.com/antlr/grammars-v4/blob/master/plsql/plsql.g4) grammar. The parser contains approximately ~50K lines and has size 1.63MB. After it I replaced all tabs on spaces and file size increased up to 1.99 MB. So, the ratio 1.99 / 1.63 ≈ **1.2** is not a critical on my opinion but good for common code style. Moreover the size can be decreased if replace tabs with empty strings (with option `-Dindent spaces0` or just `-Dindent 0`): 1.51 / 1.99  ≈ **0.76**. But zero-indent won't work with indent-sensitive languages (Python).

**Comment by KvanTTT** [comment]
@ericvergnaud, it's an option. We can use the following code for template loading and changing:

```Java
templatePath = CodeGenerator.TEMPLATE_ROOT + "/CSharp/" + getLanguage() + STGroup.GROUP_FILE_EXTENSION;
String template = new String(Files.readAllBytes(Paths.get(templatePath)));
template = template.replaceAll("\t", "    ");
STGroup result = new STGroupString(templatePath, template);
```

instead of old

```Java
STGroup result = new STGroupFile(CodeGenerator.TEMPLATE_ROOT+"/CSharp/"+getLanguage()+STGroup.GROUP_FILE_EXTENSION);
```

**Comment by KvanTTT** [comment]
@parrt, maybe this option should be also added to StringTemplate library? The file indentation can be detected automatically for most files.

**Comment by parrt** [comment]
Hmm...I guess this isn't something I'm concerned with so I'll close. people can munge the output later if they want.

**Comment by KvanTTT** [comment]
This issue also actual for code actions. The mix of tabs and whitespaces in generated code and actions is ugly.
