### ISSUE TITLE
change 4.6.1 to 4.7

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#1684]
Dear @antlr/antlr-targets: seems like with @bhamiltoncx 's amazing work on unicode 32 support and the widespread changes/fixes, we should change this to a major release 4.7 from a point release as I had originally intended. Any issues with that?

**Comment by davesisson** [comment]
I'd love to see issue #1569 addressed in 4.7.  How much time is there before a fix for it misses the cut?

**Comment by parrt** [comment]
definitely want to fix that. I think it's a chicken and the egg problem. we need to build 4.7 once where xpath uses 4.6 and then generate a new parser from xpath to wrap up in 4.7. Not sure mvn knows how to do that.

**Comment by ericvergnaud** [comment]
No issue here, the new dotnet target is also significant

Envoyé de mon iPhone
