### ISSUE TITLE
LexerATNSimulator contains LOTS of non  portable code 

### ISSUE THREAD

**Issue by RobertvanderHulst** [antlr/antlr4#1702]
LexerATNSimulator contains lots of code that uses 
`Console.WriteLine`
and is therefore not portable :-(

Robert

**Comment by mike-lischke** [comment]
Why can't Console.WriteLine not be ported? And this is very like just debug output, so you could leave it out anyway.

**Comment by RobertvanderHulst** [comment]
We are including the Antlr Runtime source in our portable project. System.Console is not available when you create a portable classlibrary, which is what we do.
We worked around this by adding our own System.Console class (which writes to the debug window) , but the author of this code has marked some section with #if PORTABLE but forgot to exclude all the System.Console lines...

**Comment by parrt** [comment]
maybe @ericvergnaud can take a look.

**Comment by KvanTTT** [comment]
Can we use an abstract wrapper for debug output?
Something like class `Logger` with dummy default implementation.

**Comment by parrt** [comment]
Console.WriteLine in the ATN thing should be error messaging only. maybe throw exception instead?

**Comment by ericvergnaud** [comment]
Hi,

just had a quick look.
Happy to bless a PR where if(debug) is surrounded by #if !PORTABLE

Eric

**Comment by parrt** [comment]
Anybody want to create a PR? If not, I will close.

**Comment by KvanTTT** [comment]
I'm gonna fix it but not sure when.

**Comment by RobertvanderHulst** [comment]
I have fixed it. But I do not have write access to this repo. How can I get it in this repo ? I did give you (terr) access to a repo from myself that has the fixes.

**Comment by KvanTTT** [comment]
Now ANTLR C# runtime has `netstandard2.0` target and it's cross-platform. `PORTABLE` directives are not used at all.

@parrt the issue can be closed.
