### ISSUE TITLE
IntervalSet.getSingleElement() returns Token.INVALID_VALUE (0) on failure

### ISSUE THREAD

**Issue by bhamiltoncx** [antlr/antlr4#1703]
I ran into this while implementing #1688 .

Currently, a number of methods in `IntervalSet` (`getSingleElement()`, `getMaxElement()`, etc.) return `Token.INVALID_VALUE` on failure.

Unfortunately, `Token.INVALID_VALUE` is `0`, which is a perfectly valid value to hold in an `IntervalSet`, which claims to support everything from `Integer.MIN_VALUE` to `Integer.MAX_VALUE`.

In fact, `Java.g4` depends on an `IntervalSet` containing `0`:

```
fragment                                                                                                    
JavaLetter                                                                                                  
       :      [a-zA-Z$_] // these are the "java letters" below 0xFF                                       
       |      // covers all characters above 0xFF which are not a surrogate                               
              ~[\u0000-\u00FF\uD800-\uDBFF]
(snip)
       ;                                                                                                   
```

There are actually no callers of `IntervalSet.getSingleElement()`, so we can probably freely change its signature, but `IntervalSet.getMaxElement()` and friends have the same problem and do have lots of callers.

I thought we might just be able to change the error result to `-1`, but `IntervalSet` supports negative values.

I can think of a few possibilities:

1. Return a boxed `Integer` instead of `int` and require callers to check for `null` (error-prone)
2. Return `long` instead of `int` and use `Long.MIN_VALUE` to signify error
3. Throw an exception on error
4. Introduce something like Java 8 / Guava's `Optional<T>` and require callers to check for the result being present

Thoughts?

**Comment by bhamiltoncx** [comment]
Oh, and there's this fun comment from @mike-lischke in 29dedd17c444d6636c06eefc4183a093eb76b61c :

https://github.com/antlr/antlr4/blob/4ec294faffa14290e51e3574bad2ed4af186948d/runtime/Cpp/runtime/src/misc/IntervalSet.cpp#L308

```
return Token::INVALID_TYPE; // XXX: this value is 0, but 0 is a valid interval range, how can that work?
```

**Comment by mike-lischke** [comment]
Interval's negative values are just error codes, not valid values. They usually denote empty/invalid intervals, so returning a -1 sounds good to me.

**Comment by bhamiltoncx** [comment]
Ah, nobody uses it for any other purpose? OK, I can change to -1 if @parrt agrees.

**Comment by parrt** [comment]
intervals can contain things like Token.EPSILON (-1) and we test it:

```java
IntervalSet following = nextTokens(s);
if (!following.contains(Token.EPSILON)) {
	return following;
}
```

**Comment by mike-lischke** [comment]
Why keep getSingleElement at all if we don't use it? Writing code for just-in-case scenarios is a waste of resources, as it creates maintenance work (as we see here) without anybody using and testing it.

**Comment by bhamiltoncx** [comment]
I don't mind removing it, but I do need the functionality of
getSingleElement() in https://github.com/antlr/antlr4/pull/1688 .

Since we still need to fix getMinElement(), I figured we could come up with
a good solution for all of them.

**Comment by mike-lischke** [comment]
Ok, I see. We could add isValid() or isEmpty() (isEpsilon()?) to denote such special intervals and always use and return positive values for a and b.

**Comment by parrt** [comment]
I kind of like the undefined if empty concept. people should check `size()!=0` or existing `isNil()`. minimally intrusive / risky change maybe

**Comment by bhamiltoncx** [comment]
So, the idea is that:

1. Asking for the minimum or maximum of an empty set is an error
2. Asking for the minimum or maximum of a set containing negative values is an error
3. Nobody uses `IntervalSet.getSingleElement()` so we should delete it

For 1. and 2., should we throw an exception?

**Comment by parrt** [comment]
1, 3 yep. 2 should be allow if we don't need a sentinel value, right?  Let's leave it returning 0 to avoid breaking anything but change comment to say it's undefined.
