### ISSUE TITLE
Antlr 4.6 does not like same named rule element labels for different alternative labels

### ISSUE THREAD

**Issue by RobertvanderHulst** [antlr/antlr4#1706]
In my language definition I have a rule with labeled alternatives, and I am using the same name for different typed elements like this:
`: Expr= Expr=expression LPAREN ArgList=argumentList  RPAREN		#methodCall`
`   | Expr=expression LBRKT ArgList=bracketedArgumentList  RBRKT #arrayAccess`
`   ;`
Antlr 4.6 now complains "label ArgList=bracketedArgumentList type mismatch with previous definition: ArgList=argumentList" 
There should really be no problem with this, since the rule alternatives are labeled and the element names are generated in different sub classes.

This worked OK with previous versions of Antlr.
Is this a bug, or is there a good reason for this change, that I am not seeing ?

Robert

**Comment by KvanTTT** [comment]
Fixed in upcoming 4.7 version via #1585.
