### ISSUE TITLE
how to define the  antlr  rule about loop 

### ISSUE THREAD

**Issue by xxfx007** [antlr/antlr4#1716]
i want to ask a issue about antlr rule 
this is my input text
A
#A1
#A2
##A2X
##A2Y
#A3
B
C

and i want get this tree like this picture by antlr ， but i try to write the rule ， but it is insuccess，please help me ， thank you very much 
 
[cut]
![default](https://cloud.githubusercontent.com/assets/26105065/23509782/f7bcb288-ff91-11e6-980c-ee6019255a46.png)

**Comment by ericvergnaud** [comment]
Hi,

the place for support is the google discussion group.

Please close this.
Thanks
