### ISSUE TITLE
c++ demo generation error

### ISSUE THREAD

**Issue by Parean** [antlr/antlr4#1729]
I am trying to build this:
https://github.com/antlr/antlr4/tree/master/runtime/Cpp/demo

When I run generate.sh, I get:
`error(156): TLexer.g4:51:18: invalid escape sequence`

I removed the changes from this commit  https://github.com/antlr/antlr4/commit/e368fb30ea3d801e78d89fcb0a0c50d4c5438e21
and error disappeared.

**Comment by KvanTTT** [comment]
What version of ANTLR generator are you using?

**Comment by Parean** [comment]
antlr-4.6

**Comment by KvanTTT** [comment]
You should use the latest ANTLR generator (4.7, not released yet).

**Comment by Parean** [comment]
Clearly, thanks.
