### ISSUE TITLE
Gitter room for Antlr?

### ISSUE THREAD

**Issue by pureconfig** [antlr/antlr4#1734]
I'm sorry for creating an issue for this, but doing so proves my point.

I'd like to see a Gitter room for Antlr. For large and small discussion between users and devs alike. I dislike using GitHub issues for quick questions, and the Google groups list is an abomination with impossible roundtrip time for people used to IRC and other IM platforms :)

Any chance someone could create this room and put a link to it on the support page?

**Comment by KvanTTT** [comment]
Good idea!

**Comment by parrt** [comment]
yikes.  I'm not sure I can handle another place I have to watch for communication :( sorry. I would have to add this to Skype and slack.

**Comment by KvanTTT** [comment]
But you do not have to watch for this place. There is a big community around ANTLR :)

**Comment by parrt** [comment]
yes, but it fractures the community. now people would have to check yet another location. what does it add over google groups and slack?

**Comment by KvanTTT** [comment]
ANTLR have a slack group? Where? google group is not convenient and not friendly for developers. gitter tightly integrated into github issues, pull requests and other features. Also it provides a real-time discussion unlike google group.

**Comment by parrt** [comment]
sorry. i meant stackoverflow

**Comment by KvanTTT** [comment]
StackOverflow is a Q/A web service for problems solving. Long discussions are not welcome there. Maybe Quora partially corresponds.

**Comment by parrt** [comment]
Hmm...i suppose we could use it for long discussions of potential features...but my experience with slack is that you get all discussion threads all jumbled up. can you create a discussion "channel" or some such for a specific disucssion?

**Comment by parrt** [comment]
Ok, looks like they have "rooms" but why not just keep conversation going on a PR or issue?

**Comment by KvanTTT** [comment]
Gitter is a less formal place. Everyone can ask any question and everyone can answer. In GitHub issues, you can't. There is a fragment from ANTLR issue template:

> I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)

However, Gitter is more reactive than StackOverflow.

Yes, it's also possible to discuss new features more quickly on Gitter or another similar place.

>i suppose we could use it for long discussions of potential features

**Comment by parrt** [comment]
Hmm...well,I think I will still hold off for now.
