### ISSUE TITLE
antlr raises symbol conflicts error, even when valid for Python targets

### ISSUE THREAD

**Issue by machow** [antlr/antlr4#1735]
When building the example [tsql](https://github.com/antlr/grammars-v4/blob/master/tsql/tsql.g4) grammer for the Python3 target, antlr4 errors out because the grammar has a rule named "id":

```
error(134): tsql.g4:1222:0: symbol id conflicts with generated code in target language or runtime
```

In this case, from looking at other parsers generated for the Python3 target, it appears that this specific conflict **would not** prevent the build from working. However, while antlr4 gives the option of treating warnings as errors, AFAIK it doesn't have the option to ignore the error above. 

I could be totally wrong, but rather than having to change a grammar whenever there is a conflict, it seems useful to be able to treat this as a warning. I realize there are other targets where these conflicts might always cause an error, so understand there's more to the picture, though.

(somewhat related to #1670 )

**Comment by ericvergnaud** [comment]
HI
Thanks for this but although id is not strictly speaking a Python reserved keyword, it is very likely that the runtime might use it, leading to broken grammar or runtime.
Please close 
Envoyé de mon iPhone

**Comment by machow** [comment]
Hello,
I am not sure I understand what you mean by "it is very likely that the runtime might use it". As far as I can tell, the current runtime will not use it in such away that would lead to a broken grammar or runtime. Could you demonstrate how that could occur with `id`?

**Comment by machow** [comment]
Actually, now that I think about it--a more specific issue might be that python builtins, and not just keywords raise the error. If just the keywords raised an error, it would resolve the issue for Python. Sorry--I realize that the issue as originally phrased was pretty broad (I'm happy to edit the title).

They can be found using the following.

```
import keyword
keyword.kwlist

# ['False', 'None', 'True', 'and', 'as', 'assert', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
```

**Comment by ericvergnaud** [comment]
What I mean is that the use of Python  keywords AND builtins is reserved for the runtime.
I will not relax that (especially not id).

Envoyé de mon iPhone

**Comment by machow** [comment]
Thanks for taking the time to respond. To be sure,

1. python keywords do not currently raise an error, only builtins (which can be explicitly accessed using `import builtins`). For example, a rule named assert will raise a SyntaxError. I'm happy to raise this in a separate issue.
2. builtins, which raise an antlr build error, would not cause an error.

Since the runtime uses class methods, generating something with a rule named `id` would continue to reserve the runtime's access to builtins. Although I can't understand the rationale, I appreciate the time you (and everyone on the project) have put into the Python targets--and that you likely have a much better sense for snags allowing builtins could have down the road.

**Comment by ericvergnaud** [comment]
Hi,

the words reserved by the python antlr runtime are as follows:

python3Keywords = {
   "abs", "all", "any", "apply", "as",
   "bin", "bool", "buffer", "bytearray",
   "callable", "chr", "classmethod", "coerce", "compile", "complex",
   "del", "delattr", "dict", "dir", "divmod",
   "enumerate", "eval", "execfile",
   "file", "filter", "float", "format", "frozenset",
   "getattr", "globals",
   "hasattr", "hash", "help", "hex",
   "id", "input", "int", "intern", "isinstance", "issubclass", "iter",
   "len", "list", "locals",
   "map", "max", "min", "next",
   "memoryview",
   "object", "oct", "open", "ord",
   "pow", "print", "property",
   "range", "raw_input", "reduce", "reload", "repr", "return", "reversed", "round",
   "set", "setattr", "slice", "sorted", "staticmethod", "str", "sum", "super",
   "tuple", "type",
   "unichr", "unicode",
   "vars",
   "with",
   "zip",
   "__import__",
   "True", "False", "None"
};

All these raise an error. If they don’t, it’s a bug. Indeed assert is missing and should be added.

Eric

**Comment by machow** [comment]
Sounds good. I'll add the missing keywords and submit a pull request. Many builtins are missing from the list (mostly those using camel case, or with leading "__"). Should I add those as well (my reflexive instinct is no, but I am in the anti-builtin camp ;)? List below of all builtins in python 3.5.

```
['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIteration',
 'SyntaxError',
 'SyntaxWarning',
 'SystemError',
 'SystemExit',
 'TabError',
 'TimeoutError',
 'True',
 'TypeError',
 'UnboundLocalError',
 'UnicodeDecodeError',
 'UnicodeEncodeError',
 'UnicodeError',
 'UnicodeTranslateError',
 'UnicodeWarning',
 'UserWarning',
 'ValueError',
 'Warning',
 'ZeroDivisionError',
 '__IPYTHON__',
 '__IPYTHON__active',
 '__build_class__',
 '__debug__',
 '__doc__',
 '__import__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'abs',
 'all',
 'any',
 'ascii',
 'bin',
 'bool',
 'bytearray',
 'bytes',
 'callable',
 'chr',
 'classmethod',
 'compile',
 'complex',
 'copyright',
 'credits',
 'delattr',
 'dict',
 'dir',
 'divmod',
 'dreload',
 'enumerate',
 'eval',
 'exec',
 'filter',
 'float',
 'format',
 'frozenset',
 'get_ipython',
 'getattr',
 'globals',
 'hasattr',
 'hash',
 'help',
 'hex',
 'id',
 'input',
 'int',
 'isinstance',
 'issubclass',
 'iter',
 'len',
 'license',
 'list',
 'locals',
 'map',
 'max',
 'memoryview',
 'min',
 'next',
 'object',
 'oct',
 'open',
 'ord',
 'pow',
 'print',
 'property',
 'range',
 'repr',
 'reversed',
 'round',
 'set',
 'setattr',
 'slice',
 'sorted',
 'staticmethod',
 'str',
 'sum',
 'super',
 'tuple',
 'type',
 'vars',
 'zip']
```

**Comment by ericvergnaud** [comment]
If I recall correctly, the initial list was established from here:
https://docs.python.org/2/library/functions.html
https://docs.python.org/3/library/functions.html
to which keywords were added.

since these are documented as essential built-in functions, it is a good boundary for reserved names, i.e. names you are strongly advised to not redefine, whether globally or locally.
so I guess I’ll stick to this (adding missing keywords if any)

**Comment by forkzor** [comment]
I think the latest list is overshot. 
Only the keywords as in https://docs.python.org/3/reference/lexical_analysis.html  sect. 2.3.1  are reserved in that sense.

Test yourselves: 
$ python3 -c 'def False():
>    print("I am false");
> False();
> '
  File "<string>", line 1
    def False():
            ^
SyntaxError: invalid syntax

$ python3 -c 'def false():
   print("I am false");

false();
'
I am false

$ python3 -c 'def abs():
   print("I am false");
abs();
'
I am false


$ python3 -c 'def assert():
   print("I am false");
abs();
'
  File "<string>", line 1
    def assert():
             ^
SyntaxError: invalid syntax

$ python3 -c 'def abs():
   print("I am false");
abs();
'
I am false

$ python3 -c 'def RuntimeError():
   print("I am false");
RuntimeError();
'
I am false

Yours, 

Jens

**Comment by ericvergnaud** [comment]
What practical problem are you trying to solve?

Envoyé de mon iPhone

**Comment by forkzor** [comment]
You wrote:
"What I mean is that the use of Python keywords AND builtins is reserved for the runtime. I will not relax that (especially not id)."

But as you see above: e.g. abs is not reserved: $ python3 -c 'def abs():
print("I am false");
abs();
'
I am false

Your list is too long.

**Comment by ericvergnaud** [comment]
That is not a practical problem.
Abs is a global function so you don’t want to shadow it involuntarily when it’s very easy to use a different name in the grammar.
Am I missing something?

Envoyé de mon iPhone

**Comment by forkzor** [comment]
See: I cannot use a grammer unchanged for generating into different languages where in one language e.g. False is disallowed and in the other isn't, but others are? 

I would really like to have: 
- auto remapping dependant to the language
or 
- generated nevertheless so I can postprocess, maybe with a force- option.


In any case I would like to have any valid Antlr grammar be processible for any output language (even if the result is not immediately usable).

Yours, 

Jens

**Comment by varunajmera0** [comment]
error(134): SqlBase.g4:132:0: symbol with conflicts with generated code in target language or runtime
   self.from = None # QualifiedNameContext
            ^
SyntaxError: invalid syntax
 Python reserved keyword "from"

**Comment by 3068168455** [comment]
i have same issue, u can try to rename ur name of g4 files

**Comment by KvanTTT** [comment]
@parrt I think this issue if fixed.
