### ISSUE TITLE
Python3 target generated Lexer has loads of error (Also it has some Java code inside it, why ?)

### ISSUE THREAD

**Issue by aptrishu** [antlr/antlr4#1737]
I have generated Python3Lexer.py file by `antlr4 -Dlanguage=Python3 Python3.g4`
I got Python3.g4 from antlr grammar repo.

You can see the Lexer file here - https://groups.google.com/forum/#!topic/antlr-discussion/TinJ7m3DqXw

**Comment by ericvergnaud** [comment]
Hi,

this is not the place for support.
Please move this question to the Google group.

Eric

**Comment by aptrishu** [comment]
Thanks, I moved the question to google group.
