### ISSUE TITLE
ANTLR cannot generate 'org.antlr.v4.codegen.target.CSharp_v1_3Target' code as of version 4.6.1-SNAPSHOT

### ISSUE THREAD

**Issue by lextm** [antlr/antlr4#1738]
This is a .NET Standard 1.3 class library project in Visual Studio 2017 RTM. Upgraded to ANTLR latest NuGet package (prerelease), and compilation triggers,
```
ANTLR cannot generate 'org.antlr.v4.codegen.target.CSharp_v1_3Target' code as of version 4.6.1-SNAPSHOT
```
I can easily use [the workaround mentioned in this blog post](https://mhusseini.wordpress.com/2014/02/16/antlr-cannot-generate-org-antlr-v4-codegen-csharp_v4_5_1target-code-as-of-version-4-1-snapshot/), but do hope the tooling can be improved to support .NET Standard profiles as target framework version soon.

**Comment by sharwell** [comment]
:memo: This issue is for the [tunnelvisionlabs/antlr4cs](https://github.com/tunnelvisionlabs/antlr4cs) repository, not this one.
