### ISSUE TITLE
JavaScript target cannot use rule exceptions

### ISSUE THREAD

**Issue by ChristophWedler** [antlr/antlr4#1741]
The `try` block around the rule body is not properly closed by `}` when using rule exceptions:

```antlr
grammar noRuleExceptions;
options { language = JavaScript; }

start
    :
        'start'
    ;
    catch [re] {
        throw re;
    }
```

In `antlr4/tool/resources/org/antlr/v4/tool/templates/codegen/JavaScript/JavaScript.stg`,
the `}` must move from _after_ to _before_ the following block (starting in line 269),
as it is done for the Java target:

```
    <if(exceptions)>
    <exceptions; separator="\n">
    <else>
```

**Comment by ericvergnaud** [comment]
Hi,

thanks for this.
can you submit a PR so we can understand how this would behave?

Eric

**Comment by ChristophWedler** [comment]
I have understood that I also need to sign contributors.txt - still need some days to get an official OK from the company I work at.

**Comment by ericvergnaud** [comment]
Closing as already fixed
