### ISSUE TITLE
`mvn clean install` doesn't work, but `mvn clean; mvn install` does

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#1742]
@bhamiltoncx, could you take a peek? thanks!

**Comment by parrt** [comment]
@teverett says: *why don't we generate the .java file in tool-codegen, output it to a jar, and include the jar as a dependency of tools.  That is; lets include the .java file we need in binary form, not source form.*

**Comment by teverett** [comment]
@bhamiltoncx Could you take a look at #1740 please?

**Comment by bhamiltoncx** [comment]
Yeah, I'll make it a jar.

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/pull/1740
