### ISSUE TITLE
Python runtime has missing methods which are required to convert Python3 grammar (to make it usable for python3 target)

### ISSUE THREAD

**Issue by aptrishu** [antlr/antlr4#1746]
missing methods include -  
`getCharPositionInLine()`
`getLine()` in LexerATNSimulator.py
`setToken()` in Lexer.py

**Comment by aptrishu** [comment]
cc @ericvergnaud

**Comment by ericvergnaud** [comment]
Hi,
I believe all this can be achieved through direct field access.
If not please submit a PR.
Eric

**Comment by KvanTTT** [comment]
You should use `column` property instead of `getCharPositionInLine()` method. See my answer on stackoverflow for detail: [Missing Lexer Methods in ANTLR4 with Python Target?](http://stackoverflow.com/a/42403553/1046374).

**Comment by aptrishu** [comment]
Yes, I have found existing methods for almost all those methods(that I supposed were missing). However, I have not yet got it working, as I'm always getting `(file_input \n <EOF>)` output for the ParseTree for any input code. :(

**Comment by aptrishu** [comment]
Solved, PR - https://github.com/antlr/grammars-v4/pull/572
