### ISSUE TITLE
Cannot parse files with a UTF-8 signature

### ISSUE THREAD

**Issue by sharwell** [antlr/antlr4#175]
When the `-encoding` option is not specified, the ANTLR tool should automatically select the correct encoding for files containing a standard Unicode signature.

**Comment by greddyatpt** [comment]
The following errors came as a complete surprise to me and apparently to a whole lot of others.

error(50): C:\TemplateExpr.g4:1:0: syntax error: 'ï' came as a complete surprise to me
error(50): C:\TemplateExpr.g4:1:1: syntax error: '»' came as a complete surprise to me
error(50): C:\TemplateExpr.g4:1:2: syntax error: '¿' came as a complete surprise to me

$ od -c TemplateExpr.g4
0000000 357 273 277   g   r   a   m   m   a   r       T   e   m   p   l
0000020   a   t   e   E   x   p   r   ;  \r  \n  \r  \n   e   x   p   r
0000040   e   s   s   i   o   n  \r  \n

The UTF-8 mark - 357 273 277 - is very common in this Unicode era.  Modern tools handle these files without any additional guidance from command-line parameters.  If ANTLR4 can auto-detect the file encoding by default, it'll create a good first impression and save a lot of time.  This will allow the developers to use the tool without RTFM/RTFB.

Also, (1) please restore AST generation, (2) please handle transitive left recursion.
