### ISSUE TITLE
TokenStreamRewriter for javascript?

### ISSUE THREAD

**Issue by andreasboos** [antlr/antlr4#1767]
Hi.
I already use antlr for a few years with java target. Now I need to use with javascript target. I followed the tutorial and everything went well. Now I missed a class: TokenStreamRewriter. Does it have a different name? I searched on google and found nothing with this topic.

**Comment by ericvergnaud** [comment]
Hi,
feel free to implement one and submit a PR
Eric

**Comment by yilingapa** [comment]
me too, hope add this class in javascript.

**Comment by eirikur-grid** [comment]
I can take a stab at porting the class to js.

**Comment by eirikur-grid** [comment]
Apologies for taking so long. PR is ready for review.

**Comment by ericvergnaud** [comment]
Closing since we can continue the conversation in the PR
