### ISSUE TITLE
Grammar best practice for similar rules

### ISSUE THREAD

**Issue by bilsaboob** [antlr/antlr4#1769]
Hi everyone.

I'm contemplating on "best practice" and performance implications for the following grammar scenario:

`
memberDef
    : varMemberDef
    | valMemberDef
    | defMemberDef
    ;
varMemberDef
    : VAR nameid (COLON type)? (memberBlockStart memberBlock)?
    ;

valMemberDef
    : VAL nameid (COLON type)? (memberBlockStart memberBlock)
    ;

defMemberDef
    : DEF nameid argDecls? (COLON type)? (memberBlockStart memberBlock)?
    ;
`

As you can see, these three member definition rules mainly differ on the first "VAR" / "VAL" / "DEF" tokens, and could be merged into a more compact "single rule" version:

`
memberDef
    : (VAR | VAL | DEF) nameid argDecls? (COLON type)? (memberBlockStart memberBlock)?
    ;
`

This rule basically covers the previous scenario, but is a bit more forgiving and requires additional "validation logic" to be added as an extra pass after the parsing.

Why I'm leaning toward the first version, is that:
- it allows me to include some more refined "logic" on what must follow what during the parsing phase without any additional logic.
- it also seems to be easier to modify one of the versions without affecting the others. (which seems useful while evolving the grammar)

So, I'm wondering:

- Which of these is in general a "best practice" / would you prefer?
- Will this have any other implications later during the evaluation of parse result?
- Will the above versions differ much in performance? (given that I use the first approach over the latter throughout all my definitions)

Thanks

**Comment by mike-lischke** [comment]
This question is probably better suited for the ANTLR mailing list or Stackoverflow.
