### ISSUE TITLE
set difference / set complement in lexer

### ISSUE THREAD

**Issue by EXC-BAD-ACCESS** [antlr/antlr4#1770]
it would be nice if there was a lexer operator which which removes characters from another lexer rule, something like set difference or set compliment.

for example in Z Notation there are parts of the specification which are written like:
"any other UCS characters with General Category S*, P* or M* and that are not in SPECIAL"

so this operator would allow you to do something like:
   
    import classify; // unicode grammar
    
    LEFT_PARENTHESIS: '\u0028'; // (
    RIGHT_PARENTHESIS: '\u0029'; // )
    LEFT_SQUARE_BRACKET: '\u005B'; // [
    RIGHT_SQUARE_BRACKET: '\u005D'; // ]
    LEFT_CURLY_BRACKET: '\u007B'; // {
    RIGHT_CURLY_BRACKET: '\u007D'; // }
    LEFT_BINDING_BRACKET: '\u2989'; // ⦉ 
    RIGHT_BINDING_BRACKET: '\u298A'; // ⦊ 
    LEFT_DOUBLE_ANGLE_BRACKET: '\u27EA'; //《 
    RIGHT_DOUBLE_ANGLE_BRACKET: '\u27EB'; // 》

    SPECIAL
        : LEFT_PARENTHESIS
	    | RIGHT_PARENTHESIS
	    | LEFT_SQUARE_BRACKET
	    | RIGHT_SQUARE_BRACKET
	    | LEFT_CURLY_BRACKET
	    | RIGHT_CURLY_BRACKET
	    | LEFT_BINDING_BRACKET
	    | RIGHT_BINDING_BRACKET
	    | LEFT_DOUBLE_ANGLE_BRACKET
	    | RIGHT_DOUBLE_ANGLE_BRACKET
	    ;

    fragment
    OTHER_UCS_SYMBOLS
    	: MY_CLASSIFY_P
    	;

    fragment 
    MY_CLASSIFY_P
    	: CLASSIFY_P ∖ SPECIAL // i've used the set difference unicode char "∖" here, but something easier to type maybe
    	;

**Comment by jimidle** [comment]
If you need a rule to catch everything else then just have: 
ANY: . ;
As your last rule. You should have this anyway for reasons iterated ad nauseum in this group in the past :)
However, I understand your point, though I suspect it may be more complicated than you think. 
Jim


_____________________________

**Comment by EXC-BAD-ACCESS** [comment]
the catchall would work if there was just one such rule, but there are often more -- in the case of Z there are:

1) any other UCS characters with General Category N* except Nd
2) characters of the mathematical General Category L*
3) any other UCS characters with General Category L*
4) characters of the mathematical toolkit with General Category neither L* nor N*
5) any other UCS characters with General Category S*, P* or M* and that are not in SPECIAL

**Comment by EXC-BAD-ACCESS** [comment]
maybe i just like weird languages, but i think it could be a pretty common use case.  

a hypothetical [dlang grammar](https://dlang.org/spec/spec.html) could possibly be written to have a rule for [NamedCharacterEntity](https://dlang.org/spec/entity.html#NamedCharacterEntity) which is a set difference of the multiple code unit characters and a rule defined in a separate HTML grammar for [named-character-references](https://www.w3.org/TR/html5/syntax.html#named-character-references)

**Comment by EXC-BAD-ACCESS** [comment]
or page 31 of the [fortress spec](http://homes.soic.indiana.edu/samth/fortress-spec.pdf) under "ordinary operator characters":

"ordinary operator characters, enumerated (along with the special operator characters) in Appendix C, which
include the following characters with code points less than U+007F:
U+0021 EXCLAMATION MARK ! U+0023 NUMBER SIGN #
U+0024 DOLLAR SIGN $ U+0025 PERCENT SIGN %
U+002B PLUS SIGN + U+002D HYPHEN-MINUS −
U+003F QUESTION MARK ? U+0040 COMMERCIAL AT @
U+007E TILDE ˜
and most Unicode characters specified to be mathematical operators (i.e., characters with code points in the
range 2200-22FF) are operators in Fortress, but there are some exceptions (e.g., ∀, ∃ and :=)."

**Comment by parrt** [comment]
perhaps lexer modes? Either way, I don't think I'll implement.
