### ISSUE TITLE
import combined grammar into split grammar(s)

### ISSUE THREAD

**Issue by EXC-BAD-ACCESS** [antlr/antlr4#1773]
i'm not sure if it would be confusing or not, but it would be nice if you could import a combined grammar (especially a 3rd party grammar) into a split lexer/parser grammar and in each case it would only pick up the appropriate rules. 

so importing the combined [unicode grammar](https://github.com/antlr/grammars-v4/blob/master/unicode/unicode16/classify.g4) into a lexer grammar would pick up all the CLASSIFY* and ID* lexer rules and ignore the codepoint parser rule

and importing the same unicode grammar into a parser grammar would pick up the codepoint parser rule and any non-fragment Lexer rules (all of the Lexer rules in this particular case)

**Comment by ericvergnaud** [comment]
Mmmm… sounds like it would be confusing.
Rule precedence would likely need to also be adjusted.
Seems much simpler to work on a copy.

**Comment by parrt** [comment]
Probably easier to just split the unicode grammar.
