### ISSUE TITLE
ParseTreePattern Matching

### ISSUE THREAD

**Issue by maybeec** [antlr/antlr4#1783]
Hi, I just found the interesting but quite old idea of [SyntaxPatterns](https://theantlrguy.atlassian.net/wiki/display/~admin/2013/09/01/Matching+parse+tree+patterns%2C+paths) or [ParseTreePattern](https://github.com/parrt/antlr4/tree/tree-patterns/runtime/Java/src/org/antlr/v4/runtime/tree/pattern).
Is there any reason why this did not made its way into the main antlr4 repository?

I really like the idea and see great potential in it. Btw. is there any publication on this?

**Comment by mike-lischke** [comment]
It's here: https://github.com/parrt/antlr4/tree/master/runtime/Java/src/org/antlr/v4/runtime/tree/pattern

**Comment by KvanTTT** [comment]
Doc is here: [Parse Tree Matching and XPath](https://github.com/antlr/antlr4/blob/master/doc/tree-matching.md).

**Comment by maybeec** [comment]
Thanks for the pointer.
