### ISSUE TITLE
No results for Hello.g4 on Windows

### ISSUE THREAD

**Issue by nevetS** [antlr/antlr4#179]
Just running through the basics here.

> java org.antlr.v4.runtime.misc.TestRig Hello r -tree

The system just hangs.  It's not eating CPU, it's memory usage is stable.  It never crashes, it simply just does not return any output or close.  Tried against java 1.6 and java 1.7.

> java org.antlr.v4.runtime.misc.TestRig Hello r -gui 

produces the same results

**Comment by Omniphage** [comment]
Happy to have found this exchange since I just had the exact same problem. Tutorial should clarify what is user input and what is not.
Not even sorry for the necro to be honest.

**Comment by NealSnooke** [comment]
yeah - I couldn't understand why nothing was happening. Obviously there had to be some text for it to parse. But I was just trying to make sure everything was installed and didn't really think it through. Instructions could have been clearer about what to expect...

**Comment by parrt** [comment]
This is a generational issue. Old people like me are used to stdin and command line. Please help out by updating doc for common programmers and submit a PR :)

**Comment by NealSnooke** [comment]
Thanks - I should do that... Antlr is a great tool. I have been using 2.74 for a very long time and finally decided to move to the latest version for a new project that is about to start. Should probably have gone straight to using it within Eclipse... I'm better at configuring stuff there :)
