### ISSUE TITLE
What to do with UnbufferedCharStream for 4.7?

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#1795]
@bhamiltoncx  Is there a way we can easily update `UnbufferedCharStream` so that it uses the new 32-bit functionality? it would be okay to get the implementation out and replace with a delegation to the new stuff. there would be no concern about buffer size in memory.

**Comment by bhamiltoncx** [comment]
I'll take a look!

**Comment by bhamiltoncx** [comment]
Just so I understand the architecture of `UnbufferedCharStream`: it seems like it only ever reads forward, so it can never support seeking backwards. Is that correct? If so, it should be easy enough to port it to use code points.

**Comment by bhamiltoncx** [comment]
Ah, yeah, it explicitly throws if you do anything but a 1-character lookbehind:

```
    @Override
    public int LA(int i) {
        if ( i==-1 ) return lastChar; // special case                                                                                       
        sync(i);
        int index = p + i - 1;
        if ( index < 0 ) throw new IndexOutOfBoundsException();
```

Hmm. So, it would be pretty easy to change `char data[]` to `int data[]` and decode UTF-16 surrogate pairs to Unicode code points, but that means 2x the memory usage.

Do I need to optimize that?

**Comment by parrt** [comment]
haha. was just thinking that. let's just switch to `int`. Seems like we'd need to decode utf-8 and utf-16 but utf-32 is out unless we add a new ctor right (`read()` returns 16 bit int).

Next question: do we leave as standalone class with ctor style construction or add to interface? I think it's not used much so we can just upgrade its guts and not complicated main CharStreams interface.

**Comment by bhamiltoncx** [comment]
I'm fine with just upgrading its guts. I just finished it, PR incoming.

**Comment by bhamiltoncx** [comment]
Here we go: https://github.com/antlr/antlr4/pull/1796

I didn't touch the other languages yet.

**Comment by bhamiltoncx** [comment]
https://github.com/antlr/antlr4/pull/1798 for C#. We don't need any changes for any other languages (JS is the only other UTF-16 one and it doesn't have an unbuffered input stream).

**Comment by parrt** [comment]
Actually, it looks like InputStream.read() returns a byte not 16bit as I thought.  anyway, how do we know that the incoming InputStream is not already doing some decoding?

**Comment by bhamiltoncx** [comment]
`InputStream.read()` is guaranteed to return raw bytes, just like C `read()`. It does no decoding.

You have to wrap `InputStream` with `InputStreamReader` to decode those bytes to Unicode (in Java's case, UTF-16).

**Comment by parrt** [comment]
ah! ok, that explains it. Is there anything in the new API that needs documentation concerning what kind of streams can be passed in? I guess one of the biggest problems with the prior constructor interface was that it allowed Readers.

**Comment by bhamiltoncx** [comment]
Nah, I don't think we need to have any special documentation.

Readers aren't really a problem, I think they just make the API less tidy.

In Java, `InputStream` is a source of `byte`s, and `Reader` is a source of `char`s (usually from an `InputStream` plus a `Charset` to decode it to UTF-16).

There shouldn't be any restrictions on what types of streams or readers you can pass in, as long as they obey the contracts Java sets out.

**Comment by parrt** [comment]
ok, I pinged you on some of the other PRs concerning whether not they are now up to snuff with the latest Java API. do we need to tweak C++, swift, python2/3 to add the new API style?

**Comment by bhamiltoncx** [comment]
Since those APIs didn't need any changes to support Unicode code points, it'd be great if we could leave them alone.

**Comment by parrt** [comment]
So C++, which has no support for encodings, will simply stay as it is now? What does he do for UTF-8?

**Comment by bhamiltoncx** [comment]
From my understanding, the C++ ANTLR runtime supports UTF-8 and only UTF-8 for input. The logic converts UTF-8 internally to and from code points in memory:

https://github.com/antlr/antlr4/blob/master/runtime/Cpp/runtime/src/ANTLRInputStream.cpp#L38
