### ISSUE TITLE
LineTerminator is not defined exception in ECMAScript.JavaScriptTarget.g4

### ISSUE THREAD

**Issue by eugenega** [antlr/antlr4#1812]
1. Downloaded grammar file from here:
`https://github.com/antlr/grammars-v4/blob/master/ecmascript/ECMAScript.JavaScriptTarget.g4`
2. Downloaded ANTLR from here:
`http://www.antlr.org/download/antlr-4.7-complete.jar`
3. Running this to generate parser and lexer:
`java -jar antlr-4.7-complete.jar -Dlanguage=JavaScript ECMAScript.g4`
4. Installed ANTLR JS runtime:
`npm install antlr4`
5. created main.js file:
```
var antlr4 = require('antlr4/index');
var ECMAScriptLexer = require('./ECMAScriptLexer').ECMAScriptLexer;
var ECMAScriptParser = require('./ECMAScriptParser').ECMAScriptParser;

var inputStream = new antlr4.InputStream("a=x(10)");
var lexer = new ECMAScriptLexer(inputStream);
var tokens = new antlr4.CommonTokenStream(lexer);
var parser = new ECMAScriptParser(tokens);
parser.buildParseTrees = true;
var tree = parser.program();
console.log(tree.toStringTree(parser));
```
5. Executed file:
`node main.js`

Result:
```
ECMAScriptParser.js:755
                throw re;
                ^
ReferenceError: LineTerminator is not defined

```

It looks like there is a defect. Instead of LineTerminator it shall be ECMAScriptParser.LineTerminator.

**Comment by eugenega** [comment]
If I replace in grammar file `LineTerminator ` to `ECMAScriptParser.LineTerminator` then I get a new exception:
```
node_modules\antlr4\Utils.js:404
    s = s.replace("\t", "\\t");
         ^

TypeError: Cannot read property 'replace' of undefined
```

**Comment by ericvergnaud** [comment]
Hi,

you need to get help from the author of that grammar.

Eric

**Comment by eugenega** [comment]
I fixed the grammar issues. There is exception in ANTLR generated parser: tree.toString(parser) (my second comment).

**Comment by ericvergnaud** [comment]
looks like the issue originates from tree.toStringTree(parser) -> Trees.getNodeText
which returns undefined under certain circumstances

I suspect line 58 in Trees.js, but you would have to debug and check the value of t.ruleIndex when this happens.

**Comment by eugenega** [comment]
t.ruleIndex - is 0
ProgramContext.ruleNames at 0 index is "program"

however, ruleNames[t.ruleIndex] instead of program returns undefined instead of "program"

**Comment by ericvergnaud** [comment]
looks like you need to pass ruleNames as parameter
tree.toStringTree(parser, parser.literalNames) // or parser.symbolicNames

**Comment by eugenega** [comment]
Changed to tree.toStringTree(parser, parser.ruleNames).
That indeed helped. Thank you.
