### ISSUE TITLE
Include lib/require.js to antlr-javascript-runtime

### ISSUE THREAD

**Issue by shds86** [antlr/antlr4#1816]
Hi. Could you add a file https://github.com/antlr/antlr4/blob/master/runtime/JavaScript/src/lib/require.js to javscript-runtime. It doesn't included in release build, only on github.

**Comment by ericvergnaud** [comment]
Hi,
As documented, this file is provided as a courtesy and is not part of antlr and not supported
Sorry 

Envoyé de mon iPhone
