### ISSUE TITLE
Missing nuget package for version 4.7

### ISSUE THREAD

**Issue by lukas-ais** [antlr/antlr4#1828]
Version 4.7 is released.
But I'm missing the nuget package on nuget.org.

**Comment by KvanTTT** [comment]
ANTLR 4 Standart is there: https://www.nuget.org/packages/Antlr4.Runtime.Standard/4.7.0

**Comment by lukas-ais** [comment]
Ok, this seams to be the replacement for ANTLR4.Runtime (https://www.nuget.org/packages/Antlr4.Runtime).
But how about ANTLR4 (https://www.nuget.org/packages/Antlr4)?

I'm asking due to problem with ANTLR4 in VS2017 (https://stackoverflow.com/questions/42568406/antlr-not-working-with-vs2017). There is noted, that the version 4.6.1-beta* solves the problem. The beta version is available as expected. I'm only missing the official release.

BTW: Could add some instructions to the website on using nuget?

**Comment by sharwell** [comment]
@lukas-ais The packages you refer to are fork of this project, developed and still maintained in a different repository: [tunnelvisionlabs/antlr4cs](https://github.com/tunnelvisionlabs/antlr4cs).

**Comment by lukas-ais** [comment]
Meanwhile I've updated to 4.6.4 which is working fine in VS2017.
