### ISSUE TITLE
generating lexers swift en masse renders errors / how to solve them?

### ISSUE THREAD

**Issue by johndpope** [antlr/antlr4#1851]
steps
I am running this script 
https://gist.github.com/johndpope/7dcb229db33836d4af031ce302924d35

it spits out errors
https://gist.github.com/johndpope/b1f58f8ea51649e5b9d5abeef5976692

I'm not interested in solving all the errors / however what is the approach when an error like  this creeps up for swift specifically. 
error(134): CPP14.g4:1180:10: **symbol operator conflicts with generated code in target language or runtime**

it would be great to lock down 6-7 specific languages to target for swift.  

I had to use a different java gramma file in order to get java tokens working. 

looks like same goes for python

<img width="309" alt="screen shot 2017-05-01 at 22 07 48" src="https://cloud.githubusercontent.com/assets/289994/25601500/9bbc2cb8-2eba-11e7-9b6a-59429d12be5c.png">

**Comment by johndpope** [comment]
@hanjoes - any ideas?

**Comment by KvanTTT** [comment]
Swift supports keywords escaping with backticks: [Keywords and Punctuation](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/LexicalStructure.html). @hanjoes what do you think about it? For example, C# runtime uses keywords escaping, see also [C# identifiers list](https://github.com/antlr/antlr4/blob/4.7/tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg#L1061).

**Comment by hanjoes** [comment]
this should be something circumvented by tweaking our grammar? for e.g.: inlining the "associativity" rule, or rename it to something else like "associativity_rule". (This breaks beautiful mapping from language spec, but works.)

@KvanTTT yeah.. we do have backtick notation in Swift, but how it can solve our problem here is not clear to me. Maybe I'm not 100% getting the bad word checking part.

**Comment by KvanTTT** [comment]
I mean the problem `symbol operator conflicts with generated code in target language or runtime`. It will be fixed if an operator keyword will be escaped with backticks:
```
`operator`
```

**Comment by hanjoes** [comment]
Ah gotcha. I initially thought you were talking about a codegen change. Then adding backtick would be great if antlr grammar allows it.

**Comment by johndpope** [comment]
So the gramma files need preprocessing. Is there any other code gen /bash script that's already doing this?

I'm intending to build parses for python golang cpp java etc...

@hanjoes - if you take a look at python tokens it's a mess.
I guess if we can resolve one reserved word in python - then we can stream line things.

**Comment by hanjoes** [comment]
For now we don't have a tool to solve this issue automatically..
In [this file](https://github.com/antlr/antlr4/blob/46b3aa98cc8d8b6908c2cabb64a9587b6b973e6c/tool/src/org/antlr/v4/codegen/target/SwiftTarget.java) you can see the list of keywords reserved by the current swift runtime. If the grammar you are interested in has symbols conflict with the keywords listed, you could actually do a search and swap based on this list (which can be automated). I'm thinking whether we can do it in our codegen to do the swap under the hood.
@parrt do you think it's reasonable to do that? I'm not sure whether it will defeat the purpose of checking for bad words.

**Comment by KvanTTT** [comment]
@hanjoes swap under the hood is a good idea. It also resolves this: https://github.com/antlr/antlr4/issues/1670.

**Comment by parrt** [comment]
Should be easy enough to check for keywords in all targets but most people don't want this so I'd be hesitant to add warnings to the output.

**Comment by hanjoes** [comment]
maybe it worth considering to give a warning while we do a swap under the hood for those language targets support escaping of keywords?  and we should be able to do it in a way it's a responsibility of the target author so it doesn't mess up the common parts.

But probably not worth it since grammar can be bound to one single language anyways, and eventually we would resort to tweaking the grammar.

**Comment by KvanTTT** [comment]
@parrt what do you think about renaming conflict keywords? I think runtime restrictions should not affect grammar. In this case, we don't need for conflicts warning at all.
* If language supports keyword escaping (C#, Swift) then escape conflict keywords: `operator` -> `@operator` (C#), \`operator\` (Swift).
* Otherwise append a special char to the end of the keyword. Something like this: `operator` -> `operator_`.

**Comment by parrt** [comment]
I think I'd like to leave the code generation as it is.  Your solution is not bad but I'm mostly in maintenance mode and don't want to make a lot of changes.
