### ISSUE TITLE
GO runtime: Can not compile on ARM

### ISSUE THREAD

**Issue by milanaleksic** [antlr/antlr4#1858]
As presented in the reproduction scenario, current code that constitutes Go runtime the can't be compiled if target is linux + ARM architecture (no problem if I remove `GOARCH=arm` from the request below). Currently reproducible in my project wallabago, commit 48a5e22d2336c12fe24ab410ab260c79809623b4.

```bash
milan@dell /opt/go/src/github.com/milanaleksic/wallabago/cmd/main → GOARCH=arm go build -o wallabago
# github.com/milanaleksic/wallabago/vendor/github.com/antlr/antlr4/runtime/Go/antlr
../../vendor/github.com/antlr/antlr4/runtime/Go/antlr/utils.go:368: constant 3432918353 overflows int
../../vendor/github.com/antlr/antlr4/runtime/Go/antlr/utils.go:374: constant 3864292196 overflows int
../../vendor/github.com/antlr/antlr4/runtime/Go/antlr/utils.go:381: constant 2246822507 overflows int
../../vendor/github.com/antlr/antlr4/runtime/Go/antlr/utils.go:383: constant 3266489909 overflows int
```

**Comment by whrool** [comment]
It is the same on windows + 386

**Comment by neatnerd** [comment]
I think the error is pretty clear. The murmur hash implementation is 64-bit (i guess?) in code, so ARM cannot handle it. Can you research the ARM murmur hash implementation, then some1 can PR that

**Comment by milanaleksic** [comment]
All I've done in my case is change undefined type (probably resolved to int) to uint and I didn't encounter any issues but didn't have time to verify via comparing with some other implementation, since there are no explicit tests for this code (murmurInit etc) that I could find. I don't like sending PR code I didn't have time to test

**Comment by milanaleksic** [comment]
I've sent a PR of the change that worked for me

**Comment by exander77** [comment]
Seems to be broken, see bottom: https://github.com/antlr/antlr4/issues/2152
