### ISSUE TITLE
Duplicate error codes

### ISSUE THREAD

**Issue by mike-lischke** [antlr/antlr4#1865]
In file [ErrorType.java](https://github.com/antlr/antlr4/blob/master/tool/src/org/antlr/v4/tool/ErrorType.java) there are 2 errors using the same error code 160, which is wrong. The first occurence also appears out of order, so I guess this a copy/paste problem and the error number should be 114 or so.

**Comment by KvanTTT** [comment]
I think we also should add a unit-test for checking error codes!

**Comment by mike-lischke** [comment]
Error code 134 is duplicated as well.
