### ISSUE TITLE
Escape quotes

### ISSUE THREAD

**Issue by kaba2** [antlr/antlr4#1871]
The following worked in version 4.5.3, but not in 4.7:

    grammar SymbolStructure;
    document : '\"';

The error is `invalid escape sequence`. If I remove the backslash, then the grammar builds. 

I have a larger grammar which uses an escaped quote. Removing the backslash leads ANTLR to fail at runtime to

    File "...\site-packages\antlr4\atn\ATNDeserializer.py", line 118, in checkUUID
        " (expected " + str(SERIALIZED_UUID) + " or a legacy UUID).", uuid, SERIALIZED_UUID)
    Exception: ('Could not deserialize ATN with UUID: 59627784-3be5-417a-b9eb-8131a7286089 (expected 
    aadb8d7e-aeef-4415-ad2b-8204d6cf042e or a legacy UUID).', UUID('59627784-3be5-417a-b9eb-
    8131a7286089'), UUID('aadb8d7e-aeef-4415-ad2b-8204d6cf042e'))

The same grammar builds and runs fine with 4.5.3.

**Comment by KvanTTT** [comment]
It's a warning, not error. Just remove useless escape literal: `'\"'` to `'"'` and it will work fine.

**Comment by zhouqilin1993** [comment]
antlr4.7 has the same error, remove backslash fail too.

**Comment by ericvergnaud** [comment]
the 2 issues are unrelated 
the UUID error is cause by incompatible tool and runtime version
use the latest tool and runtime from pypi

**Comment by ViceIce** [comment]
I got the warning too:  `invalid escape sequence '\''`

```antlr
fragment ESC		: '\\' ([\'\\/bfnrt] | UNICODE) ;
String		        : '\'' (ESC | ~[\'\\])* '\'';
```

What is wrong here?

**Comment by KvanTTT** [comment]
Remove escaping for single quotes: `\'` to `'`. They are useless.

**Comment by sharwell** [comment]
@parrt I believe this can be closed. The "invalid escape sequence" warning is fixed by removing unnecessary backslashes, and the UUID error at runtime is resolved by using the same (matching) version of the ANTLR tool and runtime library.
