### ISSUE TITLE
ExternalAntlr4Cpp.cmake can't find generated files with single run

### ISSUE THREAD

**Issue by chrisaycock** [antlr/antlr4#1872]
- [x] I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [x] I have done a search of the existing issues to make sure I'm not sending in a duplicate

ExternalAntlr4Cpp.cmake determines the list of `generated_files` via `GLOB` after ANTLR runs. However, these generated files haven't been _generated_ yet! That means `GLOB` won't see them and therefore the dependencies will be empty.

A simple work-around seems to be to run the build (`cmake` and `make`) until it fails with a linking error, then run the build again. The second invocation of `cmake` will find the generated files from the first run.

Was this behavior intended? (I've tried adding `GENERATED TRUE` to the properties for the generated file, but that didn't change anything.)

**Comment by mike-lischke** [comment]
That external app cmake file was contributed by someone else and I don't know how to fix it. Did you try the normal cmake file instead? The readme explains how to use it.
