### ISSUE TITLE
enhancement - swift test coverage / package manager

### ISSUE THREAD

**Issue by johndpope** [antlr/antlr4#1877]
Just a note from upgrading 4.6 > 4.7 it seems there's  a tiny bit of regression on the generation of  tokens / parsers.  I can't track it down specifically because I may have used unofficial java / golang gramma files that were corrected.

However - it begs the status of some test coverage which should include some official gramma files you want to support in unit test cases.  a small number maybe appropriate.
but need to lock in a set. eg. java / cpp / cpp /c / golang / proto  (protobuffer gramma) files

If I had to suggest some other areas to improve here - would be to have a batch file that could do some self contained testing. 

1) automatically download latest jar file from predetermined site.
perhaps when you release the latest build -> 

sudo curl -O http://www.antlr.org/download/antlr-4.7-complete.jar
also simply overwrite a file on server eg.
http://www.antlr.org/download/latestAntlr.jar

https://github.com/johndpope/swift-walker-antlr/blob/master/RefreshGramma.sh
2) generate the runtime across all supported grammas (from above script)
 java -cp latestRuntime.jar org.antlr.v4.Tool -Dlanguage=Swift -visitor -o gen $file_path

3) Test parsing against some real files. 
eg. https://github.com/johndpope/swift-walker-antlr/tree/master/SkyWalker

N.B. It's difficult to use the SPM package.swift as I don't believe it's currently possible to use the swift  remote url in a directory - unless I'm mistaken. People are having to create their own repo - and push source files to. It seems SPM - just wants a vanilla repo - with git tag - and sources folder in root of repo.  https://github.com/johndpope/swift-walker-antlr/blob/master/Package.swift
you need to be able to specify a git repo with tag
   .Package(url: "https://github.com/johndpope/ANTLR4Swift.git", "0.1.3")

(feel free to cherry pick any code from above scripts.)

**Comment by hanjoes** [comment]
for SPM integration we had this [PR](https://github.com/antlr/antlr4/pull/1862) merged into the latest version but not released yet. Basically it's  a hack to generate a local ANTLR4 Swfit project and people can use that as dependency. Probably not ideal but works.

**Comment by johndpope** [comment]
thanks @hanjoes  - I was thinking of hacking a script to do a crude regex find and replace across gramma files for reserved swift words. 

related
https://github.com/SwiftGen/StencilSwiftKit/issues/49

At some point want to get the python parser working / then down the track do a python to swift converter. I'll close this. 

Consider having a repo we you save a bunch of files that are generated - then when you bump the version - you could see changes propagated.
