### ISSUE TITLE
Referencing negated Token in a parser rule

### ISSUE THREAD

**Issue by malvee** [antlr/antlr4#1880]
`init : ~BOOLEAN '(' args ')' #functionRule
        | BOOLEAN #boolInInit
        ;
BOOLEAN : 'true' | 'false' ;
`
Inside the visitor visitFunctionRule(BetaParser.FunctionRuleContext ctx), how would I get the string literal corresponding to ~BOOLEAN in the init rule?

**Comment by KvanTTT** [comment]
`context.getChild(0)`

**Comment by malvee** [comment]
for the string 'func(' will ~BOOLEAN match just the 'func' and the '(' in init matches the '(' in the literal 
or
~BOOLEAN matches the entire 'func(' and '(' from init is not matched. Thanks.
