### ISSUE TITLE
Parser very slow on Node JS with Java8 Target

### ISSUE THREAD

**Issue by jundl77** [antlr/antlr4#1883]
I am trying to parse Java 8 files and create an AST out of them using antlr 4, all in Javascript / Node JS. Everything seems to be going well, with the exception of the actual AST construction. When I call ```parser.compilationUnit()```, the program does not terminate until it eventually runs out of heap memory. 

Here is what I have done so far:

I managed to generate the Java8 antlr files using: 

```antlr4 -Dlanguage=JavaScript Java8.g4 -visitor```

I created the chars, lexer, tokens and parser following [this](https://github.com/antlr/antlr4/blob/master/doc/javascript-target.md) guide:

```js
const input = JavaExampleFile.code
const chars = new antlr4.InputStream(input)
const lexer = new Java8Lexer.Java8Lexer(chars)
const tokens = new antlr4.CommonTokenStream(lexer)
const parser = new Java8Parser.Java8Parser(tokens)
parser.buildParseTrees = true
const tree = parser.compilationUnit()
```

Now the problem arises when I call ```const tree = parser.compilationUnit()```. In the grammar, the compilationUnit is defined as the following:

```
compilationUnit
    : packageDeclaration? importDeclaration* typeDeclaration* EOF
    ;
```

It seems that ```typeDeclaration``` is causing the issue. I think I to found the code that's eating up all the time (it's in the generated parser), but I don't know enough about antlr for it to be meaningful to me. Here it is:

```js
var la_ = this._interp.adaptivePredict(this._input,160,this._ctx);
 ```
It seems like this ```adaptivePredict``` function is the problem (I think). Any help would be appreciated.

**Comment by ericvergnaud** [comment]
Hi,
The place for support is the google group
Eric

Envoyé de mon iPhone

**Comment by jundl77** [comment]
After some extensive debugging, I'm pretty sure this is an issue with the java8 grammar. Other grammars work just fine. I will make an issue there.
