### ISSUE TITLE
Alternatives priority in left-recursive grammar with "repeated 1 or more times"

### ISSUE THREAD

**Issue by riccardodebenedictis** [antlr/antlr4#1889]
Dear all,

I am writing a grammar with antlr4.7. The problem is that the priority to the `>=` inequality is higher than the priority of the sum. Is this the correct behaviour? Given the order of the alternatives, I would have expected the opposite behaviour (i.e., sum before inequality). Both Java and C++ targets present this issue.

This is the grammar:

```
expr
    :   literal
    |   qualified_id
    |   expr ('+' expr)+
    |   expr '>=' expr;

literal
    :   numeric=NumericLiteral
    |   string=StringLiteral
    |   t='true'
    |   f='false';

qualified_id
    :   ID ('.' ID)*;

DOT
    :	'.';

PLUS
    :	'+';

GTEQ
    :   '>=';

ID
    :    ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'0'..'9'|'_')*;

NumericLiteral
    :   [0-9]+ ('.' [0-9]+)?
    |   '.' [0-9]+;

StringLiteral
    :   '"' (ESC|.)*? '"' ;

fragment
ESC
    : '\\"' | '\\\\' ;

LINE_COMMENT
    : '//' .*? '\r'? '\n' -> skip ;

COMMENT
    : '/*' .*? '*/' -> skip ;

WS
    :  [ \r\t\u000C\n]+ -> skip;
```

As an example, if the input `x0 + x1 >= 20` is given to the grammar, the generated tree is
```
(expr (expr (qualified_id x0)) + (expr (expr (qualified_id x1)) >= (expr (literal 20))))
```
rather than the expected
```
(expr (expr (expr (qualified_id x0)) + (expr (qualified_id x1))) >= (expr (literal 20)))
```
many thanks for your valuable work,
Riccardo

**Comment by ericvergnaud** [comment]
Hi,
The place for support is the google group 
Eric

Envoyé de mon iPhone

**Comment by riccardodebenedictis** [comment]
It seems to me a parser generator (or, at least, a documentation) issue, rather than a support request... i will ask the google group, anyway, thank you so much!!

**Comment by KvanTTT** [comment]
I think you have use `expr '+' expr` alternative instead of `expr ('+' expr)+`.

**Comment by riccardodebenedictis** [comment]
Ok, if there is no way to use the "one or more" operator while keeping the precedence among the alternatives I'll have to reorganize my code.
Just consider, for a future release, that this feature might be really useful depending on the semantic of the implemented language.
Many thanks for the quick answers!
