### ISSUE TITLE
Carriage return is not treated as newline

### ISSUE THREAD

**Issue by voidfist** [antlr/antlr4#1890]
When files having '\r' as newlines are parsed, the line numbers and the character positions in line do not correctly reflect the situation. For instance:

Grammar:

    grammar Hello;            // Define a grammar called Hello
    r  : 'hello' ID ;         // match keyword hello followed by an identifier
    ID : [a-z]+ ;             // match lower-case identifiers
    WS : [ \t\r\n]+ -> skip ; // skip spaces, tabs, newlines, \r (Windows) 

Input file: [input.txt](https://github.com/antlr/antlr4/files/1036864/input.txt)

Output:

     grun Hello r -tokens input.txt
     [@0,0:4='hello',<'hello'>,1:0]
     [@1,7:11='parrt',<ID>,1:7]
     [@2,12:11='<EOF>',<EOF>,1:12]

_2nd and 3rd token don't lie on the 1st line. The parser is failing to recognize CR as newline._

Seems to relate to [this](https://github.com/antlr/antlr4/blob/master/runtime/Java/src/org/antlr/v4/runtime/atn/LexerATNSimulator.java#L738) part of the code.

**Comment by KvanTTT** [comment]
Duplicate: #1098.
You have to replace `\r` on `\n`.

**Comment by ps-sp** [comment]
So it's unlikey to be fixed ? Actually I had searched for a duplicate before creating this one but I had my search narrowed only to issues open and thus I couldn't realize the duplicate.

**Comment by KvanTTT** [comment]
I'm afraid not :(

**Comment by ps-sp** [comment]
But several projects use ANTLR. Perhaps some others as well might want to support CR newlines ? Kindly reconsider.

**Comment by BurtHarris** [comment]
You can support return-only line breaks this by writing a custom CharStream implementation to translate.

**Comment by ps-sp** [comment]
@BurtHarris fair enough. Thank you :)

**Comment by KvanTTT** [comment]
@parrt it can be closed since it's duplicate
