### ISSUE TITLE
Unify the Python2 and Python3 code bases into a single library compatible with both

### ISSUE THREAD

**Issue by gpshead** [antlr/antlr4#1900]
It is very awkward to see two entirely separate trees of code for Python 2.7 vs Python 3.  How are these even maintained?

The normal thing for Python libraries that support both is to write code compatible with both. I strongly recommend unifying them.

**Comment by gpshead** [comment]
Looking at a diff -r of Python2 and Python3 trees, you would benefit from using a library such as six for all of your `unicode()` vs `str()` calls to be language version agnostic.  The `u""` syntax works in both language versions so there is no reason for that difference (recommendation: Just use the u's everywhere - or if you are one of the rare projects where it is _not_ the wrong thing to do, adopt `from __future__ import unicode_literals` in your files and never use a `u` prefix).

I also see type annotations in the Python3 code on function and method signatures. awesome!  For a combined codebase those can be placed in side `.pyi` files.

**Comment by ericvergnaud** [comment]
Hi,
Thanks for your comments but we believe in a strategy that is aligned on the official Python strategy, rather than goes against it.
Python 2 and Python 3 are 2 different languages. As time goes by, differences will keep growing, and will invalidate single code base strategies that rely on transitioning libraries such as six.
Eric

Envoyé de mon iPhone

**Comment by gpshead** [comment]
That is not what the rest of the Python libraries in the world are doing. By the time `six` ceases to be useful for this purpose, you won't need to support Python 2 users anymore. FWIW, there isn't an "official Python strategy" in regards to this. What libraries do is not expected to be the same thing as what CPython itself does. (I'm a CPython core developer)

How do you maintain your Python code? Require humans to make changes in both versions at once manally?

Unless you require new Python syntax features such as `yield from`, `async`, or `await` I think you will reduce your own maintenance burden by not maintaining parallel copies of the same code.  I see you are using type annotation syntax, but even those have a blessed solution of `.pyi` files for use by static checkers such as pytype and mypy when 2.7 compatibility is needed.

The reason I file this is that having two separate copies of the code for different Python versions makes it painful to check a copy of the library into our own code base which supports Python 2 and 3 at once out of a single code base.  We have to jump through hoops to put both versions of the code in place yet expose it under the same `antlr4` module name. Doable, but it is something other Python libraries do not require.

Anyways, its your project. You get to decide how you maintain it. I figured you'd be closing this as "won't fix" anyways, but I wanted to raise the issue as an FYI.  I'm closing it as I don't expect you'll change your mind.

**Comment by alexmuller** [comment]
> We have to jump through hoops to put both versions of the code in place yet expose it under the same `antlr4` module name.

@gpshead Would you mind sharing how you did this? I have a project which support Python 2 only at the moment and needs to support both Python 2 and 3. Ideally this library would do a release which supports both Python versions at the same time and then drop support for Python 2 (like popular libraries such as [requests have done](https://github.com/requests/requests/commit/c3ecb825c41f90fb6bec28c282c70c84398e08c0)).

To start with I imagine this would involve installing both `antlr4-python2-runtime` and `antlr4-python3-runtime`. But then I don't know enough about Python packages and modules to know what is made available as `import antlr4`.

**Comment by ericvergnaud** [comment]
I’m all for an official way of supporting both versions, and happy to evolve antlr4 a bit if required 
A simple idea that comes to mind is to expose something like antrl4_py2 and antlr_py3.
Feel free to explore and keep me posted.

Envoyé de mon iPhone

**Comment by gpshead** [comment]
I'm not sure it is such an issue for most users, as if you're pip installing a package, it installs in a Python interpreter specific location, so the python 2 version and python 3 version wind up installed in appropriate places for each of those interpreters.

When it matters if you do not pip install things, but check in copies of the code into your own repository rather than relying on executing someone else's random code from the Internet (as pip install can be thought of...) for your deployments.  That is where things become weird.  For us, we've got our build system selecting which sources to use based on the build time Python version and copying them into the right place.  It works.  I wish we didn't have to do it, but a few libraries such as this one require that trick.  Since we've solved it that way, I'm not inclined to work on patches to projects to combine their code into a single 2 and 3 source file.  But I happily support anyone who does so. :)

**Comment by mwisslead** [comment]
I'd like to add that it's very annoying that there are two different packages up on pypi. It is easy enough to make seperate .whl files for different python versions. If distributing the source code in this way is the problem I'd say just don't do it, it can be obtained elsewhere. If help is needed to make it happen, I'd be willing to do it.

**Comment by ericvergnaud** [comment]
Hi
Thanks for the help, but not sure what exactly you are proposing to do. Can you clarify?
Eric

Envoyé de mon iPhone

**Comment by mwisslead** [comment]
On pypi.python.org, I'm suggesting adding an antlr4 package that contains a .whl file for python2 and one for python3. Then anyone can install for their version with `pip install antlr4`.

**Comment by ericvergnaud** [comment]
can you submit a PR that would:
 - make this a seamless improvement for @parrt 
 - not break existing implementation

**Comment by tjprescott** [comment]
@gpshead our project is in the same boat. We have to support Python 2 and 3, but if we install both runtimes and import `antlr4` it takes the Python3 version, which fails on a Python2 system. What workaround did you use to load the appropriate runtime?

**Comment by parrt** [comment]
Shouldn't python 2 see whatever was installed with pip2?

**Comment by tjprescott** [comment]
The packages are listed as dependencies in our setup.py files. Importing `antlr4` then imports the Python3 version, even on Python 2, resulting in syntax errors.

**Comment by parrt** [comment]
Shouldn't there be antlr4 packages for both 2 and 3 and the python2 interpreter knows which to load?  I've not had this problem. make sure to use pip2 and pip3 to install. 

```
beast:master:~/antlr/code/antlr4 $ pip install antlr4-python3-runtime
Collecting antlr4-python3-runtime
  Downloading https://files.pythonhosted.org/packages/3e/96/aba01b2948ec67f237cd387c022820835ae0d8db5cab4bd404b351660b5e/antlr4-python3-runtime-4.7.1.tar.gz (111kB)
    100% |████████████████████████████████| 112kB 9.9MB/s 
Building wheels for collected packages: antlr4-python3-runtime
  Running setup.py bdist_wheel for antlr4-python3-runtime ... done
  Stored in directory: /Users/parrt/Library/Caches/pip/wheels/ef/f6/18/ad300e691236a3408a99edc750484b56e8d6b11b2c38eacb10
Successfully built antlr4-python3-runtime
distributed 1.21.8 requires msgpack, which is not installed.
Installing collected packages: antlr4-python3-runtime
Successfully installed antlr4-python3-runtime-4.7.1
beast:master:~/antlr/code/antlr4 $ pip2 install antlr4-python2-runtime
Requirement already satisfied: antlr4-python2-runtime in /usr/local/lib/python2.7/site-packages
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
beast:master:~/antlr/code/antlr4 $ python3
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import antlr4
>>> 
beast:master:~/antlr/code/antlr4 $ python2
Python 2.7.13 (default, Aug 26 2017, 15:43:21) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import antlr4
>>> 
```
