### ISSUE TITLE
Breaking the rules

### ISSUE THREAD

**Issue by us-er-name** [antlr/antlr4#1916]
With lexer matching, I am under the assumption that the lexer will build the longest match from the input stream. If there is more than one rule, it picks the "topmost" matching rule in the lexer source.

Are there any additional unusual "gotchas" not mentioned? This is not happening in my grammar.

Exact details are in the attached test.G4 file.

This issue is not meant as a "teach me / fix my problem". I hope it's just my code and not a bug - it is faster for me to fix a mistake than wait for a bug fix. (You people are great and have lives of your own.) I've simply googled myself to death on this issue and can not see anything other than a bug. (Sorry.)

I admit I'm new to writing grammars and especially antlr, but I've known the general concepts for many years. So I'm a bit green but not really a true green. (Rather hand code another simple scanner than to spend more time leaning flex/antlr, etc).

To learn antlr, I wrote a grammar that simply can read it's own grammar. I fed itself into itself and checked the token stream - which is not returning the results I expected.  The issue is mainly what was mentioned above and it is commented in the grammar file.

What isn't in the file:

I am using antlr 4.7 just a week old off this repository. 
Same results with combined grammar and non-combined.
I use jdk1.8.0_77 for javac

inside my batch file:
java org.antlr.v4.Tool -Dlanguage=Cpp -listener -visitor test.g4
java org.antlr.v4.Tool test.g4
javac test*.java

TestRig testing: (note the stream source is it's own grammar file)
java org.antlr.v4.gui.TestRig test all -tokens test.G4

Any help is appreciated.  If it is a bug then at least I can try to work around it. Possibly even hand-write yet another scanner... AARRGGHHH.

[test.zip](https://github.com/antlr/antlr4/files/1075582/test.zip)

**Comment by ericvergnaud** [comment]
Hi
The place for support is the google discussion group.
Please close this.
Eric

Envoyé de mon iPhone

**Comment by us-er-name** [comment]
Fine. I'll close it.

I do consider it a bug when something does not work as stated in the documentation.  I thought this is where to report bugs. I believe I read the docs right, so here is a bug. If by chance it is something in my grammar, then I believe that there is an error condition that is silently failing. Still a bug.

You should have the submission form reworded to state that all things like this should be peer reviewed by support before it should be posted here. That would save both of us time.

Rewording what I was asking: "What quirky thing did I do to trigger this so hopefully I have a workaround." Not "Teach me". That would be support. Well, if confirmed, i guess finding a workaround would fall under support. I get it.

I was hoping to use this instead of (increasingly) hard to maintain code for a client but, due to time constraints, will have to leave this for now. Open issue or closed, you have a record and sample grammar if this ever comes up again.

Considering the huge success antlr is, even I have to concede that (even if I am correct) this would be a potentially obscure bug and thus low priority. So I'll close this issue and hopefully revisit antlr in the future. I apologise if I'm coming across strong - I get that way on things I really feel passionate about. I'm impressed with what I see. If I wasn't, I would have just left it and just moved on.

Keep up the good work.
