### ISSUE TITLE
Publish updated version of JavaScript runtime

### ISSUE THREAD

**Issue by federicobond** [antlr/antlr4#1937]
The currently published JavaScript runtime lacks the fixes in 5e648f0867720ded8a251c0a5c69b506986e159c and 892aa4a3769951a531c34f60320672224319c6d3, which makes it unusable in practice. Would it be possible to do a patch release soon, to avoid the need for vendoring?

**Comment by ericvergnaud** [comment]
Hi 
Not sure how to interpret 'vendoring'
I use the current runtime on a daily basis so would not qualify it as 'unsusable'
I wouldn't expect a release until Q3
If you're in such a hurry, maybe you should move away from npm releases to uncontrolled latest ?

Envoyé de mon iPhone

**Comment by federicobond** [comment]
I meant I had to copy the patched runtime over to my repo instead of declaring the dependency in my `package.json`. When I tried to use the published version, it would break for a very straightforward use case, so I assumed others would have this problem too. I'm using node v8.1.2 btw.

**Comment by ericvergnaud** [comment]
Already fixed
