### ISSUE TITLE
How to get the token attributes in Antlr-4 lexer rule's action

### ISSUE THREAD

**Issue by kishore74lko** [antlr/antlr4#1946]
I am new to Antlr-4, but have much idea about Antlr-3, where the lexer could be created without the need of any parser rule; in order to match a lexer rule by matching some tokens like:
```
CLASS: 'Class' WS+ id=ID
{
   System.out.println("ClassName = " + $id.text + ",  LineNbr = " + $id.line);
}
ID : [a-z]+ ;
WS : [ \r\t\n]+
```
How could I do this in Antlr-4 without any parser, since the Antlr-4 lexer does not allow using attributes in the rule's action, and generates the error:
```
error(128): AntlrPPLexer.g4:210:27: attribute references not allowed in lexer actions: $id.text
1 error(s)

BUILD FAIL

```

By using the **Antlr-4.7**, giving the enough information about my question:
`warning(201): AntlrPLexer.g4:16:20: labels in lexer rules are not supported in ANTLR 4; actions cannot reference elements of lexical rules but you can use getText() to get the entire text matched for the rule`

By why Antlr 4, suppressed the labels in lexer rules??

Any idea/example will be helpful for me!

**Comment by btheu** [comment]
Same needs here

@kishore74lko have you find any work around ?

**Comment by alexZaicev** [comment]
Is there a work around this issue ? would anyone be able to look at this?

**Comment by ericvergnaud** [comment]
Please move this to the google discussion group
