### ISSUE TITLE
label 'label' type mismatch with previous definition: TOKEN_LABEL!=RULE_LABEL

### ISSUE THREAD

**Issue by yankee42** [antlr/antlr4#195]
I noticed that I can't write a rule like this:

```
ausdruck: label=ausdruck 'x' #One
        | label='foo'    #Two
        ;
```

It gives the following error:

> label 'label' type mismatch with previous definition:
> TOKEN_LABEL!=RULE_LABEL

It looks like this is because once label refers to a parser rule and once to a lexer rule. If I slightly change the rule:

```
ausdruck: label=ausdruck 'x' #One
        | label2='foo'    #Two
        ;
```

Everything works fine.
Since the labels are contained in seperate rules I think they should not interfere with each other.

(Also on stackoverflow: http://stackoverflow.com/q/15481471)

**Comment by ferhaterata** [comment]
Hi Sam,

Could you please check the same problem starts to occur again in 4.6? Because the same grammar works well in 4.5.3. 

`label left=expression type mismatch with previous definition: left=formula`

Thanks.

**Comment by KvanTTT** [comment]
@ferhaterata this is correct behavior. See this issue for detail: https://github.com/antlr/antlr4/issues/1409

**Comment by sharwell** [comment]
@ferhaterata Can you provide a specific example of what fails? We have one unit test added in #1458 but it sounds like you may have found another scenario?

**Comment by ferhaterata** [comment]
Hi @sharwell 

In the following, I provided a Grammar that ANTLR generates recognizer in 4.5.1 and 4.5.3 but fails in 4.6.1. The labels 'left' and 'right' represent two different types. Sorry for preparing a verbose grammar.

```
grammar Test;

module: formula* ;

formula:
      left=expression 'in'  right=expression    #in
    | left=formula    'and' right=formula       #and
    ;

expression:
      left=expression '+' right=expression      #union
    | variable                                  #var
    ;

variable: IDENTIFIER;

IDENTIFIER : [a-zA-Z];
``` 
It throws
`error(75): test2.g4:2:13: label left=inner type mismatch with previous definition: left=example`
`error(75): test2.g4:5:55: label right=example type mismatch with previous definition: right=inner`

In fact, this one works fine,

```
grammar test1;

example:
    left=integer '*' right=integer  #integerExample
  | left=string  '+' right=string   #stringExample
  ;

integer: IDENTIFIER;
string: INTEGER;

STRING: [a-zA-Z];
INTEGER: [a-zA-Z];
```

I assume the problem occurs once repetitions are allowed in labels. However, when I changed label name

**Comment by sharwell** [comment]
@ferhaterata Those are great examples. Can you open a new issue for this since it's a regression?

**Comment by KvanTTT** [comment]
Found out the problem: it's occures in case of left-recursion rule. Will try to fix it.

**Comment by parrt** [comment]
Added new issue: https://github.com/antlr/antlr4/issues/1543
