### ISSUE TITLE
'tree' as name of a parser rule causes syntax error.

### ISSUE THREAD

**Issue by mateuszpawlik** [antlr/antlr4#1960]
A simple grammar ('g.g4'):
```
grammar g;
tree : 'X';
```
causes the following error 
```
java -jar antlr-4.7-complete.jar g.g4 
error(50): g.g4::: syntax error: mismatched character ':' expecting 'g'
error(50): g.g4:2:7: syntax error: ''X'' came as a complete surprise to me
```
Removing the space between 'tree' and ':' or changing 'tree' to other rule name helps.

I've found that 'tree' was a keyword in antlr v3. But the reference book of v4 doesn't list it any more.

If 'tree' is a reserved keyword, the error message is confusing.

**Comment by moy** [comment]
It expects a `g`, and when you give that `g` (`tree g:`), it asks for an `r`, then a `a`, and so on until you type `tree grammar` completely, in which case it throws `syntax error: 'tree grammar' came as a complete surprise to me`. It seems ANTLR is trying to special-case `tree grammar` as a kind of two-words keyword. Weird.

Workarounds:

* Don't use `tree` as a rule name.

* Stick the `:` to `tree` as in `tree:`, and the error disappears.

**Comment by moy** [comment]
> It seems ANTLR is trying to special-case tree grammar as a kind of two-words keyword. 

Indeed: https://github.com/antlr/antlr4/blob/432022fc1ca098f2ab419d6e26a09124a518c345/tool/src/org/antlr/v4/parse/ANTLRLexer.g#L449

Actually, if I read correctly, this rule is only used to throw a relevant error message when the user writes `tree grammar` (not supported in ANTLRv4): https://github.com/antlr/antlr4/blob/432022fc1ca098f2ab419d6e26a09124a518c345/tool/src/org/antlr/v4/parse/ANTLRParser.g#L200-L210

Still, I don't understand why using a prefix (`tree `) of a token raises an error.
