### ISSUE TITLE
[C++] EPSILON Token Definition

### ISSUE THREAD

**Issue by neatnerd** [antlr/antlr4#1981]
C++ target uses unsigned int type (size_t), sometimes switching to signed one (ssize_t).
So in one place in Token.h definition, I found this:
```cpp
static const size_t EPSILON = static_cast<size_t>(-2);
```
It overflows and gets converted into 4294967294 [playground](https://code.sololearn.com/c39N9RN6b4Md/#cpp)

Is it intended this way?

**Comment by gaulouis** [comment]
Hello,

as far as I can remember EPSILON is a spécial token. Not a std::numeric_limits::epsilon

Maybe
``static const size_t EPSILON = std::numeric_limits<size_t>::max() - 2;``

And soon in IntStream:
``static const size_t EOF = std::numeric_limits<size_t>::max() - 1;``

**Comment by neatnerd** [comment]
I really dont think that it was intended this way, otherwise this constant would not make any sense:
```cpp
static const size_t MIN_USER_TOKEN_TYPE = 1;
```

I think the author just tried to port Java code where the EPSILON is indeed -2, but in signed int variable, but wanted to use idiomatic size_t type. He could not put it into signed type and just static cast it into desired type. I do believe this is a mistake. It is unlikely to come in effect since no way we will have  so many tokens, but it is still not correct imho

**Comment by neatnerd** [comment]
@mike-lischke what do u think?

**Comment by mike-lischke** [comment]
It's fully intended as is. I didn't want to use a signed type here and hence had to wrap the few negative values used in Java to unsigned types in C++.

@gaulouis This syntax doesn't work in VS 2015 (or was it VS 2013?). I tried that already.

**Comment by neatnerd** [comment]
and if you compare `MIN_USER_TOKEN_TYPE>EPSILON `?

**Comment by mike-lischke** [comment]
You wouldn't do that. Their purpose is completely different. Believe me, I checked all that. These negative constants are just markers for various things. They are not compared to anything nor does their actual value matter. Important is only they don't conflict with each other and don't use numbers that can appear for regular values.

**Comment by neatnerd** [comment]
Ok thanks!
