### ISSUE TITLE
why antlr 4.5.3 is depending on antlr-runtime:3.5.2

### ISSUE THREAD

**Issue by mcheung63** [antlr/antlr4#1993]
why antlr 4.5.3 is depending on antlr-runtime:3.5.2?

    <dependency>
      <groupId>org.antlr</groupId>
      <artifactId>antlr-runtime</artifactId>
      <version>3.5.2</version>
      <scope>compile</scope>
    </dependency>

**Comment by gaulouis** [comment]
Hello,
@sharwell have already answered this question [Why does the antlr pom have a antlr4 and antlr3 runtime dependency?](https://github.com/antlr/antlr4/issues/858)

**Comment by mcheung63** [comment]
thanks
