### ISSUE TITLE
Compile time error for Swift runtime

### ISSUE THREAD

**Issue by zskolbay** [antlr/antlr4#1998]
I'm trying to build the Swift runtime, so I can add it to my iOS project.
When I try to compile it (taken from the [ANTLR 4.7 distribution](https://github.com/antlr/antlr4/archive/4.7.zip)) with Xcode 8.3.3 I get the following error:
`CommonUtil.swift:122:33: '_buffer' is inaccessible due to 'internal' protection level`
When I clone the ANTLR repository (as written in the [documentation](https://github.com/antlr/antlr4/blob/master/doc/swift-target.md)) there is no **Antlr4.xcodeproj** file in it.
What am I missing here? How can I build this project?

**Comment by limlab** [comment]
I have the same problem. Not sure if I'm doing everything right, but seems like the code which produces the error is trying to test referential equality. I fixed this problem like it listed below:
````
// Test referential equality.
        //if lhsCount == 0 || lhs._buffer.identity == rhs._buffer.identity {
        //      return true
        //  }
    
        var isRefEqual = false
        lhs.withUnsafeBufferPointer { outer in
            rhs.withUnsafeBufferPointer { inner in
                if inner.baseAddress == outer.baseAddress {
                    isRefEqual = true
                }
            }
        }
        if isRefEqual {
            return true
        }
```` 
It needs to be rechecked, but works for me.

**Comment by ewanmellor** [comment]
The Antlr 4.7 release does not include the work to migrate to Swift 3.1 (notably https://github.com/antlr/antlr4/commit/b5caa8e945c52f1f5863cd9f4d3b27bc337d89bc and #1808).  That will be why it's not working for you.

If you're going to switch to Xcode 9 you could use [my fork] (https://github.com/ewanmellor/antlr4) temporarily or wait for the discussion on #2028 to play out.

**Comment by ewanmellor** [comment]
@parrt This issue is stale and can be closed.
