### ISSUE TITLE
Add Python targets for java8

### ISSUE THREAD

**Issue by roipoussiere** [antlr/antlr4#2003]
The [Travis CI](https://travis-ci.org/antlr/antlr4) don't includes targets for Python2 and Python3 with java8. We could fix this by adding in [.travis.yml](https://github.com/antlr/antlr4/blob/master/.travis.yml), for example:

```
    - os: linux
      jdk: oraclejdk8
      dist: trusty
      env: TARGET=python2_j8
    - os: linux
      jdk: oraclejdk8
      dist: trusty
      env: TARGET=python3_j8
```

**Comment by ericvergnaud** [comment]
Thanks but not sure this would solve any problem i.e. only the tool uses Java and it is already tested against Java 8 with the Java target 

Envoyé de mon iPhone

**Comment by roipoussiere** [comment]
Indeed.
