### ISSUE TITLE
Python 3 Target: RuleContext type hint in generated lexer

### ISSUE THREAD

**Issue by rljacobson** [antlr/antlr4#2012]
In the generated Python 3 lexer the type hint `RuleContext` is used throughout, e.g. in [line 158 of `Python3.stg`](https://github.com/antlr/antlr4/blob/master/tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg#L158). However, `RuleContext` is never imported. 

A simple fix is to change [line 15 of `antlr4/__init__.py`](https://github.com/antlr/antlr4/blob/master/runtime/Python3/src/antlr4/__init__.py#L15) in the runtime from
```python
from antlr4.ParserRuleContext import ParserRuleContext
```
to
```python
from antlr4.ParserRuleContext import ParserRuleContext, RuleContext
```
On the other hand, maybe the type hint should be `ParserRuleContext`...? I'm not familiar enough with the internals to know.

In either case, I'm happy to submit a pull request with a fix if you'd like. 

(Incidentally, if the "simple" fix is accepted, it would "increase" my contributions ANTLR4 by a factor of -13: My previous contribution fixed a bug by deleting a single character!)

**Comment by ericvergnaud** [comment]
Hi,

thanks for this. Makes sense, go for it :-°

Eric

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/pull/2013
