### ISSUE TITLE
Discussion: Swift 4 / Xcode 9 support

### ISSUE THREAD

**Issue by ewanmellor** [antlr/antlr4#2028]
cc: @parrt @hanjoes 

Xcode 9 and Swift 4 were released earlier this month.  I would like to discuss support for that, and then I can send you pull requests as appropriate.

1. What is your attitude to Xcode and maintenance of project files upstream?  We used to have Xcode project files in runtime/Swift but they were removed by @hanjoes in May and I don't know why.  I'm still using them, other people would like to (see #1998), and the documentation still references them.

2. Do you care about supporting Swift 3, now that Swift 4 is available?  I personally don't, and would prefer not to have to worry about that.  Others may have different needs of course.  The differences between the two are not large (see https://github.com/ewanmellor/antlr4/commit/e5738fd4c9c57e847c8178933aa100c858074022 for the changes against Antlr 4.7) but still there are some.

3. Is there a release / milestone that we should aim for?

Thank you!

**Comment by parrt** [comment]
I'll wait for @hanjoes to respond.

**Comment by hanjoes** [comment]
for 1, i introduced a python script to do project generation, (maybe not mentioned in the documentation). but the xcodeproj file can be generated by using that script. But for that purpose what the script really does is invoking "swift package generate-xcodeproj" to generate the package (commit 55f9c0650958dd9e20c03c57fbfc09c38b285a4e). we could put back the xcodeproj file if there are still a lot of folks use it by default. I personally don't like putting xcodeproj in the repo just to keep it pure.

2. I'm with you that i don't like to keep Swift 3 either. 

3. I see there is a 4.7.1 milestone @parrt is adding some changes to, that might be it?

**Comment by ewanmellor** [comment]
If Swift Package Manager is all working now, then I'm fine with that.  No need to commit the generated files in that case.  We just need to update the documentation.

@parrt What's the timeframe for 4.7.1?

I'll put together a pull request for Swift 4 support and for the docs update.  I found a few more changes required, some of the string handling needs to be updated, so expect it some time this week.

**Comment by ewanmellor** [comment]
Closing in favor of PR #2032 .

**Comment by parrt** [comment]
I'd like to release 4.7.1 within a week or two if we can get everything to align. I'm ready to start a completely different project and would like to get this out of the way.
