### ISSUE TITLE
Severity	Code	Description	Project	File	Line	Suppression State Error		Unknown build error: "' used multiple times in set: SET	

### ISSUE THREAD

**Issue by psllc** [antlr/antlr4#2043]
Using Visual Studio 2017 with "Antlr4" version="4.6.5-beta001".  I have a project with six grammar files in it.   i'm seeing three instances of the error: 

"Unknown build error: "' used multiple times in set: SET"

no source file, or line number is provided so i don't know which of the six files is responsible.

the Visual Studio build will complete despite these errors, but unfortunately the TFS CI build aborts on these errors.  If i enable 'continue' on the CI build i will be defeating the purpose of the CI gate.    

There are _similar_ issues discussed in various places, but i cannot find anything on this specific one.  The references i _have_ found suggest this problem was resolved in this beta.  Any help would be greatly appreciated.

**Comment by ericvergnaud** [comment]
Hi,
You are not using the official version of Antlr
Please move this to Sam Harwell’s repo.

Envoyé de mon iPhone

**Comment by sharwell** [comment]
Hi @psllc,

It sounds like you are using my C# target: https://github.com/tunnelvisionlabs/antlr4cs. Please file an issue on that repository and we'll figure this out!

Thanks,
Sam

**Comment by psllc** [comment]
i've added this issue to https://github.com/tunnelvisionlabs/antlr4cs.  

thank you gentleman!
