### ISSUE TITLE
antlr4 4.7 - Problems with maven plugin generated code

### ISSUE THREAD

**Issue by Quurz** [antlr/antlr4#2059]
Hello Sam, Hello Terence, Hello to all the other gals and guys here :)

I don't know how I managed to mess this up, but I experienced a problem unsolvable for me.
I'm using IntelliJ 2017.2.5, Maven 3.5.0 and Antlr4 4.7 - Both antlr4-maven-plugin and antlr4-runtime.
Parsing my dummy-grammars works fine but the generated parser shows some problems:

- Class _RuntimeMetaData_ seemingly could not be found (_Cannot resolve symbol 'RuntimeMetaData_')
- Method `public static final String[] tokenNames` is marked as deprecated but _Vocabulary_ is not used
- Constructor `new ParserATNSimulator(this,_ATN,_decisionToDFA,_sharedContextCache)` could not be resolved
- The generated visitor interface could not be found also despite beeing generated in the same location as the parser

Excerpt of my Pom.xml:
```
<properties>
    <antlr4.version>4.7</antlr4.version>
</properties>

<build>
    <pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.antlr</groupId>
                <artifactId>antlr4-maven-plugin</artifactId>
                <version>${antlr4.version}</version>
                <configuration>
                    <sourceDirectory>src/main/grammar/</sourceDirectory>
                    <listener>false</listener>
                    <visitor>true</visitor>
                </configuration>
                <executions>
                    <execution>
                        <id>antlr</id>
                        <goals>
                            <goal>antlr4</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </pluginManagement>

    <plugins>
        <plugin>
            <groupId>org.antlr</groupId>
            <artifactId>antlr4-maven-plugin</artifactId>
        </plugin>
    </plugins>
</build>

<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.tunnelvisionlabs</groupId>
            <artifactId>antlr4-runtime</artifactId>
            <version>${antlr4.version}</version>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
    <dependency>
        <groupId>com.tunnelvisionlabs</groupId>
        <artifactId>antlr4-runtime</artifactId>
        </dependency>
    </dependencies>
</dependencies>
```

I've attached both - lexer and parser - grammar files to this issue.
[TestomatDslParser.g4.zip](https://github.com/antlr/antlr4/files/1385352/TestomatDslParser.g4.zip)

[TestomatDslParser.g4.zip](https://github.com/antlr/antlr4/files/1385351/TestomatDslParser.g4.zip)

Would be great if somebody could help me with this problem. As I said: I can't solve it; I've run out of ideas.

Best regards and a nice Sunday to all of you

Alex

**Comment by ericvergnaud** [comment]
Hi,
The place for support is the google discussion group 
Please move this topic there 
Eric

Envoyé de mon iPhone

**Comment by Quurz** [comment]
Hello Eric

This is not a request for support in the sense a question about how to use Antlr4 or the plugin would be. I think I might have hit an issue/bug.


Best regards

Alex

**Comment by Quurz** [comment]
Hello :)

It seems that in the Antlr4 4.7 dependencies I downloaded from maven-central at least the _RuntimeMetaData_ is just missing. Yay! Didn't expect this!   =D

But where to look now?


Best regards

Alex

**Comment by parrt** [comment]
wow. RuntimeMetaData is missing from the jar?

**Comment by Quurz** [comment]
Hello Terence

Thank you very much for your answer. Unfortunately I was buried deep in work, so I forgot to update this issue.

I think we can forget about the first point. I'v changed the plugin declaration to

```
<pluginManagement>
            <plugins>
                <plugin>
                    <groupId>com.tunnelvisionlabs</groupId>
                    <artifactId>antlr4-maven-plugin</artifactId>
                    <version>${antlr4.version}</version>
                    <configuration>
                        <listener>false</listener>
                        <visitor>true</visitor>
                    </configuration>
                    <executions>
                        <execution>
                            <id>antlr</id>
                            <goals>
                                <goal>antlr4</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
```
and now it works. It seems that the _RuntimeMetaData_-class is/was only missing in the org.antlr artefact.

The second point we can forget also. I'm just blind and dumb. To put it in german: 'Dumm wie drei Meter Feldweg.'   =D

I was able to ship around the third problem too. After using the default directory structure it works again as expected. Might be that I got something wrong here but for me it looks like that the _sourceDirectory_ parameter and the package declarations in the grammar files don't work the way I expected.


Best regards

Alex

**Comment by parrt** [comment]
ok, cool. i'll close.
