### ISSUE TITLE
Grammar rule name conflicts with golang interface

### ISSUE THREAD

**Issue by jasonmoo** [antlr/antlr4#2080]
antlr version: 4.7
antlr repo tag: 4.7

This is a reduced case of a conflict I came across when developing a larger grammar.  The conflict is not with golang's keywords, but with the `antlr.RuleContext` interface methods.  Renaming the rule prevents the conflict.  

```
grammar B;

parse: String EOF ;

String: '.' ;
```

```
antlr4 *.g4 -Dlanguage=Go -o parser
go build
# github.com/jasonmoo/b/parser
parser/b_parser.go:118:2: cannot use s (type *ParseContext) as type antlr.RuleContext in return argument:
	*ParseContext does not implement antlr.RuleContext (wrong type for String method)
		have String() antlr.TerminalNode
		want String([]string, antlr.RuleContext) string
parser/b_parser.go:138:11: cannot use NewParseContext(p, p.BaseParser.GetParserRuleContext(), p.BaseParser.BaseRecognizer.GetState()) (type *ParseContext) as type IParseContext in assignment:
	*ParseContext does not implement IParseContext (wrong type for String method)
		have String() antlr.TerminalNode
		want String([]string, antlr.RuleContext) string
make: *** [build] Error 2
```

**Comment by KvanTTT** [comment]
Feel free to add the bad words to [set](https://github.com/antlr/antlr4/blob/4.7/tool/src/org/antlr/v4/codegen/target/GoTarget.java#L77) and make a pull request!

**Comment by cameron-elliott** [comment]
antlr version: 4.7.2
antlr repo tag: 4.7.2

Nice work by @jasonmoo on this.  Thanks for reporting this, helped me out a ton.

I did run into a related case, if you are using the lower-case equivalent of any of the symbols Jason protected against, the issue still occurs.  (except string cause it's covered in keywords)

[https://github.com/jasonmoo/antlr4/commit/ff2b6344b5e6ba255c77c37a3a9af65f0fd72550](the fix)

```
grammar B;

parse: accept EOF ;

accept: '.' ;
```

```
antlr4 *.g4 -Dlanguage=Go -o parser
go build
PS C:\d\sip\sip-antlr-abnf> go build
# _/C_/d/sip/sip-antlr-abnf
.\b_parser.go:126:2: cannot use s (type *ParseContext) as type antlr.RuleContext in return argument:
        *ParseContext does not implement antlr.RuleContext (wrong type for Accept method)
                have Accept() IAcceptContext
                want Accept(antlr.ParseTreeVisitor) interface {}
.\b_parser.go:146:11: cannot use NewParseContext(p, p.BaseParser.GetParserRuleContext(), p.BaseParser.BaseRecognizer.Get
State()) (type *ParseContext) as type IParseContext in assignment:
        *ParseContext does not implement IParseContext (wrong type for Accept method)
                have Accept() IAcceptContext
                want Accept(antlr.ParseTreeVisitor) interface {}

```

I haven't compiled the Antlr jar before, but I could, I suppose.
I am not sure if the right fix is to add all the lower-case equivalents,
or dig into the bad-word comparer and have it normalize everything to lower-case.
After digging a little further, it seems 'accept' gets turned into 'Accept' 
and 'Accept' gets turned into 'Accept', so both 'accept' and 'Accept' should be banned,
but 'ACcept' won't conflict, so it is fine.

So, the quick & easy method of duplicating the words Jason added,
and lower-casing them should fine.

If no one else wants to add the fix, let me know, I could give it a shot.
