### ISSUE TITLE
Event EnterOptionExplicitStmt don't fire

### ISSUE THREAD

**Issue by lsalamon** [antlr/antlr4#2128]
<b>For exact line:</b>
<pre>Option Explicit</pre>

<b>Event EnterOptionExplicitStmt don't fire but fire event ExitOptionExplicitStmt.</b>

My env:
Antlr4                              {4.6.4}                                  VisualBasic6                                                                                                                                                                          
Antlr4.CodeGenerator                {4.6.4}                                  VisualBasic6                                                                                                                                                                          
Antlr4.Runtime                      {4.6.4}                                  VisualBasic6          

Visual Studio 2017 Community 15.4.4
Windows 10 (1709)

**Comment by ericvergnaud** [comment]
Hi
It seems you’re using the tunnel labs version ?
If so please file the issue on their repo.
Eric

Envoyé de mon iPhone

**Comment by lsalamon** [comment]
Yes. Thanks.
