### ISSUE TITLE
Implement Python2 and Python3 case insensitive input streams

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#2142]
See existed pull requests as an example:

* Java, JavaScript, Go: https://github.com/antlr/antlr4/pull/2046/
* C#: https://github.com/antlr/antlr4/pull/2140

**Comment by parrt** [comment]
If runtime character streams are created in response to this issue, we should add to the documentation injected here https://github.com/antlr/antlr4/pull/2146
