### ISSUE TITLE
Implement C++ case insensitive input stream

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#2143]
See existed pull requests as an example:

* Java, JavaScript, Go: https://github.com/antlr/antlr4/pull/2046/
* C#: https://github.com/antlr/antlr4/pull/2140

**Comment by KvanTTT** [comment]
@mike-lischke how much hard to implement such stream for C++?

**Comment by mike-lischke** [comment]
I commented on #2046. I don't think this is a good idea.

**Comment by parrt** [comment]
@mike-lischke after the responses there, are you ok with this? Should be ok as it leaves actual text alone and just alters how lexer perceives the input.

**Comment by mike-lischke** [comment]
No, I'm not at all ok with such a hack and nothing else is that case conversion stream. If you are willing to add such streams it's of course your freedom to do so. However, I will not waste my time with a "solution" that is broken by design, sorry.

**Comment by parrt** [comment]
ok, let me consider your comments in the other thread.

**Comment by parrt** [comment]
If runtime character streams are created in response to this issue, we should add to the documentation injected here https://github.com/antlr/antlr4/pull/2146

**Comment by ericvergnaud** [comment]
Hi
Am I correct in thinking that keywords should always come before generic tokens such as ID or STRING in a Lexer grammar?
If so wouldn’t it be more accurate and still simple to introduce a ‘caseless’ section in the Lexer grammar ?
I appreciate this requires changing the ANTLR grammar itself but it would remove any ambiguity on what is or isn’t caseless and would immediately work for all targets.
Eric

Envoyé de mon iPhone

**Comment by ericvergnaud** [comment]
It would only accept ascii keywords

Envoyé de mon iPhone
