### ISSUE TITLE
Implement Swift case insensitive input stream

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#2144]
See existed pull requests as an example:

* Java, JavaScript, Go: https://github.com/antlr/antlr4/pull/2046/
* C#: https://github.com/antlr/antlr4/pull/2140

**Comment by parrt** [comment]
@ewanmellor @hanjoes does this impl look ok in swift?

**Comment by ewanmellor** [comment]
@parrt There's no code yet; this is "please implement" not "here's an implementation" ;-)

The Swift code would look very similar to the Java code, so we'd just port over once the discussion on #2046 is settled.

**Comment by parrt** [comment]
If runtime character streams are created in response to this issue, we should add to the documentation injected here https://github.com/antlr/antlr4/pull/2146

**Comment by hanjoes** [comment]
I'm taking a vacation in China :) will be back in a month.

**Comment by KvanTTT** [comment]
Now it's not actual since the option [`caseInsensitive`](https://github.com/antlr/antlr4/blob/dev/doc/options.md#caseinsensitive) has been implemented.
