### ISSUE TITLE
Swift 4 error logging

### ISSUE THREAD

**Issue by MutatingFunk** [antlr/antlr4#2145]
For a Swift 4 Xcode project targeting macOS, using the latest release version of Antlr, attempting to print errors (AntlrException) results in a crash, rather than printing a description of the error.

It also seems impossible to catch an AntlrException using a catch block:
```
} catch let error as AntlrException {
  print(error) //not reached
} catch let error {
  if let error = error as? AntlrException {
    print(error) //not reached
  }
  print(error) //error is of type AntlrException
}
```

I think this is partly to do with the Swift 3 to Swift 4 bridging (though this is mostly speculation based on Swift 4's behind-the-scenes changes to enums, and other libraries showing similar issues). Are there plans to add Swift 4 support by the next release?

**Comment by ewanmellor** [comment]
Swift 4 support is all in master, and will be in 4.7.1 when it ships.

I have no idea why your error handling isn't working there, but Swift 3-to-4 bridging sounds plausible to me.

Assuming you copy-pasted that code rather than retyped it, then I notice that you have `AntlrException`, whereas I have `ANTLRException`.  I don't think it's ever been spelled with the lowercase, so maybe you have some other `AntlrException` in your codebase?

Regardless, if I were you I would upgrade to master.  There are lots of improvements in the Swift runtime, not least the Swift 4 support.

**Comment by MutatingFunk** [comment]
Thanks for your response!

> `AntlrException`
Nice catch. Because it's a simple example, I tested in Xcode but then retyped from memory without double-checking the typename. I meant to put `ANTLRException`.

Using the master branch would be ideal. When I tried previously, I couldn't find an updated version of the code-generation script, and the only version linked at antlr.org/download.html is 4.7, and the docs (/doc/getting-started.md) don't give any other directions for how to obtain it. Is there a way to generate an updated version of this tool?

**Comment by ewanmellor** [comment]
@MutatingFunk You want the "Building ANTLR" instructions at https://github.com/antlr/antlr4/blob/master/doc/building-antlr.md.

Basically, it's `git clone https://github.com/antlr/antlr4.git; cd antlr4; mvn -DskipTests install`

**Comment by MutatingFunk** [comment]
Thanks! It turned out to be a bit more involved since I hadn't got mvn (Apache Maven) installed, but I can now confirm this is fixed in master.

Looking forward to the 4.7.1 release. 😊

**Comment by MutatingFunk** [comment]
On further investigation, the odd casting behaviour I described above is still happening, and attempting to print the error with `print(error)` still crashes. I don't see any obvious issues with the Antlr library, ANTLRException is just a two-case enum with associated values conforming to Error, so I think Swift is what needs fixing here. I'll close this issue.

What does now work is setting a breakpoint and printing from the debug console with `print error`, so that's some improvement.

**Comment by ewanmellor** [comment]
@MutatingFunk I just had a crash that looked like the problem you were describing (in a different project, not ANTLR).  I had one module using Swift 3.2 and one using Swift 4.0, and it crashed bridging an Error to NSError.  I fixed it by setting everything to Swift 4.0, and making sure to be dynamically linking against the Swift runtime, not embedding it anywhere (ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = NO everywhere).

**Comment by MutatingFunk** [comment]
Sounds like what I need, I'll try experimenting when I get some time.

**Comment by MutatingFunk** [comment]
It seems the key is set to NO for the command line target (and all it's libraries), yet based on the console log it's finding an embedded version of the standard library types. I've tried updating the other dependency (LLVMSwift) to the Swift 4 version from master, with no luck.

**Comment by ewanmellor** [comment]
Try setting `SWIFT_FORCE_STATIC_LINK_STDLIB=NO` and `SWIFT_FORCE_DYNAMIC_LINK_STDLIB=YES` as User-Defined Settings at the project level.  That's an (apparently undocumented) dirty trick that I found for command-line targets that I'm still using.  I'd be interested to know if that solves your problem.

**Comment by MutatingFunk** [comment]
It works!

Initially, I got an image not found error: `dyld: Library not loaded: @rpath/libswiftCore.dylib`, indicating something in the project wasn't able to find the Xcode toolchain version of libswift.

Adding `$(TOOLCHAIN_DIR)/usr/lib/swift/macosx` to the command-line target's Runpath Search Paths got it working.
(This value was already present in LLVM and Antlr's build settings, and removing it from those didn't stop it finding the toolchain version)

Sure enough, my test now prints `parseCancellation(Antlr4.NoViableAltException)` in the log, and I can catch `ANTLRException`s explicitly, too.

Thanks a lot for the help! I've not been able to find a great deal of resources to help with these project setup issues, so your assistance is much appreciated.

**Comment by martinvw** [comment]
Just for the record, maybe others end up here as well, I was facing a lot of nasty errors because of unwrapping a nil which happened in case of syntax errors:

> Unexpectedly found nil while implicitly unwrapping an Optional value

In the end, I just did not yet enable the `BailOutStrategy`, so after adding:

```swift
parser.setErrorHandler(BailErrorStrategy())
```
It stopped on errors and no more crashes.
