### ISSUE TITLE
Escaping difference in 4.7.1

### ISSUE THREAD

**Issue by davesisson** [antlr/antlr4#2157]
Before 4.7.1 the following sequence works:

fragment SPECIAL_ESC_CHAR                                                                                                                     : ('b'|'t'|'n'|'f'|'r'|'\"'|'\''|'\\')
    ;

However in 4.7.1 it yields the 
warning(156): /build/work/7223b1de40fbf08fc15b5cfc4451fe6a/google3/292309.tmp/GclLexer.g4:78:28: invalid escape sequence \"

I tried a few alternatives ("\", '\') but was not able to get the warning to go away.  Is there a recommended alternative or is this something we need to fix?

**Comment by KvanTTT** [comment]
This is a very strange sequence. A quote `'` and a backslash `\` should be escaped.

**Comment by davesisson** [comment]
Looking more carefully at the error text it's actually complaining about an escaped double quote.  The pasted text above has some escape sequences elided.

The simple fix was to not escape double quote marks.
