### ISSUE TITLE
Show labeled alternatives in tree viewer

### ISSUE THREAD

**Issue by sharwell** [antlr/antlr4#217]
Currently labeled alternatives in the parse tree show up in the tree viewer with only the enclosing rule name. It would be helpful to show the unique alternative label instead.

**Comment by rienheuver** [comment]
This feature would still be very much appreciated. If the same information could be displayed in some other way that would be fine too.

**Comment by parrt** [comment]
The intellij plugin 1.7, due soon, has this :)  You can use the new, 4.5.1, GrammerParserInterpreter to get the alt num / label. Fixed in https://github.com/antlr/antlr4/pull/914.
