### ISSUE TITLE
Comment contradicts code (in all run-times)?

### ISSUE THREAD

**Issue by niccroad** [antlr/antlr4#2172]
In this function of PredictionContext.

```
public static PredictionContext mergeRoot(SingletonPredictionContext a,
											  SingletonPredictionContext b,
											  boolean rootIsWildcard)
	{
		if ( rootIsWildcard ) {
			if ( a == EMPTY ) return EMPTY;  // * + b = *
			if ( b == EMPTY ) return EMPTY;  // a + * = *
		}
		else {
			if ( a == EMPTY && b == EMPTY ) return EMPTY; // $ + $ = $
			if ( a == EMPTY ) { // $ + x = [$,x]
				int[] payloads = {b.returnState, EMPTY_RETURN_STATE};
				PredictionContext[] parents = {b.parent, null};
				PredictionContext joined =
					new ArrayPredictionContext(parents, payloads);
				return joined;
			}
			if ( b == EMPTY ) { // x + $ = [$,x] ($ is always first if present)
				int[] payloads = {a.returnState, EMPTY_RETURN_STATE};
				PredictionContext[] parents = {a.parent, null};
				PredictionContext joined =
					new ArrayPredictionContext(parents, payloads);
				return joined;
			}
		}
		return null;
	}
```
The comments // $ + x = [$,x]
and more explicitly // x + $ = [$,x] ($ is always first if present)

Seem to contradict the implementation. This was done 6 years ago by @parrt.
Should the order in the comments not be [x,$], ($ is always second if present)?

**Comment by parrt** [comment]
Indeed that looks weird.  @sharwell note that we create

```
int[] payloads = {b.returnState, EMPTY_RETURN_STATE};
```

but `isEmpty()` tests 

```java
// since EMPTY_RETURN_STATE can only appear in the last position, we
// don't need to verify that size==1
return returnStates[0]==EMPTY_RETURN_STATE;
```

That seems like a glaring problem but we've not seen any weird bugs have we?

**Comment by parrt** [comment]
Actually, now I see something else:

```java
public boolean hasEmptyPath() {
	// since EMPTY_RETURN_STATE can only appear in the last position, we check last one
	return getReturnState(size() - 1) == EMPTY_RETURN_STATE;
}
```

**Comment by sharwell** [comment]
So this is just a bug to update the comment in code?

**Comment by parrt** [comment]
Actually, it looks like a bug. Test for ArrayPredictionContext.isEmpty expects EMPTY_RETURN_STATE in position 0 but mergeRoot() is putting it at position 1

**Comment by sharwell** [comment]
> Actually, it looks like a bug. Test for ArrayPredictionContext.isEmpty expects EMPTY_RETURN_STATE in position 0 but mergeRoot() is putting it at position 1

The result of mergeRoot is not empty.

**Comment by parrt** [comment]
Doesn't it create an array context with `int[] payloads = {b.returnState, EMPTY_RETURN_STATE};` putting the empty in 2nd position?

**Comment by sharwell** [comment]
`isEmpty` is a combination of (hasEmptyPath) and (size() == 1). The "weird" indexing is an optimization leveraging an invariant of the data structure to eliminate a call to `size()` on a hot path.

**Comment by parrt** [comment]
interesting. ok, so is the "fix" just changing this comment?

```
// x + $ = [$,x] ($ is always first if present)
```

to

```
// x + $ = [x,$] ($ is always last if present)
```

**Comment by sharwell** [comment]
> interesting. ok, so is the "fix" just changing this comment?

I believe that is correct.

**Comment by parrt** [comment]
ok, cool. thanks!
