### ISSUE TITLE
Go target generates invalid code

### ISSUE THREAD

**Issue by erbridge** [antlr/antlr4#2174]
Using the grammar from https://github.com/antlr/grammars-v4/tree/master/csharp (after renaming `type` to `type_` to avoid a conflict) to generate listeners for the Go target produces Go files with segments of Java in them.

For example, the beginning of `csharp_lexer.go`:
```go
// Generated from CSharpLexer.g4 by ANTLR 4.6.

package parser

import (
	"fmt"
	"unicode"

	"github.com/antlr/antlr4/runtime/Go/antlr"
)

import java.util.Stack;
```

And later in the same file:
```go
// CSharpLexer modes
const (
	CSharpLexerINTERPOLATION_STRING = iota + 1
	CSharpLexerINTERPOLATION_FORMAT
	CSharpLexerDIRECTIVE_MODE
	CSharpLexerDIRECTIVE_TEXT
)

private int interpolatedStringLevel;
private Stack<Boolean> interpolatedVerbatiums = new Stack<Boolean>();
private Stack<Integer> curlyLevels = new Stack<Integer>();
private boolean verbatium;
```

I tried a bunch of other grammars to see if I could work out why this is happening, but the C# grammar was the only one I tried that caused it, and this is my first encounter with ANTLR, so I have no further insight.

**Comment by ericvergnaud** [comment]
Hi
This is because the grammar itself contains Java segments.
Please go to the google discussion group for support 
Eric

Envoyé de mon iPhone

**Comment by erbridge** [comment]
Ah, ok. I wasn't aware that this was expected behaviour. It would be good if grammars explicitly stated which target(s) they supported.
