### ISSUE TITLE
Cpp Runtime has memory leak in ParserATNSimulator

### ISSUE THREAD

**Issue by niccroad** [antlr/antlr4#2175]
Looks like this will leak memory if ambigAlts.test(i) is ever true but pred != SemanticContext::NONE is always false. This will mean pairs.clear is called without its contents being deleted.

`std::vector<dfa::DFAState::PredPrediction *> ParserATNSimulator::getPredicatePredictions(const antlrcpp::BitSet &ambigAlts,
  std::vector<Ref<SemanticContext>> altToPred) {
  std::vector<dfa::DFAState::PredPrediction*> pairs;
  bool containsPredicate = false;
  for (size_t i = 1; i < altToPred.size(); i++) {
    Ref<SemanticContext> pred = altToPred[i];

    // unpredicted is indicated by SemanticContext.NONE
    assert(pred != nullptr);

    if (ambigAlts.test(i)) {
      pairs.push_back(new dfa::DFAState::PredPrediction(pred, (int)i)); /* mem-check: managed by the DFAState it will be assigned to after return */
    }
    if (pred != SemanticContext::NONE) {
      containsPredicate = true;
    }
  }

  if (!containsPredicate) {
    pairs.clear();
  }

  return pairs;
}`

Note, in the event this can't happen pairs.clear() is redundant, so my assumption would be that this can happen.
I intend to have a patch for this submitted soon myself.

**Comment by garzon** [comment]
Reference: https://github.com/antlr/antlr4/pull/2176 this PR should solve this problem.
However, there are still memory leaks somewhere else I believe. Core developers should really look into them.

**Comment by mike-lischke** [comment]
@niccroad Your observation is correct.
@garzon Let us know when you have an indication that there are more memory leaks. But please be concrete. What exactly repdoduces a leak (if it is not obvious from source code like this one here)?

**Comment by garzon** [comment]
@mike-lischke Yeah, of course, but for now I just figure out there are memory leaks (maybe ATNConfig is involved, I am not sure). When I know where they are, I will definitely let you know.

**Comment by niccroad** [comment]
@garzon Even if you only have examples of grammars and inputs which **definitely** produce a memory leak of some run-time object this would be quite useful to resolve these. To some extent its just a manual process of logging the allocations and de-allocations once the cases are known.
