### ISSUE TITLE
Enhancement Request: Adding Antlr-internal Variable and Collection Definition/Usage

### ISSUE THREAD

**Issue by jeffsaremi** [antlr/antlr4#2185]
We are recommended to not intertwine the parser/lexer definitions with target code. This rightly eliminates the portability issue of these definitions when multiple targets are desired.
However in some cases this is not avoidable. 
What I am suggesting is to extend Antlr's own vocabulary to allow common variables (int's, bool's, ...) and common collections (map, stack, queue, array) to be declared and used without being tied to any specific language including Java.
This should take care of a large percentage of cases where such structures are needed however the target specific code must be avoided.
thanks

**Comment by ericvergnaud** [comment]
Hi,
I'm afraid this is would be a bit of a pandora box.
please move this to the google discussion group.
Eric

**Comment by jeffsaremi** [comment]
closing as recommended
