### ISSUE TITLE
[CPP] ANTLR 4.7.1 multi-threading crash

### ISSUE THREAD

**Issue by chund** [antlr/antlr4#2199]
Hi,
could someone help and provide some insight?

Scenario:
ANTLR 4.7.1 C++ target
4 threads each parsing 4 different sample files in a loop.

In ANTLR multi-threading I see a crash probably because of a synchronization issue between two threads (the other 2 threads in my scenario are in waiting for the mutex). Seems there is some synchronization missing (see callstacks below).

If someone could give some input how locking should work, I could do the fix.

Thanks,
Christian

Crashing thread (this one owns the ATNSimulator::_stateLock):

>	antlr4-runtime.dll!std::vector<std::shared_ptr<antlr4::atn::ATNConfig>,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > >::size() Line 1148
 	antlr4-runtime.dll!antlr4::atn::**ATNConfigSet::operator==**(const antlr4::atn::ATNConfigSet & other) Line 140
 	antlr4-runtime.dll!antlr4::dfa::DFAState::operator==(const antlr4::dfa::DFAState & o) Line 75
 	antlr4-runtime.dll!antlr4::dfa::DFAState::Comparer::operator()(antlr4::dfa::DFAState * lhs, antlr4::dfa::DFAState * rhs) Line 136
 	[External Code]		Annotated Frame
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::addDFAState(antlr4::dfa::DFA & dfa, antlr4::dfa::DFAState * D) Line 1277
 	antlr4-runtime.dll!antlr4::atn::**ParserATNSimulator::adaptivePredict**(antlr4::TokenStream * input, unsigned int decision, antlr4::ParserRuleContext * outerContext) Line 129

Other thread also accessing/changing the ATNConfigSet (this one seems to lack the lock):

	antlr4-runtime.dll!antlr4::atn::PredictionContext::merge(const std::shared_ptr<antlr4::atn::PredictionContext> & a, const std::shared_ptr<antlr4::atn::PredictionContext> & b, bool rootIsWildcard, antlr4::atn::PredictionContextMergeCache * mergeCache) Line 135
 	antlr4-runtime.dll!antlr4::atn::**ATNConfigSet::add**(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::PredictionContextMergeCache * mergeCache) Line 61
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure_(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 884
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 874
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure_(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 943
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 874
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure_(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 943
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 874
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure_(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 943
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 874
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure_(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 943
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 874
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure_(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 943
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 874
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure_(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 943
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 874
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure_(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 943
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 874
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 862
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure_(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 943
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 874
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure_(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 943
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 874
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure_(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 943
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 874
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure_(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 943
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 874
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure_(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 943
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 874
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 862
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure_(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 943
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 874
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure_(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 943
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 874
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure_(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 943
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 874
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure_(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 943
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 874
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure_(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 943
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closureCheckingStopState(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, int depth, bool treatEofAsEpsilon) Line 874
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::closure(const std::shared_ptr<antlr4::atn::ATNConfig> & config, antlr4::atn::ATNConfigSet * configs, std::unordered_set<std::shared_ptr<antlr4::atn::ATNConfig>,antlr4::atn::ATNConfig::Hasher,antlr4::atn::ATNConfig::Comparer,std::allocator<std::shared_ptr<antlr4::atn::ATNConfig> > > & closureBusy, bool collectPredicates, bool fullCtx, bool treatEofAsEpsilon) Line 819
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::computeReachSet(antlr4::atn::ATNConfigSet * closure_, unsigned int t, bool fullCtx) Line 510
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::computeTargetState(antlr4::dfa::DFA & dfa, antlr4::dfa::DFAState * previousD, unsigned int t) Line 270
 	antlr4-runtime.dll!antlr4::atn::ParserATNSimulator::execATN(antlr4::dfa::DFA & dfa, antlr4::dfa::DFAState * s0, antlr4::TokenStream * input, unsigned int startIndex, antlr4::ParserRuleContext * outerContext) Line 165
>	antlr4-runtime.dll!antlr4::atn::**ParserATNSimulator::adaptivePredict**(antlr4::TokenStream * input, unsigned int decision, antlr4::ParserRuleContext * outerContext) Line 141

**Comment by mike-lischke** [comment]
Addressed in PR #2177 (more specifically [these lines](https://github.com/antlr/antlr4/pull/2177/files#diff-0b823cac9edba8f736200a2ffc83a17eR130))

**Comment by chund** [comment]
great :)
ANTLR 4.7.1 plus PR #2177 seem to fix all my multi-threading issues.
