### ISSUE TITLE
release management - code generation audit trail to new repo 

### ISSUE THREAD

**Issue by johndpope** [antlr/antlr4#2204]
with 4.7.1 - I noticed a breaking change to swift code generation. this bug is detailed below.
 
I recommend introducing an extra pre-step to releasing new antlr runtimes that would help avoid regression. That is to have a script that would refresh all the gramma files -  and generate out the tokens / lexars / parsers across every gramma file for every supported language.

eg. here - we're targeting swift
https://github.com/johndpope/swift-walker-antlr/blob/master/RefreshGramma.sh

// can be extended to other TARGETS = ['csharp', 'cpp', 'go', 'java', 'javascript', 'python2', 'python3', 'swift']
 java -cp antlr-4.7.1-complete.jar org.antlr.v4.Tool -Dlanguage=Swift -visitor -o gen $file_path

because it's all version controlled - every change is tracked.
![screen shot 2018-01-18 at 9 55 13 am](https://user-images.githubusercontent.com/289994/35105487-cc508552-fc39-11e7-880a-e644bcdc8ba3.png)

while drafting new version / point release of antlr - a pr could be submitted - and  the respective code could be viewable and language buffs  in domains could chime in if something looks off.

![screen shot 2018-01-18 at 10 26 04 am](https://user-images.githubusercontent.com/289994/35105589-0aed2a54-fc3a-11e7-96bb-d7c6103a193b.png)

https://github.com/johndpope/swift-walker-antlr/blob/master/gen/grammars-v4/golang/GolangParser.swift#L142

  private boolean lineTerminatorAhead()
should be
  func lineTerminatorAhead() -> Bool{

ideally - the tests would capture this too but just getting audit-able visibility across changes would help steer test cases.

**Comment by johndpope** [comment]
@hanjoes  - fyi

**Comment by ericvergnaud** [comment]
Hi,
Please note that the grammars repo is not officially supported.
If someone is interested in supporting it, it could indeed make sense to automate the validation of grammars across antlr targets and versions.
But it’s probably too much burden for target authors themselves so would require additional people to get involved. 

Envoyé de mon iPhone

**Comment by hanjoes** [comment]
@johndpope it doesn't seem to be a regression in the runtime instead of unsupported action code in grammar. 

If you look at [this line](https://github.com/antlr/grammars-v4/blob/master/golang/Golang.g4#L48) of the Golang.g4 file, it's in @members section, which are action code written in the target language assumed by the author of the grammar that will be injected in to the parser or lexer. It's unlikely the grammar author can support all potential target language when writing the gammar.

**Comment by johndpope** [comment]
Thanks hanjoes, I spent some time to get it working but thoughts are this is constantly in decay with each antlr version bump. Not sure best way to handle it. But having things in the open with automation would be a start. Totally open for title of repo to include antl-gen-gramma-UNDUPPORTED to brush off support and include big disclaimers in readme file. ‘This repo not officially supported’. We welcome contributors. Want to be a champion moderator....sign up here.
Currently targeting runtimes in cpp, csharp etc...

Each point release could safely blast away pregenerated code from previous release.
Contributors willingly re-submit updated patches. 

In this situation you end up with 1000 developers spending combined hours to fix bugs in  vs 1000 developers spending an hour patching each same file In disparate repos. 

Inside you could nest folders of targets.
And include release notes where users could go back in time to inspect things with some knowledge transfer. 

Readme.md
Swift generation 
* This proto gramma file worked in this language target but totally fails in this  language. We Use xyz file instead.

**Comment by johndpope** [comment]
going to close this - I think this is still very important as any changes could be easily tracked back to version updates. going to leave this
