### ISSUE TITLE
Can't setPredictionMode in JavaScript or Python

### ISSUE THREAD

**Issue by kasbah** [antlr/antlr4#2206]
I tried to set up ambiguity detection in JavaScript but there is neither a `getInterpreter` method nor a `setPredictionMode` on the `parser._interp` attribute. Here's what I hoped would work, translated from Java:

```js
parser
    .getInterpreter()
    .setPredictionMode(antlr.atn.PredictionMode.LL_EXACT_AMBIG_DETECTION);
```
---

same for Python, can't do:
```python
parser.getInterpreter().setPredictionMode(PredictionMode.LL_EXACT_AMBIG_DETECTION)
```
---
found that I _can_ do:
```python
parser._interp.predictionMode = PredictionMode.LL_EXACT_AMBIG_DETECTION
```

Is this safe? Is this the way it's supposed to be done?

**Comment by ericvergnaud** [comment]
What about
parser._interp.predictionMode = ...
?

Envoyé de mon iPhone

**Comment by kasbah** [comment]
Thanks @ericvergnaud, I had noticed this too and edited my issue. Is that the right way to do it then?

**Comment by ericvergnaud** [comment]
Yes
Getters and setters are a java practice but they are not a js or python one.

**Comment by kasbah** [comment]
Thanks!
