### ISSUE TITLE
VS2017 link error when using antlrcpp::Any

### ISSUE THREAD

**Issue by EternalPhane** [antlr/antlr4#2211]
Hello. I'm trying to use `antlrcpp::Any` and got the following errors when building with VS2017:
```
error LNK2019: unresolved external symbol "public: virtual __thiscall antlrcpp::Any::Base::~Base(void)" (??1Base@Any@antlrcpp@@UAE@XZ) referenced in function "public: virtual __thiscall antlrcpp::Any::Derived<int>::~Derived<int>(void)" (??1?$Derived@H@Any@antlrcpp@@UAE@XZ)
fatal error LNK1120: 1 unresolved externals
```
Test.cpp:
```cpp
#include <antlr4-runtime.h>
#include <iostream>

int main()
{
	int i = 0;
	antlrcpp::Any test(i);
	std::cout << test.as<int>() << std::endl;
	return 0;
}
```
However, if I move the definition of `antlrcpp::Any::Base::~Base()` inline, it works as expected. I don't know whether this is a bug of VS2017 or my usage of `antlrcpp::Any` is wrong in the above code. Could you please address this issue?

**Comment by Chengifei** [comment]
I have the same problem, a wild guess might be the symbol is being not exported.

**Comment by kfwalther** [comment]
I also had the same problem when extending the TParserBaseVisitor class with my own visitor class. The antlrcpp::Any::Base::~Base() in the .cpp file isn't seen by the linker for some reason. As @EternalPhane suggested, copying the destructor definition inline into my custom Visitor class header file fixed the issue. I've only tested on VS2017, so not sure if the other VS versions are seeing the same problem. Maybe @mike-lischke can provide insight on the issue.

**Comment by mike-lischke** [comment]
Unfortunately, I missed the fact that the Any class is not exported, when I approved the patch which changed the d-tor. Previously it was a header only class. In fact I think now that move of the d-tor to a cpp file was unnecessary, mea culpa. So, the best solution is to move the d-tor back to the header.

**Comment by EternalPhane** [comment]
@mike-lischke I've made a pr for this issue. Please check #2213. Thanks.

**Comment by siliconvoodoo** [comment]
it still doesn't work but now with the move constructor for some reason. and a bunch of other functions.

`error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl antlrcpp::Any::Any(struct antlrcpp::Any &&)" (__imp_??0Any@antlrcpp@@QEAA@$$QEAU01@@Z)
error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual struct antlrcpp::Any __cdecl antlr4::tree::AbstractParseTreeVisitor::visit(class antlr4::tree::ParseTree *)" (__imp_?visit@AbstractParseTreeVisitor@tree@antlr4@@UEAA?AUAny@antlrcpp@@PEAVParseTree@23@@Z)
error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl antlr4::tree::AbstractParseTreeVisitor::AbstractParseTreeVisitor(void)" (__imp_??0AbstractParseTreeVisitor@tree@antlr4@@QEAA@XZ)
error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl antlr4::tree::AbstractParseTreeVisitor::~AbstractParseTreeVisitor(void)" (__imp_??1AbstractParseTreeVisitor@tree@antlr4@@UEAA@XZ)
error LNK2001: unresolved external symbol "protected: virtual struct antlrcpp::Any __cdecl antlr4::tree::AbstractParseTreeVisitor::aggregateResult(struct antlrcpp::Any,struct antlrcpp::Any const &)" (?aggregateResult@AbstractParseTreeVisitor@tree@antlr4@@MEAA?AUAny@antlrcpp@@U45@AEBU45@@Z)
error LNK2001: unresolved external symbol "protected: virtual struct antlrcpp::Any __cdecl antlr4::tree::AbstractParseTreeVisitor::defaultResult(void)" (?defaultResult@AbstractParseTreeVisitor@tree@antlr4@@MEAA?AUAny@antlrcpp@@XZ)
error LNK2001: unresolved external symbol "protected: virtual bool __cdecl antlr4::tree::AbstractParseTreeVisitor::shouldVisitNextChild(class antlr4::tree::ParseTree *,struct antlrcpp::Any const &)" (?shouldVisitNextChild@AbstractParseTreeVisitor@tree@antlr4@@MEAA_NPEAVParseTree@23@AEBUAny@antlrcpp@@@Z)
error LNK2001: unresolved external symbol "public: virtual struct antlrcpp::Any __cdecl antlr4::tree::AbstractParseTreeVisitor::visit(class antlr4::tree::ParseTree *)" (?visit@AbstractParseTreeVisitor@tree@antlr4@@UEAA?AUAny@antlrcpp@@PEAVParseTree@23@@Z)
error LNK2001: unresolved external symbol "public: virtual struct antlrcpp::Any __cdecl antlr4::tree::AbstractParseTreeVisitor::visitChildren(class antlr4::tree::ParseTree *)" (?visitChildren@AbstractParseTreeVisitor@tree@antlr4@@UEAA?AUAny@antlrcpp@@PEAVParseTree@23@@Z)
error LNK2001: unresolved external symbol "public: virtual struct antlrcpp::Any __cdecl antlr4::tree::AbstractParseTreeVisitor::visitErrorNode(class antlr4::tree::ErrorNode *)" (?visitErrorNode@AbstractParseTreeVisitor@tree@antlr4@@UEAA?AUAny@antlrcpp@@PEAVErrorNode@23@@Z)
error LNK2001: unresolved external symbol "public: virtual struct antlrcpp::Any __cdecl antlr4::tree::AbstractParseTreeVisitor::visitTerminal(class antlr4::tree::TerminalNode *)" (?visitTerminal@AbstractParseTreeVisitor@tree@antlr4@@UEAA?AUAny@antlrcpp@@PEAVTerminalNode@23@@Z)
fatal error LNK1120: 11 unresolved externals`

**Comment by siliconvoodoo** [comment]
tried the ParseTreeWalker and same problem with 3 functions. (constr/destr and walk)

**Comment by siliconvoodoo** [comment]
dumpbin says the symbols appear to be here though. it's the same the linker complains about not finding.
![image](https://user-images.githubusercontent.com/25970839/46804968-ebd60a00-cd9e-11e8-8e87-31df985d4d9d.png)

**Comment by mike-lischke** [comment]
Yet another case of not compiling object code? Anyway, you should open a new issue instead of re-using a closed one.

Maybe we should go C++17 and use their variant (or any) class? This will limit the user base to those having upgraded or are willing to upgrade to C++17, but being a bit progressive is not a bad thing anyway (and the previous version would still be available for those that don't want).

**Comment by siliconvoodoo** [comment]
I need to test the dynamic link first. but the fix is probably less drastic, like detecting static link and requiring to define `ANTLR4CPP_STATIC` in the client project.
At least if google can match the error message and return this advice, it's good too.

**Comment by mike-lischke** [comment]
@siliconvoodoo I've created a new PR (#2383) which adds VS 2017 project + solution files. They build fine for me for all targets (DLL, static lib, debug + release). See if that works for you too.
