### ISSUE TITLE
antlr 4.7.1 parsing issue

### ISSUE THREAD

**Issue by krishnak0209** [antlr/antlr4#2212]
I have coded the following in my G4 file

fragment
CobolLetterOrDigit
    : [A-Za-z0-9-_]
    ;    

using antlr 4.7.1, I get the warning message:
chars '<INVALID>'..'_' used multiple times in set [A-Za-z0-9-_]

I am not getting this message when I use antlr 4.5.1

can you please help.

**Comment by sharwell** [comment]
You need to reverse the order of `-` and `_` in the set. The `-` character has special meaning except when placed at the beginning or end. As an alternative, you can escape the character using `\-`.

**Comment by krishnak0209** [comment]
Thanks sharwell - that worked...appreciate your help.
