### ISSUE TITLE
Antlr4 gui doesnt pop up

### ISSUE THREAD

**Issue by TekinGullu** [antlr/antlr4#2217]
On cmd or eclipse oxygen I tried antlr4.7.1 & 4.7 & 4.4 versions all of them I faced Testrig gui doesnt pop up on my windows machine but it comes on taskbar ı controlled it with alt + tab or windows tab I can see there is but  I cannot click it.  Searching internet for this issue I found this question on stackoverflow cite

https://stackoverflow.com/questions/44788952/antlr4-on-windows7-parse-tree-inspector-doesnt-pop-up-when-testrig-is-called

**Comment by schandrasekhar** [comment]
i am having a similar issue where the gui is not showing up. Followed the setup instructions here
https://github.com/antlr/antlr4/blob/master/doc/getting-started.md
Here is what i am trying out

$ grun Hello r -gui --diagnostics
hello world

This is my folder structure

$ ls
Hello.g4			HelloBaseListener.java		HelloLexer.tokens		HelloParser.class
Hello.interp			HelloLexer.class		HelloListener.class		HelloParser.java
Hello.tokens			HelloLexer.interp		HelloListener.java
HelloBaseListener.class		HelloLexer.java			HelloParser$RContext.class
This is the version of OS i am using Mac OS 10.13.6
Am I doing something wrong here ? Can anyone help

**Comment by HmSebastianH** [comment]
I am having the same problems as described above with the latest antlr4 release and Windows 10.

I tried with the very basic Hello.g4 example grammar. The Grammars seem to be parsable just fine, token and trace options seem to be working as expected. I remeber it working a few weeks ago thought, so maybe a Windows or Java update is to blame? 

Java Version
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```
Windows Version
``Windows 10 Pro 1803``

**Comment by schandrasekhar** [comment]
@HmSebastianH  u need to add a `^D` in a new line. In my mac it looks like
```
$ grun Hello r -gui --diagnostics
hello world
^D
```
This worked for me

**Comment by schandrasekhar** [comment]
@HmSebastianH  more specifically this `(That ^D means EOF on unix; it's ^Z in Windows.)`

**Comment by parrt** [comment]
no doubt it's an EOF issue. try `<` with a file as well.

**Comment by HmSebastianH** [comment]
Thank you for the quick answer, but unfortunately it does not seem to work for me.

I added a simple start rule with the EOF to test it a bit more, but I cant get the gui to open.

```
java org.antlr.v4.gui.TestRig Hello start -tree
hello world
^Z
(start (r hello world) <EOF>)

java org.antlr.v4.gui.TestRig Hello start -gui
hello world
^Z
```

The tree option works correctly, but the gui option freezes with the guis icon being displayed under windows but no Window showing up. (Its not hidden anywhere either, see screenshot below)
![screen](https://user-images.githubusercontent.com/22633824/49033788-653f8580-f1b0-11e8-9fdf-1a81a33c59cb.png
)

Is there any reason why the gui should work differently than the ``-tree`` option?
If I call the TestRig with a file as parameter, shouldn't it always have a ``<EOF>`` token?

I have no problem getting a TreeListner to work with files as input and the InteliJ IDE plugin can handle the Grammar OK too, but the TestRig would be helpfull to test grammars with embedded actions.

Greetings.

**Comment by parrt** [comment]
Hmm...mysterious. Maybe try with a file and `<` but I have no idea on windows why that wouldn't appear.

**Comment by HmSebastianH** [comment]
Didnt work either. I tried it on another windows machine with the same java and antlr version and it works just fine there. Might be a driver problem.

**Comment by chakpongchung** [comment]
same problem on windows here

**Comment by PabloCoto** [comment]
same problem on windows here
@parrt

**Comment by PabloCoto** [comment]
same problem on windows 
@parrt

**Comment by parrt** [comment]
are you hitting control-X or typing `^Z`?  maybe you need to hit return also.

**Comment by crylearner** [comment]
same problem on windows 8

**Comment by arekgofi** [comment]
same problem windows 7

**Comment by parrt** [comment]
Apparently if you "*ctrl + right click + enlarge screen, the problem is solved.*" "*The problem was that when you executed "gui.bat source" the window which contains the SVG Tree was not visible. The solution we found in our class was to press: ctrl + shift + maximize. In this way, the problem is solved.*"

**Comment by CAVAh** [comment]
For anyone that having troubles:
```
java org.antlr.v4.gui.TestRig Hello start -gui
hello world
^Z   << here is Ctrl + Z 
(after you need tap Enter)
```

**Comment by mwasigala** [comment]
> For anyone that having troubles:
> 
> ```
> java org.antlr.v4.gui.TestRig Hello start -gui
> hello world
> ^Z   << here is Ctrl + Z 
> (after you need tap Enter)
> ```

Thanks @CAVAh  this fixed the issue
