### ISSUE TITLE
C++ Runtime: Building With Ninja Fails If Path Contains Spaces

### ISSUE THREAD

**Issue by sanssecours** [antlr/antlr4#2219]
👋 Hi,

let me start by thanking everyone involved in the ANTLR project for providing this super useful parser generator.

The bug report below describes a weird bug that I encountered today, while I tried to integrate ANTLR in a CMake based project.  

# Steps to Reproduce the Problem

Open a Terminal window and paste the code below.

```sh
mkdir 'Blank Space'
cd 'Blank Space'
git clone https://github.com/antlr/antlr4.git
mkdir Build
cd Build
cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -BUILD_TESTS=OFF ../antlr4/runtime/Cpp
ninja
```

# Expected Result

Everything works fine

# Actual Result

The last command produces the following error message on my machine:

```
[300/300] Creating library symlink 'Blank Space/antlr4/runtime/Cpp/dist/libantlr4-runtime.dylib'
FAILED: Blank Space/antlr4/runtime/Cpp/dist/libantlr4-runtime.dylib
/usr/local/Cellar/cmake/3.10.2/bin/cmake -E cmake_symlink_library 'Blank Space/antlr4/runtime/Cpp/dist/libantlr4-runtime.4.7.1.dylib' Blank Space/antlr4/runtime/Cpp/dist/libantlr4-runtime.4.7.1.dylib 'Blank Space/antlr4/runtime/Cpp/dist/libantlr4-runtime.dylib' && :
CMake Error: cmake version 3.10.2
Usage: /usr/local/Cellar/cmake/3.10.2/bin/cmake -E <command> [arguments...]
Available commands:
  capabilities              - Report capabilities built into cmake in JSON format
  chdir dir cmd [args...]   - run command in a given directory
  compare_files file1 file2 - check if file1 is same as file2
  copy <file>... destination  - copy files to destination (either file or directory)
  copy_directory <dir>... destination   - copy content of <dir>... directories to 'destination' directory
  copy_if_different <file>... destination  - copy files if it has changed
  echo [<string>...]        - displays arguments as text
  echo_append [<string>...] - displays arguments as text but no new line
  env [--unset=NAME]... [NAME=VALUE]... COMMAND [ARG]...
                            - run command in a modified environment
  environment               - display the current environment
  make_directory <dir>...   - create parent and <dir> directories
  md5sum <file>...          - create MD5 checksum of files
  sha1sum <file>...         - create SHA1 checksum of files
  sha224sum <file>...       - create SHA224 checksum of files
  sha256sum <file>...       - create SHA256 checksum of files
  sha384sum <file>...       - create SHA384 checksum of files
  sha512sum <file>...       - create SHA512 checksum of files
  remove [-f] <file>...     - remove the file(s), use -f to force it
  remove_directory dir      - remove a directory and its contents
  rename oldname newname    - rename a file or directory (on one volume)
  server                    - start cmake in server mode
  sleep <number>...         - sleep for given number of seconds
  tar [cxt][vf][zjJ] file.tar [file/dir1 file/dir2 ...]
                            - create or extract a tar or zip archive
  time command [args...]    - run command and return elapsed time
  touch file                - touch a file.
  touch_nocreate file       - touch a file but do not create it.
Available on UNIX only:
  create_symlink old new    - create a symbolic link new -> old

ninja: build stopped: subcommand failed.
```

# Additional Information

It looks like the second `Blank Space/antlr4/runtime/Cpp/dist/libantlr4-runtime.4.7.1.dylib` should be quoted too. The problem does not occur if I use `make` to build the project:

```sh
mkdir 'Blank Space'
cd 'Blank Space'
git clone https://github.com/antlr/antlr4.git
mkdir Build
cd Build
cmake -G'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -BUILD_TESTS=OFF ../antlr4/runtime/Cpp
make -j9
```

. The issue described above might actually be a problem in [CMake](https://cmake.org). However, since building other CMake based projects (e.g. [Elektra](http://github.com/ElektraInitiative/libelektra)) with Ninja still works on my machine, I am not so sure about that.

## System

- macOS 10.13.3
- CMake 3.10.2
- Ninja 1.8.2

# Checkbox Checking Time

- [x] I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [x] I have done a search of the existing issues to make sure I'm not sending in a duplicate

**Comment by ChaseOxide** [comment]
The other CMake project you've tested does not call CMAKE_SYMLINK_LIBRARY, which is why the build did not fail. It's a bug with the CMake's Ninja generator.

I have addressed the issue to Kitware with a [fix](https://gitlab.kitware.com/cmake/cmake/merge_requests/1759) made, you may use that version but I can't guarantee it's bug-free.

For this project, symlink is called because VERSION and SOVERSION is set with the same value, and LIBRARY_OUTPUT_DIRECTORY is set.

**Comment by sanssecours** [comment]
Thank you very much for pointing out and fixing the problem, Marcus. Hopefully Kitware integrates your patch into CMake’s code base soon.
