### ISSUE TITLE
CSharp.stg need changes for dotnet45 something like that

### ISSUE THREAD

**Issue by tnsr1** [antlr/antlr4#2220]
/\*#if (NET45PLUS && !DOTNETCORE)\*/
contextGetterCollection(elementType) ::= <\%
IReadOnlyList\\\<\<elementType\>\>
%>
/\*#else
contextGetterCollection(elementType) ::= <\%
\<elementType\>[]
\%>
#endif\*/

**Comment by tnsr1** [comment]
Hi, Sam.
You're wrong.
See [https://github.com/antlr/antlr4/blob/master/runtime/CSharp/runtime/CSharp/Antlr4.Runtime/ParserRuleContext.cs](url)
`#if (NET45PLUS && !DOTNETCORE)
        public virtual IReadOnlyList<ITerminalNode> GetTokens(int ttype)
#else
        public virtual ITerminalNode[] GetTokens(int ttype)
#endif`

WBR, Alexey

**Comment by sharwell** [comment]
Cool, thanks for clarifying :)

**Comment by ericvergnaud** [comment]
Hi,
Can you provide a grammar where this template fragment causes an issue?
Eric

Envoyé de mon iPhone

**Comment by ericvergnaud** [comment]
Hi,
I’m happy to help but please provide an example.
Eric

**Comment by tnsr1** [comment]
For example
[https://github.com/antlr/grammars-v4/tree/master/tsql](url)

**Comment by tnsr1** [comment]
No,
I can't repeat error.
))

**Comment by tnsr1** [comment]
Got Error In MyTestGrammarParser.cs
`...
		public PostfixExpressionContext[] postfixExpression() {
			return GetRuleContexts<PostfixExpressionContext>();
		}
...`
`...
		public AdditiveLiteralExpressionContext[] additiveLiteralExpression() {
			return GetRuleContexts<AdditiveLiteralExpressionContext>();
		}
...`
`...
		public ITerminalNode[] LITERAL() { return GetTokens(HarbourParser.LITERAL); }
...`
`...
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
...`
`...
		public ArgumentContext[] argument() {
			return GetRuleContexts<ArgumentContext>();
		}
...`
My test grammar
`
grammar MyTestGrammar;

options
{
	language = CSharp;
}
/*
channels 
{ INCLUDE }
*/

fileProgram: statements? EOF;

primaryExpression
           : line
           | numValue
           | nilValue
           | dateValue
           | timeStampValue
           | literalValue
           | codeBlock
           | logical
           | selfValue
           | hash
           ;

postfixExpression
    :   primaryExpression
    |   postfixExpression '[' postfixExpression ']'
    |   funCall
    |   aliasExpr
    |   postfixExpression '++'
    |   postfixExpression '--'
//    |   objectMethod
//    |   objectData
    |   identName
    ;

paramList  : assignmentExpression asType 
           | paramList ',' postfixExpression asType
           ;

params     : paramList ',' EPSILON
           | paramList
           | EPSILON 
           ;

exprUnary   
            :   postfixExpression
            |   '++' exprUnary
            |   '--' exprUnary
            |   NOT expression 
            |   unaryOperator multiplicativeExpression
            |   macroAny
            |   ifInline
            ;

exprPOWER   : exprUnary
            | exprPOWER POWER exprUnary
            ;

multiplicativeExpression
    :   exprPOWER
    |   multiplicativeExpression '*' exprPOWER
    |   multiplicativeExpression '/' exprPOWER
    |   multiplicativeExpression '%' exprPOWER
    ;

additiveExpression
    :   multiplicativeExpression
    |   additiveExpression '+' multiplicativeExpression
    |   additiveExpression '-' multiplicativeExpression
    ;

primaryLiteralExpression
           : nilValue
           | dateValue
           | timeStampValue
           | literalValue
           | codeBlock
           | hash
           | postfixExpression '[' postfixExpression ']'
           | funCall
           | aliasExpr
//    |   objectMethod
//    |   objectData
           | identName
           | macroAny
           | ifInline
    ;

additiveLiteralExpression
    :   primaryLiteralExpression
    |   additiveLiteralExpression '+' primaryLiteralExpression
//    |   ('(' additiveExpression ')' | additiveExpression) '-' ('(' multiplicativeExpression ')' | multiplicativeExpression)
    ;

primaryBoolExpression
           : nilValue
           | logical
           | codeBlock
           | postfixExpression '[' postfixExpression ']'
           | funCall
           | aliasExpr
//    |   objectMethod
//    |   objectData
           | identName
           | hash
           ;
exprBool
    :   primaryBoolExpression
    |   additiveLiteralExpression INOP additiveLiteralExpression
    |   additiveExpression (LT | GT | LE | GE | (EQ | Equal) | (NE1 | NE2)) additiveExpression
    ;

logicalAndExpression
    : exprBool
    | logicalAndExpression AND exprBool
    ;

logicalOrExpression
    : logicalAndExpression
    | logicalOrExpression OR logicalAndExpression
    ;
/*
exprOperEq
    :   logicalOrExpression//exprBool
    ;
*/

extExprBool   
    : '('logicalOrExpression')'
    | logicalOrExpression
    ;

assignmenRightExpression
    : ('(' additiveExpression ')' | additiveExpression)
    | ('(' additiveLiteralExpression ')' | additiveLiteralExpression)
    | extExprBool
//    | ('(' assignmentExpression ')' | assignmentExpression)
    ;

assignmentExpression
    :   exprUnary assignment_operator assignmenRightExpression
    |   exprUnary assignment_operator ('(' assignmentExpression ')' | assignmentExpression)
    ;

expression
    :   assignmentExpression
    |   expression ',' assignmentExpression
    ;

extExpression : ('(' expression ')' | expression)
              | EPSILON  
              ;

emptyExpression : expression? ;

argument    : expression 
            | refArgument
            ;

extArgument : argument
            | EPSILON  
            ;

argList     : extArgument
            | argList ',' extArgument
            ;

refArgument : '@' identName    
            | '@' macroVar     
            | '@' aliasVar     
            | '@' objectData   
            | '@' variableAt   
            ;

expList     : expression
            | expList ',' expression
            ;

pareExpList : '(' expList ')'
            ;

macroExpr : '&' pareExpList
          ;

macroVar : '&' variable
//         | MACROTEXT
         ;

macroAny : macroVar
         | macroExpr
         ;

function   : funScope FUNCTION  identName '(' params? ')'
           | funScope PROCEDURE identName '(' params? ')'
           ;

asType     : strongType?
           ;

asArrayType: asArray?
           ;

strongType : /*AS_NUMERIC                    { $$ = hb_compVarTypeNew( HB_COMP_PARAM, 'N', NULL ); }
           | AS_CHARACTER                  { $$ = hb_compVarTypeNew( HB_COMP_PARAM, 'C', NULL ); }
           | AS_DATE                       { $$ = hb_compVarTypeNew( HB_COMP_PARAM, 'D', NULL ); }
           | AS_LOGICAL                    { $$ = hb_compVarTypeNew( HB_COMP_PARAM, 'L', NULL ); }
           | AS_BLOCK                      { $$ = hb_compVarTypeNew( HB_COMP_PARAM, 'B', NULL ); }
           | AS_OBJECT                     { $$ = hb_compVarTypeNew( HB_COMP_PARAM, 'O', NULL ); }
           | AS_CLASS identName            { $$ = hb_compVarTypeNew( HB_COMP_PARAM, 'S', $2 );   }
           | AS_VARIANT                    { $$ = hb_compVarTypeNew( HB_COMP_PARAM, ' ', NULL ); }
           | AsArray*/
           ;

asArray    : /*AS_ARRAY                      { $$ = hb_compVarTypeNew( HB_COMP_PARAM, 'A', NULL ); }
           | AS_NUMERIC_ARRAY              { $$ = hb_compVarTypeNew( HB_COMP_PARAM, 'n', NULL ); }
           | AS_CHARACTER_ARRAY            { $$ = hb_compVarTypeNew( HB_COMP_PARAM, 'c', NULL ); }
           | AS_DATE_ARRAY                 { $$ = hb_compVarTypeNew( HB_COMP_PARAM, 'd', NULL ); }
           | AS_LOGICAL_ARRAY              { $$ = hb_compVarTypeNew( HB_COMP_PARAM, 'l', NULL ); }
           | AS_ARRAY_ARRAY                { $$ = hb_compVarTypeNew( HB_COMP_PARAM, 'a', NULL ); }
           | AS_BLOCK_ARRAY                { $$ = hb_compVarTypeNew( HB_COMP_PARAM, 'b', NULL ); }
           | AS_OBJECT_ARRAY               { $$ = hb_compVarTypeNew( HB_COMP_PARAM, 'o', NULL ); }
           | AS_CLASS_ARRAY identName      { $$ = hb_compVarTypeNew( HB_COMP_PARAM, 's', $2 );   }
           */;

line       
           : DefLine NUM_LONG LITERAL '@' LITERAL   // Xbase++ style
           | DefLine NUM_LONG LITERAL?
           ;

statamentExpression
           : exprUnary assignment_operator '(' expression ')'
           | exprUnary assignment_operator expression
           ;

statement  
           : line
           | function
           | EXTERN extList
           | DYNAMIC dynList
           | ANNOUNCE identName 
           | PUBLIC extVarList
           | PRIVATE extVarList
           | execFlow
           | ifInline
           | funCall
//           | aliasExpr
//           | objectMethod
           | macroAny
           | doProc
           | BREAK expression?
           | EXIT
           | LOOP
           | RETURN expression?
           | varDefs
           | fieldsDef
           | memvarDef
           | PROCREQ compTimeStr ')'
           | statamentExpression
           ;

lineStat   
           : line
           | statement
           | declaration
           ;

statements : lineStat
           | statements lineStat
           ;

extList    : identName                 
           | extList ',' identName     
           ;

dynList    : identName                 
           | dynList ',' identName     
           ;

codeBlockAlias : codeBlock ALIASOP
               ;

array    : '{' elemList '}'
         ;

arrayAlias  : array ALIASOP
            ;

arrayAt     : array arrayIndex
            ;

arrayAtAlias : arrayAt ALIASOP
             ;

hash     : '{' HASHOP '}'
         | '{' hashList '}'
         ;

hashAlias: hash ALIASOP
         ;

hashList : expression HASHOP expression?
         | hashList ',' expression HASHOP expression?
         ;

variable : identName
         ;

varAlias : identName ALIASOP
         ;

macroVarAlias  : macroVar ALIASOP
               ;

macroExprAlias : macroExpr ALIASOP
               ;

/* ignore _FIELD-> or FIELD-> if a real alias is specified
 */
fieldVarAlias  : fieldAlias varAlias            
               | fieldAlias numAlias            
               | fieldAlias pareExpListAlias    
               | fieldAlias macroVarAlias       
               | fieldAlias macroExprAlias      
               | fieldAlias nilAlias            
               | fieldAlias literalAlias        
               | fieldAlias logicalAlias        
               | fieldAlias codeBlockAlias      
               | fieldAlias selfAlias           
               | fieldAlias arrayAlias          
               | fieldAlias arrayAtAlias        
               | fieldAlias hashAlias           
               | fieldAlias ifInlineAlias       
               ;

aliasId     : identName       
            | macroAny
            ;

aliasVar   : numAlias aliasId          
           | macroVarAlias aliasId     
           | macroExprAlias aliasId    
           | pareExpListAlias aliasId  
           | nilAlias aliasId          
           | literalAlias aliasId      
           | logicalAlias aliasId      
           | codeBlockAlias aliasId    
           | hashAlias aliasId        
           | selfAlias aliasId         
           | arrayAlias aliasId        
           | arrayAtAlias aliasId      
           | variableAtAlias aliasId   
           | ifInlineAlias aliasId     
           | funCallAlias aliasId      
           | objectDataAlias aliasId   
           | objectMethodAlias aliasId 
           | varAlias aliasId          
           | fieldAlias aliasId        
           | fieldVarAlias aliasId     
           ;

/* Aliased expressions
 */
/* NOTE: In the case:
 * alias->( Expression )
 * alias always selects a workarea at runtime
 */
aliasExpr  : numAlias pareExpList        
           | varAlias pareExpList        
           | macroVarAlias pareExpList   
           | macroExprAlias pareExpList  
           | pareExpListAlias pareExpList
           | fieldAlias pareExpList      
           ;

/* Array expressions access
 */

variableAt  : numValue        arrayIndex  
            | nilValue        arrayIndex  
            | dateValue       arrayIndex  
            | timeStampValue  arrayIndex  
            | literalValue    arrayIndex  
            | codeBlock       arrayIndex  
            | logical         arrayIndex  
            | hash            arrayIndex  
            | selfValue       arrayIndex  
            | variable        arrayIndex  
//            | aliasVar        arrayIndex  
            | aliasExpr       arrayIndex  
            | macroAny        arrayIndex  
            | objectData      arrayIndex  
            | objectMethod    arrayIndex  
            | funCall         arrayIndex  
            | ifInline        arrayIndex  
            | pareExpList     arrayIndex  
            ;


variableAtAlias : variableAt ALIASOP
                ;
/* function call
 */
funRef      : '@' funCall    
funRef      | '@' funIdentCall
            ;

funCall     : funIdentCall
            | macroAny  '(' argList? ')'
            ;

funIdentCall: identName '(' argList? ')'
            ;

funCallAlias : funCall ALIASOP
             ;

/* Object's method
 */
objectMethod : objectData '(' argList? ')'
             ;

objectMethodAlias : objectMethod ALIASOP
                  ;

/* Object's instance variable
 */

objectData  : expression ':' sendId
            | objectRef ':' sendId
            | ':' sendId
            ;

sendId      : identName
            | macroAny
            ;

objectRef   : '(' '@' identName ')'      
            ;

objectDataAlias : objectData ALIASOP
                ;

/* NOTE: We have to distinguish identName here because it is repeated
 * in DoArgument (a part of DO <proc> WITH .. statement)
 * where it generates different action.
 */

doArgs     : /* empty */
           | WITH doArgList   
           ;

doArgList  : ','                       
           | ',' doArgument            
           | doArgument                
           | doArgList ','             
           | doArgList ',' doArgument  
           ;

doArgument : identName        
           | refArgument
           | funRef
//           | expression //simpleExpression
           | pareExpList
           ;

lValue      : identName       
            | aliasVar
            | macroVar
            | macroExpr
            | objectData
            | variableAt
            | pareExpList
            ;

/* NOTE: The rule: Expression Operator Expression
 * that can be used standalone as a statement have to be written
 * using all possible left values to resolve shift/reduce conflicts
 */
/* NOTE: PostOp can be used in one context only - it uses $0 rule
 *    (the rule that stands before PostOp)
 */

pareExpListAlias : pareExpList ALIASOP
                 ;

arrayIndex : indexList ']'
           ;

/* NOTE: $0 represents the expression before ArrayIndex
 *    Don't use ArrayIndex in other context than as an array index!
 */
indexList  : '[' extExpression
           | indexList ',' extExpression
           | indexList ']' '[' extExpression
           ;

elemList   : extArgument
           | elemList ',' extArgument
           ;

blockHead   : CBSTART
              blockVars '|'
            ;

/* NOTE: This uses $0 then don't use BlockVars, BlockVarList and BlockExpList in other context
 */
blockVars  : /* empty list */          
           | EPSILON                   
           | blockVarList              
           | blockVarList ',' EPSILON  
           ;

blockVarList : identName asType        
             | blockVarList ',' identName asType   
             ;

blockExpList : expression                    
             | blockExpList ',' expression   
             ;

codeBlock   : blockHead
              blockExpList
              '}'
            | blockHead 
            statements?
            '}'
            ;

/* NOTE: Clipper allows to pass variable by reference only as
 * function arguments, IIF() 2-nd and 3-rd arguments and as
 * explicit array items {...@var...}
 * AFAIK these are also the only one places where empty expressions in
 * the parenthesis expressions list are accepted
 */
ifInlineAlias : ifInline ALIASOP
              ;

ifInline : IIF '(' extExprBool ',' argument ',' argument ')';

varDef     : identName asType
             INASSIGN (funCall | assignmenRightExpression)
           | identName dimList asArrayType
           | identName asType 
           ;

/* NOTE: DimList and DimIndex is the same as ArrayIndex and IndexList
 *       however we are using quite different actions here
 */

varDefs  : LOCAL
           varList
         | STATIC 
           varList
         | THREAD STATIC 
           varList 
         | PARAMETERS 
           memvarList 
         ;

varList  : varDef                         
         | varList ',' varDef             
         ;

extVarDef  
           : macroVar asType INASSIGN expression
           | macroVar dimList asArrayType
           | macroVar asType
           | varDef
           ;

extVarList  : extVarDef                   
            | extVarList ',' extVarDef    
            ;

/* NOTE: if STATIC or LOCAL variables are declared and initialized then we can
 * assign a value immediately - however for PRIVATE and PUBLIC variables
 * initialization have to be delayed because we have to create these variables
 * first.
 */
dimList    : dimIndex ']'
           ;

dimIndex   : '[' expression
           | dimIndex ',' expression
           | dimIndex ']' '[' expression
           ;

fieldsDef  : FIELD 
             fieldList inAlias 
           ;

fieldList  : identName asType  
           | fieldList ',' identName asType  
           ;

memvarList : identName asType
           | memvarList ',' identName asType
           ;

memvarDef  : MEMVAR 
             memvarList 
           ;

decData    : identName asType
           ;

decDataList: decData
           | decDataList ',' decData
           ;

formalList : identName asType
           | '@' identName asType                              
           | '@' identName '(' dummyArgList ')'                
           | formalList ',' identName asType                   
           | formalList ',' '@' identName asType               
           | formalList ',' '@' identName '(' dummyArgList ')' 
           ;

optList    : OPTIONAL identName asType                               
           | OPTIONAL '@' identName asType                           
           | OPTIONAL '@' identName '(' dummyArgList ')'             
           | optList ',' OPTIONAL identName asType                   
           | optList ',' OPTIONAL '@' identName asType               
           | optList ',' OPTIONAL '@' identName '(' dummyArgList ')' 
           ;

decListExt : /* Nothing */
           | formalList
           | optList
           | EPSILON
           | formalList ',' EPSILON
           | formalList ',' optList
           | formalList ',' optList ',' EPSILON
           ;

decMethod  : identName '(' decListExt ')' asType
           ;

classInfo  : decMethod
           | classInfo decMethod
           | decData
           | classInfo decData
           ;

decList    : /* Nothing */
           | formalList
           | optList
           | formalList ',' optList
           ;

declaration
           : DECLARE identName '(' decList ')' asType
           | DECLARE identName classInfo 
           | DECLARE_CLASS identName 
           | DECLARE_CLASS identName identName 
           | DECLARE_MEMBER decMethod 
           | DECLARE_MEMBER '{' asType decDataList '}' 
           ;

dummyArgList : dummyArgument
             | dummyArgList ',' dummyArgument
             ;

dummyArgument : expression?
              ;

execFlow   : ifEndif
           | doCase
           | doWhile
           | forNext
           | beginSeq
           | forEach
           | doSwitch
           | withObject
           ;

ifEndif    : ifBegin ifElseIf ifElse endIf    
           | ifBegin ifElseIf endIf           
           | ifBegin ifElse endIf             
           | ifBegin endIf                    
           ;

ifBegin    : IF ('('logicalOrExpression')' | logicalOrExpression)
             statements?
           ;

ifElse     : ELSE 
             statements?
           ;

ifElseIf   : ELSEIF
             extExprBool 
             statements?
           | ifElseIf ELSEIF 
             extExprBool
             statements
           ;

doCase     
           : doCaseBegin cases? otherwise? endCase                
//           | doCaseBegin cases endCase                
//           | doCaseBegin otherwise endCase
//           | doCaseBegin endCase
           ;

doCaseStart : DOCASE 
            ;

doCaseBegin : doCaseStart
//            | doCaseStart statements?
           ;

cases      : CASE expList 
             statements?
           | cases CASE expList
             statements?
           ;

otherwise  : OTHERWISE
             statements?
//           | otherwise OTHERWISE 
//             statements?
           ;

doWhile    : whileBegin expList 
             statements?
             endWhile
           ;

forNext    : FOR lValue forAssign expression          /* 1  2  3  4 */
             TO expList stepExpr                      /* 6  7  8 */
             forstatements                            /* 12 */
           ;

forAssign  : '='
           | INASSIGN
           ;

stepExpr   : /* default step expression */       
           | STEP expList                        
           ;

forstatements : 
                  statements?
                  endForID
              ;

endForID   : NEXT identName?
           | END identName?
           ;

forVar     : identName     
           | aliasVar      
           ;

forList    : forVar              
           | forList ',' forVar  
           ;

forExpr    : '@' identName       
           | expression
           ;

forArgs    : forExpr             
           | forArgs ',' forExpr 
           ;


forEach    : FOREACH forList IN forArgs          /* 1  2  3  4 */
             descend    /* 6 */
             forstatements                            /* 10 */
           ;

doSwitch    : switchBegin
               switchCases
               endSwitch
            | switchBegin
              endSwitch
            ;

endSwitch   : endSwitchID
            ;

endSwitchID : ENDSWITCH
            | END
            ;

switchStart : DOSWITCH
              expression
            ;

switchBegin : switchStart
            | switchStart statements
            ;

switchCases : CASE expression
              statements?
            | switchCases CASE expression 
              statements?
            | switchDefault
            | switchCases switchDefault
            ;

switchDefault : OTHERWISE 
                statements?
              ;

beginSeq    : BEGINSEQ        /* 1 */
               blockSeq       /* 3 */
               statements?
               recoverSeq     /* 7 */
               alwaysSeq      /* 9 */
               endSeqID       /* 10 */
            ;

endSeqID    : ENDSEQ
            | END
            ;

blockSeq    : /* no always */    
            | WITH expression
            ;

alwaysSeq   : /* no always */    
            | always 
            statements?
            ;

recoverSeq  : /* no recover */   
            | recoverEmpty  
            statements?
            | recoverUsing 
            statements?
            ;

recoverEmpty : RECOVER
             ;

recoverUsing : RECOVERUSING identName
             ;

/* NOTE: In Clipper all variables used in DO .. WITH are passed by reference
 * however if they are part of an expression then they are passed by value
 * for example:
 * DO .. WITH ++variable
 * will pass the value of variable not a reference
 */

doProc     : DO macroAny doArgs
           | DOIDENT doArgs
           ;

withObject : WITHOBJECT expression
             statements?
             endWithID
           ;

comparison_operator
    : '==' | '>' | '<' | '<' '=' | '>' '=' | '<' '>' | '!' '=' | '$' | '='
    ;

assignment_operator
    : ':=' | '+=' | '-=' | '*=' | '/=' | '%=' | '^='
    ;

funScope   :                  
           | STATIC           
           | INIT             
           | EXIT             
           ;

funScopeId :
           | STATIC
           | INIT
           | EXIT
           ;

endWithID  : ENDWITH
           | END
           ;

compTimeStr : LITERAL 
            | LITERAL '+' LITERAL 
           ;

/* SELF value and expressions
 */

selfValue : SELF              
          ;

selfAlias  : selfValue ALIASOP
           ;

/* special case: _FIELD-> and FIELD-> can be nested
 */
fieldAlias  : FIELD ALIASOP   
            | FIELD ALIASOP fieldAlias    
            ;

inAlias    : /* no alias */   //{ $$ = NULL; }
           | IN identName     
           ;

descend    : DESCEND?
           ;

endIf      : endIfID
           ;

endIfID    : ENDIF
           | END
           ;

endCase    : endCaseID
           ;

endCaseID  : ENDCASE
           | END
           ;

literalAlias : literalValue ALIASOP
             ;

whileBegin : WHILE
           ;

endWhile   : endWhileID
           ;

endWhileID : ENDDO
           | END
           ;

always      : ALWAYS
            ;

logicalAlias : logical ALIASOP
             ;

logical  : TRUEVALUE          
         | FALSEVALUE         
         ;

identName  : ID;
/*           | STEP             //{ $$ = "STEP"; }
           | TO               //{ $$ = "TO"; }
           | LOOP             //{ $$ = "LOOP"; }
           | EXIT             //{ $$ = "EXIT"; }
           | IN               //{ $$ = "IN"; }
           | OPTIONAL         //{ $$ = $<string>1; }
           | EXTERN           //{ $$ = $<string>1; }
           | DYNAMIC          //{ $$ = $<string>1; }
           | ANNOUNCE         //{ $$ = $<string>1; }
           | LOCAL            //{ $$ = $<string>1; }
           | MEMVAR           //{ $$ = $<string>1; }
           | STATIC           //{ $$ = $<string>1; }
           | PRIVATE          //{ $$ = $<string>1; }
           | PUBLIC           //{ $$ = $<string>1; }
           | PARAMETERS       //{ $$ = $<string>1; }
           | PROCREQ          //{ $$ = $<string>1; }
           | DESCEND          //{ $$ = $<string>1; }
           | THREAD           //{ $$ = $<string>1; }
           ;
*/
/* Numeric values
 */
numValue   : NUM_DOUBLE       
           | NUM_LONG         
           ;

timeStampValue: TimeStampValue;

numAlias   : NUM_LONG    ALIASOP    
           | NUM_DOUBLE  ALIASOP    
           ;

/* NIL value
 */
nilAlias   : nilValue ALIASOP
           ;

nilValue   : NIL                    
           ;

/* Literal string value
 */
literalValue : LITERAL
             | LITERALe
             ;
unaryOperator
    :   '+' | '-'
    ;

postOp      : INC    
            | DEC    
            ;

dateValue  : '"' NUM_DATE '"';

//Lexer
DOIDENT:                               DO ID;

FOREACH:                               FOR EACH;
DOCASE:                                DO CASE;
WITHOBJECT:                            WITH OBJECT;
RECOVERUSING:                          RECOVER USING;

ANYTYPE:                               A N Y T (Y (P E?)?)?;
AS_ARRAY:                              A R R A Y?;
AS_BLOCK:                              B L O C K? | C O D E (B L O C K)?;
AS_CHARACTER:                          C H A R A C T E R | S T R I N G;
AS_CLASS:                              C L A S S;
AS_DATE:                               D A T E;
AS_DATETIME:                           D A T E T I M E | T I M E S T A M P;
AS_HASH:                               H A S H;
AS_LOGICAL:                            L O G I C A L;
//AS_OBJECT:                             OBJECT;
AS_POINTER:                            P O I N T E R;
AS_SYMBOL:                             S Y M B O L;
AS_VARIANT:                            U S U A L;


// Basic keywords

ALWAYS:                                A L W A (Y S?)?;
ANNOUNCE:                              A N N O (U (N (C E?)?)?)?;
AS:                                    A S;
BEGINSEQ:                              B E G I N?;
BREAK:                                 B R E A K;
CASE:                                  C A S E;
DECLARE:                               D E C L A R E;
DESCEND:                               D E S C E N D;
DO:                                    D O;
DYNAMIC:                               D Y N A M I C;
ELSE:                                  E L S E;
ELSEIF:                                E L S E I F;
END:                                   E N D;
ENDCASE:                               E N D C A S E;
ENDDO:                                 E N D D O;
ENDIF:                                 E N D I F;
ENDSEQ:                                E N D S E Q (U E N C E)?;
ENDSWITCH:                             E N D S W I T C H;
ENDWITH:                               E N D W I T H;
EXIT:                                  E X I T;
EXTERN:                                E X T E (R (N (A L?)?)?)?;
FIELD:                                 '_'? F I E L D;
FOR:                                   F O R;
FUNCTION:                              F U N C T I O N;
IF:                                    I F;
IIF:                                   I I F;
IN:                                    I N;
INIT:                                  I N I T;
LOCAL:                                 L O C A L;
LOOP:                                  L O O P;
MEMVAR:                                M E M V A R;
NEXT:                                  N E X T;
NIL:                                   N I L;
OPTIONAL:                              O P T I O N A L;
OTHERWISE:                             O T H E R W I S E;
PARAMETERS:                            P A R A M E T E R S;
PRIVATE:                               P R I V A T E;
PROCEDURE:                             P R O C E D U R E;
PUBLIC:                                P U B L I C;
QSELF:                                 Q S E L F;
RECOVER:                               R E C O V E R;
RETURN:                                R E T U R N;
STATIC:                                S T A T I C;
STEP:                                  S T E P;
DOSWITCH:                              S W I T (C H?)?;
THREAD:                                T H R E A D;
TO:                                    T O;
WHILE:                                 W H I L E;
WITH:                                  W I T H;
PROCREQ:                               '_' P R O C R E Q '_';
DECLARE_CLASS:                         '_' H B '_' C L A S S;
DECLARE_MEMBER:                        '_' H B '_' M E M B E R;
 
// Additional keywords
        
OBJECT:                                O B J E C T;
EACH:                                  E A C H;
USING:                                 U S I N G;

SELF:                                  S E L F;

MACROVAR:                              M A C R O V A R;
//MACROTEXT:                             M A C R O T E X T;//?



ID:                  ( [a-zA-Z_] | FullWidthLetter) ( [a-zA-Z_#$@0-9] | FullWidthLetter )*;

LITERAL:              '"' (SChar1 | '""')* '"'
       |              '\'' (SChar2 | '\'\'')* '\''
       ;

LITERALe:             'e"' (SChar1 | '\\"')* '"';

fragment
SChar1
    :   ~["];

fragment
SChar2
    :   ~['];
/*
fragment
    LineKW:                                '#' L I N E;
*/

LEFT_PB : '(';//LeftParen
RIGHT_PB : ')';//RightParen
LEFT_SB : '[';//LeftBracket
RIGHT_SB : ']';//RightBracket
LEFT_CB : '{';//LeftBrace
RIGHT_CB : '}';//RightBrace

LT : '<';
LE : '<=';
GT : '>';
GE : '>=';
//LeftShift : '<<';
//RightShift : '>>';

Plus : '+';
INC : '++';
Minus : '-';
DEC : '--';
Star : '*';
Div : '/';
Mod : '%';

Ampersand : '&';
Pipe : '|';
AndAnd : '&&';
OrOr : '||';
POWER : '^' | '**';
NOT : NotSymbol | '.NOT.';
//Tilde : '~';
AND : '.AND.';
OR : '.OR.';
TRUEVALUE: '.T.' | '.Y.';
FALSEVALUE: '.F.' | '.N.';

Question : '?';
Colon : ':';
Comma : ',';

INASSIGN : ':=';
// '*=' | '/=' | '%=' | '+=' | '-=' | '<<=' | '>>=' | '&=' | '^=' | '|='
MULTEQ : '*=';
DIVEQ : '/=';
MODEQ : '%=';
PLUSEQ : '+=';
MINUSEQ : '-=';
//LeftShiftAssign : '<<=';
//RightShiftAssign : '>>=';
//AndAssign : '&=';
EXPEQ : '^=';
//OrAssign : '|=';

EQ : '==';
Equal : '=';
NE1 : '!=';
NE2 : '<>';

ALIASOP : '->';
HASHOP  : '=>';

INOP : '$';

DefLine: SHARP L I N E;

fragment SHARP: '#';

Dot : '.';
EPSILON : '...'; 

At:'@';

Tilde:'~';
NotSymbol:'!';

PragmaDirective
    :   '#pragma' ~[\r\n]*
        -> skip
    ;

InclideDirective
    :   '#include' ~[\r\n]*
        -> channel(HIDDEN)
    ;

SemiCrLf
    : ';'
        -> skip
    ;
	
Whitespace
    :   [ \t]+
        -> skip
    ;

Newline
    :   (   '\r' '\n'?
        |   '\n'
        )
        -> skip
    ;

BlockComment
    :   '/*' .*? '*/'
        -> skip
    ;

LineComment
    :   '//' ~[\r\n]*
        -> skip
    ;

CBSTART: '{|';

TimeStampValue:'"' NUM_Year DateDelim NUM_DayMonth DateDelim NUM_DayMonth (NUM_DayMonth ':' NUM_DayMonth DEC_DOT_DEC?)?'"';

NUM_DATE: NUM_Year DateDelim NUM_DayMonth DateDelim NUM_DayMonth
        | NUM_DayMonth DateDelim NUM_DayMonth DateDelim NUM_Year
        ;
DateDelim:	'/'|'.'|'-'|':';

fragment
NUM_DayMonth:DEC_DIGIT DEC_DIGIT?;

fragment
NUM_Year:DEC_DIGIT DEC_DIGIT?
        |DEC_DIGIT DEC_DIGIT DEC_DIGIT DEC_DIGIT;

NUM_DOUBLE
    :   DEC_DOT_DEC
    ;

NUM_LONG
    :   DEC_DIGIT+
    ;

fragment DEC_DIGIT:    [0-9];
fragment DEC_DOT_DEC:  (DEC_DIGIT+ '.' DEC_DIGIT+ |  DEC_DIGIT+ '.' | '.' DEC_DIGIT+);
//fragment HEX_DIGIT:    [0-9A-Fa-f];

fragment LETTER:       [a-zA-Z_];

fragment A: [aA];
fragment B: [bB];
fragment C: [cC];
fragment D: [dD];
fragment E: [eE];
fragment F: [fF];
fragment G: [gG];
fragment H: [hH];
fragment I: [iI];
fragment J: [jJ];
fragment K: [kK];
fragment L: [lL];
fragment M: [mM];
fragment N: [nN];
fragment O: [oO];
fragment P: [pP];
fragment Q: [qQ];
fragment R: [rR];
fragment S: [sS];
fragment T: [tT];
fragment U: [uU];
fragment V: [vV];
fragment W: [wW];
fragment X: [xX];
fragment Y: [yY];
fragment Z: [zZ];
fragment FullWidthLetter
    : '\u00c0'..'\u00d6' 
    | '\u00d8'..'\u00f6' 
    | '\u00f8'..'\u00ff' 
    | '\u0100'..'\u1fff' 
    | '\u2c00'..'\u2fff' 
    | '\u3040'..'\u318f' 
    | '\u3300'..'\u337f' 
    | '\u3400'..'\u3fff' 
    | '\u4e00'..'\u9fff' 
    | '\ua000'..'\ud7ff' 
    | '\uf900'..'\ufaff' 
    | '\uff00'..'\ufff0'
    // | '\u10000'..'\u1F9FF'  //not support four bytes chars
    // | '\u20000'..'\u2FA1F'
    ;
/*
	#define    RULE( p )    ? "define value", p
	#translate RULE(<p>) => ? "translate value", <p>
	#command   RULE(<p>) => ? "command value", <p>

	#define    DEF( p )     RULE( p )
	#translate TRS(<p>)  => RULE(<p>)
	#command   CMD(<p>)  => RULE(<p>)

#if
#elde
#endif
*/

`

**Comment by ericvergnaud** [comment]
Alexei,

a few comments:
 - after fixing a few minor issues in your grammar, I was able to generate an error free parser i.e. it compiles
 - not sure how you generate your parser, but there is no reference to NET45PLUS in CSharp.stg . 
 - looks like you are trying to build the runtime instead of using it. You should download it from nuget: https://www.nuget.org/packages/Antlr4.Runtime.Standard.
 - there is room for improvement in your grammar:
	- mixing explicit and implicit tokens is not supported. You should separate lexer and grammar in 2 grammar files
	- do not use empty options such as doArgs : /* empty */ | WITH doArgList; instead use doArgs?
	- unless necessary for parsing, do not include production code such as $$ = hb_compVarTypeNew( HB_COMP_PARAM, 'c', NULL ); instead walk the parse tree after parsing
 - if you need support, please use the google discussion group

Eric

**Comment by tnsr1** [comment]
Hi, Eric.
I'm newer in Antlr.
I thought Csharp.Antlr.v4.Runtime(https://github.com/antlr/antlr4/blob/master/runtime/CSharp/runtime/CSharp/Antlr4.vs2013.sln) is actual.
But it use dotnet35. I compiled it  with dotnet45 and got error. I found problem and wanted to correct it by this issue.
Thx for your comments.
I will look at Sam's Harwell project also.

Good luck.

**Comment by ericvergnaud** [comment]
The above link is actual.
It compiles to 3.5, the generated assembly can be used in 4.5
Please close this issue
