### ISSUE TITLE
Praser throws error in IE 11

### ISSUE THREAD

**Issue by spabbineedi** [antlr/antlr4#2228]
ANTLR 4 generated parser (JavaScript target) throwing an error in IE 11 if it is minified with UglifyJsPlugin in webpack.

If I remove UglifyJsPlugin plugin, its works as expected.. I was wondering what could be the issue.

The parser is failing at checkUUID() method>
`(G.indexOf(t)<0)
{
throw"Could not deserialize ATN with UUID: "+t+" (expected "+J+" or a legacy UUID).",t,J
}`

any suggestions?

**Comment by ericvergnaud** [comment]
Does it work in other browsers ?
« +t+ » is definitely not a UUID so you might need to exclude the serialized ATN from uglification

Envoyé de mon iPhone

**Comment by spabbineedi** [comment]
Uglified code is working inother browsers.. it even working in IE Edge

**Comment by spabbineedi** [comment]
`G.prototype.checkUUID = function () {
       
 var t = this.readUUID();
        if (X.indexOf(t) < 0) throw "59627784-3BE5-417A-B9EB-8131A7286089";
        this.uuid = t
    }`

![image](https://user-images.githubusercontent.com/30253451/36540720-6cb40a20-17a9-11e8-843e-813494e30e6d.png)

**Comment by ericvergnaud** [comment]
you might want to try throwing an error instead of a string in the source code and see if to improves

**Comment by spabbineedi** [comment]
Found the fix: 

new UglifyJsPlugin({
      uglifyOptions: {
        output: {
          ascii_only: true
        }
      }
    }),

**Comment by alexey-sh** [comment]
`<meta charset="utf-8">` also fix the issue
