### ISSUE TITLE
offendingToken on recursive rule. o

### ISSUE THREAD

**Issue by amodlagu** [antlr/antlr4#2236]
Target language: JavaScript

Simplified Grammar:

numberRule:
 NUMBER
| NUMBER '*' NUMBER
;

NUMBER
: [0..9]+;

numberExpr : numberRule EOF;

expression to parse, 5 *

getSynValidOrSemInvalidAltThatFinishedDecisionEntryRule

finds a NoViableAltException, but then does something wonderful to determine that my multiplication operator is the offending token instead of considering an alternative that there is a possibility of another NUMBER following, '*'.

Formula Parser calls adaptivePredict after the first number, but the alt returned is '2' that prevents it from entering the loop that has further Case statements to handle the binary operators.

**Comment by ericvergnaud** [comment]
Hi
Please close this and look for support on the google discussion group
Eric

Envoyé de mon iPhone
