### ISSUE TITLE
antlr4, python 3, Parser, ParseTreePatternMatcher, compile

### ISSUE THREAD

**Issue by jpicau** [antlr/antlr4#2237]
Dear ANTLR team,

I used `conda` to install the `antlr-python-runtime 4.7.1` package.
I compiled the Lua grammar as such:
`antlr4 -o lua -Dlanguage=Python3 -visitor Lua.g4`

I'm parsing the `factorial.lua` example and would like to use the tree pattern matching capabilities.
The first steps were as the described in many simple examples:

```
from antlr4 import *
from lua import *

def main():
    input = FileStream("factorial.lua")         # antlr4
    lexer = LuaLexer(input)
    stream = CommonTokenStream(lexer)           # antlr4
    parser = LuaParser(stream)
    tree = parser.chunk()
```

However, the next line:

```
    p = parser.compileParseTreePattern("<ID>", LuaParser.RULE_exp)
```

gives me the following error:

```
AttributeError: 'ParseTreePatternMatcher' object has no attribute 'compile'
```

I looked into the `ParseTreePatternMatcher` class, but found only `compileTreePattern`.

Am I missing something?

Thanks,
Jaroslaw

**Comment by ericvergnaud** [comment]
Hi
Not sure tree pattern matching was ever ported to Python 
If you need it may I suggest that you look into implementing it and submit a PR if you get it working?

Envoyé de mon iPhone

**Comment by jpicau** [comment]
:D Thanks. I'd love to. However, I'm still too new to ANTLR. I keep working/digging and come back later ... Thanks, again.

**Comment by shuizuo** [comment]
I also have the problem and find that the Method compile was not Implemented in the Class ParseTreePatternMatcher. And so far have you solved the problem?

**Comment by jpicau** [comment]
Hi,
my intention was to find all function definitons. I used `Trees.findAllRuleNodes(...)` instead. I don't know if this helps:

```
from antlr4 import *
from antlr4.tree.Trees import Trees
from lua import *

def main():
    
    input = FileStream("factorial.lua")         # antlr4
    lexer = LuaLexer(input)
    stream = CommonTokenStream(lexer)           # antlr4
    parser = LuaParser(stream)
    tree = parser.chunk()

    # find all function definitions
    names = Trees.findAllRuleNodes(tree, LuaParser.RULE_funcname)
    for name in names:
        funcname = name.getPayload()
        ...
```

Bye,
Jaroslaw

**Comment by shuizuo** [comment]
@jpicau Thanks a lot, your code has given me some good ideas.

**Comment by jpicau** [comment]
Cool! You're welcome.

**Comment by 80avin-sw** [comment]
@jpicau  Why was this closed ? It doesn't seem like the original issue of `compileParseTreePattern` was ever resolved.
