### ISSUE TITLE
Feature request: Support for IntelliJ lexers and parsers

### ISSUE THREAD

**Issue by NathanJAdams** [antlr/antlr4#2238]
When creating a plugin for a custom language, IntelliJ doesn't support outside lexers or parsers eg. from ANTLR. What would be really cool (but a lot of work) would be if ANTLR could integrate with IntelliJ and had an option to implement their lexers and parsers.
It would make it a lot easier for people to go straight from creating a custom language to actually developing in that new language.
Totally understand it would be a lot of work though so this is more a discussion point than an issue.

**Comment by ericvergnaud** [comment]
There is the XText add on for eclipse which uses antlr under the hood
Better place to explore this subject is the google discussion group

Envoyé de mon iPhone

**Comment by bjansen** [comment]
@NathanJAdams there's https://github.com/antlr/antlr4-intellij-adaptor/ which totally fits what you are looking for. It takes regular ANTLR4 parsers and binds them to IntelliJ's PSI.

**Comment by KvanTTT** [comment]
The issue does not relate to the repository. @ericvergnaud please close
