### ISSUE TITLE
Syntax errors on examples

### ISSUE THREAD

**Issue by elusiven** [antlr/antlr4#2256]
Hi,

I tried using your examples but getting syntax errors on all of them, it goes like this: 

`error(50): c:\Users\elusiven\Documents\Visual Studio 2017\Projects\Fran\Fran\Grammar\Fran.g:1:0: syntax error: '�' came as a complete surprise to me
error(50): c:\Users\elusiven\Documents\Visual Studio 2017\Projects\Fran\Fran\Grammar\Fran.g:1:1: syntax error: '�' came as a complete surprise to me
error(50): c:\Users\elusiven\Documents\Visual Studio 2017\Projects\Fran\Fran\Grammar\Fran.g:1:2: syntax error: missing SEMI at '�grammar'
error(50): c:\Users\elusiven\Documents\Visual Studio 2017\Projects\Fran\Fran\Grammar\Fran.g:1:11: syntax error: missing COLON at 'Hello' while matching a rule`

**Comment by KvanTTT** [comment]
Unclear. @ericvergnaud please close
