### ISSUE TITLE
Help optimizing grammar

### ISSUE THREAD

**Issue by hajnicovaci** [antlr/antlr4#2257]
Hi, 
I'm using ANTLR 4.6.4 on Windows with Visual Studio 2017 (I've added Antlr to my project through Nuget Manager) . 
I'm writing a grammar to parse a file with a format similar to XML. 
My problem is that the generated parser and lexer performs slowly for larger files. The tests that I did came out like this: 
**for a 500 KB file, running the lexer and parser takes 4 s and for a 22 MB file it takes  467 seconds.** 

Using the [Unbuffered](https://stackoverflow.com/questions/16432469/is-it-possible-to-parse-big-file-with-antlr) streams didn't help improve performance; neither did disabling the generation of the parse tree. 

I attached a file to present the format i'm trying to parse :
 [test.txt](https://github.com/antlr/antlr4/files/1824232/test.txt)

Here is my grammar:
grammar test;

/*
*  Parser rules
*/
testFile			: elementCollection COMMENT*  EOF; 
elementCollection   :  element +  ;
element			:  WHITESPACE* OPEN   content    CLOSE WHITESPACE* COMMENT*;
content			:  WHITESPACE* name  ( value | elementCollection ) ;
name			:  ANYCHAR+ ;
value			:  ( WHITESPACE | VALUE | ANYCHAR )+  ;

/*
* Lexer rules
*/
fragment NEWLINE :  '\r'? '\n' | '\r' ;
fragment WS           :  ' ' | '\t' ;
OPEN			:  '<';
CLOSE			:  '>';
COMMENT		:  '#' ~[\r\n]* '\r'? '\n' -> skip; 
WHITESPACE		:  WS | NEWLINE ;
VALUE			:  '`' (WHITESPACE* ~['] WHITESPACE*)*  '\'' ;
ANYCHAR		:  ~[<>`'] ;

Here is the code that I use to run the lexer and parser:
  
>  //using (var fileStream = new FileStream(input, FileMode.Open))
    //{
   var inputstream = new AntlrFileStream(input); 
   var lexer = new TestLexer(inputstream);// new TestLexer(new UnbufferedCharStream(fileStream));
   var stream = new UnbufferedTokenStream(lexer);
   var parser = new TestParser(stream);
   parser.BuildParseTree = false;
   
> var output = parser.testFile();
    //}

I've read in several places that optimizing the grammar will optimize the lexer and parser. The suggestions for optimizing grammars, that I found, didn't help me.

**I would appreciate any suggestion that could help improve the performance of my grammar.** 
Thank you.

**Comment by ericvergnaud** [comment]
Hi,
The place for support is the google discussion group 
Thanks

Envoyé de mon iPhone

**Comment by KvanTTT** [comment]
@ericvergnaud please close
