### ISSUE TITLE
Python2 Memory Usage

### ISSUE THREAD

**Issue by claytondaley** [antlr/antlr4#2258]
I'm trying to load 400 DSL scripts using the Py2 target.  The scripts are run (frequently) in response to events so we go through the stream->lexer->stream->parser for each at load-time.  When compiling the DSL scripts, the program quickly grows to ~8GB of memory.  Existing memory issues (e.g. #821) often attribute memory consumption to the cache and recommend `ClearDFA`.  Unfortunately, I don't seem to have that (or comparable) method in the Py2 target.

I appreciate that some contributors will want to refer me to the Google Group, but I see [others](https://github.com/antlr/antlr4/issues/1540#issuecomment-268509320) who agree that Github is a reasonable place to address performance concerns.

Each of the 400 scripts ends up around 70kb which is mostly (i.e. 99.9%) inlined libraries also written in the DSL.  If I do the math, that means I'm working with ~30MB of raw code.  The libraries certainly (and grammar likely) present opportunities for optimization, but the gap between 30MB and 8GB seems large.  I want to ensure I'm not overlooking an easy optimization before I invest time in harder optimizations.

On my development machine, the compile process OOMs much earlier than 8GB.  I don't have a ton of experience with memory profilers, but the percentages are pretty stable so I think the following is representative:

```
Index  Count   %      Size   % Cumulative  % Kind (class / dict of class)
    0 796794  10 417520056  35 417520056  35 dict of antlr4.Token.CommonToken
    1 796794  10 111551160   9 529071216  45 dict of antlr4.tree.Tree.TerminalNodeImpl
    2 736469   9  78276180   7 607347396  51 list
    3 144238   2  75580712   6 682928108  57 dict of com.ambassador.dsl.lang.gen.algo_lang_to_exprParser.ExprContext
    4 112805   1  59109820   5 742037928  62 dict of com.ambassador.dsl.lang.gen.algo_lang_to_exprParser.StatContext
    5 106973   1  56053852   5 798091780  67 dict of com.ambassador.dsl.lang.gen.algo_lang_to_exprParser.IndexesContext
    6  60741   1  31828284   3 829920064  70 dict of com.ambassador.dsl.lang.gen.algo_lang_to_exprParser.Assign_exprContext
    7 2494937  30 29939244   3 859859308  72 int
    8  52195   1  27350180   2 887209488  75 dict of com.ambassador.dsl.lang.gen.algo_lang_to_exprParser.StrContext
    9 796794  10  25497408   2 912706896  77 antlr4.Token.CommonToken
```

Is this enough to tell whether this is unavoidable overhead or part of something else (e.g. cache) that could be recovered?  If not, is there something else/more I can provide to clarify if this is expected?

**Comment by ericvergnaud** [comment]
Hi
What I can see from your dump is 796794 tokens + same count of TerminalNode (expected)
Not sure how you end up having 800k tokens in memory? This is not an Antlr memory leak, I believe. Seems like you are keeping a reference to each script parse tree?

Envoyé de mon iPhone

**Comment by claytondaley** [comment]
For each handler (DSL string), we call:

```
            handler_stream = InputStream(handler)
            lexer = algo_lang_to_exprLexer(handler_stream)
            stream = CommonTokenStream(lexer)
            parser = algo_lang_to_exprParser(stream)
            # entrypoint for our scripts
            return parser.prog()
```

`parser.prog()` calls:

```
        localctx = customParser.ProgContext(self, self._ctx, self.state)
        ...
        return localctx
```

and the ProgContext retains a reference to the parser:

```
        def __init__(self, parser, parent=None, invokingState=-1):
            ...
            self.parser = parser
```

Obviously, this cascades to all of the parser nodes.

**Comment by ericvergnaud** [comment]
What happens to the returned localctx?

Envoyé de mon iPhone

**Comment by claytondaley** [comment]
That's the reference we carry around.  Eventually, we do something like:

```
    handler = localctx_dict[event]
    visitor.visit(handler)
```

**Comment by claytondaley** [comment]
Interestingly, it doesn't look like `progContext` ever uses `self.parser` directly.  I'll try removing the reference and see if anything breaks.

**Comment by claytondaley** [comment]
I removed `self.parser` from all of the `Context` constructors with no effect.

**Comment by claytondaley** [comment]
Sorry.  I think I misunderstood your original question.  If the parse tree what is visited by the visitor to actually run the script then yes we're keeping the parse trees in memory by design.  Events are extremely common so we can't afford to re-parse a script each time an event occurs.

As a result, we're keeping around a `CommonToken` for each token which requires a reference (plus possibly a value) for:

```
        self.source = None
        self.type = None # token type of the token
        self.channel = None # The parser ignores everything not on DEFAULT_CHANNEL
        self.start = None # optional; return -1 if not implemented.
        self.stop = None  # optional; return -1 if not implemented.
        self.tokenIndex = None # from 0..n-1 of the token object in the input stream
        self.line = None # line=1..n of the 1st character
        self.column = None # beginning of the line at which it occurs, 0..n-1
        self._text = None # text of the token.
```

For simple tokens like `[`, `in`, or `==`, that could easily work out to hundreds of times the original script.  Thus the ration (8GB:30MB or 266:1) starts to sound reasonable.

I'm going to close the issue since it sounds like it's "normal" overhead and will attempt to optimize the handling of libraries.

**Comment by claytondaley** [comment]
In case someone else runs into a similar issue, we were able to solve the problem by:

 - Compiling the libraries and handlers separately
 - Having our visitor visit (sequentially) the library then the handler (without resetting in the middle)

This isn't _guaranteed_ to work as it depends on the implementation of your visitor.  Our visitor tracks function definitions by building a dictionary mapping function names to their parse trees.  Running the visitor over the library constructs that dictionary (with references to the library's parse tree).  The dictionary remains available in our visitor when we visit the handler so it can "use" the functions defined in the library.
