### ISSUE TITLE
No way to implement a q quoted string with custom delimiters

### ISSUE THREAD

**Issue by singhjayant92** [antlr/antlr4#2273]
I'm trying to implement a lexer rule for an oracle Q quoted string mechanism where we have something like q'$some string$'

Here you can have any character in place of $ other than whitespace, (, {, [, <, ' and ", but the string must start and end with the same character. Some examples of accepted tokens would be:
q'!some string!'
q'ssome strings' 
Notice how s is the custom delimiter but it is fine to have that in the string as well because we would only end at s'

Here's how I was trying to implement the rule:

`Q_QUOTED_LITERAL: Q_QUOTED_LITERAL_NON_TERMINATED . QUOTE-> type(QUOTED_LITERAL);
Q_QUOTED_LITERAL_NON_TERMINATED:
    Q QUOTE ~[ ({[<'"\t\n\r] { setDelimChar( (char)_input.LA(-1) ); }
    (
        . { !isValidEndDelimChar() }?
    )*
;` 

I have already checked the value I get from !isValidEndDelimChar() and I'm getting a false predicate here at the right place so everything should work, but antlr simply ignores this predicate. I've also tried moving the predicate around, putting that part in a separate rule, and a bunch of other stuff, after a day and a half of research on the same I'm finally raising this issue.

I have also tried to implement it in other ways but there doesn't seem to be a way to implement a custom char delimited string in antlr4 (The antlr3 version used to work).

**Comment by ericvergnaud** [comment]
Hi 
The place for support is the google discussion group 
Eric

Envoyé de mon iPhone
