### ISSUE TITLE
featrue-Is there anyway to tell parser action just end this rule?

### ISSUE THREAD

**Issue by ricardo0624** [antlr/antlr4#2282]
I am try to develop a flexible grammar.
antlr do mush job for me,but how to tell parser action end this rule in parser action?
the grammar is tab-sensible just like python,but it don't use line to end a statement,I need to use action to tell the parser rule to end.
if I use predicate action ,it judge the statement is wrong and no longer to recover it,so how to tell parser action to end the rule?

**Comment by sharwell** [comment]
ANTLR's prediction algorithm state behaves like an extremely parallelized lookahead parser. At any given point, it could easily be in 10^9 different places (in practice cases are known where this gets almost incomprehensibly large). It's not really possible to provide a generalized solution for injecting behavior into a subset of these paths without additional information.

**Comment by ricardo0624** [comment]
@sharwell Thank you very much!
I have been wrote a complete demo to explain this at [https://github.com/ricardo0624/demo-antlr-1](ricardo0624-demo-antlr-1)

**Comment by ricardo0624** [comment]
Thanks again.
I found if use action with exception,can exit this method, and finally exit this current rule.
