### ISSUE TITLE
Generate parser that target javascript

### ISSUE THREAD

**Issue by abumalick** [antlr/antlr4#2286]
Hello,

I posted a question here https://groups.google.com/forum/#!topic/antlr-discussion/fY4-xpD6gHI and now I am pretty sure that this is a bug. I am certain that I followed instructions correctly.

What I was trying to do: Generate a java/python parser with javascript target.

I am using nodejs v8.10.0

The steps:
- install antlr4 from brew (on mac) `brew install antlr` (it installs Version 4.7.1)
- pull grammars-v4 repo https://github.com/antlr/grammars-v4/
- go into java directory (https://github.com/antlr/grammars-v4/tree/master/java)
- install antlr4 js runtime:
  - `npm init`
  - `npm install antlr4` (https://www.npmjs.com/package/antlr4)
- generate lexer and parser:
```
antlr4 -Dlanguage=JavaScript JavaLexer.g4
antlr4 -Dlanguage=JavaScript JavaParser.g4
```
- add a test file according to instruction on https://github.com/antlr/antlr4/blob/4.6/doc/javascript-target.md : 
```js
const antlr4 = require('antlr4/index')
const JavaLexer = require('./JavaLexer')
const JavaParser = require('./JavaParser')

var input = "your text to parse here";
var chars = new antlr4.InputStream(input);
var lexer = new JavaLexer.JavaLexer(chars);
var tokens = new antlr4.CommonTokenStream(lexer);
var parser = new JavaParser.JavaParser(tokens);

parser.buildParseTrees = true;

// We want to print parser's properties to see if we have a rule function there:
console.log(Object.keys(parser))

// this will throw an error
parser.CompilationUnit();
```

- run the test: `node test.js`

result: 
```
[ '_listeners',
  '_interp',
  '_stateNumber',
  '_input',
  '_errHandler',
  '_precedenceStack',
  '_ctx',
  'buildParseTrees',
  '_tracer',
  '_parseListeners',
  '_syntaxErrors',
  'ruleNames',
  'literalNames',
  'symbolicNames' ]
/Users/abumalick/Documents/workspace/obytes/antlr4-grammars/java/test.js:17
parser.CompilationUnit();
       ^

TypeError: parser.CompilationUnit is not a function
```

So what's the problem ? CompilationUnit rule was not generated in the parser object.

I tried with a lot of grammars, and every time I get the same. I am pretty sure that it is a bug because I spent one week reading and trying to understand, and I am pretty sure that this is not the normal behavior..

Thank you for taking time reading all this.

**Comment by ericvergnaud** [comment]
Can you send the generated lexer and parser?

**Comment by abumalick** [comment]
https://github.com/abumalick/grammars-v4/blob/master/java/JavaParser.js

https://github.com/abumalick/grammars-v4/blob/master/java/JavaLexer.g4

**Comment by ericvergnaud** [comment]
JavaParser.prototype.compilationUnit
it’s there but it starts with lowercase like your rule

**Comment by abumalick** [comment]
very nice ! It works !! thank you very much !

**Comment by KvanTTT** [comment]
@ericvergnaud please close
