### ISSUE TITLE
Error while calling tree.toStringTree(parser) method in python 3.6.4

### ISSUE THREAD

**Issue by huilibai** [antlr/antlr4#2298]
Runtime environment: python 3.6.4
Library: antlr4-python3-runtime
Version: 4.7.1

File "~/Documents/code/CustomStaticAnalysis/analysis/antlr4/tree/Trees.py", line 48, in getNodeText
    return ruleNames[t.getRuleIndex()]
TypeError: 'ObjectiveCParser' object does not support indexing

**Comment by ericvergnaud** [comment]
Hi,
Thanks for this.
With this level of context not sure what help you can expect.
Please close this and get support from the google discussion group.

Envoyé de mon iPhone
