### ISSUE TITLE
Unable to tokenize the right parenthesis and comments using python 3.6.5

### ISSUE THREAD

**Issue by foxpangxie** [antlr/antlr4#2300]
I download the JavaLexer.g4 from GitHub. I try to use the generated JavaLexer.py to handle the java file like following:

```
    lexer = JavadocLexer(inputFile)

    it = iter(lexer.getAllTokens())
    for tk in it:
        print("line: %s ; colum: %s ; type: %s ; (%s, %s)" %(tk.line, tk.column, tk.type, tk.start, tk.stop))
        next(it)
```
and the sample java file used to analysis is like following:

```
package application;

import java.util.Iterator;

/**
 * level one class comment.
 */
public class SampleJava extends ISampleJava
{
	// level one line comment
	int a = 0;
	
	/**
	* level two class comment.
	*/
	public void first() 
	{
		// level two line comment.
	}
}
```
Every right parenthesis and level two comment is not tokenized, seems to be skipped.
Using "antlr-4.7.1-complete" to generate lexer python code. And antlr4-python3-runtime.

**Comment by ericvergnaud** [comment]
Hi
That grammar is for the Java runtime
Please get support from the google discussion group

Envoyé de mon iPhone
