### ISSUE TITLE
TypeError: '<' not supported for PrecedencePredicate (Python 3 runtime)

### ISSUE THREAD

**Issue by alberto-dellera** [antlr/antlr4#2301]
I get the exception (in ANTLR 4.7.1):

 `TypeError: '<' not supported between instances of 'PrecedencePredicate' and 'PrecedencePredicate'`

since the ` __lt__()` dunder is not implemented in PrecedencePredicate - it is almost certainly a porting issue from Python 2 since I see a `__cmp__()` method which is, of course, no longer honored in Python 3.

The issue is easily "fixed" by implementing all the equivalent Rich Methods: 
```python
    #def __cmp__(self, other):
    #    return self.precedence - other.precedence

    def __lt__(self, other):
        return self.precedence < other.precedence

    def __le__(self, other):
        return self.precedence <= other.precedence

    def __gt__(self, other):
        return self.precedence > other.precedence

    def __ge__(self, other):
        return self.precedence >= other.precedence 
```
Note: I have not implemented `__ne__()` since it is automatically implemented ad "not `__eq__()`", and that looks desirable in this case (to me).

It is "fixed" since I no longer get the exception, but I'm not sure whether this change is correct - I cannot even know how the change impacts the resulting AST - an ANTLR expert's review is certainly needed.

Additional side note, not strictly related to this issue: I see that `__eq__()` checks for the instance type:
```python
    def __eq__(self, other):
        if self is other:
            return True
        elif not isinstance(other, PrecedencePredicate):
            return False
        else:
            return self.precedence == other.precedence
```
shouldn't the original  `__cmp__()` , and hence the ported Rich Methods, check for the instance type as well?

**Comment by ericvergnaud** [comment]
Hi this sounds right however you only need to implement __lt__, all other cases will be handled gracefully by py3 (like for __ne__).
Re instance checking you would be right generally speaking however implementing type checking would slow down slightly when to my knowledge there is no scenario where this is required
It would be great if you could isolate the grammar fragment which generates this specific code, so we can add the corresponding test to our test suite

**Comment by alberto-dellera** [comment]
@ericvergnaud this is the simplest grammar reproducing the issue that I have been able to reduce to:
```
grammar Issue2301;

SPACES: [ \t\r\n]+ -> skip;

AT: 'AT';
X : 'X';
Y : 'Y';

ID: [A-Z]+;

constant
    : 'DUMMY'
    ;

expr
    : ID constant?  
    | expr AT X                       
    | expr AT Y                  
    ;
```
phrase to recognize: `POINT AT X`

**Comment by ericvergnaud** [comment]
Thanks,
this will be fixed in our next release
