### ISSUE TITLE
powerbuilder grammar has issues

### ISSUE THREAD

**Issue by ramnar** [antlr/antlr4#2310]
The powerbuilder grammar for antlr4 in github is having issues
Couple of Issues which I noticed are

- PowerBuilder statements end with new line.But the grammar doesnt include this
-datatype_decl rule in the grammar is not correct

**Comment by sharwell** [comment]
:memo: This should probably be filed in https://github.com/antlr/grammars-v4.

**Comment by ramnar** [comment]
Reported the issue in grammars-v4
