### ISSUE TITLE
how to access member variable in parser from listener

### ISSUE THREAD

**Issue by peterremote1980** [antlr/antlr4#2325]
Hi All
    how to access member variable in parser from listener? The variable is defined in the grammar:

@parser::members{
	public int xxx;
}

Thanks
Peter

**Comment by sharwell** [comment]
⚠️ Keep in mind that parser instances are allowed to be reused after parsing an input, so in general the member variables are not guaranteed to hold the correct/expected values when the listener runs.

If you are tracking the lifetime of parser instances separately, you can pass a copy of the parser to the listener constructor and keep a reference to it there, which can then be used to access variables.

**Comment by peterremote1980** [comment]
got it. thank you sir
