### ISSUE TITLE
Is antlr using anltr to build?

### ISSUE THREAD

**Issue by peterremote1980** [antlr/antlr4#2327]
Hi All
   Is antlr using antlr to build? what is the g4 file to parse g4 grammar? I want to fix this issue https://github.com/antlr/grammars-v4/issues/1165
Thanks
Peter

**Comment by ericvergnaud** [comment]
Yes, you can find the g4 in the source code.

Envoyé de mon iPhone

**Comment by jrozner** [comment]
The last time I looked ANTLR 4 used an ANTLR 3 based lexer and parser in the ANTLR tool to parse the ANTLR 4 grammar files. Looking at the tool source code it doesn't appear that ANTLR 4 is self hosting.

**Comment by ericvergnaud** [comment]
This evolved quite a while ago.
Antlr4 now uses antlr4 

Envoyé de mon iPhone

**Comment by KvanTTT** [comment]
I don't think so. Antlr 4 uses Antlr 3 grammars and parser, see https://github.com/antlr/antlr4/tree/master/tool/src/org/antlr/v4/parse

**Comment by KvanTTT** [comment]
@parrt it can be closed since it's a question.

**Comment by parrt** [comment]
Yep, we still use antlr3 I'm afraid to parse grammars. I would love to get rid of it but it's too big of a risk to change for no outward gain.
