### ISSUE TITLE
Impossible to compile parser+(tokenVocab=lexer+(import lexer)) with Gradle+Antlr4

### ISSUE THREAD

**Issue by imoverclocked** [antlr/antlr4#2335]
I've been trying really hard to compile a project that has `parser grammar Foo` which uses `options { tokenVocab=FooLexer; }` which in turn does `import FooTokens`. Since there is a bit of setup to get there, I created a [minimal repository](https://github.com/imoverclocked/antlr_bug) to reproduce the bug with [documented error conditions](https://github.com/imoverclocked/antlr_bug/blob/master/build.gradle) vs `-lib` parameters.

Ideally this would just work out of the box without tweaking `arguments` in `build.gradle`.

Otherwise, I'm really enjoying ANTLR4!

**Comment by ericvergnaud** [comment]
Hi,

the place for support os the google discussions group.

Kind regards,

Eric

**Comment by imoverclocked** [comment]
This is a bug, not a support request.

**Comment by imoverclocked** [comment]
Some related bugs:

https://github.com/antlr/antlr4/issues/638
https://github.com/gradle/gradle/issues/2565

**Comment by imoverclocked** [comment]
... and just in case I'm wrong: https://groups.google.com/forum/#!topic/antlr-discussion/5bxlRnLWsck

**Comment by ericvergnaud** [comment]
mmm... antlr does not currently support gradle
if you need gradle support you are more than welcome to contribute

**Comment by imoverclocked** [comment]
So, if the gradle use-case can't work because of a fundamental problem in antlr, who needs the issue raised? I ask because the gradle issue seems to stem from the fact that antlr ignores multiple `-lib` arguments.

**Comment by ericvergnaud** [comment]
That wouldn't be a 'fundamental problem', would it? Simply a cmd line options one.
I believe you should:
 - play with the tool outside gradle to better understand how the options work
 - find out whether new options are required for gradle support
 - if so engage with Terence to discuss

**Comment by imoverclocked** [comment]
Here is my view purely in terms of the antlr4 command:

I can compile the file com/example/foo/FooLexer.g4 which does `import FooTokens`:

```
% antlr4 -o out -package com.example.foo com/example/foo/FooLexer.g4
% find . -name FooTokens.\* -or -name FooLexer.\*
./out/com/example/foo/FooLexer.interp
./out/com/example/foo/FooLexer.java
./out/com/example/foo/FooLexer.tokens
./com/example/foo/FooTokens.g4
./com/example/foo/FooLexer.g4
```

Next, attempting to compile Foo (which does tokenVocab=FooLexer) with similar options fails:

```
% antlr4 -o out -package com.example.foo com/example/foo/Foo.g4
error(114): com/example/foo/Foo.g4:3:21: cannot find tokens file com/example/foo/FooLexer.tokens
warning(125): com/example/foo/Foo.g4:5:5: implicit definition of token FOO in parser
```

I assert that FooLexer.tokens is a generated file (aka an output file) thus it should be searched for in the appropriate output directory. Running a similar command with both grammars in the same antlr4 instance still does not resolve the problem:

```
% antlr4 -o out -package com.example.foo com/example/foo/FooLexer.g4 com/example/foo/Foo.g4
```

Finally, adding a `-lib out` option gives a pretty misleading error which points to internal inconsistency:

```
% antlr4 -o out -package com.example.foo -lib out com/example/foo/FooLexer.g4 com/example/foo/Foo.g4
error(114): com/example/foo/Foo.g4:3:21: cannot find tokens file com/example/foo/FooLexer.tokens
warning(125): com/example/foo/Foo.g4:5:5: implicit definition of token FOO in parser
```

Since I have specified the lib directory as "out" and the error output complains about not finding "com/example/foo/FooLexer.tokens" a savvy programmer might not think to do the following hack which strangely solves the issue: `-lib out/com/example/foo`

Fixing this could be considered a language level feature of the antlr4 grammar to include a package in the import path, eg: `import com.example.foo.FooTokens;` or `{tokenVocab=com.example.foo.FooLexer}`

It could also be argued to be a resolution bug where the output directory is constructed from the input directory but imports are not search appropriately in the deeper/modified output directory.

Either way, there is an inconsistency in the way the tool works and reports error output today.

**Comment by ericvergnaud** [comment]
have you tried -o out/com/example/foo?

**Comment by ericvergnaud** [comment]
I'm not sure generating both lexer and parser in one go is supported with these options
I personally use 2 commands, such as:
% antlr4 -o out/com/example/foo -package com.example.foo com/example/foo/FooLexer.g4 
% antlr4 -o out/com/example/foo -package com.example.foo com/example/foo/Foo.g4

**Comment by imoverclocked** [comment]
That doesn't work. The handling of filenames inside of the antlr4 tool is inconsistent. Feel free to reproduce:

```
% git clone  git@github.com:imoverclocked/antlr_bug.git
Cloning into 'antlr_bug'...
remote: Counting objects: 35, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 35 (delta 6), reused 26 (delta 4), pack-reused 0
Receiving objects: 100% (35/35), 55.94 KiB | 545.00 KiB/s, done.
Resolving deltas: 100% (6/6), done.
% cd antlr_bug/src/main/antlr/
% antlr4 -o out/com/example/foo -package com.example.foo com/example/foo/FooLexer.g4
% antlr4 -o out/com/example/foo -package com.example.foo com/example/foo/Foo.g4
error(114): com/example/foo/Foo.g4:3:21: cannot find tokens file com/example/foo/FooLexer.tokens
warning(125): com/example/foo/Foo.g4:5:5: implicit definition of token FOO in parser
```

There is no single set of options that can be used to compile both. Compiling both requires conflicting options per-source based on the import mechanism.

**Comment by ericvergnaud** [comment]
what works (I just tried on a very complex lexer/parser grammars set) is:
antlr4 -o out/com/example/foo -package com.example.foo com/example/foo/FooLexer.g4
antlr4 -o out/com/example/foo -lib out/com/example/foo -package com.example.foo com/example/foo/FooLexer.g4

**Comment by imoverclocked** [comment]
I assume you meant Foo.g4 in the second command; It didn't work for me with the somewhat minimally reproducible grammar in my example repository:

```
% cd antlr_bug/src/main/antlr/
% rm -rf out
% antlr4 -o out/com/example/foo -package com.example.foo com/example/foo/FooLexer.g4
% antlr4 -o out/com/example/foo -lib out/com/example/foo -package com.example.foo com/example/foo/Foo.g4
error(114): com/example/foo/Foo.g4:3:21: cannot find tokens file com/example/foo/FooLexer.tokens
warning(125): com/example/foo/Foo.g4:5:5: implicit definition of token FOO in parser
% find out -type f
out/com/example/foo/com/example/foo/FooLexer.interp
out/com/example/foo/com/example/foo/FooLexer.java
out/com/example/foo/com/example/foo/FooLexer.tokens
```

**Comment by imoverclocked** [comment]
The crux is this:

Running ` antlr4 -o out some/path/to/LexerGrammar.g4`  produces output to `out/some/path/to/LexerGrammar.tokens`

Running `antlr4 -o out some/path/to/ParserGrammar.g4` then looks for `LexerGrammar.tokens` inside of  `some/path/to` and perhaps in `out` but not in `out/some/path/to`.

**Comment by ericvergnaud** [comment]
It works for me so there is something more involved

**Comment by ericvergnaud** [comment]
renamed Foo to FooParser for clarity
the below works perfectly:
antlr4 -o out -package com.example.foo com/example/foo/FooLexer.g4
antlr4 -o out -lib out/com/example/foo -package com.example.foo com/example/foo/FooParser.g4

**Comment by imoverclocked** [comment]
I think that pretty much sums up the bug. Since `com/example/foo/FooParser.g4` requires access to `com/example/foo/FooLexer.tokens` and it already knows that `com/example/foo/FooLexer.tokens` is a build artifact from something called `com/example/foo/FooLexer.g4`, it should already know to look in the output directory `out` / `com/example/foo/FooLexer.tokens`.

Currently, the error reports:

```
error(114): com/example/foo/Foo.g4:3:21: cannot find tokens file com/example/foo/FooLexer.tokens
```

but one has to instruct antlr to find `com/example/foo/FooLexer.tokens` by adding the lib directory of `out/com/example/foo/`. Logically from the error output and this lib setting, one would expect the file to be `out/com/example/foo/com/example/foo/FooLexer.tokens` instead of where it actually is.

**Comment by ericvergnaud** [comment]
I wouldn’t call this a bug, rather an implementation that has room for improvement.
Feel free to contribute.

**Comment by imoverclocked** [comment]
Call it what you like, bug reports are contributions. Creating test cases and explaining bad behavior often takes more time than writing a code fix. I can't write code and submit to this project due to legal obligations at this time. If fixing well defined problems is not a priority then that's a good datapoint. Thanks for your time.

**Comment by ericvergnaud** [comment]
Hey, we're all doing this for free.
Evolving the spec to support additional use cases without breaking existing ones is not a small task.
My priority is indeed to fix blockers on the targets I maintain (C#, Python, JavaScript).
I believe I've helped you identify a solution to your issue, again for free, so not sure I deserve this bitter comment.

**Comment by imoverclocked** [comment]
Hi Eric, sorry I came across as bitter. I appreciate that you are attempting to help. Interestingly, I was also attempting to help this project after having already learned and understood the underlaying issue.

To re-iterate my original intent: my goal here was not for support but to report a bug to the best of my ability. I found my own work-around that is specific to my environment and I fully understand the implications of using it. Finding *and reporting* problems is part of what makes a good user population for an open source or any other community. Not everyone has the ability (technical or otherwise) to solve the problems that they find and see. Then, for every person that does report an issue, far more are just using local work-arounds or abandoning the project altogether. All of these reasons are why I am frustrated at being met with dismissive comments about something I would like to use and potentially contribute to in the future.

Cheers.

**Comment by MuntashirAkon** [comment]
Just for the record, the following gradle configuration fixed the issue for me. However, make sure not to use any `import` statement. (Assuming the package name is `example.package`)

```groovy
generateGrammarSource {
    maxHeapSize = "128m"
    File file = new File(projectDir, 'build/generated-src/antlr/main/example/package')
    file.mkdirs()
    arguments += ['-lib', file.getAbsolutePath(), '-package', 'example.package', '-visitor', '-no-listener']
}
```

**Comment by ice1000** [comment]
> Just for the record, the following gradle configuration (bold-faced) fixed the issue for me. However, make sure not to use any `import` statement. (Assuming the package name is `example.package`)
> 
> generateGrammarSource {
>     maxHeapSize = "128m"
>     File file = new File(projectDir, 'build/generated-src/antlr/main/example/package')
>     file.mkdirs()
>     arguments += ['-lib', file.getAbsolutePath(), '-package', 'example.package', '-visitor', '-no-listener']
> }

Thank you! I'm quite surprised that an official gradle plugin requires user hacking to make it work for basic use cases.
