### ISSUE TITLE
Blank chars is removed when call getText()

### ISSUE THREAD

**Issue by flying1020** [antlr/antlr4#2345]
Hello, I use antlr v4 for parse my sql statement, such as "select a a a from b", but I got following error message:
"no viable alternative at input: 'selectaaafromb' " // blank chars between tokens is removed.
"select a a a from b" ----call getText()---> "selectaaafromb"
I debug the code and found this: 
![issue](https://user-images.githubusercontent.com/14899806/44258974-d501b400-a242-11e8-8c72-ea4961cbe350.png)
I create a subclass by override method: 'getText(Interval interval)', it's solved.
It is better for add a blank char between tokens when assemble text?
sorry for I am not good at English.

**Comment by ericvergnaud** [comment]
Hi
The place for support is the google discussion group .
Kind regards 
Eric 

Envoyé de mon iPhone

**Comment by flying1020** [comment]
OK, thank you for reply!
I moved this issue into google group.
