### ISSUE TITLE
Minified Javascript Runtime with dependencies included?

### ISSUE THREAD

**Issue by jarred-naicker** [antlr/antlr4#2346]
I currently make use of the npm package antlr4 in a node js project, with antlr4 parsers running in a web-worker, this works fine, however the npm package has its own dependencies such as:

"buffer": "github:jspm/nodelibs-buffer@0.1.1",
"fs": "github:jspm/nodelibs-fs@0.1.2",
"process": "github:jspm/nodelibs-process@0.1.2"

The above dependencies have their own package dependencies and so forth. Performance on the web is crucial and I am trying to keep dependencies at a minimum. The less scripts our users need to download the better. (Our web app will be run on both desktop and mobile devices in slow network enviroments.)

I then decided to remove the node package in favour of the javascript runtime I download from antlr.org. This has its own node module requirements which are not available in the web-worker thread.

Surely there is a minified version of the javascript runtime I can use that does not require outside dependencies?

**Comment by ericvergnaud** [comment]
Hi
The place for support is the google discussion group 
But see https://github.com/antlr/antlr4/blob/master/doc/javascript-target.md
Eric

Envoyé de mon iPhone
