### ISSUE TITLE
Assign token name to generated ParserRuleContext for automatically resolved tokens

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#2347]
Consider the following grammar:

```antlr
grammar test;
root: Token;
Token: 'token';
```

After the parser generation, I have the following `RootContext`:

```java
public static class RootContext extends ParserRuleContext {
	public TerminalNode Token() { return getToken(testParser.Token, 0); }
	public RootContext(ParserRuleContext parent, int invokingState) {
		super(parent, invokingState);
	}
	@Override public int getRuleIndex() { return RULE_root; }
}
```

But for such grammar:

```antlr
grammar test;
root: 'token';
Token: 'token';
```

The terminal node `Token` is missing in `RootContext`:

```java
public static class RootContext extends ParserRuleContext {
	public RootContext(ParserRuleContext parent, int invokingState) {
		super(parent, invokingState);
	}
	@Override public int getRuleIndex() { return RULE_root; }
}
```

It would be convenient to generate the same contexts for the abovementioned grammars.

Full codes and diff are available on https://www.diffchecker.com/eg2AIeJN

**Comment by parrt** [comment]
hi! This is a totally reasonable request but I'm afraid to change the code generation to insert that method for fear of breaking something. I just don't have enough time to think about the potential issues. sorry!

**Comment by KvanTTT** [comment]
I added unit tests. Other tests also are fine.
