### ISSUE TITLE
[Go] Visitor example invalid memory address

### ISSUE THREAD

**Issue by hassanalinali** [antlr/antlr4#2367]
I'm trying to implement a project that I've previously done in Python and Java to Go, and I can't really get to run the simplest visitor example that I can think of. I've attached the code and the error below. Let me know if there's anything else that I can help with.

ANTLR4 version - 4.7.1

```go
func main() {
	is := antlr.NewInputStream("print(1+2)")

	// Create the Lexer
	lexer := parser.NewLesmaLexer(is)
	stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

	// Create the Parser
	p := parser.NewLesmaParser(stream)
	p.BuildParseTrees = true

	tree := p.Parse()  // Parse is the big block of statements

	antlr.ParseTreeVisitor.Visit(&lesmaVisitor{}, tree)
}
```

Error (line 35 is the last line of the code written above):
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5278e8]

goroutine 1 [running]:
main.(*lesmaVisitor).Visit(0xc0000e4528, 0x7fd15e356d40, 0xc0000e8760, 0xc0000e8700, 0x7fd15e356d40)
	<autogenerated>:1 +0x8
main.main()
	/home/fake/go/src/lesma/main.go:35 +0x2e3
```

**Comment by NickLarsenNZ** [comment]
Hi @hassanalinali, how did you solve this problem? I'm also trying to implement a visitor in Go, but am not sure how.

**Comment by hassanalinali** [comment]
I managed to get a working visitor example but it's tedious, as I said over here #2370 it's a different kind of implementation, in which as far as I've seen you need to implement yourself all the functions because the default is not implemented as in Java or Python's implementation, therefore you need to redirect from all the grammar rules downwards
