### ISSUE TITLE
Syntax error in antlr4/runtime/Swift/boot.py

### ISSUE THREAD

**Issue by sellingsolutions** [antlr/antlr4#2369]
**Hey guys, when running:**
`python boot.py --gen-xcodeproj`
**I got this error message:**
`  File "boot.py", line 179
    print GREEN + "[ANTLR] " + msg + RESET
              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(GREEN + "[ANTLR] " + msg + RESET)?`

So I simply did as instructed, I added the missing parentheses and the script ran fine.

**Comment by luisfelipesv** [comment]
Happened to me as well but only when using python3
