### ISSUE TITLE
Antlr4 default visitor functions not properly implemented

### ISSUE THREAD

**Issue by alinalihassan** [antlr/antlr4#2370]
The Default visitors generated by ANTLR4 v 4.7.1 do not visit their children by default. This is tedious in the sense that you need to override all the methods and wire the functions yourself to have a functional program, and that's especially difficult when you have multiple cases and for a catch-all identifier you need to check every context if it's null and etc. and that's not how ANTLR works at least in Python2/3 and Java. Are there any plans to implement this in the near future?

**Comment by hassanalinali** [comment]
I am talking about this specific part of the go target source
```go
func (v *BaseParseTreeVisitor) Visit(tree ParseTree) interface{}            { return nil }
func (v *BaseParseTreeVisitor) VisitChildren(node RuleNode) interface{}     { return nil }
func (v *BaseParseTreeVisitor) VisitTerminal(node TerminalNode) interface{} { return nil }
func (v *BaseParseTreeVisitor) VisitErrorNode(node ErrorNode) interface{}   { return nil }

// TODO
//func (this ParseTreeVisitor) Visit(ctx) {
//	if (Utils.isArray(ctx)) {
//		self := this
//		return ctx.map(function(child) { return VisitAtom(self, child)})
//	} else {
//		return VisitAtom(this, ctx)
//	}
//}
//
//func VisitAtom(Visitor, ctx) {
//	if (ctx.parser == nil) { //is terminal
//		return
//	}
//
//	name := ctx.parser.ruleNames[ctx.ruleIndex]
//	funcName := "Visit" + Utils.titleCase(name)
//
//	return Visitor[funcName](ctx)
//}
```
