### ISSUE TITLE
Allow modifying of ParseTrees

### ISSUE THREAD

**Issue by NathanJAdams** [antlr/antlr4#2387]
I'm currently writing a language and would like to use the visitor/listener to pre-process the AST to simplify the compilation process. This mostly means modifying the structure by adding/removing children. My trouble is the iteration in ParseTreeWalker seems to assume the AST is immutable eg. it caches the child count before iterating.
The current work around is to translate the ParseTree into another custom graph type that can then be edited.
Is there any way of allowing ParseTreeWalker to handle mutations to the AST while iterating? Or maybe adding a new walker that can do that?

**Comment by parrt** [comment]
Hi @NathanJAdams you'll have to create a new tree during the walk.
