### ISSUE TITLE
4.7.1 not working for trivial case - when token defined for static text

### ISSUE THREAD

**Issue by cliffbdf** [antlr/antlr4#2392]
There appears to be an error in antlr's processing of token definitions.

I am using antlr 4.7.1, and Java 1.8.0_161. Have tried also with Java 9 and Java 10.

The trivial example can be found at [https://gitlab.com/cliffbdf/antlr-bug-1](https://gitlab.com/cliffbdf/antlr-bug-1). Another can be found at [https://gitlab.com/cliffbdf/antlr-bug-2](https://gitlab.com/cliffbdf/antlr-bug-2). The second one is very close to the "hello" example in the antlr docs.

Both examples have a script, d.sh, for building and running. The script does not require any tools beside antlr and the JDK. (I removed all dependence on maven, etc.)

For the first example, the trivial grammar is,

```
grammar Flow;
	Tname					: [a-zA-Z_] [a-zA-Z_0-9]* ;
	Tcolon					: ':' ;
	Tnamespace				: 'namespace' ;
	namespace				: Tnamespace Tname Tcolon ;
	WS 						: [ \t\r\n]+ -> skip ;
```

The trivial test input is,

`namespace MyNamespace:`

The output is,

> line 1:0 missing 'namespace' at 'namespace'
> line 1:10 extraneous input 'MyNamespace' expecting ':'

Yet, the input is valid (I believe), and should not (I believe) generate an error. I own the antlr book, have written many grammars before for other compiler tools, but this is my first antlr grammar. I hope the mistake is mine, but my grammar and use of the tool seem to me to be correct.

The script for building and running the test case is in d.sh - just set the jar file locations and java home location at the beginning and then source it.

See also the comments below, which describe the second example.

**Comment by cliffbdf** [comment]
Just tried the online example in the Getting Started guide, but using the TestRig (grun), and I get the same incorrect result! Here is my console output:

> $ alias antlr4='java -Xmx500M -cp "/usr/local/lib/antlr-4.7.1-complete.jar:$cp" org.antlr.v4.Tool'
> $ java -cp .:$antlr_jar org.antlr.v4.gui.TestRig Hello r -tree
> Hello me
> line 1:0 token recognition error at: 'H'
> line 1:1 missing 'hello' at 'ello'
> (r <missing 'hello'> ello)
> $

**Comment by cliffbdf** [comment]
Found the smoking gun. This grammar works:

> grammar Hello;
> 	Tname					: [a-zA-Z_] [a-zA-Z_0-9]* ;
> 	Tcolon					: ':' ;
> 	hello  					: 'hello' Tname ;
> 	WS 						: [ \t\r\n]+ -> skip ;

but this equivalent grammar does not:

> grammar Hello;
> 	Tname					: [a-zA-Z_] [a-zA-Z_0-9]* ;
> 	Tcolon					: ':' ;
> 	Thello					: 'hello' ;
> 	hello  					: Thello Tname ;
> 	WS 						: [ \t\r\n]+ -> skip ;

**Comment by ericvergnaud** [comment]
Hi,
The place for support is the google discussion group.
You just need to define Thello before Tname.
Thanks

Envoyé de mon iPhone

**Comment by cliffbdf** [comment]
Ah. A newbie mistake :-(

I would have posted to the group, but I thought that it was a bug! Sorry about that.

Thanks for pointing out my mistake! (As I said, I am new to antlr)
