### ISSUE TITLE
Prepare / release 4.7.2

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#2395]
Howdy folks: @pboyer, @mike-lischke, @janyou, @ewanmellor, @hanjoes, @ericvergnaud et al  I'd like to get a 4.7.2 release out some time in the next few weeks.  Can you let me know what must go in this release and what would be nice? We have to fix the following for example because it prevents Swift from working and it highlighted a bug in the Java version: [issue 2372](https://github.com/antlr/antlr4/issues/2372)

**Comment by ewanmellor** [comment]
The Swift runtime is passing all my tests, and we got one confirm on #2372, so as far as I'm concerned, the Swift runtime is good to go for 4.7.2.

Note that this release will be Swift 4.2 _only_ -- it's incompatible with earlier releases.  That's usually not a problem for the Swift ecosystem given how aggressively they're pushing forward at the moment, but it's something to be aware of.  I put it in the documentation already.

**Comment by parrt** [comment]
Excellent. great. @mike-lischke what more stuff should we get in for 4.7.2?

**Comment by mike-lischke** [comment]
I see nothing else that is still pending for 4.7.2, from the C++ runtime side. Good to go...

**Comment by ericvergnaud** [comment]
Would be great to have #2412 for js, if you can wait a day or 2

**Comment by parrt** [comment]
Sure, @ericvergnaud i'm in no rush.

**Comment by plaurent** [comment]
@ericvergnaud Looks like commit dd3af945fda571db6025a0b1ad334c24eb1c4a1b from January of this year has already fixed this the bug in master.  So, I will close my issue and look forward to the imminent release of 4.7.2.  Thank you.

(Incidentally, mvn clean for antlr4 master fails for me on both Mac OS and Linux with the error `Plugin org.antlr:antlr4-maven-plugin:4.7.2-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.antlr:antlr4-maven-plugin:jar:4.7.2-SNAPSHOT`)

**Comment by parrt** [comment]
@plaurent I believe that you have to do `mvn install` not `mvn compile` etc...  as the build process has to use some things that are created and installed on the fly.

**Comment by plaurent** [comment]
@parrt Ok was following the build instructions here (https://github.com/antlr/antlr4/blob/master/doc/building-antlr.md) where the step before mvn install was "mvn clean" and that was failing.

Should we just remove the "mvn clean" step?

**Comment by parrt** [comment]
ah. maybe so. Forget the clean and try the install.

**Comment by parrt** [comment]
ok, gang. i'm starting the release process!

**Comment by parrt** [comment]
Hmm...getting 

```
/private/var/folders/93/9kzk2ccm8xj8k70059b28jk80000gp/T/BaseSwiftTest-main-1545087448994/testcase-1545087449004/Sources/testcase-1545087449004/TBaseListener.swift:3:8: error: no such module 'Antlr4'
import Antlr4
       ^
```

from swith. @ewanmellor @hanjoes ?  I have Xcode 10.1 installed.

**Comment by parrt** [comment]
Ugh. Java world has turned to shit. Now I'm getting:

```
java.lang.NoSuchMethodError: java.nio.CharBuffer.flip()Ljava/nio/CharBuffer;
```

Was working with java 7 last month :(  That is apparently a version issue.

**Comment by parrt** [comment]
Hmm...yeah, does moving to java 8 cause anybody problems though in real world?  Will it break a lot of stuff? I can't remember the issues...oh, was it android forking off at 1.7?

**Comment by ewanmellor** [comment]
Well if it's Android that you actually care about, we should have Android tests running on Travis.  Would that just be adding it to the matrix, or is there more to it?

I notice that the JDK 7 tests are passing on Travis at the moment, but if I understand correctly from that issue I cross-referenced, this issue would only show up if you compiled on JDK 9 but ran on earlier JDKs.  I don't think any of the Travis tests are doing that right now.

**Comment by KvanTTT** [comment]
Is StringTemplate library updated to the latest version (4.1)?

**Comment by parrt** [comment]
ooops. sorry. i left it as 4.0.8. rats.  anyway, it's all pushed now, even C++, C# and others
