### ISSUE TITLE
Question re use of MurmurHash in runtime

### ISSUE THREAD

**Issue by ewanmellor** [antlr/antlr4#2401]
@parrt @sharwell A question regarding the use of MurmurHash in the Java runtime (and ported to Swift): is the correctness or performance dependent on MurmurHash in particular?

The reason I ask is Swift 4.2 has added a new interface where our code would choose which values to hash over, but the standard library chooses the hash algorithm.  This is intended to allow the standard library to change out the hash algorithm as needed e.g. to avoid hash-based DoS attacks.

If there's no particular reason for Antlr to use MurmurHash, we could remove it entirely from the Swift runtime and use the standard library algorithms instead.

https://github.com/apple/swift-evolution/blob/master/proposals/0206-hashable-enhancements.md

**Comment by ericvergnaud** [comment]
Hi,
Using MurmurHash is key to performance, not just correctness (which could be achieved using other means), by avoiding uneven distribution of entries in buckets.
You want to make sure each slot in a Map only points to a very low number of values.
Éric

Envoyé de mon iPhone

**Comment by ewanmellor** [comment]
@ericvergnaud I understand that using a good hash function is important.  My question is whether there is something specific to MurmurHash, as opposed to the hash function that the Swift standard library has chosen.

**Comment by ericvergnaud** [comment]
??? Sorry if my explanation wasn’t clear enough. What is specific to MurmurHash is precisely that it’s hash algorithm provides a better distribution for typical values encountered by Antlr. By better I mean better than the standard hash functions that come with Java and C#. That said it could very well be that Swift Hasher is simply using it under the hood. Have you compared hash codes generated by Hasher and MurmurHash ?

**Comment by sharwell** [comment]
@ewanmellor Prior to the use of MurmurHash was the following:

https://github.com/sharwell/antlr4/blob/fc21b41afb93c197b8c371490c12bb1e87b72c87/runtime/Java/src/org/antlr/v4/runtime/atn/ATNConfig.java#L160-L168

We observed grammars and inputs in the wild where the prediction context graph had cycles of hash code values for its nodes, resulting in exponential time parsing. My guess is we were observing something similar to this:

https://twitter.com/vreshetnikov/status/862802737880211457

**Comment by ewanmellor** [comment]
@sharwell Yes, this kind of hash collision is exactly the kind of thing that the Swift team's work is trying to prevent.  They're also randomizing the hash seed so that you don't get the same collisions with each run (mitigating against deliberate hash collision attacks).

Do we have any tests that would expose hash collisions in particular?

**Comment by sharwell** [comment]
> Do we have any tests that would expose hash collisions in particular?

No.

**Comment by ewanmellor** [comment]
I'm going to file this one in the bucket labelled "possible future improvement (later)".
