### ISSUE TITLE
Antlrv4 failed installation

### ISSUE THREAD

**Issue by prashast** [antlr/antlr4#2422]
Hi, I was trying to test run the antlrv4 grammar and following the instructions as mentioned here https://raw.githubusercontent.com/antlr/antlr4/master/doc/getting-started.md . However, while trying to test the antlrv4 installation as given in the instructions I get the following error.
```
$ java -jar /usr/local/lib/antlr-4.7.1-complete.jar 
Error: Invalid or corrupt jarfile /usr/local/lib/antlr-4.7.1-complete.jar
```
My CLASSPATH is as follows:
```
$ echo $CLASSPATH
.:/usr/local/lib/antlr-4.7.1-complete.jar:
```
My JAVA JRE version is:
```
$ java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```
I've checked that my JRE installation is correct by running a sample hello-world jar file so my question is do I need an older runtime environment in order to run ANTLR or is there something that I am doing incorrectly? 

Also, as an additional piece of information I am running all of this inside Docker

Thanks!

**Comment by parrt** [comment]
must be a problem with the downloaded jar. ah. it all changed to https. try https not http.

**Comment by prashast** [comment]
Works fine now, thanks for the quick response!

**Comment by saeed-arian** [comment]
> must be a problem with the downloaded jar. ah. it all changed to https. try https not http.

I have the exact same problem, but I did not notice your solution.
Please give me more guidance.

**Comment by slasherM** [comment]
> must be a problem with the downloaded jar. ah. it all changed to https. try https not http.

nice!!!!

**Comment by shihanmax** [comment]
[](url)

> must be a problem with the downloaded jar. ah. it all changed to https. try https not http.

it helps!

**Comment by zhuwq585** [comment]
It helps~

**Comment by jackttj** [comment]
> must be a problem with the downloaded jar. ah. it all changed to https. try https not http.

thanks  bro
