### ISSUE TITLE
Introduce semantic versioning for ANTLR releases

### ISSUE THREAD

**Issue by reavertm** [antlr/antlr4#2425]
Please introduce some semantic versioning for ANTLR releases. At the moment ANTLR versioning seems fairly random, with major behaviour breaking features introduces for instance between 4.7. and 4.7.1

Some example proposed versioning scheme: _major_._minor_._patch_, where
_major_ - indicate ENBF grammar or other major changes
_minor_ - indicate new features and fixes, impacting generated code but with the same EBNF
_patch_ - fixes and improvements that are drop-in compatible within the same _major_._minor_

**Comment by parrt** [comment]
Yep, sorry. it's due to huge lag between releases. This project is no longer my focus. sorry.
