### ISSUE TITLE
loading js runtime in browser with new Tarp.require

### ISSUE THREAD

**Issue by rimmartin** [antlr/antlr4#2436]
Hi,
Instead of using the require.js version you have included in github at https://github.com/antlr/antlr4/blob/master/runtime/JavaScript/src/lib/require.js I add [tarp.require](https://github.com/letorbi/tarp.require) which is an upgrade by the same author.
```
yarn add letorbi/tarp.require
yarn add antlr4
```
tarp.require is capable of asynchronous loading and also allows me to use for other projects in same app.
```
var require = Tarp.require;
var antlr4 = require({main: './antlr4/index', sync: true});
var scad = require({main: './scad/index', sync: true});

//get File object file from drag & drop
...
           //Initialize the FileReader object to read the scad file
            var fileReader = new FileReader();
        let promise = new Promise((resolve, reject)=>{
            fileReader.onload = function (e) {
                var worker = new Worker("AntlrWorker.js");
            var stream = antlr4.CharStreams.fromString(fileReader.result);
            var lexer = new scad.SCADLexer.SCADLexer(stream);
            var tokens = new antlr4.CommonTokenStream(lexer);
            var parser = new scad.SCADParser.SCADParser(tokens);
            parser.buildParseTrees = true;
            var listener=new pmc.AntlrParserListener(parser);
            parser.addParseListener(listener);
            var tree = parser.scad();
                ///open to work with parse results viewStylish(tokens, lexer, parser, tree);
                resolve("completed.");
            }
            fileReader.readAsText(file);
        }).then((result)=>{
          console.log(result);}, (err)=>{console.log('err: '+err);
        });

```
Will test more with the asynchronous way

**Comment by ericvergnaud** [comment]
@rimmartin thanks for this. 
The current require is strictly speaking not part of the runtime, and only made available as a convenience, with Torben's agreement.
May I ask that you to get additional approval from Torben to achieve the same with tarp.require.
You could then add it to the repo, and update docs accordingly, through a PR?

**Comment by rimmartin** [comment]
Sure @ericvergnaud,  I'll look into it, talk with Torben, test more on the asynchronous capability an set up a PR

**Comment by ericvergnaud** [comment]
'require' is no longer required
