### ISSUE TITLE
[Java] greedy loop missing final char gets infinite loop

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#2444]
[Bug reported in plugin](https://github.com/antlr/intellij-plugin-v4/issues/333) is actually an antlr error as reported by @bjansen.

```
grammar crash;

TEXT_LITERAL :
    '"' ~( '\\' | '"' | '\r' | '\n' )* '"'
    ;

IDENTIFIER :
    ('a'..'z')+
    ;

EQ:
    '='
    ;

OTHER:
    ~('{'|'}'|'<'|'>')*?
    ;


attribute:
    IDENTIFIER (EQ attribute_value)?
    ;

attribute_value:
    TEXT_LITERAL
    | LCURL IDENTIFIER RCURL
    ;
```

**Comment by sharwell** [comment]
Can you clarify which of the following is occurring:

1. The lexer is producing a sequence of zero-length tokens but not making progress in the input
2. The parser is failing to consume tokens

The former is likely related to #691.

**Comment by parrt** [comment]
It would appear that dropping the final `"` of `name="value"` causes it to go bezerk.  From @bjansen, it looks like it's creating an infinite number of tokens via while trying to fill the token buffer:

```
$ antlr crash.g4
warning(146): crash.g4:15:0: non-fragment lexer rule OTHER can match the empty string
warning(125): crash.g4:26:6: implicit definition of token LCURL in parser
warning(125): crash.g4:26:23: implicit definition of token RCURL in parser
$ javac crash*.java
$ grun crash attribute crash.txt
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.antlr.v4.runtime.CommonTokenFactory.create(CommonTokenFactory.java:70)
	at org.antlr.v4.runtime.CommonTokenFactory.create(CommonTokenFactory.java:16)
	at org.antlr.v4.runtime.Lexer.emit(Lexer.java:245)
	at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:156)
	at org.antlr.v4.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:169)
	at org.antlr.v4.runtime.BufferedTokenStream.fill(BufferedTokenStream.java:485)
	at org.antlr.v4.gui.TestRig.process(TestRig.java:174)
	at org.antlr.v4.gui.TestRig.process(TestRig.java:166)
	at org.antlr.v4.gui.TestRig.main(TestRig.java:119)
```

Bastien reports "Yourkit shows that 4 million instances of ErrorNodeImpl and CommonToken were instantiated."

I think it must be the lexer getting stuck and constantly returning tokens, long before he gets to the actual parse phase.

**Comment by sharwell** [comment]
This is a bug in the grammar, not ANTLR. The following warning reports the possibility of a runtime infinite loop:

> warning(146): crash.g4:15:0: non-fragment lexer rule OTHER can match the empty string

**Comment by parrt** [comment]
oh wow. I was not paying attention. Sorry, my brain is elsewhere. Closing.

**Comment by sharwell** [comment]
📝 ANTLR allows this case, because there are some users who have overridden the lexer's match operation to make state-change operations following a zero-length sentinel, and the state change causes the next token to *not* be a zero-length token. Static analysis of the grammar cannot conclusively identify these cases, so we leave it as a warning.
