### ISSUE TITLE
Poor performance of Javascript parser with recursive patterns

### ISSUE THREAD

**Issue by corvana-nbaker** [antlr/antlr4#2468]
We have a pretty simple grammar similar to javascript which supports nesting expressions recursively. In general the javascript parser is performing adequately. However, when large nested expressions are encountered our parse time can balloon to 15 seconds or more. e.g. FOO(BAR(BAZ("something"))). 

I have a trivial example demonstrating this problem here: https://github.com/corvana-nbaker/antlr4-example

I'm hoping someone will identify an issue with our grammar. If not maybe this can help optimize the javascript runtime. Profiling does show that much of the processing time is spent in .toString() calls as reported in https://github.com/antlr/antlr4/issues/2360

**Comment by KvanTTT** [comment]
Have you tried to replace the fragment 

```antlr
| CASE '(' expr ')'          #FunctionExpr
| CASE '(' expr ',' expr ')'          #FunctionExpr
| CASE '(' expr ',' expr ',' expr ')'          #FunctionExpr
| CASE '(' expr ',' expr ',' expr ',' expr ')'          #FunctionExpr
| CASE '(' expr ',' expr ',' expr ',' expr ',' expr ')'          #FunctionExpr
| CASE '(' expr ',' expr ',' expr ',' expr ',' expr ',' expr ')'          #FunctionExpr
| CASE '(' expr ',' expr ',' expr ',' expr ',' expr ',' expr ',' expr ')'          #FunctionExpr
| CASE '(' expr ',' expr ',' expr ',' expr ',' expr ',' expr ',' expr ',' expr ')'          #FunctionExpr
| CASE '(' expr ',' expr ',' expr ',' expr ',' expr ',' expr ',' expr ',' expr ',' expr ')'          #FunctionExpr
| CASE '(' expr ',' expr ',' expr ',' expr ',' expr ',' expr ',' expr ',' expr ',' expr ',' expr ')'          #FunctionExpr
```

with the following one:

```antlr
| CASE '(' expr (',' expr (',' expr (',' expr (',' expr (',' expr (',' expr (',' expr (',' expr (',' expr)?)?)?)?)?)?)?)?)? ')'          #FunctionExpr
```

Moreover, you should not escape `[` char inside `[]` interval here: https://github.com/corvana-nbaker/antlr4-example/blob/96626e8bb7c4f8b152caa25785c69292f3fb165d/antlr/Query.g4#L86

**Comment by corvana-nbaker** [comment]
Actrually those expanded case statements were something I was prototyping. Our stock grammer is just 
```
| FUNC_NAME '(' paramList? ')'          #FunctionExpr
```

**Comment by corvana-nbaker** [comment]
I've updated the grammar to reflect what we're using: https://github.com/corvana-nbaker/antlr4-example/blob/master/antlr/Query.g4

**Comment by ericvergnaud** [comment]
Would this conversation not benefit to more users on the google discussion group?

Envoyé de mon iPhone

**Comment by corvana-nbaker** [comment]
I'll post in the Google Group as well. Thanks!

**Comment by youkaichao** [comment]
@ericvergnaud  would you please have a look at #2463  ?

**Comment by ericvergnaud** [comment]
I have already

Envoyé de mon iPhone

**Comment by dingchaoyan1983** [comment]
how about this issue progress, I have a same performance issue

my G4 is
```
/** Taken from "The Definitive ANTLR 4 Reference" by Terence Parr */

// Derived from http://json.org
grammar Function;

functionG4
   : expression  #simpleFunction
   ;

func
   : funcName BR_OPEN args BR_CLOSE
   ;

funcName 
   : ID
   ;

args 
   : arg* (COMMA arg)*  ;

arg
   : expression
   ;

expression
   : BR_OPEN expression (OPERATOR expression)* BR_CLOSE #parenthesisExpression
   | MINUS expression #operatorExpression
   | expression MINUS expression #operatorExpression
   | expression OPERATOR expression (OPERATOR expression)* #operatorExpression
   | func #functionItem
   | ID #defaultItem
   ;

MINUS
   : '-'
   ;

OPERATOR
   : '+'
   | '*'
   | '/'
   | '>'
   | '>='
   | '<'
   | '<='
   | '='
   | '<>'
   | ':'
   | '^'
   ;

BR_OPEN
   : (' ')* '('
   ;

BR_CLOSE
   : ')' (' ')*
   ;

COMMA
   : ','
   ;

ID
   : (' ')* BASE_STRING (' ')* ((' ')* BASE_STRING (' ')*)*
   | (' ')+
   ;

BASE_STRING
   : [a-zA-Z_0-9.\u4e00-\u9fa5]+
   ;

// \- since - means "range" inside [...]
WS
   : [ \t\n\r] + -> skip
   ;
```

**Comment by ericvergnaud** [comment]
Hi
The place for support is the google discussion group 
Éric

Envoyé de mon iPhone

**Comment by KvanTTT** [comment]
@ericvergnaud let's close it since related PR is merged.
