### ISSUE TITLE
antlr4 can not handle number literals ?

### ISSUE THREAD

**Issue by anianj** [antlr/antlr4#2480]
```
grammar Schema;

struct:  .*?;
```

and test with `123`, it will end with 
line 1:0 token recognition error at: '1'
line 1:1 token recognition error at: '2'
line 1:2 token recognition error at: '3'

**Comment by ericvergnaud** [comment]
Hi,
Please get support from the google discussion group 
Éric

Envoyé de mon iPhone

**Comment by KvanTTT** [comment]
Because you declare only parser rule without lexer ones.
