### ISSUE TITLE
Make antlr4-maven-plugin thread safe

### ISSUE THREAD

**Issue by turbanoff** [antlr/antlr4#2494]
When I run build of our multi-module maven project with `-T 2` parameter (to build it in modules in parallel) I got warning from maven about antlr4-maven-plugin thread safety.

    [WARNING] *****************************************************************
    [WARNING] * Your build is requesting parallel execution, but project      *
    [WARNING] * contains the following plugin(s) that have goals not marked   *
    [WARNING] * as @threadSafe to support parallel building.                  *
    [WARNING] * While this /may/ work fine, please look for plugin updates    *
    [WARNING] * and/or request plugins be made thread-safe.                   *
    [WARNING] * If reporting an issue, report it against the plugin in        *
    [WARNING] * question, not against maven-core                              *
    [WARNING] *****************************************************************
    [WARNING] The following plugins are not marked @threadSafe in Alerts Api:
    [WARNING] org.antlr:antlr4-maven-plugin:4.7
    [WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
    [WARNING] *****************************************************************

Is it possible to make plugin thread safe?

**Comment by dantran** [comment]
I am having random failures my maven multi-threaded build and wonder if this plugin is thread-safe? even though it is not marked as threadsafe yet

**Comment by khmarbaise** [comment]
@dantran can you explain more in detail where those issue have occured?

**Comment by KvanTTT** [comment]
Can this issue be closed?
