### ISSUE TITLE
List Index out of Range

### ISSUE THREAD

**Issue by claytondaley** [antlr/antlr4#2513]
The code [here](https://github.com/antlr/antlr4/blob/master/runtime/Python3/src/antlr4/ParserRuleContext.py#L116) throws an `IndexError` if you attempt to access a node at `len() + 1`.  E.G. a list with `len()==2` has indexes 0 and 1.  If you attempt to access index 2, the `len()` check passes, but the index is not available.  The comparison operator needs to be `>` not `>=`.

**Comment by claytondaley** [comment]
Oops.  Fixed in master.

**Comment by ericvergnaud** [comment]
Hi
In the code you reference the operator is > so not sure what you mean.
Éric 

Envoyé de mon iPhone
