### ISSUE TITLE
Code generation ignores Directory.Build.props

### ISSUE THREAD

**Issue by mwpowellhtx** [antlr/antlr4#2518]
I sometimes define my ``RootNamespace``, for instance, in a solution level ``Directory.Build.props``. However, when I do this, code generated by *Antlr4* lands in a *project* namespace ignoring this property. Suspect that the project file *itself* is being digested instead of using Visual Studio engine project properties.

Workaround is to add ``RootNamespace`` at the project level. It's a minor issue, but I should be able to relay that via the ``.props`` avenue.

**Comment by sharwell** [comment]
Can you update your sample project to demonstrate this issue? The code generator should use `$(RootNamespace)` for the old project system, and for the new project system constructs the namespace from `RootNamespace` and the relative location of the grammar file:

https://github.com/tunnelvisionlabs/antlr4cs/blob/4874e010bafe828192b6bf436a2a7d02bab161ec/runtime/CSharp/Antlr4BuildTasks/Antlr4.CodeGenerator.DefaultItems.targets#L15-L20

**Comment by sharwell** [comment]
@mwpowellhtx I believe this issue is meant to be filed on [tunnelvisionlabs/antlr4cs](https://github.com/tunnelvisionlabs/antlr4cs) instead of here.

**Comment by mwpowellhtx** [comment]
Re-filed there, thank you.

**Comment by mwpowellhtx** [comment]
Ah, I see, thanks. So, basically, this:

```xml
<ItemGroup>
  <Antlr4 Update="CaseRegression.g4"/>
</ItemGroup>
```

**Comment by mwpowellhtx** [comment]
Problem resolved. I was able to chain the build properties together, which pull my root namespace into the projects.
