### ISSUE TITLE
[Swift] Upgrade runtime to Swift 5

### ISSUE THREAD

**Issue by ewanmellor** [antlr/antlr4#2524]
The Swift runtime needs some upgrades for Swift 5.

I have started this work here: https://github.com/ewanmellor/antlr4/tree/swift-5

So far, I have crashed the Linux Swift compiler and I'm seeing what might be severe performance issues :-(   It's not ready for primetime, anyway.  Watch this space.

**Comment by ewanmellor** [comment]
The Swift compiler bug is https://bugs.swift.org/browse/SR-10260.

I presume that this is a blocker for this upgrade, since it breaks the Linux Swift runtime so fundamentally.  We are therefore blocked on the Swift team.

**Comment by mackoj** [comment]
Hi @ewanmellor since it working on the most recent version on Swift(https://forums.swift.org/t/development-open-for-swift-5-0-1-for-linux/22583) on linux maybe we should move forward with this and propose a PR if you have one ?

**Comment by ewanmellor** [comment]
My Swift 5 branch is listed above.  It still crashes the Linux Swift compiler though, due to SR-10260 listed above.  This crash is in Swift 5.0.0 and 5.0.1 (but only on Linux).  See https://travis-ci.org/ewanmellor/antlr4/jobs/528608703 for example.

I also don't understand the performance issues, but I think that they are real.  Compare for example the test case execution times for TARGET=swift GROUP=PARSER between https://travis-ci.org/antlr/antlr4/jobs/534221786 (master, Xcode 10.1) and https://travis-ci.org/ewanmellor/antlr4/jobs/528608693 (my swift-5 branch, Xcode 10.2).  Those tests are approximately 50% slower.

You're welcome to use my branch if you want, but I don't see how we can merge it into master when it is such a backwards step.

**Comment by ewanmellor** [comment]
I have updated my Swift 5 branch: https://github.com/ewanmellor/antlr4/tree/swift-5

A member of the Swift compiler team has diagnosed SR-10260.  It is something that we can work around, and I have included that workaround as a separate changeset on that branch.

All the tests now pass on both macOS and Linux.  However, things are *much* slower on Swift 5 vs Swift 4.  I have not been able to identify the cause of this.

Here are some representative results from runs on Travis:

| Test name | Swift 4 elapsed secs | Swift 5 elapsed secs | Percentage worse |
|-----------|--------------|------------|----------|
| TestCompositeLexers | 2.566 | 10.363 | 303 |
| TestCompositeParsers | 27.336 | 83.551 | 205 |
| TestFullContextParsing | 26.775 | 82.821 | 209 |
| TestLeftRecursion | 205.434 | 581.553 | 183 |
| TestLexerErrors | 15.323 | 62.026 | 304 |
| TestLexerExec | 84.689 | 230.792 | 172 |
| TestListeners | 12.975 | 39.161 | 201 |
| TestParseTrees | 17.946 | 55.542 | 209 |
| TestParserErrors | 60.048 | 185.991 | 209 |
| TestParserExec | 65.482 | 203.035 | 210 |
| TestPerformance | 44.325 | 68.173 | 53 |
| TestSemPredEvalLexer | 11.236 | 41.553 | 269 |
| TestSemPredEvalParser | 47.37 | 145.609 | 207 |
| TestSets | 56.282 | 175.702 | 212 |
| TestCompositeLexers | 18.45 | 23.223 | 25 |
| TestLexerErrors | 96.443 | 152.613 | 58 |
| TestLexerExec | 243.922 | 488.279 | 100 |
| TestSemPredEvalLexer | 45.33 | 100.266 | 121 |
| TestSets | 210.961 | 399.81 | 89 |
| TestCompositeParsers | 124.424 | 173.555 | 39 |
| TestFullContextParsing | 126.376 | 184.46 | 45 |
| TestListeners | 60.749 | 89.495 | 47 |
| TestParseTrees | 57.322 | 136.617 | 138 |
| TestParserErrors | 273.395 | 423.437 | 54 |
| TestParserExec | 270.111 | 468.394 | 73 |
| TestPerformance | 86.237 | 134.946 | 56 |
| TestSemPredEvalParser | 172.352 | 309.155 | 79 |
| TestLeftRecursion | 796.629 | 1337.968 | 67 |

One difference between Swift 4 and 5 is the way that hashing works, with it now using `hash(into:)`.  I have tried two different approaches, one using `hash(into:)` directly and one using the `MurmurHash` implementation that we were using with Swift 4.  The performance difference between these two versions was minor, and nowhere near accounting for the difference between Swift 4 and 5.  You can see these two variants on https://github.com/ewanmellor/antlr4/tree/swift-5-testing

I don't have any other ideas as to what might be causing the performance problem.

I don't have any time to work further on this at the moment, so if someone wants to try and diagnose this, that would be great.

**Comment by 100mango** [comment]
@ewanmellor According: https://forums.swift.org/t/swift5-slower-than-swift4/27392
I found some NSString use cases in the Antlr Swift Runtime. How can I test the performance After I change the implementation?

**Comment by ewanmellor** [comment]
@100mango Sorry for the delay in replying; Antlr is not an active project for me at the moment.

I test performance by pushing to a branch and letting Travis run the tests.  The elapsed time for each test is printed out in the job log.  Of course, I am assuming that Travis has reasonably consistent performance between runs for this to be valid.

You can extract the performance numbers from the downloaded log file using:

    cat mylogfile.txt | tr -d '\r' | awk '/elapsed/ { sub(/^.*\./, "", $16); print $16" "$12; }' | sort


I have found places where `NSStringFromClass` was being used.  I have replaced those.  See cset 8a7ef73e8ba on my swift-5 branch and https://travis-ci.org/ewanmellor/antlr4/jobs/579277007.  That has helped performance a bit, but it hasn't entirely fixed the problem.  Did you find other uses of `NSString` operations?

**Comment by ewanmellor** [comment]
PR https://github.com/antlr/antlr4/pull/2686.

**Comment by ewanmellor** [comment]
@mackoj @100mango @mlilback: The ANTLR Swift backend has now been upgraded to Swift 5.1 on the master branch.  Please check it if you have time; @parrt is preparing for a new release.
