### ISSUE TITLE
Run "mvn install" in antlr4 project root first or check mvn settings

### ISSUE THREAD

**Issue by starFelix** [antlr/antlr4#2537]
when I run the command "python boot.py --gen-xcodeproj" (which located in antlr4/runtime/Swift), I got this error.
But when I run the command "mvn install", it said "mvn:command not found".
After I had installed maven, the common "mvn install" run failed.
so many errors likes "java.lang.RuntimeException: Could not locate python3.6" or "No such file or directory"

So anyone can tell me how to get the entire swift project easier? I just want the swift runtime not ohters.

**Comment by EugeniaYao** [comment]
Hi, I met the same issue as you. How did you fix this?
