### ISSUE TITLE
Non Javascript code generated for javascript target in building Java Lexer

### ISSUE THREAD

**Issue by wongjasont** [antlr/antlr4#2555]
In the current grammar (under grammars) of Java, when a (javascript target) parser is built with Antlr v4.7.2, the generated javascript code (Java9Lexer) contains the following:

```
Java9Lexer.prototype.JavaLetterOrDigit_sempred = function(localctx, predIndex) {
	switch(predIndex) {
		case 2:
			return Character.isJavaIdentifierPart(_input.LA(-1));
		case 3:
			return Character.isJavaIdentifierPart(Character.toCodePoint((char)_input.LA(-2), (char)_input.LA(-1)));
		default:
			throw "No predicate with index:" + predIndex;
	}
};
```

Obviously `Character.isJavaIdentifierPart(Character.toCodePoint((char)_input.LA(-2), (char)_input.LA(-1)));` is not javascript

**Comment by ericvergnaud** [comment]
Hi,

the place for support is the google discussion group.

Eric

**Comment by ROWEND36** [comment]
Just discovered this issue also

**Comment by ericvergnaud** [comment]
That's because the grammar contains Java code
