### ISSUE TITLE
ANTLRInputStream::getText is very slow in cpp runtime

### ISSUE THREAD

**Issue by ruichu** [antlr/antlr4#2556]
When I was using ANTLR4 for CPP, I found it VERY slow in ANTLRInputStream::getText.
The reason is that in std::string utf32_to_utf8(StringUtils.h)，the UTF32Converter is a local variable,  not a static one. 
And there exists a note:  // Don't make the converter static or we have to serialize access to it.

I have tried to change the code from:
UTF32Converter converter;
to:
thread_local UTF32Converter converter;

The performance is improved dramatically. I wonder if this revision is right. 

Thanks.

**Comment by ruichu** [comment]
@mike-lischke

**Comment by mike-lischke** [comment]
For small text input I see no real difference. For a moment the thread local variant was even a bit slower. What's the usual input size for your parser? If you like you can create a pull request with the necessary changes.

**Comment by ruichu** [comment]
Thank you @mike-lischke .

Actually in my scenario, each text is rather short (usually less than 20 bytes). But my syntax tree walker call 'antlr4::CommonToken::getText' many times, so it executes more than 1 minute on Windows. 

I found the reason is that the constructor of UTF32Converter is slow, and construct a UTF32Converter each time is unnecessary. So I simply change it from local to thread_local, the performance improved from 1 minute to about 2 seconds.

I wonder if such a revision makes sense, or has any hidden problems. Thanks.

**Comment by olowo726** [comment]
I think that I've encountered a similar issue which I think might be related. 

I recently migrated a ANTLR 4.7.2 project from Java to C++. I built the C++ runtime with Visual Studio Community 2019 which I also use for everything else in the C++ project. All my tests passes which shows that the parsing itself works the same for both targets. So far so good.

The actual parsing for C++ is about 5x slower than Java even though the C++ code is built with release configuration optimized for speed and Java is executed in Eclipse debug mode! Profiling shows that 44% is spent in ANTLRInputStream::getText():

My files are larger than @ruichu , about 500K. he I can provide the grammar and data to parse if needed.

Anyone who can provide some insight? @mike-lischke ?

**Comment by mike-lischke** [comment]
The problem described here is about calling `getText()` on a parse context, which involves the creation of a UTF32 converter (since all text internally is held as UTF32). I'm just waiting for an official pull request (with signed contributors.txt).

This function, however, is not called in the normal parsing process (unless you do that in an action or predicate).

**Comment by olowo726** [comment]
I've now tested @ruichu solution on my case and I've seen a great improvement, about 10x.

Just to make sure I've got it right: @mike-lischke you think this is a good solution which should be included in future releases and hence you're waiting for someone to create a pull request? I will gladly do it but it might take some time since I'm completely new on github and doesn't even know how to use git.

**Comment by mike-lischke** [comment]
@olowo726 That's great news. Glad this approach solves the issue. I haven't thought of using thread local storage for the converter (had a static instance which crashed when being accessed by multiple threads). So, yes, I think this is a very good solution and if someone creates the pull request I will gladly approve it. Don't forget to sign the contributors.txt file, if you haven't yet.

**Comment by olowo726** [comment]
@mike-lischke I've now submitted https://github.com/antlr/antlr4/pull/2596. However the check continuous-integration/travis-ci/pr fails in the Java target - which doesn't make sense at all since this change really doesn't affect the Java target. Please advise on how to proceed.

**Comment by mike-lischke** [comment]
Thanks for the PR. The failing java build seems to be an issue with Travis, not your patch. I restarted the Travis job, but it failed again with the same error. @parrt needs to have a look there. Otherwise the patch is fine and I approved it.

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/pull/2596
