### ISSUE TITLE
[Swift] Package manager support

### ISSUE THREAD

**Issue by mackoj** [antlr/antlr4#2557]
Hi,

Can you please consider providing an official ANTLR Swift runtime suitable for use from Swift Package Manager ?  Like this one https://github.com/Flight-School/SwiftAntlr4  which is non-official but working and not maintained.

Thanks,

**Comment by flying-turnip** [comment]
Afaik this could be done similarly to the way the [PHP runtime](https://github.com/antlr/antlr-php-runtime) has been separated into it's own repo. I am under the same requirements of using a swift package, and decoupling the swift runtime files from this repo would essentially make that happen, while requiring very little effort to do so.
