### ISSUE TITLE
Problems with lexical modes inside an imported grammar

### ISSUE THREAD

**Issue by giorgiofran** [antlr/antlr4#256]
Hi All,

 I'm dealing with a big lexer grammar, and I wanted to divide it into subGrammars through the import action.

But, it seems that you cannot split grammars into chunks if you use lexical modes (i.e. you cannot use modes inside the imported grammar).

The question is: is it a bug or is it like that by design?

Regards,
  Giorgio

**Comment by WalkerCodeRanger** [comment]
I would also like the ability to define tokens that exist in multiple modes.  Yes I know about using [-> type()](http://stackoverflow.com/q/15807322/268898).  Still it would be nice.  But rather than the import that @giorgiofran suggests,  I think a better syntax would be to be able to list multiple modes in a section.  For example:

     mode MODE1;
     // mode 1 tokens
     mode MODE2;
     // mode 2 tokens
     mode MODE1, MODE2;
     // tokens that exist in both mode 1 and 2

**Comment by lawley** [comment]
I'm looking at a simple(?) use case where the mode is only referenced by the imported lexer

**Comment by may-bee** [comment]
I would like to see this feature as well. Nevertheless, I tried the workaround with -> type() syntax, which blows up my grammar quite a lot. But the there seems to be an additional problem with this. -> type() semantics does not include the execution of token action of the origin token. Thus, you have to specify your token actions redundantly for each reused token.
Am I right or have I overseen anything related?

**Comment by sharwell** [comment]
> But there seems to be a follow-up issue with this solution as `-> type()` semantics does not include the execution of token action of the origin token. Thus, you have to specify your token actions redundantly for each reused token.

This is correct. This feature was actually added in #408, but we restored the original behavior for referenced rules in #428 because many grammars relied heavily on the original behavior and changing it would make upgrading difficult or impossible.

**Comment by may-bee** [comment]
Is there any chance to see such a feature in the next months? Can you estimate the development effort of a solution like @WalkerCodeRanger has shown some posts before?

**Comment by parrt** [comment]
It's a worthy feature to consider but unfortunately there could be some compatibility issues and also on focusing primarily on both fixing, updating the documentation, building plug-ins at the moment.

**Comment by niccroad** [comment]
I think the original comment by @giorgiofran is addressed by the change to resolve #160 above. Also the grammars posted during 2013 should work with this change (though I didn't try them).

Maybe this issue is now discussing something else however where tokens can now be shared between modes?

**Comment by Lorthiz** [comment]
I have the same outcome with the example from the book and with my own grammars. Will this issue be fixed? @sharwell  @parrt

**Comment by parrt** [comment]
Not sure it's a bug. More of a feature request that I don't have time to do. closing.
