### ISSUE TITLE
[Feature Request]: Support unicode category

### ISSUE THREAD

**Issue by studentmain** [antlr/antlr4#2563]
Support match unicode category by something like `\p{L}`.

See: #1196, antlr/grammars-v4#1426

Yes, we can just copy paste from [LexUincode.g4](https://github.com/antlr/grammars-v4/blob/master/stringtemplate/LexUnicode.g4), but it's 600 lines long. More than half of [JavaScriptLexer.g4](https://github.com/antlr/grammars-v4/blob/master/javascript/JavaScriptLexer.g4) is Unicode category definition generated from database.

And it's hard to manage, if unicode adds some new character, we need update copy pasted content in *all* .g4 files:
```bash
user@pc:~$ git clone https://github.com/antlr/grammars-v4.git
Cloning into 'grammars-v4'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 20505 (delta 3), reused 12 (delta 2), pack-reused 20485
Receiving objects: 100% (20505/20505), 20.50 MiB | 1.35 MiB/s, done.
Resolving deltas: 100% (10079/10079), done.
Checking out files: 100% (4716/4716), done.
user@pc:~$ cd grammars-v4/
user@pc:~/grammars-v4$ find | grep \.g4 | wc -l
260
user@pc:~/grammars-v4$
```

**Comment by sharwell** [comment]
@parrt I believe this is already supported. https://github.com/antlr/antlr4/blob/master/doc/lexer-rules.md#lexer-rule-elements

**Comment by parrt** [comment]
Yep, i believe we added couple years ago.
