### ISSUE TITLE
ANRLR4 generated Go target source uses undefined symbol "_input"

### ISSUE THREAD

**Issue by wangkuiyi** [antlr/antlr4#2566]
I tried to build the [HIveQL grammar file](https://github.com/apache/hive/blob/release-2.0.1/hplsql/src/main/antlr4/org/apache/hive/hplsql/Hplsql.g4) in Apache Hive 2.0.1.

I noticed two problems.  I solve the first one, but for the completeness of the description of this issue, I am recording it here -- there is a grammar rule target named `string` which conflicts with the name of Go type string. My solution is to rename the grammar rule target from `string` into `char_string` as in [this pull request](https://github.com/apache/hive/pull/654), which passed HIve's CI.

What is bothering me now is the second issue. When I run `go build` with the generated code, it complains that 

```
# sqlflow.org/sqlflow/parser/hivesql [sqlflow.org/sqlflow/parser/hivesql.test]
./hplsql_parser.go:4467:8: undefined: _input
./hplsql_parser.go:24587:9: undefined: _input
./hplsql_parser.go:26203:8: undefined: _input
./hplsql_parser.go:26204:4: undefined: _input
./hplsql_parser.go:26205:4: undefined: _input
./hplsql_parser.go:26206:4: undefined: _input
./hplsql_parser.go:26207:4: undefined: _input
./hplsql_parser.go:26208:4: undefined: _input
./hplsql_parser.go:34592:8: undefined: _input
./hplsql_parser.go:37616:11: undefined: _input
./hplsql_parser.go:37616:11: too many errors
FAIL	sqlflow.org/sqlflow/parser/hivesql [build failed]
```

I searched over Go source files in https://github.com/antlr/antlr4/blob/master/runtime/Go/antlr/ and found no symbol "_input" defined there too.

**Comment by xqqcoder** [comment]
i got the same error, how to fix it?

**Comment by 2exd** [comment]
i got the same error, how to fix it?

**Comment by KvanTTT** [comment]
This is because actions of the grammar are java-targeted but not go-targeted. It's not possible to use the grammar for Go. @parrt please close.

**Comment by 2exd** [comment]
> 

Thanks for your reply

**Comment by joint-song** [comment]
Hplsql.g4 file contains Java dependent semantic predications. You can edit this file then regen it to Go. I've tried it like this:
```java
_input.LT(1).getText().equalsIgnoreCase("IS")
```
to:
```golang
strings.EqualFold(p.GetTokenStream().LT(1).GetText(), "IS")
```
And you should contains `strings` package imported in .g4 like this:
```
@parser::header {
  import "strings"
}
```
