### ISSUE TITLE
Repeating tokens for x times

### ISSUE THREAD

**Issue by IdkGoodName** [antlr/antlr4#2577]
- [x] I am not submitting a question on how to use ANTLR
- [x] I have done a search of the existing issues to make sure I'm not sending in a duplicate

> **Note:** This is a suggestion for ANTLR4.

Currently, in ANTLR4, there is no other way to repeat token **x** times, other than typing `SomeToken SomeToken SomeToken ...`. This can be frustrating if you need to repeat token a lot of times and you need to either paste or type it out. Regex already has that thing, `[abc]{6}` - this matches either `a`, `b` or `c` 6 times. But Regex isn't parser generator, it's for matching things in text. I am suggesting having something similar to Regex's `{...}`.

> **Parse token few times**

Taking idea from Regex's `{...}`, there's a problem. ANTLR4 already uses `{...}`. Since ANTLR4 already uses it, we can take operator, instead of braces. We can use `@`(because `*` is already taken) and here's the syntax `Token @ x`. `'\\u' HexDigit @ 4` is equivalent to `'\\u' HexDigit HexDigit HexDigit HexDigit`.

> **Parse between x and y**

Regex also has ability to match item between **x** and **y**, by using `{x,y}`. Since we took operator, and not brackets, it might be less-readable if we use comma. Instead, we can use `-`, which isn't used anywhere in ANTLR4 as of now. Example of that is `Token @ 1 - 10`, which is equivalent to `Token | Token Token | Token Token Token | Token Token Token Token | Token Token Token Token Token...`. That's a big list right there. You'd ask, where's the usage of that? well, there are some places. For example, "extended unicode escape" can use it. `'\\u{' HexDigit @ 1 - 6  '}'`

----------------

Just like `*` and `+` can be used on anything, you could use `@` also on anything.

**Comment by HuangLiPang** [comment]
@IdkGoodName I am wondering why do you close the issue? Did you figure out how to repeat x times?

**Comment by KvanTTT** [comment]
> Token | Token Token | Token Token Token | Token Token Token Token | Token Token Token Token Token

It also can be written as

```g4
Token (Token (Token (Token Token?)?)?)?
```

Also, there are several similar issues on repository.
