### ISSUE TITLE
Unnecessary predicate calls with regex quantifiers 

### ISSUE THREAD

**Issue by jjbr** [antlr/antlr4#2578]
Consider the following lexer:
```
lexer grammar DemoLexer;

@lexer::header {
    import de.jocbe.test.demo.LexerHelper;
}

ABs         : ('a' | 'b') ('a' | 'b')* {LexerHelper.myPredicate2(getText())}? ;

CDs         : ('c' | 'd')+ {LexerHelper.myPredicate3(getText())}? ;
REST        : .+?;
```
and the input string `aabbbaXccdcc`.

I would expect the lexer to attempt to generate a token `ABs` with text `aabbba` and  then call `myPredicate2()` once (!) with `aabbba` as argument (afterwards proceeding depending on the return value of the predicate).

Instead, the predicate is called multiple times with inputs `a`, `aa`, `aab`, `aabb`, `aabbb` before finally the entire token text `aabbba` is passed to the predicate. The return value of the predicate seems to be ignored when only partial matches are passed to it, at least I cannot see any differences in behavior.

It appears to me as though these calls are unnecessary and hence a bug. This can become especially problematic when predicates are heavy-weight, potentially resulting in performance issues.

To demonstrate issue I have created a small demo project here, which you can execute with `mvn clean test`: https://github.com/jjbr/antlr-predicate-demo

**Comment by sharwell** [comment]
> It appears to me as though these calls are unnecessary ...

The lexer is allowed to call a predicate more times than necessary. It is also allowed to omit calls to the predicate if a different path will be chosen anyway.

> Instead, the predicate is called multiple times with inputs `a`, `aa`, `aab`, `aabb`, `aabbb` before finally the entire token text `aabbba` is passed to the predicate.

This is the behavior I would expect. The rule `ABs` can match all of the inputs you described, but only when the predicate is true. The lexer implementation is *allowed* to omit the calls to the predicate for shorter inputs (they would not be used when the predicate is true for a longer input), but it is not *required* to omit the calls.

**Comment by jjbr** [comment]
> The lexer is allowed to call a predicate more times than necessary. It is also allowed to omit calls to the predicate if a different path will be chosen anyway.
I see, didn't realize it was defined in that manner. How come the lexer may omit predicate calls but instead of must? Implementation complexity?

> My general recommendation is to use lexer modes or another strategy to eliminate the use of the predicate altogether, or relocate the predicate so it doesn't follow a wildcard.
In this situation, the predicate is used in a rule to tokenize a name. There are different types of names that require different lexing modes thereafter but the lexer has no knowledge about the names themselves (they are user-defined). Hence, the predicate is used to check an external database to determine the type of name (all name types are syntactically the same) and hence the mode the lexer has to switch into. So unless I am missing something, the first part of your recommendation does not seem applicable in this situation. How would you go about relocating the predicate? After all it is not known how long the names are and placing it in the rules that succeed the in this case `ABs` rule could mean having to place it at the start of a large number of different possible rules.

**Comment by sharwell** [comment]
> How come the lexer may omit predicate calls but instead of must? Implementation complexity?

It is a combination of implementation complexity, performance, and theory. Improvements to the ALL(*) prediction algorithm over time have produced some cases where dynamic disambiguation during lookahead eliminated the need to execute certain predicates. It's difficult to know exactly which predicates could be impacted in the future.

> How would you go about relocating the predicate?

I would remove the predicate altogether, and instead handle this case in a custom action that runs after the rule matches. Predicates run during lookahead, but actions only run when the rule matches.
