### ISSUE TITLE
How to get mixed type list from parser rule context ?

### ISSUE THREAD

**Issue by gp-wang** [antlr/antlr4#2579]
I defined a parser rule which can be a list of either type A or type B:

g4: 
`sectionContent : ( WHITESPACE* ( section | ( LINE_LITERAL NEWLINE ) ) WHITESPACE*  )* ;`

generated source: cpp
```
  SectionHeaderContext* sectionHeader();

  class  SectionContentContext : public antlr4::ParserRuleContext {
  public:
    SectionContentContext(antlr4::ParserRuleContext *parent, size_t invokingState);
    virtual size_t getRuleIndex() const override;
    std::vector<SectionContext *> section();
    SectionContext* section(size_t i);
    std::vector<antlr4::tree::TerminalNode *> WHITESPACE();
    antlr4::tree::TerminalNode* WHITESPACE(size_t i);
    std::vector<antlr4::tree::TerminalNode *> LINE_LITERAL();
    antlr4::tree::TerminalNode* LINE_LITERAL(size_t i);
    std::vector<antlr4::tree::TerminalNode *> NEWLINE();
    antlr4::tree::TerminalNode* NEWLINE(size_t i);

    virtual antlrcpp::Any accept(antlr4::tree::ParseTreeVisitor *visitor) override;
   
  };
```

Question: From the generated source, I see that I can get a list of LINE_LITERALs, I can also get a list of SectionContext. But what if the text being parsed is a mixed list of LINE_LITERAL and SectionContext? Isn't the information being lost during th parsing?

**Comment by ericvergnaud** [comment]
Hi,

the place for support is the google discussion group.

Eric
