### ISSUE TITLE
Visual Studio 2019 Antlr project gets error CS1061: 'string' does not contain a definition for 'compareTo' in CPP14Parser.cs

### ISSUE THREAD

**Issue by ed-evans** [antlr/antlr4#2581]
error CS1061: 'string' does not contain a definition for 'compareTo' and no accessible extension method 'compareTo' accepting a first argument of type 'string' could be found (are you missing a using directive or an assembly reference?)

I have used Nuget to install the Antlr4 packages on Visual Studio 2019. I have set up the project according to the instructions found at: https://tomassetti.me/getting-started-with-antlr-in-csharp/

When I build the project, I get the above mentioned error and the build fails.
The section of the code failing is:

	[RuleVersion(0)]
	public PurespecifierContext purespecifier() {
		PurespecifierContext _localctx = new PurespecifierContext(_ctx, State);
		EnterRule(_localctx, 314, RULE_purespecifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 2067; Match(Assign);
			State = 2068; _localctx.val = Match(Octalliteral);
			if((_localctx.val!=null?_localctx.val.Text:null).compareTo("0")!=0) throw new InputMismatchException(this);     <<<<<<<<<<<<<<<<<<<-----------
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

**Comment by ed-evans** [comment]
Turns out the generated code is incorrect. should not be 'compareTo' ... should be 'CompareTo;=' with a capital'C' instead of lower case 'c'/

**Comment by ericvergnaud** [comment]
Seems you are using the tunnelvisionlabs version, please close this issue and raise it on their repo.

**Comment by ed-evans** [comment]
Does the following look like I'm using tunnelvisionlabs version?
![antlr](https://user-images.githubusercontent.com/5665833/60350667-e0506080-9978-11e9-85d4-5c27fc7c9bf7.PNG)

**Comment by ericvergnaud** [comment]
Yes it does.

**Comment by sharwell** [comment]
@ed-evans Yes, those packages are from https://github.com/tunnelvisionlabs/antlr4cs.

The issue you are observing occurs because the grammar contains a predicate or action that calls `compareTo`. It's likely the grammar was originally written with Java in mind, and needs to be edited to use `CompareTo` (or `Equals`) for C# scenarios.

**Comment by aeroson** [comment]
Happens to me too, Iam using version downloaded here https://www.antlr.org/download/

**Comment by ericvergnaud** [comment]
Hi,

closing this issue since it doesn't belong here.
