### ISSUE TITLE
js parser unable to parse a succesfully tested grammar.

### ISSUE THREAD

**Issue by LaTrissTitude** [antlr/antlr4#2605]
Expected behaviour: parsing correctly various tested strings (succesfully tested using grun)
Actual behaviour: the js parser errors out seemingly randomly 
Generation Target: Javascript

test string used, snippet, and call graph of the testing results are in the attached zip file

`line 3:8 no viable alternative at input 'num3r4lcommand\n        \n' ErrorListener.js:53
    syntaxError ErrorListener.js:53
    syntaxError ErrorListener.js:69
    syntaxError ErrorListener.js:69
    notifyErrorListeners Parser.js:352
    reportNoViableAlternative ErrorStrategy.js:276
    reportError ErrorStrategy.js:137
    commandSequence TerminalParser.js:199
    commandSequence TerminalParser.js:192
    executeCommands Terminal.js:630
    <anonyme> Terminal.js:136
    jQuery 2
`

The error seems to happen at the very start of the  opening rule (commandSequence), at the analysis step, when a new commandSequence is expected.

I uploaded the grammar, the input text, and the resulting svg from my testing here:
[grammars.zip](https://github.com/antlr/antlr4/files/3418584/grammars.zip)

**Comment by ericvergnaud** [comment]
Hi
Currently travelling, not sure I can look into this before mid August 
Éric

Envoyé de mon iPhone

**Comment by ericvergnaud** [comment]
seems you need to support empty commands explicitly
please move this to the google discussion group
