### ISSUE TITLE
[C++][CMake] find_package() fails when the C++ runtime is make-install'ed

### ISSUE THREAD

**Issue by delins** [antlr/antlr4#2606]
I followed [README.md](https://github.com/antlr/antlr4/blob/master/runtime/Cpp/README.md) to compile and install antlr4 on Linux. I turned `ANTLR4_INSTALL` on in the `cmake` step and I left out the `DESTDIR` variable in the `make install` step. This results in the following directory with CMake files:
```
$ ls -l /usr/local/lib/cmake/antlr4
total 24
-rw-r--r-- 1 root root 1607 jul 25 20:27 antlr4-config-version.cmake
-rw-r--r-- 1 root root 7632 jul 25 20:27 antlr4-generator-config.cmake
-rw-r--r-- 1 root root 1138 jul 25 20:27 antlr4-runtime-config.cmake
-rw-r--r-- 1 root root 3235 jul 25 20:27 antlr4-targets.cmake
-rw-r--r-- 1 root root 1427 jul 25 20:27 antlr4-targets-release.cmake
```

I then followed [Antlr4Package.md](https://github.com/antlr/antlr4/blob/master/runtime/Cpp/cmake/Antlr4Package.md) to add antlr4 to my project. However, `find_package(antlr4-runtime REQUIRED)` fails: CMake can't find `antlr4-runtime`. This makes sense, given CMake's [Search procedure](https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure)

One solution is to follow CMake's advice in the error message:
```
Add the installation prefix of "antlr4-runtime" to CMAKE_PREFIX_PATH or set
  "antlr4-runtime_DIR" to a directory containing one of the above files.
```

But I'd say it's cleaner to give the `runtime` and `generator` packages each their own directory (or perhaps there's another way that I'm unaware of). Otherwise, could a warning about this issue be added to  [Antlr4Package.md](https://github.com/antlr/antlr4/blob/master/runtime/Cpp/cmake/Antlr4Package.md)? It's not much of a problem if you're a seasoned CMake user, but if you barely use it it's quite a hassle to debug (i.e. actually finding the root cause and not simply following CMake's advice).

**Comment by mike-lischke** [comment]
Yes, the given suggestion is probably the best solution here and I will add a note to the Antlr4Package.md file.

**Comment by Nic30** [comment]
I am suffering from similar issue.

There is antlr4 c++ runtime in linux repos. But it misses the .cmake files entirely. I was speaking with author of the package but I was not able to find any package which does have cmake files for reference.

https://packages.debian.org/sid/libantlr4-runtime-dev

This is may be a problem for a people which are using cmake.
I do not remember clearly but it seems to me that cmake files in 4.7.2 were not generated correctly.

I am just saying that for peoples which want to use version from debian repo, there is an extra senseless complication.

**Comment by mike-lischke** [comment]
The suggested changes have been merged to the antlr4 repo now. Please check and close this issue, if it is solved, thanks.
