### ISSUE TITLE
Python issue with import from typing

### ISSUE THREAD

**Issue by ImanHosseini** [antlr/antlr4#2611]
Python's **TextIO** used to be in **typing.io** so you would do:
```python
from typing.io import TextIO
```
Since Python 3.6, **TextIO** is now in **typing** directly so the above (which ANTLR does) would trigger an error, it should be changed to [for 3.6+]:
```python
from typing import TextIO
```
(also the underlying reason for https://github.com/antlr/antlr4/issues/2193)

**Comment by tsotnikov** [comment]
There is another `typing.io` in LexerFile that is not fixed: https://github.com/antlr/antlr4/blob/master/tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg#L759
