### ISSUE TITLE
'constant overflows int' after update to go1.13

### ISSUE THREAD

**Issue by 1xch** [antlr/antlr4#2640]
On update to go1.13, a package using generated code begins to error 

```
/home/o/go/src/github.com/antonmedv/expr/parser/gen/expr_parser.go:2231: constant 4228579072 overflows int
/home/o/go/src/github.com/antonmedv/expr/parser/gen/expr_parser.go:2249: constant 4228579072 overflows int
/home/o/go/src/github.com/antonmedv/expr/parser/gen/expr_parser.go:2300: constant 4228579072 overflows int
```

There was no problem previously until the update, i was using the expr package and have almost zero experience with the details this deep but thought it might be wise to post an issue here.

Possibly very related to #2433

:facepalm: installed wrong version of go1.13

**Comment by r3code** [comment]
Seems to be related https://github.com/golang/go/issues/33388

**Comment by r3code** [comment]
@1xch Whta wrong version did you install and what OS you use?
