### ISSUE TITLE
[Javascript] OOM with the result of toString

### ISSUE THREAD

**Issue by xiaoiver** [antlr/antlr4#2649]
I wrote a parser for our database dialect and I want to use it to parse SQL on frontend for formatting purpose. But when running it in browser：
![image](https://user-images.githubusercontent.com/3608471/65029615-a5a30680-d970-11e9-8afe-27ba33184193.png)

I have tried the solution provided in https://github.com/antlr/antlr4/pull/1854 which memorizes the result of `toString()`. It works for a simple SQL but failed with complex one.

Then I took a snapshot and found the real reason of OOM:
![image](https://user-images.githubusercontent.com/3608471/65029297-11d13a80-d970-11e9-8176-93666dffb831.png)

And my question is should I simplify my parser or is there any improvement for `toString()` method?
```javascript
// PredictionContext.js
ArrayPredictionContext.prototype.toString = function() {
	if (this.isEmpty()) {
		return "[]";
	} else {
		var s = "[";
		for (var i = 0; i < this.returnStates.length; i++) {
			if (i > 0) {
				s = s + ", ";
			}
			if (this.returnStates[i] === PredictionContext.EMPTY_RETURN_STATE) {
				s = s + "$";
				continue;
			}
			s = s + this.returnStates[i];
			if (this.parents[i] !== null) {
				s = s + " " + this.parents[i];
			} else {
				s = s + "null";
			}
		}
		return s + "]";
	}
};
```

Here's my parse tree of following SQL:
```
SELECT `ename`, `deptno`, `sal`
FROM `emp`
WHERE `deptno`=(SELECT `deptno` FROM `dept` WHERE `loc`='NEW YORK')；
```
![antlr4_parse_tree_6](https://user-images.githubusercontent.com/3608471/65032857-8e671780-d976-11e9-8872-33273c59bb8c.png)

**Comment by ericvergnaud** [comment]
Hi,

please move this to the google discussion group.

Thanks

Eric

**Comment by xiaoiver** [comment]
Thanks，I moved it here：https://groups.google.com/forum/#!topic/antlr-discussion/qMJ0zcnwIZ4

**Comment by KvanTTT** [comment]
> please move this to the google discussion group.

Please recommend [github disccussions](https://github.com/antlr/antlr4/discussions) instead of google group since the latest one is outdated in fact. Official site agrees with me and it doesn't even has a link to the google group: https://www.antlr.org/support.html
