### ISSUE TITLE
C++ utf8_to_utf32 "bad conversion" exception for umlaut chars

### ISSUE THREAD

**Issue by mehecip** [antlr/antlr4#2656]
Hello,

I am using antlr 4.7.2 for C++.
I have build myself the runtime dll from Master with Visual Studio 2017(because of the massive improvement in multi-threaded operations since https://github.com/antlr/antlr4/commit/06cee866d2cfb506ba0b160f2f78092168a59eba)

The problem is the following:
- I have an input .txt file which contains text with umlaut (german) characters(e.g.: Kapazität - code \u00E4)
- I am reading the content of the file with std::ifstream into std::string
- I am passing the std::string to antlr4::ANTLRInputStream

At this point a "bad conversion" exception is thrown by ANTLRInputStream::load() => utf8_to_utf32() => converter.from_bytes().

As mentioned before, I am using  VS 2017, and it looks like due to some bugs in this version, a custom converter  is used. 

Some extra info:
If I read the file contents into std::wstring with std::wifstream and then convert from std::wstring to std::string with your std::string ws2s(std::wstring const& wstr) function , this issue does not occur. 

However, I do not want to do this, since the conversion from std::wstring to std::string is highly demanding( I am trying to parse files with  >> 1M lines and performance is at most important).

**Comment by mike-lischke** [comment]
I have a better idea for you: create your own input stream and derive from `ANTLRInputStream`. This gives you access to the protected `_data` member. Use that load your UTF-32 string directly without any conversion.

**Comment by mehecip** [comment]
@mike-lischke thanks for the hint. I'll give it a try.
