### ISSUE TITLE
Visual Studio crashes when using plsql grammar files

### ISSUE THREAD

**Issue by nikstuckenbrock** [antlr/antlr4#2660]
Hello there,

I'm trying to use the plsql grammar files I found [here](https://github.com/antlr/grammars-v4/tree/master/plsql). When I add the [PlSqlLexer.cs](https://github.com/antlr/grammars-v4/blob/master/plsql/PlSqlLexer.g4) to my project Visual Studio crahes and there is no way to open the project.
I added the [PlSqlBaseLexer.cs](https://github.com/antlr/grammars-v4/blob/master/plsql/CSharp/PlSqlBaseLexer.cs), [PlSqlBaseParser.cs](https://github.com/antlr/grammars-v4/blob/master/plsql/CSharp/PlSqlBaseParser.cs) and [CaseChangingFileStream.cs](https://github.com/antlr/antlr4/blob/master/doc/resources/CaseChangingCharStream.cs) before the grammar file.
I'm using Visual Studio 2015 and installed the following NuGet-Packages:
- Antlr4
- Antlr4.CodeGenerator
- Antlr4.Runtime

I'm not sure, but I suppose the following extract of the ActivityLog.xml from my Visual Studio refers to the error:
`Unexpected system error mode before loading package [Remote Control Service Package]`

I hope there is someone who can help me with this.
Thanks in advance.

**Comment by sharwell** [comment]
@nikstuckenbrock Please file your bug here and I can help you: https://github.com/tunnelvisionlabs/antlr4cs

**Comment by KvanTTT** [comment]
I think it may be related to inefficient memory management during concatenation because  PL/SQL parser is huge and contains a lot of string concatenations.

Maybe it's fixed by using of ropes in the upcoming release of .NET Core, see https://twitter.com/gafter/status/1161695828177645568
