### ISSUE TITLE
Weird error reporting: extraneous input '<EOF>'

### ISSUE THREAD

**Issue by marcospassos** [antlr/antlr4#2662]
We found a weird case where the default error recovery strategy reports the EOF token as being an extraneous token.

Grammar:
```antlr
grammar Test;

program
    : declarations? expression EOF;

declarations
    : declaration+;

declaration
    : 'let' declarator (',' declarator)* ';';

declarator
    : ID '=' expression ;

expression
    : ID
    | NUMBER
    | BOOLEAN
;

NUMBER: [0-9]+;
BOOLEAN: 'true' | 'false';
ID: [a-zA-Z_][a-zA-Z_0-9]*;
WS: (' ' | '\n' | '\r' | '\t')+ -> channel(HIDDEN);
```

Scenario:
```java
public class Test {
    public static void main(String[] args) throws Exception {
        CharStream input = CharStreams.fromString("let a = 1, b = ;\ntrue");
        TestLexer lex = new TestLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lex);
        TestParser parser = new TestParser(tokens);
        parser.program();
    }
}
```

Console output:
```
line 1:15 extraneous input ';' expecting {NUMBER, BOOLEAN, ID}
line 2:4 extraneous input '<EOF>' expecting {',', ';'}
```

I tracked down the method of the error recovery strategy that reports the EOF token as being extraneous. I believe the correct here would be to report a token mismatch rather than an extraneous token. 

I'd be glad to provide a PR if welcome, but I need some guidance on how to proceed.

**Comment by marcospassos** [comment]
@parrt, what's your opinion?

**Comment by parrt** [comment]
That does make sense, though it's kind ofScary to change the error recovery strategy. I think in this case there are two errors which is causing some confusion in the parser. What happens If you remove the extraneous `;`?  Do you get the correct error for EOF?

**Comment by marcospassos** [comment]
Humm, the `;` is not extraneous, as the `true` expression is required. As programmers, we know that what is missing is the value of `b`, but for the recovery heuristic it should either report an **a)** _extraneous `;` token_ followed by a _token mismatch EOF_ or  **b)** _no viable alternative_ (at `b = <here>;`).

Am I missing something here?

**Comment by parrt** [comment]
What if the input should be `let a = 1, b = \ntrue;`? in other words, what if the semicolon was an extraneous thing and you really meant true in there? (ignoring the `\n`)?

**Comment by marcospassos** [comment]
It's unlikely to be true as the expression part (`true`) is required.

For this grammar, these are valid interpretations:
```
let a = 1, b = <missing expression>; true
```
```
let a = 1, b =  true <missing ; and expression>
```
The construction `let a = 1, b = \ntrue;` is malformed as the expression is missing and cannot be followed by a semicolon.

(sorry if I misunderstood you again :)

**Comment by parrt** [comment]
ok, got it. thanks.  Hmm...well,If it's easy to do, perhaps send me the PR.  I'm just nervous it will mess up some common situations and it's hard to imagine all possible scenarios with so many users and applications.

**Comment by marcospassos** [comment]
I completely understand your point, but perhaps we can do something less error-prone. Once we now that `EOF` is never extraneous, is there any way to avoid this case only? [That's the point where things get messy] (https://github.com/antlr/antlr4/blob/master/runtime/Java/src/org/antlr/v4/runtime/DefaultErrorStrategy.java#L275). If you give me some guidance, I can fix it and submit a PR.

**Comment by parrt** [comment]
Yikes, We have to modify `reportUnwantedToken()`.   That terrifies me. Ha ha. What if you simply solve the problem in your case by overriding the default error handler, or even just making it work the way you want in your php version?

**Comment by marcospassos** [comment]
Yeah, we can fix it on our side, not a big deal. The motivation behind opening this PR is that whenever we find something which we believe to be an improvement, we always bring it up in the hope of helping other ANTLR users. But if your judgment is that the risk does not worth the benefit, we can keep it as is.

**Comment by marcospassos** [comment]
I am closing in favor of stability.

Thank you for your support, @parrt.
