### ISSUE TITLE
[C++] Parser & other types need to be retained

### ISSUE THREAD

**Issue by BSFishy** [antlr/antlr4#2664]
I am working on a project and I am trying to have a main "library" that allows you to parse a file or code then convert it into a more specialized AST. I've noticed, though, that the parser, lexer, and token stream all need to be retained whenever calling almost any function from antlr. My parse function used to look like this:

```c++
BrillParser::TopLevelContext *Brill::parse(std::istream &stream) {
    antlr4::ANTLRInputStream  input(stream);
    BrillLexer                lexer(&input);
    antlr4::CommonTokenStream tokens(&lexer);
    BrillParser               parser(&tokens);

    return parser.topLevel();
}
```

I am then able to call that function (`Brill::parse`) with a file stream to parse the file. Whenever I try to call a function on that returned context, though, I get a segmentation fault. Using valgrind, I deduced that it needed the parser, lexer, and token stream, all of which were deleted when the program left the context in the parse function. I was able to get around this by creating a struct that contains all of the necessary variables so that they are all retained no matter which scope it is in, but I don't feel that that is the *best* solution.

I don't know if this is the intended functionality, but I personally think that this is a relatively trivial problem that could be fixed.

**Comment by mike-lischke** [comment]
Yes, you are right, the token stream must be alive for the entire lifetime of the parser or you will get dangling pointers. However, it's your task to take care, not ANTLR4. Change your `BrillParser` class to keep local members of the input stream, the lexer, the token stream and the parser. On each parse run you can reset the parser etc. to take the new input into account. See the [parser module implementation in MySQLWorkbench](https://github.com/mysql/mysql-workbench/blob/8.0/modules/db.mysql.parser/src/mysql_parser_module.cpp#L198) for a way to do that.
