### ISSUE TITLE
Antlr4 maven plugin can't import grammar files in different directories

### ISSUE THREAD

**Issue by SteNicholas** [antlr/antlr4#2669]
@sharwell I haved already tried to import grammar files in different directories, but this didn't work.How coud I import grammar files in different directories?I created disscussion on [Antlr4 maven plugin can't import grammar files in different directories](https://groups.google.com/forum/#!topic/antlr-discussion/IUZ68ULJRgg)

**Comment by ericvergnaud** [comment]
Hi
The place for support is the google discussion group 
Eric

Envoyé de mon iPhone

**Comment by SteNicholas** [comment]
Where is google discussion group?Can you give url to access google discussion group?

**Comment by SteNicholas** [comment]
> Hi The place for support is the google discussion group Eric Envoyé de mon iPhone
> […](#)
> Le 14 oct. 2019 à 11:24, SteNicholas ***@***.***> a écrit : ﻿ I haved already tried to import grammar files in different directories, but this didn't work.How coud I import grammar files in different directories? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

@ericvergnaud Where is google discussion group?Can you give url to access google discussion group?

**Comment by sharwell** [comment]
I'm not sure if it's possible to do this.

@ericvergnaud we still need feature requests filed here, otherwise how will we know they exist?

**Comment by SteNicholas** [comment]
@sharwell I think this feature which helps developers reuse other directory g4 grammer files is very important.

**Comment by KvanTTT** [comment]
It's a feature but not a request for support. GitHub is the correct place for bugs and features.
