### ISSUE TITLE
Failing to report error with incomplete input

### ISSUE THREAD

**Issue by sergio-castro** [antlr/antlr4#2695]
Found this old [StackOverflow post](https://stackoverflow.com/questions/12190501/antlr-lexer-cant-lookahead-at-all) and just wanted to verify the status of this in ANTLR4 (the original issue was reported to appear in ANTLR3). 

In the post the author mentioned that given this rule:

`rule: 'aaa' | 'a' 'a';`

Using ANTLR3 it was not possible to parse the test: `aa`.

I see that this problem is gone in the latest ANTLR4 version, nice :)
For example, I can parse either `aaa`, or `aa`, or `aaaaa`. In the later case I obtain the expected output:

```
[@0,0:2='aaa',<'aaa'>,1:0]
[@1,3:3='a',<'a'>,1:3]
[@2,4:4='a',<'a'>,1:4]
[@3,6:5='<EOF>',<EOF>,2:0]
```

However, I think I have found some remaining issue to report. If I try to parse just the text `a`, I see an error, as expected:

```
[@0,0:0='a',<'a'>,1:0]
[@1,2:1='<EOF>',<EOF>,2:0]
line 2:0 missing 'a' at '<EOF>'
```

But if I parse `aaaa`, no error is reported and the output is just:

```
[@0,0:2='aaa',<'aaa'>,1:0]
[@1,3:3='a',<'a'>,1:3]
[@2,5:4='<EOF>',<EOF>,2:0]
```

As in the previous input (with just `a`), I believe I am missing the error message: 
`missing 'a' at '<EOF>'`

Is this a bug ?

**Comment by sharwell** [comment]
Since the start rule does not end with an explicit `EOF`, ANTLR is allowed to stop parsing before the end of the input in order to match a partial input. By definition, ANTLR should match the _longest successful subset_ (which is the entire input when possible), but there is a known limitation with the implementation (#118) so this is not always possible. The general recommendation is to always include an explicit EOF in the entry rule.

**Comment by sergio-castro** [comment]
But then why do I see a message: `line 2:0 missing 'a' at '<EOF>'` when my input is `a` ? I guess in this case ANTLR should also stop parsing in order to match a partial input? However, instead of that I see an error reported, which is a bit confusing.

**Comment by sharwell** [comment]
ANTLR is allowed to match a partial input, but it has to match the entire rule. There is no path to the end of `rule` that only has a single 'a'.
