### ISSUE TITLE
prep for next release

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#2698]
Howdy @ericvergnaud @mike-lischke @marcospassos @KvanTTT @ewanmellor @davesisson @sharwell It's that time of year again ;)  I'd like to cut a release in the next week or so. Could you start to finish off anything you want to sneak in for next release?

We're currently `4.7.3-SNAPSHOT` but I think 4.8 is more meaningful given new php target.

Ter

**Comment by ewanmellor** [comment]
I have four open PRs: #2599, #2604, #2637, #2686. 

The last of those is big: moving the Swift backend from Swift 4 to Swift 5.

**Comment by parrt** [comment]
@ewanmellor oh sorry! I'll merge those today. Please put `@parrt` on your PRs as I have push notifications turned off by default.

**Comment by parrt** [comment]
Ok, @ewanmellor merged 'em all :)

**Comment by mike-lischke** [comment]
There are 2 PRs waiting to resolve the usual conflict in the contributors.txt file and one is ready to merge for C++. I'll ping you from the pending 2 once they are resolved.

**Comment by KvanTTT** [comment]
Unfortunately, no updated from me this time :(

**Comment by parrt** [comment]
Looks like a build error with surefire-reports. Can somebody take a look? Maybe @ewanmellor as it's swift?

https://travis-ci.org/antlr/antlr4/jobs/622425298?utm_medium=notification&utm_source=email

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
.Running org.antlr.v4.test.runtime.cpp.TestListeners
.Compiler version is: Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode-10.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Building ANTLR4 C++ runtime (if necessary) at /Users/travis/build/antlr/antlr4/runtime-testsuite/target/classes/Cpp
.............................................................................................C++ runtime build succeeded
.....................Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 580.393 sec - in org.antlr.v4.test.runtime.cpp.TestListeners
Running org.antlr.v4.test.runtime.cpp.TestParserErrors
...................................................................................................................Tests run: 34, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 581.795 sec - in org.antlr.v4.test.runtime.cpp.TestParserErrors
Running org.antlr.v4.test.runtime.cpp.TestParseTrees
.................................Tests run: 10, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 164.146 sec - in org.antlr.v4.test.runtime.cpp.TestParseTrees
Running org.antlr.v4.test.runtime.cpp.TestParserExec
.................................................................................................................................................................................Tests run: 37, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 899.035 sec - in org.antlr.v4.test.runtime.cpp.TestParserExec
Running org.antlr.v4.test.runtime.cpp.TestFullContextParsing
..............................cat: target/surefire-reports/*.dumpstream: No such file or directory
```

**Comment by ewanmellor** [comment]
That's the C++ tests (TARGET=cpp) and they've timed out at 40 minutes.

(The *.dumpstream message is bogus, that's just trying to grab any test crashes, and there weren't any.)

**Comment by parrt** [comment]
ah. crap. ok, i guess we'll ignore that one.

**Comment by ewanmellor** [comment]
Yes, I'd write that off as a Travis issue.  Other recent builds are nowhere near that slow.

**Comment by parrt** [comment]
Ok,  @ericvergnaud @mike-lischke @marcospassos @KvanTTT @ewanmellor @davesisson, anything else need to get in before I make my own pass and start build process?

**Comment by parrt** [comment]
Ok,  @ericvergnaud @mike-lischke @marcospassos @KvanTTT @ewanmellor @davesisson, anything else need to get in before I make my own pass and start build process?

**Comment by ewanmellor** [comment]
Nothing else from me.

**Comment by ericvergnaud** [comment]
@parrt I've blessed a couple PRs, plus we have this code signing problem on C# target

**Comment by parrt** [comment]
@ericvergnaud cool. merged stuff, responded to question on [this](https://github.com/antlr/antlr4/pull/2632), and looks like this one needs a fix: https://github.com/antlr/antlr4/issues/2700#issuecomment-565793120

**Comment by Silvenga** [comment]
I can totally help with the strong naming issue (#2511). Is there a CI artifact I can try?

**Comment by ewanmellor** [comment]
@Silvenga This looks like the most recent nupkg if that's what you're looking for: https://ci.appveyor.com/project/parrt/antlr4/builds/29001902/artifacts

**Comment by Silvenga** [comment]
Thanks @ewanmellor - I can confirm that the strong name is now valid. 🎉 

```
> sn -Tp Antlr4.Runtime.Standard.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Public key (hash algorithm: sha1):
0024000004800000940000000602000000240000525341310004000011000000bddf0bb8b8f721
7b114cdc8402a1fec7f130d0ea8d9a87008aaae8b8889d51a14d1b024c790d83fa0729e37f0cf6
a5278ac50936f366778c232ced2b279fb99df660c11bb183bd5a58ec779fea9a29671550a170c4
a1e5eefe994afa170cf191984addc183344c5e6e5e3735630b6d7adf1628e9406c8e05421f87c3
c8b43585

Public key token is e78b2c5abd1fcb3f
```
```
> sn -v Antlr4.Runtime.Standard.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'Antlr4.Runtime.Standard.dll' is valid
```

**Comment by parrt** [comment]
Can anybody create a PR to fix the build? thanks!

**Comment by ericvergnaud** [comment]
Seems it was just a travis timeout, restarting the build fixed it

**Comment by ewanmellor** [comment]
@parrt The AppVeyor PHP tests were also broken (the PHP package has moved from 7.3 to 7.4).  I've submitted PR #2704.

My test of that looks like it should work, but it timed out at 60 minutes.  If the PR times out too, then we'll need to figure out how to break up or speed up the AppVeyor tests.  The previous passing run was 35 minutes though, so well under the timeout.

**Comment by parrt** [comment]
Ok guys, @ericvergnaud @mike-lischke @marcospassos @KvanTTT @ewanmellor @davesisson @sharwell , it looks like the continuous build systems have started passing. whew!  I'll try doing a trial release build locally to see if the instructions still work. hahah.

**Comment by parrt** [comment]
At of action on the stringtemplate4 front. waiting for that to settle so we can incorporate latest into ANTLR 4. anything else on antlr front or are we good to go?

**Comment by ericvergnaud** [comment]
all good here, happy new year!

**Comment by parrt** [comment]
@mike-lischke my windows VM is messed up. gotta reinstall. Is Visual Studio 2019 ok or do I need 2017 or something?

**Comment by mike-lischke** [comment]
Strange that the names do not match, but yes that should be corrected. And we should provide VS 2017 and VS 2019 binaries instead those for VS 2015. The solution files exist already, just the batch file has to be updated. I'll create a PR for that later today.

**Comment by parrt** [comment]
Here's what i see in that dir:

<img width="741" alt="Screen Shot 2020-01-03 at 11 13 14 AM" src="https://user-images.githubusercontent.com/178777/71743707-18e66080-2e1a-11ea-8862-e8808b06d588.png">

**Comment by mike-lischke** [comment]
There should be much more in that dir. But I have no way to check what's the normal content there. Can only judge from my Professional installation, so I'm a bit clueless now. If all fails I can send you the binaries I have created...

**Comment by parrt** [comment]
Yeah, I'm clueless for builds on this box. But, we need a solution where I can build w/o having to hassle you.  Anything else I can install (previous versions?) or perhaps give dir contents that will help?

**Comment by mike-lischke** [comment]
Previous version wouldn't help. It makes no sense to create pre-built libs for old VS releases. The only thing I see is that you fix your VS 2019 installation. We can of course also go without pre-built libs. People can easily build these libs with their own VS installation. That is necessary anyway to build any useful app with the ANTLR4 runtime.

**Comment by parrt** [comment]
ok, maybe we go without. All I did was install VS fresh but perhaps I didn’t click enough checkboxes as I didn’t have a lot of disk space.

**Comment by parrt** [comment]
Ok, i think i pushed 4.8 properly, with ST4.3.  Only thing I couldn't do was CSharp build. i messed up the appveyor thing. can anybody checkout the commit right before maven updated to 4.9-SNAPSHOT and kick off a build then send me .nupkg or whatever so i can upload?  C++ is missing windows prebuilt binary as well. thanks and great work everybody!

**Comment by parrt** [comment]
oops. @marcospassos i messed up php. you didn't tell me how to attach and i don' use submodules. now it's connected and i reset your 4.7.2 to 4.8 and pushed. problem is now code and maven think we're at 4.7-SNAPSHOT.  What is correct procedure?  Reset to 4.8.1-SNAPSHOT and republish?

**Comment by parrt** [comment]
Ugh. https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.8/antlr4-runtime-4.8.jar gets 404 even though the link is listed at https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.8.  Any ideas about maven?

**Comment by syhily** [comment]
https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/ 4.8 doesn't show here.

**Comment by parrt** [comment]
Ok, i give up until Monday. @marcospassos offered to help. I can't even get 4.8-1 to build w/o forcing tests to use 4.8. i hate build shit.

**Comment by parrt** [comment]
Wow. I think I did it right this time. Let's see if it propagates properly. Might be bug in sonatype.org as it had link but 404'd.  I also upload nuget package 4.8.

**Comment by danger89** [comment]
Please.. start using versioning in Go.

For example when using other tools like shellescape I get a nice version in my `go.mod` file. While in the case with antrl4 its a mess with commit hashes.
```go
go 1.14

require (
	github.com/alessio/shellescape v1.2.2
	github.com/antlr/antlr4 v0.0.0-20200225173536-225249fdaef5 
	github.com/stretchr/objx v0.2.0
	github.com/stretchr/testify v1.5.1
)

```

**Comment by KvanTTT** [comment]
@parrt please close since it's fixed
