### ISSUE TITLE
Can't load build/libparser.a as lexer or parser.

### ISSUE THREAD

**Issue by vifird** [antlr/antlr4#2707]
I'm using `c++` parser code(and runtime), and i dont know how to use `grun` with `c++`, i can use it fine with `java`.
The grammar is ok, the parser file is ok( i can use it to parse my code to ParserTree ), the problem may be the `object file` of parser. 
Here are my CMakeLists.txt:
```
include_directories(
  $ENV{ANTLR_RUNTIME}/include
)
include_directories(
  ${PROJECT_SOURCE_DIR}/src
)
# cpp files of parser
file(GLOB parser_files
  ${PROJECT_SOURCE_DIR}/src/grammar/*.cpp
)

add_library(parser ${parser_files} $ENV{ANTLR_RUNTIME}/lib/libantlr4-runtime.a)
# target_link_libraries(parser)
```
This will create `build/libparser.a`, then i run `grun build/libparser.a program -gui "var a=1;"`, error occured:
```
Can't load build/libparser.a as lexer or parser
```
The same error occured if i add `target_link_libraries(parser)` to CMakeLists.txt.

So what should be the type of the parser file? How could i generate it in c++?

**Comment by ericvergnaud** [comment]
Hi,
Support is on the google discussion group.

Envoyé de mon iPhone

**Comment by vifird** [comment]
@ericvergnaud Got it. [https://groups.google.com/forum/#!topic/antlr-discussion/OfxJMfB4UrI](https://groups.google.com/forum/#!topic/antlr-discussion/OfxJMfB4UrI)
