### ISSUE TITLE
cpp target: Lexer::setTokenFactory template function unusable

### ISSUE THREAD

**Issue by vinoski** [antlr/antlr4#2727]
The `Lexer` class provides the [`setTokenFactory` template function](https://github.com/antlr/antlr4/blob/master/runtime/Cpp/runtime/src/Lexer.h#L98-L101), but its function signature means that its body can't compile. The function is defined as follows:

    template<typename T1>
    void setTokenFactory(TokenFactory<T1> * factory) {
        this->_factory = factory;
    }

where [`this->_factory`](https://github.com/antlr/antlr4/blob/master/runtime/Cpp/runtime/src/Lexer.h#L34) is declared as a [`std::shared_ptr`](https://en.cppreference.com/w/cpp/memory/shared_ptr):

    Ref<TokenFactory<CommonToken>> _factory;

The function can't work because `std::shared_ptr<T>` provides no assignment operator from `T*`, nor does it provide an implicitly converting constructor from `T*` (i.e., its `T*` constructor is marked `explicit`). `Lexer` works with the default `CommonTokenFactory` only because it assigns its `_factory` using `CommonTokenFactory::DEFAULT`, which is a `shared_ptr` of the same type as `_factory`.

I believe `setTokenFactory` on `Lexer`, `Parser`, and `TokenSource` should be changed to the following signature:

    template<typename T1>
    void setTokenFactory(Ref<TokenFactory<T1>> const& factory);

and the implementation of `Lexer::setTokenFactory` should be:

    template<typename T1>
    void setTokenFactory(Ref<TokenFactory<T1>> const& factory) {
        this->_factory = std::static_pointer_cast<TokenFactory<CommonToken>>(factory);
    }

Because of the declared type of `Lexer::_factory`, it's necessary for the `factory` argument here to be convertible to a `std::shared_ptr<TokenFactory<CommonToken>>`.

**Comment by vinoski** [comment]
I've implemented the fix suggested in my previous comment, and it works fine. I can submit a PR for it if you'd like; just let me know.

**Comment by vinoski** [comment]
@mike-lischke any opinions on this problem?

**Comment by mike-lischke** [comment]
Yes, that makes a lot of sense. This has probably been slipped through my fingers, as it is never used anywhere. Please file a PR for it.

**Comment by vinoski** [comment]
Will do!

**Comment by vinoski** [comment]
Hi @mike-lischke I've submitted the PR as requested. Please have a look when you get a chance.
