### ISSUE TITLE
Python3 parser generation incorrect by ANTLR 4.7.1 and problem in Parser.py

### ISSUE THREAD

**Issue by gerrie-myburgh** [antlr/antlr4#2745]
ANTLR 4.7.1 is generating incorrect Python3 code for the grammer :
```
var_defs
locals [ varlist = [] ]
   : 'var' var_def ( ',' var_def )* ';' {print($varlist)}
   ;

var_def
   : v=VARIABLE ':' var_type {$var_defs::varlist.append($v.text)} 
   ;
```
The code generated for the parser is : 
```
...
self.state = 45
self.var_type()
getInvokingContext(1).varlist.append((None if localctx.v is None else localctx.v.text))
...
```
instead of : 
```
...
self.state = 45
self.var_type()
self.getInvokingContext(1).varlist.append((None if localctx.v is None else localctx.v.text))
...
```
When the getInvokingContext function is called then the following error pops up in Parser.py: ctx.ruleIndex is not defined.
```
    def getInvokingContext(self, ruleIndex:int):
        ctx = self._ctx
        while ctx is not None:
>>>>>> if ctx.ruleIndex == ruleIndex:
                return ctx
            ctx = ctx.parentCtx
        return None
```
I had to change it to:
```
    def getInvokingContext(self, ruleIndex:int):
        ctx = self._ctx
        while ctx is not None:
>>>>>> if ctx.getRuleIndex() == ruleIndex:
                return ctx
            ctx = ctx.parentCtx
        return None
```
I am using Python 3.8.1, vs code ANTLR4 grammer plugin. with ANTLR 4.7.1

**Comment by ericvergnaud** [comment]
Hi,

thanks for this.

Would you mind trying:
 - adding "self." to the corresponding stg here: line 587 & 588 tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg 
 - fixing the code here: line 445 in runtime/Python3/src/antlr4/Parser.py

Let me know how this goes

Eric

**Comment by Synesthesic** [comment]
Hi,

I had the same issue and changing Python3.stg and Parser.py fixed the problem.  I no longer have to manually change the generated code.

Thanks.
