### ISSUE TITLE
Feature Request: Specify interfaces for Context classes in rule options.

### ISSUE THREAD

**Issue by StochasticTinkr** [antlr/antlr4#2752]
Desired behavior:

input snippet:
```
myRule
options {
    contextInterfaces: MyFoo, MyBar
}
      : 'something'
```
output snippet:
```
    public class MyRuleContext extends ParserRuleContext implements MyFoo, MyBar {
```

Looking through the code generator, it seems there is some code in place to allow making the "FooParser.MyRuleContext" classes to implement various interfaces, however it appears that nothing calls the "`implementInterface`" on `StructDecl`.

**Comment by StochasticTinkr** [comment]
I've opened a pull-request for this feature. https://github.com/antlr/antlr4/pull/2753
Looking forward to feedback ;-)

**Comment by StochasticTinkr** [comment]
Thinking more about it, and this doesn't actually achieve what I want.  I'm going to close the PR for now, and think more about how to solve the actual problem I'm trying to solve.

**Comment by XenoAmess** [comment]
@StochasticTinkr I really need this feature....so please reopen.
thanks very much.
