### ISSUE TITLE
Typo in Java runtime documentation

### ISSUE THREAD

**Issue by XsongyangX** [antlr/antlr4#2759]
The ParseTreeWalker class has a typo the runtime documentation of the enterRule method. Here is the link to the docs: https://www.antlr.org/api/Java/index.html
![image](https://user-images.githubusercontent.com/10444460/75095456-de1fbf80-5562-11ea-8a4f-aee0d41cef8d.png)

**Comment by ericvergnaud** [comment]
Would you mind providing a PR?

**Comment by XsongyangX** [comment]
I don't really understand what the right formulation should be.

**Comment by ericvergnaud** [comment]
This was copied from the Java target, maybe you can check there?

**Comment by XsongyangX** [comment]
I found the doc entry in the [repository](https://github.com/antlr/antlr4/blob/225249fdaef5a1d6bdc3694ab0e1fc936cf7f527/runtime/Java/src/org/antlr/v4/runtime/tree/ParseTreeWalker.java#L37) but it displays the same thing. I don't think there is a correct formulation that is already written down, since the docs are automatically generated from the source code.

**Comment by ericvergnaud** [comment]
Fair enough.

What this is supposed to explain is the following sequence:
1° walker calls 'enterEveryRule(ctx)
2° walker calls rule specific 'enterRuleXXX'
3° this entire sequence (steps 1 to 5) is triggered for each child rule if any
4° walker calls rule specific 'exitRuleXXX'
5° walker calls 'exitEveryRule'

Original java doc is here:
https://github.com/antlr/antlr4/blob/master/runtime/Java/src/org/antlr/v4/runtime/tree/ParseTreeWalker.java
(you might want to also update other language targets)

**Comment by XsongyangX** [comment]
Thanks, I'll look into this. If I bump into problems, I'll post more here.

**Comment by XsongyangX** [comment]
Alright I made a pull request
