### ISSUE TITLE
pygrun to be included in antlr4-python3-runtime package 

### ISSUE THREAD

**Issue by ajilk** [antlr/antlr4#2792]
Would it be possible to include the `bin` folder in the Python runtime python package (for pygrun) when installing through `pip`?

**Comment by ericvergnaud** [comment]
hi,
not sure I'm able to commit supporting that tool.
Is it a problem to download it?

**Comment by ajilk** [comment]
Oh okay, no worries, I was able to download it. I thought it made sense for the command line tools to come with the package. Thanks!
