### ISSUE TITLE
Cannot deepcopy AST in Python

### ISSUE THREAD

**Issue by clinssen** [antlr/antlr4#2793]
First, my textfile is parsed to yield an AST. I then want to make several copies of this AST, and perform different manipulations on each individual copy. I tried to use 
```Python
import copy; copy.deepcopy(ast)
```
but this yields an error: 
```Python
TypeError: cannot serialize '_io.TextIOWrapper' object
```
because `_output` is set to wrap stdout:
```Python
 '_output': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
```
This comes from trying to copy a ```antlr4.Token.CommonToken``` instance inside my AST node class(es). stdout is assigned to ```_output``` in ```antlr4.Lexer```.

Perhaps I am missing a simple solution for making a copy of my AST, containing generated Tokens and Context etc. instances?

**Comment by ericvergnaud** [comment]
Hi,

please get support from the google discussion group

Eric

**Comment by clinssen** [comment]
I have solved this problem by manually adding a clone() method to each ASTNode class.
