### ISSUE TITLE
Is there an example that overrides getToken when emitting multiple tokens?

### ISSUE THREAD

**Issue by 0x8000-0000** [antlr/antlr4#2795]
https://github.com/antlr/antlr4/blob/a4c66dc863bb6d5de1daf2ecac59bf5342d8dd98/runtime/Java/src/org/antlr/v4/runtime/Lexer.java#L301 and https://github.com/antlr/antlr4/blob/a4c66dc863bb6d5de1daf2ecac59bf5342d8dd98/runtime/Java/src/org/antlr/v4/runtime/Lexer.java#L233 reference overriding getToken() but I can't find an example, and I find no references to this method from the rest of the runtime:

```
~/tools/antlr4$ git grep 'getToken()' runtime/Java/src/org/antlr/v4/runtime/
runtime/Java/src/org/antlr/v4/runtime/Lexer.java:       public Token getToken() { return _token; }
```

Are these comments wrong / obsolete?

**Comment by ericvergnaud** [comment]
Hi,

please get support from the google discussion group.

Eric
