### ISSUE TITLE
Error with Spark

### ISSUE THREAD

**Issue by march3032** [antlr/antlr4#2818]
My Enviroment:
    Eclipse oxygen2
    Spark version:2.3.0
    Scala  version:2.11.11
    JDK8
I'm trying operate a dataframe write to hive like this 
`179      DF`
`180     .write`
`181     .mode(SaveMode.Append)`
`182     .format("parquet")strong text`
`183     .saveAsTable("%s.deepev_TripDivide".format(dbName))`
But it seems like appear an error at line183 ,error description:
ANTLR Tool version 4.7 used for code generation does not match the current runtime version 4.5.3ANTLR Runtime version 4.7 used for parser compilation does not match the current runtime version 4.5.3Exception in thread "main" java.lang.ExceptionInInitializerError at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:84) at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:48) at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parseTableIdentifier(ParseDriver.scala:49) at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:393) at com.reachauto.bussiness.Trip.TripDivide2$.run(TripDivide2.scala:183) at com.reachauto.bussiness.Trip.StepTripDivide$.run(StepTripDivide.scala:18) at com.reachauto.main.main$$anonfun$main$6.apply(main.scala:88) at com.reachauto.main.main$$anonfun$main$6.apply(main.scala:85) at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) at com.reachauto.main.main$.main(main.scala:85) at com.reachauto.main.main.main(main.scala) Caused by: java.lang.UnsupportedOperationException: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with UUID 59627784-3be5-417a-b9eb-8131a7286089 (expected aadb8d7e-aeef-4415-ad2b-8204d6cf042e or a legacy UUID). at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:153) at org.apache.spark.sql.catalyst.parser.SqlBaseLexer.(SqlBaseLexer.java:1153) ... 12 more Caused by: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with UUID 59627784-3be5-417a-b9eb-8131a7286089 (expected aadb8d7e-aeef-4415-ad2b-8204d6cf042e or a legacy UUID). ... 14 more

But im not using antlr,so can anyone tell me what's wrong?
Have already tried put antlr-dependency(4.5.3)/(4.7) into pom.xml,but no use

**Comment by ericvergnaud** [comment]
Hi
Please move this to the google discussion group
