### ISSUE TITLE
C# target / SQL grammar. Having problems in base versus @base

### ISSUE THREAD

**Issue by jaoude** [antlr/antlr4#2825]
Hello,
I am using Antlr4 and generating C# targets for a SQL grammar.
The generated SqlParser contains code with the word .base  (in one location).
I have to manually change it to @base.
What is the proper approach to make sure that the generated .cs parser file, generates a .@base and not .base.
Kindest Regards

**Comment by ericvergnaud** [comment]
Hi, 

please move this to the google discussion group.

Eric

**Comment by jaoude** [comment]
Done.
Thanks
