### ISSUE TITLE
Module not found: Error: Can't resolve 'fs' in '/Users/Saravanan/projects/frontend/widgets/web/node_modules/antlr4'

### ISSUE THREAD

**Issue by saravanan10393** [antlr/antlr4#2852]
I am using antlr4 with javacript target since years, Now it is throwing error when i do a build using webpack
```
Module not found: Error: Can't resolve 'fs' in '/Users/Saravanan/projects/frontend/widgets/web/node_modules/antlr4'
```

It was working fine with webpack-4 with following [settings enabled](https://stackoverflow.com/questions/54754585/how-to-use-antlr-if-an-error-with-fs-occurs). But now with wbpack-5 it is throwing the error as above.

**Comment by ericvergnaud** [comment]
Smells like a webpack issue more than an antlr one...
How about checking webpack specs and submitting a PR to update the antlr docs?

Envoyé de mon iPhone

**Comment by toolgood** [comment]
Browser throws an error

require.js:178 GET http://localhost:8888/fs.js 404 (Not Found)


CharStreams.js
const fs = require("fs");

**Comment by ArtemeeSenin** [comment]
@ericvergnaud Maybe it is possible to optionally include char and file stream files? Not to force its inclusion in index.js if antlr is used on frontend

**Comment by ericvergnaud** [comment]
Suggest you stick to webpack 4 until webpack 5 provides an equivalent for the below config:

`   node: {
        module: "empty",
        net: "empty",
        fs: "empty"
    },
`

**Comment by namratha-b** [comment]
> I am using antlr4 with javacript target since years, Now it is throwing error when i do a build using webpack
> 
> ```
> Module not found: Error: Can't resolve 'fs' in '/Users/Saravanan/projects/frontend/widgets/web/node_modules/antlr4'
> ```
> 
> It was working fine with webpack-4 with following [settings enabled](https://stackoverflow.com/questions/54754585/how-to-use-antlr-if-an-error-with-fs-occurs). But now with wbpack-5 it is throwing the error as above.

hi @saravanan10393 ,
any update on this issue?

**Comment by kaiyoma** [comment]
Ah, there _is_ a solution for webpack 5, but for some reason it's not documented here. In your webpack config, add this:

```
resolve: {
  fallback: {
    fs: false
  }
}
```

**Comment by Ketler13** [comment]
@saravanan10393 if you're on webpack5 could you please try suggestion I added here - https://github.com/antlr/antlr4/pull/3414 ? Just modify manually package.json file in node_modules/antlr4 and check how it works?

**Comment by ericvergnaud** [comment]
Next release uses webpack 5, so closing this
