### ISSUE TITLE
ANTLR cannot generate Dart code as of version 4.8

### ISSUE THREAD

**Issue by SimpleZero** [antlr/antlr4#2878]
https://github.com/antlr/antlr4/blob/master/doc/dart-target.md

ANTLR cannot generate Dart code as of version 4.8

**Comment by ericvergnaud** [comment]
Dart target is not released yet.
Please close.

Envoyé de mon iPhone

**Comment by KvanTTT** [comment]
Dart target will be supported since 4.9 version: https://github.com/antlr/antlr4/pull/2728
