### ISSUE TITLE
Cannot use default TraceListener on .Net Runtime as it throws Null pointers

### ISSUE THREAD

**Issue by Marti2203** [antlr/antlr4#2893]
Code Generation Target : C# 4.8.0 Runtime
Hello, today I tried to do a simple tracing of a grammar and I constantly got NullReferenceExceptions. After poking around in the code for the TraceListener, I see that it has two constructors - one that accepts a parser and one that accepts a Text Writer as an output,  but never both... This implies that I have to either make my own Trace Listener which does exactly the same thing as the default one or use reflection to set a private readonly field as both the output TextWriter and Parser are such.
[Here is the code for the TraceListener](https://github.com/antlr/antlr4/blob/master/runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Parser.cs#L24-L58)

**Comment by ericvergnaud** [comment]
Hi,

can you submit a PR?

Eric

**Comment by Marti2203** [comment]
With a fix?

**Comment by ericvergnaud** [comment]
yes

**Comment by Marti2203** [comment]
Okay. I will make one tomorrow for it

**Comment by Marti2203** [comment]
Hi @ericvergnaud , I see that a lot of the code does not use the newer C# features, is it possible to add them or just do this fix?

**Comment by KvanTTT** [comment]
At least I think it makes sense to support different language versions. For instance, [ILSpy](https://github.com/icsharpcode/ILSpy) do this.

**Comment by Marti2203** [comment]
Okay, True. That I had not thought about, will push only the TraceListener change then.

**Comment by Marti2203** [comment]
#2934 Fixes this
