### ISSUE TITLE
The inline tokens are processed as explicite tokens

### ISSUE THREAD

**Issue by verbessern** [antlr/antlr4#2894]
In my test grammar:
```
document        : '"' (UNESCAPED | ESCAPE ('"' | 't' | ESCAPE))* '"';       
ESCAPE          : '\\';
UNESCAPED       : '\u0020'..'\u0021' | '\u0023'..'\u005B' | '\u005D'..'\uFFFF';  
``` 
the letter 't' is not recognized for my input `"string"` (with the quotes), even that `UNESCAPED` does cover it. When I change it to:
```
document        : '"' (UNESCAPED | LETTER_T | ESCAPE ('"' | LETTER_T | ESCAPE))* '"';  
LETTER_T        : 't';         
ESCAPE          : '\\';
UNESCAPED       : '\u0020'..'\u0021' | '\u0023'..'\u005B' | '\u005D'..'\uFFFF';  
```
For larger grammars this becomes a real issue, because I have to move every inline token as an explicit one, and that uglifies my grammar significantly, additionally because of the priority of the tokens, every explicit token starts to conflict with the other tokens, and the order starts to be important. Is there some elegant way to prevent this from happening?

**Comment by ericvergnaud** [comment]
Your 2 grammars are not equivalent which probably explains the difference in behaviour .
Please move this to the google discussion group.

**Comment by verbessern** [comment]
Would you like to share why the grammars are not equivalent?

**Comment by verbessern** [comment]
When I define the first grammar, that is perfectly valid grammar, the letter 't' is not parsed as expected. I find this to be an issue.

**Comment by ericvergnaud** [comment]
please move this to the google discussion group

**Comment by verbessern** [comment]
It seems that that is a popular thing: https://stackoverflow.com/questions/13779087/range-element-cannot-be-used-in-parser-rule and I'm not mistaking. Looks like its a 'feature' not an 'issue'.
