### ISSUE TITLE
[JavaScript runtime] Implementation of ArrayPredictionContext.prototype.equals is incorrect

### ISSUE THREAD

**Issue by ota-meshi** [antlr/antlr4#2902]
I checked that the JavaScript runtime is very slow compared to the Java runtime.
And I noticed that `ArrayPredictionContext.prototype.equals` rarely returns `true`.

Looking at the Java and JavaScript implementations, the Java implementation is comparing the array elements correctly, while the JavaScript implementation is comparing the array instances.

https://github.com/antlr/antlr4/blob/a4c66dc863bb6d5de1daf2ecac59bf5342d8dd98/runtime/JavaScript/src/antlr4/PredictionContext.js#L252-L253
https://github.com/antlr/antlr4/blob/be881fa6b91d1980936f8dcab902a9dc26ecd310/runtime/Java/src/org/antlr/v4/runtime/atn/ArrayPredictionContext.java#L76-L78

I think perhaps JS needs to be modified as follows:

```js
    return equalArrays(this.returnStates, other.returnStates) &&
        equalArrays(this.parents, other.parents);
```
We can also use `equalArrays` in `Utils.js`, but we also need to change `equalArrays` in `Utils.js` because `equalArrays` in `Utils.js` doesn't allow arrays of primitives.

**Comment by ota-meshi** [comment]
FYI, on my PC, the source code that took 10 seconds to parse was improved to less than 1 second after making this change.

**Comment by ericvergnaud** [comment]
Sounds promising, I’ll look into this next week

**Comment by ota-meshi** [comment]
Thanks for your comment! I'm looking forward to the results you look into this.

As additional information, I think that the cache existence judgment failed, the cache was not used, and it was always recalculated, but this change made it use the cache correctly, so it was faster.
