### ISSUE TITLE
[Python3] Large import time cost paid for inline unittests

### ISSUE THREAD

**Issue by rmcgregor1990** [antlr/antlr4#2909]
Hey,

The python3 antlr runtime spend a large proportion of its import load time importing `unittest`.
This can profiled with pythons newish `-X importtime` option.
[importtime.txt](https://github.com/antlr/antlr4/files/5215411/importtime.txt)

My on system it takes ~150ms to `import antlr4` and ~100ms of that time is spent importing `unittest`.
This seems to be like quite a high time cost to pay just the keep the tests inline with the source.

My current project involing creating a python command line tool, which utilises antlr, and I would ideally like to keep the startup time as low as possible.

Would you consider moving the unitests out of the source tree?

Cheers,
Rob

**Comment by ericvergnaud** [comment]
Hi,
sure please submit a PR

**Comment by rmcgregor1990** [comment]
Upon further investigation it appears the tests defined within the `src` tree files are not even run as part of you're test suite.
The only tests run are defined in `TestTokenStreamRewriter.py` in the `test` tree are ever evaluated.

I'll put together a PR.

**Comment by rmcgregor1990** [comment]
PR: #2911

**Comment by ericvergnaud** [comment]
Thanks

**Comment by ericvergnaud** [comment]
Are you already in the contributors list?
If not, you need to add yourself as part of this PR

Eric
