### ISSUE TITLE
ClickHouse parser Golang target doesn't compile

### ISSUE THREAD

**Issue by genzgd** [antlr/antlr4#2912]
With antlr 4.8:

Using the ClickHouse lexer and parser (https://github.com/ClickHouse/ClickHouse/tree/master/utils/grammar) and and the go language target, I ended up with a weird mixed line of Java and Go

`throw new RuntimeException("UNEXPECTED_CHAR=" + (func() string { if localctx.(*ErrContext).Get_UNEXPECTED_CHAR() == nil { return "" } else { return localctx.(*ErrContext).Get_UNEXPECTED_CHAR().GetText() }}()));`

at line 17718 of `clickhouse_parser.go`

Obviously throw new RuntimeException is not how you do things in Go.  I don't know if this is a know issue with golang generation or if there is some work around.

**Comment by ericvergnaud** [comment]
Hi,

please move this to the google discussion group.

Thanks

**Comment by KvanTTT** [comment]
You should rewrite this [Java-specific code](https://github.com/ClickHouse/ClickHouse/blob/master/utils/grammar/ClickHouseParser.g4#L588-L592) to Go.

**Comment by genzgd** [comment]
Oh, duh, I didn't even notice that in the g4 file.  Thanks so much!
