### ISSUE TITLE
Unable to generate dart code

### ISSUE THREAD

**Issue by cikelengfeng** [antlr/antlr4#2925]
```
ANTLR Parser Generator  Version 4.8
antlr -Dlanguage=Dart lib/advanced_comment_parser/AdvancedDartComment.g4
```
I get error:
error(31):  ANTLR cannot generate Dart code as of version 4.8

**Comment by cikelengfeng** [comment]
@lingyv-li Could you provide some suggestions?

**Comment by lingyv-li** [comment]
Thank you for reporting the issue. I think there isn't a release build made with Dart yet. The latest release 4.8 was made when the PHP target was added. @parrt can you please make a release in case you've forgot? Let me know if there's anything blocking.

Before that happens, can you try following [/doc/building-antlr.md](https://github.com/antlr/antlr4/blob/756e4da0087137bfc4a747bf5adf589118cdd1b7/doc/building-antlr.md) to build a snapshot jar based on latest master?

**Comment by cikelengfeng** [comment]
OK, I will try to build a snapshot on master.

**Comment by parrt** [comment]
@lingyv-li  I was waiting for things to settle down with some of the targets and also hoping people like @cikelengfeng  could give you some external feedback before we release :)

**Comment by lingyv-li** [comment]
That's reasonable, please take your time. Would you like me to update the Dart target readme noting that it's not in 4.8?

**Comment by parrt** [comment]
Well, not too many asking for it. we can just wait I guess.

**Comment by KvanTTT** [comment]
@parrt please close it
