### ISSUE TITLE
Preparing for 4.9 release

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#2932]
Howdy! @pboyer, @mike-lischke, @janyou, @ewanmellor, @hanjoes, @ericvergnaud, @lingyv-li, @marcospassos

We've got new DART target and es6 stuff to release. You've also had lots of interesting PRs related to the other targets.

Let's move towards a 4.9 release. What do we have outstanding that needs to go in?

Thanks!

**Comment by mike-lischke** [comment]
I have 2 PRs open for the C++ target. One is the small doc fix (#2923) and the other that cmake fix (#2913). Nothing else from my side.

**Comment by parrt** [comment]
Anybody else have stuff?

**Comment by ericvergnaud** [comment]
Give me a couple of days to go through the PRs

**Comment by ewanmellor** [comment]
I don't have any time available for this project at the moment, I'm afraid.  I haven't looked at any PRs since the last release.

**Comment by parrt** [comment]
No problem, @ewanmellor !

**Comment by marcospassos** [comment]
Nothing interesting happened to the PHP target recently. We intend to put some effort into performance in the next months, but nothing to be part of 4.9.

**Comment by adamwojs** [comment]
> Nothing interesting happened to the PHP target recently. We intend to put some effort into performance in the next months, but nothing to be part of 4.9.

Hi, when do you plan v4.9 release ? Maybe it's not too late for create PR solving #2709 :wink:

**Comment by lingyv-li** [comment]
Haven't heard anything abnormal with Dart target yet, I think there is nothing else for this release for Dart.

**Comment by parrt** [comment]
@adamwojs I'll wait to see if a PR pops up for #2709.  

@ericvergnaud: am I caught up with your PR merges?

**Comment by hanjoes** [comment]
@parrt PR #2901 #2809 #2819 and #2781 seem to have introduced non-intrusive changes and would be safe to merge if rebase looks good.

**Comment by parrt** [comment]
@hanjoes done!

**Comment by gkjpettet** [comment]
Absolutely amazing news on the new Dart target. Any idea of the timeframe until 4.9 is out? I'm absolutely desperate to use the Dart target for a new project I'm working on.

**Comment by parrt** [comment]
Hi @gkjpettet i'm stuck teaching at moment. a few more PRs and I guess we can call it quits

**Comment by gkjpettet** [comment]
@parrt Thanks, not just for responding but for the ANTLR project in general. I’ve only recently discovered it but it is a fantastic piece of work.

**Comment by parrt** [comment]
Ok gang.  @pboyer, @mike-lischke, @janyou, @ewanmellor, @hanjoes, @ericvergnaud, @lingyv-li, @marcospassos @davesisson  I think next week during the US Thanksgiving holiday I will try to push out 4.9. thanks for all your efforts.

**Comment by ericvergnaud** [comment]
Great!

**Comment by parrt** [comment]
ok, I'm starting now.  must swap all of the deployment knowledge back into my head from cold storage. haha

**Comment by parrt** [comment]
Okay I decided to not do a release candidate and just push out 4.9. it should be at maven now if you want to take a look at it. I'm working on updating the website and adding jars etc.  will build the individual targets next.

**Comment by parrt** [comment]
See https://github.com/antlr/antlr4/releases/tag/4.9

**Comment by parrt** [comment]
Ok, @lingyv-li  you will have to publish DART target as I don't have access.

 I'm waiting on appveyor to create a build for C#

**Comment by lingyv-li** [comment]
@parrt I have published 4.9.0. Your Google account parrt cs.usfca.edu should have admin access to the package. Please let me know if it doesn't work.

**Comment by parrt** [comment]
Ah. well, I don't have `pub` for dart on my command line, which is all the instruction I have written down. :(

**Comment by parrt** [comment]
@marcospassos  unfortunately it looks like I've screwed up this submodule thing again. here is what appveyor looks like:

```
Build started
git clone -q --branch=master https://github.com/parrt/antlr4.git C:\projects\antlr4-l7imv
git checkout -qf 954c5fab1c5abe4fa7c4241f7bfde48de7a9966b
Restoring build cache
Cache 'C:\Users\appveyor\.m2' - Restored
Cache 'C:\Users\appveyor\.nuget\packages' - Restored
Running Install scripts
git submodule update --init --recursive
Submodule 'runtime/PHP' (https://github.com/antlr/antlr-php-runtime.git) registered for path 'runtime/PHP'
Cloning into 'C:/projects/antlr4-l7imv/runtime/PHP'...
fatal: remote error: upload-pack: not our ref 6c0287e9a5be50d71578436aed99972ed23f73e0
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'runtime/PHP', but it did not contain 6c0287e9a5be50d71578436aed99972ed23f73e0. Direct fetching of that commit failed.
Command exited with code 1
```

**Comment by parrt** [comment]
Ok, somebody's going to have to build the C# package.  I literally can't get that unbelievable piece of shit appveyor to work. Has anybody but me noticed that none of the messages correspond correctly to the commits or whatever? all of them are nonsense:

<img width="810" alt="Screen Shot 2020-11-24 at 2 28 11 PM" src="https://user-images.githubusercontent.com/178777/100158601-4b99ad00-2e61-11eb-8548-344191409f01.png">

**Comment by parrt** [comment]
@marcospassos  can you check the php target? See errors here https://ci.appveyor.com/project/parrt/antlr4-l7imv/builds/36494430

```
ANTLR Tool version 4.9 used for code generation does not match the current runtime version 4.8 in C:\projects\antlr4l7imv\runtime\PHP\src\RuntimeMetaData.php on line 140
```

damn. seems the submodule shows:

    public const VERSION = '4.8';

**Comment by parrt** [comment]
@ericvergnaud  does this package look right?
[Antlr4.Runtime.Standard.4.9.0.nupkg.zip](https://github.com/antlr/antlr4/files/5599734/Antlr4.Runtime.Standard.4.9.0.nupkg.zip)

**Comment by marcospassos** [comment]
Just updated it. Can you update the submodule? It should work now.

**Comment by parrt** [comment]
hi! Sorry my brain can't handle submodules ;)

```
beast:master:~/antlr/code/antlr4 $ cd runtime
beast:master:~/antlr/code/antlr4/runtime $ cd PHP
(reverse-i-search)`pull': git pull origin master
beast:master⤓:~/antlr/code/antlr4/runtime/PHP $ https://github.com/parrt/tensor-sensor/issues/16
beast:master⤓:~/antlr/code/antlr4/runtime/PHP $ git submodule update --recursive
beast:master⤓:~/antlr/code/antlr4/runtime/PHP $ git submodule update --remote --merge # might only need this last one but do both
beast:master⤓:~/antlr/code/antlr4/runtime/PHP $ grep 4.8 src/RuntimeMetaData.php 
    public const VERSION = '4.8';
beast:master⤓:~/antlr/code/antlr4/runtime/PHP $ 
```

**Comment by marcospassos** [comment]
Weird
https://github.com/antlr/antlr-php-runtime/blob/c84f4b077b1ecf17a6465c6a442c370597578325/src/RuntimeMetaData.php#L54

**Comment by parrt** [comment]
I did a pull and i get it:

```
beast:master⤓:~/antlr/code/antlr4/runtime/PHP $ git pull origin master
From https://github.com/antlr/antlr-php-runtime
 * branch            master     -> FETCH_HEAD
Updating 62fd3c3..c84f4b0
Fast-forward
 src/RuntimeMetaData.php | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```
Up in main repo, do i need a commit again?

```
beast:master:~/antlr/code/antlr4 $ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   runtime/PHP (new commits, untracked content)
...
```

Hmm...same problem:

```
beast:master:~/antlr/code/antlr4 $ git commit -a -m "Update PHP Runtime to latest version"
[master 479091306] Update PHP Runtime to latest version
 1 file changed, 1 insertion(+), 1 deletion(-)
beast:master⤒:~/antlr/code/antlr4 $ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   runtime/PHP (untracked content)
```

**Comment by marcospassos** [comment]
Yep, you’ve to commit the submodule update

**Comment by parrt** [comment]
Status is clean in runtime/PHP though. Main repo is not clean.

I add runtime/PHP and then commit. still unclean:

```
	modified:   runtime/PHP (untracked content)
```

**Comment by parrt** [comment]
we had trouble last release too. beginning to think `cp -r` is our friend here.

**Comment by ericvergnaud** [comment]
Hi,

yes works for me.

Eric

**Comment by parrt** [comment]
Ok,  thanks to @marcospassos I now have the PHP thing updating properly using a fresh clone.   this now says 4.9: https://github.com/antlr/antlr-php-runtime/blob/c84f4b077b1ecf17a6465c6a442c370597578325/src/RuntimeMetaData.php#L54

Ooook.  so now I think I need to cut a 4.9 release branch emanating directly from when maven reset the number. Then get appveyor to kick off a build for that and then use that for nukpkg.

**Comment by parrt** [comment]
ok, I think i updated nupkg correctly, @ericvergnaud!  https://www.nuget.org/packages/Antlr4.Runtime.Standard/4.9.0

I guess i'm done again for awhile :)

**Comment by KvanTTT** [comment]
I guess it can be closed?
