### ISSUE TITLE
go: data race in dfa.go

### ISSUE THREAD

**Issue by happygiraffe** [antlr/antlr4#2940]
I recently observed a data race in a generated parser (while running my own tests under the thread sanitizer).

```
// Write, in dfa.go.
func (d *DFA) setS0(s *DFAState) {
	d.s0Mu.Lock()
	defer d.s0Mu.Unlock()
	d.s0 = s
}

// Read, in lexer_atn_simulator.go.
dfa := l.decisionToDFA[mode]

if dfa.s0 == nil {
  return l.MatchATN(input)
}
```

The problem is that `dfa.s0` is being accessed without a read lock.

**Comment by happygiraffe** [comment]
@minjoosur, many thanks for the fix!

I'm not sure how to add the `target:go` label to this issue? That way it may get noticed and reviewed.

**Comment by DavidGamba** [comment]
Recently @Joakker and @prnvbn offered to help with the Go target maintenance (see https://github.com/antlr/antlr4/issues/2504#issuecomment-832142223) hopefully they can take a look and review the PR.
