### ISSUE TITLE
NPE in DefaultErrorStrategy.notifyErrorListeners

### ISSUE THREAD

**Issue by asarkar** [antlr/antlr4#2957]
- [x] I am not submitting a question on how to use ANTLR
- [x] I have done a search of the existing issues to make sure I'm not sending in a duplicate

Given
```
grammar SemVer;

@header {
package com.asarkar.semver.antlr;
}

semVer : normalVersion (HYPHEN preReleaseVersion)? (PLUS buildMetadata)? ;
normalVersion : majorVersion DOT minorVersion DOT patchVersion ;
majorVersion : numericId ;
minorVersion : numericId ;
patchVersion : numericId ;
preReleaseVersion : preReleaseId (DOT preReleaseId)* ;
buildMetadata : buildMetadataId (DOT buildMetadataId)* ;
preReleaseId : alphanumericId
             | numericId
             ;
buildMetadataId : alphanumericId
                | digits
                ;
alphanumericId : (characters)? nonDigit (characters)? ;
numericId : ZERO
          | POSITIVE_DIGIT (digits)?
          ;
characters : character+ ;
character : digit
          | nonDigit
          ;
digits: digit+ ;
nonDigit : LETTER
         | HYPHEN
         ;
digit : ZERO
      | POSITIVE_DIGIT
      ;
ZERO : '0' ;
HYPHEN : '-' ;
DOT : '.' ;
PLUS : '+' ;
POSITIVE_DIGIT : [1-9] ;
LETTER : [a-zA-Z] ;
```
Error strategy:
```
object FailFastErrorStrategy : DefaultErrorStrategy() {
    override fun recoverInline(recognizer: Parser): Token {
        throw InputMismatchException(recognizer)
    }

    override fun recover(recognizer: Parser, e: RecognitionException) {
        val stack = recognizer.ruleInvocationStack
        val segment = stack[stack.size - 2]
                .split("(?=\\p{Upper})".toRegex())
                .joinToString(separator = " ") { it.toLowerCase() }

        throw IllegalArgumentException("Invalid $segment in: ${recognizer.tokenStream.text}")
    }

    override fun sync(recognizer: Parser) {}
}
```
Lexer:
```
class FailFastSemVerLexer(input: CharStream) : SemVerLexer(input) {
    override fun recover(e: LexerNoViableAltException) {
        throw e
    }

    override fun recover(e: RecognitionException) {
        throw e
    }
}
```

Parser:
```
val chars = CharStreams.fromString(input)
val lexer = FailFastSemVerLexer(chars)
val tokens = CommonTokenStream(lexer)
val parser = SemVerParser(tokens)
parser.errorHandler = FailFastErrorStrategy
return SemVerVisitorImpl().visit(parser.semVer())
```

throws NPE for input "1.0.0-a&^". The exception is `LexerNoViableAltException`, which falls in the last `else` block of `DefaultErrorStrategy.reportError`, and calls `notifyErrorListeners` with a `null offendingToken`. `notifyErrorListeners` blows up.

```
line 1:7 token recognition error at: '&'
unknown recognition error type: org.antlr.v4.runtime.LexerNoViableAltException

java.lang.NullPointerException
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:540)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:146)
```

**Comment by ericvergnaud** [comment]
hi, looks like you're using Kotlin, which we do not support.
Not sure if
 `object FailFastErrorStrategy : DefaultErrorStrategy()`
is a valid construct in the antlr context...

**Comment by asarkar** [comment]
> looks like you're using Kotlin, which we do not support.

What is there to support for Kotlin? The client code could be in any JVM language. A search for “DefaultErrorStrategy” shows that similar issues have been reported by Java clients before.

`object FailFastErrorStrategy : DefaultErrorStrategy()` is valid and the code works for input other than the one shown. Again, unless proven that there’s a problem, antlr doesn’t need to know about the client language.

You don’t have to take my word for it, feel free to try it in Java. IntelliJ can convert pasted code from Kotlin to Java, so you should be able to reproduce the problem fairly easily.

**Comment by ericvergnaud** [comment]
May I suggest that you prove that it does not work in Java?

**Comment by asarkar** [comment]
> you prove that it does not work in Java?

Unless you prove first that there's a Kotlin-specific problem, no, I'm not willing to waste my time.

**Comment by ericvergnaud** [comment]
Well since we don't support Kotlin not sure why I would do that.
Thanks for contributing back so kindly to a community that provides advanced software for free

**Comment by asarkar** [comment]
@ericvergnaud Apparently you're expecting people to bow and kiss your feet because you're "_providing software for free_". Well, no one asked you to; feel free to do something else with your time, and let someone else take your place.
