### ISSUE TITLE
Antlr c# cannot compile emoji "[\p{Emoji_Presentation}]"

### ISSUE THREAD

**Issue by ZeroxLim** [antlr/antlr4#2958]
// Following lexer will cause the compilation to throw 
EMOJI: [\p{Emoji_Presentation}];

Error:
AC0156: invalid escape sequence

Seem like \p is causing the problem.

Appreciate a swift respone.

**Comment by ericvergnaud** [comment]
Not reproduced with the official Antlr 4.8 for C#

**Comment by ZeroxLim** [comment]
Yes, this can be close. 
This issue happen on visual studio Antlr code generator package. Currently still at version 4.6.1 which doesn't support emoji.

Alternative solution:
Manually generate the c# code from intelij Antlr plugin.
