### ISSUE TITLE
ANTLR4 generates outdated JavaScript

### ISSUE THREAD

**Issue by octogonz** [antlr/antlr4#2959]
The [javascript-target.md](https://github.com/antlr/antlr4/blob/master/doc/javascript-target.md) documentation recommends to subclass the listener like this:

```js
class MyGrammarListener extends ParseTreeListener {
       
    constructor() {
        super();
    }
   
   enterKey(ctx) {}
   exitKey(ctx) {}
   enterValue(ctx) {}
   exitValue(ctx) {}
}
```

However, when I invoke ANTLR4 like this (using the sample [calculator.g4](https://github.com/antlr/grammars-v4/tree/master/calculator)):
```
antlr -o out -Dlanguage=JavaScript Calculator.g4 -visitor
```
...the generated listener is not an ECMAScript class:

```js
// This class defines a complete listener for a parse tree produced by CalculatorParser.
function CalculatorListener() {
	antlr4.tree.ParseTreeListener.call(this);
	return this;
}

CalculatorListener.prototype = Object.create(antlr4.tree.ParseTreeListener.prototype);
CalculatorListener.prototype.constructor = CalculatorListener;

// Enter a parse tree produced by CalculatorParser#equation.
CalculatorListener.prototype.enterEquation = function(ctx) {
};
. . .

```

It is an ES5 simulation of a class.  Thus it appears that I cannot create a subclass of `CalculatorListener` without first transpiling my source code to ES5.  This is inappropriate because my project targets Node.js which supports `class` syntax.

Am I doing something wrong? How do I get ANTLR4 to emit modern JavaScript?  Thanks!

**Comment by octogonz** [comment]
After some digging, it appears that this problem was already fixed in the `master` branch, but has not been released yet.  

However,  [the ANTLR4 documentation](https://github.com/antlr/antlr4/blob/master/doc/javascript-target.md#what-about-modules) has already been updated to show the modern JavaScript syntax (which does NOT work with the current release of ANTLR4).  

This is highly confusing, because the "Doc" menu on the https://www.antlr.org/ website links to the `master` branch. 

@parrt If `4.8.1` can't be shipped right away, maybe the website should be linked to a GitHub branch that shows accurate documentation?

**Comment by parrt** [comment]
Hoping to do 4.9 after semester ends. early dec 2020
