### ISSUE TITLE
antlr4 4.9.0 - ERR! Error: Cannot find module 'antlr4/index'

### ISSUE THREAD

**Issue by jantimon** [antlr/antlr4#2968]
antlr4 4.9.0 is causing the following error in my webpack build: `ERR! Error: Cannot find module 'antlr4/index'`

maybe its a duplicate of #2965 but unfortunately I don't speak chinese..

In 4.8.0 the index file was directly at root:
https://unpkg.com/antlr4@4.8.0/index.js

In 4.9.0 the index file is now in the src folder:
https://unpkg.com/antlr4@4.9.0/index.js

That's a breaking change and according to the npm guidlines it must be released as 5.0 instead of 4.9 - otherwise many packages are broken

yarn & npm follow semantic versioning:

> 
> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards compatible manner, and
> PATCH version when you make backwards compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

all packages which use `"antlr4": "^4.8.0"` as a dependency will automatically install 4.9.0 and break

It breaks my dependencies because they are importing antlr4 like this: `var antlr4 = require('antlr4/index');` 

Broken Packages:

- https://github.com/adobe/htlengine/blob/ffcfeecc1d60e0f8f47c15be68ce794a8620b6d6/src/parser/generated/SightlyLexer.js#L3
- https://github.com/asbjornh/json-parser/blob/2665a97823a9d8e3f67d372d42f021b58753eb97/lib/jsonParser.js#L3
- https://github.com/RicardoGeek/lua-antlr/blob/a9a687b2150ffec3e855ee2f1471d47b17d81cf2/LuaParser.js#L3
- https://github.com/tagomaru/truffle-sca2t/blob/531d91074359f52e24d8f66b911a47d758b6a28f/packages/truffle-sca2t-eventgen/lib/SolidityParser.js#L3
- https://github.com/asbjornh/math-parser/blob/017d75a9d827fb1cd209330d456fa0b02df5b662/lib/mathParser.js#L3
- and [many many more](https://github.com/search?l=JavaScript&q=%22antlr4%2Findex%22&type=Code)

Can you please revert that change or place an additional index.js in the root with the following content: `module.exports = require('./src/index')`? I added a pr for that here: #2969

**Comment by cmoesel** [comment]
Same here, but I will add it also breaks other imports like:
```ts
import { ErrorListener } from 'antlr4/error';
```
... so just adding the `index.js` is not likely enough.  If they really wanted to ensure nothing breaks, they'd have to mirror the whole directory structure of the 4.8.0 module.

On a related note, the [@types/antlr4](https://www.npmjs.com/package/@types/antlr4) TypeScript definitions also all expect the _old_ layout and now are also broken.  But that's probably worth its own issue.

**Comment by jantimon** [comment]
@ericvergnaud says he doesn't care: #2968

**Comment by ericvergnaud** [comment]
I do care, but it's ultra easy to fix on consumer side (by removing ^).
There was never a commitment from Antlr to stick to the npm recommendation.
Rather Antlr favors versioning consistency _across_ targets over semantic versioning _within_ each target.
As of writing, we have 10 runtimes consistent with each other.
So sorry about the inconvenience but we are not reverting this change.

**Comment by jantimon** [comment]
Maybe you don't understand that it is not only changing a `^`..

If you use a npm module wich is using your module as a subdependency than also this npm module is broken..

For those cases it is really hard to resolve and providing 1 line of code could fix it until your next major release

Why don't you want to help us if it is only one line of code to add?

**Comment by ericvergnaud** [comment]
How about the following:

"resolutions": {
  "antlr4": "4.8.0"
},
"scripts": {
  "preinstall": "npx npm-force-resolutions",
  ...
}

**Comment by carocad** [comment]
afaik both npm and yarn allow developers to manually overwrite the deep-dependency resolution without having to wait for the direct dependency to release a new version. It is the same mechanism used to solve security issues with `npm audit fix`. See [here](https://ankurkaushal.com/update-dependency-package-lock/) for an overview of how to do that.

**Comment by manian-kumaran** [comment]
Does this mean that this issue won't be fixed and developers who use antlr4 will be stuck with 4.8.0?

**Comment by ericvergnaud** [comment]
No, it means one of the following:
 - if you have a direct dependency on ANTLR, you need to use nodejs >=14 and ES6 module semantics 
 - if you have an indirect dependency on ANTLR, you need to force usage of 4.8 until they migrate to 4.9
 - if you have both and want to use 4.9, you probably need to hack a bit until they migrate to 4.9
