### ISSUE TITLE
[JavaScript] 4.9.0 regression

### ISSUE THREAD

**Issue by GordonSmith** [antlr/antlr4#2975]
Generated code (in lexer, parser, visitor etc.) is producing:
```
var antlr4 = require('antlr4/index');
```

But looks like npmjs antlr4 package has been refactored and the generated code should be:
```
var antlr4 = require('antlr4/src/antlr4/index');
```

**Comment by GordonSmith** [comment]
Note - I don't believe this is a duplicate of https://github.com/antlr/antlr4/issues/2968 as this is the generated code from antlr4 and NOT code in my application.

**Comment by ericvergnaud** [comment]
Starting with 4.9, the generated code is:
`import antlr4 from 'antlr4';`
 So you're probably referring to code generated from previous versions.

**Comment by GordonSmith** [comment]
@ericvergnaud - you are correct I was generating with an older version of antlr4
