### ISSUE TITLE
possibly a typo on https://github.com/antlr/antlr4/blob/master/doc/getting-started.md

### ISSUE THREAD

**Issue by msgoff** [antlr/antlr4#2976]
I think .jar.jar should be replaced with .jar

$ export CLASSPATH=".:/usr/local/lib/antlr-4.9-complete.jar.jar:$CLASSPATH"

It's also a good idea to put this in your .bash_profile or whatever your startup script is.

    Create aliases for the ANTLR Tool, and TestRig.

$ alias antlr4='java -Xmx500M -cp "/usr/local/lib/antlr-4.9-complete.jar.jar:$CLASSPATH" org.antlr.v4.Tool'
$ alias grun='java -Xmx500M -cp "/usr/local/lib/antlr-4.9-complete.jar.jar:$CLASSPATH" org.antlr.v4.gui.TestRig'

**Comment by wilma-cyber** [comment]
possibly a typo on https://github.com/antlr/antlr4/blob/master/doc/getting-started.md #2976
