### ISSUE TITLE
Lack of Real Xcode Support

### ISSUE THREAD

**Issue by vincent-coetzee** [antlr/antlr4#2981]
It really irritates me that the the developers of this tool are so indoctrinated by Windows, Linux and Java they extensively document how to use those development environments when macOS is probably the most widely used platform by developers. There is no real support for developers to use Xcode or use Swift as the language of choice for output. It is so typical of Windows weenies that they refuse to acknowledge the number of developers that actually use Xcode and Swift in one form or another. I am not interested in Java or using Java tools to manipulate the Antlr grammars or output by the grammar processors, I am not interested in using Visual Studio,  when I can very easily use Swift and Xcode to do the same thing. Many of us do not make use of Java in any way or form hence it is nonsensical to expect us to know how to use various Java meta-tools such as maven to achieve what we need to when working with grammars we want to generate Swift files. I have been trying now for several hours to get a Swift project generated by Antlr to work correctly in Xcode with the Swift files generated by Antlr without success. So far I have had to download and use various Java projects such as Maven even though I know nothing about it, I have also had to use Python which I also don't know, all of which is bloody ridiculous when I know Swift, Objective C, C and C++ none of which help me  in this case. If you are going to support the generation of Swift code by the grammar processor them at least document it properly so that users can get the language processor and compilation to work correctly in Xcode.

**Comment by Marti2203** [comment]
Hello, as a person who uses ANTLR a lot I can tell you multiple things (one of them is to not write long chunks of text with no seperation, but that is a peeve).

ANTLR is an open-source tool which was written in Java with multiple output languages. The community makes the different language runtimes and if you do not like it, you are free to work on it and make it better. I also saw you made a package for Swift so you already know the drill with open-source development. I also had recently seen that there is ongoing work on a Rust backend so the tool is not dead, but thriving.

You begin this issue by throwing a rant about the people here being indoctrinated by Windows, Linux and Java, but in reality most people do not write language processing systems in Swift. Here  a couple of things I can point to remind that perfect tools don't exist - Swift (even though it is open source and kindda getting a standard) does not have a full grammar in any form given by Apple (the company you love with all your heart), so don't begin throwing accusations without seeing the state of the ecosystem you are in. Another issue is mentioned in the instructions for making an XCode project - Swift has no stable ABI, so ask your dear overlords to make that so you can get what you want.

I understand you want to develop things in Swfit, you said you know C++ so you can try doing it in that language and making some Interop with Swift, atleast that should work. 

I really did not understand why you needed Maven or to learn python - it is a basic script, you just need to install python and that is all.

**Comment by ericvergnaud** [comment]
Closing this as we do not encourage rants.
