### ISSUE TITLE
JS Runtime Target for Antlr 4.9 runs TOO SLOW

### ISSUE THREAD

**Issue by yulingtianxia** [antlr/antlr4#2982]
I'm generating JS runtime target with [my Objc grammer files](https://github.com/dart-native/codegen/tree/feature/antlr4.9/parser/objc) using antlr 4.9. On antlr 4.8, it works well. But when I update to 4.9, It runs too slow for a 80 lines header file.(It didn't even end for hours)

**Comment by ericvergnaud** [comment]
There has been no change in the algorithm, so something else must be going on.

**Comment by ericvergnaud** [comment]
@yulingtianxia can you confirm that 4.9.1 fixes the issue and close?

**Comment by yulingtianxia** [comment]
4.9.1 fixed.
