### ISSUE TITLE
Lexer rule selection issue

### ISSUE THREAD

**Issue by sanjanatatawati** [antlr/antlr4#2986]
Exception thrown: 'Antlr4.Runtime.InputMismatchException' in Antlr4.Runtime.Standard.dll
line 1:0 mismatched input 'Import g' expecting 'Import'

I have defined lexer rules in lexer rule

IMPORT : 'Import' ;
IDENTIFIER: [_]*[a-zA-Z][a-zA-Z0-9_]*;
EQUALS: '=';
SEMICOLON: ';' ;

parser rule goes like this

import: IMPORT prefix EQUALS IDENTIFIER ';' ;
prefix: IDENTIFIER;

Input:
Import abc = importsource;
expected output is import should be treated as token, but import abc is treated as single token.
how do we resolve this?

**Comment by ericvergnaud** [comment]
Hi,
please move this to the google discussion group
