### ISSUE TITLE
tree.toStringTree(parser) doesn't work in Javascript like in the API

### ISSUE THREAD

**Issue by geekley** [antlr/antlr4#2993]
antlr4 version (npm and tool): 4.9.0

API: [RuleContext.toStringTree(Parser)]( https://www.antlr.org/api/Java/org/antlr/v4/runtime/RuleContext.html#toStringTree(org.antlr.v4.runtime.Parser) )

CODE:
- `tree.toStringTree(parser)`
- https://github.com/antlr/antlr4/blob/master/runtime/JavaScript/src/antlr4/tree/Trees.js#L24
    error: `TypeError: Cannot read property 'replace' of undefined`

CAUSE: parameter `recog` is only accepted as 3rd parameter, not 2nd, so you'd have to do `tree.toStringTree(null, parser)` unlike what one might expect from the API

SUGGESTED FIX:
- before line 20: `if (ruleNames && ruleNames.ruleNames) recog= ruleNames;`
- before line 24: `if (s)`

**Comment by ericvergnaud** [comment]
Maybe submit a PR with a test?

**Comment by geekley** [comment]
Hmm I just noticed that `inputStream.getText(interval)` is also different in JS: it's `inputStream.getText(start, stop)` and stop is not inclusive either.

I suppose I should stop assuming the API is compatible between JS and Java. That's a bummer, because JS errors are not so trivial to track without having to use a debugger into the lib (because of stupid duck typing). Even with typescript, it's not so easy to understand the correct method signatures ...

If I may suggest an improvement, I think the JS API needs to either get a more explicit documentation (in particular differences from Java) or it should get some reviewing to make sure method signatures are compatible where possible (that is, adding the expected overloads from Java without changing the existing ones).
That's just a suggestion. It would likely require too much effort, but maybe it can be done little by little.

**Comment by ericvergnaud** [comment]
With the typescript target, there is now aa clear API. Closing.
