### ISSUE TITLE
 Get errors when generating Dart target using Java9.g4.

### ISSUE THREAD

**Issue by yulingtianxia** [antlr/antlr4#3002]
Grammer file: https://github.com/antlr/grammars-v4/blob/master/java/java9/Java9.g4
Runtime Target: Dart
Antlr Version: 4.9
Error: "Undefined name 'Character'. " and "Undefined name '_input'." in line 155 of generated file named `Java9Lexer.dart`.

**Comment by yulingtianxia** [comment]
@lingyv-li Please take a look at this issue. Thanks.

**Comment by ericvergnaud** [comment]
Hi,

Please move this the the google discussion group.

thanks

**Comment by yulingtianxia** [comment]
> Hi, Please move this the the google discussion group. thanks
> […](#)

Hi, here it is: https://groups.google.com/g/antlr-discussion/c/aLvhmGGnb08
