### ISSUE TITLE
C++ Runtime: How to support binary input stream?

### ISSUE THREAD

**Issue by g199209** [antlr/antlr4#3008]
In C++ runtime API, both `ANTLRFileStream` and `ANTLRInputStream` use UTF-8 encoding. But I need to deal with binary input stream, which would cause `std::range_error` when using `ANTLRInputStream`:

```
terminate called after throwing an instance of 'std::range_error'
  what():  wstring_convert::from_bytes
```

I found this doc: [Parsing Binary Files](https://github.com/antlr/antlr4/blob/master/doc/parsing-binary-files.md). 

But I cannot found how to do it using C++ runtime API.

Do I need to inherent from `CharStream` writing a custom InputSteam?

@mike-lischke

**Comment by ericvergnaud** [comment]
Hi,

please move this to the google discussion group

Eric
