### ISSUE TITLE
C++ runtime source zip contains utfcpp git metadata

### ISSUE THREAD

**Issue by jmairboeck** [antlr/antlr4#3014]
The [C++ runtime source zip for version 4.9](https://www.antlr.org/download/antlr4-cpp-runtime-4.9-source.zip) contains a .git folder in runtime/thirdparty/utfcpp, which apparently is a complete git clone of the utfcpp repository.

Is it a good idea to include this in the source download, or should the .git folder be stripped from it?

**Comment by mike-lischke** [comment]
I see no .git folder in this zip:

<img width="765" alt="Bildschirmfoto 2021-02-16 um 19 44 35" src="https://user-images.githubusercontent.com/2398704/108107369-7033a880-708f-11eb-9f70-68c1d644a10a.png">

And the runtime is not at all connected with utfcpp. I never heard of that library.

**Comment by jmairboeck** [comment]
utfcpp is not included in the source download of the current version 4.9.3 any more, so this is now fixed.

**Comment by jmairboeck** [comment]
Starting from version 4.10, this is included again, including the `.git` subfolder and `.circleci`.

**Comment by jmairboeck** [comment]
utfcpp is not used any more, so this is fixed once again.
