### ISSUE TITLE
Use GitHub discussions instead of google groups

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#3022]
[GitHub discussions](https://docs.github.com/en/free-pro-team@latest/discussions) have the following advantages compared to google groups:

* Tight integration with GitHub services
* Better UI and UX
* Markdown syntax support

Personally, I don't like google groups and I'm visiting them very rarely.

**Comment by parrt** [comment]
Yeah, I think the Google groups is kind of "old school".   How good are github discussions? never used them. The problem is that over the years lots of things probably pointed at the Google group.

**Comment by KvanTTT** [comment]
We can try to start using GitHub discussions and decide how good they are. But you should turn them on at first, https://docs.github.com/en/free-pro-team@latest/discussions/quickstart#enabling-github-discussions-on-your-repository

**Comment by parrt** [comment]
Done: https://github.com/antlr/antlr4/discussions

We can notify people to see if they wanna try it.

**Comment by KvanTTT** [comment]
Cool! Maybe also it makes sense to create a topic on google groups about starting using GitHub discussions? https://groups.google.com/forum/#!forum/antlr-discussion

**Comment by parrt** [comment]
Done

**Comment by KvanTTT** [comment]
BTW, it's possible to converter issues to discussions: https://docs.github.com/en/free-pro-team@latest/discussions/managing-discussions-for-your-community/moderating-discussions#converting-an-issue-to-a-discussion

**Comment by parrt** [comment]
that's very fancy!  It could be useful to go the other direction to, creating an issue from a discussion.
