### ISSUE TITLE
Variable redeclaration in a code generated for js target

### ISSUE THREAD

**Issue by shabunc** [antlr/antlr4#3027]
I'm generating **a JavaScript parser for Kotlin grammar** from https://github.com/Kotlin/kotlin-spec/tree/release/grammar/src/main/antlr and, while attempting to use it, getting 

```bash
file:///Users/shagen/mine/miamit/api/grammar/kotlin/generated/KotlinParser.js:2763
	        let _alt = this._interp.adaptivePredict(this._input,6,this._ctx) 
	            ^

SyntaxError: Identifier '_alt' has already been declared
    at Loader.moduleStrategy (node:internal/modules/esm/translators:143:18)
``` 

which is caused indeed by redeclaration of variable in the same scope which is a SyntaxError (in fact, there a dozens of similar redeclarations)

What I would have expect is either reassigning value to _alt or (even better) just creating a different variable. 

This is a major bug that makes it impossible to use generated code without manually tuning it.
I'm using antlr@4.9

**Comment by ericvergnaud** [comment]
This is a duplicate, the fix is about to be released

**Comment by ericvergnaud** [comment]
duplicate of #2980
