### ISSUE TITLE
Generated js code is invalid (ReferenceError: _modeStack is not defined)

### ISSUE THREAD

**Issue by shabunc** [antlr/antlr4#3028]
Following grammar - https://github.com/Kotlin/kotlin-spec/blob/release/grammar/src/main/antlr/KotlinLexer.g4
generates (for both 4.9 and a version build from current head), among other thing, following code:

```javascript
KotlinLexer.prototype.RCURL_action = function(localctx , actionIndex) {
    switch (actionIndex) {
    case 0:
         if (!_modeStack.isEmpty()) { popMode(); } 
        break;
    default:
        throw "No registered action for:" + actionIndex;
    }    
};
```

The problem with this code is that both _modeStack and popMode are undefined, and this code is actually invalid.

**Comment by ericvergnaud** [comment]
Please move this to the google discussion group

**Comment by shabunc** [comment]
It's a bug report, not a support issue.

**Comment by ericvergnaud** [comment]
you think it is a bug, but it's a support issue.
The invalid code comes from the grammar, not from antlr.
