### ISSUE TITLE
grammars-v4/idl parser does not parse examples/helloworld.idl in C#, but does parse in Java.

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#3042]
I've been implementing a C# regression test for grammars-v4. I have found that [grammars-v4/idl/examples/helloworld.idl](https://github.com/antlr/grammars-v4/blob/master/idl/examples/helloworld.idl) parses for Java but not for C# with version 4.9.1. Below is a script to generate and run C# and Java driver programs that reproduce the bug. You will need to cd to grammars-v4/idl on Linux before running the steps below, and you will need to replace the location of the jar files with where you have downloaded them. 

	#!/usr/bin/bash
	dotnet --version
	# 5.0.101 or newer is sufficient
	dotnet tool uninstall -g dotnet-antlr
	dotnet tool install -g dotnet-antlr --version 1.2.0
	mkdir csharp
	mkdir java
	echo ""
	echo "Generating and running C# version."
	dotnet-antlr -s specification
	mv Generated csharp
	dotnet-antlr -s specification -t Java
	mv Generated java
	cd csharp/Generated
	dotnet restore
	dotnet build
	dotnet run -file ../../examples/helloworld.idl
	cd ../..
	echo ""
	echo "Generating and running Java version."
	cd java/Generated
	java -jar /mnt/c/Users/kenne/Downloads/antlr-4.9.1-complete.jar -package Generated IDL.g4
	javac -classpath "/mnt/c/Users/kenne/Downloads/antlr-4.9.1-complete.jar:.." *.java
	java -classpath "/mnt/c/Users/kenne/Downloads/antlr-4.9.1-complete.jar:.." Generated.Program -file ../../examples/helloworld.idl

The expected output is:

	5.0.101
	Tool 'dotnet-antlr' (version '1.2.0') was successfully uninstalled.
	You can invoke the tool using the following command: dotnet-antlr
	Tool 'dotnet-antlr' (version '1.2.0') was successfully installed.

	Generating and running C# version.
	  Determining projects to restore...
	  Restored /mnt/c/Users/kenne/Documents/grammars-v4c/idl/csharp/Generated/Test.csproj (in 501 ms).
	Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
	Copyright (C) Microsoft Corporation. All rights reserved.

	  Determining projects to restore...
	  All projects are up-to-date for restore.
	  Test -> /mnt/c/Users/kenne/Documents/grammars-v4c/idl/csharp/Generated/bin/Debug/net5.0/Test.dll

	Build succeeded.
	    0 Warning(s)
	    0 Error(s)

	Time Elapsed 00:00:10.99
	line 3:2 mismatched input 'interface' expecting {'@', 'typedef', 'custom', 'struct', 'native', 'eventtype', 'enum', 'home', 'exception', 'const', 'module', 'union', 'abstract', 'typeprefix', 'typeid', 'component', 'bitset', 'bitmask', '@annotation'}
	line 3:2 mismatched input 'interface' expecting {'@', 'typedef', 'custom', 'struct', 'native', 'eventtype', 'enum', 'home', 'exception', 'const', 'module', 'union', 'abstract', 'typeprefix', 'typeid', 'component', 'bitset', 'bitmask', '@annotation'}
	parse failed.

	Generating and running Java version.
	parse completed.

I have debugged the two programs side by side, and found that after recognizing a LEFT_BRACE, the call to ErrorHandler.Sync(this) fails because the lookahead sets computed are not the same between C# and Java.

    In IDLParser.cs:
			State = 372; Match(KW_MODULE);
			State = 373; identifier();
			State = 374; Match(LEFT_BRACE);
			State = 376;
			ErrorHandler.Sync(this); <<<

    In DefaultErrorStrategy.cs
        public virtual void Sync(Parser recognizer)
        {
            ATNState s = recognizer.Interpreter.atn.states[recognizer.State];
            //		System.err.println("sync @ "+s.stateNumber+"="+s.getClass().getSimpleName());
            // If already recovering, don't try to sync
            if (InErrorRecoveryMode(recognizer))
            {
                return;
            }
            ITokenStream tokens = ((ITokenStream)recognizer.InputStream);
            int la = tokens.LA(1);
            // try cheaper subset first; might get lucky. seems to shave a wee bit off
            var nextTokens = recognizer.Atn.NextTokens(s);
            if (nextTokens.Contains(TokenConstants.EPSILON) || nextTokens.Contains(la)) 
            {
                return;
            }
            switch (s.StateType)
            {
                case StateType.BlockStart:
                case StateType.StarBlockStart:
                case StateType.PlusBlockStart:
                case StateType.StarLoopEntry:
                {
                    // report error and recover if possible
                    if (SingleTokenDeletion(recognizer) != null)
                    {
                        return;
                    }
                    throw new InputMismatchException(recognizer); <<< Fails here.

For C#, `nextTokens` is `{{35, 42, 45, 49..50, 56, 63, 66, 68, 70, 74, 79, 87, 92..93, 98, 102..103, 112}}`; `la` is 97 (KW_INTERFACE). 

For Java, `nextTokens` is `{35, 42, 45, 49..50, 56, 63, 66, 68, 70, 72, 74, 79, 87, 92..93, 95, 97..98, 102..103, 112}`; `la` is 97 (KW_INTERFACE).

It fails in C# because 97 is not in `nextTokens` then does a `throw`. I haven't figured out why the two sets are different, and I don't know which one is correct. However, I wrote a full backtracking NFA interpreter that computes the lookahead sets. It's based on [Mike Lischke's C3](https://github.com/mike-lischke/antlr4-c3) but fixes a major bug in that, and use that to determine which is wrong.

I should also note, again, that the C# and Java runtimes differ significantly. For example, in the Java runtime, `sync()` differs [here](https://github.com/antlr/antlr4/blob/b4ceb2022a1484af13df30604de342772a4d935a/runtime/CSharp/DefaultErrorStrategy.cs#L267) and [here](https://github.com/antlr/antlr4/blob/b4ceb2022a1484af13df30604de342772a4d935a/runtime/Java/src/org/antlr/v4/runtime/DefaultErrorStrategy.java#L243). 

* The order of the tests are not the same. In C#, the check for Epsilon is 1st, `la` second; In Java, Eps is 2nd, `la` 1st.
* The code before the return statements are not the same.

I hope that this bug helps to demonstrate what happens when the translation of the Java code to C# is not only not automated, but likely with all sorts of hidden bugs. I have found that when you do a port, it cleans up all targets. I'm not criticizing, but I do suggest someone go through line by line and look for these differences and resolve them.

**Comment by ericvergnaud** [comment]
Hi,

thanks for this.
By ‘regression’ do you mean this was working with previous versions of the C# runtime?


Eric

**Comment by kaby76** [comment]
Well, it may not be a "regression". But, whatever you'd like to call it, assuming the Java runtime is computing the lookahead sets correctly--which I will check--the C# port is not working here. There is no CI testing in grammars-v4, but I have a PR for testing over half the grammars, and I'm checking the rest.

**Comment by ericvergnaud** [comment]
Ok so it's possible that this grammar always exhibited a different behavior between Java and C#?
That was really my question...

**Comment by kaby76** [comment]
It's hard to say if anyone tested a C# parser for the IDL grammar, whether it be Antlr4 Java Tool+Antlr4.Runtime.Standard or Harwell's Antlr4cs (tool+runtime). There is no target-specific code within the grammar, and the pom.xml tests the Java target (my test script uses the pom.xml file, but uses a completely independent C# generator). The reason I wrote my own "C3" library (backtracking NFA parser using Antlr's ATN data structures) was because I noticed the generated C# parser would not print out the correct lookahead sets for code completion in my tool for Antlr grammars. It's likely the bug here is similar to the bug I saw before, which has to do with epsilon transitions to the end state of an ATN, and stacked ATN calls.

**Comment by ericvergnaud** [comment]
Hi

it seems some bug fixes in the java runtime did not make it to the C# one
would you mind checking if https://github.com/antlr/antlr4/pull/3046 fixes the issue?

we could be interested in integrating your "C# regression test for grammars-v4" in our CI
we could then detect more gaps earlier

**Comment by kaby76** [comment]
Yes, that fixes the problem for IDL. The rest of the grammars that did pass still pass and the lookahead set in C# for `helloworld.idl` is now the same as in Java. Reading the comments in the changed ATN code, that's exactly the BS I was talking about. It's good to see the mess in the build files for the C# runtime fixed, but it would be nice to add `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>`  to `antlr4/runtime/CSharp/Antlr4.csproj` so one can just add a `git clone`, `dotnet nuget add source`, and a couple `dotnet build`.

**Comment by ericvergnaud** [comment]
Would you mind submitting a PR for this?

**Comment by kaby76** [comment]
I would prefer not to make the PR. It confuses the roles here, going against ~40 years I've been developing. You are the developer; I am the originator of the issue. I could fork a copy of your repo, but your changes include other targets for which I can't test. The CI for antlr/antlr4 is [broken](https://github.com/antlr/antlr4/runs/1753939774?check_suite_focus=true), and PRs are being merged and closed even though they do not pass CI. The 1st build badge at https://github.com/antlr/antlr4#antlr-v4 (for Travis which is no longer being done) is wrong. There is much wrong here. To boot, the changes I made to [antlr/grammars-g4](https://github.com/antlr/grammars-v4/pull/1989) are still not being merged. I feel my changes are going just going to be ignored--including [this](https://github.com/antlr/antlr4/issues/2693) for a year before consideration.

**Comment by kaby76** [comment]
Since people still use Harwell's Antlr4cs, and since some antlr/grammars-v4 grammars target Antlr4cs, I decided to update my template driver generator for Antlr4cs C# and check it against this bug. Harwell's code parses helloworld.idl.

**Comment by ericvergnaud** [comment]
The PR I was talking about is about your proposed <GeneratePackageOnBuild>true</GeneratePackageOnBuild>.
Antlr4 now has 239 contributors.

**Comment by ericvergnaud** [comment]
RE grammars-v4, it is NOT maintained by the runtime authors.

**Comment by ericvergnaud** [comment]
The CI is broken due to a recent pricing policy at Travis CI.
We are actively working on alternatives.

**Comment by ericvergnaud** [comment]
Re #2693, you filed an issue comprising an unreadable change proposal, combining whitespacing and possibly a bug fix.
Looking at it it would have required a lot of work, when a one line change would have been immediately considered.

**Comment by ericvergnaud** [comment]
> I feel my changes are going just going to be ignored--including [this](https://github.com/antlr/antlr4/issues/2693) for a year > before consideration.
Well I have engaged on the PR related this one, and apparently it is pending action at your end?

**Comment by kaby76** [comment]
OK, thanks for the info. I'll submit a PR for `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>`, then update https://github.com/antlr/antlr4/pull/2936 after this. CI limits are annoying. Sounds like the workload needs to be divvied on to as many providers.
