### ISSUE TITLE
[Doc] JavaScript target is ES6 for Antlr 4.9+ not ES5 as stated in the doc

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#3069]
I don't think [this web page](https://github.com/antlr/antlr4/blob/master/doc/javascript-target.md#which-browsers-are-supported) is correct anymore. It should say Antlr 4.9.* is for ES6, not ES5. That's because the generated code (which I tested using the Antlr 4.9.1 tool) uses "import" and "class" (see [this](https://en.wikipedia.org/wiki/ECMAScript#6th_Edition_%E2%80%93_ECMAScript_2015), the change https://github.com/antlr/antlr4/commit/0bd0a05f24a171d01d1d8220971e87425c20e9d5 and the previous change in the day by @ericvergnaud ). (Yes, one could transpile ES6 to ES5 using Babel, but strictly speaking, the tool produces ES6 output. Perhaps make a note in the doc?) The sample driver code in the web page looks okay.

**Comment by ericvergnaud** [comment]
Hi,
you're right, feel free to propose an update

**Comment by ericvergnaud** [comment]
Already fixed in dev, closing.
