### ISSUE TITLE
Generating parser with syntax error

### ISSUE THREAD

**Issue by TrueFinch** [antlr/antlr4#3070]
Command 
`java -Xmx500M -cp antlr-4.9.1-complete.jar org.antlr.v4.Tool -Dlanguage=Python3 CPP14Parser.g4`
generates python parser with syntax error for c++ language
Grammar was downloaded from [here](https://github.com/antlr/grammars-v4/tree/master/cpp)
![изображение](https://user-images.githubusercontent.com/24905983/107191973-b908b300-6a38-11eb-8b8c-34236a15d9b7.png)

**Comment by ericvergnaud** [comment]
That grammar was designed for Java, you'll need to adapt it for Python
