### ISSUE TITLE
[JS] Utils.js: arrayToString(null) should check null arg

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#3078]
The code for [arrayToString](https://github.com/antlr/antlr4/blob/master/runtime/JavaScript/src/antlr4/Utils.js#L7) should check whether parameter "a" is null. This function is called when debugging for ParserATNInterpreter.debug=true is set. Unfortunately, the debug code throws an exception when evaluating "a.join()". Also, if the array contains null values, the output string contains no value. In C#, a null element of the array is outputted as "null".

**Comment by kaby76** [comment]
[The corresponding code in the C# runtime](https://github.com/antlr/antlr4/blob/master/runtime/CSharp/src/Sharpen/Arrays.cs#L64), in fact, handles a null parameter, again showing a translation gap. The JS arrayToString() code is too brittle. The C# code should be translated and used instead of what is there for arrayToString(), because it clearly can be passed a null value ([altToPred <- null;](https://github.com/antlr/antlr4/blob/954649d5aabdc483a7b7de7e4ea033d908744a6a/runtime/JavaScript/src/antlr4/atn/ParserATNSimulator.js#L1011), then [arrayToString(altToPred)](https://github.com/antlr/antlr4/blob/954649d5aabdc483a7b7de7e4ea033d908744a6a/runtime/JavaScript/src/antlr4/atn/ParserATNSimulator.js#L1014)).

**Comment by ericvergnaud** [comment]
Please submit a PR?
(btw the ref implementation is Java, not C#)

**Comment by kaby76** [comment]
> Please submit a PR?
> (btw the ref implementation is Java, not C#)

I don't understand your question "Please submit a PR?" Is this a question or an imperative?  I will make a PR to arrayToString() in the JS runtime code, but this change is not ready. I haven't a unit test working yet. I have not even done a "mvn install" yet.

I also do not understand your comment "(btw the ref implementation is Java, not C#)". The change I made to arrayToString() is to make the JS code more robust when debug=true, as it is already for C#. I believe the Java code also throws an exception when debug=true, but I have not compared any of this with the Java runtime yet.

**Comment by kaby76** [comment]
Well, your change doesn't exactly align with what Java or C# outputs because your JS code outputs an empty string for null elements in an array. So, I wouldn't say it's "fixed". With ParserATNSimulator.debug= true, I see this in Java `getPredsForAmbigAlts result [null, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {19:0}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?]` (null element is output as "null, "), this in C# `getPredsForAmbigAlts result [null, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {19:0}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?]`  (null element is output as "null, "), and this in JS `getPredsForAmbigAlts result [, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {19:0}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?, {-1:-1}?]`  (null element is output as ", "). Yes, tighter code is nice to have, but it does not produce the same result.

**Comment by ericvergnaud** [comment]
not sure what change you are looking at?
the below cannot return an empty string:
function arrayToString(a) {
    return Array.isArray(a) ? ("[" + a.join(", ") + "]") : "null";
}

**Comment by ericvergnaud** [comment]
> > Please submit a PR?
> > (btw the ref implementation is Java, not C#)
> 
> I don't understand your question "Please submit a PR?" Is this a question or an imperative? I will make a PR to arrayToString() in the JS runtime code, but this change is not ready. I haven't a unit test working yet. I have not even done a "mvn install" yet.
> 
> I also do not understand your comment "(btw the ref implementation is Java, not C#)". The change I made to arrayToString() is to make the JS code more robust when debug=true, as it is for C#. I believe the Java runtime also throws an exception when debug=true, but I have not compared any of this with the Java runtime yet.
> 
> Sorry, I am not trying to be rude here, but I am just trying to understand what you are saying.

What I'm saying is that since the reference runtime is the Java one, it's better to align on it, rather than align on any other since they may also exhibit a gap.

**Comment by kaby76** [comment]
> not sure what change you are looking at?
> the below cannot return an empty string:
> function arrayToString(a) {
> return Array.isArray(a) ? ("[" + a.join(", ") + "]") : "null";
> }

Yes, that change. That code does not return an empty string, even if a==null. But, if an element of a is null, it outputs an empty string between the comma separators.

**Comment by kaby76** [comment]
> What I'm saying is that since the reference runtime is the Java one, it's better to align on it, rather than align on any other since they may also exhibit a gap.

I agree. But, as I said, it's not even aligning with the Java code--the output is not the same when array "a" contains a null element. I like using C# but for one main reason: one cannot reset the program counter in a debugger to rerun a statement. Anyway, it's kind of not important because there are so many other diffs in the debug output between targets.

**Comment by ericvergnaud** [comment]
I just fixed the NPE.
(feel free to fix the null element bit)
I don't think it's possible to have outputs strictly aligned because there are sets/maps all over the place for which the order of elements is implementation dependent.

**Comment by kaby76** [comment]
> I just fixed the NPE.
> (feel free to fix the null element bit)
> I don't think it's possible to have outputs strictly aligned because there are sets/maps all over the place for which the order of elements is implementation dependent.

Right. I noticed that. The order of elements in sets/maps is different, resulting in all sorts of differences. I'll skip the null element bit. Not important. I rather look at the JS grammar on bigger examples, and across different targets. Thanks. --Ken
