### ISSUE TITLE
[C#] Setting ParserATNInterpreter.debug = true cause crashes

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#3079]
I'm am trying to debug in a side-by-side manner the actions of the ATN interpreter of C# with JS. So, I am trying to leverage the debug output information when setting ParserATNSimulator.debug = true. Unfortunately, debug output is shuffled to ConsoleWriteLine(fmt, args) which summarily crashes because it calls System.Console.WriteLine(fmt, args), and it is not a formated call because it is called with only one arg, and it is not to be intrepreted as a format. Either the method needs just call System.Console.WriteLine(fmt), or the applied references to the method changed to System.Console.WriteLine(). I thought I raised an issue years ago for this, even supplied the diffs, but it was neglected. This is important. I will submit a PR, but please merged the fix asap.

**Comment by kaby76** [comment]
The problem was introduced with [this commit](https://github.com/antlr/antlr4/commit/ef49021c8b5e84e409b2a52b7cf7de59fda18348#diff-e4b2755a11fc5fdfaaa170fbab8c65f336360f94800879c0c3258c146cf7f62e). Interpretation of the first string into ConsoleWriteLine() is the problem. As far as I can tell, there are no calls for formatted output.

**Comment by KvanTTT** [comment]
@kaby76 @ericvergnaud please close since it's fixed
