### ISSUE TITLE
Serious performance issue with JavaScript target

### ISSUE THREAD

**Issue by dhowe** [antlr/antlr4#3084]
I am new to antlr4 and have a relatively simple recursive grammar (with separate lexer/parser) for a project that runs in both Java and JavaScript. Everything works as expected for short expressions. For longer ones, Java works as expected with parses on the order of 50-100ms, while JavaScript takes many, many seconds for medium length expression and simply hangs and/or does not complete for longer ones. Some simple performance metrics rule out the lexing and visiting phases which take only a few milliseconds. I am at a loss as to how to investigate further...

In the demo below, the output parse-tree is identical, but while the Java parse takes 91 ms the JavaScript parse takes 46 seconds!!   

If I increase the length of the string any further, the JavaScript hangs and does not complete.

Java: https://github.com/dhowe/rita4j/tree/master/src/main/java/rita/antlr
JS: https://github.com/dhowe/ritajs/tree/master/grammar

Simple demo (js):
```
$ git clone https://github.com/dhowe/ritajs.git
$ cd ritajs && git checkout perf
$ npm install
$ node perf-test.js

OUTPUT:
[lexing] 0ms
(script (line (expr (chars Lorem   ipsum   dolor   sit   amet,  ) (choice ( (wexpr (expr (chars consectetur   adipiscing   elit))) )) (chars   morbi   ullamcorper   porttitor   lorem,   in   faucibus   velit   ultrices   nec .   Curabitur   convallis   luctus   felis,   sed   posuere   turpis   mollis   quis .   Suspendisse   euismod   vel   tellus   sit   amet   tempus .   Nullam   pretium   tincidunt   pellentesque .   Vestibulum   tempus   eget   eros   non   dignissim .   Nullam   faucibus   et   augue   a   commodo .   Curabitur   tellus   est,   elementum   sit   amet   finibus   a,   posuere   in   nunc .   In   libero   metus,   tempor   nec   tincidunt   eu,   vulputate   a   ex .   Aliquam   id   tincidunt   sapien .   In   pharetra   condimentum   lacus,   non   congue   arcu   tempor   nec .   Nullam   faucibus   odio   id   diam   dapibus   volutpat   sed   in   quam .   Vivamus   ex   quam,   efficitur   sit   amet   ante   eu,   congue   blandit   arcu .   Suspendisse   molestie   sit   amet   diam   ac   tristique .))) <EOF>)
[parsing] 46028ms
[visiting] 1ms
```

Same demo (java):
```
$ git clone https://github.com/dhowe/rita4j.git
$ cd rita4j && git checkout perf
$ mvn compile test-compile  exec:java  -Dexec.mainClass="rita.test.PerfTest" -Dexec.classpathScope=test 

OUTPUT:
[lexing] 50ms
(script (line (expr (chars Lorem   ipsum   dolor   sit   amet,  ) (choice ( (wexpr (expr (chars consectetur   adipiscing   elit))) )) (chars   morbi   ullamcorper   porttitor   lorem,   in   faucibus   velit   ultrices   nec .   Curabitur   convallis   luctus   felis,   sed   posuere   turpis   mollis   quis .   Suspendisse   euismod   vel   tellus   sit   amet   tempus .   Nullam   pretium   tincidunt   pellentesque .   Vestibulum   tempus   eget   eros   non   dignissim .   Nullam   faucibus   et   augue   a   commodo .   Curabitur   tellus   est,   elementum   sit   amet   finibus   a,   posuere   in   nunc .   In   libero   metus,   tempor   nec   tincidunt   eu,   vulputate   a   ex .   Aliquam   id   tincidunt   sapien .   In   pharetra   condimentum   lacus,   non   congue   arcu   tempor   nec .   Nullam   faucibus   odio   id   diam   dapibus   volutpat   sed   in   quam .   Vivamus   ex   quam,   efficitur   sit   amet   ante   eu,   congue   blandit   arcu .   Suspendisse   molestie   sit   amet   diam   ac   tristique .))) <EOF>)
[parsing] 91ms
[visiting] 18ms
```

Any suggestions would be _very_ much appreciated.

**Comment by ericvergnaud** [comment]
There is a bug in the JS runtime that was fixed recently, so suggest you try the latest code base (not released).
You should get support from the google discussions group.

**Comment by dhowe** [comment]
Thanks for the reply. Does this mean I have to build antlr4 itself from the repo? And is there a specific branch or commit I should use?

**Comment by ericvergnaud** [comment]
Yes, use latest master

**Comment by dhowe** [comment]
Ok, so I've built antlr4 from source but I'm getting many errors of a similar form when I run the javascript tests (see below). 
Also, its not clear to me how I can use these artifacts in the two projects (java/js), that is, what do I specify in my pom.xml and package.json (the latter being more the critical question) ?

> testOne[Node:EnforcedGreedyNestedBraces_1](org.antlr.v4.test.runtime.javascript.TestLexerErrors)  Time elapsed: 7.172 sec  <<< FAILURE!
> junit.framework.AssertionFailedError: 
> [Node:EnforcedGreedyNestedBraces_1] Parse output is as expected, but errors are not: expectedParseErrors:<>; actualParseErrors:<(node:59540) ExperimentalWarning: The ESM module loader is experimental.
> >; expectedToolErrors:<>; actualToolErrors:<>.
> 
> testOne[Node:DFAToATNThatMatchesThenFailsInATN](org.antlr.v4.test.runtime.javascript.TestLexerErrors)  Time elapsed: 6.246 sec  <<< FAILURE!
> junit.framework.AssertionFailedError: 
> [Node:DFAToATNThatMatchesThenFailsInATN] Parse output is as expected, but errors are not: expectedParseErrors:<line 1:5 token recognition error at: 'x'
> >; actualParseErrors:<(node:59547) ExperimentalWarning: The ESM module loader is experimental.
> line 1:5 token recognition error at: 'x'
> >; expectedToolErrors:<>; actualToolErrors:<>.
> 
> testOne[Node:DFAToATNThatFailsBackToDFA](org.antlr.v4.test.runtime.javascript.TestLexerErrors)  Time elapsed: 6.738 sec  <<< FAILURE!
> junit.framework.AssertionFailedError: 
> [Node:DFAToATNThatFailsBackToDFA] Parse output is as expected, but errors are not: expectedParseErrors:<line 1:4 token recognition error at: 'x'
> >; actualParseErrors:<(node:59554) ExperimentalWarning: The ESM module loader is experimental.
> line 1:4 token recognition error at: 'x'
> >; expectedToolErrors:<>; actualToolErrors:<>.

**Comment by ericvergnaud** [comment]
Sorry, I meant build the JS runtime...
It's located under runtime/JavaScipt

**Comment by dhowe** [comment]
Ok, so I've built the JavaScript into runtime/JavaScript/dist/antlr4.js. Do I need to use this new version to generate the lexer and parser classes as well, or can can I just substitute the runtime into my project?

**Comment by ericvergnaud** [comment]
no need to generate

**Comment by kaby76** [comment]
I ran the grammar through my driver generator and added in a "for (int i=0; i < 99; ++i)...", which the JS code does, around a complete parser/lexer setup and teardown. The input is a 745 char line, which I found via debugging the JS code. The runtime is 11s for JS, 3s for Java. The lexer grammar contains semantic predicates. You must use the latest JS runtime (and Tool--I never mix versions by habit) from github.com/antlr/antlr4 master.

**Comment by ericvergnaud** [comment]
3 to 4 times slower is in line with what you can expect.
See https://benchmarksgame-team.pages.debian.net/benchmarksgame/performance/knucleotide.html, a benchmark which like ANTLR spends most of its time manipulating hash maps. 

Can I close this?

**Comment by dhowe** [comment]
Thanks @kaby76 are you saying that with antlr tool, regenerated lexer/parser code, and js runtime all built from the lastest master, you achieve the results you describe ?

**Comment by kaby76** [comment]
I'll send a link to you @dhowe to my code in an hour or so. UTC-5h here, early here still.

**Comment by dhowe** [comment]
thanks so much, very helpful

**Comment by kaby76** [comment]
@dhowe The code is here: https://github.com/kaby76/AntlrExamples/tree/master/RiScript  I included a build of the jar and JS runtime of the latest in the repo. "cd" to JS/, then type "make", "make run" (on a Linux box). You can do the same for Java/. This bug can now be closed. Any further help should be posted on StackOverflow or the Antlr Google discussion group. Enjoy. --Ken

**Comment by dhowe** [comment]
Thanks Ken. When I try to run program.js (after doing the make) it seems to hang (several minutes now). For the Java, I need v10 or greater I guess -- and still wrestling with oracle nonsense.

**Comment by dhowe** [comment]
thanks Ken!

**Comment by kaby76** [comment]
> Any idea when the next release will happen? For deploying this javascript library, it would be great to be able to use npm for dependencies in the usual way, rather than bundling antlr ...

@dhowe -- Eric and/or Terence are in charge of the Antlr4 repo and releases. The cadence is a "+0.1.0" rev per year. Since a release was just made (actually two--4.9.0, 4.9.1), I wouldn't expect a new release anytime soon. But, I think if you should need an NPM version, then maybe you can make a private copy and stick it up on the NPM registry in the meanwhile. I'm not at all familiar with doing that (https://docs.npmjs.com/about-the-public-npm-registry; https://github.com/antlr/antlr4/blob/master/doc/releasing-antlr.md#deploying-targets). I am working on something tangential to Antlr--a transformational system and language server for parser generator grammars, which includes Antlr.

**Comment by dhowe** [comment]
So the current problem I'm having is that I can no longer build the project on node below version 14:

```bash
$ yarn install
yarn install v1.21.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error antlr4@4.9.1: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.9.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by ericvergnaud** [comment]
what stops you from upgrading node?

**Comment by dhowe** [comment]
I have upgraded node in my own setup. But I still need to test my distributed code with earlier Node versions, which I do via the standard continuous integration (CI) approach. On each pull request or release,  the code is automatically tested, in parallel, against multiple node versions on different OSs. 

The way the CI works is that it builds everything from scratch (clone, install, build, test) on a fresh OS, and (to the best of my knowledge)  uses the version of node that you specify for both the build and test phases. So testing with node 12 means building with node 12, which (as shown above) fails.

**Comment by ericvergnaud** [comment]
If I understand correctly, RitaJS is only used by developers.
Can they not upgrade to node 14 ?
Alternative would be (for you) to babelize antlr4 such that your CI uses a version that does not require node 14

**Comment by dhowe** [comment]
No, it is a production library. And it is babelized on the CI, but first needs to built... As I mention above, I don't think it is possible to use different node versions for the two steps (and certainly isn't standard, so this problem will come up again for other JS libs).

**Comment by ericvergnaud** [comment]
You could use n to switch from one node version to another (1 to build, 1 to test) in your CI.

**Comment by ericvergnaud** [comment]
can this issue be closed?

**Comment by dhowe** [comment]
This issue should definitely not be closed, in my opinion, for two reasons:
1. There is huge bug in the current public release for JS, and no good workaround
2. The JS releases do not support the most common/basic workflows (as described above)
