### ISSUE TITLE
npm and install brings all src and package.json for antlre which is breaking my code

### ISSUE THREAD

**Issue by hamedminaee** [antlr/antlr4#3118]
I am encountering a strange issue (and this was working before and all the sudden this starts to happen),

I have a small project with antlre called parser

```
 "dependencies": {
   ....
"antlr4": "^4.7.2"
```

and as you the above is the dependency. Now after merging the above I use semantic release in git to make a release tag out of then I can use it in other nodejs projects. I use it in another nodejs project as follows:

```
},
"dependencies": {
    "@proj/parser": "^3.4.0",
```

Now when I do npm i in the above I can see antlre is being added in node_modules but in this format

![image](https://user-images.githubusercontent.com/52859974/111002580-19eb1a00-835c-11eb-99a6-b0b3f8d43a6b.png)

and I can see src folder and package.json

![image](https://user-images.githubusercontent.com/52859974/111002630-2a02f980-835c-11eb-9b97-581a0f3cc8ac.png)

and this seems to be the root of the issue. I expect that the second antlr folder only being download in node_module folder I am so confused and not sure if this is npm issue or antlr. can anyone shed any light?

**Comment by ericvergnaud** [comment]
Hi,
please move this to the google discussion group.
