### ISSUE TITLE
[JAVA] Generated Parser causing errors

### ISSUE THREAD

**Issue by AurumByte** [antlr/antlr4#3120]
- [x] I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [x] I have done a search of the existing issues to make sure I'm not sending in a duplicate

I know this might not be the place to ask but this seems like an issue anyway so, here we are.

I used ANTLR to generate a parser for a project I'm working on (I'm using IntelliJ and use Java as the generation target). When I ran `gradle compileJava` to check my own code for errors, the Parser class started erring like crazy. In IntelliJ, I saw about 355 errors with the Parser, most of being:

- Cannot resolve method 'getState' in 'Parser'
- Cannot resolve symbol '_interp'

and such. I don't know how to resolve this issue and wanted some help.

PS: Is it inappropriate to post about this issue here? Should I post this somewhere else instead?

**Comment by ericvergnaud** [comment]
please move this to the google discussion group

**Comment by AurumByte** [comment]
I joined the group, but I am unable to post a conversation there. What should I do?
