### ISSUE TITLE
Add support for stream processing in JavaScript

### ISSUE THREAD

**Issue by jgalrito** [antlr/antlr4#3121]
Java API offers CharStream.fromStream. Is there a possibility of adding support for this in Javascript? How would one parse an infinite/long stream?

**Comment by ericvergnaud** [comment]
Hi,
the Java API is not meant for infinite or even long stream, it just satisfies a common practice in Java.
Parsing an infinite would likely never return, so would not be usable.
May I suggest you move this discussion to the google group.
