### ISSUE TITLE
Parsing Java with JavaScript parser fails while CSharp/Java parser succeeds

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#3126]
I have been parsing some Java code using grammars-v4/java/java/*.g4, and I noticed that for the following input, the JavaScript parser fails but the CSharp and Java parsers succeed.

    public class HelloWorld { 
       public static void main(String[] args) { 
          System.out.println("Hello, World" + "hi There");
       }
    }

Note, in all parsers I generate for the grammar, I used the default listeners.

Debugging the JavaScript parser side-by-side with the CSharp parser, I've determined that the JS parser fails to parse the expression "Hello, World" + "hi There" at the '+' operator.

Looking over the generated parsers JavaParser.cs and JavaParser.js, I have noticed that the likely culprit is the generated code:

CSharp:

    if ( ParseListeners!=null )
        TriggerExitRuleEvent();

JavaScript:

    if(this._parseListeners!==null) {
        this.triggerExitRuleEvent();
    }

These codes are not the same, and they execute differently.

In CSharp, [ParseListeners](https://github.com/antlr/antlr4/blob/4b649103f31e0c0bc3bd0bb964efd0dea6b9f5a0/runtime/CSharp/src/Parser.cs#L404) in the snippet is a `get` property call in the `Parser` class that returns an empty list if the [backing field](https://github.com/antlr/antlr4/blob/4b649103f31e0c0bc3bd0bb964efd0dea6b9f5a0/runtime/CSharp/src/Parser.cs#L158) is null. In this case, it returns an empty list, which is for sure not equal to null, and `this.triggerExitRuleEvent()` is called.

In JavaScript, `this._parseListeners` is a reference to the [backing field](https://github.com/antlr/antlr4/blob/4de9e80109530a72ccae8997bdb305c07dcbcd23/runtime/JavaScript/src/antlr4/Parser.js#L71) itself, not the getter [getParseListeners()](https://github.com/antlr/antlr4/blob/4de9e80109530a72ccae8997bdb305c07dcbcd23/runtime/JavaScript/src/antlr4/Parser.js#L165). In JavaScript, `triggerExitRuleEvent()` is never called.

Also, just scanning through the generated parsers, I've also noticed constants `~0x3f` used in CSharp vs `~0x1f` used in JavaScript. While it's likely not important in this example, it is rather irritating to see magic number differences between the runtimes.

--Ken

**Comment by ericvergnaud** [comment]
looks like the generated code should be this.getParseListeners(), but not sure why it's tested if it can never be null...
re constants, not sure which constants/magin number you are referring to?

**Comment by kaby76** [comment]
@ericvergnaud I agree with your first question reasoning: the test is never null in the C# runtime, so the function is always called. Then what is the function of the test?? Good question. All I can say is that this is one point where I see the code paths diverge between C# and JS. It's just speculation on my part whether this actually is the "culprit". I shall continue with a modified JS runtime to see where else the code paths diverge.

The other question, about the `~0x3f` vs `~0x1f` magic numbers. These are sprinkled throughout the generated code, coming from [here](https://github.com/antlr/antlr4/blob/ca2bfedb2c1c92f6370a33b4e385a553cecdff54/tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg#L684) and [here](https://github.com/antlr/antlr4/blob/ca2bfedb2c1c92f6370a33b4e385a553cecdff54/tool/resources/org/antlr/v4/tool/templates/codegen/JavaScript/JavaScript.stg#L457) in the templates, the only place I grepped the magic numbers. They are used in JavaParser.cs/js to test whether the lookahead token is in an interval. I only noticed the difference because when I include an error listener and set a breakpoint my error listener, run, it breaks in the "recoverInline()" call.

CSharp:

    _la = TokenStream.LA(1);
    if ( !(((((_la - 87)) & ~0x3f) == 0 && ((1L << (_la - 87)) & ((1L << (MUL - 87)) | (1L << (DIV - 87)) | (1L << (MOD - 87)))) != 0)) ) {
        _localctx.bop = ErrorHandler.RecoverInline(this);
    }

JS:

    _la = this._input.LA(1);
    if(!(((((_la - 87)) & ~0x1f) == 0 && ((1 << (_la - 87)) & ((1 << (JavaParser.MUL - 87)) | (1 << (JavaParser.DIV - 87)) | (1 << (JavaParser.MOD - 87)))) !== 0))) {
        localctx.bop = this._errHandler.recoverInline(this);
    }

I thought, maybe, that the expression wasn't working in the JS code, but I think it is. I checked the precedence of the operators in that "if", and I think it looks okay. But, the magic numbers are different.

**Comment by ericvergnaud** [comment]
Re the other question, these are not magic numbers, they are the technical limit of bit shift operations.
In Java/C# it can be up to 63, in JavaScript it is limited to 31.

**Comment by kaby76** [comment]
> Re the other question, these are not magic numbers, they are the technical limit of bit shift operations.
> In Java/C# it can be up to 63, in JavaScript it is limited to 31.

Understood. But, in my day, these were always referred to as "magic numbers". It's bad practice to have constants appear in code like this. It would be better to define a static final const at the top of the generated code and included a comment that explains what it means and how it's used. In any case, it's not likely a problem here.

**Comment by kaby76** [comment]
It doesn't matter that TriggerExitRuleEvent()` is called unconditionally in C#: the call turns into a no-op because the method first tests the backing field for null. But, it would probably be nice to make it consistent with Java and JavaScript, and maybe the other runtimes. So, this is not the problem.

**Comment by kaby76** [comment]
Yeah, there's something still wrong with the state representation in JavaScript, likely IntervalSet/Interval.
:( 
See state 1137 in this dot graph. 
![graphviz](https://user-images.githubusercontent.com/11389451/111560090-29a59c80-8768-11eb-979c-61097a339ece.png)
The state 1137 in the very top edge, almost dead center top, of the diagram. (I would give a svg, but Git doesn't like attaching svg, presumably because people abused the crap out of them.) Anyways, State 1137, transition on [87..88, 92] =['*', '/', '%'] to 1138 in C#; but in JS, the transition is on [85..89, 91..93]. Basically, ComputeReachSet() will return bogus edges for symbol 85='+'.

**Comment by ericvergnaud** [comment]
A redundant test certainly doesn’t improve performance, so I’d tend to promote elimination of the test altogether in all targets.

**Comment by kaby76** [comment]
And, forgot to mention, I'm checked multiple ways that I'm running 4.9.2. Ugh. Disappointing.

**Comment by ericvergnaud** [comment]
Can you provide me with the grammars and generated lexers parsers for Java and JavaScript and I'll look into it

**Comment by kaby76** [comment]
The grammar is at [grammars-v4/java/java](https://github.com/antlr/grammars-v4/tree/master/java/java) unedited. Attaching the files. For C#, the generated files are in the obj/ directory.
[save.zip](https://github.com/antlr/antlr4/files/6160801/save.zip)

**Comment by kaby76** [comment]
Adding validations to every operation in IntervalSet using collections.set. Nothing yet, but haven't gotten to splice, remove.

**Comment by kaby76** [comment]
Yep, somewhere along the way, this.atn.states[1137].transitions[0].label.intervals (where this is the parser object) gets mutated. It's fine starting out.

**Comment by kaby76** [comment]
Ah! It looks like the LL1Analyzer._LOOK() is propagating LA sets along one part of the automaton, from state 1216 to 1214 to 1139 to 1140--all okay, but now in computing "look" at 1140, obtained in LOOK() with predictionContextFromRuleContext(state=1216, ctx=null), the transition set on state 1137 is modified. Not only does this not occur In C#, but it does not make sense that an e-closure operation on a completely different part of the automaton would modify the IntervalSet on a completely different state. I'm wondering: Is IntervalSet supposed to be reuse across states? That doesn't make sense. I don't do this in the interpreter that I wrote using Antlr ATNs. It seems like there's a copy going on rather than a "new IntervalSet(other)".

**Comment by kaby76** [comment]
Oh yeah. There are a few diffs in `grep -R -i -e "new inter"`. Line 34 LL1Analyzer.js:

        const look = [];

Shouldn't it just be:

        look = new IntervalSet();

?

**Comment by ericvergnaud** [comment]
No, that part is correct, there is 1 IntervalSet per transition

**Comment by kaby76** [comment]
You're right. That's a "new IntervalSet[]" not "new IntervalSet()". Didn't grep the full thing.

**Comment by kaby76** [comment]
Well, this one doesn't look good.

C#

		protected int getAltThatFinishedDecisionEntryRule(ATNConfigSet configSet)
		{
			IntervalSet alts = new IntervalSet();
			foreach (ATNConfig c in configSet.configs)
			{
				if (c.OuterContextDepth > 0 || (c.state is RuleStopState && c.context.HasEmptyPath))
				{
					alts.Add(c.alt);

JS

    getAltThatFinishedDecisionEntryRule(configs) {
        const alts = [];
        for(let i=0;i<configs.items.length; i++) {
            const c = configs.items[i];
            if (c.reachesIntoOuterContext>0 || ((c.state instanceof RuleStopState) && c.context.hasEmptyPath())) {
                if(alts.indexOf(c.alt)<0) {
                    alts.push(c.alt);

In C#, "alts" is an IntervalSet, not an IntervalSet[]. In JS, it's an array. IntervalSet does have a Add() method. So this one does not make sense in JS.

**Comment by ericvergnaud** [comment]
The JS is actually more efficient, but there is a difference in getOuterContextDepth
Looks like this 2014 change never made it to the JS runtime (and probably Python)

**Comment by ericvergnaud** [comment]
false alert, it did, just implemented in a less tacky way

**Comment by ericvergnaud** [comment]
Found the issue, unrelated to the below

**Comment by kaby76** [comment]
Actually, it's kind of staring me in the face all along: Transition.label is being mutated. Labels in JS are "efficient" in that a copy is allocated by a "makeLabel()" call in the constructors and the object returned with the "getter" (actually no getter, just "label" field). In C#, it's allocated on each "Label" property get, no sharing. I'll make a quick change to see if that is it, in which case, I'll need to do a deep dive into when to actually make a copy of "label".

**Comment by ericvergnaud** [comment]
It's fixed. See PR3130

**Comment by ericvergnaud** [comment]
@kaby76 Thanks for the tough work of narrowing down the scenario.

**Comment by kaby76** [comment]
I always loved doing this stuff. The only good way to learn code. This seems like a nasty bug though. Hoping to see 4.9.3 in a few months. No hurries, but I'd expect others might be a b*tching.
