### ISSUE TITLE
JavaScript target for grammars-v4/java/java with input HSDB.java fails

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#3135]
The JavaScript target for grammars-v4/java/java/ with input HSDB.java fails for JavaScript, succeeds for CSharp. This is likely due to the issue https://github.com/antlr/antlr4/issues/3112. The PR addresses specifically the reuse of Interval--it performs clones of Interval but not IntervalSet itself, which is what I mentioned was being mutated. I hadn't verified and close the bug because I hadn't time until now.

**Comment by ericvergnaud** [comment]
Is it not fixed by #3130?

**Comment by kaby76** [comment]
Nope. Something else. Added defined and adding in clone() IntervalSet, but I only found one place that is a candidate. So, there's something else. No worries, will continue to debug.

**Comment by kaby76** [comment]
I added a clone to IntervalSet:

	clone() {
		var new_copy = new IntervalSet();
		for (let pos = 0; pos < this.intervals.length; pos++) {
			const existing = this.intervals[pos];
			var new_interval_copy = existing.clone();
			new_copy.addInterval(new_interval_copy);
		}
		return new_copy;
	}

Then, changed these lines:

LL1Analyzer.js:

                let set = t.label;
		if (set !== null) {
		    set = set.clone(); <<<<<<<<<<<<<<<<<<<<
                    if (t instanceof NotSetTransition) {
                        set = set.complement(Token.MIN_USER_TOKEN_TYPE, this.atn.maxTokenType);
                    }
                    look.addSet(set);
                }

And, IntervalSet:

	class SetTransition extends Transition {
	    constructor(target, set) {
		super(target);
		this.serializationType = Transition.SET;
		if (set !==undefined && set !==null) {
			var new_set = set.clone();
		    this.label = new_set;
		} else {
		    this.label = new IntervalSet();
		    this.label.addOne(Token.INVALID_TYPE);
		}
	    }

Now it works.

**Comment by ericvergnaud** [comment]
mmm…
it’s great that it solves the problem, but smells like there could be a deeper problem (and the below would just be a workaround)
I’m gonna be travelling for a week, but I’ll ok into it once settled

**Comment by kaby76** [comment]
As I mentioned in the other issue thread, a deep dive in the code on the actual of uses of IntervalSet's is required. You don't want to clone just on every damn read of the label field, otherwise the perf will likely suffer (but I haven't verified my opinion). Certainly, it's something that is ill-afforded with JavaScript, already quite slow. However, one of the uses of Transition.label is modifying what should be a read-only value. In any case, to reproduce, use `cd grammmars-v4/java/java; dotnet-antlr -m true -t JavaScript; cd Generated; make` in Ubuntu. I don't know enough about debugging with Node to be effective., because I don't know how to set a var change.

**Comment by kaby76** [comment]
You are correct, it was something else wrong here.

* In [LL1Analyzer](https://github.com/antlr/antlr4/blob/b5648f405b746d87ec559132ad1939fb6d402053/runtime/Java/src/org/antlr/v4/runtime/atn/LL1Analyzer.java#L225), `IntervalSet set = t.label();` does not perform a copy of the IntervalSet, and neither does addSet() below. So, "look" is intentionally being modified here. This change was wrong.

* In IntervalSet, ["set" is assigned directly to the field](https://github.com/antlr/antlr4/blob/b5648f405b746d87ec559132ad1939fb6d402053/runtime/Java/src/org/antlr/v4/runtime/atn/SetTransition.java#L20). There is no clone of the interval set. So, this change was also wrong.

* [IntervalSet.addInterval(toAdd)](https://github.com/antlr/antlr4/blob/master/runtime/JavaScript/src/antlr4/IntervalSet.js#L70) is the code that contains the error. There are three references to toAdd. In two references, you make a copy via clone(). However, for one case, you don't. Changing the code to `this.intervals.splice(pos, 0, toAdd.clone());` fixes the bug.

--Ken

**Comment by kaby76** [comment]
Yes, the IntervalSet was being mutated. No one would believe me. https://github.com/antlr/antlr4/pull/3275 fixes this file parse.
