### ISSUE TITLE
ANTLR not recognizing token that is also a part of another one?

### ISSUE THREAD

**Issue by jgalrito** [antlr/antlr4#3139]
I have the following lexer rules (among others):
```
EACH: [Ee] 'ach';
REACH: [Rr] 'each';
```

And the following input:
```{this} deals 1 damage to each creature and each player.```

And I'm getting the following error: ```line 65:48 mismatched input 'each' expecting {'those', EACH, THAT}``` (Javascript)

If I define the REACH rule *after* the EACH rule, it works fine.
Another weird thing is that I get no errors when using the ANTLR IntelliJ plugin, only on the javascript runtime

**Comment by KvanTTT** [comment]
Maybe it's JavaScript runtime bug because ANTLR selects the longest token in case of ambiguity, see https://stackoverflow.com/a/18420000/1046374

**Comment by ericvergnaud** [comment]
Please try the latest JS runtime which fixes a related bug

**Comment by KvanTTT** [comment]
@jgalrito please provide minimal reproducible grammar and an example or close the issue if it's already not actual.
