### ISSUE TITLE
Antlr Tool 4.9.2 generates uncompilable source code for Dart with a package name

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#3141]
* Go to [grammars-v4/kotlin/kotlin-formal](https://github.com/antlr/grammars-v4/tree/master/kotlin/kotlin-formal).
* Run the Antlr tool jar: `java -jar /tmp/antlr-4.9.2-complete.jar -Dlanguage=Dart -package org.antlr.grammars KotlinLexer.g4 KotlinParser.g4`. Note the package is specified in the pom.xml file.
* Now examine the generated KotlinParser.dart file. It contains `part 'KotlinParserLexer.dart';`. Unfortunately, that's wrong: there is no KotlinParserLexer.dart file. It's KotlinLexer.dart.

The source cannot be compiled. The workaround is to not use packages, at all, with the Dart target.

**Comment by kaby76** [comment]
The problem is [here](https://github.com/antlr/antlr4/blob/master/tool/resources/org/antlr/v4/tool/templates/codegen/Dart/Dart.stg#L59). The grammarName is "KotlinParser", since it's a split grammar. This template code is wrong. It might be worth looking at what Cpp does, because Dart requires something like `#include` statements for decls.

**Comment by KvanTTT** [comment]
A similar problem with lexer-only grammars (`lexer grammar TestLexer;`) and specified package name.
