### ISSUE TITLE
nested parenthesis problem

### ISSUE THREAD

**Issue by hlxxzt** [antlr/antlr4#3142]
Hi
I want to embed JavaScript statements in SQL, but I can’t solve the nested parentheses problem

e.g...

```
a = select * from users;

{
    let result = [];
    for (let item of a){
       let res = extend[item.name. startsWith('root') ? 'root' : 'user'].handle(item);
       if (res){
            result.push(res);
       }
    }
    return result;
}

b = select * from roles where uid in (result);
```

I tried:
```
scriptExpr: (any_char | bracket_body)+;
bracket_body: LBRACE (any_char | bracket_body)* RBRACE;
any_char: (~('{' | '}'))+;
```

but it cannot handle multiple nested parentheses

I just want to extract the JavaScript code in parentheses.then hand it over to the NodeJS VM module for processing

thanks

**Comment by ericvergnaud** [comment]
Hi,
please move this to the google discussion group
