### ISSUE TITLE
Confused on reportAttemptingFullContext() call on LL mode with Golang target

### ISSUE THREAD

**Issue by yunhailuo** [antlr/antlr4#3157]
### One test case (modified from "The Definitive ANTLR 4 Reference")
* Grammar
  ```
  grammar Ambig;

  stat: expr ';'        // expression statement
      | ID '(' ')' ';'  // function call statement
      ;

  expr: ID '(' ')'
      | INT
      ;

  INT :   [0-9]+ ;
  ID  :   [a-zA-Z]+ ;
  WS  :   [ \t\r\n]+ -> skip ;
  ```
* Source: "test.ambig"
  ```
  f();
  ```
* Code
  ```
	input, err := antlr.NewFileStream("test.ambig")
	if err != nil {
		log.Fatal(err)
	}

	lexer := NewAmbigLexer(input)
	stream := antlr.NewCommonTokenStream(lexer, 0)
	p := NewAmbigParser(stream)
	p.AddErrorListener(new(antlr.DiagnosticErrorListener))
	p.Interpreter.SetPredictionMode(antlr.PredictionModeLL)
	p.BuildParseTrees = true
	listener := new(BaseAmbigListener)
	antlr.ParseTreeWalkerDefault.Walk(listener, p.Stat())
  ```
* Actual behavior
  - See the following output with the code above, specifically `PredictionModeLL`
    ```
    line 1:3 reportAttemptingFullContext d=0 (stat), input='f();'
    line 1:3 reportAmbiguity d=0 (stat): ambigAlts={1, 2}, input='f();'
    ```
  - And see no output when using `PredictionModeSLL`
* Expected behavior: my understanding of the reference and the [method description in Java](https://www.antlr.org/api/Java/org/antlr/v4/runtime/DiagnosticErrorListener.html) is the output is expected in SLL mode since the two methods would be called for ambiguous cases but not LL mode. But if I understand `SetPredictionMode` correctly, I seem to get the opposite?

**Comment by ericvergnaud** [comment]
Please move this to the google discussion group

**Comment by yunhailuo** [comment]
> Please move this to the google discussion group

Thank you. Moved to https://groups.google.com/g/antlr-discussion/c/wj08BWW1_io Can you help me take a look

Close issue here.
