### ISSUE TITLE
Fix Go test suite

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#3175]
Currently the Go target has some problems that prevented from passing tests.  @Joakker and @prnvbn have agreed to help with the Go target so let's see if we can fix that first and then come back to https://github.com/antlr/antlr4/issues/2504

Here's a link to the [failing appveyor for Go](https://ci.appveyor.com/project/parrt/antlr4/build/job/t7k58ax1tidlimng):

```
...
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.antlr.v4.test.runtime.go.TestCompositeLexers
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.406 sec <<< FAILURE! - in org.antlr.v4.test.runtime.go.TestCompositeLexers
org.antlr.v4.test.runtime.go.TestCompositeLexers  Time elapsed: 0.406 sec  <<< ERROR!
java.lang.Exception: 
Non-zero exit while caching go runtime, output: go: go.mod file not found in current directory or any parent directory; see 'go help modules'
	at org.antlr.v4.test.runtime.go.TestCompositeLexers.groupSetUp(TestCompositeLexers.java:24)
...
```

Seems `go.mod` is missing whatever that is!

**Comment by Joakker** [comment]
Ok, this one should be pretty easy to implement. `go.mod` is a signature file that describes the directory and all it's children as part of a module. Recent versions of the go tool have migrated to using only modules by default, so more than likely that's why it's complaining. I'll open a PR shortly with the file added

**Comment by prnvbn** [comment]
Seems like running `go mod init` would be enough. Also @Joakker you might have to pull some weight before the 14th of May as I have University exams. After that, I will make up for it!

**Comment by Joakker** [comment]
Is ok, no worries 😃

**Comment by mitar** [comment]
Awesome. I can update my PR (https://github.com/antlr/antlr4/pull/3174) to get tests to pass there, too.

**Comment by parrt** [comment]
Comments from previous thread: https://github.com/antlr/antlr4/issues/2504#issuecomment-846481915
