### ISSUE TITLE
Feature request: (optional) better semantic for iterating over disjunctive lists

### ISSUE THREAD

**Issue by skef** [antlr/antlr4#3178]
(Note: I'm using the Cpp backend but I expect this is general to Antlr 4.)

This sort of grammar structure is very common:

```
foo:
     LBRACKET ( ( g | h ) i? )+ RBRACKET
     ;
```

When dealing with the resulting FooContext in a visitor it's natural to want to iterate through the inner list *as* a disjunctive list of "g-or-h and perhaps i". Unfortunately, (as far as I can tell) Antlr 4 will just put the g's, h's, and i's in their own vectors of different lengths, forcing you to either go down to the token level or "artificially" break the grammar out into separate contexts, as in:

```
fooElement:
    ( g | h ) i?
    ;

foo:
    LBRACKET fooElement+ RBRACKET
    ;
```

The latter is acceptable but annoying if you also hope to (for example) publish the Antlr grammar as a reference grammar.

It would be preferable if there was an extra unary operator one could apply to the "+" and "*" operators that would

1. Verify that there are no inner "or more" operators on what "+" or "*" are operating on (so that everything within the context occurs zero or one times).
2. Verify that the "or more" element itself occurs zero or one times.
3. Expand the vectors for the elements within the context to all be the same length with NULLs (or the equivalent) when the element is "missing".

If the first two conditions aren't met the operator would of course result in a generation-time error.

An alternate, and perhaps preferable, way of approaching the same problem would be to expand rule element labels to include such contexts, so that you can write:

```
foo:
     LBRACKET felem=( ( g | h ) i? )+ RBRACKET
     ;
```

This would add a vector called "felem" to the context where each element is something analogous to struct { GContext *g, HContext *h, IContext *i } which are NULL or non-null depending on whether the element is present, making it easier to just iterate through the elements. 

(If I'm wrong about there not being a better in-line solution for this, sorry for the issue-churn.)

**Comment by iterumllc** [comment]
> What would be the issue of using the children property?

Convenience, basically. The same argument for having separate identifiers beyond the children property in the first place. 

Since I filed this I've realized there are other factors that encourage splitting out grammatical elements into separate entries, and I guess I'm less convinced there's a quick path to "document-ready" grammars. So I'm personally at peace with breaking things out. I'll leave the idea here and folks can close this if they want to.
