### ISSUE TITLE
[C++] antlrcpp::Any incorrect behavior when storing std::string

### ISSUE THREAD

**Issue by Twinklebear** [antlr/antlr4#3194]
The `antlrcpp::Any` class does not properly handle storing std::string types in copy constructor/assignment. For example, this code:

```c++
#include <iostream>
#include <string>
#include "antlr4-runtime.h"

int main()
{
    antlrcpp::Any a = std::string("hello");
    antlrcpp::Any b = a;

    std::cout << "a = ";
    if (a.isNotNull()) {
        if (a.is<std::string>()) {
            std::cout << a.as<std::string>() << "\n";
        }
    } else {
        std::cout << "null\n";
    }

    std::cout << "b = ";
    if (b.isNotNull()) {
        if (b.is<std::string>()) {
            std::cout << b.as<std::string>() << "\n";
        }
    } else {
        std::cout << "null\n";
    }
    return 0;
}
```

Would be expected to print (and does if changed to use std::any):
```
a = hello
b = hello
```

However b does not get assigned the correct value from a and the above code actually prints:
```
a = hello
b = null
```

Wrapping the std::string in a pointer like std::shared_ptr yields the expected behavior; however it seems like the [condition on clone in Any](https://github.com/antlr/antlr4/blob/master/runtime/Cpp/runtime/src/support/Any.h#L135-L138) is too restrictive:

```c++
    template<int N = 0, typename std::enable_if<N == N && std::is_nothrow_copy_constructible<T>::value, int>::type = 0>
    Base* clone() const {
      return new Derived<T>(value);
    }
```

In looking into this I noticed that Boost's Any actually has [no restriction applied](https://www.boost.org/doc/libs/1_67_0/boost/any.hpp), which makes sense to me in terms of cloning any type to itself that is copy/move/etc constructible:

```c++
virtual placeholder * clone() const
{
    return new holder(held);
}
```

So could clone in Any just become this?
```c++
    Base* clone() const {
      return new Derived<T>(value);
    }
```

I changed this in my local build and it fixes the original issue, but I'm not sure if this has some potential side effects since I'm testing in a small codebase. If it seems ok, I can make this change and open a PR

**Comment by antonio2368** [comment]
I noticed the same thing after upgrading Antlr to a newer version (used 4.6 previously). 
Also, it's really hard to debug the problem if you're not aware, is there a reason why it randomly creates `antlrcpp::Any` with `nullptr` instead of simply not allowing the clone function to exist for move-only types?

Not sure why the `nothrow` restriction was put in place and I support making the PR with the fix if possible.

**Comment by Twinklebear** [comment]
I'm not sure, but I agree the silent failure mode makes this very difficult to track down. It also took me some time to realize this was the issue with handling string types in my interpreter. I ran the runtime tests and it looks ok, but if people do want to keep this restriction I'd actually vote for removing the version that returns a nullptr to make it a compile time error so at least folks can see something is wrong at compile time.

**Comment by efweber999** [comment]
Hi,

Can you clarify the modification to work around this issue? I tried commenting out the line:
template<int N = 0, typename std::enable_if<N == N && std::is_nothrow_copy_constructible<T>::value, int>::type = 0>
But then cmake errors out.

Thanks

**Comment by jcking** [comment]
@mike-lischke This should be resolved now that we switched to std::any

**Comment by wilderfield** [comment]
@jcking thanks for making this fix!
I see the commit here: https://github.com/antlr/antlr4/commit/70b2edcf98eb612a92d3dbaedb2ce0b69533b0cb#diff-477a7746713f8f33d2965e100b9c6bab160557ff9719c7854ce97300021d06da

Do you want to close this issue? Or do you want to wait for people to verify?

**Comment by mike-lischke** [comment]
A quick test after the new UTF8 impl is merged, would be good. After that we can close this issue here.

**Comment by KvanTTT** [comment]
I guess it can be closed now?

**Comment by mike-lischke** [comment]
I hoped @Twinklebear would do some tests, but ok. You can close it @KvanTTT .

**Comment by KvanTTT** [comment]
I can't close issues but @parrt or @ericvergnaud can :)

**Comment by mike-lischke** [comment]
@Twinklebear can as well :-)

**Comment by Twinklebear** [comment]
Yeah this can be closed, I ran into an issue testing it where ANTLR 4.9.3 still generates some older/removed members for some classes that have been removed in master so it hits some other non-any compile issue. However moving to std::any will fix the initial issue so I'll close this, and will try it out in 4.9.4. Thanks for fixing it @jcking !
