### ISSUE TITLE
Strange error recovering behavior

### ISSUE THREAD

**Issue by qoter** [antlr/antlr4#3202]
My grammar
```g4
grammar Simple;

prog: '{' declarationList '}'; 
declarationList: declaration+;
declaration : 'int' ID ';';

ID : [a-zA-Z]+ ;
WS : [ \t\r\n]+ -> skip ;
```

And my source code file:
```
{
    int x;
    y;;;
    int z;
    int t;
}
```
I try to parse my source code and expect that antlr recovered after invalid declaration ` y;;;` but parsing tree looks like this: 
![image](https://user-images.githubusercontent.com/13704520/121408092-6e149300-c979-11eb-8da1-7f7f0afa8919.png)

Notice if I replace rule `prog: '{' declarationList '}';` with `prog: '{' declaration+ '}';` I get fine parsing tree:
![image](https://user-images.githubusercontent.com/13704520/121408440-d95e6500-c979-11eb-9c3b-b597f1a1d552.png)

Why antlr can't handle errors better in the first case ` y;;;` ?

**Comment by ericvergnaud** [comment]
Hi,
please move this to the google discussion group.
