### ISSUE TITLE
Go target for Antlr tool, type ",int8" => "int8"

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#3204]
The reserved word table for the Go target contains a typo [here](https://github.com/antlr/antlr4/blob/cb4e59d420d5749d457a37b2652732b5969e5d67/tool/src/org/antlr/v4/codegen/target/GoTarget.java#L45). The string ",int8" should be "int8".

**Comment by marcauberer** [comment]
@kaby76 good catch! Fixed it in this pr: #3214
