### ISSUE TITLE
Provide .NET Framework target in the csharp nuget package

### ISSUE THREAD

**Issue by appel1** [antlr/antlr4#3212]
Currently the Antlr4.Runtime.Standard NuGet package only contains a netstandard 2.0 build. If you consume such a package targeting .NET Framework prior to 4.7.2 it adds additional dependencies that causes us some issues. Instead of working around those it would be easier if the C# runtime package included a .NET Framework 4.6.2 target. 

`<TargetFrameworks>net462;netstandard2.0</TargetFrameworks>`

We cannot upgrade to 4.7.2 or newer right now due to outside constraints for some of our projects.

**Comment by KvanTTT** [comment]
What issues? According to the [table](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) netstandard2.0 is compatible with .NET Framework >= 4.6.1.

**Comment by appel1** [comment]
It also says
> 2 The versions listed here represent the rules that NuGet uses to determine whether a given .NET Standard library is applicable. While NuGet considers .NET Framework 4.6.1 as supporting .NET Standard 1.5 through 2.0, there are several issues with consuming .NET Standard libraries that were built for those versions from .NET Framework 4.6.1 projects. For .NET Framework projects that need to use such libraries, we recommend that you upgrade the project to target .NET Framework 4.7.2 or higher.

What happens is that it pulls in additional dependencies, like System.Runtime.InteropServices.RuntimeInformation, that needs to be deployed and so on.

**Comment by appel1** [comment]
I'm fine with either. It compiles for .net 4.5 so I guess it makes sense to go for that.
