### ISSUE TITLE
JavaScript Target does not parse input as expected (arithmetic operations)

### ISSUE THREAD

**Issue by paulsobolev** [antlr/antlr4#3215]
We use `antlr 4.9.2` (both sides, npm package on UI, and `antlr-4.9.2-complete.jar` to generate target files)

Rules for Parser: 
```
expression  
            : expression operator=(MUL | DIV) expression #mulDivExp
            | expression operator=(ADD | SUB) expression #addSubExp
            | SUB? NUMBER #numericExp
            | OPEN_P expression CLOSE_P #parenthesisExp
            | FIELD #fieldExp
            ;
```

Code to test: 
```javascript
import antlr4 from 'antlr4'
import FormulaLexer from './FormulaLexer'
import FormulaParser from './FormulaParser'

function validateFormula(input) {
    console.log('INPUT: ', input)
    const chars = new antlr4.InputStream(input)
    const lexer = new FormulaLexer(chars)
    const tokens = new antlr4.CommonTokenStream(lexer)
    const parser = new FormulaParser(tokens)
    parser.buildParseTrees = true
    const tree = parser.resultExpression()
    console.log('TREE: ', tree.children)
}

validateFormula('-2\n') // OK
validateFormula('2 + 2\n') // Not OK, first child in tree is MulDivExpContext
validateFormula('2 - 2\n') // Not OK, first child in tree is MulDivExpContext
validateFormula('2 * 2\n') // OK
validateFormula('2 / 2\n') // OK
validateFormula('1 + 2 * 3 / 4\n') // Not OK, first child in tree is MulDivExpContext (instead of addSubExp), and input marked as invalid
```

Result: 
<img width="1085" alt="Screenshot 2021-07-02 at 17 19 16" src="https://user-images.githubusercontent.com/1773002/124288310-78860f00-db6a-11eb-8217-59324fd2584a.png">

Files to test (Source files, Parser.g4, Lexer.g4, and compiled files to run in browser): 
[formula-parser.zip](https://github.com/antlr/antlr4/files/6755141/formula-parser.zip)

Thanks in advance for any help or advice how to make it work!

**Comment by ericvergnaud** [comment]
Thanks, looks like a bug, I'll look into it sometimes next week

**Comment by ericvergnaud** [comment]
Hi,

closing this since:

1) your generated parser is not up to date with your grammar
2) issue is already solved using latest js runtime (not yet released)

**Comment by paulsobolev** [comment]
Hi, thanks for feedback!

> 1. your generated parser is not up to date with your grammar
I provided (by mistake) parser with more grammar rules which we use in our application, but these rules work fine.

> 2. issue is already solved using latest js runtime (not yet released)
Could you please estimate release time?
