### ISSUE TITLE
Generating files for a separated grammar

### ISSUE THREAD

**Issue by b1734** [antlr/antlr4#3223]
Hello!
I have a probably very simple question, but for some reason I just can't find a solution to it. I am trying to parse a C++ code for my project (I'm building a transpiler). The grammar for C++ is separated, namely it doesn't have a single .g4 file but it has two of them, CPP14Lexer.g4 and CPP14Parser.g4. How can I generate parser this way? When I used a singe .g4 file, I did it with this command in my command prompt:
`antlr4 -Dlanguage=Python3 -visitor GrammarName.g4`
Thank you very much for your help!

**Comment by ericvergnaud** [comment]
Hi,
please move this to the google discussion group.

**Comment by KvanTTT** [comment]
@ericvergnaud not only google discussion group, but GitHub discussions is also a suitable place.

**Comment by b1734** [comment]
> @ericvergnaud not only google discussion group, but GitHub discussions is also a suitable place.

Where is that located?

**Comment by KvanTTT** [comment]
https://groups.google.com/forum/#!forum/antlr-discussion
