### ISSUE TITLE
(Resubmitted) Generating files for a separated grammar

### ISSUE THREAD

**Issue by b1734** [antlr/antlr4#3227]
Hello!
I have a probably very simple question, but for some reason I just can't find a solution to it. I am trying to parse a C++ code for my project (I'm building a transpiler). The grammar for C++ is separated, namely it doesn't have a single .g4 file but it has two of them, CPP14Lexer.g4 and CPP14Parser.g4. How can I generate parser this way? When I used a singe .g4 file, I did it with this command in my command prompt:
`antlr4 -Dlanguage=Python3 -visitor GrammarName.g4`
Thank you very much for your help!

**NOTE:** I know, I have already submitted this issue here and a few people told me to move it to Google or GitHub discussions, which I did. But for a few days now I haven't gotten any replies there. So, I'm trying my luck here - I really need to find a solution to my problem fast.

**Comment by ericvergnaud** [comment]
This channel is for bugs only, you will not get support.

**Comment by b1734** [comment]
> This channel is for bugs only, you will not get support here.

Okay. Where can I get support then?
