### ISSUE TITLE
Python3 lexer file has implicit relative import of parser, which is not supported by Python3

### ISSUE THREAD

**Issue by SkittlePox** [antlr/antlr4#3230]
When antlr4 generates python3 lexer and parser files, it uses an *implicit* relative import of the parser from the lexer file:
```
# RLangLexer.py
...
from RLangParser import RLangParser
...
```
Apparently, this kind of import is a no-go for Python3, and at least `pytest` breaks when a test uses an imported file which itself tries to make an implicit relative import. The solution is simple, add a period to make it an *explicit* relative import:
```
# RLangLexer.py
...
from .RLangParser import RLangParser
...
```
This makes running `pytest` possible (and I presume running a listener which uses the lexer from outside the package). However, it breaks `pygrun` with an `ImportError`:
```
...
ImportError: attempted relative import with no known parent package
```
No fear, a simple fix to the`pygrun` file which updates the `__package__` global with the current working directory allows for `pygrun` to work with both implicit and explicit relative imports:
```
# pygrun
102     sys.path.append('.')
103     #print(sys.path)
104     p = os.path.basename(os.getcwd())        # New Code
105     globals().update({'__package__': p})     # New Code
106     
107     # print("Load Lexer {}".format(lexerName))
108     module_lexer = __import__(lexerName, globals(), locals(), lexerName, 1)
109     class_lexer = getattr(module_lexer, lexerName)
```

I can add the changes to `pygrun` to support these imports with a pull request, but I'm not sure how to change the initial generation of implicit relative imports in the lexer (which would add a `.` to the beginning of the parser module) without a post-processing script which adds a `.`. That would be quite messy. Is there an internal fix?

**Comment by ericvergnaud** [comment]
Hi,

the file to modify is:
 tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg

Eric

**Comment by SkittlePox** [comment]
Thanks Eric,

It appears that the listener template in Python3.stg has a working import rule:
```
...
ListenerFile(file, header, namedActions) ::= <<
<fileHeader(file.grammarFileName, file.ANTLRVersion)>
from antlr4 import *
if __name__ is not None and "." in __name__:
    from .<file.parserName> import <file.parserName>
else:
    from <file.parserName> import <file.parserName>
<header>
...
```
However the lexer file template doesn't even look like it imports the parser:
```
...
LexerFile(lexerFile, lexer, namedActions) ::= <<
<fileHeader(lexerFile.grammarFileName, lexerFile.ANTLRVersion)>
from antlr4 import *
from io import StringIO
import sys
if sys.version_info[1] > 5:
    from typing import TextIO
else:
    from typing.io import TextIO

<namedActions.header>

<lexer>
>>
...
```
Even though the actual generated lexer file does import the parser, as well as any other auxiliary libraries (I'm using antlr_denter):
```
#RLangLexer.py
...
from antlr_denter.DenterHelper import DenterHelper
from RLangParser import RLangParser
...
```
Is the parser import statement added via `<namedActions.header>`? But then why is there an import statement in the listener template? If I simply add the import statement to the stg template will I get a duplicate import in the lexer file?

**Comment by ericvergnaud** [comment]
check line 778 ?
Also notice the condition, maybe it needs to be removed ?

**Comment by SkittlePox** [comment]
I don't think that's it, the parser is not a superclass of the lexer, and even if the condition was satisfied we should expect to see
```
if __name__ is not None and "." in __name__:
    from .<superClass> import <superClass>
else:
    from <superClass> import <superClass>
```
in the lexer file, instead we see
```
from <file.parserName> import <file.parserName>
```
Now that I think more about it, where is the `antlr_denter` import coming from anyway (in my example)? My best guess is `<namedActions.header>`.

Can you point me to the code which uses the `.stg` templates to generate the actual files?

**Comment by ericvergnaud** [comment]
Suggest you try changing the stg and see how it goes ?

Envoyé de mon iPhone

**Comment by SkittlePox** [comment]
🤦  This is dumb, I realized that I defined a `@lexer::header` in my `lexer.g4` which has the import statements in it:
```
@lexer::header{
from antlr_denter.DenterHelper import DenterHelper
from RLangParser import RLangParser
}
```
It *was* coming from `<namedActions.header>`. That's what I get for copy-pasting boilerplate. Closing this issue, but my PR for the `pygrun` fix still makes sense to merge.
