### ISSUE TITLE
Upgrade to 4.9.2 unable to fail invalid input

### ISSUE THREAD

**Issue by mehrotraanand** [antlr/antlr4#3231]
While upgrading from ANTLR 4.6 to 4.9.2, we have noticed changed in parser behavior and some text which earlier didn't used to be matched gets matched with no change in grammar.

Some Negative input cases are working with lexer 
for example 

title eq "Emplyee" 1234

I have overridden sytaxError using

    lexer.addErrorListener(new BaseErrorListener()  {
        @Override
        public void syntaxError(Recognizer<?, ?> recognizer, Object offendingSymbol, int line, int charPositionInLine, String msg, RecognitionException e) {
            throw new RuntimeException(e);
        }
    });

as suggested in 
https://stackoverflow.com/questions/29834489/is-it-possible-to-throw-an-exception-if-the-input-isnt-valid?noredirect=1&lq=1

On debugging found that Lexer is not failing with runtime exception for bad input. 

We use Java for this implementation.

**Comment by mehrotraanand** [comment]
I am trying to resolve this issue caused by lexer not failing with runtime exception for bad input. Please let me know if you need any other information to debug this issue.

**Comment by ericvergnaud** [comment]
Please move this to the google discussion group
