### ISSUE TITLE
Python runtime is inconsistent with Java

### ISSUE THREAD

**Issue by Vladimir-Chan** [antlr/antlr4#3236]
Hello, I am analyzing c# source code with the grammar files in [grammar repository](https://github.com/antlr/grammars-v4/tree/master/csharp) by Python target. I converted the grammar actions to Python source. When I tested the grammar by a simple example, I got ParseCancellationException. After debugging, I find that the method `nextTokenOnChannel` in class `BufferedTokenStream` is inconsistent with Java. In Python, the comment says

> Return -1 if there are no tokens on channel between i and EOF.

While in Java, it says

> Return the index of the EOF token if there are no tokens on channel between {@code i} and EOF.

So, which is correct? Please give a consistent version, thx.

**Comment by ericvergnaud** [comment]
It's an inconsistency between the various runtimes.
Seems the 16/06/2014 change in the Java version was never ported to Python.
Might affect other runtimes, depending on which code base they used as a starting point.

**Comment by ericvergnaud** [comment]
Feel free to submit a PR

**Comment by Vladimir-Chan** [comment]
Ok I have pulled request
