### ISSUE TITLE
startRule() is not found in python target

### ISSUE THREAD

**Issue by Joxos** [antlr/antlr4#3244]
![image](https://user-images.githubusercontent.com/37507136/128619790-3b1f876c-ba88-426f-a022-621f2028d2b2.png)
In the document, I found that the example doesn't work.
![image](https://user-images.githubusercontent.com/37507136/128619830-09b2b1b9-8acc-444d-bad6-cad768e08a1d.png)
And the runtime is the newest.
![image](https://user-images.githubusercontent.com/37507136/128619901-0d8286c8-238d-40bb-a630-a66937e1f0ca.png)
If any other things are needed, I'm glad to provide them.
Waiting for help.

**Comment by ericvergnaud** [comment]
Please move this to the google discussion group
