### ISSUE TITLE
[JavaScript] Error: Module parse failed: Identifier '_alt' has already been declared

### ISSUE THREAD

**Issue by ninok** [antlr/antlr4#3260]
I'm trying to create a JavaScript parser for T-SQL using this grammar:
https://github.com/antlr/grammars-v4/tree/master/sql/tsql

Generation of the JS files works fine.
Nevertheless when trying to use them I always get:
```
ERROR in ./build/TSQLParser.js 9997:17
Module parse failed: Identifier '_alt' has already been declared (9997:17)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|                   this.state = 1106;
|                   this._errHandler.sync(this);
>                   let _alt = this._interp.adaptivePredict(this._input,7,this._ctx)
|                   while(_alt!=2 && _alt!=antlr4.atn.ATN.INVALID_ALT_NUMBER) {
|                       if(_alt===1) {
```

I get the same error without using webpack as well (i.e. node with "type": "module").

- [x] I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [x] I have done a search of the existing issues to make sure I'm not sending in a duplicate

**Comment by ericvergnaud** [comment]
I believe this is already fixed, which tool version are you using?

**Comment by ninok** [comment]
Hi @ericvergnaud,
I just newly setup my environment, so I have all the latest versions:
- Antlr 4.9
- Node 14.17.5
- Webpack 5.51.1

Do you maybe have the link for the previous issue so that I can check if it's the same.

**Comment by ericvergnaud** [comment]
Hi,

latest version is 4.9.2, please try it. It does not generate any `let _alt = ...`.

**Comment by ninok** [comment]
Thanks a lot. This fixed the issue.

One nite though. I used the getting started guide and it explicitely says `curl -O https://www.antlr.org/download/antlr-4.9-complete.jar`, so I was assuming that's the latest stable release.

Shouldn't this be updated? Or ideally the 4.9 should be a symlink to the latest patch version so that the getting started guide does not need to change for every patch release.
