### ISSUE TITLE
DELETED (moved to discussion group)

### ISSUE THREAD

**Issue by jeancallisti** [antlr/antlr4#3263]
### **DELETED (moved to discussion group)**

System : **Windows 10** 
Terminal : Command line

**Scenario :** 

1.  Created all the CLASPATH, PATH and other aliases
2.  Created simple grammar (see below)
3. Generated it  : antlr4 -visitor -no-listener -o ./outputJava -Dlanguage=Java MyGrammar.g4
4. Built it in the output folder : javac MyGrammar*.java
4.  Ran this : 
          grun SectraGrammar line -tree 
5. I can now type whatever I want into the Terminal. Unlike other noobs, I **do** type something.
6. I press return. Nothing happens. Silly me, unlike more noobs I **do** press **Ctrl+D**
7. ^D appears in the Terminal.
8. **PROBLEM**: Nothing else gets displayed. **No tree,** no message.
9. SAME ISSUE with -gui instead of -tree. No reaction from grun.

**Grammar :** 
```
grammar MyGrammar;

line : instruction ;
instruction : 
      QUIT
    | operation ;

operation  : 
    SYMBOL OPERATOR NUMBER_INT 
    | SYMBOL OPERATOR SYMBOL;

QUIT            : Q U I T;

NUMBER_INT     : [0-9]+ ;
SYMBOL         : [a-zA-Z0-9]+ ;

OPERATOR       : 
    A D D ;

WS                  : (' '|'t'|'r'? 'n' | 'r')+ -> skip ;


fragment A:('a'|'A');
fragment B:('b'|'B');
...
```

**Comment by ericvergnaud** [comment]
Please move this to the google discussion group
