### ISSUE TITLE
Drop Python2 runtime support

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#3266]
Python2 is not officially supported since January 1st, 2020: https://www.python.org/doc/sunset-python-2/

I think now it's time to stop supporting it in ANTLR because it consumes additional resources.

Also, there are a lot of code in common between Python2 and Python3 runtimes.

**Comment by ericvergnaud** [comment]
PyPi says it is still in use.

**Comment by KvanTTT** [comment]
In this case, older versions of ANTLR are still available.

**Comment by KvanTTT** [comment]
Already done.
