### ISSUE TITLE
Closure error message while compiling Rfc5322 grammar

### ISSUE THREAD

**Issue by rpinchbeck** [antlr/antlr4#328]
I converted the Rfc5322 grammar (Internet Message Format) from Abnf to Antlr using my AbnfToAntlr tool (http://sourceforge.net/projects/abnf-to-antlr).

The resulting grammar causes a compile error...

> rule 'obs_body' contains a closure with at least one alternative that can match an empty string

Rfc5322 allows for an empty string as the message body.  Why is this considered an error in the grammar?

Here is an excerpt from the converted Rfc5322 grammar to reproduce the problem...

``` antlr
// Internet Message Format (RFC 5322)
//
// ABNF grammar extracted from http://tools.ietf.org/html/rfc5322

grammar rfc5322excerpt;

start           : obs_body;

obs_body        :   ((lf* cr* ((U_0000 | text) lf* cr*)*) | crlf)*;

text            :   CL_A | CL_B;  // remaining characters omitted for clarity

crlf           :  cr lf;
                    // Internet standard newline

lf             :  LF;
                    // line feed

cr             :  CR;
                    // carriage return

//////////////////////////////////////////////////////////////////////////
// Lexer rules generated for each distinct character in original grammar
// per http://www.unicode.org/charts/PDF/U0000.pdf
//////////////////////////////////////////////////////////////////////////

LF : '\u000A';
CR : '\u000D';
CL_A : 'A';
CL_B : 'B';
U_0000 : '\u0000';
```

**Comment by Zudark** [comment]
start
    : relacionalExpression
    ;

relacionalExpression
    : term relop term 
    | term
    ;

relop
    : EQ | GT | LT | LE | GE | NEQ
    ;

term
    : factor relop factor | 
    | factor
    ;


factor
    : LPAREN relacionalExpression RPAREN
    | atom
    ;

atom
    : ID
    | NUMBER
    | LPAREN relacionalExpression RPAREN
    ;
/*
letter : ('a'..'z')|('A'..'Z')+ ;

number : ('-')?('0'..'9')+('.')('0'..'9')+ ( E('ADD'|'MINUS')?('0'..'9')+) ; */

bool_gram
    : expr_boolean
    ;


expr_boolean
    : bool_term bool_op bool_term
    | bool_term
    ;

bool_op
    : OR
    | AND
    ;

bool_term
    : boolean
    | expr_boolean
    | unary_op bool_term
    ;

unary_op
    : NOT
    ;

 The following sets of rules are mutually left-recursive [expr_boolean, bool_term]

please help

**Comment by xied75** [comment]
@rpinchbeck Sorry for commenting in an old issue here. Any chance you could put your Abnf to Antlr on GitHub other than sourceforge? That would be great for the community.

**Comment by rpinchbeck** [comment]
@xied75 The Abnf-To-Antlr project has moved to GitHub...
[https://github.com/rpinchbeck/Abnf-To-Antlr](https://github.com/rpinchbeck/Abnf-To-Antlr)
