### ISSUE TITLE
Invalid Python3 syntax in Lexer when using @lexer::members

### ISSUE THREAD

**Issue by PeterTillema** [antlr/antlr4#3281]
If you have something like this in your g4 file:
```
@lexer::members
{
	boolean maybeString = false;
}
```
then outputting Python3 yields invalid syntax:

```python
boolean maybeString = false;
```

which is clearly wrong. Also, all the actions use `maybeString = true/false;`, which is wrong for 3 reasons: `true/false` should be `True/False`, semicolon should be removed and it should be `self.maybeString` otherwise it's not defined.

**Comment by ericvergnaud** [comment]
Just write self.maybeString = False in your grammar

**Comment by PeterTillema** [comment]
Well, fine, that works at least.
