### ISSUE TITLE
Antlr4 shows weird behavior on a simple lexer grammar (grammar file is included)

### ISSUE THREAD

**Issue by manbaum** [antlr/antlr4#3293]
Antlr4 shows weird behavior on a simple lexer grammar.

Let we have the following definitions.

- `LC` is a lower case letter.
- `UC` is a upper case letter.
- `C` is a letter in either lower or upper case.
- `LID` is a `LC` followed by zero or more `C`s.
- `UID` is a `UC` followed by zero or more `C`s.
- `ID` is either a `LID` or a `UID`.
- `Q` is a `ID` or several `ID`s separated by `'.'`.
- `M` is a `UID`.
- `N` is a `ID`.
- `QNAME` has 3 parts: a `Q`, followed by a `M`, then followed by a `N`.

In order to clarify what contents are in the 3 parts of a `QNAME`, some actions are performed.

Before the acceptance of `Q`, we mark the position of input stream.

When `Q` has been accepted, we inspect the input stream
and capture the characters from the marked position to current position,
then save the captured content into a variable.

The same processes are performed on `M` and `N` also.

When `QNAME` has been recognized, we display the collected result.

For input `"aaa.Bb.ccc"`, we are like to see: `q = "aaa"`, `m = "Bb"`, and `n = "ccc"`.
That's Ok, Antlr4 also gives us the right answer.

For input `"dddd.Bbb.Ccc"`, we expect: `q = "dddd"`, `m = "Bbb"`, and `n = "Ccc"`.
Surprisingly, Antlr4 gives us this result: `q = "ddd"`, `m = ".B"`, and `n = "Ccc"`.

What's wrong?

P.S. I am using Antlr 4.9.2.

Grammar file (Test.g4):
```antlrv4
lexer grammar Test;

@header {
package test;
}

@members {
private int mark = 0;
private String q, m, n;

private void clear() {
    q = m = n = null;
}

private void mark() {
    mark = _input.index();
}

private String str() {
    return _input.getText(Interval.of(mark, _input.index() - 1));
}

private void setQ() {
    q = str();
}

private void setM() {
    m = str();
}

private void setN() {
    n = str();
}

private void display() {
    System.out.println("- " + getText() + "\n  => " + q + " | " + m + " | " + n);
}
}

QNAME           : { clear();   }
                  { mark();    } Q { setQ(); } '.'
                  { mark();    } M { setM(); } '.'
                  { mark();    } N { setN(); }
                  { display(); }
                ;
WS              : [ \t\f\r\n] -> skip
                ;

fragment LC     : [a-z]+
                ;
fragment UC     : [A-Z]+
                ;
fragment C      : LC
                | UC
                ;
fragment LID    : LC C*
                ;
fragment UID    : UC C*
                ;
fragment ID     : LID
                | UID
                ;
fragment Q      : ID ('.' ID)*
                ;
fragment M      : UID
                ;
fragment N      : ID
                ;
```

Test input file (TestQName.txt):
```text
aaa.Bb.ccc
dddd.Bbb.Ccc

ddd.Bbb.Ccc
aaaa.Bb.ccc

ddddd.Bbb.Ccc
aaaaa.Bb.ccc
```

Output of the grun tool:

```text
$ rlwrap ./grun.sh test.Test tokens -tokens TestQName.txt
- aaa.Bb.ccc
  => aaa | Bb | ccc
- dddd.Bbb.Ccc
  => ddd | .B | Ccc
- ddd.Bbb.Ccc
  => ddd | Bb | cc
- aaaa.Bb.ccc
  => aaa | .B | .ccc
- ddddd.Bbb.Ccc
  => ddd | d. | .Ccc
- aaaaa.Bb.ccc
  => aaa | a. | b.ccc
[@0,0:9='aaa.Bb.ccc',<QNAME>,1:0]
[@1,11:22='dddd.Bbb.Ccc',<QNAME>,2:0]
[@2,25:35='ddd.Bbb.Ccc',<QNAME>,4:0]
[@3,37:47='aaaa.Bb.ccc',<QNAME>,5:0]
[@4,50:62='ddddd.Bbb.Ccc',<QNAME>,7:0]
[@5,64:75='aaaaa.Bb.ccc',<QNAME>,8:0]
[@6,77:76='<EOF>',<EOF>,9:0]
```

**Comment by ericvergnaud** [comment]
Please move this to the google discussion group

**Comment by manbaum** [comment]
> 
> 
> Please move this to the google discussion group

I suspect it's a bug.
