### ISSUE TITLE
Make C++17 required for ANTLR C++ runtime

### ISSUE THREAD

**Issue by jcking** [antlr/antlr4#3330]
Making C++17 required for the ANTLR C++ runtime would allow usage of `std::string_view`, `std::any`, and many other additions. Using `std::any` would allow for potentially removing `antlrcpp::Any` and `std::string_view` would enable removing needless copying of strings at various locations of the runtime including the generated parsers/lexers.

**Comment by mike-lischke** [comment]
I actually expect a PR for switching to std::any, but I lost track of who wanted to do that and post a PR. But I'm all for that switch.

**Comment by jcking** [comment]
I took a stab at getting rid of `antlrcpp::Any`, but I quickly found out that it is not compatible with `std::any`. `std::any` only supports casting to the same type that it was constructed with. `antlrcpp::Any` allows dynamic_cast. The only way out is to ultimately break source compatibility. IMO we should deprecate all the non-std::any compatible features, wait a bit, then remove it. Up to you though, not sure what ANTLR's policy is on that.

**Comment by mike-lischke** [comment]
The thing is: there's only a single release per year, usually. Waiting would mean to delay the change by at least a year. Instead, we should just go ahead and switch. The older versions are still available for some time, if someone needs the old functionality.

**Comment by jcking** [comment]
That certainly makes things easier. I will then just switch antlrcpp::Any to std::any after #3335. Then proceed to replace std::string with std::string_view where applicable, especially in generated code to avoid making copies of strings literals that already have static storage duration.

**Comment by jcking** [comment]
Fixed now.
