### ISSUE TITLE
ANTLR C++ runtime is not thread safe

### ISSUE THREAD

**Issue by jcking** [antlr/antlr4#3332]
There are a few locations in the ANTLR C++ runtime which are not thread safe and can trigger undefined behavior. This includes mutations to `match_calls` in `LexerATNSimulator`, `globalNodeCount` in `PredictionContext`, and `s0` in `DFA`. These should be made into atomic operations or mutation exclusion should be used.

**Comment by mike-lischke** [comment]
Given the PR you posted, does it makes sense to have this issue open?

**Comment by jcking** [comment]
It should be runtime safe now, but is probably not optimal. That is a separate issue though.
