### ISSUE TITLE
Antlr4 JavaScript target not work even for the simple case

### ISSUE THREAD

**Issue by usstwxy** [antlr/antlr4#3348]
I have a verified(in antlr4 tool in Intellij) g4 grammar and want to make it work in Javascript.
The grammar g4 works in the typescript antlr4ts lib but failed in the official antlr4 js lib.

I tried a simple ID +|-|*|/ ID case using the following g4 definition and got the same weird error:
```
line 1:2 mismatched input '+' expecting {'+', '-', '*', '/'}
```

My codes

DlrLexer.g4
```
lexer grammar DlrLexer;

// Identifier
ID:	Letter LetterOrDigit*
	;

fragment
Letter
	:	[a-zA-Z_]
	;

fragment
LetterOrDigit
	:	[a-zA-Z0-9_]
	;
  
ADD : '+';
SUB : '-';
MUL : '*';
DIV : '/';

// Ignore space, tab, and newline
WS: [ \t\r\n]+ -> skip;
```

DlrParser.g4
```
parser grammar DlrParser;

options {
  tokenVocab = DlrLexer;
}

expression
  : ID
  | expression op=(MUL | DIV) expression
  | expression op=(ADD | SUB) expression
  ;
```

Command to generate  javascript code:
```
antlr4 -Dlanguage=JavaScript -o ../antlr4 DlrLexer.g4 && antlr4 -Dlanguage=JavaScript -lib ../antlr4 -o ../antlr4 -visitor DlrParser.g4
```

JS code to run
```
const chars = new InputStream("a + b");
const lexer = new DlrLexer(chars);
const tokens = new CommonTokenStream(lexer);
const parser = new DlrParser(tokens);
parser.buildParseTrees = true;
console.log("expression", parser.expression());
```

Library version
```
"antlr4": "^4.9.2"
```

It looks like that the generated code or runtime library is not correct. I've tried to debug it but have no idea on the generated code.

**Comment by ericvergnaud** [comment]
Please check against 4.9.3, which was just published

**Comment by usstwxy** [comment]
Thanks. Switch to 4.9.3 or 4.9.1 the issue would be same as https://github.com/antlr/antlr4/issues/606, which could be resolved by adding an entry in parser.
