### ISSUE TITLE
parsing token by token or parsing chunk by chunk of text

### ISSUE THREAD

**Issue by JessicaLopezEspejel** [antlr/antlr4#3361]
Hello, how can I use your parser to work as I explain in the following lines?

``` 
code = 'System'
code = 'System.'
code = 'System.out'
code = 'System.out.' 
code = 'System.out.println' 
code = 'System.println('
code = 'System.println("hello")
```

It means, the parser should be able to detect that the java syntax is doing well at each time I add one or more tokens. 

Thank you in advance.

**Comment by ericvergnaud** [comment]
Hi,
Please move this to the google discussion group and close.
