### ISSUE TITLE
The parseFile method  of the InterpreterDataReader class is missing code: "line = br.readLine();"

### ISSUE THREAD

**Issue by Tinker1024** [antlr/antlr4#3375]
target information : Java
The parseFile method  of the InterpreterDataReader class before check the code "if (line.equals("channel names:"))", missing code "line = br.readLine();"
The source code like this:
![image](https://user-images.githubusercontent.com/89579246/144011801-a0585faf-e9ee-4f47-9257-72de490d5208.png)
The code we're expecting like this:
![image](https://user-images.githubusercontent.com/89579246/144012586-627fd4f2-87b6-483f-af8c-36684a6b9f09.png)

**Comment by ericvergnaud** [comment]
Hi, please provide some context and a reproducible example

**Comment by Tinker1024** [comment]
[InterpTestFile.txt](https://github.com/antlr/antlr4/files/7624870/InterpTestFile.txt)
Use the InterpTestFile.txt file above，My test method is as follows:
/**
 *
public class TestInterpreterDataReader {
	@Test
	public void test() throws NoSuchFieldException, IllegalAccessException {
		final ClassLoader loader = Thread.currentThread().getContextClassLoader();
               // pay attention to the path where the InterpTestFile.txt is stored.
		final URL stuff = loader.getResource("org/antlr/v4/test/runtime/InterpTestFile.txt");
		InterpreterDataReader.InterpreterData interpreterData = InterpreterDataReader.parseFile(stuff.getPath());
		Field ruleNames = interpreterData.getClass().getDeclaredField("ruleNames");
		Field channels = interpreterData.getClass().getDeclaredField("channels");
		Field modes = interpreterData.getClass().getDeclaredField("modes");
		ruleNames.setAccessible(true);
		channels.setAccessible(true);
		modes.setAccessible(true);
		List<String> ruleNamesList = (List<String>) ruleNames.get(interpreterData);
		List<String> channelsList = (List<String>) channels.get(interpreterData);
		List<String> modesList = (List<String>) modes.get(interpreterData);
		Assert.assertEquals(5,ruleNamesList.size());
		Assert.assertEquals(5,channelsList.size());
		Assert.assertEquals(1,modesList.size());
	}
}
 */
Before the code “line = br.readLine(); ” was added
![image](https://user-images.githubusercontent.com/89579246/144029010-134182d9-b3db-4bb7-b7f2-f3526d5a8d86.png)

After the code “line = br.readLine(); ” was added，The test case is passed!
