### ISSUE TITLE
Log4j vulnerability for ANTLR4

### ISSUE THREAD

**Issue by antony-george-ibm** [antlr/antlr4#3428]
Hello,
I can see that while building ANTLR4 tool, log4j v1.2.17 is getting downloaded as seen in logs below . Just wanted to confirm whether or not ANTLR4 is affected by the security vulnerabilities of log4j.
```

[INFO] Downloading from central: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.pom (22 kB at 2.7 MB/s)
.
.
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.12/log4j-1.2.12.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.12/log4j-1.2.12.pom (145 B at 29 kB/s)

```

Thanks,

Antony

**Comment by ericvergnaud** [comment]
Hi,
no ANTLR4 does not have any dependency on log4j.
Chances are that what you are seeing is triggered my maven itself relying on log4j.

**Comment by antony-george-ibm** [comment]
Thanks for the response
