### ISSUE TITLE
Introduce MIX_OF_LOWER_AND_UPPER_CHAR_CASE_IN_RANGE warning

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#3433]
Consider the following set: `[A-z]`. Most likely it's an incorrect definition because the range

```
ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxy
```

contains nonimplied characters:

```
[\]^_`
```

Correct and clear definition: `[A-Za-z]`.

If these characters are implied, they can be added explicitly:

```
[A-Za-z[\\\]^_`]
```

I suggest adding at least a new warning `MIX_OF_LOWER_AND_UPPER_CHAR_CASE_IN_RANGE`. It's especially actual if use [the `caseInsensitivity` option](https://github.com/antlr/antlr4/pull/3399). Or name it as `RANGE_PROBABLY_CONTAINS_NOT_IMPLIED_CHARACTERS`.

@parrt what do you think?

**Comment by parrt** [comment]
Hmm...yes, this does seem like it could cause strange errors. On the other hand, has this ever come up? Usually I try to avoid work unless it's solving a known problem haha.

**Comment by KvanTTT** [comment]
I've encountered the error during fixing `caseInsensitive` option. Moreover, I think it is quite a real case, it's quite intuitive but wrong definition. That's why it should be fixed.

**Comment by parrt** [comment]
Understood. Well I would welcome a PR :)   I'd definitely love to get the case insensitive option merged so I can try to review some of your other work...I start work for my new galactic overlord on 4 January and it would be nice to get a stable set up...

**Comment by KvanTTT** [comment]
It would be good to take a look at this PR while I'm fixing the rest case insensitive issues: https://github.com/antlr/antlr4/pull/3349 It resolves a lot of issues including character ones (but it should be merged after case insensitive PR).

**Comment by KvanTTT** [comment]
I started testing our grammars-v4 and encountered some subtle cases with the current warning that related to Unicode ranges. Probably I was too fast about the correct solution here, but I'll resolve it (restrict to ANSI characters) or revert it tomorrow.
