### ISSUE TITLE
Go runtime missing export of "Reset()"

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#3441]
Could the Go target (commonly referred to as "Golang" in order to appease web search engines) runtime be changed to export [reset()](https://github.com/antlr/antlr4/blob/667631bb651a2e625f39988f193d08eddccd1c4e/runtime/Go/antlr/lexer.go#L121)? It's exported for the other runtimes, but Go requires an uppercased-first-letter func name in order for it to be visible.

**Comment by KvanTTT** [comment]
Could you please suggest a PR?

**Comment by kaby76** [comment]
[PR 3442](https://github.com/antlr/antlr4/pull/3442)

**Comment by kaby76** [comment]
This seems to have been fixed at some point. https://github.com/antlr/antlr4/blame/master/runtime/Go/antlr/v4/lexer.go#L122
