### ISSUE TITLE
Add compile-time errors/warnings for use of incompatible lexer commands

### ISSUE THREAD

**Issue by sharwell** [antlr/antlr4#348]
- ANTLR should produce a compile-time error if a lexer rule contains both a `skip` command and a `type` command.
- ANTLR should produce a compile-time error if a lexer rule contains both a `skip` command and a `more` command.
- ANTLR should produce a compile-time error if a lexer rule contains both a `skip` command and a `channel` command.
- ANTLR should produce a compile-time warning if a lexer rule contains both a `more` command and a `type` command.
- ~~ANTLR should produce a compile-time warning if a lexer rule contains both a `more` command and a `channel` command.~~ Edit: this should work fine.

**Comment by KvanTTT** [comment]
I guess this issue can be closed for now. Related: https://github.com/antlr/antlr4/issues/1388
