### ISSUE TITLE
Antlr4.Standard.Runtime 4.9.3 throws System.IO.FileLoadException in unit tests, 4.9.2 or earlier does not

### ISSUE THREAD

**Issue by KatMacomi** [antlr/antlr4#3490]
This is about a C# project: we have a class library (.Net Standard 2.0) that references Antlr4.Runtime.Standard 4.9.3, and a MSTest unit test project (.Net Framework 4.7.2) that tests functionality from that class library.

With Antlr4.Standard.Runtime 4.9.2, everything works. But when we upgrade to 4.9.3, unit tests that reference code that requires Antlr starts failing, with "System.IO.FileLoadException : Could not load file or assembly 'Antlr4.Runtime.Standard, Version=4.9.3.0'Culture=neutral, PublicKeyToken=e78b2c5abd1fcb3f' or one of its dependencies. Strong name signature could not be verified. The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key.". The file is there in the bin/Debug folder, however. We tried adding a reference to Antlr in the unit test project as well, but that didn't work.

In non-unit test projects (like a console application calling the exact same methods from our Antlr-using class library), there is no issue, and in a small NUnit test project we created there is also no issue.

Considering it does work in 4.9.2 (and in the versions we've used before this), and in 4.9.3 for everything but MSTest unit test projects, we strongly suspect this is a bug. I didn't find anyone having this exact issue, although #3360 might be related?

We have replicated the issue in a small attached project: if you run ConsoleApp1 or the test in the NUnit project TestProject1, there is no problem, but if you run the same code for UnitTestProject1, it throws the exception. Setting the version back to 4.9.2 allows it to run perfectly fine in UnitTestProject1 as well. I hope this helps you figure out and fix the issue, thanks for all your work!
[4.9.3FileLoadErrorExample.zip](https://github.com/antlr/antlr4/files/7871656/4.9.3FileLoadErrorExample.zip)

**Comment by KvanTTT** [comment]
https://github.com/antlr/antlr4/issues/3360
