### ISSUE TITLE
Appveyor build removed but Appveyor doesn't know that

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#3504]
With [this commit](https://github.com/antlr/antlr4/commit/82ace5fb4516d79e18515e45102740f1bf516939) two weeks ago, Appveyor was removed from CI builds. Could someone log into Appveyor and delete the project so Appveyor knows, and antlr4/ can get back to a clean CI builds? Thanks.

**Comment by ericvergnaud** [comment]
Done
