### ISSUE TITLE
Change "$self" to "$parser" in "target agnostic grammars" instructions

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#3508]
This is pretty critical.

The instructions for ["Target agnostic grammars"](https://github.com/antlr/antlr4/blob/896f90b22c485dfa5082c2e8fa8b2ec1326c726a/doc/python-target.md?plain=1#L109) are not correct. Following the [third option](https://github.com/antlr/antlr4/blob/896f90b22c485dfa5082c2e8fa8b2ec1326c726a/doc/python-target.md?plain=1#L123), after adding field "self" to a base class, and using `$self` in an action, the Antlr tool will output `"unknown attribute reference self in $self"`. In fact, there is no "$self" attribute. If one changes this to "self" (without the dollar sign), then the instructions would "work". But, as fate sometimes works, I tried something else.

If one changes `$self` to `$parser`, skip adding a field "self" to the base class altogether, "target agnostic" for a parser grammar will work for all but two targets! Note, this is only good for parser grammars. I don't think there is an equivalent "$lexer" for lexer actions, which really would be needed for actions in the lexer grammar. Or, really introduce "$self" for either lexer or parser actions.

The [documentation for attributes](https://github.com/antlr/antlr4/blob/master/doc/actions.md#parser-rule-attributes) really needs to include a discussion of "$parser". I don't know why it's missing because this attribute works.

Note, it's currently impossible to get a grammar with actions with a common syntax to work across all targets--at least for 4.9.3--but it is close using "$parser"--at least for a parser grammar. I would actually call the technique "not-quite target-agnostic grammars" because the common syntactic approach does not work for Cpp and PHP where there are include file issues and the non-conversion of "." to "->" for a pointer reference (see attached zip file for a proof of the technique working for CSharp, Dart, Go, Java, JavaScript, Python3). I have not tested "target agnostic grammars" for the old Antlr4cs port, which people shouldn't even be using at this point.
[target-agnostic2.zip](https://github.com/antlr/antlr4/files/7935242/target-agnostic2.zip)

**Comment by RossPatterson** [comment]
Since I had to work all this out too, and found @kaby76's description above so helpful, I made an attempt at closing this out.  Since this is my first commit to the project, I'd appreciate a review of my changes in my own repo, before I create the PR.  Please take a look at https://github.com/antlr/antlr4/compare/master...RossPatterson:antlr4:issue_3508.  Thanks.

**Comment by kaby76** [comment]
@RossPatterson Looks fine. Obviously, it would be nice to really fix the code for a target-independent object reference, but updating the instructions will help.

**Comment by RossPatterson** [comment]
While looking for something else in the ANTLR source, I found [commit 38c4e2b0028d2a305d0cf05ce5669d23d67ea88e](https://github.com/RossPatterson/antlr4/commit/38c4e2b0028d2a305d0cf05ce5669d23d67ea88e), from late 2014, which changed the name of the `$self` attribute to `$parser`.  The doc had never caught up.

**Comment by parrt** [comment]
Can you point me to where in the documentation you say `$self`? A grep doesn't find anything

**Comment by ericvergnaud** [comment]
It’s already fixed I think

**Comment by kaby76** [comment]
The new instructions in [antlr4/doc/python-target.md](https://github.com/antlr/antlr4/blob/2e23faa8e9679588567354429ce567c1c58f680d/doc/python-target.md#target-agnostic-grammars) look fine.

I do wish there was a "$lexer" for lexer grammar actions, but "$parser" works great at least for parser grammars. And, actually, because a few reasons, I still had to resort to a workaround:
* In grammars-v4, for grammars requiring the superClass option, keep "this." object references [e.g., here](https://github.com/antlr/grammars-v4/blob/7c6607bfc0facd14a74afc99c0fbe10658441859/python/python/PythonLexer.g4#L137).
* Run a Python script to modify the grammar *per target* to what it should be, [e.g., this](https://github.com/antlr/grammars-v4/blob/7c6607bfc0facd14a74afc99c0fbe10658441859/python/python/Cpp/transformGrammar.py)
* Provide a readme to instruct folks to run the script [e.g., here](https://github.com/antlr/grammars-v4/blob/7c6607bfc0facd14a74afc99c0fbe10658441859/python/python/Cpp/README.md).
* Add a check to call the script in the build, [e.g., here](https://github.com/antlr/grammars-v4/blob/7c6607bfc0facd14a74afc99c0fbe10658441859/_scripts/templates/Cpp/makefile#L5).

I had to resort to the workaround for several reasons--"target-agnostic grammars" isn't really possible yet:
* There's no "$lexer." object reference method call rewrite.
* "$parser." does not rewrite to "this->" for a generated C++ parser.
* The Cpp target does not generate `#include's` of the superClass base classes. The only way for a compilation to work is to manually add `@header {#include "baseparser.h"}`, [e.g. here](https://github.com/antlr/grammars-v4/blob/7c6607bfc0facd14a74afc99c0fbe10658441859/python/python/PythonLexer.g4#L32).

Admittedly, it is a hack, but it fits into a build.
