### ISSUE TITLE
Why there is no Vocabulary and VocabularyImpl in the Python3 target?

### ISSUE THREAD

**Issue by DavidShilol** [antlr/antlr4#3536]
Target information:
- Python3 target
- antlr4-python3-runtime 4.9.2

Question:
There is no "Vocabulary" and "VocabularyImpl" in Python3 target, just tokenNames. Why is that different from other language target? And the key point is what is the equivalent of "Vocabulary" and "VocabularyImpl" by using tokenNames?

Here is a comparison of some usage examples:
[Java vocabulary](https://github.com/antlr/antlr4/blob/ad29539cd2e94b2599e0281515f6cbb420d29f38/runtime/Java/src/org/antlr/v4/runtime/Recognizer.java#L67)
[Python3 tokenNames](https://github.com/antlr/antlr4/blob/ad29539cd2e94b2599e0281515f6cbb420d29f38/runtime/Python3/src/antlr4/Recognizer.py#L53) 
It seems like "vocabulary" and "tokenNames" do the same thing in Recognizer.tokenTypeMapCache. But there is no method "getTokenNames()" in python3. I can only find the implementation from [JavaScript target](https://github.com/antlr/antlr4/blob/ad29539cd2e94b2599e0281515f6cbb420d29f38/runtime/JavaScript/src/antlr4/Recognizer.js#L40).

I'm newer to antlr4 and need some answers about:
- Why there is no Vocabulary and VocabularyImpl in the Python3 target?
- What is the equivalent of "Vocabulary" and "VocabularyImpl" by using tokenNames?
- How can I get tokenNames in python3 because of lack of Recognizer.getTokenNames()?

**Comment by ericvergnaud** [comment]
Hi,

please move this support question to the google discussion group
