### ISSUE TITLE
Incorrect type of token with number 0xFFFF because of incorrect ATN serialization

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#3555]
### Grammar

```g4
lexer grammar L;
T_FFFF: 'FFFF' -> type(65535);
```

### Input

```
FFFF
```

### Actual result

```g4
[@0,0:3='FFFF',<-1>,1:0]
```

But `-1` value is reserved for `EOF`

### Expected result

```g4
[@0,0:3='FFFF',<65535>,1:0]
```

**Comment by parrt** [comment]
Yeah, seems we need to limit token types to 0..0xFFFE

**Comment by KvanTTT** [comment]
I don't think it's the best solution because `0xFFFF` is also a valid value (ANTLR can be used as a binary parser). Especially considering ANTLR in future will handle all range of int and `0xFFFF` will be puncture point in this case. I suggest resolving the problem together with the introduction of a new serialization format https://github.com/antlr/antlr4/discussions/3494

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/pull/3591
