### ISSUE TITLE
[Go] "go test" does not pass

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#3557]
This seems to be a problem with some code that wasn't updated with ATN serialization/deserialization.

Unfortunately, I don't think the tests are performed in CI builds. `cd runtime/Go/antlr4; go test`. Honestly, these Go-specific tests probably should not even go here, but it is what it is, and I'm continuing the tradition.

	ken@DESKTOP-DL44R7B:/mnt/c/msys64/home/Kenne/current/antlr4/runtime/Go/antlr$ go test
	panic: Could not deserialize ATN with version 3 (expected 4).

	goroutine 1 [running]:
	github.com/antlr/antlr4/runtime/Go/antlr.(*ATNDeserializer).checkVersion(0x678980)
		/mnt/c/msys64/home/Kenne/current/antlr4/runtime/Go/antlr/atn_deserializer.go:87 +0xdd
	github.com/antlr/antlr4/runtime/Go/antlr.(*ATNDeserializer).DeserializeFromUInt16(0xc00011a2a0, {0x678980, 0x7fffffff, 0x10})
		/mnt/c/msys64/home/Kenne/current/antlr4/runtime/Go/antlr/atn_deserializer.go:52 +0x7d
	github.com/antlr/antlr4/runtime/Go/antlr.init()
		/mnt/c/msys64/home/Kenne/current/antlr4/runtime/Go/antlr/testing_lexer_b_test.go:44 +0x672
	exit status 2
	FAIL    github.com/antlr/antlr4/runtime/Go/antlr        0.005s

I'll fix the code. Blocked on another Go PR because of this.

**Comment by jimidle** [comment]
Can this issue be closed now?

**Comment by kaby76** [comment]
Not quite. A "go get golang.org/x/exp/slices" is required and that modifies the go.mod file.
```
$ go test
lexer_action_executor.go:7:8: no required module provides package golang.org/x/exp/slices; to add it:
        go get golang.org/x/exp/slices

Kenne@DESKTOP-DL44R7B MINGW64 ~/tem3/antlr4/runtime/Go/antlr
$ go get  golang.org/x/exp/slices
go: added golang.org/x/exp v0.0.0-20220722155223-a9213eeb770e

Kenne@DESKTOP-DL44R7B MINGW64 ~/tem3/antlr4/runtime/Go/antlr
$ go test
PASS
ok      github.com/antlr/antlr4/runtime/Go/antlr        0.274s

Kenne@DESKTOP-DL44R7B MINGW64 ~/tem3/antlr4/runtime/Go/antlr
$ git status
Refresh index: 100% (2256/2256), done.
On branch dev
Your branch is up to date with 'origin/dev'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   go.mod

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        go.sum

no changes added to commit (use "git add" and/or "git commit -a")

Kenne@DESKTOP-DL44R7B MINGW64 ~/tem3/antlr4/runtime/Go/antlr
$ cat go.mod
module github.com/antlr/antlr4/runtime/Go/antlr

go 1.18

require golang.org/x/exp v0.0.0-20220722155223-a9213eeb770e // indirect
```

Shouldn't the dependency should be declared in the go.mod file?

@parrt The runtime now depends on go 1.18. Does this require any new minor or major versions numbers for the Antlr release, i.e., now Antlr 5, or Antlr 4.11?

**Comment by KvanTTT** [comment]
Honesly, I suggest getting rid of pure runtime tests and introducing a new way to describe tests with specific runtime code, see [Consolidate runtime tests](https://github.com/antlr/antlr4/pull/3775). It will help us to keep runtimes in sync. For me, the syntax described in https://github.com/antlr/antlr4/issues/1045#issuecomment-1216250170 matches the best.

**Comment by kaby76** [comment]
Sounds fine. Some of the "tests" in the Antlr Go runtime there don't even seem to actually test data structures. For example, atnconfigset_test.go has `func TestCompare(t *testing.T)`, but it doesn't actually make any use of "t". (WTF, I wrote this crap?! I thought the compiler would flag as error any variable that is unused.)

**Comment by jimidle** [comment]
I’ll check the go.mod. I thought this had been done. I don’t need that
locally.

Depending on 1.18 shouldn’t need bumping ANTLR but the go runtime should
increment. If we want to keep the go runtime version the same as the ANTLR
version, then it will mean no go runtime updates without the whole of ANTLR
updating.

**Comment by jimidle** [comment]
The go.mod file is updated and go.sum is now included in the repo, as it should be.

I think that the pure go runtime tests will be useful, but they are not very substantial as they stand. they do not have to reside in the main package, they can be in a test package.

**Comment by parrt** [comment]
I'm ok changing to 4.11 from 4.10.2 as it's "major" but if interface is same maybe 4.10.2 makes sense?

**Comment by parrt** [comment]
I changed to 4.11.  oh and I need to change in pom.xml also.  @jimidle happy to get a PR for that as I'm heading to sleep ;)

**Comment by jimidle** [comment]
No problem, I will change the POM file.

The Go tag will need to be v4.11.0 but only Go will use it, so there can be
a 4.11 tag as well of course.

Jim

**Comment by jimidle** [comment]
@parrt This can be closed now. The go test does pass, even if the tests don't really do that much and probably should be expanded greatly. 

Go pretty much requires that _test versions of a source reside along side the source they are testing. We could make external tests work, but that would not be the go 'way'.
