### ISSUE TITLE
"ambiguous call to overloaded function" error occur when compile antlr4-cpp-runtime-4.9.3 into x64 target with vs2017

### ISSUE THREAD

**Issue by Byzero512** [antlr/antlr4#3585]
1. When I use vs2017(compile target arch is x64) to compile cpp runtime, errors occur ("antlr4-cpp-runtime-4.9.3-source\runtime\src\parser.cpp(481): error C2668: 'antlr4::misc::IntervalSet::contains': ambiguous call to overloaded function").
2. these errors do not occur when the target's arch is x86.

**Comment by michalwidera** [comment]
https://github.com/conan-io/conan-center-index/blob/master/recipes/antlr4-cppruntime/all/conanfile.py#L68-L72
This is known issue with MSVC. There will be no fix for 4.9.3.
Take newer compiler.
