### ISSUE TITLE
do we need this C++ ATN serialization?

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#3592]
Hi @mike-lischke and @jcking I think only the ANTLR tool itself needs the ATN serialization; the targets only need deserialization.  can we get rid of this file?

https://github.com/antlr/antlr4/blob/dev/runtime/Cpp/runtime/src/atn/ATNSerializer.cpp

**Comment by mike-lischke** [comment]
I never used that class, but it helped me with writing custom deserializers at some point. However, if I ever need that again, I can look at the Java implementation. So IMO this file can go.

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/pull/3591
