### ISSUE TITLE
Generating XPath lexer/parser

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#3600]
Heh, we have a problem with the build system related to the XPath parsers for all of the various targets. It looks like in the java target I avoided a circular dependency (gen 4.10 parser for XPath using 4.10 which needs it to build) by hand building the parser: runtime/Java/src/org/antlr/v4/runtime/tree/xpath/XPath.java. I see the following files that should be regenerated using either the previous version or the current somehow:

```
runtime/Cpp/runtime/src/tree/xpath/XPathLexer.g4
runtime/CSharp/src/Tree/Xpath/XPathLexer.g4
```

Then I see that there is a version in the python targets but those don't have a grammar.

Any suggestions about how to resolve this? @ericvergnaud @mike-lischke @jcking  I'm pretty sure the Python ones fails. I get `Exception: Could not deserialize ATN with version  (expected 4).`

I'm in the process of building python files to automate the build. For example here is the start of my code to update the version number in the various files: 

https://github.com/antlr/antlr4/blob/a6644ee8a112a3a08e4ad5debc81960c6270d450/scripts/update_antlr_version.py

Might be as simple as adding something to an overall python release program to run ANTLR on these XPath grammars.

**Comment by mike-lischke** [comment]
Would be much better if the just built tool would generated the XPath stuff. It is pretty isolated and not used by the rest of the tool, correct? So maybe the XPath build can be moved into an own utility package, built after the main tool is done? I would much prefer if no previous build of the tool is required to build the next one.

Also, isn't it about time to remove all ANTLR3 references from ANTLR4?

**Comment by KvanTTT** [comment]
Related topic: https://github.com/antlr/antlr4/issues/3549

> Also, isn't it about time to remove all ANTLR3 references from ANTLR4?

Unfortunately, it's impossible for the current time. ANTLR4 use ANTLR3 for parsing and traversing, see https://github.com/antlr/antlr4/tree/master/tool/src/org/antlr/v4/parse

**Comment by parrt** [comment]
@mike-lischke yeah, I think since it hasn't been a problem until now, when we changed the ATN serialization, I will simply build those few files manually and check them in. I we'll take your C++ area g4 file and place it into the Python area as well, unless @ericvergnaud  indicates that he used a different one

**Comment by parrt** [comment]
I am updating the human script and hopefully will automate the process of simply generating the lexers. I have copied over the C# grammar and modified for the python targets. it appears to work for the tests in Python3.

**Comment by parrt** [comment]
@ericvergnaud Never mind about looking for the grammar as I was able to convert the C# one :)

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/pull/3599
