### ISSUE TITLE
PHP Export Unable to Create Member Variables (unable to use $ literal)

### ISSUE THREAD

**Issue by jonathan-shahen** [antlr/antlr4#3604]
Here is an example use case (limited depth of nested expressions):

```
grammar T;

@members {
  private $depth = 0;
}

parse
 : expr EOF
 ;

expr
 : {++depth <= 3}? '(' expr ')' 
 | INT
 ;

INT
 : [0-9]+
 ;
```

You can ignore the Semantic Predicate, because we cannot even declare the member variable due to the `$` being used.
The error message is: `attribute references not allowed in lexer actions: $depth`.

If we replace `$depth = 0;` with `depth = 0;`, then it compiles the php class, but the member variable is malformed (php variables require the `$`).

Is there a work around here to get this to work?

I found a work around for referencing variables in actions (`$parser->var` ==> `$this->var`), which is not the best work around but I will leave that for a separate ticket.

Target: PHP
ANTLR Version: 4.9.2
Runtime: 0.5.1 (had to downgrade to get working, see https://github.com/antlr/antlr-php-runtime/issues/19)
Original Ticket: https://github.com/antlr/antlr-php-runtime/issues/21
Suggested Code Region: https://github.com/antlr/antlr4/blob/master/tool/resources/org/antlr/v4/tool/templates/codegen/PHP/PHP.stg

Any help would be appreciated :)

**Comment by parrt** [comment]
@marcospassos should it be `\$` to escape `$` for antlr and pass to php?

**Comment by marcospassos** [comment]
Do you mean in a PHP string? If so, you can either use single quotes like `'$foo'` (that doesn't interpolate) or `"\$foo"`.
