### ISSUE TITLE
Lexer.getCharIndex() return value not behaving as expected

### ISSUE THREAD

**Issue by tianshuang** [antlr/antlr4#3606]
- [x] I have reproduced my issue using the latest version of ANTLR
- [x] I have asked at [stackoverflow](https://stackoverflow.com/questions/71645433/antlr4-lexer-getcharindex-return-value-not-behaving-as-expected)
- [x] Responses from the above seem to indicate that my issue could be an ANTLR bug
- [x] I have done a search of the existing issues to make sure I'm not sending in a duplicate

Language: Java
ANTLR Version: 4.9.3

```
parser grammar TestParser;

options { tokenVocab=TestLexer; }

root
    : LINE+ EOF
    ;
```

```
lexer grammar TestLexer;

@lexer::members {
    private int startIndex = 0;

    private void updateStartIndex() {
        startIndex = getCharIndex();
    }

    private void printNumber() {
        String number = _input.getText(Interval.of(startIndex, getCharIndex() - 1));
        System.out.println(number);
    }
}

LINE:                          {getCharPositionInLine() == 0}? ANSWER SPACE {updateStartIndex();} NUMBER {printNumber();} DOT .+? NEWLINE;
OTHER:                         . -> skip;

fragment NUMBER:               [0-9]+;
fragment ANSWER:               '( ' [A-D] ' )';
fragment SPACE:                ' ';
fragment NEWLINE:              '\n';
fragment DOT:                  '.';
```

Execute the following code:
```java
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.Lexer;
import org.antlr.v4.runtime.tree.ParseTree;

public class TestParseTest {

    public static void main(String[] args) {
        CharStream charStream = CharStreams.fromString("( B ) 12. hahaha\n"+
                "( B ) 123. hahaha\n");
        Lexer lexer = new TestLexer(charStream);

        CommonTokenStream tokens = new CommonTokenStream(lexer);
        TestParser parser = new TestParser(tokens);
        ParseTree parseTree = parser.root();

        System.out.println(parseTree.toStringTree(parser));
    }

}
```

The output is as follows:
```
12
12
(root ( B ) 12. hahaha\n ( B ) 123. hahaha\n <EOF>)
```

Expected output:
```
12
123
(root ( B ) 12. hahaha\n ( B ) 123. hahaha\n <EOF>)
```

**Comment by kaby76** [comment]
I've traced this down to the main lexer automaton, ExecATN(). In that code, there are a [few lines to check if there was a transition from a DFAState "s" and symbol "t" previously computed](https://github.com/antlr/antlr4/blob/97c793e446ba70e4e63f84e6c2bffd5fffd961a5/runtime/CSharp/src/Atn/LexerATNSimulator.cs#L184-L188). If so, the old value is used. The problem is that the old state contains a list of ATNConfig that records the actions that need to be executed. Those actions contain offsets that need to be recomputed. The easiest fix is to just recompute the DFAState from scratch. That will create a new list of ATNConfig with the correct offsets.

The following code fixes the problem.

    bool IsCandidate(DFAState target)
    {
        var es = target?.configSet?.Elements;
        foreach (var e in es)
        {
            if (e != null && e is LexerATNConfig l)
            {
                var lae = l.getLexerActionExecutor();
                if (lae == null) return false;
                foreach (var x in lae.LexerActions)
                {
                    if (x is Atn.LexerIndexedCustomAction) return true;
                }
            }
        }
        return false;
    }

ExecATN() is now modified thus:

                // As we move src->trg, src->trg, we keep track of the previous trg to
                // avoid looking up the DFA state again, which is expensive.
                // If the previous target was already part of the DFA, we might
                // be able to avoid doing a reach operation upon t. If s!=null,
                // it means that semantic predicates didn't prevent us from
                // creating a DFA state. Once we know s!=null, we check to see if
                // the DFA state has an edge already for t. If so, we can just reuse
                // it's configuration set; there's no point in re-computing it.
                // This is kind of like doing DFA simulation within the ATN
                // simulation because DFA simulation is really just a way to avoid
                // computing reach/closure sets. Technically, once we know that
                // we have a previously added DFA state, we could jump over to
                // the DFA simulator. But, that would mean popping back and forth
                // a lot and making things more complicated algorithmically.
                // This optimization makes a lot of sense for loops within DFA.
                // A character will take us back to an existing DFA state
                // that already has lots of edges out of it. e.g., .* in comments.
                DFAState target = GetExistingTargetState(s, t);
                if (target == null || IsCandidate(target))
                {
                    target = ComputeTargetState(input, s, t);
                }

With the call to IsCandidate(), the state is recomputed if the state contains ATNConfig that are index-sensitive actions. With the change, the actions for the problem are performed perfectly.

**Comment by parrt** [comment]
wow! holy crap. thanks for all the analysis @kaby76 and @tianshuang !!  Seems like easiest fix is to disable DFA caching in the presence of the actions. Would slow that rule down a bit but...

**Comment by parrt** [comment]
Hi. It appears to have been my intention, or at least a result of how I handle actually decided to match lexer rows.  please see my comment here: https://github.com/antlr/antlr4/issues/3611. I am updating the documentation to be more explicit in this case.

**Comment by kaby76** [comment]
In the meanwhile, I will add a check to Trash to warn when there is a mix of plain actions and semantic predicates. People do not read documentation. If they want to do that, they should rewrite actions into code that returns true and performs a side-effect.

**Comment by kaby76** [comment]
Indeed, a check should be implemented--it will save on a lot of headaches. The check should test mixing actions and predicates across all uses of the lexer symbols--not just within one lexer rule--as trying to do so still breaks (I tested).

**Comment by kaby76** [comment]
Right, it only affects lexer rules. There's no queue data structure on the parser side, only on the lexer side. And, I've already tested parser rules--you can mix actions and predicates.

**Comment by kaby76** [comment]
I'll check to see if placing the action in a predicate fixes this getCharIndex() problem. If so, then we don't need to change ExecATN().

**Comment by KvanTTT** [comment]
I suspect `ACTION_SHOULD_BE_PLACED_TO_THE_END_OF_LEXER_RULE` should be thrown in the following samples:

```g4
lexer grammar ACTION_SHOULD_BE_PLACED_TO_THE_END_OF_LEXER_RULE;
@members {String s = "";

// Action
void a(String x) {
    s += x;
}

// Predicate
boolean p() {
    return !s.equals("");
}}

// No warnings
OR: 'or1' {a("or1");} | 'or2' {a("or2");};
AND: 'and1' 'and2' {a("and1" + "and2");};
PREDICATE: 'predicate' {p()}? {a("predicate");};
ACTIONS: 'actions' {a("action1");} {a("action2");};

// Warnings
AND_W: 'and_w1' {a("and_w1" + "and_w2");} 'and_w2';
CLOSURE_W: ('closure_w' {a("closure_w");})+;
PREDICATE_W: 'predicate_w' {a("predicate_w");} {p()}?;
OPTIONAL_W: 'optional_' {a("optional_w");} 'w'?;

WS: [ \r\n]+;
```

**Comment by KvanTTT** [comment]
Yes, you are right. I've updated my sample with recursive (action is performed once) and fragment rule.

**Comment by KvanTTT** [comment]
> But, I would think we'd have to make sure one doesn't interleave the actions and predicates across rules, e.g., A : B { a(); }; B : 'b' { b() }?;

Could you clarify what's unexpected in this sample? It looks like action is executed after predicate as it described. I have another interesting sample:

```g4
lexer grammar L;
@members {String s = "";}
A: '(' B')';
B: 'b' {s += "b";};
END: 'end' {System.out.println(s);};
WS: [ \r\n]+;
```

In this case ref action is not executed at all. By the way we have [`FRAGMENT_ACTION_IGNORED`](https://github.com/antlr/antlr4/issues/472) warning for fragment rules but it's also actual for rules that have refs.

**Comment by kaby76** [comment]
Sorry, I meant `A : { a(); } B; B : 'b' { b() }?;`. Here the writer thought `a()` would be executed first, then `b()`, because that's how it would be executed in parser rules, but it's not that way with lexer rules. My point is that a check/error/warning message must look across lexer rules, not only within a single rule. That's all.

**Comment by KvanTTT** [comment]
```g4
A : { a(); } B; B : 'b' { b() }?;
```

In this case my first assumption works fine without subrules analysing: action should be placed to the end of lexer rule. I think it matters even without predicates since code within action may use internal lexer state (current position).

**Comment by kaby76** [comment]
Sorry. For some reason, I thought when debugging the lexer ExecATN() that actions were queued up from sub-rules. They're not. You are right, they're not even executed. Yes, a warning would be good here.

I'm not sure it's really necessary to force (or just warn??) users to change from this `A : { a(); } 'a' { b(); } 'b' ;` to this `A : 'a' 'b' { a(); } { b(); };` or this `A : 'a' 'b' { a(); b(); };`. It only needs to happen if there's a semantic predicate somewhere in that rule, right?

**Comment by KvanTTT** [comment]
> It only needs to happen if there's a semantic predicate somewhere in that rule, right?

I don't think so. Consider the following grammar:

```g4
lexer grammar L;
A: {System.out.print(getCharPositionInLine());} 'A' {System.out.print(getCharPositionInLine());};
```

It prints `11` on input `A`. But it should print `01` if actions are executed in expected order. Actions might rely on lexer state and should be moved to the end regarless of semantic predicates using.

**Comment by kaby76** [comment]
Wonderful. For CSharp, I don't get "11" but "01".
```
lexer grammar LLexer;
A:
 {System.Console.WriteLine("first " + this.CharIndex);}
 'A'
 {System.Console.WriteLine("second " + this.CharIndex);}
 ;
```
```
parser grammar LParser;
options { tokenVocab = LLexer; }
file : A+ EOF;
```
But, yes, for Java, it's "11".

What a friggin' mess.

**Comment by KvanTTT** [comment]
Interesting. Does the mix of semantic predicates and actions work sequentially for C#?

**Comment by kaby76** [comment]
Well, that is for sequential actions only. I haven't tested it with sequential predicates. I use C#. I prefer to not use primitive language and environment Java (although they are starting to finally get with it, but they will never fix the JVM to "reposition the instruction pointer and go!", the main reason I hate Java with a passion). I get the same result with or without the modifications I gave above to LexerATNSimulator.ExecATN(). That's why I've been saying there are two different bugs here in C#. Now we have another.

**Comment by KvanTTT** [comment]
Sorry, it looks like everything works fine, `getCharIndex` should be used instead of `getCharPositionInLine` for Java and other runtimes

```g4
A: {System.out.print(getCharIndex());} 'A' {System.out.print(getCharIndex());};
```

It prints `01` as C#.

**Comment by ericvergnaud** [comment]
Maybe it's a good time to unify these ? (getCharPositionInLine is definitely much better than getCharIndex)

**Comment by KvanTTT** [comment]
Sorry, I started discussion about action/predicate order in wrong topic. Correct topic is #3611. The current topic is about incorrect working of  `getCharIndex` (or action execution?). Semantic predicates are not required at all for repoducing:

```g4
lexer grammar L;

@lexer::members {private int startIndex = 0;}

LINE: {startIndex = getCharIndex();} LETTER {System.out.println(_input.getText(Interval.of(startIndex, getCharIndex() - 1)));} SLASH;
fragment LETTER: [a-z]+;
fragment SLASH: '-';
```

It prints `aabb` instead of `aabbb`.

**Comment by KvanTTT** [comment]
> Maybe it's a good time to unify these ? (getCharPositionInLine is definitely much better than getCharIndex)

They are different, `getCharIndex` returns linear index starts from the beginning of file. `getCharPositionInLine` returns index from the beginning of the current line and it looks like it's being updated after matching of token.

**Comment by ericvergnaud** [comment]
I was referring to unify the names across runtimes

**Comment by KvanTTT** [comment]
There are similar methods accross runtimes: `CharIndex` for C#, `getCharIndex()` for Java etc.

**Comment by kaby76** [comment]
I'm not sure how much can be done coordinating the names in the runtime fields/method/properties across targets. The least that can be done is to have a nice table to refer to or an IDE plugin that implements the table.

**Comment by parrt** [comment]
hi guys. Trying to dive into this conversation but there's a lot going on.  first, let me clear up some spell misconceptions about the interaction of semantic predicates and actions.   No semantic predicate is evaluated during prediction that is hidden by an action. further, semantic predicates are not evaluated during prediction if syntax on is sufficient to make decisions. for example,

```
y: ({a = true;} {a}? A | {b = true;} {b}? B);
```

No semantic predicates need to be evaluated to distinguish between A and B. Further, they can't be evaluated anyway because they are hidden by actions.  any action is assumed to be a side effect that affects the semantic predicates. 

The following example always matches the first alternative because these semantic predicates are hidden by the actions:

```
y: ({a = true;} {a}? A | {b = true;} {b}? A);
```

Here is a case where semantic predicates are evaluated to resolve a syntactic ambiguity:

```
y: ({a}? A | {b}? A);
```

This is not unexpected behavior either:

```
x: y | z;
y: A {false}?;
z: A;
A: 'a';
```

y and z are both 'a' which is a syntactic ambiguity for rule x.  That means that the first alternative will be given precedence in x. The semantic predicate is not evaluated becauseIt is hidden by the token. See https://github.com/antlr/antlr4/blob/master/doc/predicates.md#finding-visible-predicates

which starts with "*The parser will not evaluate predicates during prediction that occur after an action or token reference.*"

By moving the predicate, it now gets evaluated to resolve the syntactic ambiguity, forcing the second alternative to match.

```
x: y | z;
y: {false}? A;
z: A;
A: 'a';
```

**Comment by parrt** [comment]
When it comes to the evaluation of actions in the lexer, I can't remember the details but there is definitely only so much context that we can recreate. Remember that the actions are only executed after the entire rule has been matched, but we try to execute them in the right context.

**Comment by KvanTTT** [comment]
It looks like I implemented correct `ACTION_SHOULD_BE_PLACED_AFTER_PREDICATES` warning here: https://github.com/antlr/antlr4/pull/3626 I've checked for possible cases and added tests.

**Comment by parrt** [comment]
I'm not sure a warning is warranted there. The rule is clear and i might want the pred evaluated after prediction in that spot.

**Comment by KvanTTT** [comment]
> The semantic predicate is not evaluated becauseIt is hidden by the token.

But it's evaluated anyway later and failed predicate exception is raised if it returns false: `line 1:1 rule y failed predicate: {p()}?`

Could you elaborate on an example where pred evaluation after prediction is useful? Moreover, I don't completely understand why `FailedPredicateException` was introduced and where it's useful. There are no examples in docs as well (only examples with predicates at the beginning of alternative).

**Comment by parrt** [comment]
Well, If you provide a predicate it should be evaluated at some point; it can't be ignored.  the discovery of semantic predicates is complicated by the fact that it can look through multiple rules and sub rules when making a decision. So it might be hidden in one case and not hidden in another, depending on where that rule is refer to and what the parsing decision is.

So the idea is that if you give a predicate it's like an assert, but it can also be hoisted into the prediction decision to help disambiguate things.   I can't think of a great example that isn't better done with a separate semantic phase, but you might do something like:

```
varRef : ID {isDefined($ID.text)}? ;
```

**Comment by parrt** [comment]
I just read My coauthors implementation of context sensitive lexer actions.  it looks like only the index in the character stream is reset before the actions are executed; no other context is saved or restored.  So it sounds like getCharIndex() is the only thing we can rely on in an action, other than user-defined code.

I suppose there is value in actions in loops like:

```
A : ('a' {n++;})+ ;
```

But, it really does confuse people... honestly I'm not sure if I have enough of this remembered in my head now to make an accurate decision about what to do here.

**Comment by KvanTTT** [comment]
I don't understand why it was closed.

**Comment by kaby76** [comment]
> I don't understand why it was closed. It should be reopened.

Github seems to have a "feature" that automatically close issues when it parses "fixes pound-sign-number" or "fixed pound-sign-number" in a `git commit -m "message"`. Apparently, this is the "much better new way, not dumb old-school way" of ~~software engineering~~, ~~software development~~, ~~specifying~~, ~~designing~~, hacking--add "features" that we didn't ask for, add "features" we don't want, provide no tracking of the "features" added, add new bugs in the process, and do it "whenever we want".

**Comment by KvanTTT** [comment]
> Github seems to have a "feature" that automatically close issues when it parses "fixes pound-sign-number" or "fixed pound-sign-number"

Yes, I know about this feature, it's convenient in general. But I don't think such a message was in `dev` branch, maybe ref but not fix, we didn't fix the current issue.

**Comment by KvanTTT** [comment]
Got it. I see [the commit](https://github.com/antlr/antlr4/commit/8e5f2ffabdd55100d33f9a70af0fdef6b9b0a943)

```
 update doc to be more explicit about the interaction between lexer actions and semantic predicates
```

But it actually doesn't related to the current issue since the issue is about incorrect working of `getCharIndex`, it's [reproducable](https://github.com/antlr/antlr4/issues/3606#issuecomment-1089216028) even without semantic predicates. The issue should be reopened.

**Comment by parrt** [comment]
Sorry about that guys. It got interwined with preds. Can we start a fresh bug, copy over stuff from this one?
