### ISSUE TITLE
Support outputting TextMate files 

### ISSUE THREAD

**Issue by burdoto** [antlr/antlr4#3607]
Hi, I'm working on a fun little language, and I'm switching over to Antlr just recently because it is a genius invention.
Now I'm running into a small problem;
Trying to make a VSCode extension expects me to not have ANTLR files, but TypeMate files (.tmLanguage) and I was turned down to realize that I'll be required to write my grammar specification again in TypeMate, if I want that to work well.
Except - I was hoping that it might be possible to have ANTLR generate all required files from me, as it does when generating the Parser and Lexer source code.

**Comment by kaby76** [comment]
Antlr is a parser generator, not a converter from one grammar syntax to another. Instead of converting to TM, I recommend that you write a server that implements the Language Server Protocol using an Antlr-generated parser for your language. See [this implementation](https://github.com/kaby76/uni-vscode). (I have an task on my "to do" list to write a converter from Antlr to TM some day. A grammar itself does not specify classes of symbols in a language.)

**Comment by kaby76** [comment]
By the way, it's "TextMate", not "TypeMate". The [.tmlanguage files are TextMate files](https://stackoverflow.com/questions/31197184/what-is-tmlanguage).

**Comment by burdoto** [comment]
Yes you're right, that's my bad.
Also your suggestion using a language server seems to be by far my best option here.
Thanks!

**Comment by dxfoso** [comment]
> 

my solution was not to use TextMate files in vscode but instead using  the Semantic highlighting in vscode and turn off the TextMate 
you can read here about it 
https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide

**Comment by burdoto** [comment]
Thanks for the idea! Although I believe that making a Language Server is most feasible, as that can be used with IntelliJ platforms as well.

**Comment by dxfoso** [comment]
you are correct , but for Syntax Highlight there is delay in order for the server to respond , that is why i used directly in VSCode without Language Server

**Comment by svallory** [comment]
I've been thinking about writing a TextMate grammar generator (from anything, honestly, because I hate writing in tmlanguage) if anyone wants to join efforts, let me know!

**Comment by burdoto** [comment]
hello @svallory, i'm very interested in joining that! i've already started some attempts doing that but i never got really far. please contact me via my profile email address
