### ISSUE TITLE
dev version: getting assertion failures in getPredicatePredictions() after recent changes

### ISSUE THREAD

**Issue by hzeller** [antlr/antlr4#3641]
With recent dev versions, I get assertion failures:
```
runtime/Cpp/runtime/src/atn/ParserATNSimulator.cpp:714: std::vector<antlr4::dfa::DFAState::PredPrediction> antlr4::atn::ParserATNSimulator::getPredicatePredictions(const antlrcpp::BitSet&, const std::vector<std::shared_ptr<const antlr4::atn::SemanticContext> >&): Assertion `pred != nullptr' failed.
```
(using in my processing files in [Surelog](https://github.com/chipsalliance/Surelog))

git bisecting showed that this started in 0037a11b248278e38a19fd7be42a5b0fcde236e1

CC @jcking

**Comment by jcking** [comment]
I don't think that commit is the root cause. Looking at Java, the logic is similar. The `getPredsForAmbigAlts` is supposed to ensure no SemanticContext is nullptr. But it only looks a nalts where as the array is `nalts` + 1. Very odd.

**Comment by jcking** [comment]
@parrt FYI

**Comment by parrt** [comment]
Trying to go out the door this afternoon with 4.10...  should I hit the emergency stop button?  :)

**Comment by hzeller** [comment]
I just verified that if I revert that commit locally, I do _not_ get the assertion failure. This does not say that the commit is the cause of the trouble, just that with it, the assert-failure is exposed.

**Comment by parrt** [comment]
Cool. That is an excellent clue. Thanks!

**Comment by hzeller** [comment]
but also, without that patch, the runtime is significantly longer.
So ideally we'll find the culprit before release.
