### ISSUE TITLE
[Python3 Runtime] Release 4.10 breaks support for Python 3.5

### ISSUE THREAD

**Issue by amykyta3** [antlr/antlr4#3650]
The latest 4.10 runtime release breaks support for Python 3.5.
It looks like the codebase introduces the use of f-strings, which are only available in Python 3.6 and newer. Not sure if use of f-strings is limited to the setup.py, or whether they are also widely used in the runtime.

I strongly recommend you yank the release from PyPi and re-release with a proper version constraint in your `runtime/Python3/setup.py`:

```python
setup(
    ...
    python_requires='>=3.6.0',
)
```

Currently, any users still using Python 3.5 will have pip blindly fetch the v4.10 runtime despite it not being compatible.

pip install fails with the following:
```
$ python3.5 -m pip install antlr4-python3-runtime
Collecting antlr4-python3-runtime
  Using cached antlr4-python3-runtime-4.10.tar.gz (116 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.5 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4ktmdclk/antlr4-python3-runtime_a1ff11eada524b8993affbd53054989d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4ktmdclk/antlr4-python3-runtime_a1ff11eada524b8993affbd53054989d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vs2ia4lj
         cwd: /tmp/pip-install-4ktmdclk/antlr4-python3-runtime_a1ff11eada524b8993affbd53054989d/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4ktmdclk/antlr4-python3-runtime_a1ff11eada524b8993affbd53054989d/setup.py", line 18
        description=f'ANTLR {v} runtime for Python 2.7.12'
                                                         ^
    SyntaxError: invalid syntax
    ----------------------------------------
```

**Comment by dizys** [comment]
Even I'm using Python 3.8, it still breaks my code.
https://github.com/dizys/nyu-ai-lab-2
Cost me 10 points out of 100 for my course lab. 😰

**Comment by amykyta3** [comment]
@dizys - that appears to be unrelated. I think it is because your project generated the parser/lexer in Antlr 4.9. (https://github.com/dizys/nyu-ai-lab-2/blob/main/solving/bnf_parser/BNFParser.py#L1)
If you look at the release notes, Antlr 4.10 refactors many things in a way that requires parsers/lexers to be re-generated otherwise they are incompatible with the latest 4.10 runtime.
Recommend adding a version constraint here that also requires the runtime to be less than v4.10, as that would have protected you from this: https://github.com/dizys/nyu-ai-lab-2/blob/main/requirements.txt#L1.
Seems unfair for your prof to deduct points for something beyond your control :/

**Comment by SpinalRoster** [comment]
Same issue in antlr4-python2-runtime/setup.py

**Comment by amykyta3** [comment]
@dizys - that appears to be unrelated. I think it is because your project
generated the parser/lexer in Antlr 4.9. (
https://github.com/dizys/nyu-ai-lab-2/blob/main/solving/bnf_parser/BNFParser.py#L1
)
If you look at the release notes, Antlr 4.10 refactors many things in a way
that requires parsers/lexers to be re-generated otherwise they are
incompatible with the latest 4.10 runtime.
Recommend adding a version constraint here that also requires the runtime
to be less than v4.10, as that would have protected you from this:
https://github.com/dizys/nyu-ai-lab-2/blob/main/requirements.txt#L1.
Seems unfair for your prof to deduct points for something beyond your
control :/
