### ISSUE TITLE
Serious bug in generated Antlr code [reduced non-terminals missed]

### ISSUE THREAD

**Issue by crmandal** [antlr/antlr4#3661]
be returns [cktBox cB] // Boolean expression
:  lit AND be { // Boolean expression with AND connective
 $cB = new cktBox();
 $cB.cB1 = $lit.cB;
 $cB.cB2 = $be.cB;
 $cB.tag = 3;
 $cB.rCnt = $lit.cB.rCnt + $be.cB.rCnt;
 System.out.println("rCntAND: "+$lit.cB.rCnt+"+"+$be.cB.rCnt+"="+$cB.rCnt);
}
-------------------------------------------------------------
...
setState(62); ((BeContext)_localctx).lit = lit();
				setState(63); match(AND);
				setState(64); ((BeContext)_localctx).be = be();
				 // Boolean expression with AND connective
				 ((BeContext)_localctx).cB =  new cktBox();
				 _localctx.cB.cB1 = ((BeContext)_localctx).lit.cB;
				 _localctx.cB.cB2 = _localctx.cB; // BUG: should have been _localctx.be.cB;
				 _localctx.cB.tag = 3;
				 _localctx.cB.rCnt = ((BeContext)_localctx).lit.cB.rCnt + _localctx.cB.rCnt; // BUG
				 System.out.println("rCntAND: "+((BeContext)_localctx).lit.cB.rCnt+"+"+_localctx.cB.rCnt+"="+_localctx.cB.rCnt); // BUG
...

**Comment by crmandal** [comment]
[buggyG4.txt](https://github.com/antlr/antlr4/files/8499199/buggyG4.txt)

This is the full file

**Comment by crmandal** [comment]
ASSIGN ( ( ( ( ~S01ALR * ~S01E_S11OV1LR * ~S01E_S11OV2LR ) * ( ( ( 1/2XTTPR * 4XTTPR * 201bXTTPR ) * ( ( ~S01TSR * ~S01EUUYR * S01UYR ) + ( S01EUUYR * S01JSLR * ( ( S01JR ) + ( S01ATR ) ) ) + SYSINT ) ) + ( S01ESUYR * S01JR * ~EMKEY_INR ) ) ) + S01ASR ) * ( ~S01HR * ~S01HECR * ~S01UCR ) * ( ( ( ~S01E_S11OV1UHR * ~S01E_S11OV2UHR ) ) ) * ( ~S01DR * ~S01DECR * ~S01UECR ) ) TO S01ASR;

Sample input

**Comment by KvanTTT** [comment]
Could you please add a minimal sample of grammar, expected and actual outputs.

**Comment by crmandal** [comment]
I have given a sample input. It's parsing fine, but semantic actions are buggy. The g4 file is given as buggyG4.txt (as files with g4 extension cannot be attached), pl rename to DiagGen.g4

The bug is explained for the production: be --> lit AND be

**Comment by crmandal** [comment]
I think I've found the problem. All grammar symbols should be distinct in a production to avoid ambiguity in resolution of the names.
