### ISSUE TITLE
Unable to generate parser for cpp antlr4 grammar. NullPointerException in main of org.antlr.v4.Tool

### ISSUE THREAD

**Issue by prakharmishra** [antlr/antlr4#367]
I am unable to generate a parser from my grammar. Its not giving any error messages, but the NullPointerException while running org.antlr.v4.Tool on the grammar. I also tried to open this grammar file in ANTLRWorks 2.1, but navigator is showing a single message "Please wait...".

You can view the details here:-

http://stackoverflow.com/questions/20439255/antlr4-cpp-grammar-unable-to-generate-parser-nullpointereexception

Please resolve it ASAP, because I am stuck without it.

**Comment by KvanTTT** [comment]
Already not actual. @ericvergnaud please close
