### ISSUE TITLE
why PlsqlParser is so slow?

### ISSUE THREAD

**Issue by nIxedoahz** [antlr/antlr4#3670]
cpp
aarch64-linux-gnu-g++
PlsqlParser psr(&token) 
It takes more than a second to parse an SQL on average (one sql)

**Comment by nIxedoahz** [comment]
plsql

**Comment by kaby76** [comment]
This should issue should closed. I opened an issue [in grammars-v4](https://github.com/antlr/grammars-v4/issues/2589), and have started with an analysis.

**Comment by KvanTTT** [comment]
@parrt please close.
