### ISSUE TITLE
JavaScript： large number lose their precision

### ISSUE THREAD

**Issue by LeoJiang1997** [antlr/antlr4#3680]
Now i come across this problem: when i entered a large number to antlr4, digits between 18 and 21,the output number will lose their precison,like this:
123456789123456789 will become to 123456789123456780
![image](https://user-images.githubusercontent.com/54826369/165450402-adb161e0-b5b2-47e3-ae5c-f5fb4e5492f9.png)

can you help me to solve this problem or find a reason?thanks!!!

**Comment by ericvergnaud** [comment]
How does this relate to antlr ?
