### ISSUE TITLE
[JavaScript runtime] Bad field name, bad comments

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#3710]
In this [SO question](https://stackoverflow.com/questions/72244762/antlr-4-10-1-for-javascript-doesnt-seem-to-have-a-buildparsetrees-property), I took a look at the JavaScript runtime to see if `buildParseTrees` is defined for a parser. Indeed [it is](https://github.com/antlr/antlr4/blob/f25a4f6275ed259c6a155eafcd0cb1a5252dde13/runtime/JavaScript/src/antlr4/Parser.js#L40), but I noticed there is one applied occurrence of the field erroneously spelled [_buildParseTrees](https://github.com/antlr/antlr4/blob/f25a4f6275ed259c6a155eafcd0cb1a5252dde13/runtime/JavaScript/src/antlr4/Parser.js#L137). Of course, in the warped world of JS, this is not caught either by compiler or runtime.

Also, there is no "getBuildParseTree()" noted [here](https://github.com/antlr/antlr4/blob/f25a4f6275ed259c6a155eafcd0cb1a5252dde13/runtime/JavaScript/src/antlr4/Parser.js#L85) and [here](https://github.com/antlr/antlr4/blob/f25a4f6275ed259c6a155eafcd0cb1a5252dde13/runtime/JavaScript/src/antlr4/Parser.js#L120).

I realize "code reviews" are old school, but relying on a terrible programming language like Javascript to find errors is not going to work.

**Comment by matthew-dean** [comment]
Ideally the runtime would / should be written in TypeScript (or at least type-checked JavaScript annotated with JSDoc types), which would catch these immediately at build time. JavaScript is only a "terrible programming language" if the tools one is using for it are terrible.

**Comment by KvanTTT** [comment]
Maybe discussion about TypeScript target would be interesting for you: https://github.com/antlr/antlr4/discussions/3867
