### ISSUE TITLE
Enable sponsorship on the ANTLR organization

### ISSUE THREAD

**Issue by marcospassos** [antlr/antlr4#3716]
ANTLR is the result of 20+ years of hard work. Although it's a non-profit project, we'd like to make our (modest) contribution :)

**Comment by marcospassos** [comment]
@parrt

**Comment by parrt** [comment]
hi @marcospassos !!! I've thought about this before but wouldn't it be hard to decide how to assign value to each person's contribution?  (I recently turned off the PayPal donate button on the website itself.  It only brought in about $50 a year haha.)

**Comment by marcospassos** [comment]
You can configure GitHub Sponsors to allow custom values and even set predefined tiers:

![image](https://user-images.githubusercontent.com/943036/168661100-afbfb631-e8e7-41bb-8a8e-f8ad9a2e55b7.png)

**Comment by KvanTTT** [comment]
I raised a similar issue some time ago. But I don't think PayPal is suitable option, I suggest using https://opencollective.com/ It's open and it tracks expenses and transactions, a lot of opensource projects use, see Avalonia as an example: https://opencollective.com/Avalonia It looks like GitHub Sponsors is also suitable option.

**Comment by marcospassos** [comment]
GitHub is a much better option for us as it allows including the contribution as part of the monthly dispenses.

**Comment by parrt** [comment]
Does everyone over last 12 yrs that gave a PR get a fraction?  I just don't know how to be fair here.

**Comment by KvanTTT** [comment]
For instance, the money can be spent on paid services (CI).

**Comment by parrt** [comment]
Now that is a good idea... I just spent I think $90 last month on circleCI before I cut it off... Seems like it was always hitting my credit card for $15. haha. I'm also thinking about renting a Linux server to run an antlr "service" and some other things.

**Comment by marcospassos** [comment]
@parrt, I think this money can be used to cover maintenance expenses (CI/CD, hosting, etc.). Several companies depend on ANTLR somehow. We can get some sponsors with public announcements (ANTLR's Twitter, Linkedin, etc.).

**Comment by marcospassos** [comment]
JetBrains is such a good example, right @KvanTTT? 😜

**Comment by marcospassos** [comment]
(most big tech companies have sponsorship budget for OSS nowadays)

**Comment by KvanTTT** [comment]
> JetBrains is such a good example, right @KvanTTT? 😜

I don't know how much JetBrains use ANTLR but it definitely sponsors some open-source projects. For instance, last year JetBrains contributed $100K to PHP foundation: https://opencollective.com/jetbrains Also, JetBrains allows employees spending 20% of working time on opensource projects. Now I'm spending it on ANTLR 😄

**Comment by marcospassos** [comment]
Yeah, that's why every dev loves JetBrain ❤️ 

Anyway, it'd be really nice to see JetBrains backing ANTLR 😄

**Comment by yososs** [comment]
It would be nice to have an explanation of how to donate in the release notes.

**Comment by marcospassos** [comment]
If you don't think this can help, let's leave it as is ;)

**Comment by parrt** [comment]
:)  Let's revisit when bills start piling up haha
