### ISSUE TITLE
Drop old version of Visual Studio C++ (2013, 2015, 2017)

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#3723]
Currently we have the following .vsxproj files:

* antlr4cpp-vs2013.vcxproj
* antlr4cpp-vs2015.vcxproj
* antlr4cpp-vs2017.vcxproj
* antlr4cpp-vs2019.vcxproj

I suggest removing the first three and adding `antlr4cpp-vs2022.vcxproj`:

* antlr4cpp-vs2019.vcxproj
* antlr4cpp-vs2022.vcxproj

@mike-lischke what do you think?

Also, these projects can't be built because they weren't updated after some files removing (for instance, ATNSerializer.cpp).

**Comment by mike-lischke** [comment]
Makes sense, yes. Actually, I expect that PRs which change the file structure also update all project files (cmake, xcode, vcxproj), but I have to admit, I didn't check that in all PRs I approved. Unfortunately, those people who know cmake are usually not familiar with IDE project files and vice versa.
