### ISSUE TITLE
antlr lexer breaks entire program and gives bizarre error messages

### ISSUE THREAD

**Issue by kamkow1** [antlr/antlr4#3738]
All ANTLR contributors provide implementation, maintenance and support for free.
We therefore kindly ask that before submitting any issue to ANTLR, you please check off these boxes:

- [+] I have reproduced my issue using the latest version of ANTLR
- [-] I have asked at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [+] Responses from the above seem to indicate that my issue could be an ANTLR bug
- [+] I have done a search of the existing issues to make sure I'm not sending in a duplicate

Hello,
I use antlr target for c# and i've encountered some issues...

```
lexer grammar myGrammarFile;

options {
    language = CSharp;
}

FUNC                : 'func';
END                 : 'end';
LOOP                : 'loop';
RETURN              : 'ret';

STRING_VALUE        : '"' (~[\\"\r\n])* '"';
INTEGER_VALUE       : '-'? '0'..'9'+;
FLOAT_VALUE         : '-'? ('0'..'9')+ '.' ('0'..'9')*;
BOOL_VALUE          : ('True' | 'False');

ASSIGN              : '=';

PLUS                : '+';
MINUS               : '-';
STAR                : '*';
SLASH               : '/';
CIRCUMFLEX          : '^';

TERMINATOR          : ';';
COMMA               : ',';
LPAREN              : '(';
RPAREN              : ')';
LBRACE              : '{';
RBRACE              : '}';
COLON               : ':';
DOT                 : '.';
AMP                 : '&';
HASH                : '#';

IDENTIFIER          : ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A' .. 'Z' | '0'..'9' | '_')*;
WHITESPACE          : [ \r\n\t]+    -> skip;
COMMENT             : '#*' .*? '*#' -> channel(HIDDEN);
LINE_COMMENT        : '#' ~[\r\n]*  -> channel(HIDDEN);
```

 - description of the expected behavior and actual behavior
 
my problem is that my grammar file breaks the entire program after adding one more rule.
The provided snippet actually doesn't work unless you remove the "loop" rule. this behaviour is weird, because the IDENTIFIER rule if after the LOOP rule.

(i'm unsure if that's relevant) i am generating the lexer using a bash script that goes:
eval "java -jar /usr/local/bin/antlr-4.10.1-complete.jar ./myGrammarFile.g4 -Dlanguage=CSharp -o ./Interpreter/Lexer/"

also i end up getting strange error messages, for example:
line 5:23 mismatched input ';' expecting ';'

how is antlr not seeing a semicolon that is put in the right place?

also let me know if you need the parser antlr file

thanks!

**Comment by kaby76** [comment]
Could you please edit your comment above and place three [backquotes](https://www.fileformat.info/info/unicode/char/0060/index.htm) on a single line before your grammar and another single line after your grammar. Or, indent each line in the grammar with four spaces. It's impossible to understand the grammar when it is being interpreted as Markdown. See the `WHITESPACE` and `COMMENT` rules: they are being formatted in italics. I can go over the several problems that I immediately see afterward. Thanks.

**Comment by kamkow1** [comment]
> Could you please edit your comment with the grammar and place three [backquotes](https://www.fileformat.info/info/unicode/char/0060/index.htm) on a single line before your grammar and another single line with three more backquotes after your grammar. Or, indent each line in the grammar with four spaces. It's impossible to understand the grammar when it is being interpreted as Markdown. See the `WHITESPACE` and `COMMENT` rules: they are being formatted in italics. I can go over the several problems that I immediately see afterward. Thanks.

**Comment by kamkow1** [comment]
fixed my issue, it was a problem with the input code,

thanks for taking your time to reach out though ;)
