### ISSUE TITLE
antlr4-python3-runtime 4.10 not working in Python 3

### ISSUE THREAD

**Issue by angstr0m** [antlr/antlr4#3753]
The latest Python 3 Antlr package (Version 4.10 https://pypi.org/project/antlr4-python3-runtime/) does not work in Python 3.

I get the following error message:
"Exception: Could not deserialize ATN with version  (expected 4)."
in
File "/usr/local/lib/python3.8/site-packages/antlr4/atn/ATNDeserializer.py", line 50, in checkVersion

The description of the package reads "ANTLR 4.10 runtime for Python 2.7.12". Was an incorrect package submitted to Pip?

The package version 4.9.3 works well.

**Comment by KvanTTT** [comment]
Please regenerate lexer/parser using the new ANTLR 4.10.1

**Comment by mohamedmaged96** [comment]
I have the same issue, version 4.10.1 and python version 3.10.0. Regenerating lexer/parser didn't help.

**Comment by angstr0m** [comment]
Thanks for the assistance! Looks like that did the trick.

**Comment by mohdgazyanii235** [comment]
> Please regenerate lexer/parser using the new ANTLR 4.10.1

How do you do this?
