### ISSUE TITLE
Invalid Python3 Syntax in (CPP14) Parser.py

### ISSUE THREAD

**Issue by jofatmofn** [antlr/antlr4#3759]
Antlr Version: 4.10.1
Target: Python3
Grammar: https://github.com/antlr/grammars-v4/blob/master/cpp/CPP14Parser.g4 (and corresponding CPP14Lexer.g4)

Issue: While running my parser code (just printing the parse tree), am getting the following error:
```
Traceback (most recent call last):
  File "{myfolder}\main.py", line 4, in <module>
    from CPP14Parser import CPP14Parser
  File "{myfolder}\CPP14Parser.py", line 13242
    if((None if localctx.val is None else localctx.val.text).compareTo("0")!=0) throw new InputMismatchException(this);
                                                                                ^^^^^
SyntaxError: invalid syntax
```
I temporarily modified CPP14Parser.py, replacing the above code to
```
            if((None if localctx.val is None else localctx.val.text) != "0"):
                raise ValueError('InputMismatchException');
```

**Comment by ericvergnaud** [comment]
The issue comes from the grammar which is not target agnostic.
See pureSpecifier

**Comment by jofatmofn** [comment]
Feeling bad for not looking into the grammar :(. Sorry & Thanks.
