### ISSUE TITLE
python target, JavaScript lexer

### ISSUE THREAD

**Issue by Gerodote** [antlr/antlr4#3774]
in JavaScriptLexer.py, that I've got after using Java 18 and antlr4.10,1 lib and javascript.g4 which I've got here: https://github.com/antlr/grammars-v4/tree/master/javascript/javascript and then transformed using transformGrammar.py from https://github.com/antlr/grammars-v4/tree/master/javascript/javascript/Python3 :
there were this.IsStrictMode()
instead of self.IsStrictMode()

this issue was in 12 functions.

**Comment by ericvergnaud** [comment]
and close this one ?

**Comment by kaby76** [comment]
Thanks. I'll fix this in grammars-g4.
