### ISSUE TITLE
@types/antlr4 out of date

### ISSUE THREAD

**Issue by david-wb** [antlr/antlr4#3786]
I'm trying to use the antlr4-10.1 JavaScript runtime in a TypeScript project. Unfortunately, it looks like the type declaration package `@types/antlr4` is stuck at version 4.7.2. Why is that? Is there any other way to get accurate typings for the 10.1 JS runtime?

**Comment by ericvergnaud** [comment]
That package is not an official package from this org.
Please reach out to them and close.

**Comment by ericvergnaud** [comment]
Please check 4.12.0-beta.1 on npm which comes with supported typescript types. This is just the runtime, next antlr release will provide typescript as a target language.
