### ISSUE TITLE
Create accessor for Go-based IntervalSet.intervals

### ISSUE THREAD

**Issue by JamesRTaylor** [antlr/antlr4#3801]
Target: Go

Unlike the Java version, in the Go-based version of interval_sets, there's no way to access the IntervalSets.intervals field. This field is useful when using Parser.getExpectedTokens(). The alternative is to use IntervalSets#StringVerbose and parse the string returned (which is much more expensive).

**Comment by JamesRTaylor** [comment]
PR is here: https://github.com/antlr/antlr4/pull/3800

**Comment by jimidle** [comment]
@parrt Can close this - PR is merged.
