### ISSUE TITLE
'native' import statements in @parser:header are dropped 

### ISSUE THREAD

**Issue by ericvergnaud** [antlr/antlr4#3868]
Consider the following grammar:

grammar G;

@parser:header {
// import X from './X';
import X from './X';
class Y extends X {}
}

a: 'a' EOF;

The generated code will look as follows:

.../...
// import X from './X';
class Y extends X {}
class GParser extends Parser { .../... }

notice that the native statement "import X from './X';" has been dropped.
it doesn't happen with preceding comment or the succeeding declaration.
I suspect it is because the tool sees the 'import...' line as an antlr import statement...

**Comment by ericvergnaud** [comment]
mmm... this only happens during testing, so should be able to fix it without side effects

**Comment by KvanTTT** [comment]
I'm afraid I can't bless such a fix. It's unclear why `CodeGenPipilne` removes name action and method `removeParserHeader` in `Grammar` looks irrelevant. Is it possible just not to add `header` named action?

**Comment by ericvergnaud** [comment]
@KVanTT, thanks for your comments, some of them are useful, but at mentioned originally, this is not a time for review yet.

**Comment by ericvergnaud** [comment]
Closed in favor of #3877
