### ISSUE TITLE
Parser header is incorrectly inserted in Listener and Visitor files

### ISSUE THREAD

**Issue by ericvergnaud** [antlr/antlr4#3877]
When adding a `@header` or `@parser::header` to a grammar, the enclosed text block is inserted not only in the generated parser code, but also in the generated listener and visitor code.
This is incorrect because listener and visitor do not contain any production code and as such would never have a need for additional code that is never invoked.

**Comment by parrt** [comment]
We should do a quick analysis to see which targets do what; and to do a backward compatibility check. I will try to do this tomorrow if you've not looked yet.

**Comment by ericvergnaud** [comment]
Not sure this is target related, because the header scope is dropped by the tool, so targets can only insert <header>, not parser::header or lexer::header. 
My proposed PR #3878 caters for that by adding the scope to ActionAST, and all tests pass on all targets (is that the compatibility check you had in mind?) so my confidence that this fix is correct is actually quite high.
If you have another analysis in mind let me know and I'll have a look.

**Comment by parrt** [comment]
Hmm...makes me nervous about backward compat even if this looks correct. I gotta do some other work today but I'll check it out maybe tomorrow.

**Comment by parrt** [comment]
> This is incorrect because listener and visitor do not contain any production code and as such would never have a need for additional code that is never invoked.

I'm not sure about this. What about package specifications? If I want to put my generated listener or visitor in a package, what do I do?

**Comment by ericvergnaud** [comment]
You put that in the header directive, not the parser::header one

Envoyé de mon iPhone

**Comment by ericvergnaud** [comment]
One needs the ability to insert code in the parser only, which I believe is the original intent of parser::header

Envoyé de mon iPhone

**Comment by ericvergnaud** [comment]
Also the ‘package’ option is more appropriate since the package statement needs to come first in Java and is used for namespaces in other targets

Envoyé de mon iPhone

**Comment by ericvergnaud** [comment]
See package option in  https://github.com/antlr/antlr4/blob/master/doc/tool-options.md

Envoyé de mon iPhone

**Comment by parrt** [comment]
> You put that in the header directive, not the parser::header one

Yeah. hmm...  Seems like @parser::header cannot be used together with @header.  i get an error which I think makes sense.

> Also the ‘package’ option is more appropriate since the package statement needs to come first in Java and is used for namespaces in other targets

Ok, yes this is now sounding more familiar ha ha.

```
$ antlr4 -visitor -package PPP T.g4
$ grep package *.java
TBaseListener.java:package PPP;
TBaseVisitor.java:package PPP;
TLexer.java:package PPP;
TListener.java:package PPP;
TParser.java:package PPP;
TVisitor.java:package PPP;
```

**Comment by parrt** [comment]
So it looks like we should simply not generate any header stuff into listener / visitor files, right? Let me look at your code again here but it looks like you're doing more so I will investigate.

This definitely injects the import statement into the listener and visitor as well as the parser:

```
grammar T;

@parser::header { import Junk.YYY; }

a[YYY y] : A ;

A : 'abc' ;
```

**Comment by ericvergnaud** [comment]
What I’m doing is simply filtering out parser::header for listener and visitor

Envoyé de mon iPhone
