### ISSUE TITLE
Implement parse tree pretty-printing a la Cpp runtime in other runtimes

### ISSUE THREAD

**Issue by RossPatterson** [antlr/antlr4#3899]
The C++ runtime supports generating string representations of the parse tree in two forms:  the standard all-in-one-line Lisp-ish expression, and a [pretty-printed version](https://github.com/antlr/antlr4/blob/master/runtime/Cpp/runtime/src/tree/Trees.cpp#L38), which splits the Lisp expression into multiple lines and indents subexpressions.  None of the other runtime targets have the pretty-printing capability.  It would be quite handy for human-focused results, including the unit test systems of the `grammars-v4` collection.

I suggest we implement the C++ runtime behavior in all the other runtimes.

**Comment by RossPatterson** [comment]
@parrt I would be willing to work on this, if it's an interesting function to you.  If it is implemented, I would update the CI tests to use it.

**Comment by parrt** [comment]
That's a lot of work for all of the different targets ;) 

I also have a JSON generator but only for Java. :(

**Comment by RossPatterson** [comment]
I'll take a stab at pretty-printing the tree in all targets.  It's an effort, but I don't think it's a large one, and I expect it to be very isolated from the hard parts of ANTLR.

I'll think about JSON if I get this working :-)

**Comment by parrt** [comment]
Before we commit to all of this work, can you show me some sample output? Thanks

**Comment by RossPatterson** [comment]
Sure.  Given this input string:

```rexx
address COMMAND 'DESBUF' with error stem err_var_stem.
```

and the `grammars-v4/rexx` grammar, `grun` produces this tree:
```lisp
(file_ (program_ (instruction_list (instruction (single_instruction (keyword_instruction (address_ address (taken_constant (symbol (var_symbol COMMAND))) (expression (and_expression (comparison (concatenation (addition (multiplication (power_expression (prefix_expression (term (string 'DESBUF')))))))))) with (connection (error error (resourceo (resources stem (var_symbol err_var_stem.)))))))) (ncl (null_clause (delim \n)))))) <EOF>)
```

The same input and grammar, pretty-printed in the style of the Cpp runtime, looks like this:
```lisp
(file_ 
    (program_ 
        (instruction_list 
            (instruction 
                (single_instruction 
                    (keyword_instruction 
                        (address_ address 
                            (taken_constant 
                                (symbol 
                                    (var_symbol COMMAND))) 
                            (expression 
                                (and_expression 
                                    (comparison 
                                        (concatenation 
                                            (addition 
                                                (multiplication 
                                                    (power_expression 
                                                        (prefix_expression 
                                                            (term 
                                                                (string 'DESBUF')))))))))) with 
                            (connection 
                                (error error 
                                    (resourceo 
                                        (resources stem 
                                            (var_symbol err_var_stem.)))))))) 
                (ncl 
                    (null_clause 
                        (delim \n)))))) <EOF>)
```

**Comment by parrt** [comment]
@ericvergnaud @KvanTTT @mike-lischke what do you guys think about such a pretty printer across targets. I don't know how much called there's been for its and it would be something that we don't have to maintain forever. I mostly prefer the graphical version.

**Comment by ericvergnaud** [comment]
Tbh I’m not sure there’s any use, but if there isn’t then there’s no harm, provided the proper cross target testing is in place Envoyé de mon iPhoneLe 13 oct. 2022 à 19:17, Terence Parr ***@***.***> a écrit :﻿
@ericvergnaud @KvanTTT @mike-lischke what do you guys think about such a pretty printer across targets. I don't know how much called there's been for its and it would be something that we don't have to maintain forever. I mostly prefer the graphical version.

**Comment by parrt** [comment]
Yes I guess it seems like there's really no reason to add code that I will have to support for the next decade or so, when there's no strong need. A stronger need would be a JSON generator right? I have the version for Java but I don't have time to Inc. across target so people suggested we wait until other implementations are offered.

**Comment by ericvergnaud** [comment]
I’d suggest having different policies for the runtime core and the runtime tools.
I think we all agree that all runtimes should behave exactly the same.
But when it comes to tools, a number of runtimes have been out there with only a subset of tools without anyone complaining about it…
So not sure there is any value in wanting every target to implement a JSON generator before releasing the java one ?

**Comment by parrt** [comment]
An excellent point.  Ok, so I'm going to close this; I just don't want to add code to maintain when no one has bugged me about pretty printing for other targets. thanks gang.

**Comment by mike-lischke** [comment]
What's a JSON generator actually? I have to admit I haven't heard about that before.

**Comment by parrt** [comment]
I have to generate json from parse trees to serialize across socket from server to client for antlr lab.

**Comment by KvanTTT** [comment]
We've encoutered the similar issue several times:

* https://github.com/antlr/antlr4/issues/1502
* https://github.com/antlr/antlr4/pull/2340
* https://github.com/antlr/antlr4/pull/3229

> Yes I guess it seems like there's really no reason to add code that I will have to support for the next decade or so, when there's no strong need.

It's useful feature, but I consider the suggested format with a lot of confusing parentheses is confusing. I suggest using tree with indents:

```
parse 
 sql_stmt_list 
  sql_stmt 
   select_stmt 
    select_core 
     select    
     result_column 
      expr 
       column_name 
        any_name 
         id
     ,    
     result_column 
      expr 
       column_name 
        any_name 
         first_name
     from    
     table_or_subquery 
      table_name 
       any_name 
        users
  ;
 <EOF>
```

> What's a JSON generator actually? I have to admit I haven't heard about that before.

It's useful feature especially for client-server scenarious and other scenarios where serilization is required. Also, it's useful for tree comparison in tests.
