### ISSUE TITLE
JavaScript: Named exports

### ISSUE THREAD

**Issue by Codex-** [antlr/antlr4#3912]
Currently the JavaScript runtime for Antlr4 only provides a default export:
```js
const antlr4 = {
    atn, dfa, tree, error, Token, CommonToken, CharStreams, InputStream, FileStream, CommonTokenStream, Lexer, Parser,
    PredictionContextCache, ParserRuleContext, Interval, IntervalSet, LL1Analyzer, Utils
};

export default antlr4;
```

This can be problematic as a consumer as outlined nicely by the esbuild documentation: 
https://esbuild.github.io/content-types/#default-interop
```
If you are a library author: When writing new code, you should strongly consider avoiding the default export entirely. It has unfortunately been tainted with compatibility problems and using it will likely cause problems for your users at some point.
```

This is indeed the case for us currently with trying to test against our usage of antlr and how babel is handling the default export versus the imports etc.

The simplest solution would be to add named exports (without removing the default, so a non-breaking change for consumers):
```js
const antlr4 = {
    atn, dfa, tree, error, Token, CommonToken, CharStreams, InputStream, FileStream, CommonTokenStream, Lexer, Parser,
    PredictionContextCache, ParserRuleContext, Interval, IntervalSet, LL1Analyzer, Utils
};

export default antlr4;

export {
    atn, dfa, tree, error, Token, CommonToken, CharStreams, InputStream, FileStream, CommonTokenStream, Lexer, Parser,
    PredictionContextCache, ParserRuleContext, Interval, IntervalSet, LL1Analyzer, Utils
};
```

This would:
- Allow consumers successfully using the default import to continue with no change.
- Allow named imports to be handled more easily.
- Should also help with dead code elimination / tree-shaking

**Comment by ericvergnaud** [comment]
Can you be more specific about the problems you encounter ?
I agree that a full export is problematic when publishing a components library.
But I don’t see any use case where one would need only a portion of the antlr runtime...

**Comment by Codex-** [comment]
> Can you be more specific about the problems you encounter ? I agree that a full export is problematic when publishing a components library. But I don’t see any use case where one would need only a portion of the antlr runtime...

Sure thing:
```ts
import {
  GeneratedSyntaxLexer,
  GeneratedSyntaxParser,
} from "@namespace/package";
import antlr from "antlr4";

export function parse(text: string) {
  const inputStream = new antlr.InputStream(text);
  const lexer = new GeneratedSyntaxLexer(inputStream);
  const tokenStream = new antlr.CommonTokenStream(lexer);
  const parser = new GeneratedSyntaxParser(tokenStream);
  return parser.something();
}

vs;

import {
  GeneratedSyntaxLexer,
  GeneratedSyntaxParser,
} from "@namespace/package";
// This does not work currently
import { CommonTokenStream, InputStream } from "antlr4";

export function parse(text: string) {
  const inputStream = new InputStream(text);
  const lexer = new GeneratedSyntaxLexer(inputStream);
  const tokenStream = new CommonTokenStream(lexer);
  const parser = new GeneratedSyntaxParser(tokenStream);
  return parser.something();
}
```

The default export `antlr` causes big headaches when trying to bundle, such as babel ending up with `antlr.default.default` in some scenarios (not immediately obvious).

If we allow this change through then consumers can choose to use the default export, choose a named export, or also succeed with `import * as antlr from 'antlr'`

**Comment by ericvergnaud** [comment]
please check 4.12.0-beta.1 in npm, it comes with Typescript support, and I suspect it also addresses your concern

**Comment by Codex-** [comment]
Kind of, the new export is there but the typings do not represent the exports correctly, i.e. `atn` is not defined in the typings.

This causes issues when trying to generate inferred typings from the antlr generated javascript for a grammar, for example when generating types for a parser with typescript:
Using @types:
```ts
declare class SomeGrammarParser extends antlr4.Parser {
    ...
    _interp: antlr4.atn.ParserATNSimulator;
    ...
    get atn(): antlr4.atn.ATN;
    ...
}
```

Using antlr4 beta:
```ts
declare class SomeGrammarParser extends antlr4.Parser {
    ...
    _interp: any;
    ...
    get atn(): any;
    ...
}
```

`index.d.ts` should ideally be updated to reflect the exports of `index.js`:
```ts
import { default as atn } from "./atn";
import { default as dfa } from "./dfa";
import { default as context } from "./context";
import { default as misc } from "./misc";
import { default as tree } from "./tree";
import { default as error } from "./error";
import { default as CharStreams } from "./CharStreams";
import { default as Utils } from "./utils";

import Token from "./Token";
import CommonToken from "./CommonToken";
import InputStream from "./InputStream";
import CharStream from "./InputStream";
import FileStream from "./FileStream";
import CommonTokenStream from "./CommonTokenStream";
import Lexer from "./Lexer";
import Parser from "./Parser";

import RuleContext from "./context/RuleContext";
import ParserRuleContext from "./context/ParserRuleContext";
import ATN from "./atn/ATN";
import PredictionMode from "./atn/PredictionMode";
import LL1Analyzer from "./atn/LL1Analyzer";
import ATNDeserializer from "./atn/ATNDeserializer";
import LexerATNSimulator from "./atn/LexerATNSimulator";
import ParserATNSimulator from "./atn/ParserATNSimulator";
import PredictionContextCache from "./atn/PredictionContextCache";
import DFA from "./dfa/DFA";
import RecognitionException from "./error/RecognitionException";
import FailedPredicateException from "./error/FailedPredicateException";
import NoViableAltException from "./error/NoViableAltException";
import BailErrorStrategy from "./error/BailErrorStrategy";
import Interval from "./misc/Interval";
import IntervalSet from "./misc/IntervalSet";
import ParseTreeListener from "./tree/ParseTreeListener";
import ParseTreeWalker from "./tree/ParseTreeWalker";
import ErrorListener from "./error/ErrorListener";
import DiagnosticErrorListener from "./error/DiagnosticErrorListener";
import RuleNode from "./tree/RuleNode";
import TerminalNode from "./tree/TerminalNode";
import arrayToString from "./utils/arrayToString";

declare namespace antlr4 {
  export { atn };
  export { dfa };
  export { context };
  export { misc };
  export { tree };
  export { error };
  export { Token };
  export { CommonToken };
  export { CharStreams };
  export { CharStream };
  export { InputStream };
  export { FileStream };
  export { CommonTokenStream };
  export { Lexer };
  export { Parser };
  export { ParserRuleContext };
  export { Interval };
  export { IntervalSet };
  export { LL1Analyzer };
  export { Utils };
}

export default antlr4;

export {
  Token,
  CommonToken,
  CharStreams,
  CharStream,
  InputStream,
  FileStream,
  CommonTokenStream,
  Lexer,
  Parser,
  RuleNode,
  TerminalNode,
  ParseTreeWalker,
  RuleContext,
  ParserRuleContext,
  Interval,
  IntervalSet,
  PredictionMode,
  LL1Analyzer,
  ParseTreeListener,
  ATN,
  ATNDeserializer,
  PredictionContextCache,
  LexerATNSimulator,
  ParserATNSimulator,
  DFA,
  RecognitionException,
  NoViableAltException,
  FailedPredicateException,
  ErrorListener,
  DiagnosticErrorListener,
  BailErrorStrategy,
  arrayToString,
};
```

These types are currently missing from the beta release, `CommonToken`, `LL1Analyzer`, but are currently a part of the public exports for antlr4 (and have definitions on @types :) )

As a side note, I noticed while inspecting the newest index.js:
```js
/* eslint no-unused-vars: [ "off"] */
// need to import unused to force loading
import StringHashCode from './utils/stringHashCode.js';
import CodePointAt from './polyfills/codepointat.js';
import FromCodePoint from './polyfills/fromcodepoint.js';
```

You can remove this ignore by simply importing the files which will execute the contents:
```js
import './utils/stringHashCode.js';
import './polyfills/codepointat.js';
import './polyfills/fromcodepoint.js';
```

If you would like new issues reflecting these, let me know :)

**Comment by Codex-** [comment]
@ericvergnaud had another look this morning with the new beta release, the index typings will need to be updated to accurately reflect the index as described above.

Also, many of the typings are missing APIs that are provided by the @types package, did you want a PR to bring these over and fix the index?

**Comment by ericvergnaud** [comment]
@Codex- the @types package is a random initiative and there is no plan to align with it. We also won't support inferred typings. Our strategy is simple: provide a TypeScript target on top of the existing JavaScript one, without changing it. Many classes are and should remain internal, I see no reason to expose them, rather the opposite. In its current state, the TypeScript target works perfectly, so I see no reason to change anything, unless people hit a blocker. I'm happy to take small improvements such as unused vars for imports.

**Comment by Codex-** [comment]
@ericvergnaud sure, it's reasonable that many classes should remain internal, but to accurately represent the existing javascript runtime with the typescript typings then exported types for the index need to be updated, as currently, they do not represent the actual javascript runtime.

The default export, amongst others, is missing. At the very least, I recommend updating the TS index to represent the JS runtime index exports. Without this, the usage is misleading, and possibly not what you intend.

**Comment by ericvergnaud** [comment]
Well I'm certainly not going to do this since the js exports are a complete mess, resulting from a complex history moving from ES5 without packaging 10 years ago to ES6/commonjs and now ESM. 
At least the typescript runtime starts clean with all (and only) useful classes as top level exports. Developers can simply write:
```typescript
import { x, y, z } from 'antlr4';
```
We won't support any other import pattern unless here is a very string justification for doing so.

**Comment by ericvergnaud** [comment]
@Codex- please close ?
