### ISSUE TITLE
antlr4 JavaScript has incorrect main vs module in package.json

### ISSUE THREAD

**Issue by jharris4** [antlr/antlr4#3917]
Hi, the antlr4 package published to npm has a main entry in the package.json that points to a file with es6 exports.

This breaks bundling with tools like rollup/vite, as files pointed to by main are expected to be commonjs format, whereas the module entry is supposed to be used for files with es6 exports.

Could you please update the package.json for the Javascript package to fix this? Thanks!

**Comment by ericvergnaud** [comment]
Hi,Can you submit a PR ?Envoyé de mon iPhoneLe 4 oct. 2022 à 16:04, Jon Harris ***@***.***> a écrit :﻿
Hi, the antlr4 package published to npm has a main entry in the package.json that points to a file with es6 exports.
This breaks bundling with tools like rollup/vite, as files pointed to by main are expected to be commonjs format, whereas the module entry is supposed to be used for files with es6 exports.
Could you please update the package.json for the Javascript package to fix this? Thanks!

**Comment by jharris4** [comment]
My apologies, it seems there was some strange caching issue with our builds, and clearing the bundler cache resolved the issue. I had missed that the package.json already specifies `"type": "module"` which accomplishes the same things as I was requesting.

Merci d'avoir répondu tellement vite, et désoler pour avoir gaspillé votre temps!
