### ISSUE TITLE
Wrong grammarFileName in generated code

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#3937]
Somehow the grammarFileName is now messed up. We always get:

```
// Generated from java-escape by ANTLR 4.11.1
...
       @Override
        public String getGrammarFileName() { return "java-escape"; }

```

no matter what the grammar file name is.  Tool code gen is messed up.

Seems to be from the templates.  E.g.,

```
fileHeader(grammarFileName, ANTLRVersion, header) ::= <<
<header>

// Generated from <grammarFileName> by ANTLR <ANTLRVersion>
>>

LexerFileHeader(file, lexer, namedActions) ::= <<
<fileHeader(file.grammarFileName, file.ANTLRVersion, namedActions.header)>
```

`file.grammarFileName` isn't right.  Could it be an error in the template engine or object we pass in?

```
static grammarFileName = "<parser.grammarFileName; format="java-escape">";  <=============
```

**Comment by parrt** [comment]
@KvanTTT Looks like you killed `java-escape` in your refactoring (another reason not to resist refactoring).

https://github.com/antlr/antlr4/commit/6a7e651c76215633a71af1fbcd9e0b9190de4e06

**Comment by parrt** [comment]
Solution is maybe to remove java-escape from templates

**Comment by KvanTTT** [comment]
Is it just an error during template rendering? Does it cause any user bug on grammar?

**Comment by parrt** [comment]
getGrammarFileName() functions fail for multiple targets; returns "java-escape" not T.g4 or whatever.  parsing is unaffected.
