### ISSUE TITLE
target is Go but containing c++ code

### ISSUE THREAD

**Issue by Future2100** [antlr/antlr4#3944]
- target language: Go
- grammar: https://github.com/ClickHouse/ClickHouse/tree/master/utils/antlr
- issue: generated parse contains c++ code: std::set<string>

**Comment by ericvergnaud** [comment]
That’s because this grammar is targeted to C++. You’d need to adapt it for go.Envoyé de mon iPhoneLe 1 nov. 2022 à 13:49, Alex ***@***.***> a écrit :﻿


target language: Go
grammar: https://github.com/ClickHouse/ClickHouse/tree/master/utils/antlr
issue: generated parse contains c++ code: std::set

**Comment by Future2100** [comment]
got it. thank you @ericvergnaud
