### ISSUE TITLE
Javascript: Improvements to typescript allowJs integration

### ISSUE THREAD

**Issue by jonaskello** [antlr/antlr4#3955]
Typescript has an option called `allowJs` that allows direct imports of javascript files. This means we can directly import the files generated by antlr4 javascript target. This works well but there are two small fixes that would make a huge difference for this IMO. I think these fixes are non-invasive and backwards compatible.

---

1. Generate context classes with `export` modifier.

Currently code is generated like this in the parser:

**CypherParser.js**
```js
class OC_ExpressionContext extends antlr4.ParserRuleContext {
...
}

// At the end we have this way of exporting the Context classes
CypherParser.OC_ExpressionContext = OC_ExpressionContext;
```

This makes it hard to import the classes as types in typescript, for example this code will not work:

**Consumer.ts**
```ts
import { OC_OrExpressionContext } from "./generated/CypherParser.js";
```

However if we instead generate the code with `export` modifier like this the above code would work, note the added `export` modifier:

**CypherParser.js**
```js
export class OC_ExpressionContext extends antlr4.ParserRuleContext {
...
}
```

---

2. Change the typings in `@types/antlr4` in the file `context/ParserRuleContext.d.ts`

This typescript code will not work because typescript infers the wrong type for the context class:

```ts
function visitOC_Expression(ctx: Cst.OC_ExpressionContext) {
  const o = ctx.oC_OrExpression(); // o will always have type ParserRuleContext
  return visitOC_OrExpression(o); // type of o mismatches, compile error :-(
}

function visitOC_OrExpression(ctx: Cst.OC_OrExpressionContext) {
//...
}
```

If we look in the generated file where where it looks like this:

```js
	oC_OrExpression() {
	    return this.getTypedRuleContext(OC_OrExpressionContext,0);
	};
```

And then we look in the typings for it looks like this (`context/ParserRuleContext.d.ts`):

```ts
    getTypedRuleContext<T extends ParserRuleContext>(cxtType: T, i: number): T;
```

This is what causing typescript to not infer the correct type, if we just change to this the above code will work:

```ts
    getTypedRuleContext<T extends ParserRuleContext>(cxtType: { new (...args: Array<any>): T }, i: number): T;
```

**Comment by jonaskello** [comment]
Regarding (2) above I think this is actually an error in the typings, it is typed to accept a class instance but the generated code passes the class type rather than instance. So I made a [PR to DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63191) for that.

Regarding (1) above I am currently using this script in package.json to work around:

```
    "antlr:fix": "sed -i 's/class OC_/export class OC_/g' packages/xxx/CypherParser.js",
```

**Comment by ericvergnaud** [comment]
Hi,

thanks for this, but maybe there is a misunderstanding ?
At this point the TypeScript target is still WIP and no types have been published to DefinitelyTyped (I suspect these originate from the no longer maintained unofficial TypeScript target ?).
As per the WIP official Typescript target, you are more than welcome to extensively test it (really I’d love that), but you need to run the build script and get the generated types from src/antlr4/index.d.ts 

Eric

**Comment by jonaskello** [comment]
@ericvergnaud No misunderstanding :-) This issue is about the existing Javascript target (not about the WIP typescript target). It is about importing the javascript output (parser, lexer) from the javascript target into a typescript program.  So I am importing the `.js` files produced by the javascript target into a `.ts` file. This might seem strange but it totally possible with the [allowJs](
https://www.typescriptlang.org/tsconfig#allowJs) tsconfig setting.

The output produced by the javascript target has a run-time dependency on the existing [antlr4](https://www.npmjs.com/package/antlr4) npm package. When you use that npm package in a typescript file you must also use the types that goes along with it from the existing [@types/antlr4](https://www.npmjs.com/package/@types/antlr4) package. Both these npm packages has been released for a long time and the source for the `@types/antlr4` package is on DefintelyTyped [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/antlr4).

Hope that makes sense?

**Comment by jonaskello** [comment]
To clarify further, I am using the JavaScript target and generating files with the `-Dlanguage=JavaScript` command line switch. So no typescript target is involved and the generated files are pure JavaScript. Then to use the generated parser, I manually create a typescript file that imports the generated JavaScript files.

Importing the generated `.js` files into a `.ts` file works great except that importing the context classes does not work since they have no  `export` attribute in the generated `.js` files.

Even if the importing file was a `.js` file I think it would still make sense to use proper ECMAScript Modules (ESM) export syntax for exporting the context classes rather than setting them as properties of the Parser class. Perhaps it is better to open a separate issue for this and not talk about typescript in order to avoid confusion?

**Comment by ericvergnaud** [comment]
HiThanks for the clarification.We’re working on an official typescript target, and I’m not sure I can spare any bandwidth to look into this approach.May I suggest that you look into the Typescript WIP branch instead ?EricEnvoyé de mon iPhoneLe 10 nov. 2022 à 20:45, Jonas Kello ***@***.***> a écrit :﻿
To clarify further, I am using the JavaScript target and generating files with the -Dlanguage=JavaScript command line switch. So no typescript target is involved and the generated files are pure JavaScript. Then to use the generated parser, I manually create a typescript file that imports the generated JavaScript files.
Importing the generated .js files into a .ts file works great except that importing the context classes does not work since they have no  export attribute in the generated .js files.
Even if the importing file was a .js file I think it would still make sense to use proper ECMAScript Modules (ESM) export syntax for exporting the context classes rather than setting them as properties of the Parser class. Perhaps it is better to open a separate issue for this and not talk about typescript in order to avoid confusion?

**Comment by jonaskello** [comment]
Ok, I'll go ahead and close this issue and create a new issue for the missing exports that does not refer to typescript as the problem is not directly related to typescript but rather to having proper ES modules in general.

**Comment by jonaskello** [comment]
New issue with just the ESM export bug is now in #3956
