### ISSUE TITLE
Question - Generic Lexical Analyzer outputs.

### ISSUE THREAD

**Issue by Korporal** [antlr/antlr4#4003]
I've not used ANTLR but have written hand lexers and parsers in the past. I wanted to ask, would it be feasible to have ANTLR be able to generate a JSON state machine file (from the token definitions), a representation of the state machine that can then be consumed by any language we care to implement the machine in?

If this were done then writing the lexical analyzer in language X would require just implementing the state machine and initialize that state machine from the JSON (or other suitable format) text.

**Comment by Korporal** [comment]
@kaby76 - Thanks for that info, I'll do some reading! In the meantime, could you point at examples of context free lexical grammars and their actual use? Like what programming languages use such a lexical structure? What would such code look like?

Thanks.

**Comment by Korporal** [comment]
@kaby76  - Much appreciated, that's instructive.

I've been exploring the possibility of a new programming language (basically based on the PL/I language, often characterized by having no reserved words).

Anyway, at the lexical level I've interested in supporting numeric literals that can contain separator spaces (not simply underscores as is common in many languages).

e.g, these tokens would look like, starting with trivial cases that are simply regular:

```
a = 123;
a = 123.456;
a = 123:h; // Hex
a = 10101.1101:b; // binary
a = 101 110 010:b; // binary
a = DEF ABC:h; // hex
a = F0C5 770A.C4:h; // hex
a = 204 701 334:o; // octal
a = BAF4.7603p+4; // hex float
```

I've scraped together code that can recognize these but It's a little messy and I don't want to create messy code really.

Cases like 'DEF ABC:h` present a challenge because that scans into <Identifier> <Identifier> <Colon> <Identifier> and that must be converted eventually, to <NumericLiteral>, with say a lexeme of "DEFABC:h". 

I have added a "hacked" layer into the tokenizer that accumulates <Identifier> tokens looking for the pattern for the literal and when/if it sees that, it discards the accumulated tokens and creates and returns the desired <NumericLiteral> token.

If ANTRL has the power to represent this kind of thing, I will likely want to adopt that for the lexical analysis at least.

A separate question is can ANTRL handle the language grammar that has no reserved words, the way PL/I parser have done this is by having parser that:

1. Asks, is the next statement (sequence of semicolon terminated tokens) an assignment or not?
2. Yes, parse it as an assignment, generate the tree for that.
3. No, treat first token (must be an identifier) as a keyword and if it is, parse the statement as a keyword statement.

I've written such a parser in the past, a hand crafted recursive descent, but have no idea if such a grammar can be represent in systems like ANTLR.

Sorry to ask so many question!

**Comment by kaby76** [comment]
To recognize these numbers, a start would be something like `NUMBER : [0-9] ([ 0-9]* [0-9])? (':' [bho])?;`. Antlr should be able to recognize all those numbers you mentione, but you'll need to play with the rules.

**Comment by Korporal** [comment]
I'm going to close this because its clearly a discussion rather than an issue.

**Comment by kaby76** [comment]
In the future, I don't know if it is available to you, there might be a link on the Issue page to "[c]onvert to discussion".
