### ISSUE TITLE
Problem with latest Javascript runtime environment

### ISSUE THREAD

**Issue by ErikTheBerik** [antlr/antlr4#4082]
I'm trying to use antlr4 js for the browser. Following the instructions on github I used webpack to package antlr4 + my lexer, parser, visitors and listeners into a file and include that. I added the webpack configuration lines:

`resolve: { fallback: { fs: false } }`

 as explained in the readme but I was constantly getting the error:

`Uncaught TypeError: (0 , t.createRequire) is not a function`

I tried using babel-loader and other things. Searching online I found someone mentioning this error in google groups:
https://groups.google.com/g/antlr-discussion/c/TTSSPmD-Uqs/m/HLEiTlkeDAAJ

Seeing this was dated a few weeks ago, I gave up and tried using a different version of antlr4. I downloaded an npm version with a lot of downloads, which was npm version antlr4@4.9.3 and this fixed my problem.

Is it possible that the new version is accidentally calling createRequire somewhere?

**Comment by ericvergnaud** [comment]
No it's not. You might be missing other fallbacks: net, module ?

**Comment by ErikTheBerik** [comment]
Alright, so what should I add to the configuration? 
And how come it worked with an older version?

**Comment by ErikTheBerik** [comment]
Accidentally clicked on "close as completed"

**Comment by ErikTheBerik** [comment]
Alright now it seems to be working with the latest version.  I updated the antlr4 jar file and recreated the lexer and parser. Then used "import" instead of "require" and it worked. Didn't have to change any webpack settings.

Not really sure what was going on and why it worked with the older version. But it's all good now.
