### ISSUE TITLE
TypeScript missing critical class definition exports 

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#4110]
I was trying to write a template for TypeScript for testing the new target on grammars-v4. There is (are) important classes that need to be exported. Otherwise, I am blocked, and there will be no testing of the target in grammars-v4 because the [trgen templates](https://github.com/kaby76/Domemtech.Trash/tree/main/src/trgen/templates) require a consistent runtime API in order to provide consistent functionality across targets.

* Recognizer missing in export list. https://github.com/antlr/antlr4/blob/c2bfa34a66e6449ff6fb2e388e17e2ff4b7e8e82/runtime/JavaScript/src/antlr4/index.d.ts#L10 
* List not sorted alphabetically for quick lookup for missing exports. https://github.com/antlr/antlr4/blob/c2bfa34a66e6449ff6fb2e388e17e2ff4b7e8e82/runtime/JavaScript/src/antlr4/index.d.ts#L1
* TokenSource missing export.
* CommonToken missing TypeScript wrapper declaration and export.

I don't know why certain classes do not have corresponding TypeScript `export class` definition files. It should be identical to the list of exported symbols in Java.

**Comment by ericvergnaud** [comment]
As a principle, I only export what is strictly required, excluding internal classes.
That can be hard to define until you bump into issues.
Can you provide an example of failing generated trgen code ?

**Comment by kaby76** [comment]
> As a principle, I only export what is strictly required, excluding internal classes. That can be hard to define until you bump into issues. Can you provide an example of failing generated trgen code ?

I'm still going through with the creation of the template for TypeScript. So far, it's just Recognizer, which is easy to fix. But, I'll let you know what else may be missing, probably not much because the JavaScript target was working fine.

**Comment by kaby76** [comment]
Also missing is the CharStreams class. I use it in JavaScript ([here](https://github.com/kaby76/Domemtech.Trash/blob/0332403442462a69a322b7289f2f2810b6337559/src/trgen/templates/JavaScript/Test.js#L139), [here](https://github.com/kaby76/Domemtech.Trash/blob/0332403442462a69a322b7289f2f2810b6337559/src/trgen/templates/JavaScript/Test.js#L144), [here](https://github.com/kaby76/Domemtech.Trash/blob/0332403442462a69a322b7289f2f2810b6337559/src/trgen/templates/JavaScript/Test.js#L149)), but there's no TypeScript decl for the class.

**Comment by ericvergnaud** [comment]
CharStreams : There is and it is exported. Please check beta 5 ?

**Comment by kaby76** [comment]
> CharStreams : There is and it is exported. Please check beta 5 ?

Thanks so much, again!!

**Comment by kaby76** [comment]
* Version 4.12.0-beta.5 (and dev branch) doesn't have Recognizer exported.
* CharStreams is not available even in 4.12.0-beta.5. In the JavaScript code, I could [import](https://github.com/antlr/grammars-v4/blob/7da7895563958f405a56e3503dc34fccaac51fa6/_scripts/templates/JavaScript/Test.js#L3) and [reference](https://github.com/antlr/grammars-v4/blob/7da7895563958f405a56e3503dc34fccaac51fa6/_scripts/templates/JavaScript/Test.js#L144) the static methods of CharStreams.js. I can't import CharStreams in typescript, nor can I import the functions of CharStreams.js on [the import statement](https://github.com/kaby76/Domemtech.Trash/blob/0332403442462a69a322b7289f2f2810b6337559/src/trgen/templates/TypeScript/Test.ts#L3), as I can do for `CharStream` and `CommonTokenStream`. Those two are full-fledged classes. while CharStreams is not a class. How can I import the functions in TypeScript?

**Comment by ericvergnaud** [comment]
Let me check that

**Comment by ericvergnaud** [comment]
In TypeScript, CharStreams is a class, and the methods are static methods. 
It's a factory for actual streams, soy should write:
```
import { CharStreams } from 'antlr4';
const stream = CharStream.fromPath(path);
```
I have added Recognizer, and fixed another issue in beta 6.

**Comment by ericvergnaud** [comment]
If you're loading content from files you might want to upgrade to beta 8, I just added the encoding parameter to the FileStream API

**Comment by kaby76** [comment]
Excellent. Thank you.

Two other things that would be nice to have are: `Lexer.reset()` and `ParserATNSimulator.trace_atn_sim`. The later would be really nice since it allows for the parse to be compared across targets, which @Parrt added recently. `ParserATNSimulator.debug`, which is available, but isn't useful because it outputs too much, so output can't be compared across targets as easily.

Otherwise, this works great. Already, the TypeScript port has shown a few problems with the JavaScript driver code I wrote. This is a great port. It's JavaScript finally done right.

**Comment by ericvergnaud** [comment]
Done, check beta 9

**Comment by ericvergnaud** [comment]
and thanks for the compliment, I struggle with some contributors wanting me to reproduce the mistakes accumulated in the js API over 10 years...

**Comment by kaby76** [comment]
Looks like CommonToken is used in a number of base classes of the [python/python3](https://github.com/antlr/grammars-v4/tree/master/python/python3) grammar. That's somewhat easy even for me to fix.
```
import { Token } from "./Token";

export declare class CommonToken extends Token {
    constructor(source: number, type: number, channel: number, start: number, stop: number);
    clone(): CommonToken;
    cloneWithType(type: number): CommonToken;
    toString(): string;
}
```

The base class tries to set [_token](https://github.com/antlr/antlr4/blob/fbd4452fff79c6dab1dcb3e2cdc88f19e82d2b5c/runtime/JavaScript/src/antlr4/Lexer.js#L35), but it can't because [emitToken()](https://github.com/antlr/antlr4/blob/fbd4452fff79c6dab1dcb3e2cdc88f19e82d2b5c/runtime/JavaScript/src/antlr4/Lexer.js#L201) is not available in the TypeScript code. We're also going to need skip(), more(), mode(d).

**Comment by ericvergnaud** [comment]
Hey, what 'base class' are you referring to ?
Can you submit a PR ? That would avoid me adding stuff in the wrong place...

**Comment by ericvergnaud** [comment]
@kaby76 I think we can close this ?

**Comment by RobEin** [comment]
Excuse me..
How can I get the Token.DEFAULT_CHANNEL constant with the TypeScript runtime?

**Comment by ericvergnaud** [comment]
Aargh... it's missing. Can you propose a PR to fix that ?
Until it gets released, you can safely assume its value is 0.

**Comment by RobEin** [comment]
I would need additional features that are missing from the TypeScript runtime:
 - Lexer class:
        _modeStack property ([implemented here](https://github.com/RobEin/antlr4/blob/59410555af53488a2140b5efe419e6a7161980a4/runtime/JavaScript/src/antlr4/Lexer.d.ts#L19))
        mode method ([implemented here](https://github.com/RobEin/antlr4/blob/59410555af53488a2140b5efe419e6a7161980a4/runtime/JavaScript/src/antlr4/Lexer.d.ts#L28))

 - Token class:
        source property ([implemented here](https://github.com/RobEin/antlr4/blob/59410555af53488a2140b5efe419e6a7161980a4/runtime/JavaScript/src/antlr4/Token.d.ts#L12))

 - Recognizer class:
        getSymbolicNames method ([implemented here](https://github.com/RobEin/antlr4/blob/59410555af53488a2140b5efe419e6a7161980a4/runtime/JavaScript/src/antlr4/Recognizer.d.ts#L9))
        getErrorListenerDispatch method ([implemented here](https://github.com/RobEin/antlr4/blob/59410555af53488a2140b5efe419e6a7161980a4/runtime/JavaScript/src/antlr4/Recognizer.d.ts#L10))

**Comment by ericvergnaud** [comment]
Hi. Sure. Can you submit a PR ?
