### ISSUE TITLE
[Javascript] Uncaught TypeError: antlr4_1.default.PredictionContextCache is not a constructor

### ISSUE THREAD

**Issue by hieunguyen2211** [antlr/antlr4#4139]
We upgraded antlr4 to version **4.12.0** from **4.11.0**, then got a problem below when using **generated Parser javascript**:
![Screen Shot 2023-02-24 at 13 57 03](https://user-images.githubusercontent.com/52429592/221112885-349415bf-078e-4c6e-8388-5c0ede50e904.png)

After comparing the code between the 2 versions, I discovered that **PredictionContextCache** has been **removed** from the **export default object** in **index.web.js** (compared to **index.js** in version 4.11.0), leading to the error.

- 4.12.0
`export default {
    atn, dfa, context, misc, tree, error, Token, CommonToken, CharStreams, CharStream, InputStream, CommonTokenStream, Lexer, Parser,
    ParserRuleContext, Interval, IntervalSet, LL1Analyzer, Utils
}`

- 4.11.0
`const antlr4 = {
    atn, dfa, tree, error, Token, CommonToken, CharStreams, InputStream, FileStream, CommonTokenStream, Lexer, Parser,
    PredictionContextCache, ParserRuleContext, Interval, IntervalSet, LL1Analyzer, Utils
};`

- Line of code triggered the error in **generated Parser javascript**:
`const sharedContextCache = new antlr4.PredictionContextCache();`

**Comment by ericvergnaud** [comment]
Hi,

this line of code does not come from the standard parser generator.
Not sure how it is produced, but it can be changed to:
`const sharedContextCache = new antlr4.atn.PredictionContextCache();`

**Comment by hieunguyen2211** [comment]
I tested it with both Scss grammar and Javascript grammar in this grammar repository: https://github.com/antlr/grammars-v4. Both these 2 grammars could work as expected in version 4.11.0, but not in 4.12.0.

**Comment by ericvergnaud** [comment]
Did you regenerate the parser ?

**Comment by hieunguyen2211** [comment]
Of course, I did.

**Comment by hieunguyen2211** [comment]
Oh, sorry, there is a missing configuration on our side. I can fix it now. Thanks a lot for your help.

**Comment by TyrsDev** [comment]
> Oh, sorry, there is a missing configuration on our side. I can fix it now. Thanks a lot for your help.

Would you mind saying what your missing configuration was? I have met the same issue.

**Comment by milahu** [comment]
> Not sure how it is produced, but it can be changed to:
> `const sharedContextCache = new antlr4.atn.PredictionContextCache();`


yes:

```
sed -i -E 's/(new antlr4)(.PredictionContextCache\(\))/\1.atn\2/' MyGrammarParser.js
```

> I have met the same issue.

antlr binary and libray must have the same version

in my case, i used `antlr 4.11.1 binary` to generate the files
MyGrammarLexer.js MyGrammarParser.js MyGrammarParserListener.js

```
$ antlr4 | head -n1 
ANTLR Parser Generator  Version 4.11.1
```

when using these files with the `antlr 4.12.0 libray`, i get the error

```
$ jq -r .version node_modules/antlr4/package.json 
4.12.0

$ node myapp.js
MyGrammarParser.js:218
const sharedContextCache = new antlr4.PredictionContextCache();
                           ^

TypeError: antlr4.PredictionContextCache is not a constructor
```

**Comment by oldpride** [comment]
I got the same error when going over antlr4 tutorial https://tomassetti.me/antlr-mega-tutorial/.

I am using antlr4@4.13.0, node v18.12.

the fix was to change 
`antlr4.PredictionContextCache()`
to 
`antlr4.atn.PredictionContextCache()`

in both 
```
...Lexer.js
...Parser.js
```
**This fix is a hack as I had to change the standard-way-generated js files. I wish someone could fix it in the js package.**

**Comment by milahu** [comment]
> I am using antlr4@4.13.0

either/or:

- use `antlr4` CLI tool version 4.13
- downgrade the NPM package to match your `antlr4` CLI tool version

**Comment by TyrsDev** [comment]
For me, the issue appeared when I used a VSCode extension to generate Lexer and Parser files, because the extension had an old .jar file. The solution was to set the extension's "alternateJar" path to point to my installed, up-to-date .jar version of ANTLR4. The key is like @milahu says above, all tools using ANTLR4 (the one that generates, and the one you run your code with) must be the exact same ANTLR4 version.

**Comment by jimidle** [comment]
This is the answer. If the codegen is incorrect, there is a 99.9% chance
that something is using the wrong jar. After an upgrade, it’s not unusual
for the tooling to take a bit of time to catch up. Understandable.

**Comment by oldpride** [comment]
@jimidle @milahu, agree with both of you. My antlr4 js was 4.13.0 but my jar file was 4.9.3. After I used 4.13.0 jar file, the error went away by itself. thank you for pointing this out.
