### ISSUE TITLE
TypeScript: TokenStream.d.ts prototypes for `getHiddenTokensToLeft/Right()` don't match implementations

### ISSUE THREAD

**Issue by sp-llminc** [antlr/antlr4#4182]
[X] I have reproduced my issue using the latest version of ANTLR (4.12.1 @ 4a30b9a0c8815bc)
[X] I have asked at [stackoverflow](https://stackoverflow.com/questions/75738384/antlr-typescript-target-tokenstream-d-ts-prototypes-for-gethiddentokenstoleft)
[X] [Responses](https://stackoverflow.com/questions/75738384/antlr-typescript-target-tokenstream-d-ts-prototypes-for-gethiddentokenstoleft#:~:text=Those%20declarations%20need%20to%20be%20fixed) from the above seem to indicate that my issue could be an ANTLR bug
[X] I have done a search of the existing issues to make sure I'm not sending in a duplicate

The declared method signatures for TokenStream#getHiddenTokensToLeft and #getHiddenTokensToRight in [TokenStream.d.ts](https://github.com/antlr/antlr4/blob/master/runtime/JavaScript/src/antlr4/TokenStream.d.ts) take strings for their second (channelName) parameters, but TokenStream's only stock subclass, [BufferedTokenStream](https://github.com/antlr/antlr4/blob/8188dc5388dfe9246deb9b6ae507c3693fd55c3f/runtime/JavaScript/src/antlr4/BufferedTokenStream.js#L301), doesn't resolve those channel names; it's expecting integer channel IDs.

```typescript
export declare class TokenStream {
    // ....
    getHiddenTokensToLeft(tokenIndex: number, channelName?: string): Token[];
    getHiddenTokensToRight(tokenIndex: number, channelName?: string): Token[];
    // ...
}
```

```antlr4
lexer grammar QueryLexer;

channels {
    CHANN_WHITESPACE,
    CHANN_COMMENTS
}

// ...

WS:   [ \t\n\r]+ -> channel(CHANN_WHITESPACE) ;
SL_COMMENTS: '//' .*? '\n' -> channel(CHANN_COMMENTS) ;
BL_COMMENTS: '/*' .*? '*/' -> channel(CHANN_COMMENTS) ;
```
Always returns `null`:
```typescript
// `tokenStream` is a `CommonTokenStream`
const comments = this.tokenStream.getHiddenTokensToLeft(startTokenIdx, "CHANN_COMMENTS");
```
Behaves as expected:
```typescript
/* @ts-ignore */ 
const comments = this.tokenStream.getHiddenTokensToLeft(startTokenIdx, 3);
```

**Comment by ericvergnaud** [comment]
This is indeed a bug that will be fixed in the next release.
Thanks
