### ISSUE TITLE
[doc] The doc should not say to set the parser state to build trees--it is the default

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#4195]
This is in regards to https://github.com/antlr/antlr4/issues/4194#issuecomment-1475285198. It's really confusing why I keep seeing people write drivers in the Issues sections or on StackOverflow.com that set the option to build a parse tree. *It is the default.*

The problem is adding this to the driver confuses what the default constructor does. Does it initialize anything? Should I set other properties in the state of the object? Should I set [Profile](https://github.com/antlr/antlr4/blob/8188dc5388dfe9246deb9b6ae507c3693fd55c3f/runtime/CSharp/src/Parser.cs#L1185) to false? Should I set [Trace](https://github.com/antlr/antlr4/blob/8188dc5388dfe9246deb9b6ae507c3693fd55c3f/runtime/CSharp/src/Parser.cs#L1216) to false? What about Lexer()? Should I set defaults there?

* Cpp: *Uses default*. https://github.com/antlr/antlr4/blob/adbe946416f5f6d794ff4c3322739c3c5c20a90c/doc/cpp-target.md
* CSharp: *Setted--unnecessary*. https://github.com/antlr/antlr4/blob/adbe946416f5f6d794ff4c3322739c3c5c20a90c/doc/csharp-target.md?plain=1#L43
* Dart: *Setted--unnecessary*. https://github.com/antlr/antlr4/blob/adbe946416f5f6d794ff4c3322739c3c5c20a90c/doc/dart-target.md?plain=1#L92
* Go: *Setted--unnecessary*. https://github.com/antlr/antlr4/blob/adbe946416f5f6d794ff4c3322739c3c5c20a90c/doc/go-target.md?plain=1#L223
* Java: *Uses default*. https://github.com/antlr/antlr4/blob/adbe946416f5f6d794ff4c3322739c3c5c20a90c/doc/java-target.md
* JavaScript: *Setted--unnecessary*. https://github.com/antlr/antlr4/blob/adbe946416f5f6d794ff4c3322739c3c5c20a90c/doc/javascript-target.md?plain=1#L103
* PHP: *Setted--unnecessary*. https://github.com/antlr/antlr4/blob/adbe946416f5f6d794ff4c3322739c3c5c20a90c/doc/php-target.md?plain=1#L87
* Python: *Uses default*. https://github.com/antlr/antlr4/blob/adbe946416f5f6d794ff4c3322739c3c5c20a90c/doc/python-target.md
* Swift: *Uses default*. https://github.com/antlr/antlr4/blob/adbe946416f5f6d794ff4c3322739c3c5c20a90c/doc/swift-target.md
* TypeScript: *Uses default*. https://github.com/antlr/antlr4/blob/adbe946416f5f6d794ff4c3322739c3c5c20a90c/doc/typescript-target.md

**Comment by KvanTTT** [comment]
@parrt please close
