### ISSUE TITLE
[typescript] Missing InputMismatchException typing

### ISSUE THREAD

**Issue by pl7y** [antlr/antlr4#4204]
I noticed that `antlr4` doesn't expose `InputMismatchException` typings, is that wanted?

**Comment by pl7y** [comment]
To explain better, I was adventuring into antlr4 typescript target and wondering how to manage syntaxt errors to get diagnostics for an IDE.

The basic gist should be something like this:

```
		const parser = new MyGrammarParser(tokenStream);
		
		parser.removeErrorListeners();
		const e = new ErrorListener();
		parser.addErrorListener(e);
```

Nevertheless, the error listener should define its own way to extract errors and create diagnostics. A good way would be for example doing like it's done in `DefaultErrorStrategy.js` `reportError` function:

```js
    reportError(recognizer, e) {
        // if we've already reported an error and have not matched a token
        // yet successfully, don't report any errors.
        if(this.inErrorRecoveryMode(recognizer)) {
            return; // don't report spurious errors
        }
        this.beginErrorCondition(recognizer);
        if ( e instanceof NoViableAltException ) {
            this.reportNoViableAlternative(recognizer, e);
        } else if ( e instanceof InputMismatchException ) {
            this.reportInputMismatch(recognizer, e);
        } else if ( e instanceof FailedPredicateException ) {
            this.reportFailedPredicate(recognizer, e);
        } else {
            console.log("unknown recognition error type: " + e.constructor.name);
            console.log(e.stack);
            recognizer.notifyErrorListeners(e.getOffendingToken(), e.getMessage(), e);
        }
    }
```

So in the end one can implement this `if` chain inside the `syntaxError` method of the ErrorListener to understand what's going on; is this a good idea?

**Comment by ericvergnaud** [comment]
You might be better subclassing DefaultErrorStrategy and overriding the methods of interest.

**Comment by pl7y** [comment]
> You might be better subclassing DefaultErrorStrategy and overriding the methods of interest.

Even this solution sounds good but there is no way of changing the parser error strategy as `setErrorHandler` is not implemented: https://github.com/antlr/antlr4/blob/49b69bb31aa34654676a864b229a369680122470/runtime/Java/src/org/antlr/v4/runtime/Parser.java#L499

Will submit a PR for this.

**Comment by pl7y** [comment]
> InputMismatchException is a miss, would you mind submitting a PR ?

Just spotted that `dev` branch already has this change: https://github.com/antlr/antlr4/blob/dev/runtime/JavaScript/src/antlr4/error/InputMismatchException.d.ts, it just needs to be merged.

**Comment by ericvergnaud** [comment]
JavaScript doesn't need setters, you can just write `parser._errHandler = new MyStrategy()`

**Comment by pl7y** [comment]
> You might be better subclassing DefaultErrorStrategy and overriding the methods of interest.

Still didn't look into this, but as I can see from existing typescript typescript definitions there might be something to contribute. 

So for the commit, from this PR of yours https://github.com/antlr/antlr4/pull/4184/files I see that I can just manually edit the definitions. For contributing back to ANTLR4 should I need to do all the steps of https://github.com/antlr/antlr4/blob/master/CONTRIBUTING.md or some of them are automated?

**Comment by ericvergnaud** [comment]
None of them are automated, but for minor contributions you can skip steps 4 to 6.
But to report syntax errors, it is more convenient to add errorListeners than to replace the default error strategy.

**Comment by ericvergnaud** [comment]
Already fixed
