### ISSUE TITLE
Attribute addition request when generating code with CSharp

### ISSUE THREAD

**Issue by SeongSikChae** [antlr/antlr4#4214]
I want to add the property "System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage" when generating code with CSharp.

I want to exclude generated code from CodeCoverage scans.

CodeCoverage scan run command: "dotnet test --collect:"XPlat Code Coverage" --results-directory DirectoryPath"

**Comment by ericvergnaud** [comment]
You already have System.CodeDom.Compiler.GeneratedCode to exclude antlr generated files from a process

**Comment by SeongSikChae** [comment]
> 프로세스에서 antlr 생성 파일을 제외하기 위해 System.CodeDom.Compiler.GeneratedCode가 이미 있습니다.

I'm sorry.
I'm mistaken.
Excluding the corresponding Attribute in the runsettings file gave me what I wanted.
