### ISSUE TITLE
antlr4 jar doubled in size in 4.9.3

### ISSUE THREAD

**Issue by mikolajpod** [antlr/antlr4#4226]
File antlr4-4.9.3.jar is twice as big as antlr4-4.9.2.jar (2 640 255 vs 1 231 617 bytes).
Using 7-zip I can track difference to org\antlr\v4\unicode directory.
Using JD-GUI (Java decompiler) I can see, that in 4.9.3 there are additional wrapper classes which probably increase file size.

![7z_492](https://user-images.githubusercontent.com/80721892/231436833-02a1bdf9-27d2-45ff-9a06-f97fa4f9fbcf.png)
![7z_493](https://user-images.githubusercontent.com/80721892/231436889-a221b142-da3c-4484-b5bb-5fb2c95d7f52.png)

**Comment by ericvergnaud** [comment]
Yes that's because we had to incorporate icu. Is this an issue ?

**Comment by mikolajpod** [comment]
>> Yes that's because we had to incorporate icu.

This is not because of ICU. This is because of template change. Just look at commit d7303647 with message
"Upgrade com.ibm.icu:icu4j to latest (69.1) to avoid potential vulnerabilities it brings Also **change the template to suite this upgrade, as this upgrade makes the java class larger than jvm can accept**." dated at 25.08.2021 17:34.

It changes file unicodedata.st so that now each method is wrapped in separate static class. Class size limit is avoided but with some consequences. I understand, where it comes from and also I understand this was simple and quick resolution of class size limit problem. But maybe it can be done other way, e.g. dividing methods into 2 (or 3 or even 10) classes instead of 1000+

>> Is this an issue ?
Think about all those copies transferred trough Internet and lying on hard drives :)

Best regards,
Mikołaj

**Comment by KvanTTT** [comment]
This looks like a problem.

The size should be decreased to the previous value if it's possible.

**Comment by KvanTTT** [comment]
I've fixed it in referenced PR. FYI, update to the new vesion also increases the size, but generator optimization values more.

**Comment by mikolajpod** [comment]
@KvanTTT Thank you.

**Comment by KvanTTT** [comment]
@parrt it can be closed now.
