### ISSUE TITLE
[typescript] Runtime declares CommonToken(source, .....) wrong.

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#4318]
I need to create a CommonToken for [python3](https://github.com/antlr/grammars-v4/blob/5585fe7e9292a6a3855f2beef36cf75da2b41271/python/python3/JavaScript/Python3LexerBase.js#L59) but for TypeScript. Unfortunately, "source" is declared as a number [here](https://github.com/antlr/antlr4/blob/96f97704a107db99d90ea9503d637104c3bb7afe/runtime/JavaScript/src/antlr4/CommonToken.d.ts#L4). That's wrong. Completely blocked.

**Comment by kaby76** [comment]
Tried and got a couple different things.
```
Python3LexerBase.ts:68:38 - error TS1005: ',' expected.

68         return new CommonToken(source: [ this, this.input_ ], type, 0, start, stop);
                                        ~
```

```
Python3LexerBase.ts:68:33 - error TS2345: Argument of type '(CharStream | this)[]' is not assignable to parameter of type 'number'.

68         return new CommonToken( [ this, this.input_ ], type, 0, start, stop);
                                   ~~~~~~~~~~~~~~~~~~~~~
```

**Comment by kaby76** [comment]
grammars-v4 CI builds use official NPM published packages. 4.13.0 is the latest.

**Comment by ericvergnaud** [comment]
ah.

I guess in the meantime you could write:
new CommonToken( [ this, this.input_ ] as any as number, ... ?

**Comment by kaby76** [comment]
> I guess in the meantime you could write:
> new CommonToken( [ this, this.input_ ] as any as number, ... ?

Thanks, that works. What a weird type checking, coersion language.

The fix--***may be***--seems to be with [CommonToken.d.ts](https://github.com/antlr/antlr4/blob/96f97704a107db99d90ea9503d637104c3bb7afe/runtime/JavaScript/src/antlr4/CommonToken.d.ts).
```
import { Token } from "./Token";
import { CharStream } from "./CharStream";
import { Lexer } from "./Lexer";

export declare class CommonToken extends Token {
    constructor(source: (CharStream | Lexer)[], type: number, channel: number, start: number, stop: number);
    clone(): CommonToken;
    cloneWithType(type: number): CommonToken;
    toString(): string;
}
```
Good. I'll leave this off here for now as I need to back to cleaning up the horrifying chaos with the grammars-v4/python grammars.
