### ISSUE TITLE
[CI testing] Build fails because Python2 is no longer supported on Github Actions.

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#4325]
From the build:
```
 Warning: The support for python 2.7 will be removed on June 19. Related issue: https://github.com/actions/setup-python/issues/672
  Version 2.x was not found in the local cache
  Error: The version '2.x' with architecture 'x64' was not found for macOS 11.7.7.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

Yes, what day is it today?? June 21.

We can't test the Python2 Antlr target anymore. We really should not be trying to support Python 2 with Antlr. Drop the target.

**Comment by ericvergnaud** [comment]
Agreed, now's the time

**Comment by KvanTTT** [comment]
It's duplicate: https://github.com/antlr/antlr4/issues/3266

**Comment by kaby76** [comment]
It's not a duplicate. The build is failing because Python2 is not available on Github Actions. I'm changing the title to reflect that.
