### ISSUE TITLE
is it possible to compile executable from his repository?

### ISSUE THREAD

**Issue by vega0** [antlr/antlr4#4359]
The question in title. Can compile only the library.

**Comment by jimidle** [comment]
Not sure what you mean here. The build process for the ANTLR tool builds jars. The tool jar is executed via the Java command. Or you can just download the pre-built jars from the main website. Please consult the documentation. A script to run the tool will look something like this:

```sh
#!/bin/zsh

alias antlr4='java -Xmx500M -cp "./antlr4-4.12.1-SNAPSHOT-complete.jar:$CLASSPATH" org.antlr.v4.Tool'

antlr4 -Dlanguage=Go -visitor -listener -package parser -o ../parser *.g4
```

Depending on the version of ANTLR, the name of the complete jar, and what outputs you want.

**Comment by vega0** [comment]
where can i get latest antlr4 jar file .

**Comment by jimidle** [comment]
https://tomassetti.me/getting-started-antlr-cpp/

Start with this tutorial. Do you already have C++ experience?

**Comment by vega0** [comment]
> https://tomassetti.me/getting-started-antlr-cpp/
> 
> Start with this tutorial. Do you already have C++ experience?

by default it can be compiled f.e. on manjaro or ubuntu?
