### ISSUE TITLE
[go] generated lexer is not thread safe

### ISSUE THREAD

**Issue by longjiquan** [antlr/antlr4#4400]
![image](https://github.com/antlr/antlr4/assets/31589260/831d9743-832e-4805-a3a5-e23b9a5e608f)

As the above picture showed, when antlr trying to parse text under multiple thread, the access to global variable `str` makes the lexer not thread safe.

**Comment by longjiquan** [comment]
Version: antlr-4.9
Go Target Runtime: 20210826220005-b48c857c3a0e

**Comment by longjiquan** [comment]
I've also tried the newest version `4.13`, but the lexer and parser generated by the `4.13` are also not thread safe, since they will share the DFA. We already use the antlr in the production environment, so anyone can help me on this issue? Thanks in advance.
Please let me know if any other information is required.

**Comment by jimidle** [comment]
They are go routine safe. This looks like your own action is not thread
safe. Can you show me the actions you are using. Actions can usually be
avoided, but I’d need to see your grammar
