### ISSUE TITLE
Golang Visitor Pattern

### ISSUE THREAD

**Issue by mkohlhaas** [antlr/antlr4#4404]
Visitor pattern does not work as expected. Made a smaller [project](https://github.com/mkohlhaas/Antlr4-Golang-Visitor).

Custom visitor method is not called. See also the debug session in `debug-session.txt`.

Kind regards.

**Comment by mkohlhaas** [comment]
Visitor will never be `CalcVisitor` but always `BaseParseTreeVisitor`.

```
> calc/parser.(*StartContext).Accept() ./parser/calc_parser.go:179 (PC: 0x50fd63)
   174:		return antlr.TreesStringTree(s, ruleNames, recog)
   175:	}
   176:	
   177:	func (s *StartContext) Accept(visitor antlr.ParseTreeVisitor) interface{} {
   178:		switch t := visitor.(type) {
   179:		case CalcVisitor:
   180:			return t.VisitStart(s)
   181:	
   182:		default:
   183:			return t.VisitChildren(s)
   184:		}
(dlv) whatis visitor
github.com/antlr4-go/antlr/v4.ParseTreeVisitor
Concrete type: *github.com/antlr4-go/antlr/v4.BaseParseTreeVisitor
```

Maybe a generic `Visit` method is not possible in Golang due to lack of inheritance.

**Comment by mkohlhaas** [comment]
Visitor will never be `CalcVisitor` but always `BaseParseTreeVisitor`.

```
> calc/parser.(*StartContext).Accept() ./parser/calc_parser.go:179 (PC: 0x50fd63)
   174:		return antlr.TreesStringTree(s, ruleNames, recog)
   175:	}
   176:	
   177:	func (s *StartContext) Accept(visitor antlr.ParseTreeVisitor) interface{} {
   178:		switch t := visitor.(type) {
   179:		case CalcVisitor:
   180:			return t.VisitStart(s)
   181:	
   182:		default:
   183:			return t.VisitChildren(s)
   184:		}
(dlv) whatis visitor
github.com/antlr4-go/antlr/v4.ParseTreeVisitor
Concrete type: *github.com/antlr4-go/antlr/v4.BaseParseTreeVisitor
```

Maybe a generic `Visit` method is not possible in Golang due to lack of inheritance and method overloading.

**Comment by mkohlhaas** [comment]
I think the only solution is to write one's own visitor pattern using a type switch which would make the code pretty messy and ugly.

But better than to have type swiches all over the place.

**Comment by jimidle** [comment]
Sorry. I am on vacation have not had time to look at what you are doing but
I have many projects using visitors and listeners.

I can’t see your issue just on my phone.

**Comment by mkohlhaas** [comment]
> Sorry. I am on vacation have not had time to look at what you are doing but I have many projects using visitors and listeners.

No worries. Enjoy your time.

Some sample code would be helpful. I looked at some projects on Github. They almost all use the listener interface. Some use just the basic parser (no listener, no visitor).

[This project](https://github.com/mkohlhaas/Antlr4-Golang-Visitor)  has two commits: the first one is with the visitor pattern, but not working as expected. The second one with what I call a work-around. It"s only a one-liner:

```golang
func (v *Visitor) Visit(t antlr.ParseTree) any {
	return t.Accept(v)
}
```

**Comment by mkohlhaas** [comment]
This is actually the [playground project](https://github.com/mkohlhaas/York-Lassonde-EECS4302-ANTLR4-Parser-Generator-Tutorial-Go) I wanted to do. Uses also the ["work-around"](https://github.com/mkohlhaas/York-Lassonde-EECS4302-ANTLR4-Parser-Generator-Tutorial-Go/blob/6902c637db2dfdf6abbde565acc3cee112700383/visitor/visitor.go#L15C1-L18C1).

**Comment by jimidle** [comment]
Are you creating a type, emedding the base, then implementing the visitor
functions you need?

**Comment by mkohlhaas** [comment]
Yup. Here's the code with the workaround.
```golang
package main

import (
	"calc/parser"
	"fmt"

	"github.com/antlr4-go/antlr/v4"
)

type Visitor struct {
	parser.BaseCalcVisitor
}

func (v *Visitor) Visit(t antlr.ParseTree) any {
	return t.Accept(v)
}

func (v *Visitor) VisitStart(ctx *parser.StartContext) any {
	fmt.Println("StartContext")
	return nil
}

func main() {
	input, _ := antlr.NewFileStream("./test_calc.txt")
	lexer := parser.NewCalcLexer(input)
	tokens := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)
	p := parser.NewCalcParser(tokens)
	s := p.Start_()
	v := &Visitor{}
	v.Visit(s)
}
```

Uncommenting these lines (= the workaround)  won't call my VisitStart(...) method:
```golang
func (v *Visitor) Visit(t antlr.ParseTree) any {
	return t.Accept(v)
}
```

**Comment by jimidle** [comment]
It should be somewhere in the documentation, or tutorials, but that is
implemented for you. Hence when you override it, it stops working. I’ll
give a better explanation when I get back from vacation. I did not design
that, so I don’t remember the exact reasoning, or even if the reasoning is
correct. Remember that embedded interfaces are not OOP though.
