### ISSUE TITLE
A confused command in doc/python-target.md file

### ISSUE THREAD

**Issue by eleveyuan** [antlr/antlr4#4416]
Here is the problem, no big deal, just a confused command in [doc/python-target.md](https://github.com/antlr/antlr4/blob/dev/doc/python-target.md).

<img width="1020" alt="image" src="https://github.com/antlr/antlr4/assets/85916131/a7e0f251-2c7c-428c-9a6a-10262c3d5852">

**Comment by ericvergnaud** [comment]
Which program ? The one for which you are generating a parser ?
I don't think that's possible but maybe you can submit a PR ?
