### ISSUE TITLE
[Go target] ANTLR generated C++ code in go file from ClickHouse.g4

### ISSUE THREAD

**Issue by xiaodp** [antlr/antlr4#4422]
When I use anltr4 to generate Clickhouse SQL parser,  	
there comes out C++ code `GetAttrs() std::set<std::string>` in generated .go file `clickhouse_parser.go`, and report many bugs. 
```
...
type IDictionaryAttrDfntContext interface {
	antlr.ParserRuleContext

	// GetParser returns the parser.
	GetParser() antlr.Parser

	// GetAttrs returns the attrs attribute.
	GetAttrs() std::set<std::string>


	// SetAttrs sets the attrs attribute.
	SetAttrs(std::set<std::string>)


	// Getter signatures
	Identifier() IIdentifierContext
	ColumnTypeExpr() IColumnTypeExprContext
	AllDEFAULT() []antlr.TerminalNode
	DEFAULT(i int) antlr.TerminalNode
	AllLiteral() []ILiteralContext
	Literal(i int) ILiteralContext
	AllEXPRESSION() []antlr.TerminalNode
	EXPRESSION(i int) antlr.TerminalNode
	AllColumnExpr() []IColumnExprContext
	ColumnExpr(i int) IColumnExprContext
	AllHIERARCHICAL() []antlr.TerminalNode
	HIERARCHICAL(i int) antlr.TerminalNode
	AllINJECTIVE() []antlr.TerminalNode
	INJECTIVE(i int) antlr.TerminalNode
	AllIS_OBJECT_ID() []antlr.TerminalNode
	IS_OBJECT_ID(i int) antlr.TerminalNode

	// IsDictionaryAttrDfntContext differentiates from other interfaces.
	IsDictionaryAttrDfntContext()
}
...

```

My java version is :openjdk 17.0.2 2022-01-18,
The grammar file is from https://github.com/ClickHouse/ClickHouse/tree/master/utils/antlr,
The cmd is `java -jar antlr-4.13.1-complete.jar -visitor -Dlanguage=Go -o parser/ ClickHouseLexer.g4 ClickHouseParser.g4`

**Comment by xiaodp** [comment]
have got clues here: https://stackoverflow.com/questions/68687065/how-to-parse-a-clickhouse-sql-statement-using-antrl4

**Comment by lvjinyu** [comment]
> have got clues here: https://stackoverflow.com/questions/68687065/how-to-parse-a-clickhouse-sql-statement-using-antrl4

just want to know how you finally solved it.  modify the generated code? Can you give me some suggestions?

**Comment by jimidle** [comment]
The C code was in the grammar. Replace it with go code.
