### ISSUE TITLE
[Antlr4 JS/TS] Imports in TypeScript declarations don't match imports in implementations

### ISSUE THREAD

**Issue by DNikolaevAtRocket** [antlr/antlr4#4456]
Imports in TypeScript declarations don't match imports in implementations which causes runtime errors for some classes.

- [x] I have reproduced my issue using the latest version of ANTLR (=4.13.0)
- [x] I have done a search of the existing issues to make sure I'm not sending in a duplicate

## Code to reproduce

The code below compiles but throws a TypeError in runtime (`Super expression must either be null or a function`).
It simply can't find the `ErrorListener` class.
Other classes also can be affected.

```typescript
import antl4 from 'antlr4';

export class CustomErrorListener extends antl4.ErrorListener<any> {
...
}
```

Changing it to named import fixes the issue:

```typescript
import { ErrorListener } from 'antlr4';

export class CustomErrorListener extends ErrorListener<any> {
...
}
```

## Possible cause

Per my research, imports in TypeScript declarations simply don't match imports in JS implementations.
E.g. `ErrorListener` is not imported as default in `index.*.js`.

**Comment by ericvergnaud** [comment]
Hi,
thanks for this, but IIUC the latter approach works ? Since it is the recommended approach for TS, not sure there is an issue ? There is no plan to support the former syntax.

**Comment by DNikolaevAtRocket** [comment]
Hi @ericvergnaud,

Thanks for looking into this.

Indeed, now that we've figured out, there's no issue for us.

Just thought that fixing it can save some time and energy for somebody else.
In fact, the both approaches work in TS, and you can merge the first one coded and don't even notice it.

We didn't, and since the import fails during runtime, we didn't spot it immediately and in fact lost a day or two dealing with it.

**Comment by DNikolaevAtRocket** [comment]
Just to make it clearer - I'm not suggesting to support the first approach for imports.
I'm suggesting to change TS declarations to explicitly refuse it during build time so that users won't hit it in runtime.

**Comment by DNikolaevAtRocket** [comment]
Just making it consistent with JS exports should do.
Sure, I'll do a PR once get some spare time.

**Comment by DNikolaevAtRocket** [comment]
Okay, after looking into this deeper, I think it’s not such an issue indeed.

- First of all, the default imports work as designed.
  Turned out that we have `allowSyntheticDefaultImports = true` being implicitly forced by our build system.
  Which makes it compile default imports without any errors despite those not being declared.
  My bad.
  
- Nevertheless, some _named_ TS exports (e.g. `ErrorNode`, `Recognizer` etc.) end up as `undefined` in emitted JS code.
  So, they can be used for typing but not for actual calls.
  Not sure how severe it is; I'm not an expert, and maybe they aren't meant for anything but typing.
  
 Hence, closing the issue.
 Thank you.

**Comment by ericvergnaud** [comment]
Thanks! Nobody should need Recognizer, but maybe that's less true for ErrorNode... We'll deal with the unlinked types on a case be case basis.
