### ISSUE TITLE
Broken javascript download link

### ISSUE THREAD

**Issue by ZeralldMC** [antlr/antlr4#4537]
Fix the javascript target link to download please

**Comment by ericvergnaud** [comment]
Which link?

**Comment by ZeralldMC** [comment]
> Which link?

https://github.com/antlr/antlr4/blob/dev/doc/javascript-target.md

![image](https://github.com/antlr/antlr4/assets/115047953/3d9073bd-8318-44ab-a301-8faeccdd1113)
Download section is not found:
![image](https://github.com/antlr/antlr4/assets/115047953/9e91c61e-fb7a-4286-b59e-3947af22abf7)

**Comment by ericvergnaud** [comment]
From npm
