### ISSUE TITLE
ANTLR not recognizing label assignment

### ISSUE THREAD

**Issue by clueless-skywatcher** [antlr/antlr4#4542]
Target Language: Java
Antlr Version: 4.13.2
IDE: Visual Studio Code (Version 1.86.2)
IDE Extension: ANTLR4 grammar syntax support (Version 2.4.6)
Build System: Gradle

I am following a video to create a parser, and I need to parse strings and capture the parsed string in a variable. The rule for matching strings is as follows
```
STRING
    :   '"' 
        { StringBuilder b = new StringBuilder(); }
        (c=~('\n' | '\r' | '"') { b.appendCodePoint(c); })*
        '"'
        {setText(b.toString());}
    ;
```
At the equals sign (next to the "c" label in the next line after the StringBuilder initialization), ANTLR complains
```
syntax error: '=' came as a complete surprise to me while looking for lexer rule element
```
while no such issues popped up on the video.

Any help to resolve this issue and pointing out where I am going wrong would be highly appreciated. Is this due to a version mismatch since in the video they were using ANTLR 3.x?

**Comment by jimidle** [comment]
You need to use $ so that the code gen uses the correct reference code

$xxx

And so on.

**Comment by clueless-skywatcher** [comment]
@jimidle I fixed that just now and it's still throwing the error
```
STRING
    :   '"' 
        { StringBuilder b = new StringBuilder(); }
        (c=~('\n' | '\r' | '"') { $b.appendCodePoint(c); })*
        '"'
        {setText($b.toString());}
    ;
```
Where do I need to add the $ sign?

**Comment by jimidle** [comment]
Ah. I see what you are doing. Your atribgbuikder is out of scope. You need
to declare it in the @decls {} section. Ignite the $ comment. That’s for
labels in your grammar

**Comment by clueless-skywatcher** [comment]
@jimidle The problem is not with the StringBuilder here. It's just that ANTLR refuses to acknowledge the "=" sign beside the "c". Declaring the StringBuilder in the decls section still didn't fix the issue.

**Comment by clueless-skywatcher** [comment]
Here is the full grammar for reference
```
grammar Lark;

options {
    language = Java;
}

@header {
import java.util.*;
}

@decls {
    StringBuilder idB = new StringBuilder();
}
        
prog
    : stmt+
    ;

stmt
    : expr ';'
    | term ';'
    | assign ';'
    | functionDef ';'
    | functionAnonDef ';'
    | functionCall ';'
    ;

functionCall
    : IDENTIFIER '(' actualParams? ')'
    ;

actualParams
    : expr (',' expr)*
    ;

term
    : IDENTIFIER
    | '(' expr ')'
    | INTEGER
    | DECIMAL
    | STRING
    | CHARACTER
    | IDENTIFIER '(' actualParams? ')'
    ;

assign
    : id=IDENTIFIER ':=' expr { 
        System.out.println($id.text); 
        System.out.println($expr.text);
    }
    ;

returnStmt: 'return' expr ';';

functionDef
    : '<' IDENTIFIER '>' ':=' '(' params? ')' '->' '{'(stmt | returnStmt)*'}'
    ;   // <Func> := (a, b, c) -> {
        //  DoThings();
        // }

functionAnonDef
    : '<' IDENTIFIER '>'
    ;

params
    : param (',' param)*
    ;

param
    : IDENTIFIER
    ;


negate
    : '~'* term
    ;

unary
    : ('+' | '-')* negate
    ;

exponent
    : unary ('^' unary)*
    ;

multiply
    : exponent (('*' | '/' | '%') exponent)*
    ;

add
    : multiply (('+' | '-') multiply)*
    ;

relation
    : add (('=' | '!=' | '<' | '<=' | '>=' | '>') add)*
    ;

expr
    : relation (('and' | 'or') relation)*
    ;

INTEGER: DIGIT+;
DECIMAL: DIGIT+ '.' DIGIT+;

STRING
    :   '"' 
        (c=~('\n' | '\r' | '"') { idB.appendCodePoint(c); })*
        '"'
        {setText(idB.toString());}
    ;
CHARACTER
    : '\'' . '\'' { setText(getText().substring(1, 2));  }
    ;
fragment LETTER: [a-zA-Z];
fragment DIGIT: [0-9];

// NEWLINE: '\n';

IDENTIFIER: LETTER (LETTER | DIGIT)* ;

WS: [ \t\n\r\f]+ -> channel(HIDDEN);
```

**Comment by ericvergnaud** [comment]
Have you tried adding $c instead of c?

**Comment by kaby76** [comment]
STRING is a lexer symbol. You can't define an attribute (`c = .....`) in a lexer rule.

**Comment by clueless-skywatcher** [comment]
After tinkering around a bit I made a workaround like this
```
STRING
    :   '"' 
        ~('\n' | '\r')*
        '"'
        { setText(getText().substring(1, getText().length() - 1)); }
    ;
```
and it currently is working fine for my usecase.

**Comment by jimidle** [comment]
Because it supports many languages you cannot declare it and init it. Just
declare it there and either use @init{} to declare it or init in  code.
Look for examples.

**Comment by clueless-skywatcher** [comment]
Closing this issue since my problem is solved.
