### ISSUE TITLE
Is Java Lexer ATN Serialization explosion expected since 4.7.2?

### ISSUE THREAD

**Issue by dhalperi** [antlr/antlr4#4544]
- [X] I have reproduced my issue using the latest version of ANTLR
- [ ] I have asked at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [ ] Responses from the above seem to indicate that my issue could be an ANTLR bug
- [X] I have done a search of the existing issues to make sure I'm not sending in a duplicate

I was considering an upgrade from 4.7.2 to 4.13.1 - I had been reading release notes, and no major features, but thought I'd take a deeper look today.

Here's the [FlatJuniperLexer](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4) from Batfish. With 4.7.2, the generated `FlatJuniperLexer.g4` file is `1085881` bytes, but with 4.13.1 it's `1658917` bytes (+52.7%). The `diff` is just in the serialized ATN, which was 12263 lines before and 19327 lines after.

I saw a bunch of PRs and issues about optimizing the ATN for Java specially, are we sure this is working as intended?

**Comment by ericvergnaud** [comment]
Hi, can you attach the generated levers ?

**Comment by jimidle** [comment]
This has nothing to do with the expansion of the size of the serialized ATN , which I think is just related to valid changes that were made and likely isn't an issue, and so long as performance is good and thre are no obvious bugs, then jsut go with it.

However, without trying to insult anyone, this lexer is trying to do way too much at too low a level. Without looking at the parser, which is possibly making the same mistakes, it violates some principles that I have found to be useful over many years.I have not put a lot of time into this grammar, but here's some observations (it may be too late to warrant big changes in thesde grammars but this might be useful information).

Some principles:

  - Make the lexer as general as possible: keywords only when they really are keywords and not just qualifiers or options that are only valid in certain cases. Anything not an actual punctuation, keyword, or formulation such as a numeric, string, etc is just a WORD.
  - The lexer doesn't try to identify unknown words, it just has a final rule: INVALID: . ; which the parser will show as a parser error.
  - The lexer never throws errors
  - In general the lexer is as simple as possible and does not try to identify errors, os use modes to asy what the next set of WORDs should be. This lexer does the exact opposite.
  - The parser also should be pretty lenient. Anything that looks like it is possibly valid syntax is accepted
  - The next pass is a tree walk. Here is where you actually have errors such as "'xxxx' is not a valid qualifier for the 'yyyy' statement"

The basic premise is that all error detection should be push as far up the tool chain as possible as each higher level has more context and the error messages you can then generate are much more useful. 

I published a longer article about this somewhere a long time ago. The ANTLR wiki probably, but someone deleted my account from the WIki and all my articles have been orphaned/unattributed ;)

If it works though, then I think you just accept the increase in ATN size, don't worry about changing it, and just use it. It is probably faster, if that is of relevance to this project.

**Comment by dhalperi** [comment]
@jimidle - thanks for the comments. that's good insight. I would love to reach out to discuss if you have time.

The tl;dr is we're lexing and parsing a grammar that is undocumented, extremely context sensitive, and we can never reject invalid input (but instead have to recover and proceed). So we're not doing "acceptance tests on a well-defined language", but rather incrementally and gracefully parsing an unknown issue.

**Comment by jimidle** [comment]
> @jimidle - thanks for the comments. that's good insight. I would love to reach out to discuss if you have time.
> 
> The tl;dr is we're lexing and parsing a language that is undocumented, extremely context sensitive, and we can never reject invalid input (but instead have to recover and proceed). So we're not doing "acceptance tests on a well-defined language", but rather incrementally and gracefully parsing an unknown and incompletely documented language.

Sure Dan. jimi@idle.ws

No real criticism intended as sometimes more context is needed. And of course there can be a myriad use cases such as  converting known perfect syntax to highlighting and suggesting continuations in an editor where you are more or less guaranteed to be dealing with syntax errors. 

In fact the approach above started when I had to rewrite the JavaFX parser so that it could generate partial trees for the Netbeans editor. 

I have used Jupiter on and oiff, and I think that you mean that invalid input is just ignored and you go to the next input.

Feel free to contact me.

**Comment by ericvergnaud** [comment]
Re the serialization of the ATN, unless you genuinely care about the source code size, I don't think there's any issue. What matters is the size of the resulting `.class` files.  AFAIK `\6` and `\u0006` compile to the same utf-16 character, so the compiled files should have almost the same size.

**Comment by dhalperi** [comment]
Thanks, that makes sense!
