### ISSUE TITLE
ATN.NextToken(state) should be memoized

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#4560]
I was going through a bug in Antlr4ng when I came across an observation. The computation for ATN.NextToken(ATNState) should be memoized. This method recursively goes through an ATN graph to find the list of tokens that *are possible*. The computation does not depend on anything but the ATNState number and context (which is null many times). But, interpreting what can be a valid token at a state is very expensive.

**Comment by kaby76** [comment]
Seems it either doesn't happen very often, or it's already memoizing.

**Comment by ericvergnaud** [comment]
Were you able to dig into the ATNConfig hashCode caching topic ?
