### ISSUE TITLE
Migration bug in golang runtime 

### ISSUE THREAD

**Issue by wyapams** [antlr/antlr4#4567]
The documentation from the antlr website [here](https://github.com/antlr/antlr4/blob/master/doc/go-target.md) recommends using  `import "github.com/antlr4-go/antlr/v4"` 

However, documentation [here](https://github.com/antlr/antlr4/blob/master/runtime/Go/antlr/README.adoc) suggests using ` github.com/antlr4-go/antlr`

1) Do we use both versions of antlr such that go.mod looks like
```
	github.com/antlr4-go/antlr v0.0.0-20230518091524-98b52378c522
	github.com/antlr4-go/antlr/v4 v4.13.0
```

2) Using `github.com/antlr4-go/antlr` as the import seems to cause the error below

Steps to repro.

1) Use `"github.com/antlr4-go/antlr"` runtime
2) Generate lexer/parser
3) add something along the lines of 
```
	input := antlr.NewInputStream(inQuery)
	lexer := generated.NewCypherLexer(input)
```
4) Error repoduced. Example: `cannot use input (variable of type *"github.com/antlr4-go/antlr".InputStream) as "github.com/antlr4-go/antlr/v4".CharStream value in argument to generated.NewCypherLexer: *"github.com/antlr4-go/antlr".InputStream does not implement "github.com/antlr4-go/antlr/v4".CharStream (wrong type for method GetTextFromInterval)`

Current workaround seems to be to use "github.com/antlr4-go/antlr/v4" instead of the official repo.

**Comment by kaby76** [comment]
> The Golang recommended runtime https://github.com/antlr4-go/antlr?tab=readme-ov-file has a different interface from https://github.com/antlr4-go/antlr?tab=readme-ov-file.

These two links are exactly the same. What two runtimes are you actually referring to? Please check your links.

**Comment by wyapams** [comment]
> These two links are exactly the same. What two runtimes are you actually referring to? Please check your links.
I update the comments. Apologies for the confusion

> There was a change to the error interface and I think an ADDITION to input, but my own parsers and walkers are all working fine so long as you use the latest ANTLR tool jar and the latest antlr4-go runtime. Are you sure that you re-genrated?

I regenerated and updated issue description

**Comment by jimidle** [comment]
> The documentation from the antlr website [here](https://github.com/antlr/antlr4/blob/master/doc/go-target.md) recommends using  `import "github.com/antlr4-go/antlr/v4"` 
> 
> 
> 
> However, documentation [here](https://github.com/antlr/antlr4/blob/master/runtime/Go/antlr/README.adoc) suggests using ` github.com/antlr4-go/antlr`
> 
> 
> 
> 1) Do we use both versions of antlr such that go.mod looks like
> 
> ```
> 
> 	github.com/antlr4-go/antlr v0.0.0-20230518091524-98b52378c522
> 
> 	github.com/antlr4-go/antlr/v4 v4.13.0
> 
> ```
> 
> 
> 
> 2) Using `github.com/antlr4-go/antlr` as the import seems to cause the error below
> 
> 
> 
> Steps to repro.
> 
> 
> 
> 1) Use `"github.com/antlr4-go/antlr"` runtime
> 
> 2) Generate lexer/parser
> 
> 3) add something along the lines of 
> 
> ```
> 
> 	input := antlr.NewInputStream(inQuery)
> 
> 	lexer := generated.NewCypherLexer(input)
> 
> ```
> 
> 4) Error repoduced. Example: `cannot use input (variable of type *"github.com/antlr4-go/antlr".InputStream) as "github.com/antlr4-go/antlr/v4".CharStream value in argument to generated.NewCypherLexer: *"github.com/antlr4-go/antlr".InputStream does not implement "github.com/antlr4-go/antlr/v4".CharStream (wrong type for method GetTextFromInterval)`
> 
> 
> 
> 
> 
> 
> 
> Current workaround seems to be to use "github.com/antlr4-go/antlr/v4" instead of the official repo.
> 
> 
> 
> 
> 
> 

> Current workaround seems to be to use "github.com/antlr4-go/antlr/v4" instead of the official repo.

As per the docs, that IS the official repo. 

Can you post an example that reproduces this? I think you've just missed that the antlr4-go library is the official one and your trying your best to include two modules for sone reason

**Comment by wyapams** [comment]
I think most of the confusion is just being caused by looking at both sources of documentation. I reran the setup following the doc [here](https://github.com/antlr/antlr4/blob/master/doc/go-target.md) and things seem to be working again. Thank you for looking into this.
