### ISSUE TITLE
[TypeScript target] I would like to know how to create a custom visitor in TypeScript.

### ISSUE THREAD

**Issue by YuMuuu** [antlr/antlr4#4605]
I would like to know how to create a custom visitor in TypeScript.

I'm referring to the following documentation:
https://github.com/antlr/antlr4/blob/dev/doc/typescript-target.md#how-do-i-create-and-run-a-visitor

In this documentation, it calls the children instance variable from the variable cxt of type ParserRuleContext.

But, when looking at the method definition of visitChildren, the type of the argument for the visitChildren function is RuleNode.

https://github.com/antlr/antlr4/blob/380ce4b8b1658df16ada45e1d56d5aa476052376/runtime/JavaScript/src/antlr4/tree/ParseTreeVisitor.d.ts#L6

Additionally, when looking at the definition of RuleNode and its parent class ParseTree, there doesn't seem to be a definition for the variable children.

https://github.com/antlr/antlr4/blob/380ce4b8b1658df16ada45e1d56d5aa476052376/runtime/JavaScript/src/antlr4/tree/ParseTree.d.ts

How can I define a custom visitor as described in the TypeScript-target documentation?

I think the same issue may be occurring in JavaScript as well.

thank you.

## environment

```shell
$node -v
v22.0.0

$java --version
openjdk 22 2024-03-19
OpenJDK Runtime Environment Corretto-22.0.0.36.2 (build 22+36-FR)
OpenJDK 64-Bit Server VM Corretto-22.0.0.36.2 (build 22+36-FR, mixed mode, sharing)

$antlr 
ANTLR Parser Generator  Version 4.13.1

$npm list --depth=0
(abbreviation)
├── @types/antlr4@4.11.6
├── @types/node@20.12.7
├── antlr4@4.13.1-patch-1
└── typescript@5.4.5
```

**Comment by kaby76** [comment]
Here is a repo containing an example for an "Expression" grammar with TypeScript: https://github.com/kaby76/ExpressionTypeScript.  I gathered the visitor code from [Antlr4ng](https://github.com/mike-lischke/antlr4ng/tree/master?tab=readme-ov-file#usage) , which is a fork of Antlr4, then ported it back to Antlr4. That example didn't work for Antlr4ng either (compilation errors among other problems).

But, to implement an Antlr visitor in TypeScript, you need to override every single visitor "method". In the example I provide, I didn't implement methods for subtraction, multiplication, or division, but you should get the point. From command line, `bash run.sh -input '1+2'`.

**Comment by YuMuuu** [comment]
@kaby76
Thank you for quick reply.
I haven't tried this code yet, do I need to write code for the Visitor by myself instead of antlr?
And do I need to fix the Typescript implementation of the automatic generation to contribute to the document?

**Comment by YuMuuu** [comment]
I was able to understand the example you gave by running.

And what I wanted to say is how to fix this [document](https://folio-sec.slack.com/archives/C01V3EPJND6/p1714452761847239), I understand that too.

Thank you.
