### ISSUE TITLE
How to make antlr4 skip the intermediate errors and continue parsing backward when parsing Sql?

### ISSUE THREAD

**Issue by openai0229** [antlr/antlr4#4670]
I want to use antlr4 to separate a batch of Sql independently one by one, but if there is a syntax error in a certain Sql, all the Sql after this error will not be parsed correctly.

Should I develop a detailed error response strategy or modify the grammar file?

**Comment by jimidle** [comment]
Parse each line separately. However, most of the Sql parsers in the open source domain are not good, so your mileage may vary. What are you trying to parse?
