### ISSUE TITLE
generate go lexer file error

### ISSUE THREAD

**Issue by 447491480** [antlr/antlr4#4671]
antlr version 4.13.1 or 4.13.2。 

more detail please see the archive.zip

![image](https://github.com/user-attachments/assets/151b8940-0038-450e-86ce-f281cfd88c4e)
[
[Archive.zip](https://github.com/user-attachments/files/16494071/Archive.zip)
](url)

**Comment by kaby76** [comment]
Your grammar LuaLexer.g4 contains Java source code.
```
fragment
Letter
	:	[a-zA-Z$_] // these are the "java letters" below 0x7F
	|	// covers all characters above 0x7F which are not a surrogate
		~[\u0000-\u007F\uD800-\uDBFF]
		{Character.isJavaIdentifierStart(_input.LA(-1))}?
	|	// covers UTF-16 surrogate pairs encodings for U+10000 to U+10FFFF
		[\uD800-\uDBFF] [\uDC00-\uDFFF]
		{Character.isJavaIdentifierStart(Character.toCodePoint((char)_input.LA(-2), (char)_input.LA(-1)))}?
	;

fragment
LetterOrDigit
	:	[a-zA-Z0-9$_] // these are the "java letters or digits" below 0x7F
	|	// covers all characters above 0x7F which are not a surrogate
		~[\u0000-\u007F\uD800-\uDBFF]
		{Character.isJavaIdentifierPart(_input.LA(-1))}?
	|	// covers UTF-16 surrogate pairs encodings for U+10000 to U+10FFFF
		[\uD800-\uDBFF] [\uDC00-\uDFFF]
		{Character.isJavaIdentifierPart(Character.toCodePoint((char)_input.LA(-2), (char)_input.LA(-1)))}?
	;
```
Action blocks `{ .... }` or `{ .... }?` are always in the language of the target. You can't compile Java as Go.

**Comment by 447491480** [comment]
> Your grammar LuaLexer.g4 contains Java source code.
> 
> ```
> fragment
> Letter
> 	:	[a-zA-Z$_] // these are the "java letters" below 0x7F
> 	|	// covers all characters above 0x7F which are not a surrogate
> 		~[\u0000-\u007F\uD800-\uDBFF]
> 		{Character.isJavaIdentifierStart(_input.LA(-1))}?
> 	|	// covers UTF-16 surrogate pairs encodings for U+10000 to U+10FFFF
> 		[\uD800-\uDBFF] [\uDC00-\uDFFF]
> 		{Character.isJavaIdentifierStart(Character.toCodePoint((char)_input.LA(-2), (char)_input.LA(-1)))}?
> 	;
> 
> fragment
> LetterOrDigit
> 	:	[a-zA-Z0-9$_] // these are the "java letters or digits" below 0x7F
> 	|	// covers all characters above 0x7F which are not a surrogate
> 		~[\u0000-\u007F\uD800-\uDBFF]
> 		{Character.isJavaIdentifierPart(_input.LA(-1))}?
> 	|	// covers UTF-16 surrogate pairs encodings for U+10000 to U+10FFFF
> 		[\uD800-\uDBFF] [\uDC00-\uDFFF]
> 		{Character.isJavaIdentifierPart(Character.toCodePoint((char)_input.LA(-2), (char)_input.LA(-1)))}?
> 	;
> ```
> 
> Action blocks `{ .... }` or `{ .... }?` are always in the language of the target. You can't compile Java as Go.

Thank you very much, the issue is resolved.
