### ISSUE TITLE
Generate javascript parser with error

### ISSUE THREAD

**Issue by francesc79** [antlr/antlr4#4690]
Hi,

I'm trying to generate a JavaScript parser using the attached [grammar.zip](https://github.com/user-attachments/files/16886165/grammar.zip) grammars, but the generated code contains errors. In particular, the Parser class has a method:

protected void logUseOfReservedWordAsIdentifier(Token token) {
}
which is not compliant with JavaScript.

Thanks,
Francesco

**Comment by kaby76** [comment]
[HqlParser.g4](https://github.com/hibernate/hibernate-orm/blob/52a9de7cacdded9a0b3ff8f94d2c9afccb1cc917/hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4) contains the **Java** method. You have to port the grammar to JavaScript. Antlr "actions" are written in a target-specific language.

**Comment by francesc79** [comment]
thanks @kaby76
