### ISSUE TITLE
The target language is python3 but does not conform to the syntax

### ISSUE THREAD

**Issue by xianghongxu** [antlr/antlr4#4695]
Hi, I followed the instructions and I met some problems in using antlr4 to translate the MySQL grammar lexer and parser to Python3.

Maybe there is some problem with Python support, or maybe there is something wrong with my usage. Can anyone help me? 

I download the `g4` files from https://github.com/antlr/grammars-v4/tree/master/sql/mysql/Oracle. My antlr4 version is 4.13.2 and I set the target language as Python3. However, the output does not conform to the syntax of Python3.

The result of `antlr4 -Dlanguage=Python3 MySQLLexer.g4` has several syntax errors:
1. `this` should be `self` in Python
2. `true` should be `True`.
3. Invalid expressions like `!` and `&&`
4. `SqlMode` is not defined.

![image](https://github.com/user-attachments/assets/1dcf9271-bf7c-48b6-abc1-da645bfeabf3)
![image](https://github.com/user-attachments/assets/bf1cc483-337e-4be3-b536-5b9dbd4702ef)
![image](https://github.com/user-attachments/assets/5e88c06b-f76b-4aba-88fb-0fcdf2d9dd20)
![image](https://github.com/user-attachments/assets/709cc70d-9dc4-48b8-a963-37b894f148c3)

**Comment by ericvergnaud** [comment]
That's because you're using a grammar designed for Java. You need to migrate it to Python.

**Comment by xianghongxu** [comment]
> That's because you're using a grammar designed for Java. You need to migrate it to Python.

Thanks for your quick reply. This issue can be closed.

**Comment by RobEin** [comment]
[This](https://github.com/antlr/grammars-v4/blob/master/python/python3/Python3/transformGrammar.py) Python program modifies the grammar for the Python target.
