### ISSUE TITLE
Are 4.13.2 JavaScript published files for package https://www.npmjs.com/package/antlr4?activeTab=code correct?

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#4699]
I've been having difficulty building JavaScript-targeted Antlr apps. So, I looked at what is in https://www.npmjs.com/package/antlr4?activeTab=code, which is reflected in the installed package.

Open a browser to https://www.npmjs.com/package/antlr4?activeTab=code. Then, open the `src/` then `antlr4` items. Look at all the source code files. *There are no .js files.*

Now, open https://www.npmjs.com/package/antlr4/v/4.13.1?activeTab=code. Then, go to src/antlr4/. *This version of the package contains .js files.*

Is this really correct?

**Comment by ericvergnaud** [comment]
Yes, it's correct. The source code is web packed to 4 files (for web/node and CommonJS/modules) under the `dist` folder

**Comment by ericvergnaud** [comment]
These files are described in package.json

**Comment by kaby76** [comment]
Then why were the src/ directory .js files provided before, in 4.13.1?? By your reasoning, they should have never been there--ever! What changed?

**Comment by ericvergnaud** [comment]
Indeed they should never have been there (at least since we properly webpack).

**Comment by kaby76** [comment]
> I've been having difficulty building JavaScript-targeted Antlr app.

> Indeed they should never have been there (at least since we properly webpack).

It turns out I can test grammars without Webpack using Node v22.8.0. I still cannot get a test working with Webpack. (All files for building and testing, in template format, are here: https://github.com/kaby76/grammars-v4/tree/74c37af4f3950dc7ed7ac5f21c92b61d242ea769/_scripts/templates/JavaScript.)

Also, some grammars in grammars-v4 were breaking because [the JavaScript runtime now outputs a warning message when using mode()](https://github.com/antlr/antlr4/blob/2a7904a595479954ccfb1c78124fc3d7f5bebcb1/runtime/JavaScript/src/antlr4/Lexer.js#L175-L178). All output is captured and compared to a previous run.
