### ISSUE TITLE
antlr4 Trees module missing in JS runtime

### ISSUE THREAD

**Issue by ZengLawrence** [antlr/antlr4#4715]
I am trying import Trees module from JS runtime, but get "Cannot find module 'antlr4/tree/Trees' or its corresponding type declarations" error. See below screenshot.

![Screenshot 2024-10-16 at 8 52 55 PM](https://github.com/user-attachments/assets/91e8180b-a17a-4bf7-9e25-5f11f6621026)

`
import Trees from "antlr4/tree/Trees";
`

Based on the source code [Trees.js](https://github.com/antlr/antlr4/blob/dev/runtime/JavaScript/src/antlr4/tree/Trees.js), I should be able to import use above syntax.

Can someone look into why this module was not packaged into the runtime?

Target runtime: JavaScript / Typescript
Runtime version: 4.13.2

**Comment by ericvergnaud** [comment]
Have you tried import Trees from antlr4 ?Envoyé de mon iPhoneLe 17 oct. 2024 à 03:02, Lawrence Zeng ***@***.***> a écrit :﻿
I am trying import Trees module from JS runtime, but get "Cannot find module 'antlr4/tree/Trees' or its corresponding type declarations" error. See below screenshot.
Screenshot.2024-10-16.at.8.52.55.PM.png (view on web)
import Trees from "antlr4/tree/Trees";
Based on the source code Trees.js, I should be able to import use above syntax.
Can someone look into why this module was not packaged into the runtime?
Target runtime: JavaScript / Typescript

**Comment by ZengLawrence** [comment]
Tried import directly from 'antlr4' and got the same error. See below.

`
import { Trees } from "antlr4";
`

![Screenshot 2024-10-17 at 6 50 15 PM](https://github.com/user-attachments/assets/69198ede-acd6-4c17-b46c-3e628b188871)

The problem might be there is no `Trees.d.ts` type definition for `Trees.js`. I see all other modules in `/tree` folder has type definition except `Trees.js`. See [link](https://github.com/antlr/antlr4/tree/dev/runtime/JavaScript/src/antlr4/tree) to folder in repo.

**Comment by ericvergnaud** [comment]
Ah. Maybe submit a PR?Envoyé de mon iPhoneLe 18 oct. 2024 à 00:55, Lawrence Zeng ***@***.***> a écrit :﻿
Tried import directly from 'antlr4' and got the same error. See below.
import { Trees } from "antlr4";
Screenshot.2024-10-17.at.6.50.15.PM.png (view on web)
The problem might be there is no Trees.d.ts type definition for Trees.js. I see all other modules in /tree folder has type definition except Trees.js. See link to folder in repo.
