### ISSUE TITLE
JavaScript runtime ErrorListener Type definition not in sync

### ISSUE THREAD

**Issue by elorzafe** [antlr/antlr4#4730]
First of all thank you very much for this tool! Kudos and keep this awesome work.

I found that [ErrorListener.d.ts](https://github.com/antlr/antlr4/blob/dev/runtime/JavaScript/src/antlr4/error/ErrorListener.d.ts) is not in sync with actual JS module [ErrorListener.js](https://github.com/antlr/antlr4/blob/dev/runtime/JavaScript/src/antlr4/error/ErrorListener.js) 

Basically `ErrorListener` class is missing this methods on `d.ts` file.

```javascript
    reportAmbiguity(recognizer, dfa, startIndex, stopIndex, exact, ambigAlts, configs) {
    }

    reportAttemptingFullContext(recognizer, dfa, startIndex, stopIndex, conflictingAlts, configs) {
    }

    reportContextSensitivity(recognizer, dfa, startIndex, stopIndex, prediction, configs) {
    }
```

Thanks again for antlr!

**Comment by ericvergnaud** [comment]
Thanks for this. Can you submit a PR?

**Comment by elorzafe** [comment]
Hi @ericvergnaud 

I submitted the PR, maybe you can take a look.

Thanks!
