### ISSUE TITLE
antlr4 depends on antlr-runtime:3.5.3 and breaks itself

### ISSUE THREAD

**Issue by burdoto** [antlr/antlr4#4742]
Java: `openjdk 21.0.5 2024-10-15`
IDE: `IntelliJ IDEA 2024.3 (Ultimate Edition)`
Build system: `Gradle 8.10`

After adding antlr to my repo with these additions to `build.gradle`:
```groovy
plugins {
    id 'application'
    id 'antlr'
}

// ...

tasks.compileJava {
    dependsOn tasks.generateGrammarSource
}

generateGrammarSource {
    arguments += ['-visitor',
                  '-package', 'com.mydomain.htc.antlr.generated']
}

dependencies {
    antlr 'org.antlr:antlr4:4.+'
    implementation 'org.antlr:antlr4-runtime:4.+'
}
```
I was able to generate antlr source files; however when trying to compile I am encountering a problem where my generated Lexer and Parser files depend on classes from the package `org.antlr.v4.runtime`, but classes from the runtime depend on `org.antlr.runtime`.
I was not able to find any sort of arguments or causes for this, other than possibly having antlr3 somewhere in the dependencies.
Upon checking `gradle dependencies`, I noticed that `org.antlr:antlr4:4.+` depends on `org.antlr:antlr-runtime:3.5.3`:
```
antlr
\--- org.antlr:antlr4:4.+ -> 4.13.2
     +--- org.antlr:antlr4-runtime:4.13.2
     +--- org.antlr:antlr-runtime:3.5.3
     +--- org.antlr:ST4:4.3.4
     |    \--- org.antlr:antlr-runtime:3.5.3
     +--- org.abego.treelayout:org.abego.treelayout.core:1.0.3
     \--- com.ibm.icu:icu4j:72.1
```
trying to exclude this group and module from the `antlr` dependency declaration ended up in gradle not recognizing the `antlr` dependency declaration anymore

###### i'm sorry, i love antlr so much. but why is it always a pain to use?

**Comment by jimidle** [comment]
Gradle has always seemed weak to me, but to each their own :)

The Antlr tool depends on ANTLR 3, but the runtime does not. So use the antlr tool jar for generating and the antlr runtime for building. Use the ANTLR plugin.

You might find inspiration here: t.ly/jYBA7

**Comment by burdoto** [comment]
oh boy, this is incredible. i could have all the time simply used the classes from the v4 package. duh.
