### ISSUE TITLE
Need action when matching a fragment lexer rule

### ISSUE THREAD

**Issue by Anthony-Breneliere** [antlr/antlr4#477]
I need to translate a token that is a fragment token before sending it to the parser.

I began a V4.2 ANTLR grammar because it does support lexer modes. I don't know if I should come back to the V3 ANTLR grammar from which I do have the documentation.

Translating the final token would mean 2nd-level parsing of a long string. For performance reason I need the translation to be done in the lexer, at the level of the fragment rule.

**Comment by ashanand** [comment]
Why is whitespace(' ') returning <EOF> in my code?

grammar VB6;
/*
* Parser Rules
*/
compileUnit: module+ EOF;
module:declareStmt ;
declareStmt :WS? eqnStmt     #eqStatement; 
eqnStmt: VAR WS? EQ WS? NUM;

/*
* Lexer Rules
*/
NUM:[0-9]+;
VAR: LETTER LETTERORDIGIT*;
EQ : '=';
WS : [ \t]+;

// letters
fragment LETTER : [a-zA-Z];
fragment LETTERORDIGIT : [a-zA-Z0-9];

// case insensitive chars
fragment A:('a'|'A');
fragment B:('b'|'B');
fragment C:('c'|'C');
fragment D:('d'|'D');
fragment E:('e'|'E');
fragment F:('f'|'F');
fragment G:('g'|'G');
fragment H:('h'|'H');
fragment I:('i'|'I');
fragment J:('j'|'J');
fragment K:('k'|'K');
fragment L:('l'|'L');
fragment M:('m'|'M');
fragment N:('n'|'N');
fragment O:('o'|'O');
fragment P:('p'|'P');
fragment Q:('q'|'Q');
fragment R:('r'|'R');
fragment S:('s'|'S');
fragment T:('t'|'T');
fragment U:('u'|'U');
fragment V:('v'|'V');
fragment W:('w'|'W');
fragment X:('x'|'X');
fragment Y:('y'|'Y');
fragment Z:('z'|'Z');    


Above code is the grammar for variable declaration
Example 1: a=12 //Giving no error
Example 2: a = 12 //line 1:6 no viable alternative at input (EOF)

So Here, my question is
-Why is white space(' ') returning "no viable alternative at input (EOF) " ?
-Check out my grammar for input : 'a = 12'
-Note: There is a space between 'a', '=' and '12'.

**Comment by ericvergnaud** [comment]
Hi,
The place for support is the google discussion group,
Thanks
Eric

Envoyé de mon iPhone

**Comment by manjula91** [comment]
Can you please share the link of google discussion group

**Comment by manjula91** [comment]
Already done may be someone can help :)

**Comment by KvanTTT** [comment]
https://groups.google.com/forum/#!forum/antlr-discussion also you can ask questions on stackoverflow. I think you confused with token and parser rules-they are different.

**Comment by manjula91** [comment]
Thanks KvanTTT

Ok I have already posted my question on google groups. Tokens are here TokenName

TokenName1: 'something1'| 'something3 '
TokenName2: 'something2' | 'something1'

But I above one gives me an error any idea of fixing because it says I can use one value for one token
