### ISSUE TITLE
NullUsageProcessor not compatible with java>6

### ISSUE THREAD

**Issue by dgageot** [antlr/antlr4#487]
I switched to antlr 4.2 because it support java 8 and now I get this warnings:

```
Warning: Supported source version 'RELEASE_6' from annotation processor 'org.antlr.v4.runtime.misc.NullUsageProcessor' less than -source '1.7'
```

Why is NullUsageProcessor activated as soon as I add a dependency to antlr by the way? It's very annoying.

**Comment by tsegismont** [comment]
I've just upgraded to 4.5 and the issue goes away. Thanks @parrt for publishing the 4.5 artifacts to Central with the usual group/artifact IDs. And of course for the huge amount of time saved using ANTLR!

**Comment by parrt** [comment]
we are at your service, Thomas!
Ter
