### ISSUE TITLE
Support indirect left recursion

### ISSUE THREAD

**Issue by sharwell** [antlr/antlr4#522]
Currently ANTLR supports direct left recursion via a transformation prior to generating the parser. It would be helpful if the transformation also supported indirect left recursion.

**Comment by marcospassos** [comment]
Hey folks! Any news about this feature?

**Comment by parrt** [comment]
Hi. not on my side. I don't think i'll support indirect left-recursion.

**Comment by marcospassos** [comment]
Thanks for the feedback, Parr!

**Comment by fawdlstty** [comment]
hello. any news on this feature?

**Comment by parrt** [comment]
Sorry...closing. Sam/I don't have time.
