### ISSUE TITLE
mutually left-recursive error if and only if labels are used

### ISSUE THREAD

**Issue by yankee42** [antlr/antlr4#549]
ANTLR generates Parser/Lexer for the following grammar without any problem:

``` ANTLR
grammar Demo;

x: x x
 | 'y'
 ;
```

If I add labels like this:

``` ANTLR
grammar Demo;

x: one=x two=x
 | 'y'
 ;
```

It suddenly says: `error(119): Demo.g4::: The following sets of rules are mutually left-recursive [x]`

I believe that adding/removing labels should not have such an effect.

**Comment by MiroslavR** [comment]
Can't reproduce with latest ANTLR. This should probably be closed.
