### ISSUE TITLE
create runtime lib w/o dependency on swing for micro devices

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#576]
Requested from Groovy guys: https://twitter.com/jponge/statuses/469403167957204992

**Comment by FroMage** [comment]
+1.

Java ME is not at all a target for me, but I did not expect the runtime of AntLR to be this big. I understand that to _build_ my parser from my grammar I need lots of stuff ( though Swing is pushing it ;) ), but to _run_ my parser I expect a tiny tiny micro jar from AntLR. If anything in my parser relies on the graphical toolkit it's just wrong, so I don't expect those classes to be required.

Just to be clear, IMO relying on `java.util.concurrent` is fine for me, but not Swing (or Ant).

FTR: we're using AntLR for the Ceylon programming language compiler.

**Comment by ericvergnaud** [comment]
Hi,
removing the Swing dependency will NOT reduce the size of the runtime jar.
Is there a use case where the current size is an issue?
Eric

**Comment by parrt** [comment]
The runtime is where all of the magic happens for this version of ANTLR some afraid that it will stay around 300K.  I'm not sure how this could be reduced much.

**Comment by sharwell** [comment]
Technically removing the visualizer components would reduce the size of the runtime jar, just not by as much as many would expect.

1. The org.abego.treelayout dependency is embedded in the runtime jar. This is 17.8KiB.
2. The org.antlr.v4.runtime.tree.gui package only includes the visualizer components, which would not be needed in a "swing-free" build. This is 29.1KiB.

**Comment by jponge** [comment]
Embedding a visualizer for debugging purposes in the runtime seems very wrong no matter the size delta. 

This should resolve as an optional dependency to make sure that if a project uses AntLR4, then the runtime dependency is purely for parsing purposes.

**Comment by melix** [comment]
I agree with @FroMage and @jponge. It's a logical requirement to separate the runtime from the compiler. There's *no* reason to include a debugger in the runtime. It's about reducing the size of the jar, but also about separating the runtime, the absolute minimum required to run the generated classes, from what is required to compile a grammar. And if you want another example of problems it can cause, think of Android: the Swing classes are not available, so as soon as you dex things, you have to include rules to exclude classes that depend on Swing.

**Comment by glaforge** [comment]
Agreed too with what's been said by @FroMage, @jponge and @melix.
Beside Android, there's also another environment that is unhappy with Swing classes, that's apps deployed on Google App Engine, which restricts the use of such classes.

The runtime should really be as minimum as possible.
Antlr v4 requires a runtime, but there are alternative tools that just generate code without requiring runtimes at all.

**Comment by parrt** [comment]
I see no reason why we can't move the tree viewer to the tool jar, which would also move the dependency of the tree layout jar to the tool jar. It still won't help you if 300K is a problem, though ;)

**Comment by parrt** [comment]
Hmm..we might have a teeny issue.

```
	public Future<JDialog> inspect(List<String> ruleNames) {
		TreeViewer viewer = new TreeViewer(ruleNames, this);
		return viewer.open();
	}
```

without removing this method from RuleContext, a key runtime object, I can't remove the dependency.  Isn't it possible to use a jar that refs swing w/o calling a func that will try to load swing?  Only issue would be dex conversion I guess.

I hate to break backward compatibility for 4.5.1, forcing a 4.6 maybe.

**Comment by jponge** [comment]
Perhaps you could introduce and abstraction interface to return a Future<Something>. The fact that the bytecode references a JDialog will trigger the loading of JDialog at runtime, so I would suggest depending on something more abstract.

**Comment by sharwell** [comment]
@jponge Any change to the existing signature would break binary compatibility.

**Comment by parrt** [comment]
Can one of you guys confirm that everything is cool without swing for you in the new runtime released yesterday?
