### ISSUE TITLE
maven plugin generates tokens files in wrong directory

### ISSUE THREAD

**Issue by james-q-arnold** [antlr/antlr4#599]
I have a paired lexer/grammar:  XyzLexer.g4, XyzParser.g4.
The source files are in a package hierarchy: com.abc.def.
The plugin documentation claims the .tokens files should go in the same directory as the generated java files---and this would make sense.  That is not the case.  The generated tree:

```
target/
`-- generated-sources
    `-- antlr4
        |-- com
        |   `-- kestrelei
        |       `-- psl
        |           `-- lib
        |               |-- PslLexer.java
        |               |-- PslParserBaseListener.java
        |               |-- PslParser.java
        |               `-- PslParserListener.java
        |-- PslLexer.tokens
        `-- PslParser.tokens
```

The compile step is failing at the moment.  I'm not sure the .tokens placement is an issue, but it might be.

**Comment by cam-m** [comment]
Hi there!

Apologies in advance if bumping an old issue is breaking protocol... but re this:

> Can you provide an example of how this is resulting in incorrect output?

I can't report any issue with the output either, however, Intellij's antlr4 plugin (v1.8.1) actually reports a syntax error for the 'tokenVocab' option if the referenced Lexer name has no corresponding .tokens file in the package directory.

![image](https://cloud.githubusercontent.com/assets/629645/15952983/293b73e4-2f09-11e6-8fc5-2869a13f9817.png)

The maven plugin generates tokens files in the root of generated-sources, causing this error to appear.

![image](https://cloud.githubusercontent.com/assets/629645/15953006/560df3ec-2f09-11e6-94df-223cbf5969f7.png)

Copying tokens files to the package directory (or configuring the antlr plugin's output directory correctly) resolves this error.

IMO it would be preferable that the **mvn antlr plugin** and the **intellij antlr plugin** each generate tokens files in a consistent location. It would also be good to remove the antlr4 plugin error if it is in fact spurious as @sharwell implies above.

Thanks!

Cam
