### ISSUE TITLE
Making ANTLR4 runtime OSGi-ready

### ISSUE THREAD

**Issue by deklanowski** [antlr/antlr4#685]
Hi Guys,
I would like to propose adding OSGi metadata to the antlr4 runtime jar, I have achieved this locally with a relatively simple change (addition of maven-bundle-plugin config to project) and I can use antlr4 in an OSGi runtime, however there are two things that would make this really seamless:

1. abego treelayout is also not OSGi-ready so I resorted to embeddeding this jar file in the ANTLR4 bundle (jar)
2. antlr4 has a split package, org.antlr.v4.runtime.misc which have non-overlapping classes in antl4-runtime and antlr4-annotations

Point 1. can be solved by making abego treelayou OSGi ready - simple enough as it has a simple dependency tree.
 
Point 2. is a bit trickier - can be solved (this is how I did it) by merging the split packages into one OSGi jar, but there are better ways.

The ideal scenario would be to change the namespace for antlr4 annotations e.g.,
org.antlr.v4.annotations. In this way the annotations artifact can be an independent OSGi bundle with a non-overlapping namespace. From a pure modularity point of view this is also desirable. These few steps would make it completely seamless whether used in an OSGi or non-osgi environment instead of having one set of jars for pure java development and another for OSGi containers. I am aware that OSGi-readyness may not be a high priority but I am prepared to help with this. 
I am a huge antlr fan and have been using it (and its predecessor PCCTs by the way) for over 15 years :)
Cheers,
Declan

**Comment by parrt** [comment]
@deklanowski Hiya. Can you tell me specifically what metadata you need added? it is easy for me to add and I'd like to do this before we go final on 4.5.
