### ISSUE TITLE
sets referencing rules don't seem to work in the lexer.

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#70]
```
fragment NLCHAR : [\n\r];
String : '"' ~('"' | NLCHAR)* '"';
```

**Comment by mike-lischke** [comment]
Old issue, but I'm still bitten by that. I'd rather prefer this to be really solved. It's actually a regression, considering that this worked in ANTLR3. So it should get a higher prio to solve IMO.

**Comment by parrt** [comment]
well, antlr3->antlr4 was a complete rewrite so less a regression and more a smaller feature set ;)

**Comment by mike-lischke** [comment]
:-) probably depends on the view angle...

**Comment by arrdem** [comment]
Hey @parrt, this is a feature which would drastically simplify some of the grammars I'm interested in. Understood that it's a feature request not a bug from this ticket, but what would be required to support fragments as set members in antlr4? I'd be happy to sink some evenings into making this happen if you're able to give some direction on where to start.

Thanks!

**Comment by parrt** [comment]
Hi @arrdem I'm afraid I'm mostly in maintenance mode; not sure what's involved but I'd be nervous about altering anything related to the ALL(*) algorithm at this point.

**Comment by Enerccio** [comment]
at least iwth 4.5 this is still not fixed?
