### ISSUE TITLE
ParserRuleContext: "stop" token may be before "start" token

### ISSUE THREAD

**Issue by michaelpj** [antlr/antlr4#742]
If we hit a prediction error in a rule, then the resulting context may have a `start` token which is the first token that would have been consumed if the rule had succeeded, but a `stop` token which is the _preceding_ token.

This makes sense in the context of the implementation. However, from a user's point of view, I would have expected the `stop` token to always be the same or later than the `start` token - in this case probably the same.

It would probably also be fine to just update the documentation to note that `stop` may not always be a successor of `start`.

**Comment by parrt** [comment]
Fixed by https://github.com/michaelpj/antlr4/commit/6acb8e7e462d70faa465012135330d57b7d0508c.
