### ISSUE TITLE
NullPointerException in runtime: Parser.notifyErrorListeners()

### ISSUE THREAD

**Issue by fmela** [antlr/antlr4#746]
```
java.lang.NullPointerException: null
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:557) ~[antlr4-runtime-4.3.jar:4.3]
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:157) ~[antlr4-runtime-4.3.jar:4.3]
```

Looks to be happening [here](https://github.com/antlr/antlr4/blob/master/runtime/Java/src/org/antlr/v4/runtime/Parser.java#L557).

**Comment by parrt** [comment]
Hi. Not sure how offendingToken could ever be null. Does this happen for you still in 4.5? I'm closing as it's likely something altering normal error mechanism.

**Comment by fmela** [comment]
I no longer have access to the source code that triggered this, but maybe @benmccann could test with 4.5 and comment.

**Comment by parrt** [comment]
ok, thanks.

**Comment by obfischer** [comment]
I am using ANTLR 4.6 and have the same problem. You can reproduce if you try the following

    > git clone git@github.com:buschmais/jqa-json-plugin.git
    > git checkout antlr-fails-with-npe
    > mvn clean install -P IT

To cope the problem I currently have to  examine the strack trace and to suppress the NPE caused by ANTLR.

**Comment by parrt** [comment]
thanks @obfischer !

**Comment by obfischer** [comment]
Hi @parrt, is there any progress on this issue?

**Comment by parrt** [comment]
Nope. :(  Working on ST4 release.

**Comment by obfischer** [comment]
I understand. May be the label `status:not-fixing` could be removed. Indeed I am not sure of its meaning.

**Comment by parrt** [comment]
Well, i removed though I'm not sure if we can actually change anything per @sharwell above.  can you paste the small example that causes issue?

**Comment by obfischer** [comment]
I will do it on the weekend. Today is time to go to bed...
