### ISSUE TITLE
Use JFrame for TreeViewer instead of JDialog 

### ISSUE THREAD

**Issue by yourfrienddan** [antlr/antlr4#771]
I am finding that the TreeViewer open method that displays a JDialog does not work well under Ubuntu, although similar issues may exists for other operating systems.  The dialog opens and displays, but if it is minimized it disappears and I cannot get it back.   From a Swing programming perspective displaying dialogs without being associated with a frame does not make sense.   I rewrote the code to use a JFrame and now the frame appears in the launcher side bar.  I think using  a JFrame makes more sense for the TreeViewer class.

**Comment by tbodt** [comment]
I would fix and PR this myself, but I can't for the life of me figure out the insane building system. Why not just use Maven?

**Comment by parrt** [comment]
Hi. @tbodt The build system is a long story ;) @yourfrienddan: can you send the code to me?

**Comment by yourfrienddan** [comment]
Here it is. All I did really is use JFrame instead of JDialog.

**Comment by parrt** [comment]
ah. ok.

**Comment by tbodt** [comment]
@parrt seriously, what happened with the build system?

**Comment by parrt** [comment]
in summary, i hate mvn, ant.  Neither is sophisticated enough to build antlr anyway in any reasonable fashion. It is gotten extremely complicated and an imperative system is superior, though of course the system I have a place is still being smoothed out.

**Comment by sharwell** [comment]
@parrt I believe this was fixed for 4.6?

**Comment by parrt** [comment]
yup. closing.
