### ISSUE TITLE
Add way to notify error listeners about semantic errors with no reasonable location

### ISSUE THREAD

**Issue by EpsilonPrime** [antlr/antlr4#782]
After done visiting the parse tree during the semantic phase one might want to perform other error checks (like emit an error if a particular element is not present).  In that case there is no reasonable location for the error (except perhaps end of file).  I would like to show a better error message in the error listener (showing EOF or ERROR instead of the location), but there is no way to get a message to the error listener that does not include location information.

A workaround could be to directly tell the error listener that EOF has been reached and to ignore the location information when printing errors after that.

**Comment by parrt** [comment]
The error listener is for the parser only.
