### ISSUE TITLE
Make it simpler to find out how to build antlr4

### ISSUE THREAD

**Issue by krieger-od** [antlr/antlr4#793]
README.md directs us to "Getting started" article for installation info. In that article we see nothing relevant to building it and installing it into the system. Then, reading the script "bild.py" (BTW what is "bild"?) we see

```
This script uses my experimental build tool http://www.bildtool.org

In order to build the complete ANTLR4 product with Java, CSharp, Python 2/3, and JavaScript
targets, do the following from a UNIX command line.  Windows build using this script
is not yet supported. Please use the mvn build or ant build.

You will also need python 2.7, python 3.4, node.js and mono (on Mac/Linux)

!!!You might need to set path values in test_properties dictionary below to ensure non Java targets tests run.!!!

mkdir -p /usr/local/antlr # somewhere appropriate where you want to install stuff
cd /usr/local/antlr
git clone git@github.com:antlr/antlr4.git
git clone git@github.com:antlr/antlr4-python3.git
git clone git@github.com:antlr/antlr4-python2.git
git clone git@github.com:antlr/antlr4-csharp.git
git clone git@github.com:antlr/antlr4-javascript.git
cd antlr4
./bild.py tests
```

I think it is not the best place for documentation. Also it would be much better to have these lines of code in actual code (automatically called when needed), and not in comment.

I am just a Gentoo-addicted person trying to build antlr as a dependency for linphone's dependency "belle-sip". Portage way currently doesn't work for that unfortunately.

**Comment by parrt** [comment]
I added information to the README.md.
