### ISSUE TITLE
C++ target

### ISSUE THREAD

**Issue by javalama** [antlr/antlr4#808]
With the low hanging fruit like Javascript and C# targets done, let's get the really useful one done: A C++ target for Antlr4.

There's been a few attempts, the current one embarking on a dead-end approach using machine translation of the Java source base.

The target should IMO generate a C++14 parser/lexer with lambda callbacks for listener actions. For Unicode support, an ICU dependency is reasonable.

Having an issue is a start.

**Comment by parrt** [comment]
Hi. We are aware that a C++ target is desirable. I don't think we need an open issue.
