### ISSUE TITLE
Two Windows issues

### ISSUE THREAD

**Issue by ffcelo** [antlr/antlr4#813]
I think I found two interesting issues when using ANTLR 4.5 on Windows.
<ul><li>
1) <b>UTF-8 support for tree dialog box:</b> when I use portuguese keywords with letters like 'ç', 'á' and 'ã', they aren't showed correctly. It can be a Windows CP-1252 encoding issue or something else.
</li><li>
2) <b>Confusion about '\' and '/' (Windows uses the former) :</b> I named a package 'test' at grammar's @header, used it after -o Tool option, used it in TestRig first argument, like 'test\GrammarTest', and I got: "... NoClassDefFoundError: test\Grammar (wrong name: test/GrammarTestLexer)"
</li></ul>

**Comment by parrt** [comment]
Thanks we'll check it out.

**Comment by parrt** [comment]
Hi. it's GrammarName not path to grammar file ;)
```
java org.antlr.v4.runtime.misc.TestRig GrammarName startRuleName
```

also I'd suggest `-encoding encodingname` on TestRig for all non-UTF8/ascii.
