### ISSUE TITLE
Request for constructor ANTLRInputStream(File)

### ISSUE THREAD

**Issue by Reissner** [antlr/antlr4#820]
Just a little thing: 
as FileInputStream reader has a constructor with parameter File, so should have ANTLRFileStream 
which allows to turn 
            FileInputStream reader = new FileInputStream(mFile);
            ANTLRInputStream input = new ANTLRInputStream(reader);
into 
ANTLRFileStream input = new ANTLRFileStream(mFile);

**Comment by parrt** [comment]
Hi. A decent idea but not worth me making unit test, updating doc for. thanks...
