### ISSUE TITLE
wrong location on import error message reference to undefined rule

### ISSUE THREAD

**Issue by marcpawl** [antlr/antlr4#823]
Error message should point to location where rule was referenced in imported file, in this case Nested.g4

[mpawlowsky@vmott-mpawlowsky-seas error]$ ant
Buildfile: /home/mpawlowsky/error/build.xml

generate:
     [java] error(56): error.g4:4:8: reference to undefined rule: c

BUILD FAILED
/home/mpawlowsky/error/build.xml:3: Java returned: 1

Total time: 0 seconds
[mpawlowsky@vmott-mpawlowsky-seas error]$ cat error.g4 
grammar Error;
import Nested;

[mpawlowsky@vmott-mpawlowsky-seas error]$ cat Nested.g4 
grammar Nested;

a:
  'a' | c;

 <project name="error" default="generate">
  <target name="generate" >
                <java classname="org.antlr.v4.Tool" fork="false" failonerror="true">
                        <arg value="-o" />
                        <arg value="java" />
                        <arg value="-package" />
                        <arg value="com.example" />
                        <arg value="-visitor" />
                        <arg value="-Werror" />
                        <arg value="error.g4" />
                        <classpath>
                                <pathelement location="antlr-4.4-complete.jar"/>
                        </classpath>
                </java>
</target>
</project>

**Comment by parrt** [comment]
Adding testErrorInImportedGetsRightFilename() test.
