### ISSUE TITLE
parser of antlr with brackets and labels

### ISSUE THREAD

**Issue by Reissner** [antlr/antlr4#824]
I had a rule 

```
atomicExpression : (UINT | FLOAT | COMPLEX | END | string);
```

which I endowed with labels which yields 

```
atomicExpression : 
(
      UINT    # Integer 
    | FLOAT   # Real
    | COMPLEX # Complex
    | END     # EndL
    | string  # StringL
);
```

but this leads to an error message 

> syntax error: extraneous input ')' expecting SEMI while matching a rule

But then 

```
atomicExpression : 
      UINT    # Integer 
    | FLOAT   # Real
    | COMPLEX # Complex
    | END     # EndL
    | string  # StringL
;
```

worked.

**Comment by sharwell** [comment]
Labels are only allowed on outermost alternatives, which means they can never appear within parentheses. I'm leaving this issue open, however, because the error message certainly needs to be improved for this case. :smile:

**Comment by Reissner** [comment]
Ah, ok. Yes thank you for leaving the issue open.

I read the passage in Toms book on antlr4 on labels (page 117,118) and
this restriction is not described.
what do you think, dropping this restriction: would it be a reasonable
feature request.

**Comment by sharwell** [comment]
It probably wouldn't make sense to allow labels at other points in a rule. However, you can get basically the same behavior by simply creating new rules:

```
// before
foo : (x y #label);

// after
foo : (label);
label : x y;
```

**Comment by parrt** [comment]
The error first gives:

```
error(50): T.g:5:14: syntax error: missing RPAREN at '#' while looking for rule element
```

which is probably close enough. I'm gonna close ;)
