### ISSUE TITLE
labels make listener methods disappear. 

### ISSUE THREAD

**Issue by Reissner** [antlr/antlr4#825]
This bug may be a feature but i do not think so 
I replaced 

```
atomicExpression : (UINT | FLOAT | COMPLEX | END | string)
```

by 

```
atomicExpression : 
      UINT    # Integer 
    | FLOAT   # Real
    | COMPLEX # Complex
    | END     # EndL
    | string  # StringL
;
```

which makes exitAtomicExpression disappear 
being *replaced* by exitReal and others. 
What I would have expected is, that exitReal appears 
*in addition to* exitAtomicExpression 
because there is some reason that UINT and REAL are summarized in a rule 
which may result in common actions 
handled best in common enter/exit methods of the listener. 

All in all I think, labeled 'subrules' shall be treated like rules. 
That way, the user is not forced to label either all or none alternatives.

**Comment by parrt** [comment]
Sometimes I've wanted "exitAtomicExpression" as well but I think I'll leave as is. You could [shudder] use the visit all rules thing and look for that one but... ;)
