### ISSUE TITLE
Separate lexer/parser grammar files seem to have their token numbers non-synchronized ( C# )

### ISSUE THREAD

**Issue by dhmhgre** [antlr/antlr4#827]
Hi 

I wrote the following small grammar for the matrices in MATLAB using a separate parser and lexer grammar file

```antlr
// Parser grammar file  MatricesParserGrammar.g4
grammar MatricesParserGrammar;

options {tokenVocab = MatricesLexerGrammar;}

matrixdefs: (matrixdef SEMICOLON)* ;
matrixdef : OPENBRACKET matrixrows CLOSEBRACKET ;
matrixrows : matrixrow (rowbreak matrixrow)*;
matrixrow : SPACES? NUMBER ( columnbreak NUMBER )*;
rowbreak :  (SPACES|EOL|SEMICOLON_R)+;
columnbreak : SPACES | (SPACES? COMMA SPACES?);
```

```antlr
// Lexer grammar file  MatricesLexerGrammar.g4 
lexer grammar MatricesLexerGrammar;
OPENBRACKET : '['		->mode(MATRIX);
SPACE	: [ \t\r\n]+	->skip;
SEMICOLON : ';';


mode MATRIX;
NUMBER : [0-9]+;
SEMICOLON_R : ';';
COMMA : ',';
SPACES : [ \t]+;
EOL	   : '\r'?'\n';
CLOSEBRACKET: ']'		->mode(DEFAULT_MODE);
```

I compiled the grammar using Visual Studio 2013 with C# output. The problem arises if 
I write the grammar like in the following where i substitute token COMMA with the 
corresponding character ','. 
I get the message : line 1:9 no viable alternative at input ' 1 ,'
					line 1:9 extraneous input ',' expecting {NUMBER, SEMICOLON_R, SPACES, EOL}
 
```
// Parser grammar file  MatricesParserGrammar.g4
grammar MatricesParserGrammar;

options {tokenVocab = MatricesLexerGrammar;}

 matrixdefs: (matrixdef SEMICOLON)* ;
 matrixdef : '[' matrixrows ']' ;
 matrixrows : matrixrow (rowbreak matrixrow)*;
 matrixrow : SPACES? NUMBER ( columnbreak NUMBER )*;
 rowbreak :  (SPACES|EOL|';')+;
 columnbreak : SPACES | (SPACES? ',' SPACES?);
 ```

 I also quote the skeleton program and the test file
 
```csharp
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Antlr4.Runtime;
using Antlr4.Runtime.Tree;

namespace MATLAB_Matrices_Grammar1 {
    class Program {
        static void Main(string[] args) {
            IParseTree tree;
            StreamReader astream = new StreamReader(args[0]);
            AntlrInputStream Astream = new AntlrInputStream(astream.ReadToEnd());
            MatricesLexerGrammar lexer = new MatricesLexerGrammar(Astream);
            CommonTokenStream tokens = new CommonTokenStream(lexer);
            MatricesParserGrammarParser parser = new MatricesParserGrammarParser(tokens);
            tree = parser.matrixdefs();
            Console.WriteLine(tree.ToStringTree());
        }
    }
}
```

```
// Test file
[1 1 1 1 , 1 1 1 1];
[1 1
	;
		1 1];
```

 Is this a bug or am I doing something wrong?

**Comment by sharwell** [comment]
Your parser grammar should start with `parser grammar MatricesParserGrammar;`. In the current form you are generating two lexers which are not compatible with each other. The first is called `MatricesLexerGrammar`, and it can only be used by itself. The second is called `MatricesParserGrammarLexer` and it is the only one you can use with `MatricesParserGrammarParser`. If you change the parser to be a `parser grammar`, then you'll have only one lexer and one parser, and they will work together.

**Comment by dhmhgre** [comment]
It worked!!! Thank you

**Comment by davidljung** [comment]
I'm also new and struggling to figure out how to split my grammar into two files.  I have "lexer grammer MyLexer" in one file and "parser grammar MyParser" in another, then I pass the two files to antlr4 command (alias), but it complains about the lexer token identifiers being implicit definitions (presumably because it can't find them).  It isn't clear how to 'combine' the files without creating a combined grammar? (so that channels can be used).  Improving the docs and/or error message would help greatly.
