### ISSUE TITLE
Recognizer.removeErrorListeners() in Recognizer.py

### ISSUE THREAD

**Issue by RedTailedHawk** [antlr/antlr4#829]
There is no Recognizer.removeErrorListeners() in Recognizer.py, so I added the following to my local copy:

    def removeErrorListeners(self):
        self._listeners = []

I obtained the source for ANTLR 4.5 runtime for Python 2.7.6 here:
    https://pypi.python.org/pypi/antlr4-python2-runtime/

Can I contribute and update the source?

**Comment by ericvergnaud** [comment]
Certainly, but you need to sign the contributors file, in the antlr4 section.
Please also provide similar enhancement for Python3.

**Comment by RedTailedHawk** [comment]
I just created a pull request in https://github.com/antlr/antlr4-python2.  Let me know if I did this right (I'm relatively new to GitHub).  Also, I didn't quite understand where the contributors file was.  Please clarify, and I can add the change to Python3 as well.  Thanks!

**Comment by ericvergnaud** [comment]
It's here:
https://github.com/antlr/antlr4/blob/master/contributors.txt
Eric

**Comment by RedTailedHawk** [comment]
I just signed the contributors file and issued a pull request for that, and updated the Python3 code (and issued pull request for that as well).

**Comment by sharwell** [comment]
Closing this since it's not the Python repository (and @RedTailedHawk has now submitted the work to that repository).
