### ISSUE TITLE
Rewriting input stream not supported in ANTLR Python2 runtime?

### ISSUE THREAD

**Issue by RedTailedHawk** [antlr/antlr4#832]
Is rewriting the input stream not supported in the ANTLR Python2 runtime?  The ANTLR book discusses this technique in the Rewriting the Input Stream section, but I cannot find the TokenStreamRewriter class in the ANTLR Python 2 runtime.

I'm replacing a Python AST NodeTransformer with ANTLR, but I don't want to have to implement every listener method just to echo the text back out.  TokenStreamRewriter is exactly what I need to transform part of the stream, but I can't find seem to find it.

Thanks for any help.

**Comment by ericvergnaud** [comment]
Mmm,
no it's not available, but I see no reason for it not to work.
It just needs someone to write the corresponding code.

**Comment by RedTailedHawk** [comment]
OK, I'll take a look at the Java code and take a crack at porting it to Python.

**Comment by ericvergnaud** [comment]
Cool

**Comment by RedTailedHawk** [comment]
BTW, I was able to achieve something similar to the rewrite functionality by implementing a visitor like this:

class RewriteVisitor(myVisitor):
    def aggregateResult(self, aggregate, nextResult):
        return (aggregate + " " if aggregate is not None else "") + nextResult

    def visitTerminal(self, ctx):
        return ctx.getText()
        
    def visitSomeRule(self, ctx):
        value = "null_as_zero(%s)" % (ctx.getText())
        return value

What this does is wrap the result of the text of SomeRule in a null_as_zero() function call, and return the transformed expression when the visitor exits.

    tree = parser.my_expression()
    visitor = RewriteVisitor()
    transformed_expression = visitor.visit(tree)

For example, if I have an expression like this:

(a.sales + b.sales) / (a.qty + b.qty)

The transformed expression after visiting is this:

(null_as_zero(a.sales) + null_as_zero(b.sales)) / (null_as_zero(a.qty) + null_as_zero(b.qty))

I think I'm cheating though, because I'm not visiting in visitSomeRule, but instead just using the getText() value.  Seems to be working for my application, so far.

Anyway, I have my workaround for now, but would be good to get the TokenStreamRewriter class ported from Java to Python.  I'll keep it on my mental to-do list.

**Comment by ericvergnaud** [comment]
your use case does not require changing the sequence of tokens, hence why you can come up with a concise and elegant solution.

**Comment by sharwell** [comment]
@RedTailedHawk I believe you meant to file this issue here: https://github.com/antlr/antlr4-python2

This issue tracker is for the Java runtime and the ANTLR 4 Tool.

**Comment by RedTailedHawk** [comment]
I may have some bandwidth to port the Java code for TokenStreamRewriter (and supporting classes) over to Python, but I wanted to check if any work has already been done on this.

Thanks.
-Larry

**Comment by parrt** [comment]
as far as I know, no one is working on this.
