### ISSUE TITLE
Typo in ANTLR Book

### ISSUE THREAD

**Issue by RedTailedHawk** [antlr/antlr4#833]
Section 4.5 Cool Lexical Features

Last paragraph on page 68:

>>Each line of that output represents a token and contains the token index, **the start and stop character**, the token text, the token type, and finally the line and character position within the line.

Should probably be "the start and stop character **position**".

**Comment by parrt** [comment]
can you check here and add? https://pragprog.com/titles/tpantlr2/errata

**Comment by RedTailedHawk** [comment]
Yes, I just added at the link you provided.
