### ISSUE TITLE
Why does "grun XML tokens -tokens t.xml" work for XMLLexer.g4?

### ISSUE THREAD

**Issue by RedTailedHawk** [antlr/antlr4#834]
The grammar file is XML**Lexer**.g4, so why would the following example from the ANTLR book work?

    grun XML tokens -tokens t.xml

This works (as expected):

    grun XMLLexer tokens -tokens t.xml

This does not work (as expected):

    grun XMLLex tokens -tokens t.xml

**Comment by parrt** [comment]
Hi. These are really questions and not bugs for the tool. Note the help message from the tool says: Use startRuleName='tokens' if GrammarName is a lexer grammar. That would indicate that it is expected behavior.

**Comment by RedTailedHawk** [comment]
My point is that the grammar name was specified as "XML" on the command line and that worked, but the grammar file is XMLLexer.g4.  The code is automatically adding the suffix "Lexer", so that's why the shortened version worked.

~~~
	public TestRig(String[] args) throws Exception {

	public void process() throws Exception {
//		System.out.println("exec "+grammarName+"."+startRuleName);
		String lexerName = grammarName+"Lexer";
		ClassLoader cl = Thread.currentThread().getContextClassLoader();
		Class<? extends Lexer> lexerClass = null;
		try {
			lexerClass = cl.loadClass(lexerName).asSubclass(Lexer.class);
		}
		catch (java.lang.ClassNotFoundException cnfe) {
			// might be pure lexer grammar; no Lexer suffix then
			lexerName = grammarName;
			try {
				lexerClass = cl.loadClass(lexerName).asSubclass(Lexer.class);
			}

~~~

I understand now, but would be helpful if the tool (and the book) indicated that you can optionally use the shortened lexer grammar name.

**Comment by parrt** [comment]
The grammar name is not necessarily the filename. there is a relationship between T and TParser and TLexer.
