### ISSUE TITLE
inconsistent input handling, lexer vs parser rule

### ISSUE THREAD

**Issue by james-q-arnold** [antlr/antlr4#835]
This issue involves an inconsistency between how much input is consumed and what errors are reported, depending on a variation in a parser rule.  Sorry I don't have a self-contained example, but here are the relevant excerpts from the grammar.

Lexer:

    MINUS: '-' ;
    IDENTIFIER: [A-Za-z][A-Za-z0-9_]*

Parser (variant 1):

    capture_type: IDENTIFIER

Parser (variant 2):

    capture_type: IDENTIFIER ( MINUS IDENTIFIER )*

The test instantiates a parser, provides some input, and parses a capture_type.  Note the period in the input, so only the "ident" portion of the input should be recognized.

    parser = getParser("ident.ifier");
    tree = parser.capture_type();

The two variants "should" have the same behavior, it seems to me.  But the resulting trees differ.
Variant 1:

    tree.getNumberOfSyntaxErrors() => 0
    tree.toStringTree(parser) => "(capture_type ident)

Variant 2:

    tree.getNumberOfSyntaxErrors() => 1
    tree.toStringTree(parser) => (capture_type ident . ifier)

with error output:

    "line 1:0 mismatched input '.' expecting {<EOF>, MINUS}

Here's the inconsistency.  Both runs get exactly the same input.  They both could read "ident" and stop there, getting a valid capture_type.  Or they both could try going to the end of the input, seeing the period as invalid.  Clearly variant 2 must examine the period token to know whether the capture_type is complete, but it could simply declare completion if it fails to see a MINUS.  Likewise, variant 1 can declare completion after seeing the IDENTIFIER, but it could see if the input is complete and declare failure if it fails to see EOF.  Seems like the EOF handling should be the same in either case.

Minor issue.  The toStringTree() output for variant 2 includes the invalid tokens after "ident".  When exercised under grun, these tokens are highlighted in red under the -gui option.  Unclear why they are included at all in the toStringTree output.  As I said, though, this point is a quibble.

**Comment by parrt** [comment]
hi.  The issue here is that you asked it to make a decision after the first identifier and it identified a true syntax error where is the first one does not have a syntax error no matter how far we look ahead because it's identifier followed by in the file. the tree is different because of the recovery, which tries to consume until it sees something that can follow a capture_type. Because you asked it to make a decision it had to test the input. When it tests input and finds a syntax error it must report it.  Does this capture the situation?

**Comment by james-q-arnold** [comment]
I wanted to write a test for a particular grammar rule: capture_type.  I fed exactly the same input to the parser with both variants.  Either the resulting parser should read all the input, or it should not.  If it reads all the input, both variants should find syntax errors.  If the parser can read a portion of the input, both should find a valid match for the rule.

In variant 1, it read the valid portion of the input and ignored the rest.  In variant 2, it could have found exactly the same valid portion, but it did not.  As I understand the rules, one must match explicitly for EOF to say all the input must be consumed.  The capture_type rule does not require EOF, so I think it should be able to match a piece of the input and ignore any trailing tokens.  Thus I expected variant 2 to match "ident" and ignore the ".ifier", exactly the same behavior as variant 1.

Back to your point.  Yes, variant 2 forces the parser to examine more input.  But the leading "ident" is valid, so why does this particular rule give an error?

**Comment by jimidle** [comment]
If you added an EOF to the rule for variant 1, what do you get? Your
variant 1 rule can just stop after identifier so it does. But your variant
2 must look to see if there is MINUS and that will throw the error. Add an
EOF should force variant1 to do the same. If you are trying to test a rule
in the grammar where you cannot add the EOF normally, then I think you will
have to create a test rule that references variant1 then follows it with
EOF.

Jim

**Comment by james-q-arnold** [comment]
To answer jimidle, yes, adding explicit EOF to the variant 1 changes the behavior, as one would expect.  But that's not really the point.  The rule in the actual grammar cannot require EOF.

**Comment by jimidle** [comment]
Which is what I said. :)

**Comment by parrt** [comment]
Hi James, well, The unsatisfying answer is that that is just how the parser works. I don't agree with your statement "Either the resulting parser should read all the input, or it should not." You have explicitly told  the parser to examine the input and it found a syntax error. Under what conditions would you have the parser not report syntax errors?
