### ISSUE TITLE
[antlr4-csharp] global alias conflicts with .NET 4.0

### ISSUE THREAD

**Issue by nippur72** [antlr/antlr4#837]
If I try to use the C# runtime (`Antlr4.Runtime.dll`) in a .NET 4.0 Visual Studio 2013 project, I get lot of global alias conflicts (`ExtensionAttribute`, `Tuple`, `ConcurrentDictionary`, etc.).

The problem occurs only with .NET 4.0, which unfortunately is the version that I need. 

Actually I fixed by forking `antlr4-csharp`, deleting the conflicting files from the `\Sharpen\Compat\` directory, changing the target to .NET 4.0 and building my own custom .dll.

**Comment by ericvergnaud** [comment]
mmm...
I guess those conflicts only occurred in the sharpen.compat namespace, because those classes are all in that namespace so they can only occur through implicit import.
Can you confirm?

**Comment by nippur72** [comment]
Of the conflicting files, `ConcurrentDictionary`, `HashSet` and `Tuple` are from the `Sharpen` namespace.

But these are not:

* `Enumerable` from namespace `System.Linq` 
* `ExtensionAttribute` from namespace `System.Runtime.CompilerServices`

**Comment by ericvergnaud** [comment]
Hi,
I'm closing this because it does not fit with this sub-project.
Please reopen it in the antlr-csharp sub-project.

**Comment by nippur72** [comment]
I tried that before, but in the repo [antlr4-csharp](https://github.com/antlr/antlr4-csharp) the "issues" are disabled.

**Comment by ericvergnaud** [comment]
It's enabled now, sorry for that.
