### ISSUE TITLE
Parse error not thrown for invalid input

### ISSUE THREAD

**Issue by RedTailedHawk** [antlr/antlr4#839]
I'm not receiving a parse error when my input is invalid.  I can reproduce behavior with modified Hello.g4 from the book.

Change this:
````
    r  : 'hello' ID ;
````

To this:
````
    r : greeting (';' greeting)* ';'?;
    greeting : 'hello' ID;
````

I do get an error if the first input line does not start with *hello*:
````
joe
````

*grun Hello r -tree* sends the following error to the console:
````
    line 1:0 missing 'hello' at 'joe'
````
But I do not get an error for this next input:
````
hello joe;
bob
````
Instead, the following syntax tree is getting printed:
````
(r (greeting hello joe) ;)
````
It's showing the syntax tree for the first greeting, but it's not providing any information that the second greeting was invalid (because it didn't start with *hello*).

I dug into the ANTLR4 Java code and ParserATNSimulator.execATN() enters the *if (D == ERROR)* block, but it does not *throw e*.  Instead, it returns *alt* as 2.

````
			if (D == ERROR) {
				// if any configs in previous dipped into outer context, that
				// means that input up to t actually finished entry rule
				// at least for SLL decision. Full LL doesn't dip into outer
				// so don't need special case.
				// We will get an error no matter what so delay until after
				// decision; better error message. Also, no reachable target
				// ATN states in SLL implies LL will also get nowhere.
				// If conflict in states that dip out, choose min since we
				// will get error no matter what.
				NoViableAltException e = noViableAlt(input, outerContext, previousD.configs, startIndex);
				input.seek(startIndex);
				int alt = getSynValidOrSemInvalidAltThatFinishedDecisionEntryRule(previousD.configs, outerContext);
				if ( alt!=ATN.INVALID_ALT_NUMBER ) {
					return alt;
				}
				throw e;
````
When the code returns back into HelloParser.r(), it doesn't go into the *while* loop because *_alt* is 2, and the code then exits the rule without any info about the invalid second greeting.

````
	public final RContext r() throws RecognitionException {
        ...
			_alt = getInterpreter().adaptivePredict(_input,0,_ctx);
			while ( _alt!=2 && _alt!=org.antlr.v4.runtime.atn.ATN.INVALID_ALT_NUMBER ) {
        ...
````

Is this behavior by design?  Shouldn't ANTLR complain about the second invalid greeting?  Or is there a bug in my grammar that's causing the second invalid greeting to get silently ignored?

Thanks for any help.
-Larry

**Comment by sharwell** [comment]
Can you please include a complete copy of the grammar you are using? :smile:

**Comment by sharwell** [comment]
@RedTailedHawk The issue here is your entry rule `r` does not end with and explicit `EOF`. As such, there is no requirement that all input be consumed. During your test run, the parser identifies a valid match to the `r` rule even though it is not the entire file. To require that the entire input be consumed, change `r` to the following:

```antlr
r : greeting (';' greeting)* ';'? EOF;
```

**Comment by RedTailedHawk** [comment]
**Thank you** for that explanation!!  Works great with the EOF token.  Now that I know what to look for, I'm reading the *Start Rules and EOF* section in the ANTLR book.  :-)

Much appreciated.
-Larry
