### ISSUE TITLE
"grun Hello r -gui" doesn't show up any dialog box and error

### ISSUE THREAD

**Issue by ngundu** [antlr/antlr4#844]
I have done git clone https://github.com/antlr/antlr4
And run python script "./bild all" to build the antlr-4.5-complete.jar file 
And followed the below steps and example everything worked fine but at last step “grun Hello r –gui” it doesn’t show up dialog and any error after providing the input to it and ctrl+d 

please guide me already wasted couple of days to resolve this.

UNIX
0. Install Java (version 1.6 or higher)
1. Download
?
$ cd /usr/local/lib
$ curl -O http://www.antlr.org/download/antlr-4.5-complete.jar
Or just download in browser from website:
    http://www.antlr.org/download.html
and put it somewhere rational like /usr/local/lib.
2. Add antlr-4.5-complete.jar to your CLASSPATH:
?
$ export CLASSPATH=".:/usr/local/lib/antlr-4.5-complete.jar:$CLASSPATH"
It's also a good idea to put this in your .bash_profile or whatever your startup script is.
3. Create aliases for the ANTLR Tool, and TestRig.
?
$ alias antlr4='java -Xmx500M -cp "/usr/local/lib/antlr-4.5-complete.jar:$CLASSPATH" org.antlr.v4.Tool'
$ alias grun='java org.antlr.v4.runtime.misc.TestRig'
Testing the installation
Either launch org.antlr.v4.Tool directly:
?
$ java org.antlr.v4.Tool
ANTLR Parser Generator Version 4.5
-o ___ specify output directory where all output is generated
-lib ___ specify location of .tokens files
...
or use -jar option on java:
?
$ java -jar /usr/local/lib/antlr-4.5-complete.jar
ANTLR Parser Generator Version 4.5
-o ___ specify output directory where all output is generated
-lib ___ specify location of .tokens files
...
A First Example
In a temporary directory, put the following grammar inside file Hello.g4:
Hello.g4
?
// Define a grammar called Hello
grammar Hello;
r  : 'hello' ID ;         // match keyword hello followed by an identifier
ID : [a-z]+ ;             // match lower-case identifiers
WS : [ \t\r\n]+ -> skip ; // skip spaces, tabs, newlines
Then run ANTLR the tool on it:
?
$ cd /tmp
$ antlr4 Hello.g4
$ javac Hello*.java
Now test it:
?
$ grun Hello r -tree
hello parrt
^D
(r hello parrt)
(That ^D means EOF on unix; it's ^Z in Windows.) The -tree option prints the parse tree in LISP notation.
It's nicer to look at parse trees visually.
?
$ grun Hello r -gui
hello parrt
^D
That pops up a dialog box showing that rule r matched keyword hello followed by identifier parrt.

**Comment by parrt** [comment]
which error? also, don't build it. just download it.

**Comment by ngundu** [comment]
the command `grun Hello r -gui` doesn't show up dialog box for abstract tree structure and no errors its shows up.

let me know how to compile, build and test after downloading the code from git repo.

**Comment by jimidle** [comment]
First try downloading the pre-built version - see if it makes any
difference.

Jim

**Comment by ngundu** [comment]
yeah Jim I first tried with downloaded antlr-4.5-complete.jar file where faced same issue no dialog and no errors it showsup. please guide me steps to work with antlr4.

**Comment by jimidle** [comment]
What operating system is this?

**Comment by ngundu** [comment]
using unix env.

**Comment by jimidle** [comment]
OK - so I presume that you are running this from an xterm, or equivalent.
Do you have your screen/display configured? If you try to start another GUI
from the command line, does that work OK? I seem to recall someone
mentioning on the list that the gui option does not always work because it
does not use the 'right' sort of panel - but first verify that if you start
something else from the same command line, that it pops up the gui
interface.

Jim

**Comment by ngundu** [comment]
appreciate your help kindness to help... okay I didn't configure screen/display for my Linux box. and also please list me steps to compile, build and test antlr code after checking out antlr code from git repo.

**Comment by parrt** [comment]
See https://github.com/antlr/antlr4/wiki/How-to-build-ANTLR-itself

**Comment by killwas** [comment]
Hello

I can reproduce the issue!

I've installed antlr using homebrew (package manager) on Mac OS X 10.11.6
I created the Hello example and compiled it.
When I execute grun without any options it results in: 
```
antlr$ grun
java org.antlr.v4.gui.TestRig GrammarName startRuleName
  [-tokens] [-tree] [-gui] [-ps file.ps] [-encoding encodingname]
  [-trace] [-diagnostics] [-SLL]
  [input-filename(s)]
Use startRuleName='tokens' if GrammarName is a lever grammar.
```
But trying it on the Hello example simply results in no output at all:
```
antlr$ grun Hello -r -tree

```

Any idea?

**Comment by parrt** [comment]
have you tried giving it some input? ;)

**Comment by killwas** [comment]
Gosh! I assumed it would show me the some tree of the grammar. It works (with input). :-) Thanks for the feedback!

**Comment by parrt** [comment]
a grammar has not tree w/o input. a grammar is the set of rules governing all possible parse trees.

**Comment by killwas** [comment]
This has good logic, but it did not occur to me after all kind of setup issues. I simply expected more of this kind. Now I can focus on using and learning antlr/grammar…

**Comment by schandrasekhar** [comment]
i am having a similar issue where the gui is not showing up. Here is what i am trying out
```
$ grun Hello r -gui --diagnostics
hello world

```

```
$ ls
Hello.g4			HelloBaseListener.java		HelloLexer.tokens		HelloParser.class
Hello.interp			HelloLexer.class		HelloListener.class		HelloParser.java
Hello.tokens			HelloLexer.interp		HelloListener.java
HelloBaseListener.class		HelloLexer.java			HelloParser$RContext.class
```

This is the version of OS i am using Mac OS 10.13.6

**Comment by killwas** [comment]
Hi Chandra 

did you see Terence response?
"a grammar has not tree w/o input. a grammar is the set of rules governing all possible parse trees."

You need to feed it actual input for parsing. 

Regards
Kurt

**Comment by schandrasekhar** [comment]
@killwas  thanks for your response, just looked at it more closely and realized that i did given it some input but did not add `Ctrl + D` after `new line`, its working now.

**Comment by HenriqueAurelio** [comment]
Can someone help me? I am with same issue but any of the solutions worked.

**Comment by cpusam** [comment]
Just for who uses Linux:
--you can be using a java headless version.
So, in Ubuntu, purge all the java and install the jre.

This happens because the grun not found any gui, and closes witout any error.
[It takes me 2h to find a solution!]
