### ISSUE TITLE
Error when using languages other than English

### ISSUE THREAD

**Issue by younesouhbi** [antlr/antlr4#845]
I was playing with the Hello.g4 from the Getting Started page here: https://theantlrguy.atlassian.net/wiki/display/ANTLR4/Getting+Started+with+ANTLR+v4

Changing 'Hello' with any Arabic word for example crashes it. It seems that Antlr does not support Unicode. Any ideas how to overcome this?

**Comment by parrt** [comment]
sure it does. use the -encoding option on grun etc…
Ter

**Comment by younesouhbi** [comment]
Awesome!

If I'm creating a custom computer language that is to be right to left (rtl), do I need to modify the parser to scan from rtl instead of the default one? or is there a more clever way? 

Since rules are entered ltr, I could just invert the order of tokens but I'm afraid this will mess up the alternatives since most rules would end up being "expression to keyword" instead of "keyword to expression"...

Thank you for your answers and for the great tool!

**Comment by parrt** [comment]
Just have make an inputstream that reads right to left.

**Comment by whitten** [comment]
On Sun, Mar 29, 2015 at 5:12 PM, Terence Parr <notifications@github.com>
wrote:

> Just have make an inputstream that reads right to left.
>
would that involve buffering each line until an end-of-line is reached, and
then feeding data into the lexer and parser?

Or is the presentation right to left but the stream is still read a
character at a time ?  How is a typical right-to-left file stored?

David

**Comment by parrt** [comment]
I think it could just do the same thing that left to right does, reading character by character and presenting it to the lexer as it asks for it.
