### ISSUE TITLE
os.getlogin() is not valid in windows

### ISSUE THREAD

**Issue by zssty2010** [antlr/antlr4#846]
I use `os.getenv('USERNAME')` in Windows 7 instead

**Comment by sharwell** [comment]
Hi @zssty2010,

Welcome to ANTLR 4 (It looks like this is your first time posting here). :tada: 

Based on a quick search it sounds like you were having a problem here (along with one other location in the file):
https://github.com/antlr/antlr4/blob/0ed80d90dadea0a8d953d37df33b64740372fe33/bild.py#L103

Can you confirm this?

**Comment by parrt** [comment]
Ah. unfortunately, I've not tried supporting Windows. Does it work other than that line?

**Comment by Shredder121** [comment]
There is only a problem on [this line](https://github.com/antlr/antlr4/blob/0ed80d90dadea0a8d953d37df33b64740372fe33/bild.py#L155) since you can not [rename a file when the target exists](https://docs.python.org/2/library/os.html#os.rename).
But that can also become a seperate issue.
