### ISSUE TITLE
Visual Studio 2013 Antlr4.3 import Issues

### ISSUE THREAD

**Issue by fireboy0526** [antlr/antlr4#847]
Hello there,

I've been using antlr with Visual Studio and so I've import the Antlr package from Nuget. However, with Antlr4.3, it is causing that error with importing lexer and parser files, which can be found on issue number 670 (here's the link: https://github.com/antlr/antlr4/issues/670) 

Is it possible to request an update of the Antlr version on Nuget please. 

Thank you very much.

**Comment by sharwell** [comment]
Hi @fireboy0526,

This is the wrong repository for the package you are referring to. Please post your issue here:
https://github.com/tunnelvisionlabs/antlr4cs
