### ISSUE TITLE
Issue with non-greedy rules

### ISSUE THREAD

**Issue by attodorov** [antlr/antlr4#848]
Hey,

I would like to have the following grammar (part of it):

expression 
	: 
        expression 'AND' expression
	| expression 'OR' expression
	| StringSequence
        ;

StringSequence
	: 
	StringCharacters
	;

fragment
StringCharacters
    :   StringCharacter+
    ;

fragment
StringCharacter
    :   ~["\\]
    |   EscapeSequence
    ;

It should match things like "a b c d f" (without the quotes), as well as things like "a AND b AND c".

The problem is that my rule StringSequence is greedy, and consumes the OR/AND as well. I've tried different approaches but couldn't get my grammar to work in the correct way. Is this possible with ANTLR4? Note that I don't want to put quotes around every string. Putting quotes works fine because the rule becomes non greedy, i.e.:

StringSequence
    :   '"' StringCharacters? '"'
    ;

Thanks

**Comment by parrt** [comment]
Hi. this is not a bug, it's a question. I'd ask stackoverflow. thanks.
