### ISSUE TITLE
bild.py tests fails

### ISSUE THREAD

**Issue by fgotwald** [antlr/antlr4#856]
bild.py line 248 should not have a hard-coded version.
Suggest changing it to:

java(classname="org.antlr.v4.test.rt.gen.Generator", cp="out/test:dist/antlr4-" + VERSION + "-complete.jar")

**Comment by parrt** [comment]
thanks.

**Comment by parrt** [comment]
Fixed in f645e175ad69cf53be87b90cdfe80a7d952b3249
