### ISSUE TITLE
Why does the antlr pom have a antlr4 and antlr3 runtime dependency?

### ISSUE THREAD

**Issue by bertramn** [antlr/antlr4#858]
Hi I was wondering why the main antlr pom.xml as a antlr4 **and** a antlr3 runtime dependency? Can the antlr3 dependency be excluded without side effects?

```xml
<dependency>
    <groupId>org.antlr</groupId>
    <artifactId>antlr4-runtime</artifactId>
    <version>4.5</version>
</dependency>
<dependency>
    <groupId>org.antlr</groupId>
    <artifactId>antlr-runtime</artifactId>
    <version>3.5.2</version>
    <scope>compile</scope>
</dependency>
```

**Comment by sharwell** [comment]
The main ANTLR pom is for the tool. It uses ANTLR 3 to parse the grammar files.

You could exclude the dependency, but then it would be rather pointless to reference that artifact at all. If you don't need to parse grammar files you can just use the runtime, which does not depend on ANTLR 3.
