### ISSUE TITLE
Lexer empty string warning could be disabled for popMode

### ISSUE THREAD

**Issue by ryaneberly** [antlr/antlr4#860]
" non-fragment lexer rule FreeOpExtender_Any can match the empty string"

I have a grammar that does a pushMode to check for a specific case, and failing to find that performs a popMode on an empty string.  Performing a popMode should be enough to avoid the recursion/loop issues that the warning is helping identify.   Should the warning be disabled in this case?

Here's the lex code FWIW:
mode FreeOpExtender;
FreeOpExtender_OPEN_PAREN: OPEN_PAREN -> popMode,type(OPEN_PAREN),pushMode(FreeOpExtender2);
//Deliberate match no char, pop out again
FreeOpExtender_Any: -> popMode,skip;

**Comment by parrt** [comment]
nonfragment empty strings are not meaningful to antlr I'm afraid.

**Comment by ryaneberly** [comment]
Yes.  I understand that I think.   

The lex code works well w/ Antlr 4.5.  At least as I expect and want it to. (the correctness of it is a discussion for email list I suppose).

I'm suggesting that this might be a valid use case.  Empty string,popMode and skip used *together* does not need a warning from the Antlr generator.

**Comment by sharwell** [comment]
@ryaneberly I think that makes sense. If we *only* remove it for the `popMode` case (and not the `mode` or `pushMode` cases), then I think it would work. There is no way to have an infinite empty token cycle of rules using `popMode` alone.

**Comment by ryaneberly** [comment]
Yes, agreed.
