### ISSUE TITLE
Java code left in generated python parser generators cause errors

### ISSUE THREAD

**Issue by g2graman** [antlr/antlr4#861]
@parrt @sharwell @ericvergnaud 
Re: [@49](https://github.com/antlr/antlr4-python2/issues/49)

Motivation: issue makes it impossible to use the generated parser(s) out-of-the-box.

**Comment by sharwell** [comment]
Hi @g2graman, 

Thank you for taking time to report this issue. The grammar you are working with was only designed for use with the Java runtime, so it is expected that it will not work as-is with any other target. If you do create a port of this grammar to work with another runtime, I'm sure we would be happy to include it. :smile:
