### ISSUE TITLE
Lexer matches first matching alternative instead of longest one

### ISSUE THREAD

**Issue by SomMeri** [antlr/antlr4#862]
Lexer matches first matching alternative instead of longest one. If both short and long alternative in `RULE:short | long ` rule match, lexer will choose short one.

*Example Grammar:* The `COMMENT` rule in `Bod6Bad` grammar has two alternatives, second one is longer:
````antlr
grammar Bod6Bad;

fragment COMMENT_CONTENT : '/*' .*? '*/';
COMMENT : COMMENT_CONTENT | (COMMENT_CONTENT WS_FRAGMENT); //second alternative is longer

IDENT : ('a'..'z' | 'A'..'Z')+;

fragment WS_FRAGMENT : (' '|'\t'|'\f')+ ;
WS : WS_FRAGMENT ;

dummy: ;
````

Input file to lexer to be parsed (no new line in the end):
````txt
/* comment */ red
````

*Actual output:* Generated lexer produced three tokens: `COMMENT WS IDENT`
*Expected output:* Two comments, whitespace after comment should be part of comment `COMMENT IDENT`

*Workaround (only in this specific case, not necessary general):* It works correctly when I change order of alternatives or rephrase rule. Finds longest match:
* `(COMMENT_CONTENT WS_FRAGMENT) | COMMENT_CONTENT`
* `COMMENT : COMMENT_CONTENT WS_FRAGMENT?`

*Version:* I used antlr 4.5 - both runtime and generator

**Comment by sharwell** [comment]
As soon as the lexer crosses a non-greedy operator (`+?`, `*?`, or `??`), it switches to "first match" instead of "longest match" for the remainder of that rule. Your first alternative of `COMMENT` references the fragment rule `COMMENT_CONTENT`, which has a non-greedy operator.

**Comment by SomMeri** [comment]
Thanks for explanation and closing the issue. 

In case someone else runs into this, [Wildcard Operator and Nongreedy Subrules](https://theantlrguy.atlassian.net/wiki/display/ANTLR4/Wildcard+Operator+and+Nongreedy+Subrules) on wiki explains all differences against greedy lexer and also why.

**Comment by mullekay** [comment]
@SomMeri Thanks for the information in the link, unfortunately I can not access it. Do you know, whether the information is available somewhere else? Thank you very much in advance!

**Comment by mthierba** [comment]
*For reference* Updated version of the above link: https://learning.oreilly.com/library/view/the-definitive-antlr/9781941222621/f_0099.xhtml

**Comment by dgellow** [comment]
Just in case someone find this issue after 2023, the documentation page "Wildcard operator and nongreedy subrules" is now on github: https://github.com/antlr/antlr4/blob/master/doc/wildcard.md.
