### ISSUE TITLE
Allow for "single insertion token" error recovery strategy when using semantic predicates

### ISSUE THREAD

**Issue by rslemos** [antlr/antlr4#867]
Given the following grammar:

```antlr4```
grammar AAAGrammar;

aaaaa : 
    a* ';'
  ;

a :
    'A'
  ;
```

Running over the following inputs, the resulting parse trees are:

- "AAA;": (aaaaa (a A) (a A) (a A) ;);
- "AAA" : (aaaaa (a A) (a A) (a A) missing ';') (this one emits a warning on stderr: line 1:5 missing ';' at '').

Note the missing token ";" correctly injected.


If I introduce a semantic predicate (albeit an innocuous one) into rule a, so it looks like:
```antlr4```
a :
    {true}? 'A'
  ;
```

Then token insertion stops working:

- "AAA;": (aaaaa (a A) (a A) (a A) ;);
- "AAA" : (aaaaa (a A) (a A) (a A)) (this one also emits a warning on stderr: line 1:5 no viable alternative at input '').

Isn't it possible to have both, semantic predicate and single token insertion recovery at the same time? Or are they anyhow incompatible?

**Comment by parrt** [comment]
Hiya! yeah, we could probably come up with some rules but it won't likely bump up in priority for me so I'll close for now.
