### ISSUE TITLE
Parser  not able to load lexer

### ISSUE THREAD

**Issue by pbajaj14** [antlr/antlr4#872]
I have to two lexer.g4 and parser.g4 files.  Error showing unable to find or load grammer SQLLexer.
Kindly provide solution.
![antlr4](https://cloud.githubusercontent.com/assets/8348389/7698301/b647b630-fe2c-11e4-9971-9a8bda179581.PNG)

**Comment by parrt** [comment]
worst bug report ever. wrong place, unknown IDE plugin.
