### ISSUE TITLE
`triggerEnterRuleEvent` invoked twice for rules with alt labels

### ISSUE THREAD

**Issue by sharwell** [antlr/antlr4#879]
Pull request #876 added a second call to `triggerEnterRuleEvent` from within rules with outer alt labels.

Consider the following rule:

```antlr
typeBound
    :   type ('&' type)* # TypeBounds
    ;
```

The generated code for this rule is the following (this may differ slightly from the code generated by the reference release, but it's close):

```java
public final TypeBoundContext typeBound() throws RecognitionException {
    TypeBoundContext _localctx = new TypeBoundContext(_ctx, getState());
    enterRule(_localctx, 24, RULE_typeBound);
    int _la;
    try {
        _localctx = new TypeBoundsContext(_localctx);
        enterOuterAlt(_localctx, 1);

// rest of rule ...
```

The first call to `triggerEnterRuleEvent` occurs within `enterRule`. The second call, introduced by #876, occurs within `enterOuterAlt`. While this is not a problem if a user only adds code for `enterTypeBound`, it causes a problem for general listeners which handle `enterEveryRule`. One such rule in the runtime library itself is `TraceListener`.

**Comment by parrt** [comment]
it seems to me that ensure every rule should not be mutually exclusive with the other rule entries. I would expect to get every rule event the matter what and then an extra event for any labels. I'm trying some examples now

**Comment by parrt** [comment]
Adding ref to original bug https://github.com/antlr/antlr4/issues/802.

**Comment by parrt** [comment]
I undid previous commit to fix https://github.com/antlr/antlr4/issues/802 so this one is now stale.
