### ISSUE TITLE
Generated file contains syntax error

### ISSUE THREAD

**Issue by jadielam** [antlr/antlr4#886]
The Java code generated by ANTLR has some syntax errors that cause the source code not to compile. 
The error happens in the *Lexer.java file.

I can submit the grammar that I used for reproduction. Using antlr 4.5.

![image](https://cloud.githubusercontent.com/assets/1026067/7976062/dfec4c44-0a43-11e5-9908-b322e29ac328.png)

**Comment by jadielam** [comment]
grammar BibleReference; 

ref: book (DOT)? SPACE refList;

book: AMOS | FIRSTCHRONICLES | SECONDCHRONICLES | DANIEL | DEUTERONOMY | ECCLESIASTES | ESTHER | EXODUS |
	  EZEKIEL | EZRA | GENESIS | HABAKKUK | HAGGAI | HOSEA | ISAIAH | JEREMIAH | JOB | JOEL | JONAH |
	  JOSHUA | JUDGES | FIRSTKINGS | SECONDKINGS | LAMENTATIONS | LEVITICUS | MALACHI | MICAH |
	  NAHUM | NEHEMIAH | NUMBERS | OBADIAH | PROVERBS | PSALMS | RUTH | FIRSTSAMUEL | SECONDSAMUEL | SONGOFSOLOMON |
	  ZECHARIAH | ZEPHANIAH | 
	  ACTS | REVELATION | COLOSSIANS | FIRSTCORINTHIANS | SECONDCORINTHIANS | EPHESIANS | GALATIANS |
	  HEBREWS | JAMES | JOHN | FIRSTJOHN | SECONDJOHN | THIRDJOHN | JUDE | LUKE | MARK | MATTHEW | FIRSTPETER | SECONDPETER | PHILEMON |
	  PHILIPPIANS | ROMANS | FIRSTTHESSALONIANS | SECONDTHESSALONIANS | FIRSTTIMOTHY | SECONDTIMOTHY | TITUS ;

refList: chapterRef ((SPACE)? PUNTOYCOMA (SPACE)? chapterRef)* ;

chapterRef: simpleRef | rangeRef | multipleVerseRef ;

simpleRef: chapterOnly | chapterVerse | chapterVerseRange ;
chapterOnly: NUM ;
chapterVerse: NUM SEPARATOR NUM;
chapterVerseRange: NUM SEPARATOR NUM GUION NUM ;

rangeRef : chapterRange | chapterVerseRange ;
chapterRange : NUM GUION NUM ;
chapterRangeVerse : NUM (SEPARATOR NUM)? GUION NUM SEPARATOR NUM ;

multipleVerseRef : NUM SEPARATOR verseExp (COMA SPACE verseExp)* ;
verseExp : NUM | NUM GUION NUM ;

//TOKENS

NUM: [1-9][0-9]{0,2} ;  //Chapter and verse numbers
DOT: '.' ;
GUION: '-' ;
DOSPUNTOS: ':' ;
SPACE : [\t\s]+ ;
PUNTOYCOMA : ';' ;
SEPARATOR : DOT | DOSPUNTOS ;
COMA : ',' ;


//Old Testament books in alphabetical order
AMOS: 'Amos' | 'Am' ;
FIRSTCHRONICLES : '1 Chronicles' | '1 Chron' | '1 Chr' | '1Chron' | '1Chr' ;
SECONDCHRONICLES : '2 Chronicles' | '2 Chron' | '2 Chr' | '2Chron' | '2Chr' ;
DANIEL : 'Daniel' | 'Dan' | 'Dn' ;
DEUTERONOMY : 'Deuteronomy' | 'Deut' | 'Dt' ;
ECCLESIASTES : 'Ecclesiastes' | 'Eccles' | 'Eccl' ;
ESTHER : 'Esther' | 'Est' ;
EXODUS: 'Exodus' | 'Exod' | 'Exo' | 'Ex' ;
EZEKIEL : 'Ezekiel' | 'Ezek' | 'Ez' ;
EZRA: 'Ezra' | 'Ezr' ;
GENESIS: 'Genesis' | 'Gen' | 'Gn' ;
HABAKKUK: 'Habakkuk' | 'Hab' | 'Hb' ;
HAGGAI: 'Haggai' | 'Hag' | 'Hg' ;
HOSEA: 'Hosea' | 'Hos' ;
ISAIAH: 'Isaiah' | 'Isa' | 'Is' ;
JEREMIAH: 'Jeremiah' | 'Jer';
JOB: 'Job' | 'Jb';
JOEL: 'Joel' | 'Jl' ;
JONAH: 'Jonah' | 'Jon' ;
JOSHUA: 'Joshua' | 'Josh' | 'Jo' ;
JUDGES: 'Judges' | 'Judg' | 'Jgs' ;
FIRSTKINGS: '1 Kings' | '1 Kgs' | '1Kings' | '1Kgs' ;
SECONDKINGS: '2 Kings' | '2 Kgs' | '2Kings' | '2Kgs' ;
LAMENTATIONS: 'Lamentations' | 'Lam' | 'Lm' ;
LEVITICUS: 'Leviticus' | 'Lev' | 'Lv' ;
MALACHI: 'Malachi' | 'Mal' ;
MICAH: 'Micah' | 'Mic' | 'Mi' ;
NAHUM: 'Nahum' | 'Nah' | 'Na' ;
NEHEMIAH: 'Nehemiah' | 'Neh' ;
NUMBERS: 'Numbers' | 'Num' | 'Nm' ;
OBADIAH: 'Obadiah' | 'Obad' | 'Ob' ;
PROVERBS: 'Proverbs' | 'Prov' | 'Prv' ;
PSALMS: 'Psamls' | 'Psalm' | 'Ps' | 'Pss' ;
RUTH: 'Ruth' | 'Ru' ;
FIRSTSAMUEL: '1 Samuel' | '1 Sam' | '1Samuel' | '1Sam' ;
SECONDSAMUEL: '2 Samuel' | '2 Sam' | '2Samuel' | '2Sam' ;
SONGOFSOLOMON: 'Song of Solomon' | 'Song of Sol' | 'Sg' | 'Song' | 'Song of Songs' ;
ZECHARIAH: 'Zechariah' | 'Zech' | 'Zec' ;
ZEPHANIAH: 'Zephaniah' | 'Zeph' | 'Zep' ;

//New Testament books in alphabetical order
ACTS: 'Acts of the Apostles' | 'Acts' ;
REVELATION: 'Revelation' | 'Apocalypse' | 'Ap' | 'Apoc' | 'Rev' | 'Rv' ;
COLOSSIANS: 'Colossians' | 'Col' ;
FIRSTCORINTHIANS: '1 Corinthians' | '1 Cor' | '1Corinthians' | '1Cor' ;
SECONDCORINTHIANS: '2 Corinthians' | '2 Cor' | '2Corinthians' | '2Cor' ;
EPHESIANS: 'Ephesians' | 'Eph' ;
GALATIANS: 'Galatians' | 'Gal' ;
HEBREWS: 'Hebrews' | 'Heb' ;
JAMES: 'James' | 'Jam' | 'Jas' ;
JOHN: 'John' | 'Jn' ;
FIRSTJOHN: '1 John' | '1 Jn' | '1John' | '1Jn' ;
SECONDJOHN: '2 John' | '2 Jn' | '2John' | '2Jn' ;
THIRDJOHN: '3 John' | '3 Jn' | '3John' | '3Jn' ;
JUDE: 'Jude' | 'Jd' ;
LUKE: 'Luke' | 'Luk' ;
MARK: 'Mark' | 'Mk' ;
MATTHEW: 'Matthew' | 'Matt' | 'Mt' ;
FIRSTPETER: '1 Peter' | '1 Pet' | '1 Pt' | '1Peter' | '1Pet' | '1Pt' ;
SECONDPETER: '2 Peter' | '2 Pet' | '2 Pt' | '2Peter' | '2Pet' | '2Pt' ;
PHILEMON: 'Philemon' | 'Philem' | 'Phlm' ;
PHILIPPIANS: 'Philippians' | 'Phil' ;
ROMANS: 'Romans' | 'Rom' ;
FIRSTTHESSALONIANS: '1 Thessalonians' | '1 Thess' | '1 Thes' | '1Thessalonians' | '1Thess' | '1Thes' ;
SECONDTHESSALONIANS: '2 Thessalonians' | '2 Thess' | '2 Thes' | '2Thessalonians' | '2Thess' | '2Thes' ;
FIRSTTIMOTHY: '1 Timothy' | '1 Tim' | '1 Tm' | '1Timothy' | '1Tim' | '1Tm' ;
SECONDTIMOTHY: '2 Timothy' | '2 Tim' | '2 Tm' | '2Timothy' | '2Tim' | '2Tm' ;
TITUS: 'Titus' | 'Ti' ;

**Comment by jadielam** [comment]
Is there a quick fix that I can do to that file to make it work? I don't want to remove that line of code and be left with a parser that does not parse things well.

**Comment by jadielam** [comment]
Issue fixed. I realized that I had an error in the grammar because what i thought were quantifiers is actually java code that gets inserted.

**Comment by jimidle** [comment]
This rule:

NUM
:
    [1-9] [0-9]
    {0,2}

Is not correct. the {0,2} is just seen as action code so it is placed in
your output file. I think that you are trying to use RE like occurrence
limiters but such things are not supported in ANTLR.

Jim

**Comment by jadielam** [comment]
Thank you very much for your quick response!

On Wed, Jun 3, 2015 at 11:05 PM, Jim Idle <notifications@github.com> wrote:

> This rule:
>
> NUM
> :
> [1-9] [0-9]
> {0,2}
>
> Is not correct. the {0,2} is just seen as action code so it is placed in
> your output file. I think that you are trying to use RE like occurrence
> limiters but such things are not supported in ANTLR.
>
> Jim
>
> On Thu, Jun 4, 2015 at 10:58 AM, Jadiel <notifications@github.com> wrote:
>
> > The Java code generated by ANTLR has some syntax errors that cause the
> > source code not to compile.
> > The error happens in the *Lexer.java file.
> >
> > I can submit the grammar that I used for reproduction. Using antlr 4.5.
> >
> > [image: image]
> > <
> https://cloud.githubusercontent.com/assets/1026067/7976062/dfec4c44-0a43-11e5-9908-b322e29ac328.png
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/antlr/antlr4/issues/886>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/antlr/antlr4/issues/886#issuecomment-108698379>.
>



-- 
Jadiel de Armas
Student of Computer Science/Mathematics
Arizona State University
