### ISSUE TITLE
Antlr4 unable to parse 2 consecutive optional parameter.

### ISSUE THREAD

**Issue by sumanta23** [antlr/antlr4#894]
when the grammar is defined in such a way that it will accept two consecutive optional parameter, its not behaving they way it should behave.

         listselection :

	(propertyFromListWithValue[list(withAlias("--entitytype", "-type")), list("ca", "ee")]   
		
       ( propertyFromList[list(withAlias("--name", "-n"))]?       propertyFromListWithValue[list(withAlias("--test", "-t")), list("a", "b")]?	) 

       | propertyFromListWithoutValue[list(withAlias("--all", "-a"))]  )
;

ex : 
-type ca -n abc  accepted
-type ca -n abc -t a  accepted
-type ca -t a  not accepting

What I observed, it its expecting the name token. So the name token is not behaving as optional.(partially)

![er](https://cloud.githubusercontent.com/assets/4776144/8034819/1037629e-0e09-11e5-98c0-d23e29b59219.jpg)

**Comment by parrt** [comment]
Can you show more of grammar and throw out those actions in the [...]?

**Comment by sumanta23** [comment]
below is the snippet for more code snippet.

parser snippet
command :    ( managementlist ) ;

managementlist: 	MGMTLIST listselection;

listselection :
(propertyFromListWithValue[list(withAlias("--entitytype", "-type")), list("ca", "ee")]

( propertyFromList[list(withAlias("--name", "-n"))]?    propertyFromListWithValue[list(withAlias("--test", "-t")), list("a", "b")]?   )
| propertyFromListWithoutValue[list(withAlias("--all", "-a"))] )
;

Lexer snippet..
MGMTLIST : ('mgmt -l') -> mode(inside_command);



generated java code snippet.

setState(61);
				switch ( getInterpreter().adaptivePredict(_input,0,_ctx) ) {     //??
				case 1:
					{ //is getting executed.
					setState(60); propertyFromList(list(withAlias("--name", "-n")));
					}
					break;
				}
				setState(64);
				_la = _input.LA(1);
				if (_la==TEXT || _la==PROPERTY_PREFIX) {
					{
					setState(63); propertyFromListWithValue(list(withAlias("--test", "-t")), list("a", "b"));
					}
				}

**Comment by sharwell** [comment]
@sumanta23 The fastest way to help us track this down is include the following:

1. Complete grammar
2. Input to provide to the grammar
3. Expected output
4. Actual output

However, based on what you've shown so far, I'm guessing you have semantic predicates inside of `propertyFromList` and/or `propertyFromListWithValue` which references whatever value is being returned by the `list()` method. In some situations, ANTLR 4 is not able to evaluate context-sensitive semantic predicates because the context does not exist at the time the predicate is evaluated. If you receive a `FailedPredicateException` while parsing, it's probably due to this.

**Comment by sumanta23** [comment]
@sharwell Here is the sample project  https://www.dropbox.com/s/hy4k8k7czfou86o/antlr.zip?dl=0

input : mgmt -l -type ca -t b

expected output :  {test=b, command=MGMTLIST, entitytype=ca}

Actual output : 
command error com.exception.MyException: command error
	at com.CParser.propertyFromValidProperties(CParser.java:656)
	at com.CParser.propertyFromList(CParser.java:503)
	at com.CParser.listselection(CParser.java:210)
	at com.CParser.managementlist(CParser.java:163)
	at com.CParser.command(CParser.java:130)
	at com.CParser.parseCommand(CParser.java:269)
	at Test.main(Test.java:16)

**Comment by sumanta23** [comment]
@sharwell any idea if its a bug in antlr or in my grammar.

**Comment by parrt** [comment]
almost certainly not a bug. I suggest to shrink your grammar until you isolate your issue, or get rid of all those actions in the grammar.

**Comment by sumanta23** [comment]
Thanks, Closing it.
