### ISSUE TITLE
fetchedEOF not reset in BufferedTokenStream.reset()

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#895]
Seems like a bug, right, @sharwell?

**Comment by sharwell** [comment]
I don't think so. The `reset()` method just does a `seek(0)` but doesn't discard the contents of the existing buffer. The documentation for the `fetchedEOF` field is quite detailed, and according to that I wouldn't expect `reset()` to change it unless it also clears `tokens`.

**Comment by parrt** [comment]
Hmm...I think reset should reset the stream to something like initial state. if i want just seek(0) I can do that.

**Comment by parrt** [comment]
Care to comment on adding a "clip(start,stop)" functionality to the BufferedTokenStream btw?

**Comment by sharwell** [comment]
At this point, it's probably better to just document it as-implemented. In addition to changing the behavior of a method in the public API, there's no `TokenSource.reset` operation so this would cascade.

**Comment by sharwell** [comment]
> Care to comment on adding a "clip(start,stop)" functionality to the BufferedTokenStream btw?

Adding non-abstract methods to a class is generally a non-breaking change. But this proposal should probably be its own issue so it can be defined and discussed.
