### ISSUE TITLE
Can't load Hello as lexer or parser

### ISSUE THREAD

**Issue by avnibharne** [antlr/antlr4#900]
I am trying to run the simplest Hello.g4 grammar and I am getting the error "Can't load Hello as lexer or parser" 
I am running it on windows and my CLASSPATH has the dot.
the Path environment variable has the directory of batch files as well.
![failure](https://cloud.githubusercontent.com/assets/12853884/8122535/0994c832-1070-11e5-8853-28a9d9fd5f45.png)
I really don't know where i am going wrong
Thanks

**Comment by thefteye** [comment]
Hey, can someone please help me? I am facing the same problem. Thanks!!

**Comment by rEaL-jAsE** [comment]
Still having this problem? If not how did you resolve it?

**Comment by parrt** [comment]
Dot is not in the classpath despite claims that it is

**Comment by drsalehi** [comment]
How can fix this problem? 
I am trying to run the sample experiment.g4 grammar and I am getting the error
 "Can't load Hello as lexer or parser"
I am running it on windows and my CLASSPATH has the dot.
The Path environment variable has the directory of batch files as well.
I problem like as avnibharne !!!!
