### ISSUE TITLE
Make Grammar-object-aware ParserInterpreter

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#905]
This interpreter will have parse tree nodes that know which alternative or label was matched for a particular parse tree subtree root.

**Comment by whitten** [comment]
Is it ever the case that two alternatives have the same prefix ?
Do you intend to mark both of them as the alternative matched ?

**Comment by parrt** [comment]
hiya. Yep. two alts can have same alt label. They will get correct altnum but also access to the correct altlabel...even for left-recursive rules :)

**Comment by parrt** [comment]
Fixed by pull request #918
