### ISSUE TITLE
org.antlr.v4.runtime.misc.Predicate not present

### ISSUE THREAD

**Issue by ZenHarbinger** [antlr/antlr4#919]
I just did an upstream merge and build and org.antlr.v4.runtime.tree.Trees makes use of a Predicate.java that is not included:

/home/matta/Dev/antlr4/runtime/Java/src/main/java/org/antlr/v4/runtime/tree/Trees.java:[38,32] error: cannot find symbol
[ERROR]   symbol:   class Predicate
  location: package org.antlr.v4.runtime.misc
/home/matta/Dev/antlr4/runtime/Java/src/main/java/org/antlr/v4/runtime/tree/Trees.java:[321,45] error: cannot find symbol

**Comment by parrt** [comment]
missed one. pushed.
