### ISSUE TITLE
maybe someone has this problem already

### ISSUE THREAD

**Issue by JustKain** [antlr/antlr4#930]
in SQLParser.g4 we can see this rule:

```antlr
create_trigger_statement
    : CONSTRAINT? TRIGGER name=schema_qualified_name (before_true=BEFORE | (INSTEAD OF) | AFTER)
    (((insert_true=INSERT | delete_true=DELETE | truncate_true=TRUNCATE) | update_true=UPDATE (OF names_references )?)OR?)+
    ON tabl_name=schema_qualified_name 
    (FROM referenced_table_name=schema_qualified_name)?
    table_deferrable? table_initialy_immed?
    (for_each_true=FOR EACH? (ROW | STATEMENT))?
    when_trigger?
    EXECUTE PROCEDURE func_name=function_parameters
    ;
```

after autogeneration **SQLParser.java** we can find method `create_trigger_statement`, in this method first lines is:

```java
Create_trigger_statementContext _localctx = new Create_trigger_statementContext(_ctx, getState());
enterRule(_localctx, 86, RULE_create_trigger_statement);
int _la;
try {
	enterOuterAlt(_localctx, 1);
	{
	setState(1493);
	_la = _input.LA(1);
	if (_la==CONSTRAINT) {
		{
		setState(1492);
		match(CONSTRAINT);
		}
	}
```

and problem come from `_la = _input.LA(1)` - in debug mode this `_la` has number of `TRIGGER` token, so when program come to if we have such expression `if (TRIGGER==CONSTRAINT) {` 
sure program pass this if every time and created context didn't has keyword `CONSTRAINT` before keyword `TRIGGER`.

have anyone suggestion with this problem or this is bug and need to wait while it will be fixed?

**Comment by sharwell** [comment]
@JustKain The `CONSTRAINT` keyword is optional in this rule, as indicated by the `?` in `CONSTRAINT?`. The code block you reference simply checks to see if a `CONSTRAINT` token is present; if not it moves on to the `TRIGGER` token and does not include a `CONSTRAINT` token in the generated context.

**Comment by JustKain** [comment]
https://github.com/sharwell
sure it optional but i create constraint trigger, for example:
CREATE CONSTRAINT TRIGGER test_tri
    AFTER INSERT OR UPDATE
    ON test
    FOR EACH ROW
    EXECUTE PROCEDURE test(); 
in IDEA test rule parsetree seems good, in create_trigger_statement we can see CONSTRAINT before TRIGGER, but when come to debug and walk into method that i described upper, we can see that first IF failed everytime and created trigger statement didn't include CONSTRAINT word in it's expression. For example you can create listener for parsetree and override method enterCreate_trigger_statement,  and write next line "System.out.print(ctx.getText());", when you start default walker with this listener you will see that first word will be TRIGGER even if CONSTRAINT exist before TRIGGER. I'm so confused because i need to autogenerate SQLParser everytime when project starts and in this case i can't do anything because problem in generated file.

**Comment by jimidle** [comment]
Are you sure that your lexer and parser are in sync - as in you regen the
lexer and THEN regen the parser to make sure that the token numbers are
synchronized.

Jim

**Comment by JustKain** [comment]
sure they are
