### ISSUE TITLE
Antlr for C# Target inheritance problem for Parser class

### ISSUE THREAD

**Issue by limsk1** [antlr/antlr4#936]
In Parser interface, _input is declared as private attribute so the inherited classes cannot access this attribute directly. However, the derived parser from Antlr tries to access _input directly and it causes an error while building. Changing the scope form private to protected works.

**Comment by ericvergnaud** [comment]
Hi,

the place for C# issues is antlr4-csharp if you are using the version from this repo, or tunnelvisionlabs if you are using their version.
please close this issue and reopen it where appropriate.

Eric

**Comment by sharwell** [comment]
Hi @limsk1,

It looks like you are not using the same version of the code generator as the runtime. In particular, if you use the ANTLR 4 package from NuGet for automatic code generation during a build, you will also need to reference the ANTLR 4 Runtime package from NuGet.

**Comment by limsk1** [comment]
Thanks Mr.Harwell,

What I used for my project were 1) code generator a.k.a. Antlr4.5 tool
(.jar file) at http://www.antlr.org/download.html, and 2) Antlr 4.5 C#
Runtime library also at http://www.antlr.org/download.html. Aren't they
what I supposed to use?

Thanks!

Best,
Sunkyu Lim

On Wed, Jun 24, 2015 at 12:26 AM, Sam Harwell <notifications@github.com>
wrote:

> Hi @limsk1 <https://github.com/limsk1>,
>
> It looks like you are not using the same version of the code generator as
> the runtime. In particular, if you use the ANTLR 4 package from NuGet for
> automatic code generation during a build, you will also need to reference
> the ANTLR 4 Runtime package from NuGet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/antlr/antlr4/issues/936#issuecomment-114762012>.
>



-- 
Sunkyu Lim
Stanford University, Class of 2016
Coterminal Student in Computer Science
