### ISSUE TITLE
What is the current state of unit testing antlr4 grammars in Java?

### ISSUE THREAD

**Issue by Suseika** [antlr/antlr4#938]
Is there a recommended way to unit-test antlr4 grammars? I heard gunit is for that, but it seems to be for antlr3 only. I tried maven-gunit-plugin, but it doesn't seem to see my gunit tests placed in `src/test/gunit`. I'm really confused, where do I start with unit testing antlr4 grammars?

**Comment by parrt** [comment]
It turns out that plain old junit, for the Java target anyway, works just as well as gunit. In fact you can look at some of the unit tests for antlr4 itself to see how we do it.
