### ISSUE TITLE
ANTLR4 : no viable alternative at input user

### ISSUE THREAD

**Issue by BruceXu1991** [antlr/antlr4#947]
this is my grammar below:
select_statement:
        select_expression (  UNION (ALL | DISTINCT)?  select_expression )*
;

select_expression:
	SELECT
	( ALL | DISTINCT  )?
	select_list
	(
		FROM table_references
		( where_clause )?
		( groupby_clause )?
		( having_clause )?
	) ?
	( orderby_clause )?
	( limit_clause )?
;

table_references:
        table_reference ( COMMA table_reference )*
;
table_reference:
	table_factor1 | table_atom
;
table_factor1:
	table_factor2 (  (CROSS)? JOIN table_atom (join_condition)?  )?
;
table_factor2:
	table_factor3 (  (LEFT|RIGHT|FULL) (OUTER)? JOIN table_factor3 join_condition  )?
;
table_factor3:
	table_atom (  ( (LEFT|RIGHT|FULL) (OUTER)? )? JOIN table_atom )?
;
table_atom:
	  ( table_spec (alias)?  )
	| ( subquery alias )
	| ( LPAREN table_references RPAREN )
	|  ID
;
ID:
	( 'A'..'Z' | 'a'..'z' | '_' | '$') ( 'A'..'Z' | 'a'..'z' | '_' | '$' | '0'..'9' )*
;
when the input : select * from user  OR  select * from use ;
the error is " ANTLR4 : no viable alternative at input (use |  user)"
and when I input other : select * from us OR 
                                      select * from usera OR 
                                      select * from abc..               It  turn out right.

So  why the  " use' "and " user " can't be recognized ?

**Comment by BruceXu1991** [comment]
I want to add that  'use' and 'user' has been define in lexer,so it is key word ,but  i still don't know how to resolve it.. Could anyone help?

**Comment by BruceXu1991** [comment]
what should  i do inorder to recognize the 'use' and 'user'.

**Comment by jimidle** [comment]
Make sure that it is listed in your lexer before rules like ID






On Mon, Jul 6, 2015 at 1:18 AM -0700, "Bruce Xu" <notifications@github.com> wrote:












what should  i do inorder to recognize the 'use' and 'user'.

**Comment by BruceXu1991** [comment]
Thx for your answer.
but , I give a simple grammar：
grammar usetest;

USE: 'use';

SELECT: 'select';

select: SELECT ID ;

ID: ( 'A'..'Z' | 'a'..'z' | '_' | '$') ( 'A'..'Z' | 'a'..'z' | '_' | '$' | '0'..'9' )*
;

WHITE_SPACE	: ( ' '|'\r'|'\t'|'\n' ) -> skip ;

the input is :  select 'use' 
it turns out that : mismatch input 'use' expecting ID

I am using antlr4 to create a SQL paser, so if  'use'  is a table or column , it should be recognized out. 

could you help me how I can   recognize  'use'

**Comment by jimidle** [comment]
You can't tell it it is a keyword and then expect it to be matched as an
ID. There is no interaction between the parser and the lexer. You need:

select: SELECT id_orkey;

id_orkey: id=(ID | USE);

Jim

**Comment by BruceXu1991** [comment]
Thx so much，you help my solve the problem.

And  I would like to ask you another quention :
I want to identifiy the Single_Quote of Double_Quote, this is my grammar below :
grammar sql;
DATABASES : 'DATEBASES'
SHOW :   'SHOW' ;
Double_Quote   : ' " ' ; 
Single_Quote :  ' \' ' ;
root_statement:
	data_definition_statements 
	(SEMI)?
;

data_definition_statements:
     show_event_statement
;

show_event_statement:
      SHOW show_specification;

show_specification:
       (DATABASES | SCHEMAS) LIKE Double_Quote ID Double_Quote
;
And  the input：  SHOW DATABASES LIKE  "xwc" ;
the screen shows: mismatched input  ' "xwc" ' expecting Double_Quote.
I am confused why the input "xwc" is being read by Double_Quote?
And how to resolve?

**Comment by parrt** [comment]
what token does it match? ask intellij plugin.

**Comment by parrt** [comment]
PS: please don't ask questions here
