### ISSUE TITLE
DefaultErrorStrategy.recover has some bad cases

### ISSUE THREAD

**Issue by michaelpj** [antlr/antlr4#948]
It looks like the current error recovery strategy has some pathological cases.

Consider the example in the documentation for `DefaultErrorStrategy.recover`:

```
a : '[' b ']'
  | '(' b ')'
  ;
b : c '^' INT ;
c : ID
  | INT
  ;
```

Given input `[]`, the current implementation constructs the combined contextual follow sets for the call chain `a -> b -> c`, and then consumes until it sees one of them. This results in syncing up to `]`, whence we can continue with `a`.

However, consider the following input: `[]^9]`. To the human eye this is a single malformed instance of `a`, with an extraneous `]`. However, currently we will synchronise in the same way, consuming only up until the `]`, and then falling over on the subsequent `^`. On the other hand, if we'd synced up to the `^` (which is in the follow set for `c`), we would have been fine.

---

To give a concrete example of how this is biting me, I have a grammar roughly like this:

```
main : (query | predicate)* ;
query : 'from' vardecl 'where' ... 'select' ... ;
vardecl: type lowerid ;
predicate: type lowerid '{' ... '}' ;
```

A query looks like this:

```
from int i
where ...
select ...
```

However, if we add an error:

```
from 'int i
where ...
select ...
```

things go wrong. I would like us to consume the `'`, `int` and `i` tokens, and resume the `query` rule from `where`. However, before we reach the `where` token, we see the `int` token, which could be the start of a `predicate`, and so is in our combined follow set. So we stop looking, and when we resume we start trying to parse a `predicate`, which doesn't go very well.

(This is a recurring problem for this grammar, as many constructs have `vardecl`s, and so the parser quite frequently ends up recovering into a `predicate`, which is usually not very helpful.)

The situation is analagous to the one I described before: we have an deep rule in the context stack which has a following token after some number of consumptions. However, before we reach that, we see a following token for a rule higher up in stack, and so we stop there.

---

My intuitive thought is that we should prioritise deeper rules when looking for following characters. But
1. This would be more expensive, since we'd need to look ahead for each rule in the stack in turn, until we found a following token.
2. I suspect this may have pathological cases of it's own. If we are willing to look far ahead (maybe even to EOF) for a following token, we may just discard too many tokens.

Hence I don't really have a good suggestion for what I'd like to happen here, except that I'd like it to avoid these particular cases!

**Comment by sharwell** [comment]
This came up in the past, and some great ideas were put forward for working to improve recovery. I think error recovery is one of the biggest open problems in parsing.

The one area to be particularly careful about is the algorithmic complexity of the recovery mechanism. Expensive recovery algorithms could leave systems exposed to [algorithmic complexity attacks](https://en.wikipedia.org/wiki/Algorithmic_complexity_attack), and changing the recovery algorithm runs the risk of side-stepping protection mechanisms companies may have in place to mitigate such attacks (if the protection assumes recovery works in a particular way but we change that, the protection may no longer work).

**Comment by michaelpj** [comment]
This bit me again today. Different bit of the same grammar - it's pretty easy to trigger this in a variety of ways if you have tokens that can appear in different places.

As an aside, almost all the cases that are particularly annoying are cases where single token insertion/deletion would have allowed for a recovery. I don't entirely understand why we try that`recoverInline`, but not in `recover`. Is it just likely to be more expensive in that case?

**Comment by sharwell** [comment]
`recover` is called from inside `adaptivePredict`. There should be a call to `sync` before each `adaptivePredict` which attempts to perform the single-token insertion or deletion if it's clear that the prediction would fail otherwise.

**Comment by michaelpj** [comment]
Hm, in this instance there doesn't seem to be such a call before the
*first* call to `adaptivePredict`, although it does appear later. I would
also guess that that doesn't work well with trailing tokens that need
deletion? e.g. `foo().bar().`, which would parse fine as a Java-like
expression if you deleted the trailing `.`, but I suspect that confuses the
predictor.

**Comment by michaelpj** [comment]
Returning to this issue, I decided to have a little poke around in the codegen for those missing calls to `sync`. 

I notice that [here](https://github.com/antlr/antlr4/blob/master/tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg#L534) and [here](https://github.com/antlr/antlr4/blob/master/tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg#L547) there are calls to `sync` that were commented out in 2c52166dd057f55493e7e8a2772002ec635cac95. Uncommenting these and regenerating my parsers improves recovery in quite a few cases with leading extraneous tokens.

It still doesn't handle cases where the extraneous token is trailing, but I can see that this is trickier, since the possibility of discarding tokens would have to be woven into the prediction.

I don't suppose @parrt can remember the reason that those `sync` calls were removed? It doesn't break any tests, but I could see that it might have performance implications. If it's inoccuous enough, then it seems like an easy improvement to recovery.

**Comment by parrt** [comment]
Hiya. Yeah, those are there to make sure we remove extra bad tokens *before* making a decision with the switch etc...

**Comment by michaelpj** [comment]
That would make sense, except they're currently commented out!

**Comment by parrt** [comment]
oh shit. ;)

**Comment by michaelpj** [comment]
I'm going to interpret that as "pull requests welcome" :wink:

**Comment by parrt** [comment]
Closing as we added sync back.
