### ISSUE TITLE
XPath.java uses XPathLexer; but it is not in the project

### ISSUE THREAD

**Issue by ZenHarbinger** [antlr/antlr4#957]
I am maintaining a fork w/o graphics for Android and currently I am seeing that XPath.java is requiring XPathLexer to compile.  Am I missing something?  I admit I am using a modified pom.xml file to compile the runtime jar instead of using bild

**Comment by parrt** [comment]
I just remove the dependency on swing in 4.5.1 so you should be good to go. that file is generated by ANTLR itself using bootstrapping. you should now see pom.xmsl

**Comment by ZenHarbinger** [comment]
Awesome!
That makes life easier for me.
Love the tool.

**Comment by parrt** [comment]
cool :)
