### ISSUE TITLE
Antlr4 throws NoViableAltException instead of reporting missing token

### ISSUE THREAD

**Issue by vlprof** [antlr/antlr4#960]
Example grammar:

```
expr
    : parenthesis 
    | parenthesis '&' parenthesis
    ;

parenthesis 
    : '(' ID ')'
    ;

ID
    :	( 'a'..'z' | 'A'..'Z' )+
    ;
```
While parsing next input `(x` Parser throws _NoViableAltException_. If I remove ` parenthesis '&' parenthesis` rule it reports missing token error: _line 1:2 missing ')' at '\<EOF\>'_. Even if I rewrite 2-nd rule just to ignore it via semantic predicate `| {false}? parenthesis '&' parenthesis` I still get _NoViableAltException_.

Found a temporary solution, next grammar works fine:
```
expr
    : parenthesis 
    | TEMP_FIX parenthesis '&' parenthesis
    ;

TEMP_FIX  
    : ''
    ;
```

**Comment by parrt** [comment]
removing that 2nd alt leaves 1 alt, which is not a decision so it attempts no matter what. With 2 alts it has to choose and cannot based upon your input. I don't see why it can't match `(x` though. Are you giving it just `(x` or `(x)`?

**Comment by vlprof** [comment]
I'm giving it `(x`, it misses `)` by desire. Interesting that with TEMP_FIX prefix literal everything works fine

**Comment by parrt** [comment]
Well, (x EOF prevents it from deciding between alts 1 and 2. You can write an error handler to look at all possible paths if you want.

**Comment by vlprof** [comment]
Thanks for the help! I think will try to create custom handler

**Comment by goyaltushar92** [comment]
> Well, (x EOF prevents it from deciding between alts 1 and 2. You can write an error handler to look at all possible paths if you want.

Why it works with TEMP_FIX?
