### ISSUE TITLE
fetchedEOF field holds true even after call on reset() in BufferedTokenStream

### ISSUE THREAD

**Issue by pablo53** [antlr/antlr4#962]
BufferedTokenStream.reset() leaves boolean field fetchedEOF intact, making it impossible to reuse the stream object after the first EOF is hit.

**Comment by sharwell** [comment]
This is a duplicate of #895, where we decided not to make a change to this method. If you are running into problems with a particular use pattern, can you post an example as a comment in that method? I'm interested to see how this is affecting you and if there's anything we can do to improve it.
