### ISSUE TITLE
Antlr doesn't check all alternatives?

### ISSUE THREAD

**Issue by Felix-Helsch** [antlr/antlr4#964]
First the links: [minimal grammar](https://gist.github.com/Felix-Helsch/fea3182a39231e46c1a7), [minimal program](https://gist.github.com/Felix-Helsch/8588eaf7c7faf853d978)

The linked grammar was reduced to a minimal working example, so it should hopefully be quite understandable. It seperates strings in string prefix and string content.
The problem is encountered, when an expression contains a variable, which is named like a string prefix (here `r`), e.g.:
```python
r= x ;
```
Antlr seemingly always wants to parse this as a string and produces an error like:
```
line 2:1 mismatched input '=' expecting Str
```
But when you remove the string_prefix from the string rule, it uses the rule for a variable and parses correctly.
As far as i understood antlr should accept any grammar, as long as it doesnt contain indirect left recursion. So either there is something fundamental which i have not yet understood about antlr, or this is a bug.

(FYI, I also encountered a similar problem for a different parser rule in version 4.4, which disappeared in version 4.5, so I assumed that it was a fixed bug)

And a bit of context, in case it helps:
The described grammar extract belongs to a python compiler I have been developing as a  project at our university. The compiler was mainly done for  learning purposes, so the grammar is self written (and not the official python grammar). It includes semicolons because pythons indentation is handled by preprocessing.

**Comment by parrt** [comment]
you have an error in your grammar.

```
Var : Letter_ (Letter_|Digit)*;
```

 matches 'r' and you also have a literal 'r' in your grammar, which is matched instead of Var because it is mentioned first. you have an ambiguity in your lexer in other words.

**Comment by Felix-Helsch** [comment]
Thank you for pointing out my mistake, I assumed the file would first be  
tokenized using only the lexer rules.
Does this means (approximately) that before the tokenizing a unique lexer  
rule is added for every (different) literal in the parser rules?
