### ISSUE TITLE
Change generated code comment to be more version control friendly

### ISSUE THREAD

**Issue by Groostav** [antlr/antlr4#974]
>As an ANTLR and git user, and working on a code-base that regenerates ANTLR files are part of every build, I want ANTLR's generated 'This is generated code!' warning message to be developer-idempotent, such that simply running ANTLR scripts on different machines will produce character-identical parser.java and grammer.java files.

This might sound small but its driving me nuts.

Currently your message looks like this:
```Java
// Generated from C:\Users\Geoff\Code\OASIS/Problem-Definition//pre-src/BabelParser.g4 by ANTLR 4.4
package com.empowerops.problem_definition.parser;
```

Meaning, if my good friend and coworker Justin builds our codebase, he gits this
```diff
-// Generated from C:\Users\Geoff\Code\OASIS/Problem-Definition//pre-src/BabelParser.g4 by ANTLR 4.4
+// Generated from C:\Users\Justin\Documents\Github/Problem-Definition//pre-src/BabelParser.g4 by ANTLR 4.4 
package com.empowerops.problem_definition.parser;
```

in his pull request, which is annoying.

The quickest and cheapest way to solve this is to simply have the message use a path relative to the output directory. Given that the generated java files are in `D:\Users\Geoff\Code\OASIS\Problem-Definition\gen-src\com\empowerops\problem_definition\parser\` this gives us

```java
// Generated from ../../../../..//pre-src/BabelParser.g4 by ANTLR 4.4
```

which would not change from build to rebuild.

I could probably implement this myself, if you guys are interested in me doing so.

### Feature creeping:

But, what I would really like is to _customize_ that message

>As a new software developer at a big company my very first development issue was to add a feature to a consumer of a Sprint SOAP service. I knew of SOAP and its purpose but had never used it. I eventually stumbled on a ~10k line, mostly annotations/meta, C-Sharp interface with no implementations. Turns out it was a piece of code generated by visual studio. If it had contained generated code warnings that pointed to the wiki article we had, my life would've been much easier.

Specifically, If I could have every class, nested class, method and public field on the generated file contain the javadoc
```java
/**
 * THIS CODE WAS AUTOGENERATED BY ANTLR 4.4
 * YOU CANNOT MODIFY THIS FILE.
 * please see <a href="github.com/ourproject/ourwiki/antlr">our wiki</a> for more details
 */
@SuppressWarnings({"all", "warnings", "unchecked", "unused", "cast"})
public class BabelParser extends Parser {
```

Thus a feature request in a related area:
> as a team lead / somebody concerned with on-boarding people to our project and its use of ANTLR, I would like to customize the behaviour of ANTLR's auto-generated message so that I can point readers of generated code to informative sources about it, so that newbies to our project wont waste hours trying to figure out what the hell `setState` and/or `[WSDLNonsense="NONSENSE-GUID"]` do. 

Which is something I do not believe I can implement.

**Comment by sharwell** [comment]
@Groostav What step(s) are you using to generate code? I know the Maven plugin always produces identical output. It should be straightforward to use a similar code generation command line to produce identical output in your workflow.

**Comment by jimidle** [comment]
Sam - unless there is a Maven plugin that I don't know about ;), it does as
he says and includes the file path in the comment:

// Generated from com\armorize\vicara\compiler\recognizers\VicaraParser.g4
by ANTLR 4.5

I sort of agree with the suggestion of making it the same everywhere, even
though you should never really include generated code in source code
control - everyone should be able to sync, and immediately build from
scratch.

However, with the C target I had a project that needed to compile on about
8 different versions of Unix, some of which had either very poor (HPSUX) or
non-existent Java implementations. I was happy I had made the generated
source be the same on all platforms as then I could check in the generated
source and accommodate this.

Does not apply in this case as if you can't run java then you can't run the
generated code, but the point is that there are sometimes legit reasons for
checking in the generated code.

It's a trivial change to remove the "from *filename*" and replace the file
path with just the file name - best of both worlds as this will not change
on different platforms and is just replacing the call to get the path with
the call to get the filename.

Having custom messages seems overkill - once you see the comment "Generated
from" then you should know to go find the source file and read the comments
there. I suppose though it is trivial to add a search for .a4gencomment,
then ~/a4/.a4gencomment and use the text in there if it is present - it
could help some.

Jim

**Comment by sharwell** [comment]
> Sam - unless there is a Maven plugin that I don't know about ;), it does as
he says and includes the file path in the comment:

As I said, the path is relative to the **pom.xml**, which means it should be identical for all developers. The problem mentioned by @Groostav isn't that there is a path in the header, it's that the path in the header is an absolute path on the file system.

That said, it does look like there would be a difference on Windows systems compared to other systems (`\` vs. `/`). We should probably update the code generator to always use `/` for consistency.

**Comment by jimidle** [comment]
Yeah - but he is not using Maven I am guessing - I still think it's a valid
point and that just using the file name is enough.

**Comment by Groostav** [comment]
I'm not using the maven goal, I'm using ant to call antlr via java, like this:
```xml
  <macrodef name="antlr4"
            description="runs the ANTLR parser generator on the file specified">

    <attribute name="grammarFile"/>
    <attribute name="package"/>
    <attribute name="outputDir"/>
    <attribute name="lib" default="@{outputDir}"/>

    <sequential>
      <local name="package.path.modifier"/>
      <loadresource property="package.path.modifier">
        <string value="@{package}" />
        <filterchain>
          <replaceregex pattern="\." replace="/" flags="g" />
        </filterchain>
      </loadresource>

      <local name="fullyQualifierClass.path"/>
      <!--suppress AntResolveInspection -->
      <property name="fullyQualifierClass.path" value="@{outputDir}/${package.path.modifier}"/>

      <mkdir dir="${fullyQualifierClass.path}"/>

      <java jar=".build/antlr-4.4-complete.jar" fork="true">
        <arg value="-o"/>
        <arg value="${fullyQualifierClass.path}"/>
        <arg value="-package"/>
        <arg value="@{package}"/>
        <arg value="-lib"/>
        <arg value="@{lib}"/>
        <arg value="@{grammarFile}"/>
      </java>
    </sequential>
  </macrodef>

  <target name="antlr.babel" description="Rebuilds the code in gen-src with antlr for the problem setup math functions"
          depends="config.clean, init">
    <antlr4 grammarFile="${problem_definition.project.dir}/pre-src/BabelLexer.g4"
            outputDir="${problem_definition.project.dir}/gen-src/"
            package="com.empowerops.problem_definition.parser"/>
    <antlr4 grammarFile="${problem_definition.project.dir}/pre-src/BabelParser.g4"
            outputDir="${problem_definition.project.dir}/gen-src/"
            package="com.empowerops.problem_definition.parser"/>
  </target>
```

Maven has always confused me and so I've avoided it. That seeming more and more like a mistake.

**Comment by Groostav** [comment]
Re:
>:memo: It appears that your generated code is in source control. This should never be the case with ANTLR.

Yeah I debated this when I was adding it. Ultimately, what I wanted was for somebody to be able to clone our repo, open it in intelliJ, and have it run out of the box. Because of the way IntelliJ handles its run configurations, It would've been difficult to have a users repo automagically know to run ANTLR, and even more difficult to have it implement some sort of cache for 'yes I need to run antlr, no I don't need to run ANTLR and I wont to keep build times down'. 

Thus ANTLR is part of our formal build scripts but not part of our "press the run button and our application runs as you've written it" flow.

**Comment by Groostav** [comment]
>Having custom messages seems overkill - once you see the comment "Generated from" then you should know to go find the source file and read the comments there. I suppose though it is trivial to add a search for .a4gencomment, then ~/a4/.a4gencomment and use the text in there if it is present - it could help some.

I would agree except that as java programmers we're trained not to look at the top of a file because of the relative uselessness of import statements. Further, even if that wasn't an issue, I would still really like for somebody that navigated to a generated file to be _forced_ to read this comment, rather than have it sorta off somewhere in the distance.

**Comment by jimidle** [comment]
I would switch to Maven then. It will handle all the grabbing of the
toolset etc for you.

**Comment by Groostav** [comment]
@jimidle :disappointed: Our ant script is about 200 lines of well maintained code, pushing to maven so a comment will be slightly more pretty seems a little much. There are a couple of reasons I'd like to get over to gradle, but I was hoping to wait until java-9 (and its [project Jigsaw](http://openjdk.java.net/projects/jigsaw/)) before I made any sweeping changes to the build system. 

But I agree that it the original problem I was trying to solve would be nicely resolved if you simply used the file-name rather than the full path, such that we get

```Java
//Generated from BabelParser.g4 by ANTLR 4.4
```

**Comment by sharwell** [comment]
@Groostav I'm going to solve all of your problems at once. The following Ant script builds grammars with the following advantages:

1. Automatically downloads the ANTLR Tool if necessary. The download is cached.
2. Only rebuilds generated code if the grammars are newer than the generated code.
3. Generates code in parallel (one thread per package containing grammars).
4. Omits the path from the name of the file in the header.

https://github.com/tunnelvisionlabs/antlrworks2/blob/master/org-antlr-works-editor/build.xml

**Comment by jimidle** [comment]
:)

**Comment by Groostav** [comment]
>@Groostav I'm going to solve all of your problems at once. The following Ant script builds grammars with the following advantages:
> -snip-

Thanks a bunch of this. I'll push it to our repo tonight.

Any takers on making the generated-code comments more visible?

**Comment by parrt** [comment]
One could argue that generated artifacts are typically not added to the revision system though right?

**Comment by parrt** [comment]
Hahah. Yepthat's the reason I often do add things to the repository

**Comment by parrt** [comment]
How about simply putting a new version of the Java.stg file in your class path that is customize the way you want?

**Comment by jimidle** [comment]
Yeah - I said that, but I have had occasion where it is more useful to add
the generated code (though that was the C target).

As you say below thoguh, you can just modify the .stg file, or even just
build a custom version.

Jim

**Comment by Groostav** [comment]
Hey Sam, I started using your antlr4 macro and its giving me the error header. I haven't dug into your targets to figure out your caching system.

Could it be that I'm using the antlr 4.4 complete jar and you're using the two different jars?

And my last point on checking in generated code vs not checking in generated code:
Given that we have a UX-focused developer on our team who is only concerned with FXML files and CSS files, why should he ever need to run ANTLR? (for that matter, why should he ever run javac?) I could build in the tooling to cache the generated code and make sure that any rebuild invokes this logic, but hey, that's doing one of the [two hard things](http://martinfowler.com/bliki/TwoHardThings.html)

**Comment by sharwell** [comment]
@Groostav Did you update the script to point to the correct web address? The address I'm using is a custom build of ANTLR for that project, so the code it generates would be incompatible.
