### ISSUE TITLE
No error in case of token name matches mode name

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#996]
I have the following token name:
```SingleLineComment: '//' -> channel(HIDDEN), pushMode(SingleLineComment);```

And mode ```mode SingleLineComment;```

There is no error when I generate parser with ANTLR (for C# runtime).

But I'am getting an error while compile generated parser because of two equal constants ```SingleLineComment```.

**Comment by KvanTTT** [comment]
@parrt, @sharwell, what is the best way of fixing this issue?
* Add ```MODE_``` prefix to mode constants (as it implemented in parser class with RULE_ prefix). In this case same token and mode names are allowed.
* Dont allow same names and place error to output.

**Comment by sharwell** [comment]
I would go for the second option - not allowing modes and tokens to have the same name.
